"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l20-reveal-${id}`;
  return <div className="pc-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className={visible ? "pc-reveal__panel visible" : "pc-reveal__panel"} hidden={!visible}>{children}</div></div>;
}

function Instruction({ opcode, operand, note }: { opcode: string; operand?: string; note?: string }) {
  return <div className="pc-instruction"><b>{opcode}</b>{operand && <strong>{operand}</strong>}{note && <span>{note}</span>}</div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Language and instruction anatomy", subtitle: "Distinguish representation from meaning", marks: 10,
    questions: [
      { id: "l20-1", marks: 4, lines: 4, prompt: <><b>Explain the relationship between an assembly-language instruction and machine code.</b></>, answer: <p>Assembly uses mnemonic opcodes and readable operands; machine code represents opcode/operand as binary bit patterns; both are processor/instruction-set specific; an assembler translates assembly into machine/object code for execution. <em>[1 each]</em></p> },
      { id: "l20-2", marks: 6, lines: 5, prompt: <><b>For ADD &2A, identify the opcode, operand, number base, destination register, operation and one equivalent denary operand.</b></>, answer: <p>Opcode <b>ADD</b>; operand <b>&2A</b>; hexadecimal; destination <b>ACC</b>; add the literal number to current ACC; hexadecimal 2A is denary <b>42</b>, so an equivalent operand is <b>#42</b>. <em>[1 each]</em></p> },
    ],
  },
  {
    code: "B", title: "Instruction groups", subtitle: "Classify first, then state the effect", marks: 10,
    questions: [
      { id: "l20-3", marks: 5, lines: 4, prompt: <><b>Give the instruction group for each example.</b><p>LDD 200 · IN · SUB #4 · JPN LOOP · CMI 300</p></>, answer: <p><b>Data movement; input/output; arithmetic; unconditional and conditional instructions; compare instructions.</b> <em>[1 each]</em></p> },
      { id: "l20-4", marks: 5, lines: 5, prompt: <><b>State the exact effect of each instruction.</b><p>LDR #3 · MOV IX · INC ACC · CMP #65 · OUT</p></>, answer: <p><b>LDR #3:</b> IX←3. <b>MOV IX:</b> IX←ACC. <b>INC ACC:</b> ACC←ACC+1. <b>CMP #65:</b> compare ACC with 65 and set comparison result/flag. <b>OUT:</b> display the character whose ASCII value is in ACC. <em>[1 each]</em></p> },
    ],
  },
  {
    code: "C", title: "Authentic Paper 1 practice", subtitle: "Three published instruction-group patterns", marks: 10,
    questions: [
      { id: "l20-5", marks: 3, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Using this list, give one valid instruction for each group.</b><p>LDR #n · STO address · ADD address · INC register · JPE address · OUT</p><p>Groups: data movement; arithmetic; conditional. Adapted from 9618/11 O/N 2023 Q8(b)(i). [3]</p></>, answer: <p>Examples: <b>LDR #50</b> or <b>STO 201</b>; <b>ADD 100</b> or <b>INC IX</b>; <b>JPE 96</b>. Operand must be suitable. <em>[1 each]</em></p> },
      { id: "l20-6", marks: 3, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Name the groups containing: loading into ACC; incrementing IX; branching to another address.</b><p>Adapted from 9618/13 O/N 2025 Q6(c). [3]</p></>, answer: <p><b>Data movement; arithmetic operations; conditional and unconditional (jump) instructions.</b> <em>[1 each]</em></p> },
      { id: "l20-7", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Give one valid instruction for each remaining group.</b><p>Input/output · arithmetic · jump · compare. Adapted from 9618/12 O/N 2021 Q8(b)(ii). [4]</p></>, answer: <p>Examples: <b>IN</b> or <b>OUT</b>; <b>INC ACC</b>; <b>JPN 120</b> or <b>JMP 120</b>; <b>CMP 100</b>. <em>[1 each; alternatives from the syllabus set valid]</em></p> },
    ],
  },
];

export default function Lesson20Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "3 min", focus: "Introduce assembly as a readable representation of instructions the processor can execute after translation.", prompt: "Ask which form a human would rather debug: a mnemonic or a bit pattern?", source: "Syllabus 4.2 pp.20-21; Coursebook 6.01-6.02, printed pp.91-93 / PDF pp.98-100.", content: <Slide number="01" eyebrow="CHAPTER 4 · ASSEMBLY LANGUAGE" sourceLabel="TEXTBOOK CH.6 · pp.91-100" syllabusLabel="SYLLABUS 4.2 · pp.20-21" className="slide--pc-title"><section className="pc-title-grid"><div><span>LESSON 20 · 90 MINUTES</span><h1>Readable command.<br /><em>Executable bits.</em></h1><p>Decode opcode and operand, then organise the current instruction set by purpose.</p></div><div className="pc-assembly-hero"><Instruction opcode="LDM" operand="#65" /><i>ASSEMBLER ↓</i><Instruction opcode="00100001" operand="01000001" /></div></section></Slide> },
    { time: "4 min", focus: "Define the lesson boundary: foundations and groups now; addressing, assembly process and tracing later.", prompt: "Students name the three later skills shown in the footer.", source: "Syllabus 4.2 p.20 and instruction set p.21.", content: <Slide number="02" eyebrow="TODAY'S SYLLABUS ROUTE" sourceLabel="OFFICIAL SYLLABUS · pp.20-21" syllabusLabel="SYLLABUS 4.2" title="Relate → read → group → execute one step." className="slide--pc-route"><section className="pc-route-grid"><article><b>1</b><span>RELATION</span><p>assembly ↔ machine</p></article><article><b>2</b><span>ANATOMY</span><p>opcode + operand</p></article><article><b>3</b><span>GROUPS</span><p>five instruction purposes</p></article></section><p className="pc-note"><b>Next:</b> addressing modes · two-pass assembler · full program tracing.</p></Slide> },
    { time: "6 min", focus: "Explain what the assembler changes and what semantic instruction remains.", prompt: "Which parts are easier for a human, and which can the CPU execute directly?", source: "Coursebook 6.01-6.02, printed pp.92-93 / PDF pp.99-100; Syllabus 4.2 p.20.", content: <Slide number="03" eyebrow="ASSEMBLY AND MACHINE CODE" sourceLabel="TEXTBOOK 6.01-6.02 · pp.92-93" syllabusLabel="SYLLABUS 4.2" title="The same instruction is represented in two languages." className="slide--pc-translate"><section><div><b>ASSEMBLY</b><Instruction opcode="ADD" operand="#5" note="mnemonic + readable operand" /></div><i>assembler</i><div><b>MACHINE CODE</b><Instruction opcode="0110 0010" operand="0000 0101" note="binary opcode + operand field" /></div></section><p className="pc-takeaway">Both forms are tied to a particular processor instruction set.</p></Slide> },
    { time: "6 min", focus: "Teach opcode and operand as functional parts, not merely first and second tokens.", prompt: "What is the operation? What value/address/register does it use?", source: "Coursebook 6.01 and 6.06, printed pp.92,98 / PDF pp.99,105.", content: <Slide number="04" eyebrow="INSTRUCTION ANATOMY" sourceLabel="TEXTBOOK pp.92,98" syllabusLabel="SYLLABUS 4.2" title="Opcode says what; operand says with what." className="slide--pc-anatomy"><Instruction opcode="SUB" operand="TOTAL" /><section className="pc-anatomy-labels"><p><b>OPCODE</b>subtract</p><p><b>OPERAND</b>symbolic memory address</p></section><p className="pc-note">Some instructions, such as IN, OUT and END, have no operand.</p></Slide> },
    { time: "6 min", focus: "Decode the current syllabus literal notation and address placeholders.", prompt: "Write the same value 74 using all three immediate number forms.", source: "Official syllabus instruction-set notes p.21.", content: <Slide number="05" eyebrow="READ THE OPERAND" sourceLabel="OFFICIAL INSTRUCTION SET · p.21" syllabusLabel="SYLLABUS 4.2" title="# is denary; B is binary; & is hexadecimal." className="slide--pc-operands"><section className="pc-literal-grid"><Instruction opcode="LDM" operand="#74" note="denary" /><Instruction opcode="ADD" operand="B01001010" note="binary" /><Instruction opcode="SUB" operand="&4A" note="hexadecimal" /><Instruction opcode="LDD" operand="TOTAL" note="symbolic address" /></section><p className="pc-caution"><b>SYNTAX</b> Do not write #B01001010 or #&4A. The current p.21 notation is #n / Bn / &n.</p></Slide> },
    { time: "6 min", focus: "Survey every data-movement instruction in the current syllabus without yet reteaching addressing modes.", prompt: "For each instruction, name the destination register or memory.", source: "Official syllabus instruction set p.21; Coursebook Table 6.07, printed p.98 / PDF p.105.", content: <Slide number="06" eyebrow="GROUP 1 · DATA MOVEMENT" sourceLabel="TEXTBOOK TABLE 6.07 · p.98" syllabusLabel="SYLLABUS 4.2 · p.21" title="Load into ACC or IX; move between registers; store from ACC." className="slide--pc-instruction-group"><section className="pc-opcode-grid seven"><Instruction opcode="LDM" operand="#n" /><Instruction opcode="LDD" operand="address" /><Instruction opcode="LDI" operand="address" /><Instruction opcode="LDX" operand="address" /><Instruction opcode="LDR" operand="#n" /><Instruction opcode="MOV" operand="IX" /><Instruction opcode="STO" operand="address" /></section><p className="pc-note">ACC is the destination for LDM/LDD/LDI/LDX; LDR and MOV target IX; STO writes ACC to memory.</p></Slide> },
    { time: "6 min", focus: "Tie IN and OUT to ASCII, avoiding the misconception that OUT prints the number itself.", prompt: "If ACC=65, what does OUT display? What does IN do when A is typed?", source: "Official syllabus instruction set p.21; Coursebook 6.06, printed p.99 / PDF p.106.", content: <Slide number="07" eyebrow="GROUP 2 · INPUT AND OUTPUT" sourceLabel="TEXTBOOK 6.06 · p.99" syllabusLabel="SYLLABUS 4.2 · p.21" title="Characters cross the boundary as ASCII values." className="slide--pc-io"><section className="pc-ascii-flow"><div><b>KEYBOARD</b><span>A</span></div><Instruction opcode="IN" note="ACC ← 65" /><div><b>ACC</b><span>65</span></div><Instruction opcode="OUT" note="display A" /><div><b>SCREEN</b><span>A</span></div></section><p className="pc-note">IN, OUT and END have an opcode but no operand.</p></Slide> },
    { time: "6 min", focus: "Cover both address and immediate forms of arithmetic instructions.", prompt: "Which instructions change ACC? Which can also change IX?", source: "Official syllabus instruction set p.21; Coursebook Table 6.09, printed p.100 / PDF p.107.", content: <Slide number="08" eyebrow="GROUP 3 · ARITHMETIC" sourceLabel="TEXTBOOK TABLE 6.09 · p.100" syllabusLabel="SYLLABUS 4.2 · p.21" title="ADD and SUB use memory or literals; INC and DEC use a register." className="slide--pc-instruction-group"><section className="pc-opcode-grid"><Instruction opcode="ADD" operand="address" /><Instruction opcode="ADD" operand="#n / Bn / &n" /><Instruction opcode="SUB" operand="address" /><Instruction opcode="SUB" operand="#n / Bn / &n" /><Instruction opcode="INC" operand="ACC / IX" /><Instruction opcode="DEC" operand="ACC / IX" /></section><p className="pc-takeaway">Unless a register is named, arithmetic in this model updates ACC.</p></Slide> },
    { time: "6 min", focus: "Teach compare instructions as flag-setting operations that preserve ACC.", prompt: "What changes after CMP #10 if ACC already contains 10?", source: "Official syllabus instruction set p.21; Coursebook Table 6.08, printed p.100 / PDF p.107.", content: <Slide number="09" eyebrow="GROUP 5 · COMPARE" sourceLabel="TEXTBOOK TABLE 6.08 · p.100" syllabusLabel="SYLLABUS 4.2 · p.21" title="Compare sets a result for the next conditional jump." className="slide--pc-compare"><section className="pc-compare-flow"><Instruction opcode="CMP" operand="address" /><Instruction opcode="CMP" operand="#n" /><Instruction opcode="CMI" operand="address" /></section><div className="pc-caution"><b>ACC IS NOT CHANGED</b><p>CMP/CMI compare values and record whether the comparison is True or False.</p></div></Slide> },
    { time: "6 min", focus: "Distinguish unconditional and conditional changes to PC.", prompt: "Which jump always happens? What must immediately precede JPE/JPN?", source: "Official syllabus instruction set p.21; Coursebook Table 6.08, printed p.100 / PDF p.107.", content: <Slide number="10" eyebrow="GROUP 4 · JUMP INSTRUCTIONS" sourceLabel="TEXTBOOK TABLE 6.08 · p.100" syllabusLabel="SYLLABUS 4.2 · p.21" title="A jump replaces the next sequential address." className="slide--pc-jumps"><section className="pc-jump-grid"><article><Instruction opcode="JMP" operand="address" /><p>always jump</p></article><article><Instruction opcode="JPE" operand="address" /><p>jump if compare was True</p></article><article><Instruction opcode="JPN" operand="address" /><p>jump if compare was False</p></article></section><p className="pc-note">JPE/JPN test the result of the preceding comparison—not greater-than or less-than.</p></Slide> },
    { time: "6 min", focus: "Complete the current p.21 set and introduce labels without teaching the two-pass process early.", prompt: "What changes in control flow when END executes?", source: "Official syllabus instruction set pp.21-22; Coursebook 6.03 and 6.06, printed pp.94,100 / PDF pp.101,107.", content: <Slide number="11" eyebrow="PROGRAM STRUCTURE" sourceLabel="TEXTBOOK pp.94,100" syllabusLabel="SYLLABUS 4.2 · pp.21-22" title="Labels name addresses; END returns control to the OS." className="slide--pc-program"><section className="pc-code-block"><code><b>LOOP:</b> IN<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CMP #88<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JPN LOOP<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;END</code></section><section className="pc-program-notes"><p><b>LOOP:</b> symbolic address</p><p><b>END</b> stop this program; return to OS</p></section></Slide> },
    { time: "7 min", focus: "Retrieve the five syllabus group names and classify representative instructions.", prompt: "Students move each opcode to one group, then justify the ambiguous-looking item CMP.", source: "Syllabus 4.2 p.20; current instruction set p.21.", content: <Slide number="12" eyebrow="GROUP SORT" sourceLabel="OFFICIAL SYLLABUS · pp.20-21" syllabusLabel="SYLLABUS 4.2" title="Five purposes organise the instruction set." className="slide--pc-groups"><section className="pc-group-grid"><article><b>DATA MOVEMENT</b><span>LDD · STO · MOV</span></article><article><b>INPUT / OUTPUT</b><span>IN · OUT</span></article><article><b>ARITHMETIC</b><span>ADD · SUB · INC</span></article><article><b>JUMPS</b><span>JMP · JPE · JPN</span></article><article><b>COMPARE</b><span>CMP · CMI</span></article></section><p className="pc-note">Bitwise operations and shifts belong to syllabus 4.3 and return in Lesson 24.</p></Slide> },
    { time: "8 min", focus: "Use a current Paper 1 item that assesses exact group names.", prompt: "Students answer before seeing the instruction examples from earlier slides.", source: "Adapted from 9618/13 O/N 2025 Q6(c), checked against published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 3 MARKS" sourceLabel="9618/13 O/N 2025 · Q6(c)" syllabusLabel="SYLLABUS 4.2 — EXAM PRACTICE" title="Name the group for each action." className="slide--pc-paper"><section className="pc-paper-list"><p><b>1</b>Load data into ACC.</p><p><b>2</b>Increment IX.</p><p><b>3</b>Branch to another address.</p></section><Reveal id="paper-groups" visible={revealed.has("paper-groups")} onToggle={toggleReveal}><p><b>1 Data movement.</b> <b>2 Arithmetic operations.</b> <b>3 Conditional and unconditional (jump) instructions.</b></p></Reveal><small>Adapted from 9618/13 O/N 2025 Q6(c).</small></Slide> },
    { time: "10 min", focus: "Combine group recognition with valid opcode-and-operand construction.", prompt: "Six minutes individual; insist that each operand is valid for its opcode.", source: "Adapted from 9618/11 O/N 2023 Q8(b)(i), checked against published mark scheme.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE · 6 MARKS" sourceLabel="9618/11 O/N 2023 · Q8(b)(i)" syllabusLabel="SYLLABUS 4.2 — EXAM PRACTICE" title="Choose a valid instruction—and state its effect." className="slide--pc-paper"><section className="pc-paper-split"><p><b>DATA MOVEMENT</b>LDR #n or STO address</p><p><b>ARITHMETIC</b>ADD address or INC register</p><p><b>CONDITIONAL</b>JPE address</p><p><b>ADD 1 MARK EACH</b>for three precise effects</p></section><Reveal id="paper-instructions" visible={revealed.has("paper-instructions")} onToggle={toggleReveal}><p>Example: <b>LDR #50</b> loads 50 into IX; <b>ADD 100</b> adds memory[100] to ACC; <b>JPE 96</b> jumps to address 96 when the previous compare was True.</p></Reveal><small>Instruction-selection task adapted from 9618/11 O/N 2023 Q8(b)(i); effect prompts added for consolidation.</small></Slide> },
    { time: "4 min", focus: "Close by retrieving the five groups and previewing addressing modes.", prompt: "Students say one valid opcode from each group without looking back.", source: "Lesson 20 synthesis; Syllabus 4.2 pp.20-21.", content: <Slide number="15" eyebrow="EXIT · FIVE GROUPS" sourceLabel="LESSON 20 SYNTHESIS" syllabusLabel="SYLLABUS 4.2" title="Move. Input/output. Calculate. Jump. Compare." className="slide--pc-exit"><section className="pc-exit-copy"><b>MOVE</b><i>·</i><b>I/O</b><i>·</i><b>ARITHMETIC</b><i>·</i><b>JUMP</b><i>·</i><b>COMPARE</b></section><div className="pc-homework-callout"><b>HOMEWORK 20</b><span>30 marks · 45 minutes · inline mark schemes</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="20" slides={slides} homework={<HomeworkSheet lessonNumber="20" title="Assembly Foundations and Instruction Groups" marks={30} minutes={45} syllabusLabel="SYLLABUS 4.2 · pp.20-21" sourceLabel="TEXTBOOK CH.6 · PRINTED pp.91-100 / PDF pp.98-107 + PAPER 1" instructions="Use only the current syllabus instruction set and write a syntactically valid operand. For each effect, name the source and destination or explain the control-flow change. Past-paper prompts are concise adaptations with original references." sections={homeworkSections} challenge={{ id: "l20-challenge", prompt: <p><Mark>CHALLENGE</Mark> ACC contains 65. Explain the different effects of OUT, ADD #1 and MOV IX without tracing a full program.</p>, answer: <p><b>OUT</b> displays the ASCII character A and leaves ACC unchanged. <b>ADD #1</b> changes ACC to 66. <b>MOV IX</b> copies 65 from ACC into IX and leaves ACC unchanged.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 4.2 pp.20-21, Coursebook Chapter 6 printed pp.91-100 (PDF pp.98-107), and published 2021/2023/2025 Paper 1 questions and mark schemes." sourceDetail="Core: relationship between assembly language and machine code; opcode, operand, literal and label conventions; the five named instruction groups; every non-bitwise instruction in the current p.21 set. Authentic anchors: 9618/13 O/N 2025 Q6(c), 9618/11 O/N 2023 Q8(b)(i), and 9618/12 O/N 2021 Q8(b)(ii). Addressing-mode calculations, two-pass assembly and full tracing are intentionally reserved for Lessons 21-23." />;
}
