"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l22-reveal-${id}`;
  return <div className="asm-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className="asm-reveal__panel" hidden={!visible}>{children}</div></div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Pass responsibilities", subtitle: "Assign each action to the correct pass", marks: 10,
    questions: [
      { id: "l22-1", marks: 6, lines: 5, prompt: <><b>State whether each action occurs in pass 1, pass 2 or both.</b><p>Read the source one line at a time; remove comments/whitespace; validate opcodes; add labels to the symbol table; substitute label addresses; generate object code.</p></>, answer: <p><b>Both; pass 1; pass 1; pass 1; pass 2; pass 2.</b> <em>[1 each]</em></p> },
      { id: "l22-2", marks: 4, lines: 4, prompt: <><b>Explain why two passes are needed when a program contains a forward reference.</b></>, answer: <p>A forward reference uses a label before its definition has been scanned. Pass 1 reads the whole source and records each label with its address in a symbol table. Pass 2 can then look up the earlier reference, substitute the address and generate object/machine code. <em>[4 linked points]</em></p> },
    ],
  },
  {
    code: "B", title: "Authentic Paper 1 practice", subtitle: "Three independently verified assembler questions", marks: 10,
    questions: [
      { id: "l22-3", marks: 3, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Match four actions to first pass, second pass or both:</b><p>generate object code; read source line by line; remove whitespace; add labels to the symbol table. Adapted from 9618/12 M/J 2023 Q3(a). [3]</p></>, answer: <p>Generate object code → <b>second</b>. Read source line by line → <b>both</b>. Remove whitespace and add labels to the symbol table → <b>first</b>. The published scheme awards the final mark only when both of those last actions are linked to pass 1. <em>[3]</em></p> },
      { id: "l22-4", marks: 2, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Classify four tasks by assembler pass:</b><p>remove comments; read the assembly program line by line; generate object code; check that an opcode is in the instruction set. Adapted from 9618/11 O/N 2022 Q6(c). [2]</p></>, answer: <p><b>Remove comments—first; read line by line—both; generate object code—second; check opcode—first.</b> <em>[2: one mark for each correct pair of rows in the original table]</em></p> },
      { id: "l22-5", marks: 1, lines: 2, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Identify the purpose of the first pass of a two-pass assembler.</b><p>Adapted from 9618/11 O/N 2023 Q8(a). [1]</p></>, answer: <p>To <strong>create a symbol table</strong>. <em>[1]</em></p> },
      { id: "l22-6", marks: 4, lines: 4, prompt: <><b>Pass 1 assigns addresses 0–5 to five instructions followed by one data item.</b><p>The labels are LOOP on instruction address 1 and TOTAL on data address 5. Write the two symbol-table entries and state what happens to <span className="asm-code">JMP LOOP</span> and <span className="asm-code">STO TOTAL</span> in pass 2.</p></>, answer: <p>Symbol table: <b>LOOP → 1; TOTAL → 5</b>. In pass 2, the label operands are replaced with their addresses: <span className="asm-code">JMP 1</span> and <span className="asm-code">STO 5</span>, before object code is generated. <em>[1 each entry; 1 each substitution]</em></p> },
    ],
  },
  {
    code: "C", title: "Apply both passes", subtitle: "Build a symbol table, resolve labels and describe output", marks: 10,
    questions: [
      { id: "l22-7", marks: 10, lines: 5, prompt: <><b>Apply a two-pass assembler to this source, starting at address 0:</b><pre className="asm-program">      LDM #3{"\n"}      STO COUNT{"\n"}LOOP: LDD COUNT{"\n"}      DEC ACC{"\n"}      STO COUNT{"\n"}      JPN LOOP{"\n"}      END{"\n"}COUNT: 0</pre><p>(a) Assign addresses. [2] (b) Give the symbol table. [2] (c) Identify every forward reference. [2] (d) Give all label substitutions made in pass 2. [3] (e) State the pass-2 output. [1]</p></>, answer: <p><b>(a)</b> Lines occupy addresses 0–7 in order. <b>(b)</b> LOOP=2; COUNT=7. <b>(c)</b> COUNT is a forward reference in <span className="asm-code">STO COUNT</span>, <span className="asm-code">LDD COUNT</span> and the later <span className="asm-code">STO COUNT</span>; credit identifying COUNT and its use before definition. LOOP in JPN is a backward reference. <b>(d)</b> STO 7; LDD 7; STO 7; JPN 2. <b>(e)</b> Object/machine code. <em>[10]</em></p> },
    ],
  },
];

export default function Lesson22Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "3 min", focus: "Introduce labels as the reason a simple assembler needs two scans.", prompt: "Ask how JMP LOOP can be encoded before LOOP's address is known.", source: "Syllabus 4.2 p.20; Coursebook Chapter 6 printed pp.95-97.", content: <Slide number="01" eyebrow="CHAPTER 4 · TRANSLATION" sourceLabel="TEXTBOOK CH.6 · pp.95-97" syllabusLabel="SYLLABUS 4.2 · p.20" className="slide--asm-title"><section className="asm-title-grid"><div className="asm-title-copy"><span>LESSON 22 · 90 MINUTES</span><h1>Scan twice.<br /><em>Resolve once.</em></h1><p>A two-pass assembler discovers every label before it generates the final object code.</p></div><div className="asm-chip-stack"><p><b>PASS 1</b><span>build the symbol table</span></p><p><b>PASS 2</b><span>replace labels with addresses</span></p><p><b>OUTPUT</b><span>object / machine code</span></p></div></section></Slide> },
    { time: "4 min", focus: "Set the syllabus boundary: describe and apply both passes.", prompt: "Students name the artifact carried from pass 1 to pass 2.", source: "Syllabus 4.2 p.20.", content: <Slide number="02" eyebrow="TODAY'S ROUTE" sourceLabel="SYLLABUS 4.2" syllabusLabel="SYLLABUS 4.2 — TWO-PASS" title="Source → symbol table → resolved instructions → object code."><section className="asm-route"><article><b>READ</b><p>every source line</p></article><article><b>RECORD</b><p>labels and addresses</p></article><article><b>RESOLVE</b><p>replace label operands</p></article><article><b>GENERATE</b><p>object code</p></article></section></Slide> },
    { time: "5 min", focus: "Connect assembly mnemonics to machine code and the role of assembler software.", prompt: "Students distinguish translation from execution.", source: "Coursebook 6.01-6.04 pp.92-97; syllabus 4.2.", content: <Slide number="03" eyebrow="WHY AN ASSEMBLER?" sourceLabel="TEXTBOOK 6.01-6.04" syllabusLabel="SYLLABUS 4.2" title="The CPU recognises machine code; programmers use mnemonics and labels."><section className="asm-memory-chain"><article><span>SOURCE</span><b>ADD TOTAL</b></article><i>→</i><article><span>ASSEMBLER</span><b>translate</b></article><i>→</i><article><span>OBJECT CODE</span><b>opcode + address</b></article></section><p className="asm-note">Assembly instructions usually map closely to machine instructions, but symbolic labels must first become numeric addresses.</p></Slide> },
    { time: "6 min", focus: "Show the complete two-pass workflow before zooming into each pass.", prompt: "Students point to where a forward reference becomes resolvable.", source: "Coursebook two-pass assembler pp.95-97.", content: <Slide number="04" eyebrow="THE WHOLE PROCESS" sourceLabel="TEXTBOOK pp.95-97" syllabusLabel="SYLLABUS 4.2" title="Both passes read the source; they produce different things."><section className="asm-pass-grid"><article className="asm-pass"><span>PASS 1</span><h3>discover structure</h3><ol><li>scan line by line</li><li>clean/check source</li><li>assign addresses</li><li>create symbol table</li></ol></article><i>→</i><article className="asm-pass"><span>PASS 2</span><h3>produce translation</h3><ol><li>scan line by line again</li><li>look up opcode</li><li>substitute label addresses</li><li>generate object code</li></ol></article></section></Slide> },
    { time: "7 min", focus: "Teach first-pass source cleaning and validation.", prompt: "Classify comments, whitespace and opcode checking.", source: "Coursebook p.96; 9618/11 O/N 2022 Q6(c) mark scheme.", content: <Slide number="05" eyebrow="PASS 1 · PREPARE" sourceLabel="TEXTBOOK p.96 + PAPER 1" syllabusLabel="SYLLABUS 4.2 — FIRST PASS" title="Read each line; remove non-code; check what can be checked."><section className="asm-card-grid"><article className="asm-card"><span>CLEAN</span><h3>comments</h3><p>Remove explanatory text that is not translated.</p></article><article className="asm-card"><span>CLEAN</span><h3>whitespace</h3><p>Normalise spacing that does not affect meaning.</p></article><article className="asm-card"><span>VALIDATE</span><h3>opcode</h3><p>Check the mnemonic exists in the instruction set.</p></article></section></Slide> },
    { time: "7 min", focus: "Build the symbol table by assigning each label its address.", prompt: "Students calculate LOOP and TOTAL from the displayed source.", source: "Coursebook p.96; syllabus application requirement.", content: <Slide number="06" eyebrow="PASS 1 · SYMBOL TABLE" sourceLabel="TEXTBOOK p.96" syllabusLabel="SYLLABUS 4.2 — FIRST PASS" title="A symbol table maps each label to one address."><section className="asm-card-grid two"><pre className="asm-program">0  LDM #3{"\n"}1  STO TOTAL{"\n"}2  LOOP: DEC ACC{"\n"}3  JPN LOOP{"\n"}4  STO TOTAL{"\n"}5  END{"\n"}6  TOTAL: 0</pre><div className="asm-symbol-table"><b>LABEL</b><b>ADDRESS</b><code>LOOP</code><span>2</span><code>TOTAL</code><span>6</span></div></section></Slide> },
    { time: "6 min", focus: "Define a forward reference and show why one pass cannot resolve it immediately.", prompt: "Students circle all references that appear before their label definitions.", source: "Coursebook two-pass rationale pp.95-96.", content: <Slide number="07" eyebrow="FORWARD REFERENCES" sourceLabel="TEXTBOOK pp.95-96" syllabusLabel="SYLLABUS 4.2" title="The label is used before its address has been discovered."><section className="asm-memory-chain"><article><span>ADDRESS 1</span><b>STO TOTAL</b></article><i>?</i><article><span>SCAN CONTINUES</span><b>...</b></article><i>→</i><article><span>ADDRESS 6</span><b>TOTAL: 0</b></article></section><p className="asm-note">Pass 1 records TOTAL=6. Pass 2 can then return to the earlier instruction and substitute 6.</p></Slide> },
    { time: "7 min", focus: "Teach second-pass substitution and object-code generation.", prompt: "Students replace every label in the sample source.", source: "Coursebook pp.96-97.", content: <Slide number="08" eyebrow="PASS 2 · RESOLVE AND GENERATE" sourceLabel="TEXTBOOK pp.96-97" syllabusLabel="SYLLABUS 4.2 — SECOND PASS" title="Use both lookup tables: opcode table and symbol table."><section className="asm-equation"><b>STO TOTAL</b><i>+</i><b>TOTAL → 6</b><i>→</i><strong>STO 6 → object code</strong></section><p className="asm-note">The opcode mnemonic is replaced by its binary opcode; a symbolic operand is replaced by its numeric address.</p></Slide> },
    { time: "6 min", focus: "Contrast pass responsibilities explicitly.", prompt: "Students explain why 'read line by line' belongs to both columns.", source: "Coursebook pp.95-97; published mark schemes.", content: <Slide number="09" eyebrow="PASS 1 vs PASS 2" sourceLabel="TEXTBOOK + MARK SCHEMES" syllabusLabel="SYLLABUS 4.2" title="Do not attach every task to only one pass."><div className="asm-table-wrap"><table><thead><tr><th>Action</th><th>Pass 1</th><th>Pass 2</th></tr></thead><tbody><tr><td>read source line by line</td><td className="changed">✓</td><td className="changed">✓</td></tr><tr><td>remove comments / whitespace</td><td className="changed">✓</td><td>—</td></tr><tr><td>build symbol table</td><td className="changed">✓</td><td>—</td></tr><tr><td>replace labels / generate object code</td><td>—</td><td className="changed">✓</td></tr></tbody></table></div></Slide> },
    { time: "8 min", focus: "Apply both passes to a compact program with forward and backward references.", prompt: "Pairs assign addresses, build the table, then resolve operands.", source: "Coursebook worked process pp.95-97.", content: <Slide number="10" eyebrow="WORKED APPLICATION" sourceLabel="TEXTBOOK pp.95-97" syllabusLabel="SYLLABUS 4.2 — APPLY" title="One source; two different readings."><section className="asm-card-grid two"><pre className="asm-program">0  LDM #2{"\n"}1  STO COUNT{"\n"}2  LOOP: DEC ACC{"\n"}3  STO COUNT{"\n"}4  JPN LOOP{"\n"}5  END{"\n"}6  COUNT: 0</pre><article className="asm-card"><span>PASS RESULTS</span><h3>LOOP=2 · COUNT=6</h3><p>Pass 2 produces STO 6 at addresses 1 and 3, and JPN 2 at address 4.</p></article></section></Slide> },
    { time: "7 min", focus: "Use the exact marking logic of a recent two-pass question.", prompt: "Four minutes individual, then reveal; note the paired final mark.", source: "Adapted from 9618/12 M/J 2023 Q3(a), checked against published mark scheme.", content: <Slide number="11" eyebrow="PAST PAPER PRACTICE · 3 MARKS" sourceLabel="9618/12 M/J 2023 · Q3(a)" syllabusLabel="SYLLABUS 4.2 — EXAM" className="asm-paper" title="Connect each action to first, second or both passes."><section className="asm-paper-grid"><article><b>generate object code</b><p>first / second / both?</p></article><article><b>read source line by line</b><p>first / second / both?</p></article><article><b>remove whitespace</b><p>first / second / both?</p></article><article><b>add labels to symbol table</b><p>first / second / both?</p></article></section><Reveal id="mj23" visible={revealed.has("mj23")} onToggle={toggleReveal}><p><b>Second; both; first; first.</b> The mark scheme groups the final two correct first-pass links for one mark.</p></Reveal><small>Adapted from 9618/12 M/J 2023 Q3(a).</small></Slide> },
    { time: "5 min", focus: "Repair misconceptions about symbol tables and output.", prompt: "Students correct all three statements.", source: "Syllabus and recurring Paper 1 errors.", content: <Slide number="12" eyebrow="MISCONCEPTION CLINIC" sourceLabel="EXAMINER LANGUAGE" syllabusLabel="SYLLABUS 4.2" title="Reject three tempting shortcuts."><section className="asm-card-grid"><article className="asm-card"><span>FALSE</span><h3>Pass 1 executes code</h3><p>It analyses source; it does not run it.</p></article><article className="asm-card"><span>FALSE</span><h3>Labels use memory</h3><p>A label names an address; it is not extra data.</p></article><article className="asm-card"><span>FALSE</span><h3>Pass 2 builds labels</h3><p>It uses the table built in pass 1.</p></article></section></Slide> },
    { time: "6 min", focus: "Use a verified table question to distinguish both passes.", prompt: "Students tick the four rows before revealing.", source: "Adapted from 9618/11 O/N 2022 Q6(c).", content: <Slide number="13" eyebrow="PAST PAPER CHECK · 2 MARKS" sourceLabel="9618/11 O/N 2022 · Q6(c)" syllabusLabel="SYLLABUS 4.2 — EXAM" className="asm-paper" title="Which pass removes, reads, generates and checks?"><section className="asm-paper-grid"><p>remove comments · read line by line</p><p>generate object code · check opcode</p></section><Reveal id="on22" visible={revealed.has("on22")} onToggle={toggleReveal}><p>Remove comments—<b>first</b>; read line by line—<b>both</b>; generate object code—<b>second</b>; check opcode—<b>first</b>.</p></Reveal><small>Adapted from 9618/11 O/N 2022 Q6(c).</small></Slide> },
    { time: "8 min", focus: "Complete a timed mini-assembly process from source to resolved instructions.", prompt: "Five minutes work, then three minutes self-mark.", source: "Syllabus-style application plus 9618/11 O/N 2023 Q8(a).", content: <Slide number="14" eyebrow="EXAM SPRINT · 6 MARKS" sourceLabel="9618/11 O/N 2023 · Q8(a) + ORIGINAL" syllabusLabel="SYLLABUS 4.2 — APPLY" className="asm-paper" title="Build, resolve, explain."><section className="asm-paper-grid three"><article><b>1 mark</b><p>Purpose of pass 1?</p></article><article><b>2 marks</b><p>LOOP at 12; DATA at 18. Give both entries.</p></article><article><b>3 marks</b><p>Explain how JMP LOOP and STO DATA become object code.</p></article></section><Reveal id="sprint" visible={revealed.has("sprint")} onToggle={toggleReveal}><p>Create the symbol table. Entries: LOOP→12 and DATA→18. In pass 2, look up each label, substitute 12/18, look up each opcode and generate the corresponding machine/object code.</p></Reveal><small>Part 1 adapted from 9618/11 O/N 2023 Q8(a); remaining items are syllabus-style originals.</small></Slide> },
    { time: "5 min", focus: "Close with the invariant carried between passes.", prompt: "Students complete: pass 1 knows __; pass 2 produces __.", source: "Syllabus 4.2 exit check.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK CH.6 · REVIEW" syllabusLabel="SYLLABUS 4.2" className="slide--asm-exit" title="Pass 1 discovers. Pass 2 translates."><section className="asm-exit-grid"><article><b>PASS 1</b><p>symbol table</p></article><article><b>BRIDGE</b><p>label → address</p></article><article><b>PASS 2</b><p>object code</p></article></section><div className="asm-homework-callout"><b>HOMEWORK 22</b><span>30 marks · three verified Paper 1 anchors · inline answers</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="22" slides={slides} homework={<HomeworkSheet lessonNumber="22" title="The Two-Pass Assembler" marks={30} minutes={45} syllabusLabel="SYLLABUS 4.2 · p.20" sourceLabel="TEXTBOOK CH.6 · pp.95-97 + PAPER 1" instructions="Name the pass for every action. When applying the process, assign addresses, create the symbol table and show label substitutions before stating that object code is generated. Adapted past-paper tasks retain their original references and marks." sections={homeworkSections} challenge={{ id: "l22-challenge", prompt: <p><Mark>CHALLENGE</Mark> A label is defined twice. Explain why this must be reported as an assembler error.</p>, answer: <p>A symbol table requires one unambiguous address for each label. Two definitions would give the same symbolic operand two possible targets, so the assembler cannot substitute a unique address safely.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 4.2 p.20, Coursebook Chapter 6 printed pp.95-97, and published 2022-2023 Paper 1 questions and mark schemes." sourceDetail="Core: relationship between assembly and machine code; first-pass source checking and symbol-table construction; forward references; second-pass label substitution and object-code generation. Authentic anchors: 9618/12 M/J 2023 Q3(a), 9618/11 O/N 2022 Q6(c), and 9618/11 O/N 2023 Q8(a). Every past-paper prompt is marked Adapted." />;
}
