"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Byte parity", subtitle: "Calculate, detect and state the limit", marks: 10,
    questions: [
      { id: "l32-1", marks: 2, lines: 2, prompt: <><b>State the rule for an even parity bit and for an odd parity bit.</b></>, answer: <p><strong>Even parity:</strong> choose the parity bit so the complete transmitted unit contains an even number of 1s. <strong>Odd parity:</strong> choose it so the complete unit contains an odd number of 1s. <em>[1 each]</em></p> },
      { id: "l32-2", marks: 4, lines: 3, prompt: <><b>Add the required parity bit at the right of each seven-bit item.</b><p>(i) 1011010 using even parity &nbsp; (ii) 1100100 using odd parity</p><p>(iii) 0000000 using even parity &nbsp; (iv) 1111111 using odd parity</p></>, answer: <p>(i) has four 1s → <strong>0</strong>; (ii) has three 1s and odd is required → <strong>0</strong>; (iii) has zero 1s, already even → <strong>0</strong>; (iv) has seven 1s, already odd → <strong>0</strong>. <em>[1 each]</em></p> },
      { id: "l32-3", marks: 4, lines: 4, prompt: <><b>Explain why a single parity bit detects any one-bit change but can fail to detect two changed bits.</b></>, answer: <p>One flipped bit changes the number of 1s by one, so even becomes odd or odd becomes even and the recalculated parity fails. Two flips may change the count by zero or two, preserving the expected parity, so the error can pass undetected. Parity detects an odd number of bit changes, not every error. <em>[4]</em></p> },
    ],
  },
  {
    code: "B", title: "Blocks and checksums", subtitle: "Locate an intersection; compare a recalculated total", marks: 10,
    questions: [
      { id: "l32-4", marks: 4, lines: 4, prompt: <><b>In an even-parity block, row 3 fails and column 2 fails; all other rows/columns pass.</b><p>Identify the most likely erroneous bit and explain the evidence.</p></>, answer: <p>The likely error is at the <strong>intersection of row 3 and column 2</strong>. That changed bit makes both its row and its column contain the wrong parity while the others remain correct. Under the single-bit-error assumption, flipping that bit restores both checks. <em>[location + three linked points]</em></p> },
      { id: "l32-5", marks: 4, lines: 4, prompt: <><b>A stated checksum algorithm adds byte values and takes the remainder modulo 256.</b><p>Calculate the checksum for 100, 55 and 240. The receiver obtains 100, 55 and 241; show how the error is detected.</p></>, answer: <p>Sender: 100 + 55 + 240 = 395; 395 MOD 256 = <strong>139</strong>. Receiver: 100 + 55 + 241 = 396; 396 MOD 256 = <strong>140</strong>. Since 140 ≠ transmitted 139, an error is detected. <em>[4]</em></p> },
      { id: "l32-6", marks: 2, lines: 2, prompt: <><b>State what a receiver should do after a parity or checksum mismatch.</b></>, answer: <p>Reject/flag the corrupted block and request retransmission (or use an agreed error-handling procedure). The check normally detects; it does not reconstruct arbitrary corrupted data. <em>[2]</em></p> },
    ],
  },
  {
    code: "C", title: "Published transfer checks", subtitle: "Parity calculation and checksum description", marks: 10,
    questions: [
      { id: "l32-7", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>For the supplied even-parity block, calculate the missing parity bit and identify the changed bit from the failing row and column.</b><p>Adapted from 9618/12 O/N 2025 Q6(c). [2]</p></>, answer: <p>The published results are: missing even-parity bit <strong>0</strong>; altered bit at <strong>row 2, column 5</strong>. <em>[1 each]</em></p> },
      { id: "l32-8", marks: 3, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Describe how a checksum is used to check transferred data.</b><p>Adapted from 9618/11 M/J 2025 Q7(c). [3]</p></>, answer: <p>The sender calculates a checksum from the data and transmits it with the data; the receiver recalculates the checksum using the same algorithm; the values are compared and a mismatch indicates an error. <em>[3]</em></p> },
      { id: "l32-9", marks: 5, lines: 5, prompt: <><b>Choose and justify the correct syllabus method for each need:</b><p>(i) test a typed product code; (ii) locate one changed bit in a small transferred block; (iii) check a large transferred file with a compact value.</p></>, answer: <p>(i) <strong>check digit validation</strong>, recalculate from the code and compare. (ii) <strong>block parity</strong>, failing row/column intersect at the likely bit. (iii) <strong>checksum</strong>, calculate/send/recalculate a compact value for the whole data. Award method plus justification; one additional comparative point. <em>[5]</em></p> },
    ],
  },
];

export default function Lesson32Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Move from entry integrity to transfer integrity and define today's evidence.", prompt: "Ask what can change between sender and receiver even when entry was perfect.", source: "Syllabus 6.2; Coursebook 9.05 printed pp.141–143.", content: <Slide number="01" eyebrow="CHAPTER 6 · TRANSFER INTEGRITY" sourceLabel="TEXTBOOK §9.05 · pp.141–143" syllabusLabel="SYLLABUS 6.2" className="se-title"><section className="se-title-grid"><div className="se-title-copy"><span>LESSON 32 · 90 MINUTES</span><h1>Check what <em>arrived.</em></h1><p>Add redundancy before transmission; recalculate after it. Use byte parity, block parity and checksums without claiming they detect every possible error.</p></div><div className="se-title-visual"><div><b>1</b><span>CALCULATE BEFORE SENDING</span></div><div><b>2</b><span>TRANSFER DATA + CHECK</span></div><div><b>3</b><span>RECALCULATE AT RECEIVER</span></div><div><b>4</b><span>COMPARE · ACCEPT OR REJECT</span></div></div></section></Slide> },
    { time: "5 min", focus: "Connect Lesson 31 entry checks to today's transmission checks.", prompt: "Sort each method into entry validation, entry verification or transfer verification.", source: "Syllabus 6.2 full integrity methods; Coursebook 9.05.", content: <Slide number="02" eyebrow="DO NOW · WHERE IS THE ERROR?" sourceLabel="TEXTBOOK §9.05 · pp.140–143" syllabusLabel="SYLLABUS 6.2" title="Different stage—different evidence."><section className="se-compare"><div><b>STAGE</b><b>QUESTION</b><b>METHODS</b></div><div><b>Data entry</b><span>reasonable and copied as intended?</span><span>validation; visual check; double entry</span></div><div><b>Data transfer</b><span>same bits arrived?</span><span>byte parity; block parity; checksum</span></div></section><p className="se-note">All methods add a way to <strong>detect inconsistency</strong>; detection is not the same as automatic correction.</p></Slide> },
    { time: "6 min", focus: "Define even and odd parity using the total count including the parity bit.", prompt: "Does the parity bit always equal 1 when odd parity is used?", source: "Coursebook 9.05 printed pp.141–142; syllabus 6.2 parity check.", content: <Slide number="03" eyebrow="ONE EXTRA BIT" sourceLabel="TEXTBOOK §9.05 · pp.141–142" syllabusLabel="SYLLABUS 6.2" title="Choose the parity bit to make the total count of 1s even or odd."><section className="se-grid two"><article className="se-card"><span>EVEN PARITY</span><h3>Total number of 1s is even</h3><p>1011010 contains four 1s → parity bit <strong>0</strong>.</p></article><article className="se-card"><span>ODD PARITY</span><h3>Total number of 1s is odd</h3><p>1011010 contains four 1s → parity bit <strong>1</strong>.</p></article></section><p className="se-warning">Count the 1s in the <strong>complete unit, including the parity bit</strong>.</p></Slide> },
    { time: "6 min", focus: "Practise parity-bit calculation with zero and seven-one edge cases.", prompt: "Students show the count before choosing each bit.", source: "Coursebook 9.05 parity activity; syllabus 6.2 use parity check.", content: <Slide number="04" eyebrow="CALCULATE BYTE PARITY" sourceLabel="TEXTBOOK §9.05 · pp.141–142" syllabusLabel="SYLLABUS 6.2" title="Count → target → choose."><section className="se-compare four"><div><b>DATA</b><b>1s NOW</b><b>RULE</b><b>PARITY BIT</b></div><div><b>1100100</b><span>3</span><span>even</span><span><strong>1</strong></span></div><div><b>0000000</b><span>0</span><span>even</span><span><strong>0</strong></span></div><div><b>1111111</b><span>7</span><span>odd</span><span><strong>0</strong></span></div></section><p className="se-note">The bit is derived from the current count; it is not a fixed marker for “even” or “odd”.</p></Slide> },
    { time: "6 min", focus: "Explain detection through parity change and expose even-error blindness.", prompt: "Predict the result after one flipped bit, then after two.", source: "Coursebook 9.05 parity limitations; syllabus 6.2 parity.", content: <Slide number="05" eyebrow="WHAT BYTE PARITY CAN DETECT" sourceLabel="TEXTBOOK §9.05 · pp.141–142" syllabusLabel="SYLLABUS 6.2" title="Odd number of changed bits flips the expected parity."><section className="se-grid three"><article className="se-card"><span>1 BIT CHANGES</span><h3>Detected</h3><p>1-count changes by one; even ↔ odd.</p></article><article className="se-card"><span>2 BITS CHANGE</span><h3>May be missed</h3><p>1-count can remain the same or change by two.</p></article><article className="se-card"><span>RESULT</span><h3>Evidence—not certainty</h3><p>Pass means “no detectable parity mismatch”.</p></article></section><p className="se-warning">Single parity detects any odd number of bit flips but can miss an even number.</p></Slide> },
    { time: "6 min", focus: "Extend parity across rows and columns and explain the extra parity row/column.", prompt: "What two independent checks does every data bit contribute to?", source: "Coursebook 9.05 block parity printed pp.142–143; syllabus 6.2 block parity.", content: <Slide number="06" eyebrow="BLOCK PARITY" sourceLabel="TEXTBOOK §9.05 · pp.142–143" syllabusLabel="SYLLABUS 6.2" title="Give each data bit a row check and a column check."><table className="se-parity-table"><thead><tr><th>EVEN</th><th>D1</th><th>D2</th><th>D3</th><th>D4</th><th>ROW P</th></tr></thead><tbody><tr><th>ROW 1</th><td>1</td><td>0</td><td>1</td><td>1</td><td>1</td></tr><tr><th>ROW 2</th><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td></tr><tr><th>ROW 3</th><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td></tr><tr><th>COL P</th><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td></tr></tbody></table><p className="se-note">The final row and column are derived so every full row and full column satisfies the agreed parity.</p></Slide> },
    { time: "8 min", focus: "Locate a single changed bit at the intersection of failed row and column.", prompt: "Audit row counts and column counts before naming the intersection.", source: "Coursebook 9.05 block parity; syllabus 6.2; pattern used in 9618/12 O/N 2025 Q6(c).", content: <Slide number="07" eyebrow="LOCATE ONE ERROR" sourceLabel="TEXTBOOK pp.142–143 + PAPER 1" syllabusLabel="SYLLABUS 6.2" title="Failed row 2 × failed column 3 → inspect their intersection."><table className="se-parity-table"><thead><tr><th>EVEN</th><th>D1</th><th>D2</th><th>D3 ↓</th><th>D4</th><th>ROW P</th></tr></thead><tbody><tr><th>ROW 1</th><td>1</td><td>0</td><td>1</td><td>1</td><td>1</td></tr><tr><th>ROW 2 →</th><td>0</td><td>1</td><td className="error">0</td><td>0</td><td>0</td></tr><tr><th>ROW 3</th><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td></tr><tr><th>COL P</th><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td></tr></tbody></table><p className="se-warning">This location logic assumes a single changed bit. Multiple errors can create ambiguous or undetected patterns.</p></Slide> },
    { time: "6 min", focus: "Explain why block parity improves evidence but has limits.", prompt: "Can two failed rows and two failed columns identify one unique pair of errors?", source: "Coursebook 9.05 block parity limitations; syllabus 6.2.", content: <Slide number="08" eyebrow="DETECT, LOCATE, QUALIFY" sourceLabel="TEXTBOOK §9.05 · pp.142–143" syllabusLabel="SYLLABUS 6.2" title="Block parity can locate a single error—not every multi-bit pattern."><section className="se-grid three"><article className="se-card"><span>ONE ERROR</span><p>one failed row + one failed column → unique intersection</p></article><article className="se-card"><span>MULTIPLE ERRORS</span><p>several failed lines may give several possible intersections</p></article><article className="se-card"><span>EVEN PATTERNS</span><p>some changes preserve every row/column parity and remain hidden</p></article></section></Slide> },
    { time: "6 min", focus: "Define checksum as a compact value computed from the whole data block.", prompt: "What three things must sender and receiver share for the comparison to be meaningful?", source: "Coursebook 9.05 printed p.141; syllabus 6.2 checksum.", content: <Slide number="09" eyebrow="CHECKSUM" sourceLabel="TEXTBOOK §9.05 · p.141" syllabusLabel="SYLLABUS 6.2" title="Calculate → send with data → recalculate → compare."><section className="se-flow"><span>SENDER USES<br />AGREED ALGORITHM</span><i>→</i><span>DATA + CHECKSUM<br />TRANSMITTED</span><i>→</i><span>RECEIVER<br />RECALCULATES</span><i>→</i><span>MATCH?<br />ACCEPT / FLAG</span></section><p className="se-note">A checksum is compact evidence about a block/file. A mismatch detects change; a match does not mathematically guarantee perfection.</p></Slide> },
    { time: "6 min", focus: "Use a simple stated modulo checksum and show a mismatch after one byte changes.", prompt: "Calculate both results without a calculator; identify the first divergent step.", source: "Coursebook 9.05 checksum example; syllabus 6.2 describe and use checksum.", content: <Slide number="10" eyebrow="USE A STATED CHECKSUM" sourceLabel="TEXTBOOK §9.05 · p.141" syllabusLabel="SYLLABUS 6.2" title="Example algorithm: sum bytes MOD 256."><div className="se-sum-strip"><span>100</span><span>+</span><span>55</span><span>+</span><span>240</span><span>= 395</span><span>MOD 256</span><span>139</span></div><p className="se-note">Receiver gets 100, 55, <strong>241</strong>: sum 396 → checksum 140. Because <strong>140 ≠ 139</strong>, flag the data or request retransmission.</p></Slide> },
    { time: "5 min", focus: "Differentiate three methods by stage, evidence and scale.", prompt: "Choose the method for a typed ISBN-like code, a small bit block and a downloaded file.", source: "Syllabus 6.2 check digit, block parity and checksum; Coursebook 9.05.", content: <Slide number="11" eyebrow="DO NOT MIX THE CHECKS" sourceLabel="TEXTBOOK §9.05 · pp.141–143" syllabusLabel="SYLLABUS 6.2" title="Derived digit, parity geometry or block summary."><section className="se-compare four"><div><b>METHOD</b><b>STAGE</b><b>EVIDENCE</b><b>BEST FIT HERE</b></div><div><b>Check digit</b><span>data entry validation</span><span>digit derived from code</span><span>product/identifier entry</span></div><div><b>Block parity</b><span>transfer verification</span><span>row + column parity</span><span>locate one bit error</span></div><div><b>Checksum</b><span>transfer verification</span><span>compact value for data</span><span>block/file comparison</span></div></section></Slide> },
    { time: "6 min", focus: "Consolidate the whole of Chapter 6 around threat, control and evidence.", prompt: "Students connect one threat to one preventive control and one integrity check.", source: "Syllabus 6.1–6.2; Coursebook Chapter 9 summary printed p.144.", content: <Slide number="12" eyebrow="CHAPTER 6 · COMPLETE MAP" sourceLabel="TEXTBOOK CH.9 · p.144" syllabusLabel="SYLLABUS 6.1–6.2" title="Protect access; protect content; detect bad data."><section className="se-grid four"><article className="se-card"><span>L29</span><h3>Promises + threats</h3><p>security, privacy, integrity; virus, spyware, hacker, phishing, pharming</p></article><article className="se-card"><span>L30</span><h3>Protective layers</h3><p>accounts, authentication, filtering, anti-malware, encryption, rights</p></article><article className="se-card"><span>L31</span><h3>Entry integrity</h3><p>validation, check digit, visual check and double entry</p></article><article className="se-card"><span>L32</span><h3>Transfer integrity</h3><p>byte parity, block parity and checksum</p></article></section></Slide> },
    { time: "8 min", focus: "Practise a published even-parity calculation and error location.", prompt: "Complete independently in two minutes; explain the row-column evidence before reveal.", source: "Adapted from 9618/12 O/N 2025 Q6(c), checked against the published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 2 MARKS" sourceLabel="9618/12 O/N 2025 · Q6(c)" syllabusLabel="SYLLABUS 6.2 — EXAM PRACTICE" title="Complete even parity; locate the altered bit." className="slide--se-paper"><section className="se-paper-grid"><article><span>1 MARK</span><p>Calculate the supplied block&apos;s missing <strong>even-parity bit</strong>.</p></article><article><span>1 MARK</span><p>Use its failed row and column to identify the <strong>altered position</strong>.</p></article></section><ExamReveal><p>Published answers: parity bit <strong>0</strong>; altered position <strong>row 2, column 5</strong>.</p></ExamReveal><small className="se-source-line">Concise adaptation of 9618/12 O/N 2025 Q6(c); original allocation [2].</small></Slide> },
    { time: "7 min", focus: "Practise the three-stage checksum mark scheme.", prompt: "Underline the sender action, receiver action and comparison in the answer.", source: "Adapted from 9618/11 M/J 2025 Q7(c), checked against the published mark scheme.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE · 3 MARKS" sourceLabel="9618/11 M/J 2025 · Q7(c)" syllabusLabel="SYLLABUS 6.2 — EXAM PRACTICE" title="Describe how a checksum checks transferred data." className="slide--se-paper"><section className="se-paper-grid three"><article><span>SENDER</span><p>What is calculated and transmitted?</p></article><article><span>RECEIVER</span><p>What is recalculated?</p></article><article><span>DECISION</span><p>What is compared—and what does mismatch mean?</p></article></section><ExamReveal><p>The sender calculates a checksum and sends it with the data; the receiver recalculates using the same algorithm; the two values are compared and a mismatch indicates an error.</p></ExamReveal><small className="se-source-line">Concise adaptation of 9618/11 M/J 2025 Q7(c); original allocation [3].</small></Slide> },
    { time: "5 min", focus: "Check parity reasoning, method selection and Chapter 6 language.", prompt: "Students submit all three; no answer may use 'guarantees'.", source: "Syllabus 6.1–6.2 lesson synthesis; Coursebook Chapter 9.", content: <Slide number="15" eyebrow="EXIT TICKET · CHAPTER 6" sourceLabel="TEXTBOOK CH.9 · REVIEW" syllabusLabel="SYLLABUS 6.1–6.2" title="Finish the chapter with three defensible claims."><section className="se-exit"><article><span>1 · CALCULATE</span><p>Even parity for 1010111 needs bit ___.</p></article><article><span>2 · CHOOSE</span><p>One failed row and column: use ___.</p></article><article><span>3 · QUALIFY</span><p>A checksum match means… but does not prove…</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="32" slides={slides} homework={<HomeworkSheet lessonNumber="32" title="Data Integrity in Transfer: Parity, Block Checks and Checksums" marks={30} minutes={45} syllabusLabel="SYLLABUS 6.2" sourceLabel="TEXTBOOK CH.9 · pp.141–145 + PAPER 1" instructions="Show every parity count and checksum calculation. Describe sender, receiver and comparison stages in order. State limitations carefully: these methods detect specified error patterns but do not guarantee perfect transfer." sections={homeworkSections} challenge={{ id: "l32-challenge", prompt: <p><Mark>CHALLENGE</Mark> In a rectangular even-parity block, four data bits at the corners of an imaginary rectangle are flipped. Explain why every affected row and column can still pass.</p>, answer: <p>Each of the two affected rows contains two flipped bits, so its number of 1s changes by an even amount and even parity can remain satisfied. The same is true for each of the two affected columns. The rectangular four-bit pattern therefore demonstrates that two-dimensional parity cannot detect every multi-bit error.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 6.2, Coursebook Chapter 9 printed pp.141–145, and the published 2025 Paper 1 parity and checksum questions and mark schemes." sourceDetail="Core: even/odd byte parity, block parity, checksum and their limitations, followed by complete Chapter 6 consolidation. Authentic anchors: 9618/12 O/N 2025 Q6(c) [2] and 9618/11 M/J 2025 Q7(c) [3]. Error-correcting codes and cryptographic hashes are beyond this AS transfer-verification lesson." />;
}
