"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip, WorkedBoard } from "../../_components/a2-theory-lesson";
import { AdtBoard } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "ADT operations", subtitle: "Name the contract before choosing a representation", marks: 10,
    questions: [
      { id: "a2-26-1", marks: 3, lines: 6, prompt: <><b>Explain what is meant by an Abstract Data Type.</b></>, answer: <p>An ADT defines a set of values/data and permitted operations <em>[1]</em> while hiding implementation details <em>[1]</em>. The same external behaviour can therefore be implemented using different built-in types or other ADTs <em>[1]</em>.</p> },
      { id: "a2-26-2", marks: 3, lines: 6, prompt: <><b>Compare a stack and a queue.</b></>, answer: <p>A stack is LIFO: both insertion (PUSH) and deletion (POP) occur at the top <em>[1]</em>. A queue is FIFO: ENQUEUE adds at the rear and DEQUEUE removes from the front <em>[1]</em>. Therefore they remove items in different orders <em>[1]</em>.</p> },
      { id: "a2-26-3", marks: 4, lines: 8, prompt: <><b>Describe how a dictionary ADT could be implemented and used.</b></>, answer: <p>A dictionary stores key-value pairs and keys are unique <em>[1]</em>. It provides add/update, lookup-by-key and delete operations <em>[1]</em>. It may be implemented by a built-in map/hash table or a list of records <em>[1]</em>, allowing fast retrieval of a value such as a student record from its ID <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Linked-list algorithms", subtitle: "Change pointers without losing the remaining chain", marks: 10,
    questions: [
      { id: "a2-26-4", marks: 3, lines: 8, prompt: <><b>Write pseudocode to find Target in a singly linked list</b> using StartPointer, Data and Next.</>, answer: <pre><code>{`Current ← StartPointer\nWHILE Current <> -1 AND Data[Current] <> Target\n   Current ← Next[Current]\nENDWHILE\nRETURN Current`}</code></pre> },
      { id: "a2-26-5", marks: 3, lines: 7, prompt: <><b>Explain how to insert NewNode between Previous and Current.</b></>, answer: <p>Store <code>Next[NewNode] ← Current</code> <em>[1]</em>, then set <code>Next[Previous] ← NewNode</code> <em>[1]</em>. If insertion is at the head, update <code>StartPointer ← NewNode</code> instead of a previous link <em>[1]</em>.</p> },
      { id: "a2-26-6", marks: 4, lines: 8, prompt: <><b>Explain how to delete Current from a singly linked list safely.</b></>, answer: <p>Find Current while retaining Previous <em>[1]</em>. Bypass it using <code>Next[Previous] ← Next[Current]</code> <em>[1]</em>; if Current is the head, set <code>StartPointer ← Next[Current]</code> <em>[1]</em>. Return the removed node to the free list/mark it unused without losing the successor pointer <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Trees, graphs and composition", subtitle: "Use structural invariants and build one ADT from another", marks: 10,
    questions: [
      { id: "a2-26-7", marks: 3, lines: 7, prompt: <><b>Describe how to find a value in a binary search tree.</b></>, answer: <p>Begin at the root and compare the target with the node data <em>[1]</em>. If smaller follow the left pointer; if larger follow the right pointer <em>[1]</em>. Stop when equal or when a null pointer proves the target is absent <em>[1]</em>.</p> },
      { id: "a2-26-8", marks: 3, lines: 6, prompt: <><b>Explain why a graph is an ADT and justify one use.</b></>, answer: <p>A graph is defined by vertices, edges and operations such as adding/finding vertices or neighbours, independent of its representation <em>[2]</em>. It suits a route network because weighted edges can represent connections and costs <em>[1]</em>.</p> },
      { id: "a2-26-9", marks: 4, lines: 8, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>A queue is held in Stack1 with its front at the top. Explain how Stack2 can be used to add NewItem at the rear.</b></p><p>Adapted from 9618/31 M/J 2023 Q11(c). [4]</p></>, answer: <p>Pop every existing item from Stack1 and push it onto empty Stack2 <em>[1]</em>, reversing the order <em>[1]</em>. Push NewItem onto Stack1 <em>[1]</em>. Pop every item from Stack2 back onto Stack1 so the original front is again at the top and NewItem is at the bottom/rear <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson26Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Separate promised behaviour from storage detail.", prompt: "Can two different data structures implement the same ADT?", source: "2027–2029 syllabus 19.1 p.37; coursebook Chapter 23 printed pp.415–429.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch23" syllabusLabel="SYLLABUS 19.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 26 · 90 MINUTES</span><h1>Define the behaviour.<br /><em>Hide the storage.</em></h1><p>stack · queue · linked list · binary tree · dictionary · graph</p></div><div className="a2-at-hero" role="img" aria-label="Abstract data type lesson themes"><strong>ABSTRACT DATA TYPE</strong><span>LIFO</span><span>FIFO</span><span>POINTER</span><span>KEY → VALUE</span></div></section></Slide> },
    { time: "5 min", focus: "Map the unusually detailed ADT algorithm requirement.", prompt: "Which structures require find, insert or delete algorithms?", source: "Official 2027–2029 syllabus 19.1 p.37.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.37" syllabusLabel="19.1 · REQUIRED" title="Describe six ADTs, write named operations and demonstrate composition." className="a2-slide a2-at-slide"><CompareTable headers={["Requirement", "Structures"]} rows={[["find", "linked list · binary tree"], ["insert", "stack · queue · linked list · binary tree"], ["delete", "stack · queue · linked list"], ["describe / implement", "stack · queue · linked list · dictionary · binary tree"], ["justify, no structure code", "graph"], ["build from another ADT", "for example queue from stacks"]]} /></Slide> },
    { time: "5 min", focus: "Define abstraction as an operation contract.", prompt: "Which details should a stack user not need to know?", source: "Coursebook §23.05 p.415; syllabus 19.1.", content: <Slide number="03" eyebrow="ADT CONTRACT" sourceLabel="TEXTBOOK p.415" syllabusLabel="19.1 · ABSTRACT" title="An ADT says what operations mean, not how bytes are arranged." className="a2-slide a2-at-slide"><CompareTable headers={["Interface / behaviour", "Possible implementation"]} rows={[["PUSH, POP, PEEK", "array + Top pointer or linked list"], ["ENQUEUE, DEQUEUE", "circular array or linked list"], ["lookup(key), add, remove", "hash table or list of records"], ["find / insert tree value", "array of node records with pointers"]]} /></Slide> },
    { time: "6 min", focus: "Recognise structure and removal order at a glance.", prompt: "Which structure removes C first, and which removes A first?", source: "Coursebook §§23.06–23.10 pp.415–425.", content: <Slide number="04" eyebrow="STRUCTURE GALLERY" sourceLabel="TEXTBOOK pp.415–425" syllabusLabel="19.1 · DESCRIBE" title="Each ADT preserves a different relationship or access rule." className="a2-slide a2-at-slide"><AdtBoard /></Slide> },
    { time: "6 min", focus: "Write bounded stack operations.", prompt: "Which pointer update happens before storing during PUSH?", source: "Coursebook §23.08 pp.421–422; 9618/32 O/N 2025 Q12(a).", content: <Slide number="05" eyebrow="STACK · LIFO" sourceLabel="9618/32 O/N 2025 · Q12(a)" syllabusLabel="19.1 · INSERT / DELETE" title="PUSH adds at Top; POP removes the most recently added item." className="a2-slide a2-at-slide"><CompareTable headers={["PUSH(NewData)", "POP()"]} rows={[["if Top = Max: overflow", "if Top = -1: underflow"], ["Top ← Top + 1", "Item ← Stack[Top]"], ["Stack[Top] ← NewData", "Top ← Top - 1"], ["inserts one item", "returns/deletes one item"]]} /></Slide> },
    { time: "6 min", focus: "Write queue operations with front and rear roles.", prompt: "Why must a circular queue also track length or a full flag?", source: "Coursebook §23.09 pp.422–423; 9618/31 M/J 2023 Q11.", content: <Slide number="06" eyebrow="QUEUE · FIFO" sourceLabel="9618/31 M/J 2023 · Q11" syllabusLabel="19.1 · INSERT / DELETE" title="ENQUEUE at Rear; DEQUEUE from Front; wrap pointers without changing FIFO order." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "ENQUEUE", title: "advance Rear", body: "wrap after Max" }, { eyebrow: "STORE", title: "Queue[Rear] ← Item" }, { eyebrow: "DEQUEUE", title: "read Queue[Front]" }, { eyebrow: "REMOVE", title: "advance Front", body: "decrease Length" }]} /></Slide> },
    { time: "6 min", focus: "Read a linked list as logical order rather than array order.", prompt: "Which field tells us the next logical node?", source: "Coursebook §23.06 pp.415–417.", content: <Slide number="07" eyebrow="LINKED LIST" sourceLabel="TEXTBOOK pp.415–417" syllabusLabel="19.1 · STRUCTURE" title="Each node stores data and a pointer; StartPointer identifies the first logical node." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "NODE", title: "Data field", body: "Value held by this logical item." }, { eyebrow: "LINK", title: "Next pointer", body: "Index/address of the successor." }, { eyebrow: "HEAD", title: "StartPointer", body: "Entry to the chain." }, { eyebrow: "END", title: "Null pointer", body: "No further node." }]} /></Slide> },
    { time: "6 min", focus: "Find, insert and delete while preserving the chain.", prompt: "Why must deletion retain Previous?", source: "Coursebook linked-list algorithms pp.415–417.", content: <Slide number="08" eyebrow="LINKED-LIST ALGORITHMS" sourceLabel="TEXTBOOK pp.415–417" syllabusLabel="19.1 · FIND / INSERT / DELETE" title="Traverse by pointers; rewire links in an order that never loses the tail." className="a2-slide a2-at-slide"><CompareTable headers={["Operation", "Essential pointer action"]} rows={[["find", "Current ← Start; repeat Current ← Next[Current]"], ["insert after Previous", "Next[New] ← Next[Previous], then Next[Previous] ← New"], ["insert at head", "Next[New] ← Start, then Start ← New"], ["delete after Previous", "Next[Previous] ← Next[Current]"], ["delete head", "Start ← Next[Current]"]]} /></Slide> },
    { time: "6 min", focus: "Distinguish a binary tree from an ordered binary search tree.", prompt: "Does every binary tree guarantee smaller values on the left?", source: "Coursebook §23.07 pp.418–420.", content: <Slide number="09" eyebrow="BINARY TREE" sourceLabel="TEXTBOOK pp.418–420" syllabusLabel="19.1 · STRUCTURE" title="Binary means at most two children; ordering is an extra invariant." className="a2-slide a2-at-slide"><CompareTable headers={["Binary tree", "Binary search tree / ordered binary tree"]} rows={[["each node has up to two children", "also has up to two children"], ["left/right do not automatically imply value order", "left subtree values smaller, right larger (by chosen rule)"], ["a general find may traverse many nodes", "comparison selects one branch per level"], ["useful for hierarchies", "useful for ordered search and insertion"]]} /></Slide> },
    { time: "6 min", focus: "Write iterative ordered-tree search and insertion.", prompt: "Which pointer changes only when the new null position is found?", source: "Coursebook binary-tree algorithms pp.418–420; 9618/31 O/N 2024 Q11.", content: <Slide number="10" eyebrow="TREE · FIND + INSERT" sourceLabel="9618/31 O/N 2024 · Q11" syllabusLabel="19.1 · WRITE" title="Compare at a node, choose left or right, and stop at equal or null." className="a2-slide a2-at-slide"><WorkedBoard label="Search rule"><pre><code>{`Current ← Root\nWHILE Current <> -1 AND Tree[Current].Data <> Target\n   IF Target < Tree[Current].Data THEN\n      Current ← Tree[Current].Left\n   ELSE\n      Current ← Tree[Current].Right\n   ENDIF\nENDWHILE`}</code></pre><p>Insertion follows the same comparisons while retaining Parent, then connects NewNode to the null child pointer.</p></WorkedBoard></Slide> },
    { time: "7 min", focus: "Describe dictionary behaviour independently of hashing.", prompt: "What makes a key different from a position number?", source: "Coursebook §23.12 pp.428–429.", content: <Slide number="11" eyebrow="DICTIONARY" sourceLabel="TEXTBOOK pp.428–429" syllabusLabel="19.1 · DESCRIBE / IMPLEMENT" title="A dictionary maps each unique key to a value." className="a2-slide a2-at-slide"><CompareTable headers={["Operation", "Example", "Possible implementation"]} rows={[["add / update", <code key="add">Age[&quot;Sam&quot;] ← 17</code>, "built-in map or hash table"], ["lookup", <code key="lookup">Age[&quot;Sam&quot;]</code>, "hash key or search records"], ["membership", <code key="member">&quot;Sam&quot; in Age</code>, "check key exists"], ["delete", <code key="delete">remove &quot;Sam&quot;</code>, "remove key-value pair"]]} /></Slide> },
    { time: "7 min", focus: "Treat graph behaviour as an ADT and respect the no-code boundary.", prompt: "What graph feature makes it better than a tree for a road network?", source: "Coursebook §23.10 pp.424–426; syllabus 19.1 p.37.", content: <Slide number="12" eyebrow="GRAPH AS AN ADT" sourceLabel="TEXTBOOK pp.424–426" syllabusLabel="19.1 · JUSTIFY · NO CODE" title="Graphs allow arbitrary many-to-many connections, directions and weights." className="a2-slide a2-at-slide"><CompareTable headers={["Feature", "Why useful"]} rows={[["vertices + edges", "models entities and relationships"], ["directed / undirected", "one-way or mutual relationships"], ["weighted / unweighted", "stores cost or simple reachability"], ["cycles and multiple paths", "models real transport/social/network systems"], ["representations", "adjacency list or matrix can implement the same ADT"]]} /></Slide> },
    { time: "7 min", focus: "Demonstrate one ADT implemented using another.", prompt: "When should OutStack be refilled?", source: "Syllabus 19.1; coursebook ADT composition; 9618/31 M/J 2023 Q11(c).", content: <Slide number="13" eyebrow="ADT FROM ANOTHER ADT" sourceLabel="9618/31 M/J 2023 · Q11(c)" syllabusLabel="19.1 · DEMONSTRATE" title="Two LIFO stacks can expose FIFO queue behaviour." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "ENQUEUE", title: "PUSH onto InStack" }, { eyebrow: "NEED FRONT", title: "If OutStack empty…" }, { eyebrow: "TRANSFER", title: "POP In; PUSH Out", body: "reverses order" }, { eyebrow: "DEQUEUE", title: "POP OutStack", body: "oldest item emerges" }]} /></Slide> },
    { time: "8 min", focus: "Explain the exact two-stack transformation in mark-point order.", prompt: "Track where the old front and the new rear finish.", source: "Adapted from Cambridge 9618/31 M/J 2023 Q11(c) and published mark scheme.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/31 M/J 2023 · Q11(c)" syllabusLabel="19.1 · 4 MARKS" title="Reverse, add, restore." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/31 M/J 2023 · Q11(c) · ADAPTED" marks={4} prompt={<p>A queue is stored in Stack1 with its front at the top. Explain how empty Stack2 can be used to add NewItem at the rear. [4]</p>} answer={<ul><li>POP every item from Stack1 and PUSH it onto Stack2. [1]</li><li>This reverses the existing order. [1]</li><li>PUSH NewItem onto empty Stack1. [1]</li><li>POP all items from Stack2 back to Stack1; the old front is again on top and NewItem is at the bottom/rear. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve operation, invariant and implementation for every ADT.", prompt: "Students name one invariant and one implementation choice.", source: "Syllabus 19.1 synthesis; coursebook Chapter 23 pp.415–429.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch23 · SYLLABUS p.37" syllabusLabel="19.1 · LESSON CLOSE" title="Protect the contract, preserve the links and choose a fitting implementation." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>ORDER</span><p>LIFO or FIFO.</p></article><article><span>LINK</span><p>Rewire without losing nodes.</p></article><article><span>INVARIANT</span><p>Ordered-tree branch rule.</p></article><article><span>ABSTRACTION</span><p>Same behaviour, many implementations.</p></article></section><div className="homework-callout"><b>HOMEWORK 26</b><span>30 marks · ADT operations and composition</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="26" title="Abstract Data Types and their algorithms" syllabusLabel="SYLLABUS 19.1" sourceLabel="TEXTBOOK Ch23 · pp.415–429" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 19.1 p.37 · endorsed coursebook Chapter 23 printed pp.415–429 · verified 2023–2025 Paper 3 questions and mark schemes" sourceDetail="The lesson describes stacks, queues, linked lists, dictionaries, binary trees and graphs; writes the required find, insert and delete operations; distinguishes binary from ordered binary trees; and demonstrates one ADT implemented from other ADTs." />;
}
