"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip, Formula, WorkedBoard } from "../../_components/a2-theory-lesson";
import { WeightedGraph } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Graph structure", subtitle: "Name the objects before searching them", marks: 10,
    questions: [
      { id: "a2-23-1", marks: 3, lines: 5, prompt: <><b>Define vertex, edge and weight</b> in a graph.</>, answer: <p>A vertex/node represents an object or state <em>[1]</em>. An edge/arc represents a connection between two vertices <em>[1]</em>. A weight is the numerical cost attached to an edge, such as distance, time or price <em>[1]</em>.</p> },
      { id: "a2-23-2", marks: 3, lines: 6, prompt: <><b>Distinguish directed and undirected graphs.</b> Give one suitable use of each.</>, answer: <p>A directed edge has a specified direction, so A→B need not allow B→A; one-way roads are suitable <em>[2]</em>. An undirected edge can be followed both ways; a mutual-friend network is suitable <em>[1]</em>.</p> },
      { id: "a2-23-3", marks: 4, lines: 7, prompt: <><b>Explain why a route-finding problem can be represented as a weighted graph.</b></>, answer: <p>Locations are represented by vertices <em>[1]</em>, available direct routes by edges <em>[1]</em>, and distance/time/cost by weights <em>[1]</em>. A graph-search algorithm can then compare path totals to select a least-cost route <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Shortest-path search", subtitle: "Track cost so far and make each update explicit", marks: 10,
    questions: [
      { id: "a2-23-4", marks: 3, lines: 6, prompt: <><b>Describe the purpose of relaxation in Dijkstra&apos;s algorithm.</b></>, answer: <p>For an edge from the current node to a neighbour, calculate current distance + edge weight <em>[1]</em>. If this is less than the neighbour&apos;s tentative distance, replace it <em>[1]</em> and record the current node as its predecessor <em>[1]</em>.</p> },
      { id: "a2-23-5", marks: 3, lines: 6, prompt: <><b>State how Dijkstra&apos;s algorithm chooses and finalises nodes.</b></>, answer: <p>Choose the unvisited node with the smallest tentative distance <em>[1]</em>. Mark/finalise it as visited <em>[1]</em>, then relax its unvisited neighbours; repeat until the destination is finalised or no reachable node remains <em>[1]</em>.</p> },
      { id: "a2-23-6", marks: 4, lines: 7, prompt: <><b>Use Dijkstra&apos;s algorithm on the lesson graph to find the least-cost route from S to G.</b> Show the route and total.</>, answer: <p>The successive best distances include A=2, C=4, D=6 and G=7 <em>[2]</em>. Following predecessors gives S→A→C→D→G <em>[1]</em>, with total 2+2+2+1=<strong>7</strong> <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "A* and exam comparison", subtitle: "Separate accumulated cost from the estimate", marks: 10,
    questions: [
      { id: "a2-23-7", marks: 3, lines: 6, prompt: <><b>Define g(n), h(n) and f(n) in A* search.</b></>, answer: <p><code>g(n)</code> is known path cost from the start to n <em>[1]</em>. <code>h(n)</code> is an estimate of cost from n to the goal <em>[1]</em>. <code>f(n)=g(n)+h(n)</code> ranks candidates <em>[1]</em>.</p> },
      { id: "a2-23-8", marks: 3, lines: 6, prompt: <><b>Explain how A* differs from Dijkstra&apos;s algorithm.</b></>, answer: <p>Dijkstra ranks nodes using accumulated cost only <em>[1]</em>. A* adds a heuristic estimate of remaining cost <em>[1]</em>, so a useful heuristic can prioritise promising nodes and explore fewer alternatives <em>[1]</em>.</p> },
      { id: "a2-23-9", marks: 4, lines: 8, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>State the purpose of A* and Dijkstra&apos;s algorithms and outline one difference.</b></p><p>Adapted from 9618/33 M/J 2025 Q10(a)–(b). [4 adapted marks]</p></>, answer: <p>Both find a path/least-cost route between vertices in a weighted graph <em>[1]</em>. Dijkstra chooses by lowest known accumulated distance <em>[1]</em>; A* also uses a heuristic estimate of remaining cost <em>[1]</em>, which gives priority to nodes estimated to lead more cheaply toward the goal <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson23Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame graph search as a representation problem before an algorithm problem.", prompt: "What is a node and what is a connection in a route planner?", source: "2027–2029 syllabus 18.1 p.36; coursebook Chapter 22 printed pp.397–402.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch22" syllabusLabel="SYLLABUS 18.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 23 · 90 MINUTES</span><h1>Model the space.<br /><em>Find the best path.</em></h1><p>graphs · weights · Dijkstra · A* · heuristic</p></div><div className="a2-at-hero" role="img" aria-label="Graph search lesson themes"><strong>GRAPH SEARCH</strong><span>VERTEX</span><span>WEIGHT</span><span>g(n)</span><span>h(n)</span></div></section></Slide> },
    { time: "5 min", focus: "Map every syllabus requirement and the explicit coding boundary.", prompt: "Which two algorithms must candidates use, rather than write from scratch?", source: "Official 2027–2029 syllabus p.36.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.36" syllabusLabel="18.1 · REQUIRED" title="Understand the structure, then perform two graph searches." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "MODEL", title: "Graph", body: "Purpose, vertices, edges and weights." }, { eyebrow: "PERFORM", title: "Dijkstra", body: "Least accumulated cost first." }, { eyebrow: "PERFORM", title: "A*", body: "Cost so far plus a heuristic." }, { eyebrow: "BOUNDARY", title: "No graph code", body: "Setup, access and search code are not required." }]} /></Slide> },
    { time: "5 min", focus: "Build precise graph vocabulary.", prompt: "Which word describes a sequence of connected edges?", source: "Coursebook §22.02 pp.398–399.", content: <Slide number="03" eyebrow="GRAPH VOCABULARY" sourceLabel="TEXTBOOK pp.398–399" syllabusLabel="18.1 · STRUCTURE" title="A graph stores objects and the relationships between them." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "VERTEX / NODE", title: "Object or state", body: "A city, web page, position or decision state." }, { eyebrow: "EDGE / ARC", title: "Connection", body: "Directed or undirected relationship." }, { eyebrow: "WEIGHT", title: "Cost", body: "Distance, time, price or risk." }, { eyebrow: "PATH", title: "Edge sequence", body: "A route from one vertex to another." }]} /></Slide> },
    { time: "6 min", focus: "Read a weighted graph without confusing layout with cost.", prompt: "Why is the visually shortest line not necessarily the cheapest path?", source: "Coursebook Figure 22.01 and graph examples pp.398–401.", content: <Slide number="04" eyebrow="READ THE MODEL" sourceLabel="TEXTBOOK pp.398–401" syllabusLabel="18.1 · WEIGHTED GRAPH" title="Edge labels determine path cost; page geometry does not." className="a2-slide a2-at-slide"><WeightedGraph /></Slide> },
    { time: "6 min", focus: "Connect AI problems to state-space graphs.", prompt: "What could a vertex and edge mean in a game-playing system?", source: "Coursebook Chapter 22 overview and §22.02.", content: <Slide number="05" eyebrow="WHY AI USES GRAPHS" sourceLabel="TEXTBOOK Ch22" syllabusLabel="18.1 · PURPOSE" title="Many AI tasks are searches through possible states and actions." className="a2-slide a2-at-slide"><CompareTable headers={["Application", "Vertex", "Edge", "Weight"]} rows={[["route planner", "location", "road/rail link", "distance or time"], ["game playing", "board position", "legal move", "estimated cost/risk"], ["robot navigation", "reachable position", "movement", "energy or time"], ["network routing", "device/router", "link", "latency or cost"]]} /></Slide> },
    { time: "6 min", focus: "Initialise Dijkstra's working state.", prompt: "Why does every non-start node begin at infinity?", source: "Coursebook Dijkstra algorithm pp.399–400.", content: <Slide number="06" eyebrow="DIJKSTRA · INITIALISE" sourceLabel="TEXTBOOK pp.399–400" syllabusLabel="18.1 · PERFORM" title="Store a tentative distance, predecessor and visited state for each vertex." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "START", title: "distance = 0" }, { eyebrow: "OTHERS", title: "distance = ∞" }, { eyebrow: "ALL", title: "unvisited" }, { eyebrow: "REPEAT", title: "choose smallest tentative distance" }]} /></Slide> },
    { time: "6 min", focus: "Apply edge relaxation correctly.", prompt: "When is an existing tentative distance replaced?", source: "Coursebook Dijkstra structured-English steps pp.399–400.", content: <Slide number="07" eyebrow="DIJKSTRA · RELAX" sourceLabel="TEXTBOOK pp.399–400" syllabusLabel="18.1 · PERFORM" title="A newly discovered route matters only when its total is smaller." className="a2-slide a2-at-slide"><Formula>candidate = distance[current] + weight(current, neighbour)</Formula><WorkedBoard label="Update rule"><p>If <code>candidate &lt; distance[neighbour]</code>, store the candidate and set the neighbour&apos;s predecessor to the current vertex.</p></WorkedBoard></Slide> },
    { time: "6 min", focus: "Trace Dijkstra on a small graph.", prompt: "After S is visited, which node is selected next and why?", source: "Coursebook worked shortest-path method pp.399–400.", content: <Slide number="08" eyebrow="DIJKSTRA · TRACE" sourceLabel="TEXTBOOK pp.399–400" syllabusLabel="18.1 · WORKED" title="Finalise the unvisited node with the least tentative distance." className="a2-slide a2-at-slide"><CompareTable headers={["Finalised", "A", "B", "C", "D", "G"]} rows={[["S (0)", "2 via S", "5 via S", "∞", "∞", "∞"], ["A (2)", "—", "5 via S", "4 via A", "∞", "∞"], ["C (4)", "—", "5 via S", "—", "6 via C", "11 via C"], ["B (5)", "—", "—", "—", "6 via C", "11 via C"], ["D (6)", "—", "—", "—", "—", "7 via D"]]} /></Slide> },
    { time: "6 min", focus: "Recover the route from predecessor links.", prompt: "Why is the final distance alone insufficient to print the route?", source: "Coursebook Dijkstra method pp.399–400.", content: <Slide number="09" eyebrow="DIJKSTRA · FINISH" sourceLabel="TEXTBOOK pp.399–400" syllabusLabel="18.1 · SHORTEST PATH" title="The destination cost is 7; predecessors reconstruct the path backwards." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "GOAL", title: "G", body: "distance 7" }, { eyebrow: "PREDECESSOR", title: "D" }, { eyebrow: "PREDECESSOR", title: "C" }, { eyebrow: "PREDECESSOR", title: "A" }, { eyebrow: "START", title: "S", body: "reverse to report route" }]} /></Slide> },
    { time: "6 min", focus: "Define the two A* score components.", prompt: "Which score is measured and which is estimated?", source: "Coursebook A* method pp.401–402; syllabus 18.1.", content: <Slide number="10" eyebrow="A* SCORE" sourceLabel="TEXTBOOK pp.401–402" syllabusLabel="18.1 · PERFORM" title="A* combines known cost with an estimate of what remains." className="a2-slide a2-at-slide"><Formula>f(n) = g(n) + h(n)</Formula><ConceptCards items={[{ eyebrow: "g(n)", title: "Cost so far", body: "Exact accumulated path cost from the start." }, { eyebrow: "h(n)", title: "Heuristic", body: "Estimated cost from n to the goal." }, { eyebrow: "f(n)", title: "Priority", body: "Choose the open node with the smallest total estimate." }]} /></Slide> },
    { time: "7 min", focus: "Use heuristic labels without treating them as edge weights.", prompt: "At A, what are g, h and f after following S→A?", source: "Coursebook A* worked example pp.401–402.", content: <Slide number="11" eyebrow="A* · WORKED GRAPH" sourceLabel="TEXTBOOK pp.401–402" syllabusLabel="18.1 · HEURISTIC" title="The heuristic points toward the goal; edge weights still build g." className="a2-slide a2-at-slide"><WeightedGraph showHeuristic /></Slide> },
    { time: "7 min", focus: "Compare A* and Dijkstra using the same vocabulary.", prompt: "What value of h would make A* rank nodes like Dijkstra?", source: "Coursebook pp.399–402; 9618/33 M/J 2025 Q10.", content: <Slide number="12" eyebrow="COMPARE THE SEARCHES" sourceLabel="9618/33 M/J 2025 · Q10" syllabusLabel="18.1 · EXPLAIN" title="Both seek a least-cost path; only A* adds informed direction." className="a2-slide a2-at-slide"><CompareTable headers={["Feature", "Dijkstra", "A*"]} rows={[["priority", "lowest g", "lowest g + h"], ["heuristic", "none", "estimate to goal"], ["edge costs", "requires non-negative weights", "normally non-negative costs + suitable h"], ["search behaviour", "expands outward by cost", "can focus toward goal"], ["special relationship", "—", "h = 0 behaves like Dijkstra"], ["shared record", "distance + predecessor", "g/f + predecessor"]]} /></Slide> },
    { time: "7 min", focus: "Hold the exact current-syllabus boundary.", prompt: "What might an exam ask you to do with a supplied graph?", source: "Official 2027–2029 syllabus 18.1 p.36.", content: <Slide number="13" eyebrow="EXAM BOUNDARY" sourceLabel="SYLLABUS p.36" syllabusLabel="18.1 · NO GRAPH CODE" title="You perform the searches; you are not required to program graph setup, access or search." className="a2-slide a2-at-slide"><CompareTable headers={["Required", "Not required by 18.1"]} rows={[["identify graph structure and purpose", "write code to create a graph"], ["apply Dijkstra to a supplied graph", "write a full Dijkstra implementation"], ["apply A* using supplied heuristics", "write graph traversal/search code"], ["state route, cost and comparison", "invent hidden data structures"]]} /></Slide> },
    { time: "8 min", focus: "Answer a current-style comparison in mark-point language.", prompt: "Give a purpose shared by both, then one algorithmic distinction.", source: "Adapted from Cambridge 9618/33 M/J 2025 Q10(a)–(b) and published mark scheme.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/33 M/J 2025 · Q10(a)–(b)" syllabusLabel="18.1 · 3 MARKS" title="Purpose first; heuristic distinction second." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/33 M/J 2025 · Q10(a)–(b) · ADAPTED" marks={3} prompt={<p>State the purpose of A* and Dijkstra&apos;s algorithms. Outline one difference between them. [3]</p>} answer={<ul><li>They find a path/least-cost route between two vertices in a weighted graph. [1]</li><li>A* ranks a candidate using a heuristic estimate as well as accumulated cost. [1]</li><li>Dijkstra uses accumulated/tentative distance without a heuristic, so it may explore more alternatives. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve the complete graph-search decision process.", prompt: "Students state one graph term, one Dijkstra step and the A* formula.", source: "Syllabus 18.1 synthesis; coursebook Chapter 22 pp.397–402.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch22 · SYLLABUS p.36" syllabusLabel="18.1 · LESSON CLOSE" title="Represent connections, accumulate cost, then choose the next frontier." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>GRAPH</span><p>Vertices joined by weighted edges.</p></article><article><span>DIJKSTRA</span><p>Lowest tentative g first.</p></article><article><span>A*</span><p>Lowest f = g + h first.</p></article><article><span>REPORT</span><p>Path plus total cost.</p></article></section><div className="homework-callout"><b>HOMEWORK 23</b><span>30 marks · graphs, Dijkstra and A*</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="23" title="Graphs, Dijkstra and A* search" syllabusLabel="SYLLABUS 18.1" sourceLabel="TEXTBOOK Ch22 · pp.397–402" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 18.1 p.36 · endorsed coursebook Chapter 22 printed pp.397–402 · verified 2023 and 2025 Paper 3 questions and mark schemes" sourceDetail="The lesson establishes graph structure and purpose, then performs Dijkstra and A* searches. It explicitly respects the syllabus boundary that candidates are not required to write graph setup, access or search algorithms." />;
}
