"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l24-reveal-${id}`;
  return <div className="asm-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className="asm-reveal__panel" hidden={!visible}>{children}</div></div>;
}

function Bits({ value, changed = "" }: { value: string; changed?: string }) {
  return <div className="asm-bit-row" aria-label={`Binary value ${value}`}>{value.split("").map((bit, index) => <span className={changed.includes(String(index)) ? "changed" : ""} key={`${value}-${index}`}>{bit}</span>)}</div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Shift precisely", subtitle: "Show the fixed-width result and distinguish the shift types", marks: 10,
    questions: [
      { id: "l24-1", marks: 6, lines: 5, prompt: <><b>Apply each operation to an 8-bit value.</b><p>(a) 11001010 LSL 2 [1] (b) 10011110 LSR 3 [1] (c) 10011110 arithmetic right 3 [1] (d) 11001010 cyclic left 2 [1] (e) Explain the difference between logical and arithmetic right shift. [2]</p></>, answer: <p><b>(a)</b> 00101000. <b>(b)</b> 00010011. <b>(c)</b> 11110011. <b>(d)</b> 00101011. <b>(e)</b> Logical right inserts 0 at the left; arithmetic right copies the original sign bit/MSB so a two’s-complement number retains its sign. Both discard bits leaving the right. <em>[6]</em></p> },
      { id: "l24-2", marks: 4, lines: 4, prompt: <><b>Explain when a left shift can be described as multiplication by 2, and why the statement is not always safe.</b></>, answer: <p>Each left shift moves every bit one place to a weight twice as large and inserts 0 at the right, so an unsigned value is multiplied by 2 for each place <strong>if no significant bit is lost</strong>. In a fixed-width register, high bits are discarded; this can cause overflow, and for signed two’s-complement data it can also change the sign. <em>[4]</em></p> },
    ],
  },
  {
    code: "B", title: "Authentic Paper 1 operations", subtitle: "Recent shifts, masks and mixed number bases", marks: 10,
    questions: [
      { id: "l24-3", marks: 4, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Give the instruction/result for four independent tasks.</b><p>(a) 00011110 becomes 01111000—write the instruction. (b) 11100011 XOR &12. (c) 11100011 AND #63. (d) 11100011 OR the contents of address 100, where M[100]=00110011.</p><p>Adapted from 9618/11 O/N 2025 Q4(a)-(d). [4]</p></>, answer: <p><b>(a)</b> LSL #2. <b>(b)</b> 11110001. <b>(c)</b> 00100011. <b>(d)</b> 11110011. <em>[1 each]</em></p> },
      { id: "l24-4", marks: 3, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Complete three bit-manipulation tasks.</b><p>(i) Write an instruction that sets only the LSB. (ii) 01010101 XOR &FE. (iii) 01101011 LSR #5. Adapted from 9618/11 M/J 2025 Q8(b)(i)-(iii). [3]</p></>, answer: <p><b>(i)</b> OR B00000001 (also OR #1 / OR &01). <b>(ii)</b> 10101011. <b>(iii)</b> 00000011. <em>[1 each]</em></p> },
      { id: "l24-5", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Shift two 8-bit two’s-complement values.</b><p>(i) Logical left 2 on 11001010. (ii) Arithmetic right 3 on 10011110. Adapted from 9618/13 M/J 2025 Q7(a)(i)-(ii). [2]</p></>, answer: <p><b>(i)</b> 00101000. <b>(ii)</b> 11110011. <em>[1 each]</em></p> },
      { id: "l24-6", marks: 1, lines: 2, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>ACC=11110000. Give the result of OR B00001111.</b><p>Adapted from 9618/12 M/J 2025 Q7(b)(i). [1]</p></>, answer: <p><strong>11111111</strong>. <em>[1]</em></p> },
    ],
  },
  {
    code: "C", title: "Masks for monitoring and control", subtitle: "Test, set and clear one flag without damaging the others", marks: 10,
    questions: [
      { id: "l24-7", marks: 3, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain how bit manipulation can test whether an ACC value is odd, then write the instruction.</b><p>Adapted from 9618/12 O/N 2024 Q8(b)(ii). [3]</p></>, answer: <p>An odd binary integer has LSB=1. AND with a mask containing only that bit clears all other bits; compare the result with 1. Instruction: <strong>AND B00000001</strong> (also AND #1 / AND &01). <em>[3]</em></p> },
      { id: "l24-8", marks: 7, lines: 5, prompt: <><b>A device status register contains 10100100, with bit positions 7 to 0 from left to right.</b><p>(a) Test bit 5 and give the result. [2] (b) Set bit 1 and give the new byte. [2] (c) Clear bit 7 and give the new byte. [2] (d) Explain why each mask preserves the other bits. [1]</p></>, answer: <p><b>(a)</b> AND 00100000 → 00100000, so bit 5 is set. <b>(b)</b> OR 00000010 → 10100110. <b>(c)</b> AND 01111111 → 00100100. <b>(d)</b> AND with 1 preserves a bit while OR with 0 preserves a bit; only the target mask position changes/tests state. <em>[7]</em></p> },
    ],
  },
];

export default function Lesson24Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "3 min", focus: "Frame a byte as eight independent switches as well as one number.", prompt: "Ask what bit 5 could represent in a sensor register.", source: "Syllabus 4.3 p.22; Coursebook 6.05 p.102 and 7.03 pp.115-120.", content: <Slide number="01" eyebrow="CHAPTER 4 · BIT MANIPULATION" sourceLabel="TEXTBOOK 6.05 + 7.03" syllabusLabel="SYLLABUS 4.3 · p.22" className="slide--asm-title"><section className="asm-title-grid"><div className="asm-title-copy"><span>LESSON 24 · 90 MINUTES</span><h1>Shift bits.<br /><em>Control states.</em></h1><p>Move a fixed-width pattern, isolate one flag, set an output or toggle a device—without disturbing the other bits.</p></div><div className="asm-chip-stack"><p><b>SHIFT</b><span>logical · arithmetic · cyclic</span></p><p><b>MASK</b><span>AND · OR · XOR</span></p><p><b>CONTROL</b><span>test · set · clear · toggle</span></p></div></section></Slide> },
    { time: "4 min", focus: "Expose the full syllabus scope and its device-control application.", prompt: "Students match test/set/toggle with an operator.", source: "Syllabus 4.3 p.22.", content: <Slide number="02" eyebrow="TODAY'S ROUTE" sourceLabel="SYLLABUS 4.3" syllabusLabel="SYLLABUS 4.3 — COMPLETE" title="Move patterns; then change one chosen bit."><section className="asm-route"><article><b>SHIFT</b><p>left and right</p></article><article><b>DISTINGUISH</b><p>logical · arithmetic · cyclic</p></article><article><b>MASK</b><p>AND · OR · XOR</p></article><article><b>APPLY</b><p>monitor and control</p></article></section></Slide> },
    { time: "5 min", focus: "Fix bit numbering before using masks.", prompt: "Students point to bit 0, bit 5 and the MSB.", source: "Coursebook 7.03 pp.115-118.", content: <Slide number="03" eyebrow="ANATOMY OF AN 8-BIT REGISTER" sourceLabel="TEXTBOOK 7.03" syllabusLabel="SYLLABUS 4.3" title="Bit 7 is the MSB; bit 0 is the LSB."><div className="asm-bit-labels">{[7,6,5,4,3,2,1,0].map((bit) => <span key={bit}>bit {bit}</span>)}</div><Bits value="10100100" changed="2" /><p className="asm-note">A flag byte gives each sensor or actuator one fixed position. Here, bit 5 is 1.</p></Slide> },
    { time: "6 min", focus: "Perform logical shifts within a fixed 8-bit width.", prompt: "Students identify introduced zeros and discarded bits.", source: "Coursebook 6.05 pp.101-102; syllabus LSL/LSR p.22.", content: <Slide number="04" eyebrow="LOGICAL SHIFTS" sourceLabel="TEXTBOOK pp.101-102" syllabusLabel="SYLLABUS 4.3 — LOGICAL" title="Discard bits at one end; introduce zeros at the other."><section className="asm-shift-stack"><article><b>11001010 · LSL 2</b><Bits value="11001010" /></article><i>→</i><article><b>result</b><Bits value="00101000" changed="67" /></article></section><p className="asm-note">LSR works in the opposite direction and introduces zeros at the left.</p></Slide> },
    { time: "7 min", focus: "Use sign extension for arithmetic right shift and qualify arithmetic left shift.", prompt: "Compare logical-right and arithmetic-right results for a negative byte.", source: "Syllabus 4.3; published 9618/13 M/J 2025 Q7(a).", content: <Slide number="05" eyebrow="ARITHMETIC SHIFTS" sourceLabel="SYLLABUS 4.3 + PAPER 1" syllabusLabel="SYLLABUS 4.3 — ARITHMETIC" title="Arithmetic right preserves the original sign bit."><section className="asm-shift-stack"><article><b>10011110 · right 3</b><Bits value="10011110" /></article><i>→</i><article><b>sign-extended result</b><Bits value="11110011" changed="012" /></article></section><p className="asm-warning">Arithmetic left has the same bit movement as logical left—zeros enter at the right—but signed overflow can make the numerical interpretation invalid.</p></Slide> },
    { time: "6 min", focus: "Teach cyclic shifts as rotations that reinsert the leaving bit.", prompt: "Students rotate 11001010 left twice by hand.", source: "Syllabus 4.3 cyclic shifts.", content: <Slide number="06" eyebrow="CYCLIC SHIFTS" sourceLabel="SYLLABUS 4.3" syllabusLabel="SYLLABUS 4.3 — CYCLIC" title="The bit leaving one end returns at the other end."><section className="asm-shift-stack"><article><b>11001010 · rotate left 2</b><Bits value="11001010" /></article><i>↻</i><article><b>result</b><Bits value="00101011" changed="67" /></article></section><p className="asm-note">Unlike a logical or arithmetic shift, a pure cyclic shift does not discard a bit.</p></Slide> },
    { time: "5 min", focus: "Qualify multiply/divide shortcuts with fixed-width overflow.", prompt: "Students decide whether each shortcut is safe for one given byte.", source: "Coursebook shift discussion p.101.", content: <Slide number="07" eyebrow="NUMERICAL EFFECT" sourceLabel="TEXTBOOK p.101" syllabusLabel="SYLLABUS 4.3" title="A shift changes place value only while important bits survive."><section className="asm-card-grid"><article className="asm-card"><span>LEFT</span><h3>×2 per place</h3><p>for an unsigned value if no 1 is lost</p></article><article className="asm-card"><span>LOGICAL RIGHT</span><h3>÷2 per place</h3><p>unsigned integer, rounded down</p></article><article className="asm-card"><span>ARITHMETIC RIGHT</span><h3>sign extend</h3><p>preserve a two’s-complement sign</p></article></section></Slide> },
    { time: "7 min", focus: "Use AND to isolate/test or clear selected positions.", prompt: "Students derive a mask for bit 5.", source: "Coursebook 6.05 p.102 and 7.03 pp.115-118.", content: <Slide number="08" eyebrow="AND MASK" sourceLabel="TEXTBOOK 6.05 / 7.03" syllabusLabel="SYLLABUS 4.3 — TEST" title="AND with 1 preserves; AND with 0 clears."><section className="asm-mask-grid"><article><h3>value</h3><code>10100100</code><p>status register</p></article><article><h3>mask bit 5</h3><code>00100000</code><p>only target position is 1</p></article><article><h3>result</h3><code>00100000</code><p>non-zero: bit 5 was set</p></article></section></Slide> },
    { time: "7 min", focus: "Use OR to force a selected bit to 1 without changing others.", prompt: "Students set bit 1 of 10100100.", source: "Coursebook 6.05 p.102 and 7.03.", content: <Slide number="09" eyebrow="OR MASK" sourceLabel="TEXTBOOK 6.05 / 7.03" syllabusLabel="SYLLABUS 4.3 — SET" title="OR with 1 sets; OR with 0 preserves."><section className="asm-mask-grid"><article><h3>value</h3><code>10100100</code></article><article><h3>mask bit 1</h3><code>00000010</code></article><article><h3>result</h3><code>10100110</code></article></section><p className="asm-note">To clear bit 1 instead, AND with 11111101.</p></Slide> },
    { time: "7 min", focus: "Use XOR to toggle selected bits.", prompt: "Students predict the effect of applying the same XOR mask twice.", source: "Coursebook bitwise instruction table p.102.", content: <Slide number="10" eyebrow="XOR MASK" sourceLabel="TEXTBOOK 6.05 · p.102" syllabusLabel="SYLLABUS 4.3 — TOGGLE" title="XOR with 1 flips; XOR with 0 preserves."><section className="asm-mask-grid"><article><h3>value</h3><code>10100100</code></article><article><h3>mask bit 2</h3><code>00000100</code></article><article><h3>result</h3><code>10100000</code></article></section><p className="asm-note">Applying the same XOR mask again restores the original byte.</p></Slide> },
    { time: "7 min", focus: "Connect one status byte to monitoring and actuator control.", prompt: "Students write masks to read sensor 3 and switch actuator 1 on.", source: "Coursebook 7.03 pp.115-120; syllabus monitor/control application.", content: <Slide number="11" eyebrow="DEVICE FLAG BYTE" sourceLabel="TEXTBOOK 7.03 · pp.115-120" syllabusLabel="SYLLABUS 4.3 — CONTROL" title="Each bit can represent one sensor or one actuator."><section className="asm-flag-byte">{[7,6,5,4,3,2,1,0].map((bit) => <article className={[5,2].includes(bit) ? "on" : ""} key={bit}><b>{[5,2].includes(bit) ? 1 : 0}</b><span>BIT {bit}</span></article>)}</section><section className="asm-trace-rule"><p><b>TEST</b><br />AND target mask</p><p><b>SET ON</b><br />OR target mask</p><p><b>SET OFF</b><br />AND inverse mask</p></section></Slide> },
    { time: "8 min", focus: "Use a verified four-mark recent Paper 1 operation set.", prompt: "Four minutes independent; four minutes reveal and recompute.", source: "Adapted from 9618/11 O/N 2025 Q4(a)-(d), checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/11 O/N 2025 · Q4(a-d)" syllabusLabel="SYLLABUS 4.3 — EXAM" className="asm-paper" title="Shift, XOR, AND and OR—one mark each."><section className="asm-paper-grid"><article><b>1</b><p>00011110 → 01111000: instruction?</p></article><article><b>2</b><p>11100011 XOR &12</p></article><article><b>3</b><p>11100011 AND #63</p></article><article><b>4</b><p>11100011 OR M[100], where M[100]=00110011</p></article></section><Reveal id="on25" visible={revealed.has("on25")} onToggle={toggleReveal}><p><b>LSL #2 · 11110001 · 00100011 · 11110011.</b></p></Reveal><small>Adapted from 9618/11 O/N 2025 Q4(a)-(d).</small></Slide> },
    { time: "6 min", focus: "Use an authentic mask explanation with mark-ready reasoning.", prompt: "Students write the reasoning before the instruction.", source: "Adapted from 9618/12 O/N 2024 Q8(b)(ii).", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 3 MARKS" sourceLabel="9618/12 O/N 2024 · Q8(b)(ii)" syllabusLabel="SYLLABUS 4.3 — EXAM" className="asm-paper" title="How can bit manipulation test whether a value is odd?"><section className="asm-paper-grid"><article><b>PROPERTY</b><p>Which bit determines odd/even?</p></article><article><b>MASK</b><p>How do all other bits disappear?</p></article></section><Reveal id="odd" visible={revealed.has("odd")} onToggle={toggleReveal}><p>Odd means LSB=1. AND with 00000001, then compare the result with 1. Instruction: <strong>AND B00000001</strong> / AND #1 / AND &01.</p></Reveal><small>Adapted from 9618/12 O/N 2024 Q8(b)(ii).</small></Slide> },
    { time: "7 min", focus: "Interleave shift type and masks in a final timed check.", prompt: "Five minutes work; two minutes peer verification.", source: "Adapted from 2025 Paper 1 questions.", content: <Slide number="14" eyebrow="MIXED EXAM SPRINT · 5 MARKS" sourceLabel="PAPER 1 · 2025" syllabusLabel="SYLLABUS 4.3 — EXAM" className="asm-paper" title="No calculator: preserve eight bits."><section className="asm-paper-grid three"><article><b>2 marks</b><p>11001010 LSL 2; 10011110 arithmetic right 3.</p></article><article><b>2 marks</b><p>01010101 XOR &FE; 01101011 LSR #5.</p></article><article><b>1 mark</b><p>Set only the LSB.</p></article></section><Reveal id="sprint" visible={revealed.has("sprint")} onToggle={toggleReveal}><p><b>00101000; 11110011; 10101011; 00000011; OR B00000001</b> (or OR #1 / OR &01).</p></Reveal><small>Adapted from 9618/13 M/J 2025 Q7(a) and 9618/11 M/J 2025 Q8(b).</small></Slide> },
    { time: "5 min", focus: "Close with one operator rule and one safe mask.", prompt: "Students choose a bit and write test, set and clear masks.", source: "Syllabus 4.3 exit check.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK CH.6/7 · REVIEW" syllabusLabel="SYLLABUS 4.3" className="slide--asm-exit" title="Move it. Test it. Change only what you intend."><section className="asm-exit-grid"><article><b>SHIFT</b><p>What enters? What leaves?</p></article><article><b>MASK</b><p>Which bit is targeted?</p></article><article><b>VERIFY</b><p>Did every other bit remain?</p></article></section><div className="asm-homework-callout"><b>HOMEWORK 24</b><span>30 marks · five verified Paper 1 anchors · inline answers</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="24" slides={slides} homework={<HomeworkSheet lessonNumber="24" title="Binary Shifts, Masks & Device Control" marks={30} minutes={45} syllabusLabel="SYLLABUS 4.3 · p.22" sourceLabel="TEXTBOOK 6.05 + 7.03 · pp.101-102,115-120 + PAPER 1" instructions="Keep every answer at the stated bit width. For masks, show the original byte, mask and result, then explain which target bit is tested or changed. All adapted past-paper prompts retain their exact component, session, question and marks." sections={homeworkSections} challenge={{ id: "l24-challenge", prompt: <p><Mark>CHALLENGE</Mark> Write one instruction that toggles bits 6 and 2 while preserving every other bit.</p>, answer: <p><strong>XOR B01000100</strong>. A 1 in mask positions 6 and 2 flips those bits; the six 0 mask positions preserve their corresponding bits.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 4.3 p.22, Coursebook 6.05 printed pp.101-102 and 7.03 printed pp.115-120, and published 2024-2025 Paper 1 questions and mark schemes." sourceDetail="Core: logical, arithmetic and cyclic left/right shifts; fixed-width effects; AND/OR/XOR masks to test, set, clear and toggle bits; monitoring/control flags. Authentic anchors: 9618/11 O/N 2025 Q4(a)-(d), 9618/11 M/J 2025 Q8(b), 9618/13 M/J 2025 Q7(a), 9618/12 M/J 2025 Q7(b)(i), and 9618/12 O/N 2024 Q8(b)(ii). Every past-paper prompt is marked Adapted." />;
}
