"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { PipelineGrid } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "RISC and CISC", subtitle: "Use paired, exam-safe differences", marks: 10,
    questions: [
      { id: "a2-11-1", marks: 3, lines: 5, prompt: <><b>State three typical features of a RISC processor.</b></>, answer: <p>Any three: small/simple instruction set; fixed-length instructions; few addressing modes; load/store architecture; many general-purpose registers; mainly single-cycle execution; hard-wired control; well suited to pipelining <em>[3]</em>.</p> },
      { id: "a2-11-2", marks: 3, lines: 5, prompt: <><b>State three typical features of a CISC processor.</b></>, answer: <p>Any three: large/complex instruction set; variable-length instructions; many addressing modes; instructions can access memory directly; often multi-cycle; microprogrammed control; fewer general-purpose registers; more complex decoding <em>[3]</em>.</p> },
      { id: "a2-11-3", marks: 4, lines: 7, prompt: <><b>Explain two paired differences</b> between RISC and CISC processors.</>, answer: <p>RISC uses fewer, simpler and normally fixed-length instructions, whereas CISC provides more complex, often variable-length instructions <em>[2]</em>. RISC normally uses load/store instructions and many registers, whereas CISC instructions may access memory directly and use more addressing modes <em>[2]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Pipeline and registers", subtitle: "Distinguish latency from throughput", marks: 10,
    questions: [
      { id: "a2-11-4", marks: 3, lines: 5, prompt: <><b>Name three stages</b> in the five-stage instruction pipeline and state what each does.</>, answer: <p>Any three paired stages: IF fetches the instruction; ID decodes the opcode; OF fetches operands; IE executes the operation; WB writes the result back <em>[3]</em>.</p> },
      { id: "a2-11-5", marks: 3, lines: 5, prompt: <><b>Explain why registers are important</b> in a RISC pipeline.</>, answer: <p>Many fast registers reduce slower memory access <em>[1]</em>. Pipeline registers hold intermediate data/control information between stages <em>[1]</em>, allowing different stages to process different instructions concurrently <em>[1]</em>.</p> },
      { id: "a2-11-6", marks: 4, lines: 7, prompt: <><b>Five instructions enter a five-stage pipeline.</b> State the ideal cycle count and explain the performance effect.</>, answer: <p>The ideal count is <strong>5 + 5 − 1 = 9 cycles</strong> <em>[1]</em>, compared with 25 sequential stage-cycles <em>[1]</em>. Overlap increases throughput and, once full, one instruction can complete per cycle <em>[1]</em>; it does not make the latency of one instruction shorter <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Interrupt clinic", subtitle: "Protect the program state", marks: 10,
    questions: [
      { id: "a2-11-7", marks: 3, lines: 5, prompt: <><b>Outline interrupt handling on a typical sequential CISC processor.</b></>, answer: <p>The current instruction completes and the interrupt is accepted at an instruction boundary <em>[1]</em>; the PC/register state is saved and the ISR runs <em>[1]</em>; saved state is restored and the interrupted program resumes <em>[1]</em>.</p> },
      { id: "a2-11-8", marks: 3, lines: 5, prompt: <><b>Explain why a pipelined RISC processor makes interrupt handling more complex.</b></>, answer: <p>Several instructions can be partly complete at once <em>[1]</em>. A completed/write-back instruction is retained while other in-flight instructions are flushed/discarded <em>[1]</em>, so execution can restart at the correct next instruction after the ISR <em>[1]</em>.</p> },
      { id: "a2-11-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Explain how an interrupt is handled in a pipelined RISC processor.</b></p><p>Adapted from 9618/31 M/J 2024 Q11(b)–(c). [4 adapted marks]</p></>, answer: <p>The interrupt is detected at an appropriate instruction boundary <em>[1]</em>; current register contents/status, including the PC or return point, are stored on the stack <em>[1]</em>; the completed/write-back instruction is retained and other in-flight instructions are flushed/discarded <em>[1]</em>; the ISR runs, state is restored and execution resumes at the next valid instruction <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson11Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Compare two processor design philosophies through one task.", prompt: "Would one complex instruction or several simple instructions be easier to pipeline?", source: "2027–2029 syllabus 15.1; coursebook Chapter 18 printed pp.340–343.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch18" syllabusLabel="SYLLABUS 15.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 11 · 90 MINUTES</span><h1>Simple instructions.<br /><em>Continuous flow.</em></h1><p>RISC · CISC · registers · pipeline · interrupts</p></div><div className="a2-at-hero" role="img" aria-label="Instruction stages moving through a processor"><strong>PROCESSOR</strong><span>FETCH</span><span>DECODE</span><span>EXECUTE</span><span>WRITE BACK</span></div></section></Slide> },
    { time: "5 min", focus: "Map every lesson outcome to syllabus 15.1.", prompt: "Students turn each objective into a sentence they must be able to explain.", source: "Syllabus p.34; coursebook Chapter 18 pp.340–343.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.34" syllabusLabel="15.1 · PROCESSORS" title="Architecture features matter because they change execution." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "COMPARE", title: "RISC / CISC", body: "Use paired features." }, { eyebrow: "EXPLAIN", title: "Registers", body: "Keep operands and stage state close." }, { eyebrow: "EXPLAIN", title: "Pipelining", body: "Overlap stages to raise throughput." }, { eyebrow: "TRACE", title: "Interrupt", body: "Save, service, restore, resume." }]} /></Slide> },
    { time: "5 min", focus: "Define an instruction-set architecture without overloading terminology.", prompt: "Which choices are visible to the machine-code programmer?", source: "Coursebook §18.02 pp.341–342.", content: <Slide number="03" eyebrow="FOUNDATION" sourceLabel="TEXTBOOK pp.341–342" syllabusLabel="15.1 · ISA" title="An instruction set defines the operations a processor can execute." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "OPERATION", title: "Opcode", body: "What the instruction does." }, { eyebrow: "FORMAT", title: "Instruction fields", body: "How opcode and operands are encoded." }, { eyebrow: "ACCESS", title: "Registers + addressing", body: "Where operands are found." }]} /></Slide> },
    { time: "6 min", focus: "Build a precise RISC feature set.", prompt: "Which features make instruction timing predictable?", source: "Coursebook pp.341–343; 9618/33 O/N 2024 Q2.", content: <Slide number="04" eyebrow="RISC" sourceLabel="O/N 2024 · PAPER 33" syllabusLabel="15.1 · UNDERSTAND" title="RISC favours a small set of simple, regular instructions." className="a2-slide a2-at-slide"><CompareTable headers={["Design choice", "Typical RISC feature", "Effect"]} rows={[["format", "fixed length", "simpler decode"], ["memory", "load/store only", "operations use registers"], ["timing", "often one cycle", "predictable stages"], ["control", "hard-wired", "fast control signals"]]} /></Slide> },
    { time: "6 min", focus: "Build a precise CISC feature set.", prompt: "Why can a single CISC instruction perform more work?", source: "Coursebook pp.341–342; 9618/32 O/N 2024 Q8.", content: <Slide number="05" eyebrow="CISC" sourceLabel="O/N 2024 · PAPER 32" syllabusLabel="15.1 · UNDERSTAND" title="CISC favours a rich set of specialised instructions." className="a2-slide a2-at-slide"><CompareTable headers={["Design choice", "Typical CISC feature", "Effect"]} rows={[["format", "variable length", "more complex decode"], ["memory", "instructions may access it", "fewer explicit loads/stores"], ["timing", "often several cycles", "less regular flow"], ["control", "microprogrammed", "complex operations are easier to define"]]} /></Slide> },
    { time: "6 min", focus: "Compare processor styles using paired statements.", prompt: "Rewrite each row using whereas, not two disconnected lists.", source: "Syllabus 15.1; coursebook comparison table p.342.", content: <Slide number="06" eyebrow="PAIR THE DIFFERENCE" sourceLabel="TEXTBOOK p.342" syllabusLabel="15.1 · EXPLAIN" title="Cambridge comparison marks come from explicit contrasts." className="a2-slide a2-at-slide"><CompareTable headers={["RISC", "whereas", "CISC"]} rows={[["fewer simple instructions", "↔", "more complex instructions"], ["fixed-length format", "↔", "variable-length formats"], ["few addressing modes", "↔", "many addressing modes"], ["many general registers", "↔", "typically fewer registers"]]} /></Slide> },
    { time: "6 min", focus: "Explain why RISC relies on registers and compiler work.", prompt: "Convert one memory calculation into load, operate and store steps.", source: "Coursebook pp.342–343.", content: <Slide number="07" eyebrow="LOAD / STORE" sourceLabel="TEXTBOOK pp.342–343" syllabusLabel="15.1 · REGISTERS" title="RISC moves data to registers before arithmetic." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "LOAD", title: "Memory → R1" }, { eyebrow: "LOAD", title: "Memory → R2" }, { eyebrow: "ADD", title: "R1 + R2 → R3" }, { eyebrow: "STORE", title: "R3 → memory" }]} /></Slide> },
    { time: "6 min", focus: "Name and order the five pipeline stages.", prompt: "What must be held between one stage and the next?", source: "Coursebook §18.02 pp.342–343.", content: <Slide number="08" eyebrow="FIVE-STAGE PIPELINE" sourceLabel="TEXTBOOK pp.342–343" syllabusLabel="15.1 · PIPELINING" title="Different hardware stages can work on different instructions at once." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "IF", title: "Instruction fetch" }, { eyebrow: "ID", title: "Instruction decode" }, { eyebrow: "OF", title: "Operand fetch" }, { eyebrow: "IE", title: "Instruction execute" }, { eyebrow: "WB", title: "Write back" }]} /></Slide> },
    { time: "6 min", focus: "Read a complete timing diagram.", prompt: "Locate instruction 4 during cycle 6.", source: "Coursebook p.343; 9618/32 M/J 2023 Q8.", content: <Slide number="09" eyebrow="OVERLAP" sourceLabel="9618/32 M/J 2023 · Q8" syllabusLabel="15.1 · PIPELINING" title="Five instructions finish in nine ideal cycles, not twenty-five." className="a2-slide a2-at-slide"><PipelineGrid /></Slide> },
    { time: "6 min", focus: "Distinguish instruction latency from processor throughput.", prompt: "Challenge the claim: the pipeline makes one instruction take one cycle.", source: "Coursebook p.343; current syllabus wording.", content: <Slide number="10" eyebrow="PERFORMANCE" sourceLabel="TEXTBOOK p.343" syllabusLabel="15.1 · EXPLAIN" title="Pipelining raises throughput; one instruction still crosses every stage." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "LATENCY", title: "Five stages", body: "One instruction still travels IF → WB." }, { eyebrow: "THROUGHPUT", title: "One per cycle", body: "Possible after the pipeline fills." }, { eyebrow: "COST", title: "Hazards + flushes", body: "Dependencies and interrupts disturb the flow." }]} /></Slide> },
    { time: "7 min", focus: "Explain the register role between pipeline stages.", prompt: "What would be overwritten if adjacent stages shared one temporary value?", source: "Syllabus 15.1; coursebook p.343.", content: <Slide number="11" eyebrow="PIPELINE REGISTERS" sourceLabel="TEXTBOOK p.343" syllabusLabel="15.1 · REGISTERS" title="Registers preserve each instruction's intermediate state." className="a2-slide a2-at-slide"><CompareTable headers={["Register purpose", "Why it matters"]} rows={[["hold instruction/control bits", "next stage receives the correct operation"], ["hold operands/intermediate results", "stages do not overwrite one another"], ["provide fast local storage", "less waiting for main memory"], ["separate pipeline stages", "stages operate concurrently"]]} /></Slide> },
    { time: "7 min", focus: "Sequence interrupt handling on a typical sequential CISC processor.", prompt: "Why must the program counter and registers be saved at the instruction boundary?", source: "Coursebook p.343; 9618/31 M/J 2024 Q11.", content: <Slide number="12" eyebrow="CISC · INTERRUPT SEQUENCE" sourceLabel="9618/31 M/J 2024 · Q11" syllabusLabel="15.1 · CISC INTERRUPTS" title="Finish the current instruction, save state, service, then resume." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "BOUNDARY", title: "Complete instruction" }, { eyebrow: "SAVE", title: "Store PC + state" }, { eyebrow: "SERVICE", title: "Run ISR" }, { eyebrow: "RESTORE", title: "Reload state" }, { eyebrow: "RETURN", title: "Resume program" }]} /></Slide> },
    { time: "7 min", focus: "Compare pipelined RISC handling with the sequential CISC case.", prompt: "Mark completed, in-flight and not-yet-fetched instructions.", source: "Coursebook p.343; M/J 2024 Paper 31 mark scheme.", content: <Slide number="13" eyebrow="RISC · PIPELINE INTERRUPT" sourceLabel="M/J 2024 · PAPER 31" syllabusLabel="15.1 · RISC INTERRUPTS" title="RISC must also resolve several in-flight instructions." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "CISC BASELINE", title: "Instruction boundary", body: "A sequential instruction is completed before state is saved." }, { eyebrow: "RISC PIPELINE", title: "Flush incomplete work", body: "Retain the completed/write-back instruction; discard other in-flight instructions." }, { eyebrow: "RETURN", title: "Restart correctly", body: "Restore architectural state and continue at the next instruction." }]} /></Slide> },
    { time: "8 min", focus: "Apply processor, pipeline and interrupt mark points.", prompt: "Answer in four linked sentences, then reveal the marking route.", source: "Adapted from Cambridge 9618/31 M/J 2024 Q11(a)–(c).", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/31 M/J 2024 · Q11(a)–(c)" syllabusLabel="15.1 · 6 ADAPTED MARKS" title="Why is RISC easy to pipeline, and what happens on an interrupt?" className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/31 M/J 2024 · Q11(a)–(c) · ADAPTED" marks={6} prompt={<p>Explain two RISC features that support pipelining and outline interrupt handling in a pipeline. [6 adapted marks]</p>} answer={<ul><li>Fixed-length/simple, often single-cycle instructions make decode and stage timing predictable. [2]</li><li>Many registers and load/store operation keep operands readily available. [1]</li><li>Store current registers/status, including PC or return point, then run the ISR. [2]</li><li>Retain the completed/write-back instruction, discard other in-flight instructions, restore state and resume correctly. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve the whole lesson through one causal chain.", prompt: "Complete: regular instructions → predictable stages → overlap → higher …", source: "Syllabus 15.1 synthesis; coursebook Chapter 18.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch18 · SYLLABUS p.34" syllabusLabel="15.1 · CHECKPOINT" title="Regular instructions enable flow; precise state enables recovery." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>RISC</span><p>Simple · fixed · load/store · registers.</p></article><article><span>CISC</span><p>Rich · variable · complex decode.</p></article><article><span>PIPELINE</span><p>Overlap raises throughput.</p></article><article><span>INTERRUPT</span><p>Save · service · restore · resume.</p></article></section><div className="homework-callout"><b>HOMEWORK 11</b><span>30 marks · processors, pipeline and interrupts</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="11" title="RISC, CISC, pipelining and interrupts" syllabusLabel="SYLLABUS 15.1" sourceLabel="TEXTBOOK Ch18 · pp.340–343" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 15.1 p.34 · endorsed coursebook Chapter 18 printed pp.340–343 · verified 2023–2024 Paper 3 questions and mark schemes" sourceDetail="The lesson uses current syllabus terminology, keeps RISC/CISC features paired, and distinguishes pipeline throughput from instruction latency." />;
}
