"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Identity before permission", subtitle: "Accounts, passwords and authentication", marks: 10,
    questions: [
      { id: "l30-1", marks: 4, lines: 4, prompt: <><b>Distinguish authentication from authorisation. Use a school network example.</b></>, answer: <p><strong>Authentication</strong> checks that a user is who they claim to be, for example a student supplies a password and fingerprint. <strong>Authorisation</strong> decides what an authenticated account may access/do, for example the student can read their folder but cannot edit staff records. <em>[2 definitions + 2 linked examples]</em></p> },
      { id: "l30-2", marks: 3, lines: 3, prompt: <><b>Explain why a long, unique passphrase plus a second authentication factor is safer than one short reused password.</b></>, answer: <p>Length increases the number of possible guesses; uniqueness stops one breached service exposing other accounts; a second factor means the stolen password alone is insufficient. <em>[3]</em></p> },
      { id: "l30-3", marks: 3, lines: 3, prompt: <><b>Give one advantage and two limitations of biometric authentication.</b></>, answer: <p>Advantage: tied to the user and difficult to forget/share casually. Limitations include false acceptance/rejection, sensor cost, injury/environment affecting readings, and biometric templates being difficult to replace after compromise. <em>[1 + any 2]</em></p> },
    ],
  },
  {
    code: "B", title: "Layer the controls", subtitle: "Network, endpoint and data protection", marks: 10,
    questions: [
      { id: "l30-4", marks: 3, lines: 3, prompt: <><b>Describe how a firewall protects a network and state one limitation.</b></>, answer: <p>It monitors incoming/outgoing network traffic, compares packets/connections with configured rules and allows or blocks them. It cannot stop every malicious attachment, trusted insider or social-engineering attack. <em>[2 operation + 1 limitation]</em></p> },
      { id: "l30-5", marks: 3, lines: 3, prompt: <><b>Describe how anti-virus or anti-spyware software restricts risk.</b></>, answer: <p>It scans files/memory/activity for known signatures or suspicious behaviour, uses regularly updated definitions/rules, and blocks, quarantines or removes detected malware. <em>[3]</em></p> },
      { id: "l30-6", marks: 4, lines: 4, prompt: <><b>Explain how encryption and access rights protect the same payroll file in different ways.</b></>, answer: <p><strong>Encryption</strong> transforms plaintext into ciphertext using a key, so intercepted/stolen data is unreadable without the correct key. <strong>Access rights</strong> allow only authorised accounts specified operations such as read/write/delete. Encryption protects content; rights restrict actions through the system. <em>[2 + 2]</em></p> },
    ],
  },
  {
    code: "C", title: "Published mark-scheme chain", subtitle: "Digital signatures and protection software", marks: 10,
    questions: [
      { id: "l30-7", marks: 5, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain how a digital signature can authenticate a transmitted document and show whether it changed.</b><p>Adapted from 9618/13 M/J 2023 Q6(a). [5]</p></>, answer: <p>The sender hashes the document to produce a digest; encrypts/signs the digest using the sender&apos;s private key; sends the document and signature. The receiver verifies/decrypts the signature using the corresponding public key, hashes the received document and compares the two digests. A match supports origin and integrity. <em>[5]</em></p> },
      { id: "l30-8", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Name and describe one program that protects a computer from threats.</b><p>Adapted from 9618/13 M/J 2023 Q6(b). [2]</p></>, answer: <p>Example: <strong>anti-virus</strong> scans using updated signatures/behaviour and quarantines or deletes detected malware; or <strong>firewall</strong> filters network traffic using rules and blocks unauthorised connections. <em>[1 name + 1 description]</em></p> },
      { id: "l30-9", marks: 3, lines: 3, prompt: <><b>A school uses passwords and a firewall but pupils can still overwrite staff files.</b><p>Identify the missing control and explain two settings it needs.</p></>, answer: <p>Configure <strong>access rights/permissions</strong>. Pupil accounts should have no access or read-only access to staff areas, while authorised staff groups receive the minimum read/write rights needed; delete/admin rights should be more restricted. <em>[1 + 2]</em></p> },
    ],
  },
];

export default function Lesson30Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame security as layered controls selected from a threat path.", prompt: "Ask why one excellent password cannot protect every part of a system.", source: "Syllabus 6.1 security measures; Coursebook 9.03–9.04 printed pp.137–140.", content: <Slide number="01" eyebrow="CHAPTER 6 · · · PROTECTIVE MEASURES" sourceLabel="TEXTBOOK CH.9 · pp.137–140" syllabusLabel="SYLLABUS 6.1" className="se-title"><section className="se-title-grid"><div className="se-title-copy"><span>LESSON 30 · 90 MINUTES</span><h1>Build <em>layers.</em></h1><p>Authenticate people, filter traffic, protect endpoints and make stolen data unreadable—without pretending any single control is perfect.</p></div><div className="se-title-visual"><div><b>1</b><span>IDENTITY</span></div><div><b>2</b><span>PERMISSION</span></div><div><b>3</b><span>NETWORK + ENDPOINT</span></div><div><b>4</b><span>DATA</span></div></div></section></Slide> },
    { time: "5 min", focus: "Retrieve Lesson 29 threats and require a first control hypothesis.", prompt: "For each threat, name where a control could interrupt the chain.", source: "Syllabus 6.1 threats and methods to restrict risks; Coursebook 9.02–9.04.", content: <Slide number="02" eyebrow="DO NOW · THREAT → CONTROL" sourceLabel="TEXTBOOK §§9.02–9.04" syllabusLabel="SYLLABUS 6.1" title="Start with the route, not a favourite product."><section className="se-grid five"><article className="se-card"><span>VIRUS</span><p>file execution and replication</p></article><article className="se-card"><span>SPYWARE</span><p>hidden monitoring/exfiltration</p></article><article className="se-card"><span>HACKER</span><p>unauthorised access</p></article><article className="se-card"><span>PHISHING</span><p>deceptive message/action</p></article><article className="se-card"><span>PHARMING</span><p>redirection to fake site</p></article></section><p className="se-note">Propose a control and state <strong>which step it interrupts</strong>.</p></Slide> },
    { time: "6 min", focus: "Introduce defence in depth and the control categories required by the syllabus.", prompt: "Which layer limits damage after credentials have already been stolen?", source: "Coursebook 9.03–9.04; syllabus 6.1 system and data security measures.", content: <Slide number="03" eyebrow="DEFENCE IN DEPTH" sourceLabel="TEXTBOOK §§9.03–9.04" syllabusLabel="SYLLABUS 6.1" title="One layer can fail; the next can still prevent or limit harm."><section className="se-layer-stack"><div><b>USER + IDENTITY</b><span>accounts · passwords · biometrics · awareness</span></div><div><b>AUTHORISATION</b><span>access rights · least privilege</span></div><div><b>NETWORK</b><span>firewall · traffic rules</span></div><div><b>ENDPOINT</b><span>anti-virus · anti-spyware · updates</span></div><div><b>DATA</b><span>encryption · signatures · recovery copies</span></div></section></Slide> },
    { time: "6 min", focus: "Separate account identification, authentication and authorisation.", prompt: "A user logs in correctly but cannot edit a file—which stage rejected the action?", source: "Coursebook 9.03–9.04 printed pp.137–140; syllabus 6.1 user accounts and access rights.", content: <Slide number="04" eyebrow="ACCOUNT → AUTHENTICATE → AUTHORISE" sourceLabel="TEXTBOOK pp.137, 139–140" syllabusLabel="SYLLABUS 6.1" title="Who are you? Prove it. What may you do?"><section className="se-flow"><span>USER ID<br />CLAIM</span><i>→</i><span>AUTHENTICATION<br />EVIDENCE</span><i>→</i><span>ACCOUNT /<br />GROUP</span><i>→</i><span>ACCESS RIGHTS<br />ALLOW / DENY</span></section><p className="se-warning"><strong>Authentication</strong> proves identity. <strong>Authorisation</strong> applies permissions after identity is accepted.</p></Slide> },
    { time: "5 min", focus: "Update the textbook's short-password activity with current passphrase principles.", prompt: "Which improvement helps after a different website leaks the same password?", source: "Coursebook 9.03 printed p.137, updated with long unique passphrase and MFA guidance; syllabus 6.1 passwords.", content: <Slide number="05" eyebrow="PASSWORDS" sourceLabel="TEXTBOOK §9.03 · p.137" syllabusLabel="SYLLABUS 6.1" title="Long. Unique. Secret. Strengthened by another factor."><section className="se-grid four"><article className="se-card"><span>LONG</span><p>more possible guesses</p></article><article className="se-card"><span>UNIQUE</span><p>one breach does not unlock every service</p></article><article className="se-card"><span>PROTECTED</span><p>never share; store as salted hashes server-side</p></article><article className="se-card"><span>MULTI-FACTOR</span><p>stolen password alone is insufficient</p></article></section><p className="se-note">Exam focus: explain how a measure <strong>reduces a named risk</strong>; avoid claiming any password is “unhackable”.</p></Slide> },
    { time: "6 min", focus: "Organise authentication evidence into knowledge, possession and inherence.", prompt: "Classify a password, phone token and fingerprint; design two-factor authentication.", source: "Syllabus 6.1 authentication techniques; Coursebook 9.03 printed pp.137–138.", content: <Slide number="06" eyebrow="AUTHENTICATION FACTORS" sourceLabel="TEXTBOOK §9.03 · pp.137–138" syllabusLabel="SYLLABUS 6.1" title="Two factors means two different evidence categories."><section className="se-factor-row"><article><span>1</span><h3>Something you know</h3><p>Password, PIN or passphrase.</p></article><article><span>2</span><h3>Something you have</h3><p>Security token, registered phone or smart card.</p></article><article><span>3</span><h3>Something you are</h3><p>Fingerprint, face, iris or another biometric measurement.</p></article></section></Slide> },
    { time: "6 min", focus: "Evaluate biometric authentication rather than treating it as infallible.", prompt: "Why can a biometric template be more difficult to recover from than a password?", source: "Coursebook 9.03 printed p.138; syllabus 6.1 biometrics.", content: <Slide number="07" eyebrow="BIOMETRICS" sourceLabel="TEXTBOOK §9.03 · p.138" syllabusLabel="SYLLABUS 6.1" title="Convenient evidence—with measurement error and privacy costs."><section className="se-compare"><div><b>PROPERTY</b><b>VALUE</b><b>LIMIT / RISK</b></div><div><b>Tied to user</b><span>harder to share or forget</span><span>can sometimes be copied/spoofed</span></div><div><b>Measured match</b><span>fast local authentication</span><span>false accept / false reject</span></div><div><b>Persistent trait</b><span>no memorisation</span><span>cannot simply be changed after template theft</span></div></section></Slide> },
    { time: "6 min", focus: "Explain a digital signature as origin/integrity evidence, not secrecy.", prompt: "Which key is used by the sender and what does the receiver compare?", source: "Syllabus 6.1 digital signatures; Coursebook 9.03 printed p.138; 9618/13 M/J 2023 Q6(a).", content: <Slide number="08" eyebrow="DIGITAL SIGNATURE" sourceLabel="TEXTBOOK p.138 + 9618/13 M/J 2023" syllabusLabel="SYLLABUS 6.1" title="Sign a digest; verify origin and change."><section className="se-signature"><article><h3>Sender</h3><ol><li>Hash document → digest.</li><li>Sign/encrypt digest with private key.</li><li>Send document + signature.</li></ol></article><i>⇄</i><article><h3>Receiver</h3><ol><li>Verify/decrypt signature with public key.</li><li>Hash received document.</li><li>Compare digests.</li></ol></article></section><p className="se-warning">A digital signature supports <strong>authenticity and integrity</strong>. It does not make the document secret.</p></Slide> },
    { time: "6 min", focus: "Describe firewall operation and its boundary.", prompt: "Give one rule a school firewall might apply and one threat it cannot solve alone.", source: "Coursebook 9.03 printed p.138; syllabus 6.1 firewall, clarified as traffic filtering.", content: <Slide number="09" eyebrow="FIREWALL" sourceLabel="TEXTBOOK §9.03 · p.138" syllabusLabel="SYLLABUS 6.1" title="Inspect network traffic; apply rules; allow or block."><section className="se-flow"><span>INCOMING /<br />OUTGOING TRAFFIC</span><i>→</i><span>INSPECT ADDRESS,<br />PORT, PROTOCOL</span><i>→</i><span>COMPARE WITH<br />RULES / STATE</span><i>→</i><span>ALLOW, BLOCK<br />AND LOG</span></section><p className="se-warning">A firewall is a boundary control—not a cure for unsafe attachments, trusted insiders or a user who gives away credentials.</p></Slide> },
    { time: "5 min", focus: "Describe anti-virus and anti-spyware as endpoint detection and response.", prompt: "Why must detection data and software be updated?", source: "Coursebook 9.03 printed p.138; syllabus 6.1 anti-virus and anti-spyware.", content: <Slide number="10" eyebrow="ANTI-VIRUS + ANTI-SPYWARE" sourceLabel="TEXTBOOK §9.03 · p.138" syllabusLabel="SYLLABUS 6.1" title="Detect, block, quarantine or remove."><section className="se-grid four"><article className="se-card"><span>SCAN</span><p>files, memory, downloads and behaviour</p></article><article className="se-card"><span>COMPARE</span><p>known signatures and suspicious patterns</p></article><article className="se-card"><span>RESPOND</span><p>block, isolate/quarantine or delete</p></article><article className="se-card"><span>UPDATE</span><p>recognise newly discovered threats</p></article></section></Slide> },
    { time: "7 min", focus: "Explain encryption from plaintext through key and ciphertext to decryption.", prompt: "What exactly becomes useless to an interceptor, and under what condition?", source: "Coursebook 9.04 printed pp.139–140; syllabus 6.1 encryption; 9618/12 M/J 2024 Q3(a)(ii).", content: <Slide number="11" eyebrow="ENCRYPTION" sourceLabel="TEXTBOOK §9.04 · pp.139–140" syllabusLabel="SYLLABUS 6.1" title="Protect content when storage or transmission is exposed."><section className="se-flow"><span>PLAINTEXT<br />READABLE DATA</span><i>→</i><span>ALGORITHM<br />+ KEY</span><i>→</i><span>CIPHERTEXT<br />UNREADABLE</span><i>→</i><span>CORRECT KEY<br />DECRYPTS</span></section><p className="se-note">An interceptor may still copy the ciphertext, but without the correct key should not understand the original data. Key protection is therefore part of the control.</p></Slide> },
    { time: "6 min", focus: "Prevent the common confusion between encryption, access rights and digital signatures.", prompt: "Choose the control for: hide content, restrict editing, detect alteration.", source: "Syllabus 6.1 encryption, access rights and digital signatures; Coursebook 9.03–9.04.", content: <Slide number="12" eyebrow="THREE CONTROLS—THREE JOBS" sourceLabel="TEXTBOOK §§9.03–9.04" syllabusLabel="SYLLABUS 6.1" title="Confidentiality, permission and evidence of change."><section className="se-compare four"><div><b>CONTROL</b><b>PRIMARY QUESTION</b><b>HOW</b><b>LIMIT</b></div><div><b>Encryption</b><span>Can an interceptor read it?</span><span>ciphertext + key</span><span>does not decide legitimate permissions</span></div><div><b>Access rights</b><span>May this account read/write?</span><span>authorisation rules</span><span>stolen privileged account can misuse rights</span></div><div><b>Digital signature</b><span>Who signed it; did it change?</span><span>hash/digest + key pair</span><span>does not provide secrecy</span></div></section></Slide> },
    { time: "8 min", focus: "Practise the full five-mark digital-signature chain and a protection program.", prompt: "Write the sender and receiver stages in order; self-mark only after all verbs are present.", source: "Adapted from 9618/13 M/J 2023 Q6(a)–(b), checked against the published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 7 MARKS" sourceLabel="9618/13 M/J 2023 · Q6(a)–(b)" syllabusLabel="SYLLABUS 6.1 — EXAM PRACTICE" title="Authenticate a document; describe one protective program." className="slide--se-paper"><section className="se-paper-grid"><article><span>5 MARKS</span><p>Explain the sender/receiver stages of a <strong>digital signature</strong>.</p></article><article><span>2 MARKS</span><p>Name and describe one <strong>protection program</strong>.</p></article></section><ExamReveal><p>Hash document → digest; sign/encrypt digest with sender&apos;s private key; send both; receiver verifies/decrypts with public key; rehashes and compares. Program example: anti-virus scans using updated signatures/behaviour and quarantines threats, or firewall filters traffic using rules.</p></ExamReveal><small className="se-source-line">Concise adaptation of 9618/13 M/J 2023 Q6(a)–(b); original allocation [5 + 2].</small></Slide> },
    { time: "9 min", focus: "Design a layered response for a realistic school deployment.", prompt: "Teams must assign one control to each point and state its limit.", source: "Syllabus 6.1 measures from stand-alone PC to network; Coursebook 9.03–9.04.", content: <Slide number="14" eyebrow="DESIGN CLINIC · SCHOOL NETWORK" sourceLabel="TEXTBOOK §§9.03–9.04 · APPLICATION" syllabusLabel="SYLLABUS 6.1" title="Protect a laptop, network, account and examination file."><section className="se-grid four"><article className="se-card"><span>LOGIN</span><h3>Stolen password</h3><p>Choose identity evidence and justify it.</p></article><article className="se-card"><span>NETWORK</span><h3>Unknown connection</h3><p>Write one filtering rule and limit.</p></article><article className="se-card"><span>ENDPOINT</span><h3>Malicious download</h3><p>Describe detection and response.</p></article><article className="se-card"><span>FILE</span><h3>Laptop stolen</h3><p>Protect content and editing rights.</p></article></section></Slide> },
    { time: "5 min", focus: "Close with control selection and non-absolute language.", prompt: "Students answer all three in one minute, then compare verbs.", source: "Syllabus 6.1 lesson synthesis; Coursebook 9.03–9.04.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK §§9.03–9.04 · REVIEW" syllabusLabel="SYLLABUS 6.1" title="Choose; explain; qualify."><section className="se-exit"><article><span>1 · CHOOSE</span><p>Which control limits a pupil to read-only access?</p></article><article><span>2 · EXPLAIN</span><p>How does ciphertext protect an intercepted file?</p></article><article><span>3 · QUALIFY</span><p>Why can a firewall never be the only layer?</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="30" slides={slides} homework={<HomeworkSheet lessonNumber="30" title="Layered Security: Authentication, Firewalls, Encryption and Access Rights" marks={30} minutes={45} syllabusLabel="SYLLABUS 6.1" sourceLabel="TEXTBOOK CH.9 · pp.137–140 + PAPER 1" instructions="For every protective measure, describe its action, connect that action to a named risk and avoid absolute claims. The authentic digital-signature question uses the published five-stage marking chain." sections={homeworkSections} challenge={{ id: "l30-challenge", prompt: <p><Mark>CHALLENGE</Mark> A signed document is sent without encryption. State what a successful signature check proves and what it does not prove.</p>, answer: <p>It supports that the signature was produced with the sender&apos;s corresponding private key and that the received document matches the signed digest, so origin/authenticity and integrity are supported. It does <strong>not</strong> prove confidentiality: anyone able to access the unencrypted document may read it.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 6.1, Coursebook Chapter 9 printed pp.137–140, and the published 2023–2024 Paper 1 questions and mark schemes." sourceDetail="Core: user accounts, passwords, biometrics, digital signatures, firewall, anti-virus, anti-spyware, encryption and access rights; distinguish authentication, authorisation, confidentiality and integrity. Authentic anchor: 9618/13 M/J 2023 Q6(a)–(b) [5 + 2]. Advanced PKI, certificate chains and cryptographic mathematics are outside this AS lesson." />;
}
