"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip, WorkedBoard } from "../../_components/a2-theory-lesson";
import { StackMachine } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Interpreter and compiler stages", subtitle: "Use the named syllabus stages precisely", marks: 10,
    questions: [
      { id: "a2-20-1", marks: 3, lines: 6, prompt: <><b>Explain how an interpreter executes a program</b> without producing a saved translated version.</>, answer: <p>It reads/checks a source statement <em>[1]</em>, translates and executes it immediately before continuing <em>[1]</em>; translation is repeated for loops and on each later run because no separate complete executable/object-code version is saved <em>[1]</em>.</p> },
      { id: "a2-20-2", marks: 3, lines: 6, prompt: <><b>Describe lexical analysis.</b></>, answer: <p>Source characters are grouped into lexemes <em>[1]</em> and classified as tokens such as keyword, identifier, operator or literal <em>[1]</em>; comments/unnecessary whitespace are removed and identifier information may be entered in the symbol table <em>[1]</em>.</p> },
      { id: "a2-20-3", marks: 4, lines: 7, prompt: <><b>Describe syntax analysis, code generation and optimisation.</b></>, answer: <p>Syntax analysis checks the token sequence against grammar and builds a parse structure/reports syntax errors <em>[2]</em>. Code generation produces target/object code <em>[1]</em>. Optimisation improves time or space efficiency without changing program behaviour <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Grammar and BNF", subtitle: "Read alternatives, sequence and repetition", marks: 10,
    questions: [
      { id: "a2-20-4", marks: 3, lines: 5, prompt: <><b>State the meaning of</b> <code>&lt;digit&gt;</code>, <code>::=</code> and <code>|</code> in BNF.</>, answer: <p><code>&lt;digit&gt;</code> is a non-terminal/syntactic category <em>[1]</em>; <code>::=</code> means “is defined as” <em>[1]</em>; <code>|</code> separates alternatives <em>[1]</em>.</p> },
      { id: "a2-20-5", marks: 3, lines: 6, prompt: <><b>Write BNF for an operator</b> that is +, −, × or ÷, and an unsigned digit from 0 to 3.</>, answer: <p><code>&lt;operator&gt; ::= + | - | * | /</code> <em>[1]</em>; <code>&lt;digit&gt; ::= 0 | 1 | 2 | 3</code> <em>[1]</em>; use of non-terminal brackets, definition symbol and alternatives is syntactically consistent <em>[1]</em>.</p> },
      { id: "a2-20-6", marks: 4, lines: 7, prompt: <><b>Use recursive BNF to define a number containing one or more digits.</b> Explain why an empty number is impossible.</>, answer: <p><code>&lt;number&gt; ::= &lt;digit&gt; | &lt;digit&gt;&lt;number&gt;</code> <em>[2]</em>. The first alternative is the base case containing one digit <em>[1]</em>; there is no empty alternative, so every derivation produces at least one digit <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Reverse Polish Notation", subtitle: "Convert, trace the stack and preserve operand order", marks: 10,
    questions: [
      { id: "a2-20-7", marks: 3, lines: 6, prompt: <><b>Give two benefits of RPN</b> and identify the data structure used to evaluate it.</>, answer: <p>Operators follow their operands, so brackets are unnecessary <em>[1]</em> and there is no precedence ambiguity/the evaluation order is explicit <em>[1]</em>. A stack is used <em>[1]</em>.</p> },
      { id: "a2-20-8", marks: 3, lines: 6, prompt: <><b>Convert</b> <code>(A + B) × (C − D)</code> <b>to RPN and outline its evaluation.</b></>, answer: <p><code>A B + C D - *</code> <em>[1]</em>. Push operands; on each operator pop right then left, calculate and push the result <em>[1]</em>; a valid complete expression leaves one value on the stack <em>[1]</em>.</p> },
      { id: "a2-20-9", marks: 4, lines: 8, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Convert (7 − 2 + 8) / (9 − 5) to RPN and evaluate it.</b></p><p>Adapted from 9618/32 M/J 2024 Q5(a). [4 adapted marks]</p></>, answer: <p>The numerator becomes <code>7 2 - 8 +</code> <em>[1]</em>; denominator becomes <code>9 5 -</code> <em>[1]</em>; complete RPN is <code>7 2 - 8 + 9 5 - /</code> <em>[1]</em>; value is <code>13 / 4 = 3.25</code> <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson20Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Connect human-readable source to execution.", prompt: "What must translation software preserve while changing representation?", source: "2027–2029 syllabus 16.2; coursebook Chapter 20 printed pp.375–382.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch20" syllabusLabel="SYLLABUS 16.2" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 20 · 90 MINUTES</span><h1>Read the grammar.<br /><em>Build the meaning.</em></h1><p>interpreter · compiler stages · syntax diagrams · BNF · RPN</p></div><div className="a2-at-hero" role="img" aria-label="Source code passes through translation stages"><strong>TRANSLATION</strong><span>TOKENS</span><span>GRAMMAR</span><span>OBJECT CODE</span><span>RPN STACK</span></div></section></Slide> },
    { time: "5 min", focus: "Map the complete current-syllabus translation scope.", prompt: "Which four compiler stages are explicitly named?", source: "Official 2027–2029 syllabus p.35.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.35" syllabusLabel="16.2 · REQUIRED" title="Execution, translation, grammar and expression evaluation form one pipeline." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "EXECUTE", title: "Interpreter", body: "No saved complete translated version." }, { eyebrow: "COMPILE", title: "Four stages", body: "Lexical, syntax, generation, optimisation." }, { eyebrow: "DESCRIBE", title: "Grammar", body: "Syntax diagrams and BNF." }, { eyebrow: "EVALUATE", title: "RPN", body: "Postfix expression + stack." }]} /></Slide> },
    { time: "5 min", focus: "Explain interpreter operation at statement level.", prompt: "What work repeats when the program runs again?", source: "Coursebook §20.06 pp.375–376; 9618/31 M/J 2021 Q3(b).", content: <Slide number="03" eyebrow="INTERPRETER" sourceLabel="9618/31 M/J 2021 · Q3(b)" syllabusLabel="16.2 · EXECUTE" title="Read, check, translate and execute—then repeat." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "READ", title: "Next source statement" }, { eyebrow: "CHECK", title: "Report an error here" }, { eyebrow: "TRANSLATE", title: "Create executable action" }, { eyebrow: "EXECUTE", title: "Perform it immediately" }]} /></Slide> },
    { time: "6 min", focus: "Compare interpreter and compiler consequences.", prompt: "Which is faster for repeated execution after translation?", source: "Coursebook §20.06 pp.375–376.", content: <Slide number="04" eyebrow="TWO WORKFLOWS" sourceLabel="TEXTBOOK pp.375–376" syllabusLabel="16.2 · INTERPRETER" title="The key distinction is whether a separate translated program is produced." className="a2-slide a2-at-slide"><CompareTable headers={["Interpreter", "Compiler"]} rows={[["translates and executes as it proceeds", "translates the complete source program"], ["no separate complete translated version saved", "produces target/object code"], ["reports error at relevant statement; can stop there", "reports errors after analysis/translation pass"], ["translation repeats on later runs", "translated code can run repeatedly"], ["usually slower execution", "compiled program usually executes faster"]]} /></Slide> },
    { time: "6 min", focus: "Turn character sequences into token categories.", prompt: "In total = price + 7, which are lexemes and which are token types?", source: "Coursebook lexical analysis pp.376–377.", content: <Slide number="05" eyebrow="LEXICAL ANALYSIS" sourceLabel="TEXTBOOK pp.376–377" syllabusLabel="16.2 · COMPILATION STAGE 1" title="A lexeme is the source spelling; a token is its category." className="a2-slide a2-at-slide"><CompareTable headers={["Lexeme", "Token category"]} rows={[["total", "IDENTIFIER"], ["=", "ASSIGNMENT_OPERATOR"], ["price", "IDENTIFIER"], ["+", "ARITHMETIC_OPERATOR"], ["7", "INTEGER_LITERAL"]]} /></Slide> },
    { time: "6 min", focus: "Explain lexical outputs and symbol-table purpose.", prompt: "Why is the symbol table not simply a list of tokens?", source: "Coursebook pp.376–377.", content: <Slide number="06" eyebrow="TOKENS + SYMBOL TABLE" sourceLabel="TEXTBOOK pp.376–377" syllabusLabel="16.2 · LEXICAL ANALYSIS" title="Tokens simplify parsing; the symbol table records identifier attributes." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "REMOVE", title: "Noise", body: "Ignore comments and unnecessary whitespace." }, { eyebrow: "EMIT", title: "Token stream", body: "Categories consumed by the parser." }, { eyebrow: "RECORD", title: "Identifiers", body: "Name, type, scope and address information as available." }]} /></Slide> },
    { time: "6 min", focus: "Explain syntax analysis as grammar checking.", prompt: "Why can every token be valid but their order still be invalid?", source: "Coursebook syntax analysis pp.377–378; 9618/32 O/N 2022 Q2.", content: <Slide number="07" eyebrow="SYNTAX ANALYSIS" sourceLabel="9618/32 O/N 2022 · Q2" syllabusLabel="16.2 · COMPILATION STAGE 2" title="The parser checks token structure against the language grammar." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "INPUT", title: "Token stream" }, { eyebrow: "GRAMMAR", title: "Match productions" }, { eyebrow: "OUTPUT", title: "Parse tree / structure" }, { eyebrow: "FAIL", title: "Report syntax error" }]} /></Slide> },
    { time: "6 min", focus: "Place the four named stages in order.", prompt: "Which stage may improve code but must not alter meaning?", source: "Syllabus p.35; 9618/31 O/N 2022 Q4.", content: <Slide number="08" eyebrow="COMPILER PIPELINE" sourceLabel="9618/31 O/N 2022 · Q4" syllabusLabel="16.2 · FOUR STAGES" title="Analyse form first; generate and improve target code second." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "01", title: "Lexical analysis", body: "lexemes → tokens" }, { eyebrow: "02", title: "Syntax analysis", body: "tokens → parse structure" }, { eyebrow: "03", title: "Code generation", body: "target/object code" }, { eyebrow: "04", title: "Optimisation", body: "same behaviour; less time/space" }]} /></Slide> },
    { time: "6 min", focus: "Keep coursebook supporting stages outside the named core list.", prompt: "What extra question does semantic analysis ask?", source: "Coursebook pp.377–379; current syllabus p.35.", content: <Slide number="09" eyebrow="CORE + SUPPORTING DETAIL" sourceLabel="TEXTBOOK pp.377–379" syllabusLabel="16.2 · EXAM BOUNDARY" title="The coursebook adds useful detail; the syllabus names four core stages." className="a2-slide a2-at-slide"><CompareTable headers={["Named in syllabus", "Useful coursebook support"]} rows={[["lexical analysis", "symbol-table creation/update"], ["syntax analysis", "semantic/type checks and intermediate form"], ["code generation", "target instruction selection"], ["optimisation", "remove redundancy; improve time/space"]]} /></Slide> },
    { time: "6 min", focus: "Read a syntax diagram from entry to exit.", prompt: "What visual pattern represents an alternative and what represents repetition?", source: "Coursebook grammar and syntax diagrams pp.378–379.", content: <Slide number="10" eyebrow="SYNTAX DIAGRAMS" sourceLabel="TEXTBOOK pp.378–379" syllabusLabel="16.2 · GRAMMAR" title="Follow arrows: sequence moves forward, branches choose, loops repeat." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "ENTRY", title: "letter" }, { eyebrow: "LOOP", title: "letter or digit", body: "optional return arrow means repeat" }, { eyebrow: "EXIT", title: "valid identifier" }]} /></Slide> },
    { time: "7 min", focus: "Decode BNF notation and alternatives.", prompt: "Why is the vertical bar not Boolean OR?", source: "Coursebook pp.378–379; O/N 2021 Paper 31 Q4.", content: <Slide number="11" eyebrow="BACKUS–NAUR FORM" sourceLabel="9618/31 O/N 2021 · Q4" syllabusLabel="16.2 · BNF" title="BNF names grammatical categories and defines how they are formed." className="a2-slide a2-at-slide"><CompareTable headers={["Notation", "Meaning", "Example"]} rows={[[<code key="name">&lt;name&gt;</code>, "non-terminal category", <code key="digit">&lt;digit&gt;</code>], [<code key="defines">::=</code>, "is defined as", <code key="definition">&lt;digit&gt; ::= …</code>], [<code key="alternative">|</code>, "alternative", <code key="choices">0 | 1 | 2</code>], ["adjacent items", "required sequence", <code key="sequence">&lt;letter&gt;&lt;digit&gt;</code>]]} /></Slide> },
    { time: "7 min", focus: "Use a base case and recursion to express one-or-more repetition.", prompt: "Which alternative stops the recursion?", source: "Coursebook pp.378–379; verified BNF past-paper patterns.", content: <Slide number="12" eyebrow="RECURSIVE BNF" sourceLabel="TEXTBOOK pp.378–379" syllabusLabel="16.2 · BNF" title="A recursive production can generate an unbounded sequence." className="a2-slide a2-at-slide"><WorkedBoard label="One or more digits"><p><code>&lt;number&gt; ::= &lt;digit&gt; | &lt;digit&gt;&lt;number&gt;</code></p><p>The first alternative is the <strong>base case</strong>. The second adds one digit and recurses.</p></WorkedBoard></Slide> },
    { time: "7 min", focus: "Evaluate RPN with correct operand order.", prompt: "For subtraction, which popped value is right-hand operand?", source: "Coursebook RPN pp.379–382; M/J 2021 Paper 31 Q4.", content: <Slide number="13" eyebrow="RPN STACK MACHINE" sourceLabel="TEXTBOOK pp.379–382" syllabusLabel="16.2 · RPN" title="Operators follow operands, so precedence and brackets are unnecessary." className="a2-slide a2-at-slide"><StackMachine stack={[5, 2]} operation="5 − 2" result={3} /></Slide> },
    { time: "8 min", focus: "Convert and evaluate an authentic RPN expression.", prompt: "Build each sub-expression before appending its operator.", source: "Adapted from Cambridge 9618/32 M/J 2024 Q5(a).", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/32 M/J 2024 · Q5(a)" syllabusLabel="16.2 · 5 MARKS" title="Postfix records the parse tree in evaluation order." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/32 M/J 2024 · Q5(a) · ADAPTED" marks={5} prompt={<p>Convert <code>(7 − 2 + 8) / (9 − 5)</code> to RPN. Then evaluate it, showing the two sub-expression results. [5]</p>} answer={<ul><li>Numerator: <code>7 2 - 8 +</code> → 13. [2]</li><li>Denominator: <code>9 5 -</code> → 4. [1]</li><li>Complete: <code>7 2 - 8 + 9 5 - /</code>. [1]</li><li>Result: 3.25. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve the whole translation chain.", prompt: "Students distinguish lexeme/token and state the RPN pop order.", source: "Syllabus 16.2 synthesis; coursebook Chapter 20 pp.375–382.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch20 · SYLLABUS p.35" syllabusLabel="16.2 · CHAPTER 16 CLOSE" title="Analyse source, describe grammar, then evaluate without ambiguity." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>INTERPRET</span><p>Translate and execute as needed.</p></article><article><span>COMPILE</span><p>Lexical → syntax → generate → optimise.</p></article><article><span>GRAMMAR</span><p>Syntax diagram or BNF.</p></article><article><span>RPN</span><p>Operands first; stack evaluation.</p></article></section><div className="homework-callout"><b>HOMEWORK 20</b><span>30 marks · translation, BNF and RPN</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="20" title="Translation software, grammar and RPN" syllabusLabel="SYLLABUS 16.2" sourceLabel="TEXTBOOK Ch20 · pp.375–382" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 16.2 p.35 · endorsed coursebook Chapter 20 printed pp.375–382 · verified 2021–2024 Paper 3 questions and mark schemes" sourceDetail="The lesson covers interpreter operation, the four named compilation stages, syntax diagrams, BNF and stack-based RPN evaluation. Semantic analysis is identified as useful coursebook support, not substituted for a named syllabus stage." />;
}
