"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l18-reveal-${id}`;
  return <div className="pc-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className={visible ? "pc-reveal__panel visible" : "pc-reveal__panel"} hidden={!visible}>{children}</div></div>;
}

function BusDiagram() {
  return <div className="pc-bus-diagram" role="img" aria-label="CPU, memory and input output connected by address, data and control buses"><div className="pc-bus-nodes"><b>CPU</b><b>MEMORY</b><b>INPUT / OUTPUT</b></div><div className="pc-bus-line address"><span>ADDRESS BUS</span><i>→</i></div><div className="pc-bus-line data"><span>DATA BUS</span><i>↔</i></div><div className="pc-bus-line control"><span>CONTROL BUS</span><i>↔</i></div></div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "The system bus", subtitle: "Name what each bus carries and its exam-model direction", marks: 10,
    questions: [
      { id: "l18-1", marks: 6, lines: 5, prompt: <><b>Describe the address bus, data bus and control bus.</b><p>For each, state what it carries and its direction.</p></>, answer: <p><b>Address:</b> carries the address of a memory/I/O location from the CPU; unidirectional. <b>Data:</b> carries data/instructions between CPU, memory and I/O; bidirectional. <b>Control:</b> carries command, timing and status signals; bidirectional. <em>[2 each]</em></p> },
      { id: "l18-2", marks: 4, lines: 4, prompt: <><b>Explain one effect of increasing address-bus width and one effect of increasing data-bus width.</b></>, answer: <p>An n-bit address bus can identify <b>2ⁿ locations</b>, so a wider address bus allows more memory locations to be addressed. A wider data bus transfers more bits in one operation, reducing the number of transfers for the same data and potentially increasing throughput. <em>[2 + 2]</em></p> },
    ],
  },
  {
    code: "B", title: "Performance and ports", subtitle: "Make a cause-and-effect link for every factor", marks: 10,
    questions: [
      { id: "l18-3", marks: 4, lines: 4, prompt: <><b>Explain how clock speed and cache memory can affect computer performance.</b></>, answer: <p>A higher clock speed allows more F-E cycles each second, so more instructions/data may be processed. A larger/effective cache can hold more frequently used data/instructions close to the CPU, reducing access to slower RAM. <em>[2 each]</em></p> },
      { id: "l18-4", marks: 3, lines: 3, prompt: <><b>Identify the most suitable syllabus port for each connection.</b><p>Digital monitor with sound · older analogue monitor · keyboard</p></>, answer: <p><b>HDMI</b> · <b>VGA</b> · <b>USB</b>. <em>[1 each]</em></p> },
      { id: "l18-5", marks: 3, lines: 4, prompt: <><b>Explain why doubling the number of processor cores does not always double performance.</b></>, answer: <p>Software may not divide into parallel tasks; some instructions remain sequential; cores share resources such as cache/memory buses; another component may be the bottleneck. <em>[Any three]</em></p> },
    ],
  },
  {
    code: "C", title: "Authentic Paper 1 practice", subtitle: "Four recent mark-scheme patterns", marks: 10,
    questions: [
      { id: "l18-6", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain how the CU and system clock work together.</b><p>Adapted from 9618/13 M/J 2025 Q2(a)(i). [2]</p></>, answer: <p>The clock produces timing signals; the CU uses each timing signal to synchronise processor activity by sending commands/signals along the control bus. <em>[2]</em></p> },
      { id: "l18-7", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Describe one benefit of cache memory.</b><p>Adapted from 9618/13 M/J 2025 Q2(b). [2]</p></>, answer: <p>Cache is fast memory close to the CPU that stores frequently used data/instructions, so they can be accessed faster than from RAM. <em>[2 linked points]</em></p> },
      { id: "l18-8", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain how HDMI connects a peripheral.</b><p>Adapted from 9618/13 M/J 2025 Q2(c). [2]</p></>, answer: <p>HDMI can transmit digital audio and video through one cable and has high bandwidth; the data is sent as a stream of uncompressed digital signals. <em>[Any two]</em></p> },
      { id: "l18-9", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain why a higher clock speed and a larger cache can improve performance.</b><p>Adapted from 9618/12 O/N 2025 Q3(c). [4]</p></>, answer: <p>Higher clock speed means more F-E cycles per second, allowing more instructions/data to be processed. Larger cache stores more frequently used instructions/data, reducing access to slower RAM. <em>[2 + 2]</em></p> },
    ],
  },
];

export default function Lesson18Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "3 min", focus: "Frame the lesson around movement and speed: how components communicate and why some systems finish sooner.", prompt: "Ask: a fast CPU is waiting—what might it be waiting for?", source: "Syllabus 4.1 p.19; Coursebook 5.03-5.05, printed pp.83-86 / PDF pp.90-93.", content: <Slide number="01" eyebrow="CHAPTER 4 · PROCESSOR FUNDAMENTALS" sourceLabel="TEXTBOOK CH.5 · pp.83-86" syllabusLabel="SYLLABUS 4.1 · p.19" className="slide--pc-title"><section className="pc-title-grid"><div><span>LESSON 18 · 90 MINUTES</span><h1>Move the bits.<br /><em>Find the bottleneck.</em></h1><p>Follow addresses, data and control signals—then judge performance factors and ports.</p></div><BusDiagram /></section></Slide> },
    { time: "4 min", focus: "Make the three lesson strands explicit.", prompt: "Students predict which strand explains capacity, throughput and connectivity.", source: "Syllabus 4.1 p.19.", content: <Slide number="02" eyebrow="TODAY'S SYLLABUS ROUTE" sourceLabel="OFFICIAL SYLLABUS · p.19" syllabusLabel="SYLLABUS 4.1" title="Connect → transfer → perform." className="slide--pc-route"><section className="pc-route-grid"><article><b>1</b><span>BUSES</span><p>address · data · control</p></article><article><b>2</b><span>PERFORMANCE</span><p>cores · width · clock · cache</p></article><article><b>3</b><span>PORTS</span><p>USB · HDMI · VGA</p></article></section><p className="pc-note">Exam answers must link each feature to what changes inside the system.</p></Slide> },
    { time: "6 min", focus: "Show the three buses as a coordinated system rather than three disconnected definitions.", prompt: "Which bus identifies where, which carries what, and which says what action to take?", source: "Coursebook 5.03, printed pp.83-84 / PDF pp.90-91.", content: <Slide number="03" eyebrow="THE SYSTEM BUS" sourceLabel="TEXTBOOK 5.03 · pp.83-84" syllabusLabel="SYLLABUS 4.1" title="Three shared pathways connect CPU, memory and I/O." className="slide--pc-buses"><BusDiagram /><section className="pc-bus-words"><b>WHERE</b><b>WHAT</b><b>WHEN / HOW</b></section></Slide> },
    { time: "6 min", focus: "Teach address-bus purpose and the simplified exam direction.", prompt: "Why can memory not send an address back on this bus in the syllabus model?", source: "Coursebook 5.03, printed p.84 / PDF p.91.", content: <Slide number="04" eyebrow="ADDRESS BUS" sourceLabel="TEXTBOOK 5.03 · p.84" syllabusLabel="SYLLABUS 4.1" title="The CPU selects one memory or I/O location." className="slide--pc-bus-focus"><section className="pc-one-bus address"><b>CPU / MAR</b><i>ADDRESS 0101 1010 →</i><b>MEMORY OR I/O</b></section><div className="pc-equation"><strong>n address lines</strong><span>→</span><strong>2ⁿ addressable locations</strong></div><p className="pc-note">Exam model: the address bus is unidirectional from the CPU.</p></Slide> },
    { time: "6 min", focus: "Teach data-bus content, direction and the inclusion of fetched instructions.", prompt: "Can an instruction travel on the data bus? Explain.", source: "Coursebook 5.03, printed p.84 / PDF p.91.", content: <Slide number="05" eyebrow="DATA BUS" sourceLabel="TEXTBOOK 5.03 · p.84" syllabusLabel="SYLLABUS 4.1" title="Data—including an instruction—can travel both ways." className="slide--pc-bus-focus"><section className="pc-one-bus data"><b>CPU / MDR</b><i>← DATA OR INSTRUCTION →</i><b>MEMORY OR I/O</b></section><section className="pc-two-examples"><p><b>READ</b> memory → CPU</p><p><b>WRITE</b> CPU → memory</p></section><p className="pc-note">The MDR buffers what crosses the CPU–memory boundary.</p></Slide> },
    { time: "6 min", focus: "Separate control signals from addresses and payload data.", prompt: "Classify read, write, interrupt and clock as control signals.", source: "Coursebook 5.03, printed p.84 / PDF p.91.", content: <Slide number="06" eyebrow="CONTROL BUS" sourceLabel="TEXTBOOK 5.03 · p.84" syllabusLabel="SYLLABUS 4.1" title="Signals coordinate the transfer." className="slide--pc-bus-focus"><section className="pc-one-bus control"><b>CONTROL UNIT</b><i>← READ · WRITE · CLOCK · INTERRUPT →</i><b>MEMORY OR I/O</b></section><p className="pc-takeaway">The control bus is <b>bidirectional overall</b>: different signal lines can travel in different directions.</p></Slide> },
    { time: "7 min", focus: "Distinguish address width from data width using powers of two and transfer size.", prompt: "What changes when 16 address lines become 32? What changes when a data bus doubles?", source: "Coursebook 5.04, printed p.85 / PDF p.92.", content: <Slide number="07" eyebrow="BUS WIDTH CHANGES DIFFERENT THINGS" sourceLabel="TEXTBOOK 5.04 · p.85" syllabusLabel="SYLLABUS 4.1" title="Address width changes reach; data width changes each transfer." className="slide--pc-width"><section className="pc-width-compare"><article><b>ADDRESS BUS</b><strong>2ⁿ locations</strong><p>16 lines → 65,536 locations</p></article><article><b>DATA BUS</b><strong>n bits per transfer</strong><p>wider bus → fewer transfers for a word</p></article></section><div className="pc-caution"><b>DO NOT CONFUSE</b><p>Bus width is not one single quantity: always name the bus.</p></div></Slide> },
    { time: "7 min", focus: "Explain clock speed through cycles, not vague claims about speed.", prompt: "Turn 3.2 GHz into a sentence without claiming one instruction per cycle.", source: "Coursebook 5.04, printed p.85 / PDF p.92; Syllabus 4.1 p.19.", content: <Slide number="08" eyebrow="PERFORMANCE · CLOCK SPEED" sourceLabel="TEXTBOOK 5.04 · p.85" syllabusLabel="SYLLABUS 4.1" title="A faster clock offers more timing cycles each second." className="slide--pc-performance"><section className="pc-meter"><span>1.8 GHz</span><i><b /></i><span>3.2 GHz</span></section><p className="pc-big-statement">More cycles per second <b>can</b> allow more instructions or data to be processed.</p><p className="pc-note">Do not write “3.2 billion instructions per second”: instructions may require different numbers of cycles.</p></Slide> },
    { time: "6 min", focus: "Explain cache as a latency bridge between CPU and RAM.", prompt: "Why does frequently used matter more than simply saying cache is fast?", source: "Coursebook 5.04, printed p.85 / PDF p.92; 9618/13 M/J 2025 Q2(b) mark scheme.", content: <Slide number="09" eyebrow="PERFORMANCE · CACHE" sourceLabel="TEXTBOOK 5.04 · p.85" syllabusLabel="SYLLABUS 4.1" title="Cache avoids some journeys to slower RAM." className="slide--pc-cache"><section className="pc-cache-path"><b>CPU</b><i>very fast</i><strong>CACHE<br /><small>frequently used</small></strong><i>slower</i><b>RAM</b></section><p className="pc-takeaway">More useful data/instructions in cache → fewer slower RAM accesses → lower average access time.</p></Slide> },
    { time: "7 min", focus: "Treat processor type and number of cores as contextual factors, not automatic multipliers.", prompt: "Name one workload that splits well and one that remains mostly sequential.", source: "Coursebook 5.04, printed p.85 / PDF p.92; Syllabus 4.1 p.19.", content: <Slide number="10" eyebrow="PERFORMANCE · PROCESSOR AND CORES" sourceLabel="TEXTBOOK 5.04 · p.85" syllabusLabel="SYLLABUS 4.1" title="More cores help only when work can run in parallel." className="slide--pc-cores"><section className="pc-core-grid"><div><b>CORE 1</b><span>TASK A</span></div><div><b>CORE 2</b><span>TASK B</span></div><div><b>CORE 3</b><span>WAITING</span></div><div><b>CORE 4</b><span>WAITING</span></div></section><p className="pc-note">Architecture/instruction set, cache, software design, heat and shared resources all affect the result.</p></Slide> },
    { time: "7 min", focus: "Differentiate the three named ports by signal and use case.", prompt: "Students choose a port for a keyboard, modern projector and older analogue display.", source: "Coursebook 5.05, printed p.86 / PDF p.93; Syllabus 4.1 p.19.", content: <Slide number="11" eyebrow="PORTS CONNECT PERIPHERALS" sourceLabel="TEXTBOOK 5.05 · p.86" syllabusLabel="SYLLABUS 4.1" title="USB is general-purpose; HDMI and VGA specialise in display." className="slide--pc-ports"><section className="pc-port-grid"><article><span className="pc-port-icon usb" /><b>USB</b><p>serial data; many peripherals; may supply power</p></article><article><span className="pc-port-icon hdmi" /><b>HDMI</b><p>digital video + audio; high bandwidth</p></article><article><span className="pc-port-icon vga" /><b>VGA</b><p>analogue video; no audio</p></article></section><p className="pc-note">A USB drive is a storage device connected to a USB port; the bus itself is not storage.</p></Slide> },
    { time: "8 min", focus: "Apply recent Cambridge mark-scheme language to cache and HDMI.", prompt: "Four minutes individual, then reveal and underline each cause-effect link.", source: "Adapted from 9618/13 M/J 2025 Q2(b)-(c), checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/13 M/J 2025 · Q2(b-c)" syllabusLabel="SYLLABUS 4.1 — EXAM PRACTICE" title="Explain one cache benefit and how HDMI connects a monitor." className="slide--pc-paper"><section className="pc-paper-split"><p><b>2 marks</b>Describe one benefit of cache memory.</p><p><b>2 marks</b>Explain how HDMI provides the connection.</p></section><Reveal id="paper-cache" visible={revealed.has("paper-cache")} onToggle={toggleReveal}><p>Cache stores frequently used data/instructions in fast memory close to the CPU, so access is faster than RAM. HDMI carries digital audio and video in one high-bandwidth cable; data is a stream of uncompressed digital signals. <em>[Any two HDMI points]</em></p></Reveal><small>Concise adaptation of 9618/13 M/J 2025 Q2(b)-(c).</small></Slide> },
    { time: "7 min", focus: "Compare two specifications using linked explanations.", prompt: "Ban the phrase 'it is faster' unless the next clause says why.", source: "Adapted from 9618/12 O/N 2025 Q3(c), checked against published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/12 O/N 2025 · Q3(c)" syllabusLabel="SYLLABUS 4.1 — EXAM PRACTICE" title="Why do clock speed and cache size matter?" className="slide--pc-paper"><section className="pc-spec-compare"><article><b>OLD</b><strong>1.8 GHz</strong><span>16 MB cache</span></article><i>→</i><article><b>NEW</b><strong>2.3 GHz</strong><span>32 MB cache</span></article></section><Reveal id="paper-performance" visible={revealed.has("paper-performance")} onToggle={toggleReveal}><p>Higher clock speed → more F-E cycles each second → potentially more instructions/data processed. Larger cache → more frequently used instructions/data held close to CPU → fewer accesses to slower RAM.</p></Reveal><small>Adapted from 9618/12 O/N 2025 Q3(c).</small></Slide> },
    { time: "6 min", focus: "Expose common misconceptions before the exit check.", prompt: "Pairs select every false statement and repair it aloud.", source: "Syllabus-style diagnostic based on 4.1.", content: <Slide number="14" eyebrow="MISCONCEPTION CHECK" sourceLabel="SYLLABUS-STYLE ORIGINAL" syllabusLabel="SYLLABUS 4.1" title="Which claims fail the exam model?" className="slide--pc-check"><section className="pc-claim-grid"><p>Address bus is bidirectional.</p><p>Data bus carries instructions.</p><p>More cores always doubles speed.</p><p>HDMI carries digital audio and video.</p><p>VGA carries digital sound.</p><p>USB is a storage device.</p></section><Reveal id="claims" visible={revealed.has("claims")} onToggle={toggleReveal}><p><b>False:</b> address bus is one-way from CPU; core gains depend on parallel work; VGA is analogue video only; USB is an interface/bus. <b>True:</b> instructions can cross the data bus; HDMI carries digital audio and video.</p></Reveal></Slide> },
    { time: "4 min", focus: "Close with the three-bus mnemonic and transfer students into the 45-minute homework.", prompt: "Class answers together: where, what, when/how?", source: "Lesson 18 synthesis; Syllabus 4.1 p.19.", content: <Slide number="15" eyebrow="EXIT · THREE QUESTIONS" sourceLabel="LESSON 18 SYNTHESIS" syllabusLabel="SYLLABUS 4.1" title="Where? What? When and how?" className="slide--pc-exit"><section className="pc-exit-copy"><b>ADDRESS</b><i>→</i><b>DATA</b><i>→</i><b>CONTROL</b></section><div className="pc-homework-callout"><b>HOMEWORK 18</b><span>30 marks · 45 minutes · inline mark schemes</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="18" slides={slides} homework={<HomeworkSheet lessonNumber="18" title="Buses, Performance and Ports" marks={30} minutes={45} syllabusLabel="SYLLABUS 4.1 · p.19" sourceLabel="TEXTBOOK CH.5 · PRINTED pp.83-86 / PDF pp.90-93 + PAPER 1" instructions="For every performance factor, write a cause-and-effect chain. For buses, always state both what is carried and the direction used in the Cambridge model. Past-paper prompts are concise adaptations with original references." sections={homeworkSections} challenge={{ id: "l18-challenge", prompt: <p><Mark>CHALLENGE</Mark> A processor has a 24-bit address bus. How many distinct locations can it address, and why does this not state the amount of data transferred per operation?</p>, answer: <p><strong>2²⁴ = 16,777,216 locations.</strong> Address width selects locations; data transferred per operation depends on the separate data-bus width.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 4.1 p.19, Coursebook Chapter 5 printed pp.83-86 (PDF pp.90-93), and published 2025 Paper 1 questions and mark schemes." sourceDetail="Core: address, data and control buses; processor type/cores, bus width, clock speed and cache; USB, HDMI and VGA. Authentic anchors: 9618/13 M/J 2025 Q2(a)(i),(b),(c) and 9618/12 O/N 2025 Q3(c). The outdated textbook claim that USB 3.2 is the latest version is deliberately excluded; no vendor-specific speed tables are required by syllabus 4.1." />;
}
