"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip, WorkedBoard } from "../../_components/a2-theory-lesson";
import { SearchWindow } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Searching", subtitle: "Write the loop, maintain the interval, state the order", marks: 10,
    questions: [
      { id: "a2-25-1", marks: 3, lines: 8, prompt: <><b>Write pseudocode for a linear search</b> that returns the index of Target in Data[1:100], or -1 if absent.</>, answer: <pre><code>{`FOR Index ← 1 TO 100\n   IF Data[Index] = Target THEN\n      RETURN Index\n   ENDIF\nNEXT Index\nRETURN -1`}</code></pre> },
      { id: "a2-25-2", marks: 3, lines: 7, prompt: <><b>State the condition required for binary search and describe one iteration.</b></>, answer: <p>The values must be sorted in the order used by the comparisons <em>[1]</em>. Inspect the middle value <em>[1]</em>; if the target is lower/greater, discard the incompatible half and update the upper/lower boundary <em>[1]</em>.</p> },
      { id: "a2-25-3", marks: 4, lines: 10, prompt: <><b>Write the central loop of an iterative binary search</b> using Low, High and Mid.</>, answer: <pre><code>{`WHILE Low <= High\n   Mid ← (Low + High) DIV 2\n   IF Data[Mid] = Target THEN\n      RETURN Mid\n   ELSE\n      IF Data[Mid] < Target THEN\n         Low ← Mid + 1\n      ELSE\n         High ← Mid - 1\n      ENDIF\n   ENDIF\nENDWHILE`}</code></pre> },
    ],
  },
  {
    code: "B", title: "Sorting", subtitle: "Swap neighbours or insert into a sorted prefix", marks: 10,
    questions: [
      { id: "a2-25-4", marks: 3, lines: 7, prompt: <><b>Describe one pass of bubble sort and the purpose of a Swapped flag.</b></>, answer: <p>Compare adjacent pairs in order <em>[1]</em> and swap any pair in the wrong order, so the largest remaining value moves to the upper end <em>[1]</em>. If no swap occurs, the flag shows the list is already sorted and later passes can stop <em>[1]</em>.</p> },
      { id: "a2-25-5", marks: 3, lines: 7, prompt: <><b>Describe insertion sort using the terms sorted prefix, Value and shift.</b></>, answer: <p>Treat the first item as a sorted prefix and store the next item in Value <em>[1]</em>. Shift larger prefix items one position right <em>[1]</em>, then insert Value into the gap and extend the sorted prefix <em>[1]</em>.</p> },
      { id: "a2-25-6", marks: 4, lines: 10, prompt: <><b>Write pseudocode for insertion sort</b> on Data[1:n] in ascending order.</>, answer: <pre><code>{`FOR Index ← 2 TO n\n   Value ← Data[Index]\n   Position ← Index - 1\n   WHILE Position >= 1 AND Data[Position] > Value\n      Data[Position + 1] ← Data[Position]\n      Position ← Position - 1\n   ENDWHILE\n   Data[Position + 1] ← Value\nNEXT Index`}</code></pre> },
    ],
  },
  {
    code: "C", title: "Complexity and data", subtitle: "Compare growth, not one stopwatch reading", marks: 10,
    questions: [
      { id: "a2-25-7", marks: 3, lines: 6, prompt: <><b>Explain what O(log n) means for binary search performance.</b></>, answer: <p>The remaining search interval is approximately halved after each comparison <em>[1]</em>. Therefore the maximum comparisons grow logarithmically with n <em>[1]</em>; doubling n adds about one comparison rather than doubling the work <em>[1]</em>.</p> },
      { id: "a2-25-8", marks: 3, lines: 6, prompt: <><b>Compare the time and auxiliary-space complexity of iterative linear and binary search.</b></>, answer: <p>Linear search is O(n) time; iterative binary search is O(log n) time <em>[2]</em>. Both use O(1) auxiliary space because only a fixed number of variables are stored <em>[1]</em>.</p> },
      { id: "a2-25-9", marks: 4, lines: 8, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Explain two ways the input data affects sort performance, then state the worst-case time order of insertion sort.</b></p><p>Adapted from 9618/33 M/J 2025 Q12(b)–(c). [4 adapted marks]</p></>, answer: <p>More items normally require more comparisons/moves and therefore more time <em>[1]</em>. Already/nearly sorted data needs fewer shifts for insertion sort, while reverse/disordered input needs more <em>[1]</em>. Worst-case time is <code>O(n²)</code> <em>[1]</em>, meaning the dominant work grows proportionally to the square of n <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson25Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame algorithms as choices whose cost grows with input size.", prompt: "What changes when a dataset becomes ten times larger?", source: "2027–2029 syllabus 19.1 p.37; coursebook Chapter 23 printed pp.411–431.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch23" syllabusLabel="SYLLABUS 19.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 25 · 90 MINUTES</span><h1>Find it.<br /><em>Order it. Measure it.</em></h1><p>linear search · binary search · bubble · insertion · Big O</p></div><div className="a2-at-hero" role="img" aria-label="Search, sort and complexity themes"><strong>ALGORITHM CHOICE</strong><span>O(log n)</span><span>O(n)</span><span>O(n²)</span><span>SPACE</span></div></section></Slide> },
    { time: "5 min", focus: "Map the full search, sort and complexity requirement.", prompt: "Which four algorithms must candidates be able to write?", source: "Official 2027–2029 syllabus 19.1 p.37.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.37" syllabusLabel="19.1 · REQUIRED" title="Write four algorithms and compare how their resource use grows." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "SEARCH", title: "Linear", body: "Sequential checks; no sorting required." }, { eyebrow: "SEARCH", title: "Binary", body: "Sorted data; repeatedly halve." }, { eyebrow: "SORT", title: "Bubble + insertion", body: "Write and trace both." }, { eyebrow: "COMPARE", title: "Big O", body: "Time and space; n and initial order matter." }]} /></Slide> },
    { time: "5 min", focus: "Trace linear search and its stopping conditions.", prompt: "When may the algorithm stop before the final item?", source: "Coursebook §23.01 p.412; syllabus 19.1.", content: <Slide number="03" eyebrow="LINEAR SEARCH" sourceLabel="TEXTBOOK p.412" syllabusLabel="19.1 · WRITE" title="Inspect each item in sequence until the target is found or data ends." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "START", title: "Index = first position" }, { eyebrow: "COMPARE", title: "Data[Index] = Target?" }, { eyebrow: "FOUND", title: "Return Index" }, { eyebrow: "NOT YET", title: "Advance Index" }, { eyebrow: "END", title: "Return not found" }]} /></Slide> },
    { time: "6 min", focus: "Write a complete linear search with a not-found outcome.", prompt: "What should be returned if no element matches?", source: "Coursebook Chapter 13 worked search recalled; Chapter 23 §23.01.", content: <Slide number="04" eyebrow="LINEAR SEARCH · PSEUDOCODE" sourceLabel="TEXTBOOK p.412" syllabusLabel="19.1 · WRITE" title="A correct search defines both success and failure." className="a2-slide a2-at-slide"><WorkedBoard label="Function contract"><pre><code>{`FUNCTION LinearSearch(Data, Target) RETURNS INTEGER\n   FOR Index ← 1 TO LENGTH(Data)\n      IF Data[Index] = Target THEN\n         RETURN Index\n      ENDIF\n   NEXT Index\n   RETURN -1\nENDFUNCTION`}</code></pre></WorkedBoard></Slide> },
    { time: "6 min", focus: "State binary search preconditions before tracing it.", prompt: "Why is random access useful, and what condition is essential?", source: "Coursebook §23.04 pp.413–415; 9618/31 M/J 2024 Q10(a).", content: <Slide number="05" eyebrow="BINARY SEARCH · CONTRACT" sourceLabel="9618/31 M/J 2024 · Q10(a)" syllabusLabel="19.1 · CONDITION" title="The data must be sorted consistently before halves can be discarded." className="a2-slide a2-at-slide"><CompareTable headers={["Required", "Why"]} rows={[["sorted ascending or descending", "comparison identifies which half cannot contain the target"], ["known lower and upper boundaries", "defines the current candidate interval"], ["direct access to the middle item", "supports efficient midpoint inspection"], ["matching comparison direction", "updates Low or High correctly for the chosen order"]]} /></Slide> },
    { time: "6 min", focus: "Shrink the inclusive search interval without off-by-one errors.", prompt: "Target 58 is above 32: which five indices can be discarded?", source: "Coursebook binary-search worked example pp.413–415.", content: <Slide number="06" eyebrow="BINARY SEARCH · TRACE" sourceLabel="TEXTBOOK pp.413–415" syllabusLabel="19.1 · PERFORM" title="Each comparison discards the middle item or an entire incompatible half." className="a2-slide a2-at-slide"><SearchWindow /></Slide> },
    { time: "6 min", focus: "Write the binary loop using Low, High and Mid.", prompt: "Why must the updated boundary pass Mid?", source: "Coursebook §23.04 pp.413–415; 9618/31 M/J 2024 Q10(b).", content: <Slide number="07" eyebrow="BINARY SEARCH · PSEUDOCODE" sourceLabel="9618/31 M/J 2024 · Q10(b)" syllabusLabel="19.1 · WRITE" title="Move to Mid + 1 or Mid − 1, otherwise the interval may never shrink." className="a2-slide a2-at-slide"><WorkedBoard label="Ascending data"><pre><code>{`Low ← 1\nHigh ← LENGTH(Data)\nWHILE Low <= High\n   Mid ← (Low + High) DIV 2\n   IF Data[Mid] = Target THEN RETURN Mid\n   IF Data[Mid] < Target THEN\n      Low ← Mid + 1\n   ELSE\n      High ← Mid - 1\n   ENDIF\nENDWHILE\nRETURN -1`}</code></pre></WorkedBoard></Slide> },
    { time: "6 min", focus: "Relate halving to logarithmic growth.", prompt: "How many halvings reduce about 1024 sorted items to one candidate?", source: "Coursebook Big O pp.429–431; 9618/31 M/J 2024 Q10(c).", content: <Slide number="08" eyebrow="SEARCH PERFORMANCE" sourceLabel="9618/31 M/J 2024 · Q10(c)" syllabusLabel="19.1 · BIG O" title="Linear work follows n; binary work follows the number of halvings." className="a2-slide a2-at-slide"><CompareTable headers={["n", "Linear worst-case item checks", "Binary growth indicator · log₂ n"]} rows={[["16", "16", "4 halvings"], ["1,024", "1,024", "10 halvings"], ["1,048,576", "1,048,576", "20 halvings"]]} caption="A final equality/absence check may add one; Big O ignores constant differences. Doubling n adds about one binary-search step." /></Slide> },
    { time: "6 min", focus: "Trace how bubble sort moves an extreme value per pass.", prompt: "What fact becomes true at the upper boundary after a complete ascending pass?", source: "Coursebook §23.02 p.412 and earlier worked algorithm.", content: <Slide number="09" eyebrow="BUBBLE SORT" sourceLabel="TEXTBOOK p.412" syllabusLabel="19.1 · WRITE" title="Compare neighbours; swap those in the wrong order; reduce the unsorted boundary." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "COMPARE", title: "Data[i] and Data[i+1]" }, { eyebrow: "IF WRONG", title: "Swap adjacent values" }, { eyebrow: "CONTINUE", title: "Move through pass" }, { eyebrow: "FIXED", title: "Largest reaches the end" }, { eyebrow: "REPEAT", title: "Smaller unsorted region" }]} /></Slide> },
    { time: "6 min", focus: "Write an optimised bubble sort with an early-exit flag.", prompt: "What happens when a whole pass makes no swap?", source: "Coursebook §23.02; Chapter 13 bubble-sort pseudocode recalled.", content: <Slide number="10" eyebrow="BUBBLE · PSEUDOCODE" sourceLabel="TEXTBOOK p.412" syllabusLabel="19.1 · WRITE" title="The flag turns an already sorted input into a linear best case." className="a2-slide a2-at-slide"><WorkedBoard label="Ascending order"><pre><code>{`Upper ← LENGTH(Data)\nREPEAT\n   Swapped ← FALSE\n   FOR Index ← 1 TO Upper - 1\n      IF Data[Index] > Data[Index + 1] THEN\n         Temp ← Data[Index]\n         Data[Index] ← Data[Index + 1]\n         Data[Index + 1] ← Temp\n         Swapped ← TRUE\n      ENDIF\n   NEXT Index\n   Upper ← Upper - 1\nUNTIL NOT Swapped OR Upper = 1`}</code></pre></WorkedBoard></Slide> },
    { time: "7 min", focus: "Trace insertion into a sorted prefix.", prompt: "Why should values shift instead of repeatedly swapping Value?", source: "Coursebook §23.03 pp.412–413.", content: <Slide number="11" eyebrow="INSERTION SORT" sourceLabel="TEXTBOOK pp.412–413" syllabusLabel="19.1 · WRITE" title="Keep a sorted prefix; open one gap and insert the next value." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SELECT", title: "Value = next item" }, { eyebrow: "SCAN LEFT", title: "Compare with prefix" }, { eyebrow: "SHIFT", title: "Move larger items right" }, { eyebrow: "INSERT", title: "Place Value in gap" }, { eyebrow: "GROW", title: "Extend sorted prefix" }]} /></Slide> },
    { time: "7 min", focus: "Write insertion sort in the order expected by mark schemes.", prompt: "Where must Value be reinserted after the while loop?", source: "Coursebook pp.412–413; 9618/33 M/J 2025 Q12(b).", content: <Slide number="12" eyebrow="INSERTION · PSEUDOCODE" sourceLabel="9618/33 M/J 2025 · Q12(b)" syllabusLabel="19.1 · WRITE" title="Store Value, shift while larger, then insert at Position + 1." className="a2-slide a2-at-slide"><WorkedBoard label="Ascending order"><pre><code>{`FOR Index ← 2 TO n\n   Value ← Data[Index]\n   Position ← Index - 1\n   WHILE Position >= 1 AND Data[Position] > Value\n      Data[Position + 1] ← Data[Position]\n      Position ← Position - 1\n   ENDWHILE\n   Data[Position + 1] ← Value\nNEXT Index`}</code></pre></WorkedBoard></Slide> },
    { time: "7 min", focus: "Compare time and auxiliary space using dominant growth.", prompt: "Why does Big O omit constant factors and smaller terms?", source: "Coursebook §23.13 pp.429–431; syllabus 19.1.", content: <Slide number="13" eyebrow="BIG O · TIME + SPACE" sourceLabel="TEXTBOOK pp.429–431" syllabusLabel="19.1 · COMPARE" title="Big O describes how required resources grow as n grows." className="a2-slide a2-at-slide"><CompareTable headers={["Algorithm", "Time", "Auxiliary space", "Input-order effect"]} rows={[["linear search", "O(n)", "O(1)", "target position affects actual comparisons"], ["iterative binary search", "O(log n)", "O(1)", "requires sorted data"], ["bubble + early exit", "best O(n), worst O(n²)", "O(1)", "nearly sorted can stop early"], ["insertion sort", "best O(n), worst O(n²)", "O(1)", "nearly sorted needs few shifts"]]} /></Slide> },
    { time: "8 min", focus: "Write and explain the highest-yield current sort pattern.", prompt: "Secure marks for stored Value, inner loop, shifts and reinsertion.", source: "Adapted from Cambridge 9618/33 M/J 2025 Q12(b)–(c) and published mark scheme.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/33 M/J 2025 · Q12(b)–(c)" syllabusLabel="19.1 · 6 MARKS" title="Insertion sort is an algorithm plus a performance explanation." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/33 M/J 2025 · Q12(b)–(c) · ADAPTED" marks={6} prompt={<><p>Write insertion-sort pseudocode for an ascending array. Then describe two ways the data affects the routine&apos;s performance. [6]</p></>} answer={<ul><li>Store the item to insert and initialise a position in the sorted prefix. [1]</li><li>While the position is valid and its item is larger, shift that item right and decrement the position. [2]</li><li>Reinsert the stored item at Position + 1; repeat for all remaining items. [1]</li><li>A larger n normally causes more comparisons/moves. [1]</li><li>Already/nearly sorted data needs fewer shifts than disordered/reverse data. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve the four algorithms and their growth classes.", prompt: "Students state the binary precondition and one order for each algorithm.", source: "Syllabus 19.1 synthesis; coursebook Chapter 23 pp.411–431.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch23 · SYLLABUS p.37" syllabusLabel="19.1 · LESSON CLOSE" title="Correctness chooses the answer; complexity chooses the scalable method." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>LINEAR</span><p>Any order · O(n).</p></article><article><span>BINARY</span><p>Sorted · O(log n).</p></article><article><span>BUBBLE</span><p>Adjacent swaps · O(n²).</p></article><article><span>INSERTION</span><p>Sorted prefix · O(n²).</p></article></section><div className="homework-callout"><b>HOMEWORK 25</b><span>30 marks · search, sort and Big O</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="25" title="Search, sort and Big O comparison" syllabusLabel="SYLLABUS 19.1" sourceLabel="TEXTBOOK Ch23 · pp.411–431" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 19.1 p.37 · endorsed coursebook Chapter 23 printed pp.411–431 · verified 2024–2025 Paper 3 questions and mark schemes" sourceDetail="The lesson writes linear and binary search plus bubble and insertion sort, states the binary-search precondition, and compares time and auxiliary-space growth with Big O while explaining the effects of item count and initial order." />;
}
