"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l14-reveal-${id}`;
  return <div className="c3-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className={visible ? "c3-reveal__panel visible" : "c3-reveal__panel"} hidden={!visible}>{children}</div></div>;
}

function ControlLoop() {
  return <div className="c3-control-loop" role="img" aria-label="Feedback loop: sensor sends data to processor, processor sends a control signal to an actuator, actuator changes the physical system, then the sensor measures the new state"><article><span>1</span><b>SENSOR</b><p>measure state</p></article><i>→</i><article><span>2</span><b>PROCESSOR</b><p>compare with target</p></article><i>→</i><article><span>3</span><b>ACTUATOR</b><p>change the system</p></article><i>→</i><article><span>4</span><b>NEW STATE</b><p>measure again</p></article><strong>↩ FEEDBACK</strong></div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Core vocabulary", subtitle: "Separate observation from automatic action", marks: 10,
    questions: [
      { id: "l14-1", marks: 4, lines: 4, prompt: <><b>Distinguish a monitoring system from a control system.</b><p>Include the role of output in each.</p></>, answer: <p>A <strong>monitoring system</strong> senses, records or displays conditions for a person or another system; its output does not automatically alter the measured process. A <strong>control system</strong> processes sensor data and automatically sends signals to actuators, changing the process. <em>[2 + 2]</em></p> },
      { id: "l14-2", marks: 6, lines: 5, prompt: <><b>Define sensor, actuator and feedback.</b><p>Give one suitable example of each sensor type named in the syllabus.</p></>, answer: <p>A <strong>sensor</strong> detects a physical property and produces a signal. An <strong>actuator</strong> converts a control signal into physical action. <strong>Feedback</strong> is the new measured state returned to the controller after an action. Examples: temperature—greenhouse heat; pressure—vehicle weight; infrared—distance/presence; sound—noise level. <em>[3 definitions; 3 appropriate examples]</em></p> },
    ],
  },
  {
    code: "B", title: "Trace the loop", subtitle: "Name the input, decision, output and next input", marks: 10,
    questions: [
      { id: "l14-3", marks: 6, lines: 5, prompt: <><b>A greenhouse must remain at 24°C.</b><p>Describe one complete feedback cycle when the temperature falls to 21°C.</p></>, answer: <p>The temperature sensor measures 21°C and sends data to the processor. The processor compares 21°C with the 24°C target and sends a signal to a heater/relay actuator. Heating raises the temperature. The sensor measures the changed temperature again; the controller reduces or stops heating when the target is reached. <em>[6 linked stages]</em></p> },
      { id: "l14-4", marks: 4, lines: 4, prompt: <><b>A river station records water pressure and sends an alert to staff.</b><p>Explain why this is monitoring, then state one change that would make it control.</p></>, answer: <p>It is monitoring because it senses/records a condition and alerts a person, but does not automatically change the river system. It becomes control if the processor automatically operates an actuator, for example opening a sluice gate, and then uses new sensor readings as feedback. <em>[2 monitoring; 2 valid change]</em></p> },
    ],
  },
  {
    code: "C", title: "Authentic Paper 1 practice", subtitle: "Adapted prompts retain the original marks", marks: 10,
    questions: [
      { id: "l14-5", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>A restaurant robot navigates to a table.</b><p>(a) Identify two sensors and give one matching navigation use for each. [2]</p><p>(b) Describe how feedback is used in a control system. [2]</p><p>Adapted from 9618/13 M/J 2024 Q7(a),(c).</p></>, answer: <p>Valid pairs include pressure—detect a collision/load; infrared—detect an obstacle or arrival at a table; sound—detect a spoken instruction. Feedback provides a new input after an output/action, allowing the controller to compare with its criterion and adjust automatically. <em>[2 + 2]</em></p> },
      { id: "l14-6", marks: 6, lines: 5, prompt: <><b>Design a control loop for an automatic water tank.</b><p>Name a sensor and actuator, then describe four linked processing/feedback steps.</p></>, answer: <p>Use a pressure/level sensor and a valve or pump actuator. The sensor measures the level; data are compared with a target; the controller opens the valve or runs the pump when too low; water level changes; the sensor measures again; the controller changes/stops the actuator at the target. <em>[1 sensor; 1 actuator; 4 linked stages]</em></p> },
    ],
  },
];

export default function Lesson14Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "3 min", focus: "Open with the difference between observing a process and changing it.", prompt: "Ask: does a weather station control the weather?", source: "Syllabus 3.1 p.17; Coursebook Chapter 7 printed pp.112-114.", content: <Slide number="01" eyebrow="CHAPTER 3 · SYSTEMS IN THE WORLD" sourceLabel="TEXTBOOK CH.7 · pp.112-114" syllabusLabel="SYLLABUS 3.1 · p.17" className="slide--c3-title"><section className="c3-title-grid"><div><span>LESSON 14 · 90 MINUTES</span><h1>Sense.<br /><em>Decide. Act.</em></h1><p>Monitoring observes. Control changes the physical world and checks what happened next.</p></div><ControlLoop /></section></Slide> },
    { time: "4 min", focus: "Make the cross-chapter textbook mapping explicit.", prompt: "Students identify the four syllabus nouns in the route.", source: "2027-2029 syllabus 3.1 p.17; content sits in legacy Coursebook Chapter 7.", content: <Slide number="02" eyebrow="TEXTBOOK × CURRENT SYLLABUS" sourceLabel="TEXTBOOK 7.01-7.02" syllabusLabel="SYLLABUS 3.1 · p.17" title="One syllabus objective, four connected ideas." className="slide--c3-map"><section className="c3-route-grid"><article><b>1</b><span>MONITOR</span><p>measure · record · alert</p></article><article><b>2</b><span>SENSE</span><p>temperature · pressure · IR · sound</p></article><article><b>3</b><span>ACT</span><p>motor · valve · heater · relay</p></article><article><b>4</b><span>FEEDBACK</span><p>measure the result again</p></article></section><p className="c3-note"><Mark>BOUNDARY</Mark> Bit manipulation from textbook 7.03 returns in Lesson 24 under syllabus 4.3.</p></Slide> },
    { time: "7 min", focus: "Give a mark-ready distinction between monitoring and control.", prompt: "Classify a weather logger, heart-rate alarm and thermostat.", source: "Coursebook 7.01 printed p.112; syllabus 3.1 monitoring/control distinction.", content: <Slide number="03" eyebrow="MONITOR ≠ CONTROL" sourceLabel="TEXTBOOK 7.01 · p.112" syllabusLabel="SYLLABUS 3.1 — DISTINCTION" title="The decisive question: does the system automatically alter the process?" className="slide--c3-compare"><section className="c3-two"><article><span>MONITORING</span><h3>observe and report</h3><ul><li>collects sensor data</li><li>stores, displays or alerts</li><li>person may decide what to do</li></ul></article><article><span>CONTROL</span><h3>observe and intervene</h3><ul><li>collects and processes data</li><li>operates an actuator automatically</li><li>action changes a later input</li></ul></article></section></Slide> },
    { time: "7 min", focus: "Model both systems as input-process-output before adding feedback.", prompt: "Students narrate each arrow using a greenhouse.", source: "Coursebook 7.01-7.02 pp.112-114.", content: <Slide number="04" eyebrow="INPUT → PROCESS → OUTPUT" sourceLabel="TEXTBOOK pp.112-114" syllabusLabel="SYLLABUS 3.1" title="The same three stages; a different kind of output." className="slide--c3-flow"><section className="c3-process-flow"><article><span>INPUT</span><b>sensor signal</b><p>measured physical condition</p></article><i>→</i><article><span>PROCESS</span><b>compare</b><p>reading against rule or target</p></article><i>→</i><article><span>OUTPUT</span><b>alert or action</b><p>display for monitoring; actuator for control</p></article></section></Slide> },
    { time: "7 min", focus: "Teach only the four sensor families named in the syllabus, with matching properties.", prompt: "Give a scenario; students name a sensor and measured quantity.", source: "Syllabus 3.1 p.17; Coursebook p.113 examples.", content: <Slide number="05" eyebrow="SENSORS · INPUT FROM REALITY" sourceLabel="TEXTBOOK 7.02 · p.113" syllabusLabel="SYLLABUS 3.1 — SPECIFIED SENSORS" title="Choose the sensor from the physical property being measured." className="slide--c3-sensors"><section className="c3-card-grid"><article><span>TEMPERATURE</span><b>thermal condition</b><p>greenhouse · freezer</p></article><article><span>PRESSURE</span><b>force per area</b><p>tank · vehicle weight</p></article><article><span>INFRARED</span><b>radiation / proximity</b><p>person · obstacle</p></article><article><span>SOUND</span><b>sound level / signal</b><p>alarm · voice</p></article></section></Slide> },
    { time: "6 min", focus: "Explain analogue sensor signals and conditional ADC use without overclaiming.", prompt: "Ask why a binary processor may need conversion.", source: "Coursebook 7.02 p.113; syllabus application context.", content: <Slide number="06" eyebrow="FROM PHYSICAL VALUE TO DATA" sourceLabel="TEXTBOOK CONTEXT · p.113" syllabusLabel="SYLLABUS 3.1 — SENSOR DATA" title="A sensor produces a signal; the processor needs usable data." className="slide--c3-signal"><section className="c3-signal-strip"><b>physical quantity</b><i>→</i><b>sensor signal</b><i>→</i><strong>ADC if analogue</strong><i>→</i><b>digital value</b></section><p className="c3-note"><Mark>PRECISION</Mark> ADC is required only when the sensor/interface supplies an analogue signal.</p></Slide> },
    { time: "6 min", focus: "Broaden actuator beyond the textbook's narrow motor example.", prompt: "Match motor, valve, heater and relay to physical changes.", source: "Syllabus 3.1 actuators; Coursebook p.113 with corrected broader definition.", content: <Slide number="07" eyebrow="ACTUATORS · OUTPUT INTO REALITY" sourceLabel="TEXTBOOK 7.02 · p.113" syllabusLabel="SYLLABUS 3.1 — ACTUATORS" title="An actuator converts a control signal into physical action." className="slide--c3-actuators"><section className="c3-card-grid"><article><span>MOTOR</span><b>movement</b><p>fan · robot wheel</p></article><article><span>VALVE</span><b>flow</b><p>water · gas</p></article><article><span>HEATER</span><b>temperature</b><p>room · tank</p></article><article><span>RELAY</span><b>switching</b><p>high-power device</p></article></section></Slide> },
    { time: "5 min", focus: "Keep DAC conditional and separate it from the actuator itself.", prompt: "Students correct: 'the DAC moves the motor'.", source: "Coursebook context; syllabus actuator role.", content: <Slide number="08" eyebrow="CONTROL SIGNAL → ACTION" sourceLabel="TEXTBOOK CONTEXT" syllabusLabel="SYLLABUS 3.1" title="The converter changes the signal; the actuator changes the world." className="slide--c3-signal"><section className="c3-signal-strip"><b>digital decision</b><i>→</i><strong>DAC / interface if needed</strong><i>→</i><b>actuator</b><i>→</i><b>physical change</b></section><p className="c3-note"><Mark>EXAM LANGUAGE</Mark> Name the actuator and the action it performs.</p></Slide> },
    { time: "8 min", focus: "Make feedback a closed, repeated loop rather than a one-off reading.", prompt: "Point to the exact moment feedback occurs.", source: "Coursebook 7.02 pp.113-114; syllabus importance of feedback.", content: <Slide number="09" eyebrow="WHY FEEDBACK MATTERS" sourceLabel="TEXTBOOK 7.02 · pp.113-114" syllabusLabel="SYLLABUS 3.1 — FEEDBACK" title="An action changes the system; feedback tells the controller by how much." className="slide--c3-loop"><ControlLoop /><div className="c3-rule"><b>target − new reading</b><span>drives the next decision</span><strong>repeat</strong></div></Slide> },
    { time: "7 min", focus: "Trace one complete feedback cycle with linked causal verbs.", prompt: "Pairs narrate the greenhouse cycle without saying 'it just knows'.", source: "Coursebook worked context pp.113-114.", content: <Slide number="10" eyebrow="SCENARIO TRACE · GREENHOUSE" sourceLabel="TEXTBOOK pp.113-114" syllabusLabel="SYLLABUS 3.1 — APPLY" title="Below target → heat → re-measure → stop at target." className="slide--c3-scenario"><section className="c3-steps"><article><span>01</span><p>sensor reads <b>21°C</b></p></article><article><span>02</span><p>processor compares with <b>24°C</b></p></article><article><span>03</span><p>heater actuator switches <b>on</b></p></article><article><span>04</span><p>new reading feeds back; heating adjusts</p></article></section></Slide> },
    { time: "7 min", focus: "Compare two scenarios to prevent sensor-name guessing.", prompt: "Require a measured property, a decision and an actuator for each.", source: "Syllabus 3.1 application; Coursebook Chapter 7 examples.", content: <Slide number="11" eyebrow="CHOOSE · LINK · JUSTIFY" sourceLabel="TEXTBOOK CONTEXT" syllabusLabel="SYLLABUS 3.1 — SCENARIOS" title="A valid answer links the sensor to the decision and the physical response." className="slide--c3-scenarios"><section className="c3-two"><article><span>SECURITY LIGHT</span><h3>infrared → controller → lamp relay</h3><p>Presence is sensed; darkness/rule is checked; the light is switched.</p></article><article><span>WATER TANK</span><h3>pressure → controller → valve</h3><p>Level is inferred; target is checked; inflow changes and is re-measured.</p></article></section></Slide> },
    { time: "7 min", focus: "Use a verified four-mark Paper 1 task and expose the mark allocation.", prompt: "Four minutes closed-book, then reveal and self-mark.", source: "Adapted from 9618/12 O/N 2024 Q9(a)-(b), verified against the published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/12 O/N 2024 · Q9(a-b)" syllabusLabel="SYLLABUS 3.1 — EXAM PRACTICE" title="A bridge warning system checks vehicle height and weight." className="slide--c3-paper"><section className="c3-paper-grid"><p><b>(a)</b> Name two suitable sensors and state the purpose of each. <strong>[2]</strong></p><p><b>(b)</b> Is a warning-only system monitoring or control? Explain. <strong>[2]</strong></p></section><Reveal id="bridge" visible={revealed.has("bridge")} onToggle={toggleReveal}><p><b>(a)</b> Infrared measures/checks height; pressure measures/checks weight. <b>(b)</b> Monitoring: it only indicates a warning; no actuator/feedback changes the measured process.</p></Reveal><small>Adapted from 9618/12 O/N 2024 Q9(a)-(b).</small></Slide> },
    { time: "5 min", focus: "Turn the mark scheme into a reusable answer frame.", prompt: "Students improve one vague answer using the frame.", source: "Published mark scheme principles for 9618/12 O/N 2024 Q9.", content: <Slide number="13" eyebrow="MARK-SCHEME LANGUAGE" sourceLabel="9618/12 O/N 2024 · MS" syllabusLabel="SYLLABUS 3.1 — AO2" title="Name → purpose → automatic effect." className="slide--c3-frame"><section className="c3-answer-frame"><b>Sensor:</b><span>___ measures ___ so the processor can ___.</span><b>System:</b><span>It is control because ___ operates ___, changing ___; the new ___ is feedback.</span></section></Slide> },
    { time: "6 min", focus: "Interleave classification, sensor selection and feedback order.", prompt: "Students answer all three before discussion.", source: "Syllabus 3.1 retrieval.", content: <Slide number="14" eyebrow="MIXED RETRIEVAL" sourceLabel="SYLLABUS CHECK" syllabusLabel="SYLLABUS 3.1" title="Three decisions in six minutes." className="slide--c3-retrieval"><section className="c3-quiz"><p><b>1</b> Monitoring or control: a logger emails a nurse?</p><p><b>2</b> Which sensor detects an approaching obstacle?</p><p><b>3</b> Why must a thermostat measure again after heating?</p></section><Reveal id="retrieval" visible={revealed.has("retrieval")} onToggle={toggleReveal}><p><b>1</b> Monitoring, if it only reports. <b>2</b> Infrared. <b>3</b> The new reading is feedback used to adjust/stop the heater.</p></Reveal></Slide> },
    { time: "5 min", focus: "Finish with one complete causal chain and direct students to homework.", prompt: "Exit sentence must contain sensor, processor, actuator and feedback.", source: "Syllabus 3.1 exit check.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="SYLLABUS 3.1" syllabusLabel="CHAPTER 3 CHECKPOINT" title="Explain one control system in exactly four linked clauses." className="slide--c3-exit"><ControlLoop /><div className="c3-homework-callout"><b>HOMEWORK 14</b><span>30 marks · one verified Paper 1 task · inline answers</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="14" slides={slides} homework={<HomeworkSheet lessonNumber="14" title="Monitoring, Control, Sensors, Actuators & Feedback" marks={30} minutes={45} syllabusLabel="SYLLABUS 3.1 · p.17" sourceLabel="TEXTBOOK CH.7 · pp.112-114 + PAPER 1" instructions="Use linked cause-and-effect language. Every scenario answer should name the physical property, the processing decision and the output action. Past-paper wording is concisely adapted and fully cited." sections={homeworkSections} challenge={{ id: "l14-challenge", prompt: <p><Mark>CHALLENGE</Mark> A control system can oscillate around its target. Explain how repeated feedback could reduce this problem.</p>, answer: <p>Measure after each smaller adjustment, compare the error with the target and reduce the actuator response as the error becomes smaller. This limits overshoot; exact advanced control terminology is not required.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 3.1 p.17, Coursebook 7.01-7.02 printed pp.112-114, and published 2024 Paper 1 questions and mark schemes." sourceDetail="Core: monitoring versus control; temperature, pressure, infrared and sound sensors; actuators; feedback. Authentic anchors: 9618/12 O/N 2024 Q9(a)-(b) and 9618/13 M/J 2024 Q7(a),(c). Prompts are concise adaptations, not reproductions of complete papers. Textbook 7.03 bit manipulation is taught in Lesson 24 under syllabus 4.3." />;
}
