"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Three different promises", subtitle: "Security, privacy and integrity", marks: 10,
    questions: [
      { id: "l29-1", marks: 3, lines: 3, prompt: <><b>Define data security, data privacy and data integrity.</b></>, answer: <p><strong>Security</strong> is the protection of systems/data from unauthorised access, loss, damage or disruption. <strong>Privacy</strong> is control over authorised collection, access, use and disclosure of personal data. <strong>Integrity</strong> means data remains complete, accurate, consistent and unaltered without authorisation. <em>[1 each]</em></p> },
      { id: "l29-2", marks: 3, lines: 3, prompt: <><b>Explain why a hospital must protect both its data and its computer system.</b></>, answer: <p>Patient data must remain confidential/accurate so treatment and legal decisions use trustworthy information. The system must remain available so staff can retrieve records and operate connected services. A breach or outage could harm patients and damage trust. <em>[3 relevant linked points]</em></p> },
      { id: "l29-3", marks: 4, lines: 4, prompt: <><b>Use the terms asset, vulnerability, threat and impact for this event:</b><p>An unpatched laptop is infected and examination files are deleted.</p></>, answer: <p><strong>Asset:</strong> examination files/laptop. <strong>Vulnerability:</strong> missing security patch. <strong>Threat:</strong> malware/attacker exploiting the weakness. <strong>Impact:</strong> files lost, work interrupted or results delayed. <em>[1 each]</em></p> },
    ],
  },
  {
    code: "B", title: "Recognise the route", subtitle: "Five threats named by syllabus 6.1", marks: 10,
    questions: [
      { id: "l29-4", marks: 4, lines: 4, prompt: <><b>Compare a virus with spyware.</b></>, answer: <p>Both are malicious programs that may run without the user&apos;s knowledge. A <strong>virus</strong> attaches to files/programs and replicates when executed, often corrupting or disrupting data. <strong>Spyware</strong> secretly monitors activity or records data and sends it to another party; replication is not its defining feature. <em>[2 similarity/difference pairs]</em></p> },
      { id: "l29-5", marks: 4, lines: 4, prompt: <><b>Explain one similarity and one difference between phishing and pharming.</b></>, answer: <p>Both imitate a trusted organisation/site to obtain personal or financial data. <strong>Phishing</strong> usually sends a deceptive message that persuades the user to click, reply or enter data. <strong>Pharming</strong> redirects the user to a fake site even when an apparently correct address is requested, often through altered DNS/host settings. <em>[2 + 2]</em></p> },
      { id: "l29-6", marks: 2, lines: 2, prompt: <><b>State what makes a person a hacker in a security context and give one possible impact.</b></>, answer: <p>A hacker attempts/gains unauthorised access to a computer system or data; an impact could be theft, alteration/deletion of data, service disruption or disclosure. <em>[1 + 1]</em></p> },
    ],
  },
  {
    code: "C", title: "Paper 1 application", subtitle: "Use precise contrasts, then diagnose a scenario", marks: 10,
    questions: [
      { id: "l29-7", marks: 5, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Distinguish security from integrity, then compare spyware with a virus.</b><p>Adapted from 9618/11 O/N 2021 Q2(a), Q2(c). [2 + 3]</p></>, answer: <p><strong>Security:</strong> protection against loss/corruption or unauthorised access; <strong>integrity:</strong> data remains accurate/consistent. Both spyware and viruses are malicious and may run hidden; a virus replicates and may damage files, whereas spyware monitors/records and exports information. <em>[2 + 3]</em></p> },
      { id: "l29-8", marks: 5, lines: 5, prompt: <><b>A student types the bank&apos;s correct web address but reaches a convincing fake page. Later, login details are stolen.</b><p>Identify the threat and explain the complete threat-to-impact chain.</p></>, answer: <p>The threat is <strong>pharming</strong>. Malicious changes redirect the request to a fake site; the page imitates the bank; the user submits credentials; the attacker captures them and can access the account, causing financial loss and loss of privacy. <em>[1 identification + up to 4 linked steps]</em></p> },
    ],
  },
];

export default function Lesson29Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame security as three distinct promises before introducing threats.", prompt: "Ask: can data be private but inaccurate?", source: "Syllabus 6.1; Coursebook Chapter 9 printed pp.133–136.", content: <Slide number="01" eyebrow="CHAPTER 6 · SECURITY" sourceLabel="TEXTBOOK CH.9 · pp.133–136" syllabusLabel="SYLLABUS 6.1" className="se-title"><section className="se-title-grid"><div className="se-title-copy"><span>LESSON 29 · 90 MINUTES</span><h1>Protect the <em>promise.</em></h1><p>Separate security, privacy and integrity—then recognise how five named threats reach people, systems and data.</p></div><div className="se-title-visual"><div><b>1</b><span>WHAT MUST BE PROTECTED?</span></div><div><b>2</b><span>WHERE IS THE WEAKNESS?</span></div><div><b>3</b><span>HOW DOES THE THREAT ARRIVE?</span></div><div><b>4</b><span>WHAT IS THE IMPACT?</span></div></div></section></Slide> },
    { time: "5 min", focus: "Activate intuitive distinctions using one incident with three consequences.", prompt: "Which promise is broken by viewing, editing and deleting a record?", source: "Coursebook 9.01 printed pp.134–135; syllabus 6.1 distinctions.", content: <Slide number="02" eyebrow="DO NOW · ONE BREACH, THREE QUESTIONS" sourceLabel="TEXTBOOK §9.01 · pp.134–135" syllabusLabel="SYLLABUS 6.1" title="A stranger opens, changes and then deletes a patient record."><section className="se-grid three"><article className="se-card"><span>OPENED</span><h3>Who was allowed to see it?</h3><p>Think <strong>privacy</strong> and authorised disclosure.</p></article><article className="se-card"><span>CHANGED</span><h3>Can the values still be trusted?</h3><p>Think <strong>integrity</strong> and unauthorised alteration.</p></article><article className="se-card"><span>DELETED</span><h3>Was it protected and available?</h3><p>Think <strong>security</strong>, loss and disruption.</p></article></section></Slide> },
    { time: "6 min", focus: "Establish mark-scheme-ready definitions with clear boundaries.", prompt: "Students create one counterexample for each term.", source: "Syllabus 6.1; Coursebook 9.01 printed pp.134–135, clarified for current terminology.", content: <Slide number="03" eyebrow="THE THREE DEFINITIONS" sourceLabel="TEXTBOOK §9.01 · pp.134–135" syllabusLabel="SYLLABUS 6.1" title="Related—not interchangeable."><div className="se-definition"><b>SECURITY</b><p>Measures that protect systems and data against unauthorised access, loss, damage or disruption.</p><span>Can we prevent or contain harm?</span></div><div className="se-definition"><b>PRIVACY</b><p>Control over authorised collection, access, use and disclosure of personal data.</p><span>Who may use which personal data—and why?</span></div><div className="se-definition"><b>INTEGRITY</b><p>Data remains complete, accurate, consistent and unchanged without authorisation.</p><span>Can the data be trusted?</span></div></Slide> },
    { time: "5 min", focus: "Distinguish protecting data from protecting the platform that stores/processes it.", prompt: "What happens to accurate encrypted data if the server is unavailable?", source: "Syllabus 6.1 need for data and computer-system security; Coursebook 9.01 and 9.03–9.04.", content: <Slide number="04" eyebrow="TWO SECURITY TARGETS" sourceLabel="TEXTBOOK pp.134, 137–140" syllabusLabel="SYLLABUS 6.1" title="Protect the information and the system that keeps it useful."><section className="se-grid two"><article className="se-card"><span>DATA SECURITY</span><h3>Records, messages, files</h3><p>Prevent unauthorised reading/change, accidental loss and disclosure. Preserve confidentiality, integrity and availability.</p></article><article className="se-card"><span>SYSTEM SECURITY</span><h3>Devices, accounts, services</h3><p>Keep hardware/software trustworthy and available; stop unauthorised control and service disruption.</p></article></section><p className="se-note">A secure course-registration system needs both: protected student records <strong>and</strong> a working, controlled platform.</p></Slide> },
    { time: "6 min", focus: "Give students a reusable causal vocabulary for scenario explanations.", prompt: "Name the vulnerability—not just the threat—in an unpatched browser attack.", source: "Threat-and-risk framing synthesised from Coursebook 9.02–9.04 and syllabus 6.1.", content: <Slide number="05" eyebrow="READ A SECURITY SCENARIO" sourceLabel="TEXTBOOK §§9.02–9.04" syllabusLabel="SYLLABUS 6.1" title="Follow the chain: asset → weakness → threat → impact."><section className="se-risk-chain"><div><span>ASSET</span><b>valuable data or system</b></div><i>→</i><div><span>VULNERABILITY</span><b>exploitable weakness</b></div><i>→</i><div><span>THREAT</span><b>possible cause of harm</b></div><i>→</i><div><span>EVENT</span><b>weakness is exploited</b></div><i>→</i><div><span>IMPACT</span><b>loss, change or disruption</b></div></section><p className="se-warning">A threat is not the same as a vulnerability. “Weak password” is a weakness; “hacker guesses it” is the threat event.</p></Slide> },
    { time: "6 min", focus: "Survey every threat explicitly named by syllabus 6.1.", prompt: "Classify each by its main route: malicious software, unauthorised actor or deception/redirection.", source: "Syllabus 6.1 named threats; Coursebook 9.02 printed pp.135–136.", content: <Slide number="06" eyebrow="THE FIVE NAMED THREATS" sourceLabel="TEXTBOOK §9.02 · pp.135–136" syllabusLabel="SYLLABUS 6.1" title="Recognise the route before choosing a control."><section className="se-grid five"><article className="se-card"><span>VIRUS</span><p>replicates through infected files/programs</p></article><article className="se-card"><span>SPYWARE</span><p>secretly monitors and exports data</p></article><article className="se-card"><span>HACKER</span><p>seeks unauthorised access</p></article><article className="se-card"><span>PHISHING</span><p>message persuades a user to act</p></article><article className="se-card"><span>PHARMING</span><p>request is redirected to a fake site</p></article></section></Slide> },
    { time: "6 min", focus: "Explain virus infection, execution and replication as a sequence.", prompt: "Which step means merely receiving an infected file may not yet run the virus?", source: "Coursebook 9.02 printed pp.135–136; syllabus 6.1 virus.", content: <Slide number="07" eyebrow="VIRUS" sourceLabel="TEXTBOOK §9.02 · pp.135–136" syllabusLabel="SYLLABUS 6.1" title="Host, execute, replicate, harm."><section className="se-flow"><span>INFECTED<br />FILE</span><i>→</i><span>USER / SYSTEM<br />EXECUTES IT</span><i>→</i><span>VIRUS CODE<br />RUNS</span><i>→</i><span>MORE FILES /<br />SYSTEMS INFECTED</span></section><p className="se-note">Possible impacts include corrupted/deleted data, changed behaviour, slowed systems and further spread. <strong>Replication</strong> is the defining contrast with spyware.</p></Slide> },
    { time: "5 min", focus: "Describe spyware through observation and exfiltration, not replication.", prompt: "What could keylogging reveal beyond passwords?", source: "Coursebook 9.02 printed p.136; syllabus 6.1 spyware.", content: <Slide number="08" eyebrow="SPYWARE" sourceLabel="TEXTBOOK §9.02 · p.136" syllabusLabel="SYLLABUS 6.1" title="Observe quietly; send information elsewhere."><section className="se-flow"><span>INSTALLED<br />SECRETLY</span><i>→</i><span>MONITORS<br />ACTIVITY</span><i>→</i><span>CAPTURES<br />DATA</span><i>→</i><span>EXFILTRATES<br />TO ATTACKER</span></section><p className="se-warning">Spyware may record keystrokes, browsing, screenshots or credentials. It is malicious software, but it need not copy itself from file to file.</p></Slide> },
    { time: "5 min", focus: "Treat hacking as unauthorised access and connect motives to impact without stereotypes.", prompt: "Can an attempted access be a threat even if no data is stolen?", source: "Coursebook 9.02 printed pp.135–136; syllabus 6.1 hackers.", content: <Slide number="09" eyebrow="HACKER / UNAUTHORISED ACCESS" sourceLabel="TEXTBOOK §9.02 · pp.135–136" syllabusLabel="SYLLABUS 6.1" title="The defining feature is lack of authorisation."><section className="se-grid four"><article className="se-card"><span>ENTER</span><p>guess credentials or exploit a weakness</p></article><article className="se-card"><span>VIEW</span><p>breach confidentiality and privacy</p></article><article className="se-card"><span>CHANGE</span><p>damage integrity or permissions</p></article><article className="se-card"><span>DISRUPT</span><p>make services or data unavailable</p></article></section><p className="se-note">Paper 1 explanations score the <strong>action and consequence</strong>, not a dramatic label.</p></Slide> },
    { time: "6 min", focus: "Model phishing as social engineering that depends on user action.", prompt: "Find three warning signs in the mock message.", source: "Coursebook 9.02 printed p.136; syllabus 6.1 phishing.", content: <Slide number="10" eyebrow="PHISHING" sourceLabel="TEXTBOOK §9.02 · p.136" syllabusLabel="SYLLABUS 6.1" title="A believable message creates urgency, then asks the user to act."><section className="se-threat-mail"><div className="se-inbox"><span>INBOX · ACCOUNT TEAM</span><p><strong>Urgent:</strong> access expires today.</p><p>Confirm your password at<br /><strong>bank-secure-login.example</strong></p><p>Dear valued customer…</p></div><article className="se-card"><span>THE ROUTE</span><h3>Message → trust → action</h3><p>The victim clicks, replies, opens an attachment or enters data. The attacker relies on deception more than technical redirection.</p></article></section></Slide> },
    { time: "6 min", focus: "Model pharming as redirection even when the user intends the correct destination.", prompt: "Why might a bookmark fail to protect the user in a pharming attack?", source: "Coursebook 9.02 printed p.136; syllabus 6.1 pharming, clarified as redirection.", content: <Slide number="11" eyebrow="PHARMING" sourceLabel="TEXTBOOK §9.02 · p.136" syllabusLabel="SYLLABUS 6.1" title="The request is redirected; the fake destination imitates the real one."><section className="se-threat-mail"><div className="se-address-bar"><code>https://<strong>mybank.example</strong></code><p>The user enters or selects the intended address, but corrupted DNS/host information sends the request to an attacker-controlled site.</p></div><article className="se-card"><span>THE ROUTE</span><h3>Correct intention → wrong destination</h3><p>The fake page captures credentials or financial data. The user may not need to click a deceptive email.</p></article></section></Slide> },
    { time: "5 min", focus: "Consolidate phishing/pharming and virus/spyware contrasts.", prompt: "Complete each missing cell without using the threat name in the explanation.", source: "Coursebook 9.02; syllabus 6.1; comparison pattern from 9618/11 O/N 2021 Q2(c).", content: <Slide number="12" eyebrow="COMPARE—DON'T JUST DEFINE" sourceLabel="TEXTBOOK §9.02 + PAPER 1" syllabusLabel="SYLLABUS 6.1" title="Use one similarity and one defining difference."><section className="se-compare"><div><b>PAIR</b><b>SIMILARITY</b><b>DEFINING DIFFERENCE</b></div><div><b>Virus / spyware</b><span>malicious, hidden software</span><span>replication/damage vs monitoring/exfiltration</span></div><div><b>Phishing / pharming</b><span>fake trusted identity/site; steals data</span><span>persuasive message/action vs automatic redirection</span></div><div><b>Hacker / malware</b><span>can compromise systems/data</span><span>person/actor vs malicious program</span></div></section></Slide> },
    { time: "9 min", focus: "Apply precise definitions and comparisons to an authentic Paper 1 pattern.", prompt: "Write five mark points in four minutes, then self-mark.", source: "Adapted from 9618/11 O/N 2021 Q2(a), Q2(c), checked against the published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 5 MARKS" sourceLabel="9618/11 O/N 2021 · Q2(a), Q2(c)" syllabusLabel="SYLLABUS 6.1 — EXAM PRACTICE" title="Distinguish security from integrity; compare spyware with a virus." className="slide--se-paper"><section className="se-paper-grid"><article><span>2 MARKS</span><p>State a precise difference between <strong>security</strong> and <strong>integrity</strong>.</p></article><article><span>3 MARKS</span><p>Give a similarity and a defining difference between <strong>spyware</strong> and a <strong>virus</strong>.</p></article></section><ExamReveal><p>Security protects data/systems from loss, corruption or unauthorised access; integrity means data is accurate/consistent. Both threats are malicious/hidden; a virus replicates and may corrupt data, while spyware records and sends information to another party.</p></ExamReveal><small className="se-source-line">Concise adaptation of 9618/11 O/N 2021 Q2(a), Q2(c); original allocation [2 + 3].</small></Slide> },
    { time: "10 min", focus: "Require full threat chains in a collaborative security triage.", prompt: "Groups diagnose three cases, then rotate and challenge one link in another group's explanation.", source: "Syllabus 6.1 threat application; Coursebook 9.02.", content: <Slide number="14" eyebrow="SECURITY TRIAGE" sourceLabel="TEXTBOOK §9.02 · APPLICATION" syllabusLabel="SYLLABUS 6.1" title="Name the evidence, route and impact."><section className="se-grid three"><article className="se-card"><span>CASE A</span><h3>Files keep duplicating and corrupting.</h3><p>Threat? Entry/activation route? Two impacts?</p></article><article className="se-card"><span>CASE B</span><h3>A payroll clerk follows an urgent email link.</h3><p>Threat? User action? Data at risk?</p></article><article className="se-card"><span>CASE C</span><h3>The typed address opens a cloned payment page.</h3><p>Threat? Redirection clue? Likely impact?</p></article></section><p className="se-note"><strong>High-scoring chain:</strong> clue → named threat → mechanism → affected asset → concrete impact.</p></Slide> },
    { time: "6 min", focus: "Check all three definitions and the two most confused threat pairs.", prompt: "Collect one sentence per box; responses must include the underlined contrast.", source: "Syllabus 6.1 lesson synthesis; Coursebook 9.01–9.02.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK §§9.01–9.02 · REVIEW" syllabusLabel="SYLLABUS 6.1" title="Three sentences before you leave."><section className="se-exit"><article><span>1 · DEFINE</span><p>Integrity is not the same as security because…</p></article><article><span>2 · CONTRAST</span><p>Phishing needs ___; pharming instead ___.</p></article><article><span>3 · DIAGNOSE</span><p>Malware secretly records keystrokes. It is ___ because…</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="29" slides={slides} homework={<HomeworkSheet lessonNumber="29" title="Security, Privacy, Integrity and Internet Threats" marks={30} minutes={45} syllabusLabel="SYLLABUS 6.1" sourceLabel="TEXTBOOK CH.9 · pp.133–136 + PAPER 1" instructions="Use the exact security vocabulary from the lesson. For every scenario, identify the clue, name the threat, describe its route and connect it to a concrete impact. Answers remain beside each question when revealed or printed." sections={homeworkSections} challenge={{ id: "l29-challenge", prompt: <p><Mark>CHALLENGE</Mark> Give one example where data privacy is breached but data integrity remains intact, and one where integrity is breached without public disclosure.</p>, answer: <p><strong>Privacy only:</strong> an unauthorised employee reads an accurate record but does not alter it. <strong>Integrity only:</strong> an authorised interface accidentally changes a private balance, but nobody outside the authorised group sees it. The examples show that viewing/disclosure and trustworthiness are separate properties.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 6.1, Coursebook Chapter 9 printed pp.133–136, and the published 2021 Paper 1 question and mark scheme." sourceDetail="Core: distinguish security, privacy and integrity; explain the need to protect both data and systems; recognise virus, spyware, hackers, phishing and pharming and connect each to an impact. Authentic anchor: 9618/11 O/N 2021 Q2(a), Q2(c) [2 + 3]. Controls are deliberately reserved for Lesson 30." />;
}
