"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip, WorkedBoard } from "../../_components/a2-theory-lesson";
import { RecursionStack } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Recursive structure", subtitle: "Name the call, the stop and the progress", marks: 10,
    questions: [
      { id: "a2-27-1", marks: 3, lines: 6, prompt: <><b>State three essential features of a recursive algorithm.</b></>, answer: <p>A function/procedure calls itself directly or indirectly <em>[1]</em>. It has a base/terminating case that returns without another recursive call <em>[1]</em>. The general case changes its argument/state so execution progresses toward the base case <em>[1]</em>.</p> },
      { id: "a2-27-2", marks: 3, lines: 7, prompt: <><b>Explain the difference between winding and unwinding.</b></>, answer: <p>Winding occurs while further recursive calls are made and stack frames are pushed <em>[1]</em>. The base case stops new calls <em>[1]</em>. Unwinding returns results and pops frames in reverse order <em>[1]</em>.</p> },
      { id: "a2-27-3", marks: 4, lines: 8, prompt: <><b>Identify two faults that can make recursion fail and explain each consequence.</b></>, answer: <p>A missing/unreachable base case means calls do not terminate <em>[1]</em>, eventually causing stack overflow <em>[1]</em>. A recursive case that does not move toward the base case can repeat/cycle <em>[1]</em> and also exhaust stack memory or give an incorrect result <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Write and trace", subtitle: "Return through every pending call", marks: 10,
    questions: [
      { id: "a2-27-4", marks: 3, lines: 8, prompt: <><b>Write a recursive function SumTo(n)</b> that returns 1 + 2 + … + n for n ≥ 0.</>, answer: <pre><code>{`FUNCTION SumTo(n : INTEGER) RETURNS INTEGER\n   IF n = 0 THEN\n      RETURN 0\n   ELSE\n      RETURN n + SumTo(n - 1)\n   ENDIF\nENDFUNCTION`}</code></pre> },
      { id: "a2-27-5", marks: 3, lines: 7, prompt: <><b>Trace SumTo(4)</b>, showing the winding calls and final result.</>, answer: <p>Calls wind as <code>SumTo(4) → SumTo(3) → SumTo(2) → SumTo(1) → SumTo(0)</code> <em>[1]</em>. Returns unwind as 0, 1, 3, 6, 10 <em>[1]</em>. Final result is <strong>10</strong> <em>[1]</em>.</p> },
      { id: "a2-27-6", marks: 4, lines: 10, prompt: <><b>Write a recursive binary-search function</b> using Data, Target, Low and High.</>, answer: <pre><code>{`FUNCTION Search(Data, Target, Low, High) RETURNS INTEGER\n   IF Low > High THEN RETURN -1\n   Mid ← (Low + High) DIV 2\n   IF Data[Mid] = Target THEN RETURN Mid\n   IF Target < Data[Mid] THEN\n      RETURN Search(Data, Target, Low, Mid - 1)\n   ELSE\n      RETURN Search(Data, Target, Mid + 1, High)\n   ENDIF\nENDFUNCTION`}</code></pre> },
    ],
  },
  {
    code: "C", title: "Stack, compiler and use", subtitle: "Explain implementation and choose recursion deliberately", marks: 10,
    questions: [
      { id: "a2-27-7", marks: 3, lines: 6, prompt: <><b>Explain why a stack is used when recursive code executes.</b></>, answer: <p>Each call pushes an activation record containing parameters/local values and a return address <em>[1]</em>. Calls are nested, so the most recent must finish first <em>[1]</em>. LIFO popping restores callers in reverse order during unwinding <em>[1]</em>.</p> },
      { id: "a2-27-8", marks: 3, lines: 6, prompt: <><b>State when recursion is beneficial and give one suitable example.</b></>, answer: <p>It is beneficial when a problem is naturally defined using smaller instances of itself or a recursive structure <em>[1]</em>, making the algorithm shorter/clearer than manual stack management <em>[1]</em>. Examples include traversing a tree, divide-and-conquer search, directory traversal or backtracking <em>[1]</em>.</p> },
      { id: "a2-27-9", marks: 4, lines: 8, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>For Fib(n), state the first depth-first (leftmost) winding sequence used to obtain Fib(5) and show the corresponding key unwind values.</b></p><p>Adapted from 9618/31 M/J 2023 Q12(b). [4 adapted marks]</p></>, answer: <p>The first depth-first/leftmost descent is <code>Fib(5), Fib(4), Fib(3), Fib(2), Fib(1)</code>; evaluation then reaches <code>Fib(0)</code> for the pending <code>Fib(2)</code> <em>[1]</em>, with base returns 1 and 0 <em>[1]</em>. Key results unwind as <code>Fib(2)=1, Fib(3)=2, Fib(4)=3</code> <em>[1]</em> and <code>Fib(5)=5</code> <em>[1]</em>. The full depth-first trace also evaluates the repeated right-hand subcalls.</p> },
    ],
  },
];

export default function A2Lesson27Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame recursion as deferred work stored in nested calls.", prompt: "What must happen before the first call can return?", source: "2027–2029 syllabus 19.2 p.37; coursebook Chapter 24 printed pp.434–442.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch24" syllabusLabel="SYLLABUS 19.2" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 27 · 90 MINUTES</span><h1>Call inward.<br /><em>Return outward.</em></h1><p>base case · recursive case · stack frame · winding · unwinding</p></div><div className="a2-at-hero" role="img" aria-label="Recursion lesson themes"><strong>RECURSION</strong><span>CALL</span><span>BASE CASE</span><span>STACK</span><span>RETURN</span></div></section></Slide> },
    { time: "5 min", focus: "Map every current recursion requirement.", prompt: "Which part asks about translation rather than writing the source algorithm?", source: "Official 2027–2029 syllabus 19.2 p.37.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.37" syllabusLabel="19.2 · REQUIRED" title="Define, write, trace, justify and explain the run-time stack." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "DEFINE", title: "Essential features", body: "Self-call, base case, progress." }, { eyebrow: "PROGRAM", title: "Write + trace", body: "Parameters, results and call order." }, { eyebrow: "CHOOSE", title: "When beneficial", body: "Naturally recursive structure." }, { eyebrow: "TRANSLATE / RUN", title: "Compiler + stack", body: "Frames, return address and unwinding." }]} /></Slide> },
    { time: "5 min", focus: "State the three essential features precisely.", prompt: "Why are both a base case and progress required?", source: "Coursebook §24.01–24.02 pp.434–436; 9618/31 O/N 2021 Q10(a).", content: <Slide number="03" eyebrow="RECURSION CONTRACT" sourceLabel="9618/31 O/N 2021 · Q10(a)" syllabusLabel="19.2 · ESSENTIAL" title="A self-call is safe only when some case stops and every other case moves toward it." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "SELF-REFERENCE", title: "Recursive call", body: "Function/procedure invokes itself directly or indirectly." }, { eyebrow: "STOP", title: "Base case", body: "Returns without another recursive call." }, { eyebrow: "PROGRESS", title: "General case", body: "Changes input/state toward the base case." }]} /></Slide> },
    { time: "6 min", focus: "Recognise direct and indirect recursive expression.", prompt: "Which call is recursive if A calls B and B calls A?", source: "Coursebook §24.02 pp.435–436.", content: <Slide number="04" eyebrow="EXPRESSED IN CODE" sourceLabel="TEXTBOOK pp.435–436" syllabusLabel="19.2 · PROGRAMMING" title="Recursion may be direct or indirect, but termination rules are the same." className="a2-slide a2-at-slide"><CompareTable headers={["Form", "Call pattern", "Exam check"]} rows={[["direct", "Factorial calls Factorial", "base + changing parameter visible"], ["indirect", "A calls B; B calls A", "combined cycle must reach a base case"], ["procedure", "performs action before/after CALL", "trace side effects in call order"], ["function", "uses returned recursive value", "trace both calls and returns"]]} /></Slide> },
    { time: "6 min", focus: "Write a minimal recursive function.", prompt: "What value should 0 factorial return?", source: "Coursebook factorial examples pp.434–437.", content: <Slide number="05" eyebrow="WRITE · FACTORIAL" sourceLabel="TEXTBOOK pp.434–437" syllabusLabel="19.2 · WRITE" title="The base case returns immediately; the general case defers multiplication." className="a2-slide a2-at-slide"><WorkedBoard label="Recursive function"><pre><code>{`FUNCTION Factorial(n : INTEGER) RETURNS INTEGER\n   IF n = 0 THEN\n      RETURN 1\n   ELSE\n      RETURN n * Factorial(n - 1)\n   ENDIF\nENDFUNCTION`}</code></pre></WorkedBoard></Slide> },
    { time: "6 min", focus: "Trace winding as creation of pending work.", prompt: "Which multiplications are known but not yet completed?", source: "Coursebook §24.03 pp.437–439.", content: <Slide number="06" eyebrow="TRACE · WINDING" sourceLabel="TEXTBOOK pp.437–439" syllabusLabel="19.2 · TRACE" title="Calls descend toward the base while operators wait for returned values." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "CALL 1", title: "4 × Factorial(3)" }, { eyebrow: "CALL 2", title: "3 × Factorial(2)" }, { eyebrow: "CALL 3", title: "2 × Factorial(1)" }, { eyebrow: "CALL 4", title: "1 × Factorial(0)" }, { eyebrow: "BASE", title: "return 1" }]} /></Slide> },
    { time: "6 min", focus: "Visualise nested activation records.", prompt: "Which call frame is at the top when the base case is reached?", source: "Coursebook running a recursive subroutine pp.439–440.", content: <Slide number="07" eyebrow="CALL STACK" sourceLabel="TEXTBOOK pp.439–440" syllabusLabel="19.2 · STACKS" title="Every active call owns a frame; LIFO matches nested return order." className="a2-slide a2-at-slide"><RecursionStack /></Slide> },
    { time: "6 min", focus: "Explain what compiler-generated run-time support stores.", prompt: "Why must each call keep a separate copy of n?", source: "Coursebook §24.04 pp.439–440; syllabus 19.2.", content: <Slide number="08" eyebrow="COMPILER + ACTIVATION RECORD" sourceLabel="TEXTBOOK pp.439–440" syllabusLabel="19.2 · TRANSLATION AWARENESS" title="Compiled call instructions create and remove stack frames at run time." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "PARAMETERS", title: "Call inputs", body: "A separate n for each Factorial call." }, { eyebrow: "LOCALS", title: "Private state", body: "Local variables and temporary values." }, { eyebrow: "RETURN ADDRESS", title: "Resume point", body: "Instruction after the call." }, { eyebrow: "RESULT / STATE", title: "Pending work", body: "Value and registers needed by the caller." }]} /></Slide> },
    { time: "6 min", focus: "Trace unwinding in exact reverse call order.", prompt: "Why does Factorial(3) finish before Factorial(4)?", source: "Coursebook §24.03–24.04 pp.437–440.", content: <Slide number="09" eyebrow="TRACE · UNWINDING" sourceLabel="TEXTBOOK pp.437–440" syllabusLabel="19.2 · UNWIND" title="The base result returns to the most recent caller, then frames pop outward." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "BASE", title: "Factorial(0) = 1" }, { eyebrow: "RETURN", title: "Factorial(1) = 1" }, { eyebrow: "RETURN", title: "Factorial(2) = 2" }, { eyebrow: "RETURN", title: "Factorial(3) = 6" }, { eyebrow: "RETURN", title: "Factorial(4) = 24" }]} /></Slide> },
    { time: "6 min", focus: "Write a recursive process with a clear decreasing measure.", prompt: "What measure proves this algorithm approaches termination?", source: "Coursebook programming examples pp.435–437; syllabus 19.2.", content: <Slide number="10" eyebrow="WRITE · SUM A RANGE" sourceLabel="TEXTBOOK pp.435–437" syllabusLabel="19.2 · WRITE" title="Choose a base result, then combine it with one smaller instance." className="a2-slide a2-at-slide"><WorkedBoard label="SumTo"><pre><code>{`FUNCTION SumTo(n : INTEGER) RETURNS INTEGER\n   IF n = 0 THEN\n      RETURN 0\n   ELSE\n      RETURN n + SumTo(n - 1)\n   ENDIF\nENDFUNCTION`}</code></pre><p>The non-negative measure <code>n</code> decreases by 1 until it reaches 0.</p></WorkedBoard></Slide> },
    { time: "7 min", focus: "Connect divide-and-conquer search to recursion.", prompt: "Which two arguments prove the search interval shrinks?", source: "Syllabus 19.2 and binary-search spiral from 19.1.", content: <Slide number="11" eyebrow="WRITE · RECURSIVE BINARY SEARCH" sourceLabel="SYLLABUS 19.1 + 19.2" syllabusLabel="19.2 · WRITE / TRACE" title="Each call keeps only the half that can still contain the target." className="a2-slide a2-at-slide"><CompareTable headers={["Condition", "Return / next call"]} rows={[["Low > High", "return -1 (base: absent)"], ["Data[Mid] = Target", "return Mid (base: found)"], ["Target < Data[Mid]", "Search(Low, Mid - 1)"], ["Target > Data[Mid]", "Search(Mid + 1, High)"]]} /></Slide> },
    { time: "7 min", focus: "Choose recursion where the structure mirrors the definition.", prompt: "Which examples naturally contain smaller versions of themselves?", source: "Coursebook §24.05 p.441; syllabus 19.2.", content: <Slide number="12" eyebrow="WHEN RECURSION HELPS" sourceLabel="TEXTBOOK p.441" syllabusLabel="19.2 · BENEFITS" title="Recursion is clearest when the data or problem is recursively structured." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "TREE", title: "Traverse children", body: "Each subtree is another tree." }, { eyebrow: "DIVIDE", title: "Binary search", body: "Solve one smaller interval." }, { eyebrow: "BACKTRACK", title: "Maze / game", body: "Try a branch, return, try another." }, { eyebrow: "HIERARCHY", title: "Directories", body: "Folders may contain folders." }]} /></Slide> },
    { time: "7 min", focus: "Balance clarity against time and stack memory.", prompt: "Why can an iterative algorithm be safer for very deep input?", source: "Coursebook §24.05 p.441; syllabus 19.2.", content: <Slide number="13" eyebrow="BENEFITS + DRAWBACKS" sourceLabel="TEXTBOOK p.441" syllabusLabel="19.2 · EVALUATE" title="Elegant source code still consumes a frame for every active call." className="a2-slide a2-at-slide"><CompareTable headers={["Benefit", "Drawback / caution"]} rows={[["mirrors recursive definitions and structures", "call overhead can increase execution time"], ["often shorter and easier to reason about", "each active call consumes stack space"], ["naturally supports divide-and-conquer/backtracking", "deep or non-terminating calls can overflow the stack"], ["local state is isolated per call", "repeated subproblems can duplicate work"]]} /></Slide> },
    { time: "8 min", focus: "Trace a recursive function through winding and unwinding.", prompt: "Record the first depth-first descent, then key results upward; do not jump directly to 5.", source: "Adapted from Cambridge 9618/31 M/J 2023 Q12(b) and published mark scheme.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/31 M/J 2023 · Q12(b)" syllabusLabel="19.2 · 5 MARKS" title="A trace must distinguish the leftmost descent from the complete branching evaluation." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/31 M/J 2023 · Q12(b) · ADAPTED" marks={5} prompt={<p>A recursive Fibonacci function returns n when n≤1; otherwise it returns Fib(n−1)+Fib(n−2). Trace the first depth-first (leftmost) descent and the key returns for Fib(5). [5]</p>} answer={<ul><li>First depth-first descent: Fib(5), Fib(4), Fib(3), Fib(2), Fib(1); the pending Fib(2) then calls Fib(0). [2]</li><li>Base returns: Fib(1)=1 and Fib(0)=0. [1]</li><li>Key accumulated returns: Fib(2)=1, Fib(3)=2, Fib(4)=3. [1]</li><li>After the required repeated right-hand subcalls, final return Fib(5)=5. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve recursion from source definition to run-time mechanism.", prompt: "Students state three essentials and explain one push/pop event.", source: "Syllabus 19.2 synthesis; coursebook Chapter 24 pp.434–442.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch24 · SYLLABUS p.37" syllabusLabel="19.2 · CHAPTER 19 CLOSE" title="Progress reaches the base; the stack brings every result home." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>CALL</span><p>Function/procedure refers to itself.</p></article><article><span>BASE</span><p>Returns without another call.</p></article><article><span>WIND</span><p>Push a frame per active call.</p></article><article><span>UNWIND</span><p>Pop in reverse order.</p></article></section><div className="homework-callout"><b>HOMEWORK 27</b><span>30 marks · recursion, stacks and unwinding</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="27" title="Recursion, stacks and unwinding" syllabusLabel="SYLLABUS 19.2" sourceLabel="TEXTBOOK Ch24 · pp.434–442" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 19.2 p.37 · endorsed coursebook Chapter 24 printed pp.434–442 · verified 2021–2025 Paper 3 questions and mark schemes" sourceDetail="The lesson defines the essential features of recursion, writes and traces recursive functions, evaluates suitable uses, and explains how compiler-generated activation records use a stack during winding and unwinding." />;
}
