"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { PacketBranchRoute } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Follow one circuit", subtitle: "Use the same four verbs every time", marks: 10,
    questions: [
      { id: "a2-09-1", marks: 3, lines: 5, prompt: <><b>Describe what happens before, during and after a circuit-switched call.</b><p>Use these starters: <em>First… During the call… Finally…</em></p></>, answer: <p>First, a dedicated end-to-end circuit is established <em>[1]</em> and bandwidth is reserved. During the call, all data uses the same route <em>[1]</em>. Finally, the circuit is released and the resources become available again <em>[1]</em>.</p> },
      { id: "a2-09-2", marks: 3, lines: 5, prompt: <><b>Explain why a circuit-switched call usually has predictable delivery.</b><p>Link the design choice to two consequences.</p></>, answer: <p>The route and bandwidth are reserved for the connection <em>[1]</em>, so other traffic cannot compete for that allocation. The same route is used throughout <em>[1]</em>, so data normally arrives in order with predictable delay <em>[1]</em>.</p> },
      { id: "a2-09-3", marks: 4, lines: 6, prompt: <><b>Explain two drawbacks</b> of circuit switching for a call with long silences.</>, answer: <p>There is setup time before user data can be sent <em>[2]</em>. During silence the reserved route is still unavailable to other users, so capacity is wasted <em>[2]</em>. A fixed-route failure is another valid explained drawback.</p> },
    ],
  },
  {
    code: "B", title: "Follow one message", subtitle: "Split it, label it, then rebuild it", marks: 10,
    questions: [
      { id: "a2-09-4", marks: 3, lines: 5, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Describe how a message is prepared for packet switching.</b></p><p>Name the payload and two useful header items. Adapted from 9618/32 O/N 2024 Q1.</p></>, answer: <p>The message is split into smaller packets <em>[1]</em>. Each packet contains a payload, which is part of the message, and a header <em>[1]</em>. The header can include a destination address and a sequence number <em>[1]</em>.</p> },
      { id: "a2-09-5", marks: 3, lines: 5, prompt: <><b>Explain why packets from one message may take different routes.</b><p>Use <em>independently</em> and <em>network conditions</em>.</p></>, answer: <p>Packets are forwarded independently <em>[1]</em>. A router uses the destination information and current routing/network conditions <em>[1]</em>, so a later packet may be sent through a different available next hop <em>[1]</em>.</p> },
      { id: "a2-09-6", marks: 4, lines: 6, prompt: <><b>Explain how the receiver handles packets that arrive out of order or go missing.</b></>, answer: <p>Sequence numbers show the correct order and reveal a gap <em>[1]</em>. The receiver temporarily stores and reorders packets <em>[1]</em>, then reassembles the message <em>[1]</em>. If the service provides acknowledgements/retransmission, missing data can be requested or sent again <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Compare and choose", subtitle: "Turn a feature into a consequence", marks: 10,
    questions: [
      { id: "a2-09-7", marks: 3, lines: 5, prompt: <><b>Give three paired differences</b> between circuit and packet switching.</>, answer: <p>Any three paired contrasts: dedicated same route vs shared links with packets on possibly different routes; reserved bandwidth vs on-demand sharing; ordered predictable arrival vs variable or out-of-order arrival; setup required vs no dedicated end-to-end setup <em>[3]</em>.</p> },
      { id: "a2-09-8", marks: 3, lines: 5, prompt: <><b>Choose a method for a large email sent across the Internet and justify it.</b><p>Write: <em>I choose… because… therefore…</em></p></>, answer: <p>Choose <strong>packet switching</strong> <em>[1]</em> because links are shared and capacity is used only when packets are sent <em>[1]</em>; packets can be rerouted, and a reliability protocol may retransmit missing data if a route is busy or fails <em>[1]</em>.</p> },
      { id: "a2-09-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Describe circuit switching and state one benefit and one drawback.</b></p><p>Adapted from 9618/31 O/N 2024 Q3. [4]</p></>, answer: <p>A dedicated circuit is established before data transfer <em>[1]</em> and the same route/reserved bandwidth is used for the session <em>[1]</em>. One benefit is ordered, predictable continuous delivery or guaranteed capacity <em>[1]</em>. One drawback is setup delay, wasted idle capacity or failure of the fixed route <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson09Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Give students one familiar message and two possible journeys.", prompt: "Alice wants to send ‘MEET AT 3’ to Bob. Would a traditional telephone call and an email use the network in the same way?", source: "2027–2029 syllabus §14.2 p.33; coursebook Chapter 17 §17.01 printed pp.330–331.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch17 §17.01" syllabusLabel="SYLLABUS 14.2" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 09 · 90 MINUTES</span><h1>One message.<br /><em>Two journeys.</em></h1><p>Alice sends <strong>“MEET AT 3”</strong> to Bob. We will trace a traditional telephone call and an email.</p></div><div className="a2-at-hero" role="img" aria-label="One message travelling through a reserved circuit or as independent packets"><strong>MEET AT 3</strong><span>CALL</span><span>EMAIL</span><span>ONE MESSAGE</span><span>TWO METHODS</span></div></section></Slide> },
    { time: "5 min", focus: "Build only the vocabulary needed for the two journeys.", prompt: "Students point to each item on the route and say its job in one short phrase.", source: "Coursebook Chapter 17 §17.01 pp.330–331; bridge from earlier network lessons.", content: <Slide number="02" eyebrow="START WITH THE ROUTE" sourceLabel="TEXTBOOK pp.330–331" syllabusLabel="14.2 · VOCABULARY" title="Four words are enough to start the story." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "MESSAGE", title: "what Alice sends", body: "The complete user data." }, { eyebrow: "PACKET", title: "a small piece", body: "One numbered part of a message." }, { eyebrow: "LINK", title: "one connection", body: "A single hop between two nodes." }, { eyebrow: "ROUTE", title: "the whole journey", body: "A chain of links from Alice to Bob." }]} /><p className="a2-rule"><b>ANCHOR</b><span>A route is made of links. Circuit and packet switching differ in how those links are shared.</span></p></Slide> },
    { time: "5 min", focus: "Make the central contrast explicit before adding detail.", prompt: "Ask: who keeps the path — one connection, or many packets sharing links?", source: "Syllabus §14.2 p.33; coursebook p.330.", content: <Slide number="03" eyebrow="THE BIG QUESTION" sourceLabel="TEXTBOOK p.330" syllabusLabel="14.2 · CORE CONTRAST" title="How do the two methods share the same links?" className="a2-slide a2-at-slide"><section className="a2-dr-split"><article><span>CIRCUIT SWITCHING</span><b>Keep one path</b><p>Reserve an end-to-end route first. The call keeps it until the connection ends.</p><code>reserve → send → release</code></article><article><span>PACKET SWITCHING</span><b>Share the links</b><p>Split the message. Each packet competes for a next hop when it is ready.</p><code>split → label → forward → rebuild</code></article></section><p className="a2-rule"><b>ONE SENTENCE</b><span>Circuit protects a route for one conversation; packet switching shares routes between many conversations.</span></p></Slide> },
    { time: "7 min", focus: "Rehearse the circuit answer as four observable actions.", prompt: "Students say the sentence starters aloud: first, next, during, finally.", source: "Coursebook §17.01 p.330; 9618/31 O/N 2024 Q3.", content: <Slide number="04" eyebrow="JOURNEY 1 · CIRCUIT" sourceLabel="TEXTBOOK p.330 · O/N 2024 Q3" syllabusLabel="14.2 · OPERATION" title="A circuit-switched call reserves its lane before speaking." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "FIRST", title: "Set up", body: "Find an end-to-end route." }, { eyebrow: "NEXT", title: "Reserve", body: "Hold the route and bandwidth." }, { eyebrow: "DURING", title: "Transfer", body: "All voice data uses that circuit." }, { eyebrow: "FINALLY", title: "Release", body: "Free the resources." }]} /><p className="a2-rule"><b>EXAM VERB</b><span>Established before transmission → reserved for the session → released afterwards.</span></p></Slide> },
    { time: "6 min", focus: "Use a silence example so ‘reserved’ has a concrete consequence.", prompt: "During a pause in the traditional call, can another user use this reserved capacity? Why not?", source: "Coursebook p.330; syllabus §14.2 benefits and drawbacks.", content: <Slide number="05" eyebrow="CIRCUIT · SEE THE CONSEQUENCE" sourceLabel="TEXTBOOK p.330" syllabusLabel="14.2 · BENEFITS" title="A traditional call keeps its lane—even when nobody is speaking." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "TALK", title: "Voice data", body: "The reserved route carries the call." }, { eyebrow: "PAUSE", title: "Silence", body: "The route stays unavailable to others." }, { eyebrow: "TALK", title: "Voice resumes", body: "The same route is ready immediately." }]} /><p className="a2-rule"><b>YOUR TURN</b><span>Reserved bandwidth gives predictable delay and ordered delivery, but silence can waste capacity.</span></p></Slide> },
    { time: "6 min", focus: "Turn each circuit design choice into one cause-and-effect sentence.", prompt: "Students complete: ‘Because the route is fixed…, therefore…’", source: "Coursebook p.330; 9618/31 O/N 2024 Q3 mark scheme.", content: <Slide number="06" eyebrow="CIRCUIT · EVALUATE" sourceLabel="O/N 2024 Q3 · TEXTBOOK p.330" syllabusLabel="14.2 · EVALUATE" title="Do not memorise drawbacks: explain what the design causes." className="a2-slide a2-at-slide"><CompareTable headers={["Design choice", "What follows", "Exam wording"]} rows={[["Set up first", "Initial delay before data", "setup is needed before transfer"], ["Reserve while idle", "Unused capacity cannot be shared", "bandwidth may be wasted"], ["Keep one fixed route", "A broken link ends the session", "the route must be rebuilt"]]} /><p className="a2-rule"><b>CHAIN</b><span>Design choice → network consequence → effect on the user.</span></p></Slide> },
    { time: "7 min", focus: "Contrast the packet journey with the circuit journey using the same message.", prompt: "What changes first: the route, or the message itself?", source: "Coursebook §17.01 pp.330–331; syllabus §14.2.", content: <Slide number="07" eyebrow="JOURNEY 2 · PACKET" sourceLabel="TEXTBOOK pp.330–331" syllabusLabel="14.2 · OPERATION" title="Packet switching changes the message before it travels." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SPLIT", title: "Message → pieces", body: "Make smaller packets." }, { eyebrow: "LABEL", title: "Add headers", body: "Address and number each one." }, { eyebrow: "FORWARD", title: "Choose each hop", body: "Routers send packets independently." }, { eyebrow: "REBUILD", title: "Join at Bob", body: "Order and reassemble the message." }]} /><p className="a2-rule"><b>KEY DIFFERENCE</b><span>No dedicated end-to-end circuit is reserved before the message starts.</span></p></Slide> },
    { time: "5 min", focus: "Separate the part being delivered from the information that guides delivery.", prompt: "Which field tells a router where to send the packet? Which field helps Bob restore order?", source: "Coursebook §17.01 pp.330–331; 9618/32 O/N 2024 Q1.", content: <Slide number="08" eyebrow="INSIDE ONE PACKET" sourceLabel="TEXTBOOK pp.330–331 · O/N 2024 Q1" syllabusLabel="14.2 · PACKET" title="Payload is the message piece; the header is its travel label." className="a2-slide a2-at-slide"><section className="a2-dr-split"><article><span>PAYLOAD</span><b>Part of “MEET AT 3”</b><p>The actual user data carried by this packet.</p><code>MEET</code></article><article><span>HEADER</span><b>Directions + order</b><p>Destination address routes it; sequence number helps Bob put pieces back.</p><code>destination · sequence</code></article></section><p className="a2-rule"><b>REMEMBER</b><span>Routers need the destination. Bob needs the sequence number.</span></p></Slide> },
    { time: "7 min", focus: "Show that independent routes are possible, not compulsory.", prompt: "If P02 meets congestion on the upper route, what could happen to P03?", source: "Coursebook pp.330, 333; 9618 Paper 3 packet-switching mark points.", content: <Slide number="09" eyebrow="PACKETS MAY DIVERGE" sourceLabel="TEXTBOOK pp.330,333 · PAPER 3" syllabusLabel="14.2 · ROUTING" title="One message can arrive by more than one route." className="a2-slide a2-at-slide"><PacketBranchRoute /><p className="a2-rule"><b>ROUTER STEP</b><span>At each hop: read the destination → choose a next hop → forward. Packets are independent, so paths may differ and arrival may be out of order.</span></p></Slide> },
    { time: "6 min", focus: "Make destination recovery a visible, ordered routine.", prompt: "Which step happens at the receiver, not at an intermediate router?", source: "Coursebook pp.330–331; syllabus §14.2 message passing.", content: <Slide number="10" eyebrow="AT BOB · RECOVERY" sourceLabel="TEXTBOOK pp.330–331" syllabusLabel="14.2 · DESTINATION" title="Bob uses the numbers to turn packets back into one message." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "CHECK", title: "Read numbers", body: "Find the expected order." }, { eyebrow: "HOLD", title: "Buffer early pieces", body: "Keep a packet that arrived too soon." }, { eyebrow: "RECOVER", title: "If supported, request gap", body: "A reliability service can ask again." }, { eyebrow: "JOIN", title: "Reassemble", body: "Deliver the complete message." }]} /><p className="a2-rule"><b>BOUNDARY</b><span>Routers forward packets. The destination reorders and reassembles; retransmission depends on the service/protocol.</span></p></Slide> },
    { time: "6 min", focus: "Evaluate packet switching with the same cause-and-effect method.", prompt: "Which row is a benefit, and which row is the price paid for flexibility?", source: "Coursebook pp.330–331; published 9618 Paper 3 mark schemes.", content: <Slide number="11" eyebrow="PACKET · EVALUATE" sourceLabel="TEXTBOOK pp.330–331 · PAPER 3" syllabusLabel="14.2 · EVALUATE" title="Sharing is efficient, but it makes timing less predictable." className="a2-slide a2-at-slide"><CompareTable headers={["Design choice", "What follows", "Exam wording"]} rows={[["Share links on demand", "Bursty users can use spare capacity", "better utilisation"], ["Route packets independently", "A busy or failed link can be avoided", "more resilient"], ["Add a header to every packet", "Extra bits use bandwidth", "header overhead"], ["Rebuild at Bob", "Waiting and buffering may be needed", "variable delay / processing"]]} /><p className="a2-rule"><b>CHAIN</b><span>Flexibility → shared use and recovery; the cost is overhead and less predictable arrival.</span></p></Slide> },
    { time: "7 min", focus: "Compare methods by four tests instead of recalling two separate lists.", prompt: "Turn each row into a sentence beginning ‘Circuit…, whereas packet…’.", source: "Coursebook §17.01; 9618/31 M/J 2022 Q3.", content: <Slide number="12" eyebrow="ONE COMPARISON GRID" sourceLabel="TEXTBOOK §17.01 · M/J 2022 Q3" syllabusLabel="14.2 · COMPARE" title="Use the same four tests for both journeys." className="a2-slide a2-at-slide"><CompareTable headers={["Test", "Circuit switching", "Packet switching"]} rows={[["Route", "one dedicated route", "packets may use different routes"], ["Capacity", "reserved for the connection", "shared when a packet is ready"], ["Timing", "ordered, predictable", "variable, possibly out of order"], ["Failure", "fixed route breaks", "packets may be rerouted"]]} /><p className="a2-rule"><b>YOUR TURN</b><span>Write one complete “Circuit…, whereas packet…” sentence for each row.</span></p></Slide> },
    { time: "6 min", focus: "Read application clues and justify the method rather than guessing from a familiar device.", prompt: "For each row, underline the clue and say ‘therefore’ before the choice.", source: "Syllabus §14.2 applications; coursebook p.330.", content: <Slide number="13" eyebrow="CHOOSE FROM THE CLUE" sourceLabel="SYLLABUS 14.2 · TEXTBOOK p.330" syllabusLabel="14.2 · APPLY" title="The workload tells you which trade-off matters." className="a2-slide a2-at-slide"><CompareTable headers={["Workload clue", "Choice", "Because…"]} rows={[["traditional telephone / leased line", "circuit", "a dedicated channel gives predictable timing"], ["large email or file", "packet", "shared capacity and recovery"], ["many users with bursty traffic", "packet", "idle capacity is not locked away"], ["Internet voice or video", "packet", "Internet links are shared; protocols manage loss"]]} /><p className="a2-rule"><b>JUSTIFY</b><span>Choice + one feature + the consequence for this workload. Do not assume every modern call is circuit-switched.</span></p></Slide> },
    { time: "8 min", focus: "Model a short 5-mark response with one mark point per sentence.", prompt: "Give students four minutes closed-book, then reveal and annotate the operation, benefit and drawback marks.", source: "Adapted from Cambridge 9618/31 O/N 2024 Q3.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/31 O/N 2024 · Q3" syllabusLabel="14.2 · 5 MARKS" title="Build the answer in a fixed order: operation → consequence → evaluation." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/31 O/N 2024 · Q3 · ADAPTED" marks={5} prompt={<p>Describe circuit switching, and state one benefit and one drawback. [5]</p>} answer={<ul><li>A dedicated circuit is established before transmission. [1]</li><li>Route and bandwidth remain reserved for the session. [1]</li><li>All data follows the same route / arrives in order. [1]</li><li>Benefit: predictable delay or guaranteed capacity for continuous data. [1]</li><li>Drawback: setup delay, wasted idle capacity or fixed-route failure. [1]</li></ul>} /><p className="a2-rule"><b>PLAN</b><span>Do not list five facts: make each sentence earn one distinct marking point.</span></p></Slide> },
    { time: "5 min", focus: "Retrieve the complete journey without adding new terminology.", prompt: "Students explain one call and one email in four sentences, then choose the method for a video call.", source: "Lesson synthesis aligned to syllabus §14.2 p.33; coursebook pp.330–331.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK §17.01 · SYLLABUS p.33" syllabusLabel="SYLLABUS 14.2" title="Say the journey, then justify the trade-off." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>01</span><p>Circuit: set up → reserve → transfer → release.</p></article><article><span>02</span><p>Packet: split → label → forward → rebuild.</p></article><article><span>03</span><p>One cause → one consequence for each method.</p></article><article><span>04</span><p>Choose for email and justify with a feature.</p></article></section><div className="homework-callout"><b>HOMEWORK 09</b><span>30 marks · two journeys + comparison · inline answers</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="09" title="Circuit and packet switching" syllabusLabel="SYLLABUS 14.2" sourceLabel="TEXTBOOK Ch17 §17.01 · pp.330–331" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus §14.2 p.33 · endorsed coursebook Chapter 17 §17.01 printed pp.330–331 · verified 2022–2024 Paper 3 questions and mark schemes" sourceDetail="The lesson now follows one message from sender to receiver. Each method is taught as operation → consequence → application, with the comparison grid and exam answer built only after the journeys are clear." />;
}
