"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { PacketRoute } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Circuit switching", subtitle: "Describe the reserved route and evaluate it", marks: 10,
    questions: [
      { id: "a2-09-1", marks: 3, lines: 5, prompt: <><b>Describe how circuit switching establishes and uses a connection.</b></>, answer: <p>A dedicated end-to-end circuit is established before transmission <em>[1]</em>. All data uses the same reserved route/bandwidth <em>[1]</em>, and the circuit is released after the communication ends <em>[1]</em>.</p> },
      { id: "a2-09-2", marks: 3, lines: 4, prompt: <><b>Give three benefits of circuit switching.</b></>, answer: <p>Any three: reserved/guaranteed bandwidth; predictable delay/low jitter; data arrives in order; no destination reassembly; suitable for a continuous real-time stream <em>[3]</em>.</p> },
      { id: "a2-09-3", marks: 4, lines: 5, prompt: <><b>Give two drawbacks of circuit switching and explain each.</b></>, answer: <p>Setup takes time before data can flow <em>[2]</em>. Reserved capacity cannot be used by others while the circuit is idle, so bandwidth is wasted <em>[2]</em>. Accept route failure ending the session as another explained drawback.</p> },
    ],
  },
  {
    code: "B", title: "Packet switching", subtitle: "Follow independently routed packets", marks: 10,
    questions: [
      { id: "a2-09-4", marks: 3, lines: 5, prompt: <><b>Describe how a message is prepared for packet switching.</b></>, answer: <p>The message is divided into packets <em>[1]</em>. Each packet contains a payload and header <em>[1]</em>, with information such as source/destination address and sequence number <em>[1]</em>.</p> },
      { id: "a2-09-5", marks: 3, lines: 5, prompt: <><b>Explain why packets from one message may follow different routes.</b></>, answer: <p>Packets are routed independently <em>[1]</em>. A router reads the destination and routing information <em>[1]</em>, choosing an available/best next hop according to congestion or network state <em>[1]</em>.</p> },
      { id: "a2-09-6", marks: 4, lines: 6, prompt: <><b>Explain what happens when packets are missing or arrive out of order.</b></>, answer: <p>Sequence numbers reveal the correct order <em>[1]</em> and the receiver reorders/reassembles the message <em>[1]</em>. A missing packet is detected <em>[1]</em> and requested/sent again <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Compare and select", subtitle: "Link the method to an application", marks: 10,
    questions: [
      { id: "a2-09-7", marks: 3, lines: 5, prompt: <><b>Give three paired differences</b> between circuit and packet switching.</>, answer: <p>Any three paired contrasts: dedicated end-to-end circuit vs no dedicated circuit/shared links; whole stream on one route vs packets whose routes may differ; reserved bandwidth vs shared capacity; in-order vs possibly out-of-order; setup required vs no end-to-end circuit setup; no reassembly vs reassembly <em>[3]</em>.</p> },
      { id: "a2-09-8", marks: 3, lines: 5, prompt: <><b>Select a switching method</b> for a large email sent across the Internet and justify it.</>, answer: <p>Use <strong>packet switching</strong> <em>[1]</em>. Shared links use capacity efficiently <em>[1]</em>, and packets can be rerouted/retransmitted if a link fails or data is lost <em>[1]</em>.</p> },
      { id: "a2-09-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Describe circuit switching and state one benefit and one drawback.</b></p><p>Adapted from 9618/31 O/N 2024 Q3. [4]</p></>, answer: <p>Dedicated circuit established before data transfer <em>[1]</em>; same route/reserved bandwidth throughout <em>[1]</em>; benefit such as ordered continuous delivery/guaranteed bandwidth <em>[1]</em>; drawback such as setup delay, wasted idle capacity or total route failure <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson09Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Contrast one reserved path with shared routed packets.", prompt: "Which method better matches a continuous call and which a large email?", source: "2027–2029 syllabus 14.2; coursebook Chapter 17 §17.01 printed pp.330–331.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch17 §17.01" syllabusLabel="SYLLABUS 14.2" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 09 · 90 MINUTES</span><h1>Reserve one route.<br /><em>Or share the network.</em></h1><p>Circuit switching · packet switching · benefits · drawbacks · applications</p></div><div className="a2-at-hero" role="img" aria-label="A circuit and packets travelling through a network"><strong>TRANSFER</strong><span>CIRCUIT</span><span>PACKET 01</span><span>PACKET 02</span><span>ROUTE</span></div></section></Slide> },
    { time: "5 min", focus: "Map operation, evaluation and application to syllabus 14.2.", prompt: "Students turn each syllabus verb into a success criterion.", source: "Syllabus p.33; coursebook pp.330–331; recent Paper 3 questions.", content: <Slide number="02" eyebrow="SOURCE MAP" sourceLabel="SYLLABUS p.33 · TEXTBOOK pp.330–331" syllabusLabel="14.2 · SWITCHING" title="Describe the route, evaluate it, then choose it for a workload." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "OPERATION", title: "How does it move?", body: "Dedicated circuit or independent packets." }, { eyebrow: "EVALUATION", title: "What is gained or lost?", body: "Bandwidth, delay, resilience and overhead." }, { eyebrow: "APPLICATION", title: "Where does it fit?", body: "Continuous reserved stream or bursty Internet data." }]} /></Slide> },
    { time: "5 min", focus: "Retrieve the difference between a link and an end-to-end route.", prompt: "Draw one route containing three individual links.", source: "Bridge from syllabus 14.1 Internet and Link layers.", content: <Slide number="03" eyebrow="DO NOW · NETWORK ROUTE" sourceLabel="BRIDGE FROM LESSON 07" syllabusLabel="14.2 · FOUNDATION" title="A route is a sequence of links and switching nodes between hosts." className="a2-slide a2-at-slide"><PacketRoute nodes={[{ label: "Host A", detail: "sender", state: "host" }, { label: "S1", detail: "switching node" }, { label: "S2", detail: "switching node" }, { label: "Host B", detail: "receiver", state: "host" }]} packets={["LINK 1", "LINK 2", "LINK 3"]} /></Slide> },
    { time: "6 min", focus: "Describe circuit establishment, use and release.", prompt: "Students narrate the three phases using before, during and after.", source: "Coursebook §17.01 p.330; 9618/31 O/N 2024 Q3.", content: <Slide number="04" eyebrow="CIRCUIT SWITCHING" sourceLabel="TEXTBOOK p.330 · O/N 2024 Q3" syllabusLabel="14.2 · OPERATION" title="Establish a dedicated circuit before any user data is sent." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SET UP", title: "Find end-to-end route" }, { eyebrow: "RESERVE", title: "Hold route + bandwidth" }, { eyebrow: "TRANSFER", title: "All data uses same circuit" }, { eyebrow: "RELEASE", title: "Free resources at the end" }]} /></Slide> },
    { time: "6 min", focus: "Explain linked benefits of a reserved channel.", prompt: "Why do in-order arrival and predictable delay follow from one route?", source: "Coursebook p.330; published 9618 mark schemes.", content: <Slide number="05" eyebrow="CIRCUIT · BENEFITS" sourceLabel="TEXTBOOK p.330" syllabusLabel="14.2 · EVALUATE" title="Reserved resources make the stream predictable." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "BANDWIDTH", title: "Reserved capacity", body: "Other sessions cannot take the circuit's allocation." }, { eyebrow: "ORDER", title: "One route", body: "Data arrives in sequence; no packet reassembly." }, { eyebrow: "TIMING", title: "Stable delay", body: "Useful for continuous real-time communication." }]} /></Slide> },
    { time: "6 min", focus: "Explain circuit costs and failure modes.", prompt: "Link each drawback to exclusive use of a fixed route.", source: "Coursebook p.330; 9618/31 O/N 2024 Q3.", content: <Slide number="06" eyebrow="CIRCUIT · DRAWBACKS" sourceLabel="O/N 2024 Q3" syllabusLabel="14.2 · EVALUATE" title="Exclusive capacity helps one connection by denying it to others." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "SETUP", title: "Delay before transfer", body: "The route must be established first." }, { eyebrow: "IDLE", title: "Capacity can be wasted", body: "Reserved links remain unavailable even during silence." }, { eyebrow: "FAILURE", title: "Fixed route breaks", body: "The session cannot simply use another path without rebuilding." }]} /></Slide> },
    { time: "6 min", focus: "Identify packet payload and header fields.", prompt: "Which header field supports ordering and which supports routing?", source: "Coursebook §17.01 pp.330–331; 9618/32 O/N 2024 Q1.", content: <Slide number="07" eyebrow="ANATOMY OF A PACKET" sourceLabel="TEXTBOOK pp.330–331 · O/N 2024 Q1" syllabusLabel="14.2 · PACKET" title="The payload carries data; the header makes independent delivery possible." className="a2-slide a2-at-slide"><CompareTable headers={["Field", "Purpose", "Used by"]} rows={[["destination address", "identify where packet must go", "routers"], ["source address", "identify sender / return path", "network endpoints"], ["sequence number", "restore message order / find gaps", "receiver"], ["error/control data", "check integrity and recovery", "receiver / transport"]]} /></Slide> },
    { time: "6 min", focus: "Describe the full packet-switching sequence.", prompt: "Use split, route, receive and rebuild as sentence starters.", source: "Coursebook pp.330–331; syllabus 14.2.", content: <Slide number="08" eyebrow="PACKET SWITCHING" sourceLabel="TEXTBOOK pp.330–331" syllabusLabel="14.2 · OPERATION" title="Split the message, route packets independently, then reassemble." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SPLIT", title: "Message → packets" }, { eyebrow: "LABEL", title: "Add headers + sequence" }, { eyebrow: "ROUTE", title: "Routers choose each next hop" }, { eyebrow: "REBUILD", title: "Order, check, reassemble" }]} /></Slide> },
    { time: "6 min", focus: "Explain independent paths and variable arrival order.", prompt: "Predict the arrival order if P02 takes the shorter route.", source: "Coursebook p.330; 9618 Paper 3 packet-switching questions.", content: <Slide number="09" eyebrow="INDEPENDENT ROUTES" sourceLabel="9618/32 O/N 2024 · Q1" syllabusLabel="14.2 · ROUTING" title="Packets from one message need not travel together." className="a2-slide a2-at-slide"><PacketRoute nodes={[{ label: "Host A", detail: "split message", state: "host" }, { label: "R1", detail: "P01 → upper; P02 → lower" }, { label: "R2 / R3", detail: "different congestion" }, { label: "Host B", detail: "reorder + reassemble", state: "host" }]} /></Slide> },
    { time: "6 min", focus: "Evaluate shared-bandwidth and resilience benefits.", prompt: "Explain why a failed link need not lose the whole message.", source: "Coursebook pp.330–331; published 9618 mark schemes.", content: <Slide number="10" eyebrow="PACKET · BENEFITS" sourceLabel="9618 PAPER 3 MARK POINTS" syllabusLabel="14.2 · EVALUATE" title="Sharing and rerouting use network capacity flexibly." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "UTILISATION", title: "Links are shared", body: "Bursty traffic does not reserve idle capacity." }, { eyebrow: "RESILIENCE", title: "Choose another route", body: "Later packets can bypass a failed or congested link." }, { eyebrow: "RECOVERY", title: "Resend only what is missing", body: "Sequence/control data identifies the gap." }]} /></Slide> },
    { time: "7 min", focus: "Evaluate overhead, delay and destination processing.", prompt: "Which costs occur at every packet and which at the receiver?", source: "Coursebook pp.330–331; 9618/32 O/N 2024 Q1.", content: <Slide number="11" eyebrow="PACKET · DRAWBACKS" sourceLabel="O/N 2024 Q1" syllabusLabel="14.2 · EVALUATE" title="Flexibility requires headers, routing decisions and reconstruction." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "OVERHEAD", title: "Header on every packet", body: "Address and control bits consume bandwidth." }, { eyebrow: "VARIABLE DELAY", title: "Congestion and route length", body: "Arrival time and order are not guaranteed." }, { eyebrow: "DESTINATION", title: "Buffer + reassemble", body: "Memory and processing are needed; missing packets wait or resend." }]} /></Slide> },
    { time: "7 min", focus: "Compare both methods through paired features.", prompt: "Turn each row into a full 'whereas' sentence.", source: "Coursebook §17.01; 9618/31 M/J 2022 Q3.", content: <Slide number="12" eyebrow="CIRCUIT VS PACKET" sourceLabel="TEXTBOOK §17.01 · M/J 2022 Q3" syllabusLabel="14.2 · COMPARE" title="Compare the consequence, not just the vocabulary." className="a2-slide a2-at-slide"><CompareTable headers={["Feature", "Circuit switching", "Packet switching"]} rows={[["route", "dedicated; same route", "no dedicated route; packets may differ"], ["unit", "continuous data stream", "message split into packets"], ["capacity", "reserved", "links shared; used on demand"], ["arrival", "ordered, predictable", "variable, possibly out of order"], ["failure", "circuit breaks", "packets may reroute"], ["receiver", "little/no reassembly", "buffer, order and reassemble"]]} /></Slide> },
    { time: "7 min", focus: "Select a method from workload evidence.", prompt: "Justify each choice with one feature and one consequence.", source: "Syllabus 14.2 applications; coursebook p.330.", content: <Slide number="13" eyebrow="CHOOSING A METHOD" sourceLabel="SYLLABUS 14.2" syllabusLabel="14.2 · APPLY" title="The scenario supplies the decision evidence." className="a2-slide a2-at-slide"><CompareTable headers={["Workload", "Likely choice", "Linked reason"]} rows={[["reserved continuous point-to-point stream", "circuit", "guaranteed bandwidth / ordered delivery"], ["email or file over the Internet", "packet", "shared capacity and recovery"], ["bursty traffic from many users", "packet", "idle links are not reserved"], ["legacy fixed telephone circuit", "circuit", "dedicated connection for call duration"]]} /></Slide> },
    { time: "8 min", focus: "Practise circuit-switching operation and evaluation.", prompt: "One operation sentence, one benefit, one drawback, one linked detail.", source: "Adapted from Cambridge 9618/31 O/N 2024 Q3.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/31 O/N 2024 · Q3" syllabusLabel="14.2 · 5 MARKS" title="Explain circuit switching, then evaluate it." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/31 O/N 2024 · Q3 · ADAPTED" marks={5} prompt={<p>Describe circuit switching and give one benefit and one drawback for a real-time connection. [5]</p>} answer={<ul><li>A dedicated circuit is established before transmission and retained for the session. [2]</li><li>All data uses the same route / reserved bandwidth. [1]</li><li>Benefit: ordered continuous delivery, predictable delay or guaranteed capacity. [1]</li><li>Drawback: setup time, idle reserved capacity or failure of the fixed route. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Check operation, comparison and application.", prompt: "Students give one complete packet journey and three paired differences.", source: "Lesson synthesis aligned to syllabus 14.2.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK §17.01 · SYLLABUS p.33" syllabusLabel="SYLLABUS 14.2" title="Can you justify the route rather than name it?" className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>01</span><p>Describe circuit setup and release.</p></article><article><span>02</span><p>Name four packet header fields.</p></article><article><span>03</span><p>Give three paired differences.</p></article><article><span>04</span><p>Choose for email and justify.</p></article></section><div className="homework-callout"><b>HOMEWORK 09</b><span>30 marks · switching comparison + applications · inline answers</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="09" title="Circuit and packet switching" syllabusLabel="SYLLABUS 14.2" sourceLabel="TEXTBOOK Ch17 §17.01 · pp.330–331" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus §14.2 p.33 · endorsed coursebook Chapter 17 §17.01 printed pp.330–331 · verified 2022–2024 Paper 3 questions and mark schemes" sourceDetail="Both methods are taught as operation → consequence → application, so comparison points are linked rather than memorised as isolated lists." />;
}
