"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { CertificateCard, KeyJourney } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Quantum cryptography", subtitle: "Purpose, mechanism, benefit and limitation", marks: 10,
    questions: [
      { id: "a2-22-1", marks: 3, lines: 6, prompt: <><b>State the main purpose of quantum cryptography</b> and describe its central detection principle.</>, answer: <p>Its main purpose is secure encryption-key distribution/quantum key distribution <em>[1]</em>. Information is encoded using quantum states of particles such as photons <em>[1]</em>; measuring/intercepting them changes/disturbs the state and can reveal eavesdropping <em>[1]</em>.</p> },
      { id: "a2-22-2", marks: 3, lines: 6, prompt: <><b>Explain two benefits of quantum cryptography.</b></>, answer: <p>Eavesdropping can be detected because measurement disturbs the quantum state <em>[1+1]</em>. A compromised key exchange can be discarded before encrypted data is trusted, and security rests on physical properties rather than only computational difficulty <em>[1]</em>.</p> },
      { id: "a2-22-3", marks: 4, lines: 7, prompt: <><b>Explain four practical drawbacks of quantum cryptography.</b></>, answer: <p>Any four developed points: specialised photon source/detector hardware <em>[1]</em>; high cost <em>[1]</em>; restricted distance/signal loss <em>[1]</em>; dedicated fibre or line-of-sight infrastructure <em>[1]</em>; lower practical key rates/error sensitivity; it distributes keys rather than encrypting all application data.</p> },
    ],
  },
  {
    code: "B", title: "SSL/TLS", subtitle: "Authenticate, establish keys, then protect records", marks: 10,
    questions: [
      { id: "a2-22-4", marks: 3, lines: 6, prompt: <><b>State three purposes of SSL/TLS in client-server communication.</b></>, answer: <p>Confidentiality through encryption <em>[1]</em>; server authentication using a certificate (and optional client authentication) <em>[1]</em>; integrity so unauthorised changes are detected <em>[1]</em>.</p> },
      { id: "a2-22-5", marks: 3, lines: 6, prompt: <><b>Describe the role of the server certificate during a TLS handshake.</b></>, answer: <p>The server sends its digital certificate <em>[1]</em>. The client verifies the CA signature, identity/domain and validity <em>[1]</em>, then obtains/trusts the server public key for authentication/key-establishment purposes <em>[1]</em>.</p> },
      { id: "a2-22-6", marks: 4, lines: 7, prompt: <p><b>Explain why TLS normally changes to symmetric session encryption after authentication and key establishment.</b></p>, answer: <p>Public-key or asymmetric operations support authentication or secure key agreement <em>[1]</em>. Both sides derive or obtain a shared session secret <em>[1]</em>. Symmetric encryption is faster and less computationally expensive <em>[1]</em>, so it efficiently protects the application data for that session <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Certificates and signatures", subtitle: "A CA binds identity to a public key", marks: 10,
    questions: [
      { id: "a2-22-7", marks: 3, lines: 6, prompt: <><b>Describe how an organisation acquires a digital certificate.</b></>, answer: <p>It generates a key pair and submits identity/domain details plus its public key/CSR to a certificate authority <em>[1]</em>. The CA verifies identity/domain control <em>[1]</em> and issues a certificate containing the identity and public key, signed with the CA&apos;s private key <em>[1]</em>.</p> },
      { id: "a2-22-8", marks: 3, lines: 6, prompt: <><b>Explain how a digital signature is produced.</b></>, answer: <p>A hash function produces a message digest <em>[1]</em>; the sender signs/encrypts the digest using the sender&apos;s private key <em>[1]</em>; the signature is sent with the message and the sender&apos;s certificate makes the verified public key and identity available <em>[1]</em>.</p> },
      { id: "a2-22-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Explain how a recipient verifies a signed message using the sender&apos;s digital certificate.</b></p><p>Adapted from 9618/32 M/J 2022 Q7. [4 adapted marks]</p></>, answer: <p>Validate the certificate/CA signature and obtain the authenticated sender public key <em>[1]</em>. Use that public key to verify the signature/recover the signed digest <em>[1]</em>. Independently hash the received message <em>[1]</em>. Matching digests support sender authenticity and message integrity; a mismatch rejects it <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson22Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Link quantum key distribution, TLS and certificates through trust.", prompt: "How does a client know both that a channel is private and who is at the other end?", source: "2027–2029 syllabus 17.1; coursebook Chapter 21 printed pp.390–395.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch21" syllabusLabel="SYLLABUS 17.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 22 · 90 MINUTES</span><h1>Establish trust.<br /><em>Protect the session.</em></h1><p>quantum cryptography · SSL/TLS · certificates · digital signatures</p></div><div className="a2-at-hero" role="img" aria-label="Certificate trust establishes a protected client-server channel"><strong>TRUSTED CHANNEL</strong><span>PHOTON</span><span>SSL / TLS</span><span>CERTIFICATE</span><span>SIGNATURE</span></div></section></Slide> },
    { time: "5 min", focus: "Map the rest of syllabus 17.1 without omissions.", prompt: "Which item requires purpose, benefits and drawbacks?", source: "Official 2027–2029 syllabus p.36.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.36" syllabusLabel="17.1 · REQUIRED" title="Detect interception, protect sessions and bind identity to a key." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "EVALUATE", title: "Quantum", body: "Purpose, benefits and drawbacks." }, { eyebrow: "AWARENESS", title: "SSL/TLS", body: "Purpose and client-server use." }, { eyebrow: "APPLY", title: "Situations", body: "When a protected channel is appropriate." }, { eyebrow: "UNDERSTAND", title: "Certification", body: "Acquisition and signatures." }]} /></Slide> },
    { time: "5 min", focus: "Define quantum cryptography at syllabus depth.", prompt: "Does quantum cryptography primarily encrypt the whole website session?", source: "Coursebook quantum cryptography pp.393–394; 9618/31 M/J 2023 Q9.", content: <Slide number="03" eyebrow="QUANTUM PURPOSE" sourceLabel="9618/31 M/J 2023 · Q9" syllabusLabel="17.1 · QUANTUM CRYPTOGRAPHY" title="Quantum key distribution detects interception while establishing key material." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "ENCODE", title: "Quantum states", body: "Use properties of photons/particles to carry key information." }, { eyebrow: "MEASURE", title: "Disturbance", body: "An eavesdropper cannot inspect an unknown state invisibly." }, { eyebrow: "COMPARE", title: "Error evidence", body: "Too many mismatches reveal possible interception; discard the key." }]} /></Slide> },
    { time: "6 min", focus: "Trace the detection sequence without claiming the key is transmitted as plaintext.", prompt: "At which point is a suspicious key rejected?", source: "Coursebook pp.393–394.", content: <Slide number="04" eyebrow="QKD SEQUENCE" sourceLabel="TEXTBOOK pp.393–394" syllabusLabel="17.1 · QUANTUM" title="Measurement changes evidence before the final secret is accepted." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SEND", title: "Prepare quantum states" }, { eyebrow: "MEASURE", title: "Receiver samples states" }, { eyebrow: "COMPARE", title: "Discuss bases/sample bits" }, { eyebrow: "DECIDE", title: "Reject if errors suggest interception" }]} /></Slide> },
    { time: "6 min", focus: "Evaluate quantum cryptography rather than presenting it as perfect.", prompt: "Which drawbacks concern physics and which concern deployment?", source: "Coursebook pp.393–394; 2022–2023 Paper 3 mark schemes.", content: <Slide number="05" eyebrow="QUANTUM TRADE-OFF" sourceLabel="TEXTBOOK pp.393–394" syllabusLabel="17.1 · BENEFITS + DRAWBACKS" title="Detectable eavesdropping comes with cost, distance and equipment limits." className="a2-slide a2-at-slide"><CompareTable headers={["Benefits", "Drawbacks"]} rows={[["measurement can reveal interception", "specialist photon hardware and expertise"], ["compromised exchange can be discarded", "high installation/operating cost"], ["security uses physical laws", "range, signal loss and error-rate limits"], ["future-resistant key-distribution principle", "dedicated fibre/line-of-sight; not a complete application protocol"]]} /></Slide> },
    { time: "6 min", focus: "State the three practical security goals of SSL/TLS.", prompt: "Which property lets a browser reject silent message changes?", source: "Coursebook SSL/TLS pp.392–393; 9618/31 O/N 2021 Q8.", content: <Slide number="06" eyebrow="SSL / TLS PURPOSE" sourceLabel="9618/31 O/N 2021 · Q8" syllabusLabel="17.1 · SSL/TLS" title="TLS authenticates, encrypts and protects integrity in client-server communication." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "AUTHENTICATE", title: "Server identity", body: "Validate a CA-signed certificate." }, { eyebrow: "CONFIDENTIALITY", title: "Encrypt records", body: "Observers cannot read application data." }, { eyebrow: "INTEGRITY", title: "Detect changes", body: "Protected records reject tampering." }]} /></Slide> },
    { time: "6 min", focus: "Trace certificate-based authentication at handshake start.", prompt: "What exactly does the client validate before trusting the public key?", source: "Coursebook pp.392–393; O/N 2021 Paper 31 Q8 MS.", content: <Slide number="07" eyebrow="TLS HANDSHAKE · TRUST" sourceLabel="TEXTBOOK pp.392–393" syllabusLabel="17.1 · CLIENT-SERVER" title="A certificate connects the server's identity to its public key." className="a2-slide a2-at-slide"><KeyJourney purpose="CLIENT AUTHENTICATES SERVER" steps={[{ actor: "CLIENT", action: "Sends supported TLS options / hello" }, { actor: "SERVER", action: "Chooses parameters and sends certificate" }, { actor: "CLIENT", action: "Checks CA signature, name and validity", keyLabel: "TRUSTED PUBLIC KEY" }]} /></Slide> },
    { time: "6 min", focus: "Move from asymmetric authentication to session protection.", prompt: "Why are fresh session keys preferred to one permanent shared secret?", source: "Coursebook pp.392–393; verified SSL/TLS mark schemes.", content: <Slide number="08" eyebrow="TLS HANDSHAKE · KEYS" sourceLabel="TEXTBOOK pp.392–393" syllabusLabel="17.1 · CLIENT-SERVER" title="The handshake establishes shared secrets; fast symmetric keys protect records." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "NEGOTIATE", title: "Version + algorithms" }, { eyebrow: "AUTHENTICATE", title: "Certificate + public-key proof" }, { eyebrow: "DERIVE", title: "Shared session keys" }, { eyebrow: "PROTECT", title: "Encrypted, integrity-checked records" }]} /></Slide> },
    { time: "6 min", focus: "Select situations where SSL/TLS is appropriate.", prompt: "What data or action makes each example security-sensitive?", source: "Official syllabus p.36; coursebook pp.392–393.", content: <Slide number="09" eyebrow="WHEN TO USE TLS" sourceLabel="SYLLABUS p.36" syllabusLabel="17.1 · APPROPRIATE SITUATIONS" title="Use a protected channel whenever identity, secrecy or integrity matters." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "LOGIN", title: "Credentials", body: "Passwords and session cookies." }, { eyebrow: "PAYMENT", title: "Transactions", body: "Card details and order integrity." }, { eyebrow: "PORTAL", title: "Private records", body: "Health, school or account data." }, { eyebrow: "API", title: "Machine traffic", body: "Tokens and commands between client and server." }]} /></Slide> },
    { time: "6 min", focus: "Read the contents and trust claim of a digital certificate.", prompt: "Which field binds a subject to a cryptographic capability?", source: "Coursebook digital certification pp.390–392; 9618/31 M/J 2024 Q7.", content: <Slide number="10" eyebrow="DIGITAL CERTIFICATE" sourceLabel="9618/31 M/J 2024 · Q7" syllabusLabel="17.1 · DIGITAL CERTIFICATION" title="A CA-signed record binds an identity to a public key for a validity period." className="a2-slide a2-at-slide"><CertificateCard /></Slide> },
    { time: "7 min", focus: "Explain certificate acquisition from request to issue.", prompt: "Why must the CA verify identity or domain control before signing?", source: "Coursebook pp.390–392; 9618/32 M/J 2022 Q7.", content: <Slide number="11" eyebrow="ACQUIRE A CERTIFICATE" sourceLabel="9618/32 M/J 2022 · Q7" syllabusLabel="17.1 · ACQUISITION" title="The certificate authority verifies the claim before vouching for it." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "OWNER", title: "Generates key pair + CSR" }, { eyebrow: "SUBMIT", title: "Identity/domain + public key" }, { eyebrow: "CA", title: "Verifies identity/control" }, { eyebrow: "ISSUE", title: "Signs certificate with CA private key" }]} /></Slide> },
    { time: "7 min", focus: "Produce and verify a digital signature.", prompt: "Which digest is signed, and which digest is calculated independently?", source: "Coursebook pp.389–391; 9618/32 M/J 2022 Q7.", content: <Slide number="12" eyebrow="DIGITAL SIGNATURE" sourceLabel="9618/32 M/J 2022 · Q7" syllabusLabel="17.1 · CERTIFICATE + SIGNATURE" title="Sign one digest; recompute another; compare them." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SENDER", title: "Hash message" }, { eyebrow: "SIGN", title: "Use sender private key on digest" }, { eyebrow: "RECEIVER", title: "Verify using certified public key" }, { eyebrow: "COMPARE", title: "Re-hash message; digests must match" }]} /></Slide> },
    { time: "7 min", focus: "Clarify the certificate-signature relationship.", prompt: "Does the certificate itself create the sender's signature?", source: "Syllabus p.36; coursebook pp.389–392.", content: <Slide number="13" eyebrow="TRUST CHAIN CLINIC" sourceLabel="SYLLABUS 17.1" syllabusLabel="17.1 · PRECISION" title="The private key signs; the certificate authenticates the public key used to verify." className="a2-slide a2-at-slide"><CompareTable headers={["Object", "Created / controlled by", "Job"]} rows={[["message digest", "hash function", "compact fingerprint of message"], ["digital signature", "sender private key", "bind sender control to digest"], ["digital certificate", "CA signs subject details + public key", "bind identity to verification key"], ["verification", "recipient + sender public key", "compare digest; check authenticity/integrity"]]} /></Slide> },
    { time: "8 min", focus: "Explain an authentic SSL/TLS handshake pattern.", prompt: "Sequence the certificate check before session encryption.", source: "Adapted from Cambridge 9618/31 O/N 2021 Q8.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/31 O/N 2021 · Q8" syllabusLabel="17.1 · 6 MARKS" title="A secure session begins with identity and key agreement." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/31 O/N 2021 · Q8 · ADAPTED" marks={6} prompt={<p>Describe the purpose of SSL/TLS and outline how a client establishes a protected session with a server. [6]</p>} answer={<ul><li>Provides confidentiality/encryption, integrity and server authentication. [2]</li><li>Server sends a digital certificate; client validates the CA signature, identity/domain and validity. [2]</li><li>Handshake agrees/derives a shared symmetric session key. [1]</li><li>Subsequent client-server records are encrypted and integrity protected. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve the complete Chapter 17 trust model.", prompt: "Students finish: quantum detects…, TLS protects…, a CA binds…", source: "Syllabus 17.1 synthesis; coursebook Chapter 21 pp.389–395.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch21 · SYLLABUS p.36" syllabusLabel="17.1 · CHAPTER 17 CLOSE" title="Detect interception, authenticate the endpoint, then protect the data." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>QUANTUM</span><p>Measurement reveals possible interception.</p></article><article><span>SSL / TLS</span><p>Authenticated protected channel.</p></article><article><span>CERTIFICATE</span><p>Identity ↔ public key, signed by CA.</p></article><article><span>SIGNATURE</span><p>Private-key digest, publicly verified.</p></article></section><div className="homework-callout"><b>HOMEWORK 22</b><span>30 marks · quantum, TLS and certification</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="22" title="Quantum cryptography, SSL/TLS and certificates" syllabusLabel="SYLLABUS 17.1" sourceLabel="TEXTBOOK Ch21 · pp.389–395" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 17.1 p.36 · endorsed coursebook Chapter 21 printed pp.389–395 · verified 2021–2024 Paper 3 questions and mark schemes" sourceDetail="The lesson evaluates quantum key distribution, traces certificate-based SSL/TLS client-server protection, and keeps the roles of the sender private key, sender public key and CA-signed certificate distinct." />;
}
