"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { KMap } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "K-map rules", subtitle: "Protect adjacency and group size", marks: 10,
    questions: [
      { id: "a2-16-1", marks: 3, lines: 5, prompt: <><b>State the four-column Gray-code order</b> and explain why ordinary binary order is not used.</>, answer: <p>The order is <code>00, 01, 11, 10</code> <em>[1]</em>. Adjacent cells must differ in exactly one variable <em>[1]</em>, which allows a changing variable to be eliminated from a group <em>[1]</em>.</p> },
      { id: "a2-16-2", marks: 3, lines: 5, prompt: <><b>State three valid K-map grouping rules.</b></>, answer: <p>Any three: group 1,2,4,8… cells; make groups as large as possible; every 1 must be covered; groups may overlap; opposite edges are adjacent/wrap; use as few groups as practical <em>[3]</em>.</p> },
      { id: "a2-16-3", marks: 4, lines: 7, prompt: <><b>Explain how a group becomes one product term.</b></>, answer: <p>Find the variables that remain constant across every cell in the group <em>[1]</em>. Keep a variable uncomplemented when it is always 1 <em>[1]</em>, complemented when it is always 0 <em>[1]</em>, and remove any variable that changes <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Solve the maps", subtitle: "Cover all 1s with the largest groups", marks: 10,
    questions: [
      { id: "a2-16-4", marks: 3, lines: 6, prompt: <><b>Simplify</b> <code>F(A,B,C)=Σm(1,2,3,5,7)</code> using a K-map.</>, answer: <p>The four cells in columns BC=01 and 11 form <code>C</code> <em>[1]</em>. The two top-row cells at BC=11 and 10 form <code>¬A·B</code> <em>[1]</em>. Therefore <code>F = C + ¬A·B</code> <em>[1]</em>.</p> },
      { id: "a2-16-5", marks: 3, lines: 6, prompt: <><b>Explain why the first and last columns of a four-column K-map may form one group.</b></>, answer: <p>K-maps wrap around at their edges <em>[1]</em>. The first and last Gray-code labels 00 and 10 differ in only one bit <em>[1]</em>, so they are logically adjacent even though drawn apart <em>[1]</em>.</p> },
      { id: "a2-16-6", marks: 4, lines: 7, prompt: <><b>Simplify</b> <code>G=Σm(0,2,5,7,8,10,13,15)</code>.</>, answer: <p>The four corner cells group through both wrapped edges to give <code>¬B·¬D</code> <em>[2]</em>. The centre four cells give <code>B·D</code> <em>[1]</em>. Therefore <code>G = ¬B·¬D + B·D</code> <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Chapter 15 checkpoint", subtitle: "Select the right representation", marks: 10,
    questions: [
      { id: "a2-16-7", marks: 3, lines: 5, prompt: <><b>State three benefits</b> of simplifying a logic circuit with a K-map.</>, answer: <p>It gives a fast visual route to a minimal/shorter expression <em>[1]</em>; reduces algebraic error <em>[1]</em>; and usually needs fewer gates/inputs, reducing cost, delay and power consumption <em>[1]</em>.</p> },
      { id: "a2-16-8", marks: 3, lines: 5, prompt: <><b>Correct these two errors:</b> “K-map labels use 00,01,10,11. Every group must be a rectangle of exactly two cells.”</>, answer: <p>Labels use Gray code <code>00,01,11,10</code> so adjacent cells change one bit <em>[2]</em>. Groups may contain any power-of-two number of cells—1,2,4,8…—and should be as large as possible <em>[1]</em>.</p> },
      { id: "a2-16-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE · FORMAT MODELLED</span><p><b>For G(A,B,C,D), a four-variable map has 1s at minterms 0,2,5,7,8,10,13,15. Give the simplified SOP.</b></p><p>Modelled on 9618/32 O/N 2024 Q6(b)–(d). [4 adapted marks]</p></>, answer: <p>Use Gray-code rows and columns <em>[1]</em>. Group the four corners using wrap-around to obtain <code>¬B·¬D</code> <em>[1]</em>; group the central four to obtain <code>B·D</code> <em>[1]</em>; simplified SOP: <code>¬B·¬D + B·D</code> <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson16Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Turn a truth-table pattern into a smaller circuit.", prompt: "What visual feature lets two minterms lose one variable?", source: "2027–2029 syllabus 15.2; coursebook Chapter 19 printed pp.360–362.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch19" syllabusLabel="SYLLABUS 15.2" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 16 · 90 MINUTES</span><h1>See the pattern.<br /><em>Remove the changing bit.</em></h1><p>Karnaugh maps · Gray code · grouping · simplified SOP · Chapter 15 review</p></div><div className="a2-at-hero" role="img" aria-label="Karnaugh map cells grouped to simplify logic"><strong>K-MAP</strong><span>GRAY CODE</span><span>GROUP 1,2,4,8</span><span>WRAP</span><span>SIMPLIFY</span></div></section></Slide> },
    { time: "5 min", focus: "Map the final Chapter 15 outcomes.", prompt: "Students identify the input, method and output of a K-map solution.", source: "Syllabus p.34; coursebook pp.360–362.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.34" syllabusLabel="15.2 · K-MAPS" title="A K-map is a structured visual method for Boolean simplification." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "FILL", title: "Map values", body: "From truth table, SOP or minterms." }, { eyebrow: "GROUP", title: "Adjacent 1s", body: "Powers of two; largest first." }, { eyebrow: "READ", title: "Constant variables", body: "Changing variables disappear." }, { eyebrow: "EXPLAIN", title: "Benefit", body: "Fewer terms and gates." }]} /></Slide> },
    { time: "5 min", focus: "Connect truth tables, SOP and K-maps.", prompt: "Which representation changes the truth function?", source: "Coursebook §19.05 pp.360–362.", content: <Slide number="03" eyebrow="THREE REPRESENTATIONS" sourceLabel="TEXTBOOK pp.360–362" syllabusLabel="15.2 · METHOD" title="The truth function stays the same; only its representation changes." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "ROWS", title: "Truth table output 1" }, { eyebrow: "TERMS", title: "Canonical SOP / minterms" }, { eyebrow: "CELLS", title: "Place 1s in K-map" }, { eyebrow: "GROUPS", title: "Find adjacency" }, { eyebrow: "RESULT", title: "Simplified SOP" }]} /></Slide> },
    { time: "6 min", focus: "Explain Gray-code ordering.", prompt: "Count how many bits change from 01 to 11, and from 10 back to 00.", source: "Coursebook p.362.", content: <Slide number="04" eyebrow="GRAY CODE" sourceLabel="TEXTBOOK p.362" syllabusLabel="15.2 · REQUIRED" title="Adjacent labels differ in exactly one bit: 00, 01, 11, 10." className="a2-slide a2-at-slide"><CompareTable headers={["Step", "Labels", "Changing bit"]} rows={[["1", "00 → 01", "second"], ["2", "01 → 11", "first"], ["3", "11 → 10", "second"], ["wrap", "10 → 00", "first"]]} /></Slide> },
    { time: "6 min", focus: "Fill a 3-variable K-map from minterms.", prompt: "Place each minterm using row A and Gray-code column BC.", source: "Coursebook pp.360–361.", content: <Slide number="05" eyebrow="FILL THE MAP" sourceLabel="TEXTBOOK pp.360–361" syllabusLabel="15.2 · SOLVE" title="Each truth-table row maps to one uniquely labelled cell." className="a2-slide a2-at-slide"><KMap rowLabels={["A=0", "A=1"]} columnLabels={["BC=00", "BC=01", "BC=11", "BC=10"]} values={[[0,1,1,1],[0,1,1,0]]} caption={<><code>F = Σm(1,2,3,5,7)</code> · blue cells contain 1.</>} /></Slide> },
    { time: "6 min", focus: "Apply legal group sizes.", prompt: "Why can a three-cell group never eliminate variables cleanly?", source: "Coursebook pp.360–362.", content: <Slide number="06" eyebrow="GROUP SIZE" sourceLabel="TEXTBOOK pp.360–362" syllabusLabel="15.2 · RULES" title="Groups contain powers of two: 1, 2, 4, 8 … cells." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "1", title: "No elimination", body: "all variables remain" }, { eyebrow: "2", title: "Remove 1 variable", body: "one bit changes" }, { eyebrow: "4", title: "Remove 2 variables", body: "two bits vary" }, { eyebrow: "8", title: "Remove 3 variables", body: "three bits vary" }]} /></Slide> },
    { time: "6 min", focus: "Prioritise largest groups and full coverage.", prompt: "Compare four pairs with one group of four.", source: "Coursebook pp.360–362.", content: <Slide number="07" eyebrow="LARGEST FIRST" sourceLabel="TEXTBOOK pp.360–362" syllabusLabel="15.2 · SIMPLIFY" title="Larger groups remove more variables and create shorter terms." className="a2-slide a2-at-slide"><CompareTable headers={["Choice", "Terms produced", "Quality"]} rows={[["four separate singles", "four 3-variable terms", "not simplified"], ["two pairs", "two 2-variable terms", "better"], ["one group of four", "one 1-variable term", "best when legal"]]} /></Slide> },
    { time: "6 min", focus: "Use overlap when it creates larger groups.", prompt: "Why may one cell legally contribute to two product terms?", source: "Coursebook pp.361–362.", content: <Slide number="08" eyebrow="OVERLAP" sourceLabel="TEXTBOOK pp.361–362" syllabusLabel="15.2 · RULES" title="A 1 may be reused when overlap makes groups larger or covers an isolated neighbour." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "COVER", title: "Every 1 included", body: "No output-one case can be missed." }, { eyebrow: "REUSE", title: "Overlap allowed", body: "A cell can belong to more than one group." }, { eyebrow: "PURPOSE", title: "Shorter expression", body: "Overlap must help create useful groups." }]} /></Slide> },
    { time: "6 min", focus: "Use wrap-around adjacency.", prompt: "Touch the paper edges together: which cells become neighbours?", source: "Coursebook pp.361–362.", content: <Slide number="09" eyebrow="WRAP-AROUND" sourceLabel="TEXTBOOK pp.361–362" syllabusLabel="15.2 · RULES" title="Opposite edges—and all four corners—are adjacent." className="a2-slide a2-at-slide"><KMap rowLabels={["AB=00", "AB=01", "AB=11", "AB=10"]} columnLabels={["CD=00", "CD=01", "CD=11", "CD=10"]} values={[[1,0,0,1],[0,0,0,0],[0,0,0,0],[1,0,0,1]]} caption="The four blue corner cells form one wrapped group." /></Slide> },
    { time: "6 min", focus: "Read a product term from constant variables.", prompt: "Across the four corners, which variables never change?", source: "Coursebook pp.361–362.", content: <Slide number="10" eyebrow="GROUP → TERM" sourceLabel="TEXTBOOK pp.361–362" syllabusLabel="15.2 · DERIVE" title="Keep constants; delete variables that change within the group." className="a2-slide a2-at-slide"><CompareTable headers={["Variable", "Across group", "Write"]} rows={[["A", "0 and 1", "remove"], ["B", "always 0", "¬B"], ["C", "0 and 1", "remove"], ["D", "always 0", "¬D"], ["term", "constants only", "¬B·¬D"]]} /></Slide> },
    { time: "7 min", focus: "Complete a 3-variable worked example.", prompt: "Name the cells covered by C and by ¬A·B.", source: "Coursebook pp.360–362; current Paper 3 K-map method.", content: <Slide number="11" eyebrow="WORKED · 3 VARIABLES" sourceLabel="TEXTBOOK pp.360–362" syllabusLabel="15.2 · SOLVE" title="One group of four plus one overlapping pair covers every 1." className="a2-slide a2-at-slide"><KMap rowLabels={["A=0", "A=1"]} columnLabels={["BC=00", "BC=01", "BC=11", "BC=10"]} values={[[0,1,1,1],[0,1,1,0]]} caption={<><strong>columns 01 + 11 → C</strong> · <strong>top cells 11 + 10 → ¬A·B</strong> · <code>F=C+¬A·B</code></>} /></Slide> },
    { time: "7 min", focus: "Complete a 4-variable wrap-and-centre example.", prompt: "Read constant variables from each four-cell group.", source: "Adapted current Paper 3 K-map format.", content: <Slide number="12" eyebrow="WORKED · 4 VARIABLES" sourceLabel="PAPER 3 K-MAP FORMAT" syllabusLabel="15.2 · SOLVE" title="Two groups of four reduce eight minterms to two terms." className="a2-slide a2-at-slide"><KMap rowLabels={["AB=00", "AB=01", "AB=11", "AB=10"]} columnLabels={["CD=00", "CD=01", "CD=11", "CD=10"]} values={[[1,0,0,1],[0,1,1,0],[0,1,1,0],[1,0,0,1]]} caption={<><strong>four corners → ¬B·¬D</strong> · <strong>centre four → B·D</strong> · <code>G=¬B·¬D+B·D</code></>} /></Slide> },
    { time: "7 min", focus: "Explain the practical benefit of simplification.", prompt: "Turn fewer terms into hardware consequences.", source: "Syllabus explicitly asks for K-map benefits; coursebook p.360, followed by engineering consequences.", content: <Slide number="13" eyebrow="WHY K-MAPS?" sourceLabel="TEXTBOOK p.360 · ENGINEERING LINK" syllabusLabel="15.2 · BENEFITS" title="A shorter expression can become a smaller, faster circuit." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "VISUAL", title: "Reduce algebraic effort" }, { eyebrow: "EXPRESSION", title: "Fewer literals / terms" }, { eyebrow: "CIRCUIT", title: "Fewer gates / inputs" }, { eyebrow: "SYSTEM", title: "Lower cost, delay and power" }]} /></Slide> },
    { time: "8 min", focus: "Solve a four-variable map in exam order.", prompt: "Fill, group, annotate constants, write simplified SOP.", source: "Modelled on the four-variable format in Cambridge 9618/32 O/N 2024 Q6(b)–(d).", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE · FORMAT MODELLED" sourceLabel="9618/32 O/N 2024 · Q6(b)–(d)" syllabusLabel="15.2 · 6 ADAPTED MARKS" title="Show the groups before writing the expression." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/32 O/N 2024 · Q6(b)–(d) FORMAT · MODELLED" marks={6} prompt={<p>Simplify <code>G(A,B,C,D)=Σm(0,2,5,7,8,10,13,15)</code> using a four-variable K-map. [6 adapted marks]</p>} answer={<ul><li>Use Gray-code rows/columns and place all eight 1s correctly. [2]</li><li>Group the four corners through wrap-around → <code>¬B·¬D</code>. [1]</li><li>Group the centre four → <code>B·D</code>. [1]</li><li>Simplified SOP: <code>G=¬B·¬D+B·D</code>. [2]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Close Chapter 15 with an interleaved retrieval map.", prompt: "One precise sentence for each branch, without notes.", source: "Chapter 15 synthesis aligned to syllabus p.34.", content: <Slide number="15" eyebrow="CHAPTER 15 EXIT" sourceLabel="TEXTBOOK Ch18–19 · SYLLABUS p.34" syllabusLabel="CHAPTER 15 COMPLETE" title="Process in parallel. Emulate in software. Simplify in logic." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>15.1</span><p>RISC/CISC · pipeline · interrupts.</p></article><article><span>15.1</span><p>Flynn · massive parallel · VM.</p></article><article><span>15.2</span><p>Boolean · adders · flip-flops.</p></article><article><span>15.2</span><p>Gray code · groups · K-map.</p></article></section><div className="homework-callout"><b>HOMEWORK 16</b><span>30 marks · K-maps + Chapter 15 checkpoint</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="16" title="Karnaugh maps and Chapter 15 review" syllabusLabel="SYLLABUS 15.1–15.2" sourceLabel="TEXTBOOK Ch18–19 · pp.340–362" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus Chapter 15 p.34 · endorsed coursebook Chapters 18–19 printed pp.340–362 · verified 2022–2024 Paper 3 question styles and mark schemes" sourceDetail="The lesson uses Gray-code ordering, legal power-of-two grouping, overlap and wrap-around, then links simplified SOP terms to smaller logic circuits and interleaves the whole Chapter 15 specification." />;
}
