"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l27-reveal-${id}`;
  return <div className="ss-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className={visible ? "ss-reveal__panel visible" : "ss-reveal__panel"} hidden={!visible}>{children}</div></div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Three translators", subtitle: "Describe the input, process and output of each translator", marks: 10,
    questions: [
      { id: "l27-1", marks: 3, lines: 3, prompt: <><b>Describe the purpose of an assembler.</b></>, answer: <p>An assembler translates a program written in assembly language into machine/object code. Mnemonic opcodes are replaced by binary opcodes and symbolic labels/addresses are resolved. There is generally a one-to-one relationship between assembly instructions and machine instructions. <em>[any 3]</em></p> },
      { id: "l27-2", marks: 4, lines: 4, prompt: <><b>Describe how a compiler translates a high-level-language program.</b></>, answer: <p>It analyses/translates the complete source program. Errors are collected/reported; if errors remain, no executable/object code is produced. If translation succeeds, object code is produced and can be linked with required library code to form an executable. <em>[4]</em></p> },
      { id: "l27-3", marks: 3, lines: 3, prompt: <><b>Describe how an interpreter processes a program containing an error.</b></>, answer: <p>It translates and executes one statement at a time. At the erroneous statement it stops and reports the error. The programmer can correct it immediately and continue/restart; no standalone executable is produced. <em>[any 3]</em></p> },
    ],
  },
  {
    code: "B", title: "Choose and combine", subtitle: "Use development, distribution and Java clues", marks: 10,
    questions: [
      { id: "l27-4", marks: 4, lines: 4, prompt: <><b>Justify using an interpreter while an unfinished program is being developed.</b></>, answer: <p>An interpreter can run a partially completed section; reports an error when its statement is reached; allows immediate/real-time correction; can continue from that point; avoids waiting for the whole source program to compile after every small change. <em>[any 4]</em></p> },
      { id: "l27-5", marks: 3, lines: 3, prompt: <><b>Give three reasons to compile a completed, tested program before distribution.</b></>, answer: <p>The executable runs faster; users do not need the source code; users do not need the compiler at runtime; the programmer&apos;s source is less exposed; repeated runs do not translate the source again. <em>[any 3]</em></p> },
      { id: "l27-6", marks: 3, lines: 3, prompt: <><b>Explain how Java uses both compilation and a virtual machine.</b></>, answer: <p>Java source is compiled into platform-independent Java bytecode. A Java Virtual Machine designed for the host platform loads and executes/translates that bytecode. Therefore the same bytecode can run on different systems that have a compatible JVM. <em>[3]</em></p> },
    ],
  },
  {
    code: "C", title: "Authentic Paper 1 practice", subtitle: "Recent compiler/interpreter forms and mark-scheme language", marks: 10,
    questions: [
      { id: "l27-7", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Complete the description.</b><p>A successful compiler produces ______ that runs without the ______. An interpreter reaches an erroneous line, then ______; the programmer can correct it ______. Adapted from 9618/13 M/J 2025 Q3(a). [4]</p></>, answer: <p><strong>an executable file/object code; source/program code; stops; immediately/in real time.</strong> <em>[1 each]</em></p> },
      { id: "l27-8", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain how a programmer can first use an interpreter and then a compiler during development.</b><p>Adapted from 9618/12 O/N 2025 Q10(a). [4]</p></>, answer: <p><strong>Interpreter:</strong> use while writing to test/debug incomplete code because errors are identified one at a time and can be corrected immediately. <strong>Compiler:</strong> use after completion to create an executable for repeated use/distribution, without exposing the source. <em>[max 2 per translator]</em></p> },
      { id: "l27-9", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>State two disadvantages of a compiler compared with an interpreter during program development.</b><p>Adapted from 9618/13 O/N 2025 Q8(a). [2]</p></>, answer: <p>Any two: a large program takes time to compile; it must be recompiled after changes; it cannot run while errors remain; errors cannot be corrected in real time; one error may trigger misleading further errors; partial code is harder to test. <em>[2]</em></p> },
    ],
  },
];

export default function Lesson27Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame translation as the route from human-readable source to processor-executable instructions.", prompt: "Ask which of today's three translators accepts assembly language rather than a high-level language.", source: "Syllabus 5.2; Coursebook Chapter 8 printed pp.127-129.", content: <Slide number="01" eyebrow="CHAPTER 5 · SYSTEM SOFTWARE" sourceLabel="TEXTBOOK CH.8 · pp.127-129" syllabusLabel="SYLLABUS 5.2" className="slide--ss-title"><section className="ss-title-grid"><div className="ss-title-copy"><span>LESSON 27 · 90 MINUTES</span><h1>Write once.<br /><em>Translate well.</em></h1><p>Assemblers, compilers and interpreters solve different translation problems—and Java deliberately combines stages.</p></div><div className="ss-title-visual"><div><b>A</b><span>ASSEMBLER</span></div><div><b>C</b><span>COMPILER</span></div><div><b>I</b><span>INTERPRETER</span></div><div><b>J</b><span>BYTECODE + JVM</span></div></div></section></Slide> },
    { time: "5 min", focus: "Separate source code, translator and executable output.", prompt: "Why can the processor not directly execute a Python or assembly mnemonic?", source: "Syllabus 5.2 translator purpose; Coursebook 8.05 printed p.127.", content: <Slide number="02" eyebrow="WHY TRANSLATE?" sourceLabel="TEXTBOOK p.127" syllabusLabel="SYLLABUS 5.2" title="The processor executes machine code—not source notation."><section className="ss-translation-pipeline"><article><b>SOURCE CODE</b><p>assembly or high-level language written for people</p></article><i>→</i><article><b>TRANSLATOR</b><p>checks and converts the representation</p></article><i>→</i><article><b>LOW-LEVEL RESULT</b><p>machine/object code or an immediately executed instruction</p></article></section><p className="ss-note">The correct translator depends first on the <strong>source language</strong>, then on how the program will be developed and used.</p></Slide> },
    { time: "6 min", focus: "Compare the three translators by source input and translation unit.", prompt: "Students complete the input column before the output/process column appears.", source: "Syllabus 5.2; Coursebook p.127 and Chapter 6 cross-reference.", content: <Slide number="03" eyebrow="THREE TRANSLATORS" sourceLabel="TEXTBOOK p.127 + CH.6" syllabusLabel="SYLLABUS 5.2" title="Input identifies the translator."><section className="ss-card-grid three"><article><span>ASSEMBLER</span><b>Assembly language</b><p>mnemonic instructions → machine/object code</p></article><article><span>COMPILER</span><b>Whole high-level program</b><p>source → object/executable code after checks</p></article><article><span>INTERPRETER</span><b>High-level statements</b><p>translate and execute one statement at a time</p></article></section><p className="ss-warning">An assembler does not translate a high-level language. A compiler and interpreter do.</p></Slide> },
    { time: "6 min", focus: "Reinforce the assembler's close relationship with machine code and its two-pass label resolution.", prompt: "Why can a forward label be used before its address is known?", source: "Syllabus 5.2 assembler role; Coursebook p.127 cross-reference to Chapter 6.", content: <Slide number="04" eyebrow="ASSEMBLER" sourceLabel="TEXTBOOK p.127 · CH.6" syllabusLabel="SYLLABUS 5.2" title="Replace mnemonics and resolve symbolic addresses."><section className="ss-split"><article><span className="ss-kicker">CLOSE TO THE PROCESSOR</span><h3>Assembly instruction</h3><p><code>LDM #12</code><br /><code>STO Total</code></p><p>Usually one assembly instruction maps to one machine instruction.</p></article><article><span className="ss-kicker">TWO PASSES</span><ul><li><strong>Pass 1:</strong> build the symbol table and record addresses.</li><li><strong>Pass 2:</strong> replace opcodes/labels and generate object or machine code.</li></ul></article></section></Slide> },
    { time: "6 min", focus: "Model whole-program compilation and the all-errors-before-object-code rule.", prompt: "At what point is an executable possible, and what blocks it?", source: "Coursebook pp.127-128 compiler sequence; syllabus 5.2.", content: <Slide number="05" eyebrow="COMPILER" sourceLabel="TEXTBOOK pp.127-128" syllabusLabel="SYLLABUS 5.2" title="Analyse the whole source program, then build a runnable result."><section className="ss-compiler-pass"><article><span>1</span><b>Read + analyse</b><p>process every source statement</p></article><article><span>2</span><b>Record errors</b><p>continue and create an error list</p></article><article><span>3</span><b>Generate object code</b><p>only when translation succeeds</p></article><article><span>4</span><b>Link + execute</b><p>combine required routines into a runnable program</p></article></section><p className="ss-note">If compilation finds errors, it reports them and <strong>does not produce the runnable result</strong>.</p></Slide> },
    { time: "5 min", focus: "Model line-at-a-time interpretation and immediate error feedback.", prompt: "What happens to later lines if line 3 contains a syntax error?", source: "Coursebook p.127 interpreter sequence; syllabus 5.2.", content: <Slide number="06" eyebrow="INTERPRETER" sourceLabel="TEXTBOOK p.127" syllabusLabel="SYLLABUS 5.2" title="Translate, execute, move on—until an error stops the run."><section className="ss-interpreter-tape"><div><b>READ 1</b><p>analyse</p></div><div><b>TRANSLATE 1</b><p>intermediate form</p></div><div><b>EXECUTE 1</b><p>perform action</p></div><div><b>READ 2</b><p>repeat</p></div><div><b>ERROR</b><p>stop + report</p></div><div><b>CORRECT</b><p>edit immediately</p></div></section><p className="ss-note">No separate executable is produced; the interpreter and source are needed whenever the program runs.</p></Slide> },
    { time: "6 min", focus: "Create an exam-ready comparison across development and runtime.", prompt: "Cover one cell and ask students to infer the opposite translator's characteristic.", source: "Coursebook p.128 advantages/disadvantages; syllabus 5.2.", content: <Slide number="07" eyebrow="COMPILER ↔ INTERPRETER" sourceLabel="TEXTBOOK p.128" syllabusLabel="SYLLABUS 5.2" title="Compare the same criterion—not unrelated facts."><section className="ss-compare-table"><div><strong>CRITERION</strong><strong>COMPILER</strong><strong>INTERPRETER</strong></div><div><b>Translation unit</b><span>whole program</span><span>one statement at a time</span></div><div><b>Error reporting</b><span>list after analysis</span><span>stop at first reached error</span></div><div><b>Development</b><span>recompile after changes</span><span>immediate correction; partial tests</span></div><div><b>Runtime</b><span>faster executable</span><span>retranslation makes execution slower</span></div><div><b>Distribution</b><span>executable; source can remain private</span><span>source + interpreter required</span></div></section></Slide> },
    { time: "6 min", focus: "Justify the interpreter during iterative development using causal chains.", prompt: "Turn each feature into a because-therefore explanation.", source: "Coursebook p.128 development trade-offs; 9618/12 O/N 2025 Q10(a).", content: <Slide number="08" eyebrow="DURING DEVELOPMENT" sourceLabel="TEXTBOOK p.128" syllabusLabel="SYLLABUS 5.2" title="Interpreter first: short edit-test-debug loops."><section className="ss-choice-scale"><article><h3>Interpreter helps</h3><ul><li>test unfinished sections</li><li>find an error when its line executes</li><li>correct immediately</li><li>continue from the fault</li></ul></article><i>↔</i><article><h3>Compiler costs</h3><ul><li>large sources take time to compile</li><li>every change needs recompilation</li><li>program cannot run while errors remain</li><li>one error may cause misleading later reports</li></ul></article></section></Slide> },
    { time: "6 min", focus: "Justify compilation once a program is stable and ready for repeated use.", prompt: "Which benefits belong to the developer and which to the end user?", source: "Coursebook pp.128-129 compiled-program advantages; syllabus 5.2.", content: <Slide number="09" eyebrow="FOR DISTRIBUTION" sourceLabel="TEXTBOOK pp.128-129" syllabusLabel="SYLLABUS 5.2" title="Compiler later: protect, distribute and run efficiently."><section className="ss-card-grid four"><article><span>FASTER</span><b>Native result</b><p>source is not retranslated on every run</p></article><article><span>PORTABLE PACKAGE?</span><b>Executable file</b><p>users need not receive the source</p></article><article><span>PRIVATE</span><b>Source hidden</b><p>implementation is harder for users to inspect</p></article><article><span>REPEATABLE</span><b>Run again</b><p>without the compiler taking part at runtime</p></article></section><p className="ss-warning">A native executable is normally built for a particular processor/operating environment; it is not automatically cross-platform.</p></Slide> },
    { time: "5 min", focus: "Introduce Java's two-stage model without claiming that bytecode is native machine code.", prompt: "Which stage is performed once by the developer and which occurs on the host system?", source: "Coursebook p.129 Java; syllabus 5.2 hybrid translation.", content: <Slide number="10" eyebrow="JAVA · A HYBRID ROUTE" sourceLabel="TEXTBOOK p.129" syllabusLabel="SYLLABUS 5.2" title="Compile to bytecode; execute through a JVM."><section className="ss-java-path"><span>JAVA<br />SOURCE</span><i>→</i><span>JAVA<br />COMPILER</span><i>→</i><span>JAVA<br />BYTECODE</span><i>→</i><span>JVM ON<br />HOST</span></section><p className="ss-note">Bytecode is an intermediate, platform-independent representation—not the host processor&apos;s final machine code.</p></Slide> },
    { time: "6 min", focus: "Explain portability as a property of matching JVM implementations, not magic in the bytecode alone.", prompt: "What must exist on each target platform before the same bytecode can run?", source: "Coursebook p.129 Java Virtual Machine; syllabus 5.2.", content: <Slide number="11" eyebrow="THE JVM CONTRACT" sourceLabel="TEXTBOOK p.129" syllabusLabel="SYLLABUS 5.2" title="Same bytecode. Platform-specific virtual machine."><section className="ss-jvm-grid"><div className="ss-jvm-core"><span>PORTABLE INPUT</span><strong>Java<br />bytecode</strong><span>EXECUTED BY A JVM</span></div><div className="ss-jvm-hosts"><p><b>JVM A</b><span>processor / OS A</span></p><p><b>JVM B</b><span>processor / OS B</span></p><p><b>JVM C</b><span>processor / OS C</span></p><p><b>RESULT</b><span>same bytecode can run</span></p></div></section><p className="ss-note">The JVM translates/executes bytecode for its host, commonly by interpretation and/or just-in-time compilation.</p></Slide> },
    { time: "9 min", focus: "Use the 2025 fill-the-gaps item to test precise vocabulary.", prompt: "Students answer all four blanks before any discussion; require exact functional terms.", source: "Adapted from 9618/13 M/J 2025 Q3(a), checked against the published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/13 M/J 2025 · Q3(a)" syllabusLabel="SYLLABUS 5.2 — EXAM PRACTICE" title="Complete the compiler/interpreter description." className="slide--ss-paper"><section className="ss-paper-grid"><article><span>COMPILER</span><p>A successful compilation produces ______ that runs without access to the ______.</p></article><article><span>INTERPRETER</span><p>At an erroneous line it ______; the programmer can correct the error ______.</p></article></section><Reveal id="paper-gaps" visible={revealed.has("paper-gaps")} onToggle={toggleReveal}><p><strong>an executable file/object code; source/program code; stops; immediately/in real time.</strong> One mark for each correct term.</p></Reveal><small>Adapted from 9618/13 M/J 2025 Q3(a).</small></Slide> },
    { time: "9 min", focus: "Practise a four-mark workflow answer with a balanced two marks per translator.", prompt: "Students label their response Interpreter and Compiler, then give action plus reason for each.", source: "Adapted from 9618/12 O/N 2025 Q10(a), checked against the published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/12 O/N 2025 · Q10(a)" syllabusLabel="SYLLABUS 5.2 — EXAM PRACTICE" title="First interpreter, then compiler: explain the workflow." className="slide--ss-paper"><section className="ss-paper-grid"><article><span>DEVELOPMENT · 2</span><p>What should the programmer use while writing and debugging—and why?</p></article><article><span>RELEASE · 2</span><p>What should the programmer use after completion—and why?</p></article></section><Reveal id="paper-workflow" visible={revealed.has("paper-workflow")} onToggle={toggleReveal}><p>Use the <strong>interpreter</strong> to test/debug partially completed code with immediate error correction. Use the <strong>compiler</strong> once complete to create an executable for repeated use/distribution without supplying source code.</p></Reveal><small>Adapted from 9618/12 O/N 2025 Q10(a).</small></Slide> },
    { time: "8 min", focus: "Consolidate translator choice through three distinct contexts.", prompt: "Pairs give the translator and one decisive clue for every scenario.", source: "Syllabus-style synthesis informed by 9618/13 O/N 2025 Q8(a).", content: <Slide number="14" eyebrow="TRANSLATOR DECISION SPRINT" sourceLabel="SYLLABUS + 2025 PAPER 1" syllabusLabel="SYLLABUS 5.2" title="Choose from the source and the purpose."><section className="ss-paper-grid three"><article><span>1 · EMBEDDED</span><p>Mnemonics must become processor instructions.</p></article><article><span>2 · PROTOTYPE</span><p>Incomplete high-level code changes every minute.</p></article><article><span>3 · RELEASE</span><p>A tested program should run quickly without sharing its source.</p></article></section><Reveal id="decision" visible={revealed.has("decision")} onToggle={toggleReveal}><p><strong>1 Assembler</strong>—assembly source. <strong>2 Interpreter</strong>—partial testing and immediate feedback. <strong>3 Compiler</strong>—fast distributable executable and no source needed by the user.</p></Reveal></Slide> },
    { time: "3 min", focus: "Close with the source-language test, development trade-off and Java route.", prompt: "Students say one sentence for each card without notes.", source: "Syllabus 5.2 completion check; Coursebook pp.127-129.", content: <Slide number="15" eyebrow="LESSON 27 · EXIT" sourceLabel="TEXTBOOK pp.127-129" syllabusLabel="SYLLABUS 5.2" title="Translate for the moment that matters." className="slide--ss-exit"><section className="ss-exit-grid"><article><b>IDENTIFY</b><p>Assembly → assembler; high-level source → compiler or interpreter.</p></article><article><b>JUSTIFY</b><p>Interpreter for iterative development; compiler for stable repeated use.</p></article><article><b>COMBINE</b><p>Java source → compiler → bytecode → platform-specific JVM.</p></article></section><div className="ss-homework-callout"><b>HOMEWORK 27</b><span>30 marks · three verified 2025 translator anchors · inline answers</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="27" slides={slides} homework={<HomeworkSheet lessonNumber="27" title="Assemblers, Compilers, Interpreters and Java" marks={30} minutes={45} syllabusLabel="SYLLABUS 5.2" sourceLabel="TEXTBOOK CH.8 · pp.127-129 + PAPER 1" instructions="Compare translators against the same criterion and develop every choice with a reason. Past-paper prompts are concise adaptations checked against the published 2025 mark schemes." sections={homeworkSections} challenge={{ id: "l27-challenge", prompt: <p><Mark>CHALLENGE</Mark> A team develops one Java application for three operating systems. Explain why bytecode improves portability but does not remove the need for platform-specific system software.</p>, answer: <p>The Java compiler produces the same platform-independent bytecode for distribution. Each operating system/processor combination still needs its own compatible JVM. That JVM is platform-specific software that translates or executes the bytecode using the host system&apos;s services and instructions.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 5.2, Coursebook Chapter 8 printed pp.127-129, and published 2025 Paper 1 questions and mark schemes." sourceDetail="Core: explain the assembler, compiler and interpreter; compare compiler/interpreter use; explain a hybrid model such as Java bytecode and the JVM. Authentic anchors: 9618/13 M/J 2025 Q3(a), 9618/12 O/N 2025 Q10(a), and 9618/13 O/N 2025 Q8(a). Compiler construction phases and JVM implementation internals are outside this AS lesson." />;
}
