"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { LayerStack, PacketRoute } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Name and purpose", subtitle: "Select the protocol that matches the transfer", marks: 10,
    questions: [
      { id: "a2-08-1", marks: 3, lines: 4, prompt: <><b>State the purpose of HTTP, FTP and BitTorrent.</b></>, answer: <p><strong>HTTP</strong> transfers web/hypertext resources <em>[1]</em>; <strong>FTP</strong> transfers files between networked devices/client and server <em>[1]</em>; <strong>BitTorrent</strong> supports peer-to-peer file sharing <em>[1]</em>.</p> },
      { id: "a2-08-2", marks: 3, lines: 4, prompt: <><b>State the purpose of SMTP, POP3 and IMAP.</b></>, answer: <p><strong>SMTP</strong> sends/pushes email <em>[1]</em>; <strong>POP3</strong> retrieves/downloads email <em>[1]</em>; <strong>IMAP</strong> retrieves and synchronises server-held email <em>[1]</em>.</p> },
      { id: "a2-08-3", marks: 4, lines: 5, prompt: <><b>Choose the correct protocol for each task:</b><p>request a web page; upload site files; send an email; synchronise mail on two devices.</p></>, answer: <p><strong>HTTP</strong> for the web page <em>[1]</em>; <strong>FTP</strong> for the upload <em>[1]</em>; <strong>SMTP</strong> to send email <em>[1]</em>; <strong>IMAP</strong> to synchronise mail <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Email journey", subtitle: "Use direction and storage to compare protocols", marks: 10,
    questions: [
      { id: "a2-08-4", marks: 3, lines: 5, prompt: <><b>Explain how SMTP is used</b> between composing and delivering an email to the receiving mail server.</>, answer: <p>The sender&apos;s email client pushes the message to its mail server using SMTP <em>[1]</em>. SMTP sends the message between mail servers <em>[1]</em> until it reaches the recipient&apos;s server <em>[1]</em>.</p> },
      { id: "a2-08-5", marks: 3, lines: 5, prompt: <><b>Describe POP3.</b></>, answer: <p>POP3 is used to retrieve email from a mail server <em>[1]</em>. It downloads/pulls messages to the client <em>[1]</em>, commonly for local/offline storage and access <em>[1]</em>.</p> },
      { id: "a2-08-6", marks: 4, lines: 6, prompt: <><b>Compare POP3 and IMAP</b> for a user with a phone and laptop.</>, answer: <p>Both retrieve email <em>[1]</em>. POP3 commonly downloads a local copy <em>[1]</em>. IMAP manages messages/folders on the server <em>[1]</em> and synchronises read state and changes across both devices <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Application-layer transfer", subtitle: "Apply protocol choices to exam scenarios", marks: 10,
    questions: [
      { id: "a2-08-7", marks: 3, lines: 5, prompt: <><b>Explain peer-to-peer file sharing.</b></>, answer: <p>Peers exchange file pieces directly <em>[1]</em>; each peer may upload and download/act as client and server <em>[1]</em>; there is no central server storing and serving the complete shared content <em>[1]</em>.</p> },
      { id: "a2-08-8", marks: 3, lines: 5, prompt: <><b>Distinguish FTP from BitTorrent.</b></>, answer: <p>FTP normally uses a client-server relationship and transfers a file to/from the server <em>[2]</em>. BitTorrent obtains/distributes pieces among multiple peers <em>[1]</em>.</p> },
      { id: "a2-08-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Name and describe two Application-layer protocols.</b></p><p>Adapted from 9618/32 O/N 2024 Q5(a). [4]</p></>, answer: <p>Award one mark for each valid protocol name and one for its matched purpose. Examples: HTTP — transfers web resources; FTP — transfers files; SMTP — sends email; POP3 — downloads email; IMAP — retrieves/synchronises server-held email; BitTorrent — peer-to-peer file sharing.</p> },
    ],
  },
];

export default function A2Lesson08Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Select protocols from familiar communication scenarios.", prompt: "Web page, uploaded folder, sent email and shared file: one protocol each.", source: "2027–2029 syllabus 14.1; coursebook Chapter 17 printed pp.335–337.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch17 §17.06–17.07" syllabusLabel="SYLLABUS 14.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 08 · 90 MINUTES</span><h1>Name the service.<br /><em>Choose the protocol.</em></h1><p>HTTP · FTP · SMTP · POP3 · IMAP · BitTorrent</p></div><div className="a2-at-hero" role="img" aria-label="Application protocols around a transfer"><strong>APPLICATION</strong><span>HTTP</span><span>EMAIL</span><span>FTP</span><span>P2P</span></div></section></Slide> },
    { time: "5 min", focus: "Set the exact six-protocol syllabus boundary.", prompt: "Students circle only the protocols explicitly named in syllabus 14.1.", source: "Syllabus p.33; coursebook pp.335–337.", content: <Slide number="02" eyebrow="SOURCE MAP" sourceLabel="SYLLABUS p.33 · TEXTBOOK pp.335–337" syllabusLabel="14.1 · SIX PROTOCOLS" title="Purpose, direction and relationship earn the marks." className="a2-slide a2-at-slide"><ConceptCards columns={3} items={[{ eyebrow: "WEB", title: "HTTP", body: "Request and transfer web resources." }, { eyebrow: "FILES", title: "FTP · BitTorrent", body: "Client-server or peer-to-peer transfer." }, { eyebrow: "EMAIL", title: "SMTP · POP3 · IMAP", body: "Send, download or synchronise." }]} /></Slide> },
    { time: "5 min", focus: "Reconnect every named protocol to the Application layer.", prompt: "What do lower layers do that HTTP does not need to do?", source: "Syllabus 14.1; coursebook §17.06.", content: <Slide number="03" eyebrow="RETRIEVAL" sourceLabel="TEXTBOOK p.335" syllabusLabel="14.1 · APPLICATION" title="Application protocols define the service; lower layers deliver the data." className="a2-slide a2-at-slide"><LayerStack layers={[{ name: "Application", detail: "HTTP · FTP · SMTP · POP3 · IMAP · BitTorrent", tag: "TODAY'S FOCUS" }, { name: "Transport", detail: "end-to-end delivery" }, { name: "Internet", detail: "IP and routing" }, { name: "Link", detail: "local frames and medium" }]} /></Slide> },
    { time: "6 min", focus: "Give students a repeatable protocol-selection method.", prompt: "Apply the three questions to a browser request.", source: "Syllabus 14.1; published Paper 3 protocol questions.", content: <Slide number="04" eyebrow="SELECTION FRAMEWORK" sourceLabel="9618 PAPER 3" syllabusLabel="14.1 · SELECT" title="Ask what moves, in which direction, and between which roles." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "WHAT?", title: "web · file · email" }, { eyebrow: "DIRECTION?", title: "send · retrieve · sync" }, { eyebrow: "RELATIONSHIP?", title: "client-server · peer-to-peer" }, { eyebrow: "NAME", title: "select + state purpose" }]} /></Slide> },
    { time: "6 min", focus: "Describe HTTP as web-resource transfer.", prompt: "Write one request and one response action without drifting into HTML.", source: "Coursebook §17.06 p.335; 9618/31 O/N 2023 Q2.", content: <Slide number="05" eyebrow="HTTP" sourceLabel="TEXTBOOK p.335 · O/N 2023 Q2" syllabusLabel="14.1 · PURPOSE" title="A browser requests; a web server responds with a web resource." className="a2-slide a2-at-slide"><PacketRoute nodes={[{ label: "Browser", detail: "HTTP request", state: "host" }, { label: "Internet", detail: "lower layers deliver" }, { label: "Web server", detail: "HTTP response", state: "host" }]} packets={["GET", "200"]} /></Slide> },
    { time: "6 min", focus: "Describe FTP with an explicit client-server transfer.", prompt: "Which word in the answer proves that FTP can upload as well as download?", source: "Coursebook §17.06 p.336; syllabus 14.1.", content: <Slide number="06" eyebrow="FTP" sourceLabel="TEXTBOOK p.336" syllabusLabel="14.1 · PURPOSE" title="FTP transfers files between networked devices, commonly client and server." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "UPLOAD", title: "Client → server", body: "Publish or back up a file." }, { eyebrow: "DOWNLOAD", title: "Server → client", body: "Retrieve a remote file." }, { eyebrow: "MODEL", title: "Client-server", body: "The server provides the file-transfer service." }]} /></Slide> },
    { time: "6 min", focus: "Explain SMTP as the email sending protocol.", prompt: "Trace SMTP twice in a normal email journey.", source: "Coursebook §17.06 pp.335–336; 9618/32 M/J 2024 Q2(b).", content: <Slide number="07" eyebrow="SMTP" sourceLabel="TEXTBOOK pp.335–336 · M/J 2024 Q2" syllabusLabel="14.1 · PURPOSE" title="SMTP pushes email from client to server and between mail servers." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "COMPOSE", title: "Sender client" }, { eyebrow: "SMTP", title: "send to mail server" }, { eyebrow: "SMTP", title: "server-to-server transfer" }, { eyebrow: "ARRIVE", title: "Recipient mail server" }]} /></Slide> },
    { time: "6 min", focus: "Describe POP3 as retrieval/download.", prompt: "Why is POP3 often associated with one main client device?", source: "Coursebook §17.06 p.336; published Paper 3 mark schemes.", content: <Slide number="08" eyebrow="POP3" sourceLabel="TEXTBOOK p.336" syllabusLabel="14.1 · PURPOSE" title="POP3 pulls messages from the server to the email client." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SERVER", title: "Mailbox holds message" }, { eyebrow: "POP3", title: "client requests / downloads" }, { eyebrow: "LOCAL", title: "message stored on device" }, { eyebrow: "USE", title: "offline access possible" }]} /></Slide> },
    { time: "6 min", focus: "Describe IMAP as server-managed synchronisation.", prompt: "A message is marked read on a phone: what should the laptop see?", source: "Coursebook §17.06 p.336; 9618/32 O/N 2022 Q3(c).", content: <Slide number="09" eyebrow="IMAP" sourceLabel="TEXTBOOK p.336 · O/N 2022 Q3" syllabusLabel="14.1 · PURPOSE" title="IMAP keeps the mailbox state synchronised across clients." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "SERVER", title: "Authoritative mailbox", body: "Messages and folders remain managed centrally." }, { eyebrow: "CLIENTS", title: "Multiple devices", body: "Phone, laptop and webmail access the same state." }, { eyebrow: "SYNC", title: "Changes propagate", body: "Read, move and delete status stays consistent." }]} /></Slide> },
    { time: "6 min", focus: "Compare POP3 and IMAP with linked differences.", prompt: "Write two paired contrasts rather than two isolated definitions.", source: "Coursebook p.336; syllabus protocol purposes.", content: <Slide number="10" eyebrow="POP3 OR IMAP?" sourceLabel="TEXTBOOK p.336" syllabusLabel="14.1 · COMPARE" title="Both retrieve email; their storage and synchronisation models differ." className="a2-slide a2-at-slide"><CompareTable headers={["Feature", "POP3", "IMAP"]} rows={[["main action", "download / pull", "access + synchronise"], ["mail state", "commonly local client copy", "managed on server"], ["multiple devices", "less naturally consistent", "changes stay synchronised"], ["best fit", "single-device / offline copy", "multi-device mailbox"]]} /></Slide> },
    { time: "7 min", focus: "Trace the complete email journey with correct protocols.", prompt: "Identify which arrows are SMTP and where the final choice branches.", source: "Coursebook Figure 17.04 pp.335–336; 9618/32 M/J 2024 Q2.", content: <Slide number="11" eyebrow="END-TO-END EMAIL" sourceLabel="TEXTBOOK Figure 17.04" syllabusLabel="14.1 · APPLY" title="Send with SMTP; retrieve with POP3 or IMAP." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SENDER", title: "Mail client", code: "SMTP" }, { eyebrow: "OUTBOUND", title: "Sender mail server", code: "SMTP" }, { eyebrow: "INBOUND", title: "Receiver mail server", code: "POP3 / IMAP" }, { eyebrow: "RECIPIENT", title: "Mail client" }]} /></Slide> },
    { time: "7 min", focus: "Explain peer-to-peer file sharing accurately.", prompt: "What is absent, and what role can every peer perform?", source: "Coursebook §17.07 pp.336–337; syllabus 14.1.", content: <Slide number="12" eyebrow="BITTORRENT" sourceLabel="TEXTBOOK pp.336–337" syllabusLabel="14.1 · PEER-TO-PEER" title="Peers exchange pieces directly and can upload while downloading." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "PEER", title: "Equal network role", body: "Each participant can request and supply pieces." }, { eyebrow: "DISTRIBUTED", title: "Many sources", body: "Pieces may arrive from several peers." }, { eyebrow: "NO CONTENT HUB", title: "No central content server", body: "A tracker may help discovery but does not host the shared file." }]} /></Slide> },
    { time: "7 min", focus: "Compare centralised and peer-to-peer file transfer.", prompt: "Which model gains sources as more complete peers join?", source: "Coursebook §§17.06–17.07 pp.336–337.", content: <Slide number="13" eyebrow="FTP VS BITTORRENT" sourceLabel="TEXTBOOK pp.336–337" syllabusLabel="14.1 · COMPARE" title="One server supplies the service; many peers share the workload." className="a2-slide a2-at-slide"><CompareTable headers={["Feature", "FTP", "BitTorrent"]} rows={[["relationship", "client-server", "peer-to-peer"], ["source", "chosen file server", "multiple peers"], ["participant role", "client uploads/downloads to server", "peer can upload and download"], ["content server", "central service", "no central content server"]]} /></Slide> },
    { time: "8 min", focus: "Practise naming and describing protocols concisely.", prompt: "Two protocol names and two matched descriptions in four minutes.", source: "Adapted from Cambridge 9618/32 O/N 2024 Q5(a).", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/32 O/N 2024 · Q5" syllabusLabel="14.1 · 4 MARKS" title="Name and describe two Application-layer protocols." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/32 O/N 2024 · Q5(a) · ADAPTED" marks={4} prompt={<p>Name two protocols from HTTP, FTP, SMTP, POP3, IMAP and BitTorrent, then give the precise purpose of each. [4]</p>} answer={<ul><li>One mark for each correct protocol name.</li><li>One mark for each correctly matched purpose: web-resource transfer; file transfer; email sending; email download; server-mail synchronisation; peer-to-peer file sharing.</li></ul>} /></Slide> },
    { time: "5 min", focus: "Check name, purpose, direction and relationship.", prompt: "Six scenarios; students answer with protocol plus one purpose phrase.", source: "Lesson synthesis aligned to syllabus 14.1.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK §§17.06–17.07" syllabusLabel="SYLLABUS 14.1" title="Can you choose all six without guessing?" className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>01</span><p>Web resource and file upload?</p></article><article><span>02</span><p>Send, download and synchronise email?</p></article><article><span>03</span><p>Explain one POP3/IMAP difference.</p></article><article><span>04</span><p>Define BitTorrent&apos;s peer relationship.</p></article></section><div className="homework-callout"><b>HOMEWORK 08</b><span>30 marks · protocol selection + email journey · inline answers</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="08" title="Application-layer protocols" syllabusLabel="SYLLABUS 14.1" sourceLabel="TEXTBOOK Ch17 · pp.335–337" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus §14.1 p.33 · endorsed coursebook Chapter 17 printed pp.335–337 · verified 2022–2024 Paper 3 questions and mark schemes" sourceDetail="All six named syllabus protocols are taught through purpose, transfer direction and client-server or peer-to-peer relationship. Tracker terminology is clearly marked as supporting textbook detail." />;
}
