"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { ProcessStateDiagram } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "The OS as resource manager", subtitle: "Name the resource and the service", marks: 10,
    questions: [
      { id: "a2-17-1", marks: 3, lines: 5, prompt: <><b>State three hardware resources</b> managed by an operating system.</>, answer: <p>Any three: processor/CPU time <em>[1]</em>; main memory/RAM <em>[1]</em>; secondary storage or input/output devices <em>[1]</em>.</p> },
      { id: "a2-17-2", marks: 3, lines: 6, prompt: <><b>Explain how an operating system can maximise CPU use</b> when one process requests input.</>, answer: <p>The requesting process becomes blocked while it waits for the input <em>[1]</em>. The scheduler selects a ready process <em>[1]</em>, so the CPU can execute useful instructions instead of remaining idle <em>[1]</em>.</p> },
      { id: "a2-17-3", marks: 4, lines: 7, prompt: <><b>Explain two ways a user interface hides hardware complexity.</b></>, answer: <p>A file name and folder path hide the physical disk blocks and device commands <em>[1+1]</em>. Icons, menus or commands let the user request an action without manipulating registers, buses or device signals directly <em>[1+1]</em>. Accept a developed driver/system-call example.</p> },
    ],
  },
  {
    code: "B", title: "Processes and states", subtitle: "Use running, ready and blocked precisely", marks: 10,
    questions: [
      { id: "a2-17-4", marks: 3, lines: 5, prompt: <><b>Distinguish a program from a process.</b></>, answer: <p>A program is stored executable instructions/code <em>[1]</em>. A process is a program currently in execution <em>[1]</em>, with a current state and allocated resources/context <em>[1]</em>.</p> },
      { id: "a2-17-5", marks: 3, lines: 5, prompt: <><b>Define the three required process states:</b> running, ready and blocked.</>, answer: <p>Running: currently executing on the CPU <em>[1]</em>. Ready: able to execute but waiting for CPU time <em>[1]</em>. Blocked: waiting for an event or resource, such as I/O completion <em>[1]</em>.</p> },
      { id: "a2-17-6", marks: 4, lines: 7, prompt: <><b>Give the transition caused by each event:</b> dispatch; time slice expires; I/O requested; I/O completes.</>, answer: <p>Dispatch: ready → running <em>[1]</em>; time slice expires: running → ready <em>[1]</em>; I/O requested: running → blocked <em>[1]</em>; I/O completes: blocked → ready <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Multi-tasking and exam language", subtitle: "Turn an event into a valid transition", marks: 10,
    questions: [
      { id: "a2-17-7", marks: 3, lines: 6, prompt: <><b>Explain how multi-tasking creates the appearance</b> that several programs run at once on one CPU core.</>, answer: <p>The OS divides processor time into short intervals <em>[1]</em>; scheduling/context switches share the CPU among ready processes <em>[1]</em>; switching happens quickly enough that users perceive concurrent progress <em>[1]</em>.</p> },
      { id: "a2-17-8", marks: 3, lines: 5, prompt: <><b>Explain why a blocked process cannot move directly to running.</b></>, answer: <p>When its event completes it becomes eligible to execute and enters the ready state/queue <em>[1]</em>. Other ready processes may exist <em>[1]</em>, so it must wait until the scheduler selects and dispatches it <em>[1]</em>.</p> },
      { id: "a2-17-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>A process is running when its time slice ends. Name its next state and explain two other state transitions.</b></p><p>Adapted from 9618/31 O/N 2023 Q7. [4 adapted marks]</p></>, answer: <p>It moves to <strong>ready</strong> <em>[1]</em> because it can run but no longer has the CPU <em>[1]</em>. Running → blocked occurs when it must wait for I/O/an event <em>[1]</em>; blocked → ready occurs when that event completes <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson17Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame the operating system as an active resource manager.", prompt: "If the OS disappeared, which shared resource would fail first?", source: "2027–2029 syllabus 16.1; coursebook Chapter 20 printed pp.368–371 and p.375.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch20" syllabusLabel="SYLLABUS 16.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 17 · 90 MINUTES</span><h1>One machine.<br /><em>Many demands.</em></h1><p>OS resources · interface abstraction · processes · state transitions</p></div><div className="a2-at-hero" role="img" aria-label="Operating system coordinates shared resources"><strong>OPERATING SYSTEM</strong><span>CPU TIME</span><span>MEMORY</span><span>DEVICES</span><span>PROCESSES</span></div></section></Slide> },
    { time: "5 min", focus: "Map every lesson objective to syllabus 16.1.", prompt: "Students underline the verbs maximise, describe and show understanding.", source: "Official 2027–2029 syllabus p.35.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.35" syllabusLabel="16.1 · REQUIRED" title="The OS hides complexity while allocating finite resources." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "MAXIMISE", title: "Resource use", body: "CPU, memory, storage and I/O." }, { eyebrow: "HIDE", title: "Hardware detail", body: "A usable interface replaces low-level control." }, { eyebrow: "MANAGE", title: "Processes", body: "Multi-tasking and controlled execution." }, { eyebrow: "TRACE", title: "Three states", body: "Running, ready and blocked." }]} /></Slide> },
    { time: "5 min", focus: "Identify the resources an OS shares and protects.", prompt: "For each resource, name one conflict the OS must prevent.", source: "Coursebook §20.01 pp.368–369.", content: <Slide number="03" eyebrow="RESOURCE MANAGER" sourceLabel="TEXTBOOK pp.368–369" syllabusLabel="16.1 · MAXIMISE USE" title="Every resource is finite, shared and scheduled." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "PROCESSOR", title: "CPU time", body: "Choose which ready process executes." }, { eyebrow: "MEMORY", title: "RAM", body: "Allocate space and keep processes isolated." }, { eyebrow: "STORAGE", title: "Files", body: "Organise, locate, protect and buffer data." }, { eyebrow: "I/O", title: "Devices", body: "Coordinate access through drivers and queues." }]} /></Slide> },
    { time: "6 min", focus: "Explain how useful CPU work continues during I/O waits.", prompt: "Trace what happens after Process A requests a disk read.", source: "Coursebook §20.01–20.03 pp.368–371.", content: <Slide number="04" eyebrow="MAXIMISE CPU USE" sourceLabel="TEXTBOOK pp.368–371" syllabusLabel="16.1 · RESOURCES" title="A blocked process releases the CPU to a ready process." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "PROCESS A", title: "Requests disk I/O", body: "Cannot continue until data arrives." }, { eyebrow: "OS", title: "Marks A blocked", body: "A leaves the processor." }, { eyebrow: "SCHEDULER", title: "Selects ready B", body: "The CPU resumes useful work." }, { eyebrow: "INTERRUPT", title: "I/O completes", body: "A returns to ready." }]} /></Slide> },
    { time: "6 min", focus: "Connect user-facing actions to hidden low-level work.", prompt: "What hardware detail is hidden by Save, Print and Play?", source: "Coursebook §20.05 p.375; syllabus wording on UI abstraction.", content: <Slide number="05" eyebrow="THE UI AS ABSTRACTION" sourceLabel="TEXTBOOK p.375" syllabusLabel="16.1 · HIDE COMPLEXITY" title="Users request outcomes—not register transfers or device signals." className="a2-slide a2-at-slide"><CompareTable headers={["User action", "What the interface hides"]} rows={[["Save report.docx", "disk blocks, addresses, buffering and write commands"], ["Print 20 copies", "device protocol, spooling, interrupts and status codes"], ["Open camera", "driver commands, memory buffers and sensor timing"], ["Move a window", "graphics memory, coordinates and display refresh"]]} /></Slide> },
    { time: "6 min", focus: "Separate interface, system call and driver roles.", prompt: "Which layer is device-specific?", source: "Coursebook §20.01–20.02 pp.368–370.", content: <Slide number="06" eyebrow="CONTROLLED PATH TO HARDWARE" sourceLabel="TEXTBOOK pp.368–370" syllabusLabel="16.1 · OS SERVICES" title="Applications reach devices through controlled OS services." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "USER", title: "Chooses Print" }, { eyebrow: "APPLICATION", title: "Requests an OS service", code: "system call" }, { eyebrow: "KERNEL", title: "Checks and coordinates" }, { eyebrow: "DRIVER", title: "Issues device commands", code: "printer-specific" }]} /></Slide> },
    { time: "6 min", focus: "Distinguish stored code from an executing instance.", prompt: "Can two processes come from the same program?", source: "Coursebook §20.03 p.370.", content: <Slide number="07" eyebrow="PROGRAM ≠ PROCESS" sourceLabel="TEXTBOOK p.370" syllabusLabel="16.1 · PROCESS" title="A process is a program in execution with a current context." className="a2-slide a2-at-slide"><CompareTable headers={["Program", "Process"]} rows={[["stored instructions", "instructions currently being executed"], ["passive file on storage", "active entity managed by the OS"], ["one code base", "its own state, data and resources"], ["example: browser executable", "example: each running browser instance/tab workload"]]} /></Slide> },
    { time: "6 min", focus: "Explain multi-tasking without claiming simultaneous execution on one core.", prompt: "What changes at each context switch?", source: "Coursebook §20.03 pp.370–371.", content: <Slide number="08" eyebrow="MULTI-TASKING" sourceLabel="TEXTBOOK pp.370–371" syllabusLabel="16.1 · PROCESS MANAGEMENT" title="Rapid CPU sharing makes several processes appear concurrent." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "SHARE", title: "CPU time", body: "Only a running process uses one core at an instant." }, { eyebrow: "SAVE", title: "Context", body: "Register values and execution position are preserved." }, { eyebrow: "SWITCH", title: "Ready process", body: "The scheduler and dispatcher resume another process." }]} /></Slide> },
    { time: "6 min", focus: "Define all three current-syllabus process states.", prompt: "Ready and blocked both wait—what is the exact difference?", source: "Syllabus p.35; coursebook pp.370–371 uses waiting for blocked.", content: <Slide number="09" eyebrow="THREE REQUIRED STATES" sourceLabel="SYLLABUS p.35" syllabusLabel="16.1 · RUNNING / READY / BLOCKED" title="The reason for waiting determines the state." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "RUNNING", title: "Has the CPU", body: "Instructions are currently executing." }, { eyebrow: "READY", title: "Waits for CPU", body: "Able to run as soon as selected." }, { eyebrow: "BLOCKED", title: "Waits for event", body: "Cannot continue until I/O/resource/event completes." }]} /></Slide> },
    { time: "6 min", focus: "Trace only valid transitions among required states.", prompt: "Point to the one transition that never occurs directly.", source: "Coursebook §20.03 pp.370–372; current syllabus uses blocked rather than waiting.", content: <Slide number="10" eyebrow="PROCESS STATE MODEL" sourceLabel="TEXTBOOK pp.370–372" syllabusLabel="16.1 · STATE TRANSITIONS" title="Events—not elapsed time alone—move a process between states." className="a2-slide a2-at-slide"><ProcessStateDiagram /></Slide> },
    { time: "7 min", focus: "Explain ready-to-running and running-to-ready transitions.", prompt: "Which transition is dispatch, and which is pre-emption?", source: "Coursebook pp.370–372.", content: <Slide number="11" eyebrow="CPU-SIDE TRANSITIONS" sourceLabel="TEXTBOOK pp.370–372" syllabusLabel="16.1 · PROCESS STATES" title="Dispatch grants the CPU; pre-emption removes it without blocking." className="a2-slide a2-at-slide"><CompareTable headers={["Transition", "Trigger", "Meaning"]} rows={[["ready → running", "scheduler selects; dispatcher restores context", "process receives CPU"], ["running → ready", "time slice expires", "still able to run"], ["running → ready", "higher-priority work / interrupt", "pre-empted, not waiting for I/O"]]} /></Slide> },
    { time: "7 min", focus: "Explain event-side transitions and the mandatory ready queue.", prompt: "Why is I/O completion not blocked-to-running?", source: "Syllabus p.35; coursebook pp.370–371.", content: <Slide number="12" eyebrow="EVENT-SIDE TRANSITIONS" sourceLabel="SYLLABUS p.35" syllabusLabel="16.1 · PROCESS STATES" title="Completing an event makes a process eligible—not selected." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "RUNNING", title: "Requests input" }, { eyebrow: "BLOCKED", title: "Waits; cannot execute" }, { eyebrow: "EVENT", title: "Input arrives" }, { eyebrow: "READY", title: "Queues for CPU" }]} /></Slide> },
    { time: "7 min", focus: "Correct high-frequency vocabulary traps.", prompt: "Students repair each unsafe sentence aloud.", source: "Syllabus 16.1 and coursebook terminology reconciliation.", content: <Slide number="13" eyebrow="EXAM LANGUAGE CLINIC" sourceLabel="SYLLABUS 16.1" syllabusLabel="16.1 · PRECISION" title="Waiting for CPU is ready; waiting for an event is blocked." className="a2-slide a2-at-slide"><CompareTable headers={["Unsafe statement", "Exam-safe correction"]} rows={[["Ready means executing.", "Running means executing; ready means eligible but waiting for CPU."], ["Blocked means crashed.", "Blocked means waiting for a required event/resource."], ["A program is a process.", "A process is an executing instance of a program."], ["The UI makes it easy.", "Name the hidden hardware or OS complexity."]]} /></Slide> },
    { time: "8 min", focus: "Apply current process-state vocabulary to an authentic exam pattern.", prompt: "Name the state first, then justify it with the event.", source: "Adapted from Cambridge 9618/31 O/N 2023 Q7.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/31 O/N 2023 · Q7" syllabusLabel="16.1 · 5 MARKS" title="A state answer needs both a name and a cause." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/31 O/N 2023 · Q7 · ADAPTED" marks={5} prompt={<p>A running process reaches the end of its time slice. State its next state. Then explain the transitions caused by an I/O request and by I/O completion. [5]</p>} answer={<ul><li>Time slice ends: running → ready; it remains able to run but waits for CPU. [2]</li><li>I/O request: running → blocked because it cannot continue yet. [2]</li><li>I/O completion: blocked → ready. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve the OS-process model in four statements.", prompt: "Students give one hidden complexity and one valid transition.", source: "Syllabus 16.1 synthesis; coursebook Chapter 20 pp.368–375.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch20 · SYLLABUS p.35" syllabusLabel="16.1 · CHECKPOINT" title="The OS allocates, abstracts, schedules and protects." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>RESOURCE</span><p>Share finite hardware efficiently.</p></article><article><span>ABSTRACTION</span><p>Hide low-level hardware detail.</p></article><article><span>PROCESS</span><p>A program currently executing.</p></article><article><span>R / R / B</span><p>Running, ready and blocked.</p></article></section><div className="homework-callout"><b>HOMEWORK 17</b><span>30 marks · OS resources, UI and process states</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="17" title="OS resources, processes and states" syllabusLabel="SYLLABUS 16.1" sourceLabel="TEXTBOOK Ch20 · pp.368–375" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 16.1 p.35 · endorsed coursebook Chapter 20 printed pp.368–375 · verified 2023 Paper 3 question and mark scheme" sourceDetail="The lesson treats the OS as a resource manager, makes UI abstraction concrete, and uses only the current-syllabus running, ready and blocked state model. The coursebook term waiting is explicitly mapped to blocked." />;
}
