"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Name the gate correctly", subtitle: "Validation, verification and rule types", marks: 10,
    questions: [
      { id: "l31-1", marks: 4, lines: 4, prompt: <><b>Distinguish validation from verification and explain how each supports data integrity.</b></>, answer: <p><strong>Validation</strong> checks whether input follows rules/is reasonable and rejects or flags values that fail. <strong>Verification</strong> checks that entered data matches the source/original. Both reduce errors reaching stored/processed data, but neither guarantees that a plausible matching source value is true. <em>[2 + 2]</em></p> },
      { id: "l31-2", marks: 4, lines: 3, prompt: <><b>Name the most specific validation check for each rule:</b><p>(i) must not be blank; (ii) exactly eight characters; (iii) begins with two letters then four digits; (iv) appears in the registered Course table.</p></>, answer: <p>(i) <strong>presence</strong>; (ii) <strong>length</strong>; (iii) <strong>format</strong>; (iv) <strong>existence</strong>. <em>[1 each]</em></p> },
      { id: "l31-3", marks: 2, lines: 2, prompt: <><b>Distinguish a range check from a limit check.</b></>, answer: <p>A range check uses both a lower and upper boundary; a limit check compares with one boundary/maximum/minimum. Boundaries may be inclusive as specified. <em>[1 each]</em></p> },
    ],
  },
  {
    code: "B", title: "Design and use the checks", subtitle: "Inputs, double entry and a supplied check-digit algorithm", marks: 10,
    questions: [
      { id: "l31-4", marks: 4, lines: 4, prompt: <><b>A concert form collects Age (12–18), EmailAddress and TicketCode (two letters followed by four digits).</b><p>Choose two fields and describe one suitable validation check for each.</p></>, answer: <p>Examples: <strong>Age—range check</strong>, accept only 12 ≤ Age ≤ 18; <strong>EmailAddress—presence check</strong>, reject blank input; <strong>TicketCode—format check</strong>, require LLDDDD. Award named suitable check plus explicit rule for each field. <em>[2 + 2]</em></p> },
      { id: "l31-5", marks: 3, lines: 3, prompt: <><b>Compare visual checking with double entry verification.</b></>, answer: <p>Visual checking displays/reads back the entered value so a person compares it with the source; it can miss an error. Double entry requires the value to be entered twice, usually independently, and the computer compares both versions; matching repeated mistakes can still pass. <em>[3]</em></p> },
      { id: "l31-6", marks: 3, lines: 3, prompt: <><b>Use this check-digit rule for 4725:</b><p>Multiply alternate digits by 1,3,1,3. Add the products. Choose a final digit that makes the total a multiple of 10.</p></>, answer: <p>4×1 + 7×3 + 2×1 + 5×3 = 4 + 21 + 2 + 15 = <strong>42</strong>. The next multiple of 10 is 50, so the check digit is <strong>8</strong> and the full code is <strong>47258</strong>. <em>[working, digit, code]</em></p> },
    ],
  },
  {
    code: "C", title: "Paper 1 selection", subtitle: "Recognise checks from their algorithmic evidence", marks: 10,
    questions: [
      { id: "l31-7", marks: 3, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Name the validation method represented by each algorithm:</b><p>(i) checks Lower ≤ Value ≤ Upper; (ii) searches a stored list for Code; (iii) tests two letters followed by four digits.</p><p>Adapted from 9618/13 O/N 2025 Q7(e). [3]</p></>, answer: <p>(i) <strong>range check</strong>; (ii) <strong>existence check</strong>; (iii) <strong>format check</strong>. <em>[1 each]</em></p> },
      { id: "l31-8", marks: 4, lines: 4, prompt: <><b>A product code must contain exactly nine characters and exist in ProductTable.</b><p>Explain why both checks are useful rather than either one alone.</p></>, answer: <p>A <strong>length check</strong> rejects values that are not nine characters, but a nine-character invented code could pass. An <strong>existence check</strong> confirms a match in ProductTable; together they reject malformed and unknown values and better protect integrity. <em>[2 checks + 2 limitations/combo]</em></p> },
      { id: "l31-9", marks: 3, lines: 3, prompt: <><b>A user twice enters the wrong but plausible date, 12/06/2027, instead of 21/06/2027. Explain why validation and double-entry verification can both pass.</b></>, answer: <p>The wrong date has a valid format and plausible day/month/year, so validation passes. The same wrong value was entered twice, so the two entries match and verification passes. These checks reduce errors but cannot prove real-world accuracy/truth. <em>[3]</em></p> },
    ],
  },
];

export default function Lesson31Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame data entry as a sequence of gates that reduce—not eliminate—errors.", prompt: "Ask whether a plausible lie can pass validation.", source: "Syllabus 6.2; Coursebook 9.05 printed pp.140–142.", content: <Slide number="01" eyebrow="CHAPTER 6 · DATA INTEGRITY" sourceLabel="TEXTBOOK §9.05 · pp.140–142" syllabusLabel="SYLLABUS 6.2" className="se-title"><section className="se-title-grid"><div className="se-title-copy"><span>LESSON 31 · 90 MINUTES</span><h1>Check the <em>entry.</em></h1><p>Use seven validation rules, two verification methods and a supplied check-digit algorithm—while remembering that “passes” never means “true”.</p></div><div className="se-title-visual"><div><b>1</b><span>RULES: IS IT ACCEPTABLE?</span></div><div><b>2</b><span>COMPARE: DOES IT MATCH?</span></div><div><b>3</b><span>CHECK DIGIT: IS THE CODE CONSISTENT?</span></div><div><b>4</b><span>STORE ONLY AFTER THE GATES</span></div></div></section></Slide> },
    { time: "5 min", focus: "Locate where errors enter and how a gate protects later processing.", prompt: "Which error could occur before the user ever touches the keyboard?", source: "Coursebook 9.05 printed pp.140–142; syllabus 6.2 integrity protection.", content: <Slide number="02" eyebrow="THE DATA-ENTRY JOURNEY" sourceLabel="TEXTBOOK §9.05 · pp.140–142" syllabusLabel="SYLLABUS 6.2" title="Bad data can be plausible, copied wrongly or malformed."><section className="se-flow"><span>REAL-WORLD<br />SOURCE</span><i>→</i><span>HUMAN<br />ENTRY</span><i>→</i><span>VALIDATE +<br />VERIFY</span><i>→</i><span>STORE /<br />PROCESS</span></section><p className="se-note">Checks protect integrity by catching errors <strong>before</strong> they contaminate later calculation, decisions and records.</p></Slide> },
    { time: "6 min", focus: "Establish the core distinction with different questions and evidence.", prompt: "Classify: '18 is permitted' and '18 matches the paper form'.", source: "Syllabus 6.2 validation versus verification; Coursebook 9.05.", content: <Slide number="03" eyebrow="VALIDATION ≠ VERIFICATION" sourceLabel="TEXTBOOK §9.05 · pp.140–142" syllabusLabel="SYLLABUS 6.2" title="Reasonable by rule—or copied as intended?"><section className="se-compare"><div><b>METHOD</b><b>QUESTION</b><b>EVIDENCE</b></div><div><b>Validation</b><span>Does the value satisfy stated rules?</span><span>range, pattern, size, presence, lookup, check digit</span></div><div><b>Verification</b><span>Does the entered/transferred value match the source?</span><span>visual/double entry now; parity/checksum next lesson</span></div></section><p className="se-warning">A valid value can still be wrong. Age 16 passes a 12–18 range even if the source says 15.</p></Slide> },
    { time: "6 min", focus: "Separate two-boundary range checks from one-boundary limit checks.", prompt: "Which check fits file size ≤ 20 MB? Which fits month 1–12?", source: "Syllabus 6.2 range and limit checks; Coursebook 9.05.", content: <Slide number="04" eyebrow="BOUNDARY CHECKS" sourceLabel="TEXTBOOK §9.05 · p.140" syllabusLabel="SYLLABUS 6.2" title="Two ends for a range; one boundary for a limit."><section className="se-grid two"><article className="se-card"><span>RANGE CHECK</span><h3>Lower ≤ value ≤ upper</h3><p>Example: month must be from <strong>1 to 12 inclusive</strong>.</p></article><article className="se-card"><span>LIMIT CHECK</span><h3>Value ≤ maximum—or ≥ minimum</h3><p>Example: upload size must be <strong>no more than 20 MB</strong>.</p></article></section><p className="se-note">Always state the actual rule and whether its boundary is inclusive.</p></Slide> },
    { time: "6 min", focus: "Distinguish format, length and presence through explicit rule notation.", prompt: "Can a six-character string still have the wrong format? Give an example.", source: "Syllabus 6.2 format, length and presence checks; Coursebook 9.05.", content: <Slide number="05" eyebrow="SHAPE + SIZE + NOT BLANK" sourceLabel="TEXTBOOK §9.05 · p.140" syllabusLabel="SYLLABUS 6.2" title="Three checks answer three different questions."><section className="se-rule-board"><article><b>FORMAT</b><code>LL-DDDD</code><p>Characters occur in a required pattern/type/order.</p></article><article><b>LENGTH</b><code>LEN = 7</code><p>Exact/minimum/maximum number of characters.</p></article><article><b>PRESENCE</b><code>value ≠ &quot;&quot;</code><p>Required field is not empty.</p></article><article><b>COMBINE</b><code>AB-2048</code><p>One value may pass several independent rules.</p></article></section></Slide> },
    { time: "5 min", focus: "Define existence as membership in an allowed lookup set, not merely a file check.", prompt: "Why can 'CS99' have the correct format and still fail existence?", source: "Syllabus 6.2 existence check; Coursebook 9.05, broadened to lookup tables.", content: <Slide number="06" eyebrow="EXISTENCE CHECK" sourceLabel="TEXTBOOK §9.05 · p.140" syllabusLabel="SYLLABUS 6.2" title="Does this value exist in the approved data set?"><section className="se-grid two"><article className="se-card"><span>INPUT</span><h3>CourseCode = “CS99”</h3><p>It may satisfy the format: two letters + two digits.</p></article><article className="se-card"><span>LOOKUP</span><h3>Search Course table</h3><p>If no matching key exists, the value fails the <strong>existence check</strong>.</p></article></section><p className="se-warning">Correct shape does not prove a real referenced record exists.</p></Slide> },
    { time: "6 min", focus: "Practise selecting the most specific validation check from a scenario.", prompt: "Students hold up the method, then articulate its accept/reject rule.", source: "Syllabus 6.2 all listed validation methods except check digit; Coursebook 9.05.", content: <Slide number="07" eyebrow="CHOOSE THE RULE" sourceLabel="TEXTBOOK §9.05 · p.140" syllabusLabel="SYLLABUS 6.2" title="Name it—and state what is accepted."><section className="se-grid four"><article className="se-card"><span>AGE 11–18</span><h3>Range</h3><p>11 ≤ Age ≤ 18</p></article><article className="se-card"><span>MAX 2 GB</span><h3>Limit</h3><p>Size ≤ 2 GB</p></article><article className="se-card"><span>REQUIRED EMAIL</span><h3>Presence</h3><p>Email is not blank</p></article><article className="se-card"><span>KNOWN USER ID</span><h3>Existence</h3><p>ID found in User table</p></article></section></Slide> },
    { time: "6 min", focus: "Show why real forms layer independent checks on one field.", prompt: "Design the minimum useful set of checks for a student ID and date.", source: "Coursebook 9.05 task/application; syllabus 6.2 use validation methods.", content: <Slide number="08" eyebrow="LAYER VALIDATION RULES" sourceLabel="TEXTBOOK §9.05 · APPLICATION" syllabusLabel="SYLLABUS 6.2" title="Each rule removes a different class of bad input."><section className="se-compare four"><div><b>FIELD</b><b>FORMAT</b><b>RANGE / LENGTH</b><b>EXISTENCE / PRESENCE</b></div><div><b>Student ID</b><span>LLDDDD</span><span>exactly 6 characters</span><span>found in Student table</span></div><div><b>Exam date</b><span>DD/MM/YYYY</span><span>valid day/month ranges</span><span>not blank; session exists</span></div><div><b>Quantity</b><span>digits expected</span><span>1–20</span><span>product exists</span></div></section></Slide> },
    { time: "6 min", focus: "Describe visual checking and double-entry verification precisely.", prompt: "Which method depends on a human comparison and which on two matching entries?", source: "Syllabus 6.2 data-entry verification; Coursebook 9.05 printed pp.141–142.", content: <Slide number="09" eyebrow="VERIFY AT ENTRY" sourceLabel="TEXTBOOK §9.05 · pp.141–142" syllabusLabel="SYLLABUS 6.2" title="Compare the entry with its intended source."><section className="se-grid two"><article className="se-card"><span>VISUAL CHECK</span><h3>Display/read back → person compares</h3><p>Fast and familiar, but the person can overlook a difference.</p></article><article className="se-card"><span>DOUBLE ENTRY</span><h3>Enter twice → computer compares</h3><p>A mismatch triggers re-entry; identical repeated mistakes may still pass.</p></article></section></Slide> },
    { time: "5 min", focus: "Make the limitations explicit so students avoid 'guarantees correctness'.", prompt: "Invent one wrong value that passes each gate.", source: "Coursebook 9.05 limitations; syllabus 6.2 integrity.", content: <Slide number="10" eyebrow="PASS ≠ TRUE" sourceLabel="TEXTBOOK §9.05 · pp.140–142" syllabusLabel="SYLLABUS 6.2" title="Checks reduce predictable errors; they do not know reality."><section className="se-grid three"><article className="se-card"><span>VALID BUT WRONG</span><p>Age 17 is in range; actual age is 16.</p></article><article className="se-card"><span>MATCHING BUT WRONG</span><p>Wrong date typed identically twice.</p></article><article className="se-card"><span>VALID CODE, WRONG ITEM</span><p>A real product code belongs to a different product.</p></article></section><p className="se-warning">Use “checks”, “detects” or “reduces”—never “guarantees accurate data”.</p></Slide> },
    { time: "6 min", focus: "Place check digit in the current syllabus validation list despite textbook grouping.", prompt: "What kind of entry error might an extra derived digit reveal?", source: "Syllabus 6.2 explicitly lists check digit under validation; Coursebook 9.05 printed p.141.", content: <Slide number="11" eyebrow="CHECK DIGIT" sourceLabel="TEXTBOOK §9.05 · p.141" syllabusLabel="SYLLABUS 6.2 · VALIDATION" title="A digit derived from the others tests whether the code is internally consistent."><section className="se-flow"><span>DATA<br />DIGITS</span><i>→</i><span>STATED WEIGHTS /<br />ALGORITHM</span><i>→</i><span>EXPECTED<br />CHECK DIGIT</span><i>→</i><span>COMPARE WITH<br />SUPPLIED DIGIT</span></section><p className="se-warning">The 2027–2029 syllabus classifies <strong>check digit as validation</strong>. It can detect many entry errors, but not prove the code refers to the intended real-world item.</p></Slide> },
    { time: "9 min", focus: "Use a supplied weighted-modulus rule step by step.", prompt: "Pairs calculate first, then one student audits each arithmetic step.", source: "Coursebook 9.05 check-digit activity; syllabus 6.2 describe and use check digit.", content: <Slide number="12" eyebrow="USE THE GIVEN ALGORITHM" sourceLabel="TEXTBOOK §9.05 · p.141" syllabusLabel="SYLLABUS 6.2" title="Find the check digit for 4725."><section className="se-check-digit"><div><span className="se-kicker">RULE</span><p>Multiply alternate digits by 1, 3, 1, 3. Add the products. Choose a check digit that makes the final total a multiple of 10.</p><code>4×1 + 7×3 + 2×1 + 5×3 = 42</code></div><div><span className="se-kicker">FINISH</span><p>Next multiple of 10: 50</p><code>50 − 42 = 8</code><p>Full code: <strong>47258</strong></p></div></section><p className="se-note">Do not memorise one universal check-digit formula. <strong>Use the algorithm stated in the question.</strong></p></Slide> },
    { time: "7 min", focus: "Recognise three syllabus methods from pseudocode-like evidence.", prompt: "Write only the method name, then justify verbally using the exact test.", source: "Adapted from 9618/13 O/N 2025 Q7(e), checked against the published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 3 MARKS" sourceLabel="9618/13 O/N 2025 · Q7(e)" syllabusLabel="SYLLABUS 6.2 — EXAM PRACTICE" title="Name the validation method in each algorithm." className="slide--se-paper"><section className="se-paper-grid three"><article><span>ALGORITHM 1</span><p>Accept only if Lower ≤ Value ≤ Upper.</p></article><article><span>ALGORITHM 2</span><p>Search the stored list for Code.</p></article><article><span>ALGORITHM 3</span><p>Test for two letters followed by four digits.</p></article></section><ExamReveal><p><strong>Range check</strong>; <strong>existence check</strong>; <strong>format check</strong>. Each earns one mark.</p></ExamReveal><small className="se-source-line">Concise adaptation of 9618/13 O/N 2025 Q7(e); original allocation [3].</small></Slide> },
    { time: "8 min", focus: "Design a defensible form with complementary checks and verification.", prompt: "Teams annotate the field, rule, error caught and residual limitation.", source: "Syllabus 6.2 application; Coursebook 9.05.", content: <Slide number="14" eyebrow="FORM DESIGN CLINIC" sourceLabel="TEXTBOOK §9.05 · APPLICATION" syllabusLabel="SYLLABUS 6.2" title="Registration form: choose checks that catch different errors."><section className="se-grid four"><article className="se-card"><span>STUDENT ID</span><p>six characters; must exist</p></article><article className="se-card"><span>DATE OF BIRTH</span><p>DD/MM/YYYY; plausible boundaries</p></article><article className="se-card"><span>COURSE CODE</span><p>pattern plus lookup</p></article><article className="se-card"><span>EMAIL</span><p>required; verify before submission</p></article></section><p className="se-note">For each: <strong>named method → exact acceptance rule → error caught → one limitation</strong>.</p></Slide> },
    { time: "5 min", focus: "Check the core distinction and two boundary methods.", prompt: "Students complete without notes and hand in one misconception they corrected.", source: "Syllabus 6.2 lesson synthesis; Coursebook 9.05.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK §9.05 · REVIEW" syllabusLabel="SYLLABUS 6.2" title="Three gates; three precise answers."><section className="se-exit"><article><span>1 · CLASSIFY</span><p>“Enter the value twice” is ___ because…</p></article><article><span>2 · DISTINGUISH</span><p>Range differs from limit because…</p></article><article><span>3 · QUALIFY</span><p>A check digit cannot prove…</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="31" slides={slides} homework={<HomeworkSheet lessonNumber="31" title="Data Integrity at Entry: Validation and Verification" marks={30} minutes={45} syllabusLabel="SYLLABUS 6.2" sourceLabel="TEXTBOOK CH.9 · pp.140–142 + PAPER 1" instructions="Name each method exactly, write the explicit acceptance/comparison rule and explain what error it can detect. Validation and verification reduce errors; neither guarantees truth. Use only the supplied check-digit algorithm." sections={homeworkSections} challenge={{ id: "l31-challenge", prompt: <p><Mark>CHALLENGE</Mark> Design a value that passes presence, length, format and existence checks but is still the wrong input for the user. Explain why every check passes.</p>, answer: <p>Example: the intended registered course is CS1024, but the user selects CS2048, which is another real course. It is non-blank, has the correct six-character format/length and exists in the Course table, yet it is not the intended course. This demonstrates that validation tests rules, not intention or truth.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 6.2, Coursebook Chapter 9 printed pp.140–142, and the published 2025 Paper 1 validation question and mark scheme." sourceDetail="Core: validation versus verification; range, format, length, presence, existence, limit and check digit; visual and double-entry verification. Authentic anchor: 9618/13 O/N 2025 Q7(e) [3]. Type check is a textbook extension rather than a named 2027–2029 requirement; parity and checksum are reserved for Lesson 32." />;
}
