"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { VmTower } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "VM structure", subtitle: "Label host, guest and virtual resources", marks: 10,
    questions: [
      { id: "a2-13-1", marks: 3, lines: 5, prompt: <><b>Define a virtual machine</b> and identify what creates it.</>, answer: <p>A virtual machine is a software emulation of a computer system <em>[1]</em>. VM software/a hypervisor creates and manages it <em>[1]</em>, presenting virtual hardware/resources to a guest operating system or process <em>[1]</em>.</p> },
      { id: "a2-13-2", marks: 3, lines: 5, prompt: <><b>Distinguish a host OS from a guest OS.</b></>, answer: <p>The host OS runs on and controls the physical computer/resources <em>[1]</em> and supports the VM software <em>[1]</em>. A guest OS runs inside a VM and controls the virtual hardware for its guest applications <em>[1]</em>.</p> },
      { id: "a2-13-3", marks: 4, lines: 7, prompt: <><b>Put these in a valid host-based order:</b> hardware, guest app, guest OS, host OS, VM software, virtual machine. Explain one link.</>, answer: <p>Hardware → host OS → VM software/monitor → virtual machine → guest OS → guest application <em>[3]</em>. The guest behaves as if virtual resources were real, while requests are mapped to host/physical resources <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Roles and benefits", subtitle: "Link every use to a mechanism", marks: 10,
    questions: [
      { id: "a2-13-4", marks: 3, lines: 5, prompt: <><b>Explain how a VM supports legacy software.</b></>, answer: <p>The old application can run with its required guest OS/environment <em>[1]</em> even if the host uses a different modern OS <em>[1]</em>, avoiding the need to keep separate old physical hardware <em>[1]</em>.</p> },
      { id: "a2-13-5", marks: 3, lines: 5, prompt: <><b>Explain how VMs make software testing safer.</b></>, answer: <p>The test runs in an isolated guest environment <em>[1]</em>, so a crash or malicious change is less likely to affect the host/other VMs <em>[1]</em>; the VM can be reset, cloned or discarded <em>[1]</em>.</p> },
      { id: "a2-13-6", marks: 4, lines: 7, prompt: <><b>Explain two benefits of server consolidation with VMs.</b></>, answer: <p>Several virtual servers share one physical host, increasing hardware utilisation and reducing the number of physical machines/cost/energy <em>[2]</em>. Each service keeps a separate guest environment, improving isolation and allowing different OS configurations on the same host <em>[2]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Limits and exam clinic", subtitle: "Evaluate the trade-off", marks: 10,
    questions: [
      { id: "a2-13-7", marks: 3, lines: 5, prompt: <><b>State three limitations of virtual machines.</b></>, answer: <p>Any three: performance overhead; physical resources must be shared; setup/administration complexity; some hardware cannot be fully emulated or accessed; failure of the host affects several VMs <em>[3]</em>.</p> },
      { id: "a2-13-8", marks: 3, lines: 5, prompt: <><b>Distinguish a system VM from a process VM.</b></>, answer: <p>A system VM emulates a complete computer so a guest OS and applications can run <em>[2]</em>. A process VM provides a platform-independent execution environment for one program/process, such as the JVM <em>[1]</em>.</p> },
      { id: "a2-13-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Explain two benefits and two limitations of running a guest OS in a virtual machine.</b></p><p>Adapted from 9618/32 M/J 2024 Q9(a). [4]</p></>, answer: <p>Benefits, any two linked points: incompatible/legacy OS and software can run; isolated testing protects the host; several systems share one physical machine, reducing hardware cost <em>[2]</em>. Limitations, any two: extra software/resource sharing reduces performance; configuration can be complex; hardware support may be incomplete; host failure affects guests <em>[2]</em>.</p> },
    ],
  },
];

export default function A2Lesson13Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Reveal how one physical computer can present several independent systems.", prompt: "Which layers are physical, and which are software?", source: "2027–2029 syllabus 15.1; coursebook Chapter 18 printed pp.346–347.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch18" syllabusLabel="SYLLABUS 15.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 13 · 90 MINUTES</span><h1>One physical host.<br /><em>Several virtual computers.</em></h1><p>VM structure · host and guest · roles · benefits · limitations</p></div><div className="a2-at-hero" role="img" aria-label="Virtual machine stack"><strong>VIRTUAL MACHINE</strong><span>GUEST OS</span><span>VM SOFTWARE</span><span>HOST OS</span><span>HARDWARE</span></div></section></Slide> },
    { time: "5 min", focus: "Map the exact VM learning outcomes.", prompt: "Students identify a definition, two roles, two benefits and two limits.", source: "Syllabus p.34; coursebook pp.346–347.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.34" syllabusLabel="15.1 · VIRTUAL MACHINES" title="A VM is software; its value comes from the environment it creates." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "DEFINE", title: "Software emulation", body: "Behaves like a computer system." }, { eyebrow: "LABEL", title: "Host + guest", body: "Separate physical and virtual control." }, { eyebrow: "APPLY", title: "Roles", body: "Compatibility, testing, consolidation." }, { eyebrow: "EVALUATE", title: "Trade-offs", body: "Isolation and flexibility cost resources." }]} /></Slide> },
    { time: "5 min", focus: "Define VM using software and emulation.", prompt: "Repair the statement: a VM is a second physical computer inside the case.", source: "Coursebook §18.04 p.346.", content: <Slide number="03" eyebrow="DEFINITION" sourceLabel="TEXTBOOK p.346" syllabusLabel="15.1 · CONCEPT" title="A virtual machine is software that emulates a computer system." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "SOFTWARE", title: "Created by VM software", body: "No extra physical processor is inserted." }, { eyebrow: "EMULATION", title: "Virtual resources", body: "CPU, memory, storage and devices are presented." }, { eyebrow: "ILLUSION", title: "Independent computer", body: "Guest software behaves as if resources were its own." }]} /></Slide> },
    { time: "6 min", focus: "Label the coursebook host-based VM stack.", prompt: "Trace a guest disk write down to physical storage.", source: "Coursebook Figure 18.05 pp.346–347.", content: <Slide number="04" eyebrow="SYSTEM STACK" sourceLabel="TEXTBOOK pp.346–347" syllabusLabel="15.1 · STRUCTURE" title="Virtual requests ultimately use resources controlled by the physical host." className="a2-slide a2-at-slide"><VmTower layers={[{ name: "Guest applications", detail: "run inside the guest environment", tone: "guest" }, { name: "Guest operating system", detail: "controls virtual hardware", tone: "guest" }, { name: "Virtual machine", detail: "emulated computer", tone: "virtual" }, { name: "VM software / monitor", detail: "maps and isolates resources", tone: "virtual" }, { name: "Host operating system", detail: "controls physical resources", tone: "host" }, { name: "Physical hardware", detail: "CPU · RAM · storage · devices", tone: "host" }]} /></Slide> },
    { time: "6 min", focus: "Distinguish host and guest OS responsibilities.", prompt: "Who believes the virtual disk is hardware, and who controls the real disk?", source: "Coursebook pp.346–347; 9618/32 M/J 2024 Q9(b).", content: <Slide number="05" eyebrow="HOST VS GUEST" sourceLabel="9618/32 M/J 2024 · Q9(b)" syllabusLabel="15.1 · TERMINOLOGY" title="The host manages physical resources; the guest manages virtual ones." className="a2-slide a2-at-slide"><CompareTable headers={["Host operating system", "Guest operating system"]} rows={[["runs on the physical machine", "runs inside a VM"], ["controls real devices/resources", "controls presented virtual devices"], ["supports/runs VM software", "supports guest applications"], ["one host environment", "one per virtual system"]]} /></Slide> },
    { time: "6 min", focus: "Explain the VM monitor's mediation role.", prompt: "Why can two guests both believe they own address 0?", source: "Coursebook p.347.", content: <Slide number="06" eyebrow="VM SOFTWARE" sourceLabel="TEXTBOOK p.347" syllabusLabel="15.1 · ROLE" title="The monitor maps virtual resources to shared physical resources." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "GUEST", title: "requests virtual CPU / memory" }, { eyebrow: "MONITOR", title: "maps + schedules + isolates" }, { eyebrow: "HOST", title: "controls physical resource" }, { eyebrow: "RESULT", title: "returns to correct guest" }]} /></Slide> },
    { time: "6 min", focus: "Separate system and process virtual machines.", prompt: "Does the environment run a whole OS or one application process?", source: "Coursebook pp.346–347; JVM supporting example.", content: <Slide number="07" eyebrow="TWO SCALES" sourceLabel="TEXTBOOK pp.346–347" syllabusLabel="15.1 · CONCEPT" title="A system VM hosts an OS; a process VM hosts a program." className="a2-slide a2-at-slide"><CompareTable headers={["System VM", "Process VM"]} rows={[["emulates a complete computer", "provides one execution environment"], ["runs a guest OS and applications", "runs one process/application"], ["server/test desktop example", "Java Virtual Machine example"], ["persists as a system", "usually ends with the process"]]} /></Slide> },
    { time: "6 min", focus: "Apply compatibility and legacy roles.", prompt: "How can an old application survive a host OS upgrade?", source: "Coursebook p.347; syllabus VM roles.", content: <Slide number="08" eyebrow="ROLE · COMPATIBILITY" sourceLabel="TEXTBOOK p.347" syllabusLabel="15.1 · ROLE" title="Preserve the environment an application expects." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "MODERN HOST", title: "Current hardware + OS" }, { eyebrow: "VM", title: "Emulates expected machine" }, { eyebrow: "OLD GUEST OS", title: "Required services" }, { eyebrow: "LEGACY APP", title: "Runs unchanged" }]} /></Slide> },
    { time: "6 min", focus: "Apply isolation to testing and security.", prompt: "What is contained when the guest crashes?", source: "Coursebook p.347; M/J 2022 Paper 31 VM scenario.", content: <Slide number="09" eyebrow="ROLE · SAFE TESTING" sourceLabel="9618/31 M/J 2022 · Q6" syllabusLabel="15.1 · ROLE" title="An isolated guest can fail without replacing the host environment." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "CLONE", title: "Repeatable baseline", body: "Begin each test from the same state." }, { eyebrow: "ISOLATE", title: "Contain changes", body: "Guest crash/malware is separated from host." }, { eyebrow: "RESET", title: "Discard or restore", body: "Recover quickly after a failed test." }]} /></Slide> },
    { time: "6 min", focus: "Explain server consolidation.", prompt: "Where do hardware savings come from, and what remains separate?", source: "Coursebook p.347; syllabus benefits.", content: <Slide number="10" eyebrow="ROLE · CONSOLIDATION" sourceLabel="TEXTBOOK p.347" syllabusLabel="15.1 · BENEFIT" title="Several isolated servers can share one physical host." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "VM 1", title: "Web", body: "guest A" }, { eyebrow: "VM 2", title: "Mail", body: "guest B" }, { eyebrow: "VM 3", title: "Database", body: "guest C" }, { eyebrow: "HOST", title: "Shared hardware", body: "CPU · RAM · storage" }]} /></Slide> },
    { time: "7 min", focus: "Link VM benefits to mechanisms.", prompt: "Turn each vague benefit into because + therefore.", source: "Coursebook p.347; 2022–2024 mark schemes.", content: <Slide number="11" eyebrow="BENEFITS" sourceLabel="2022–2024 PAPER 3" syllabusLabel="15.1 · EXPLAIN" title="Name the feature, then state what it enables." className="a2-slide a2-at-slide"><CompareTable headers={["Feature", "Mechanism", "Benefit"]} rows={[["compatibility", "guest recreates required OS", "legacy software runs"], ["isolation", "guests separated from host/each other", "safer testing"], ["consolidation", "several VMs share hardware", "lower hardware/energy cost"], ["portability", "VM state is software-defined", "clone/move environments"]]} /></Slide> },
    { time: "7 min", focus: "Evaluate VM limitations precisely.", prompt: "Which limits affect speed, management, hardware and resilience?", source: "Coursebook p.347; M/J 2024 Paper 32 mark scheme.", content: <Slide number="12" eyebrow="LIMITATIONS" sourceLabel="M/J 2024 · PAPER 32" syllabusLabel="15.1 · EVALUATE" title="Virtualisation adds a management layer and shares finite resources." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "SPEED", title: "Overhead", body: "Mapping and scheduling consume resources." }, { eyebrow: "CAPACITY", title: "Contention", body: "Guests share CPU, RAM and storage." }, { eyebrow: "SUPPORT", title: "Hardware limits", body: "Some devices are difficult to emulate." }, { eyebrow: "RISK", title: "Host dependency", body: "One host failure can stop many guests." }]} /></Slide> },
    { time: "7 min", focus: "Select a VM for a realistic school migration.", prompt: "Students justify use, benefit and limitation in three linked sentences.", source: "Adapted from 9618/31 M/J 2022 Q6.", content: <Slide number="13" eyebrow="DECISION CASE" sourceLabel="9618/31 M/J 2022 · Q6" syllabusLabel="15.1 · APPLY" title="A useful VM answer always returns to the scenario." className="a2-slide a2-at-slide"><CompareTable headers={["Need", "VM choice", "Linked consequence"]} rows={[["keep old database", "legacy guest OS", "application remains compatible"], ["test replacement", "cloned test VM", "failure is isolated/resettable"], ["reduce machines", "consolidate guests", "share one host"], ["predict performance", "test cautiously", "VM overhead may distort results"]]} /></Slide> },
    { time: "8 min", focus: "Apply host/guest and evaluation marks.", prompt: "Use two paired benefits/limitations, not four unlinked nouns.", source: "Adapted from Cambridge 9618/31 M/J 2022 Q6.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/31 M/J 2022 · Q6" syllabusLabel="15.1 · 6 MARKS" title="Explain why an organisation might use a virtual machine." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/31 M/J 2022 · Q6 · ADAPTED" marks={6} prompt={<p>Explain two benefits and one limitation of running a guest operating system in a VM. [6]</p>} answer={<ul><li>Compatibility: the guest recreates the OS expected by legacy/incompatible software. [2]</li><li>Isolation/consolidation: test safely or run several systems on one host, reducing separate hardware. [2]</li><li>Limitation: VM management/resource sharing adds overhead, so performance may be lower than native hardware. [2]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Close the VM topic with a complete structure-and-trade-off answer.", prompt: "One sentence each: definition, host, guest, role, benefit, limitation.", source: "Syllabus 15.1 synthesis; coursebook pp.346–347.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch18 · SYLLABUS p.34" syllabusLabel="15.1 · CHECKPOINT" title="Software creates the machine; resource mapping creates the trade-off." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>DEFINE</span><p>Software emulation of a computer.</p></article><article><span>STRUCTURE</span><p>Host · monitor · VM · guest.</p></article><article><span>ROLE</span><p>Compatibility · testing · consolidation.</p></article><article><span>EVALUATE</span><p>Flexibility vs overhead and complexity.</p></article></section><div className="homework-callout"><b>HOMEWORK 13</b><span>30 marks · VM structure, roles and trade-offs</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="13" title="Virtual machines" syllabusLabel="SYLLABUS 15.1" sourceLabel="TEXTBOOK Ch18 · pp.346–347" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 15.1 p.34 · endorsed coursebook Chapter 18 printed pp.346–347 · verified 2022 and 2024 Paper 3 questions and mark schemes" sourceDetail="The structure follows the coursebook host-based model, distinguishes host and guest operating systems, and evaluates VM roles with scenario-linked benefits and limitations." />;
}
