"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Reach third normal form", subtitle: "Dependencies, anomalies and complete designs", marks: 10,
    questions: [
      { id: "l38-1", marks: 3, lines: 3, prompt: <><b>State the conditions for a relation to be in 3NF.</b></>, answer: <p>It is already in 2NF; no non-key attribute depends on another non-key attribute (no transitive dependency); therefore every non-key attribute depends on the key, the whole key and nothing but the key. <em>[3]</em></p> },
      { id: "l38-2", marks: 3, lines: 3, prompt: <><b>Distinguish partial dependency from transitive dependency.</b></>, answer: <p>A partial dependency is a non-key attribute depending on only part of a composite key and is removed for 2NF. A transitive dependency is a non-key attribute depending on another non-key attribute rather than directly on the primary key and is removed for 3NF. <em>[3]</em></p> },
      { id: "l38-3", marks: 4, lines: 5, prompt: <><b>Normalise EMPLOYEE(EmployeeID, EmployeeName, DepartmentID, DepartmentName) to 3NF.</b></>, answer: <p>EMPLOYEE(<u>EmployeeID</u>, EmployeeName, DepartmentID) and DEPARTMENT(<u>DepartmentID</u>, DepartmentName). EMPLOYEE.DepartmentID is a foreign key referencing DEPARTMENT.DepartmentID. DepartmentName is moved because EmployeeID → DepartmentID → DepartmentName is a transitive dependency. <em>[4]</em></p> },
    ],
  },
  {
    code: "B", title: "Use the DBMS", subtitle: "Metadata, models, integrity, security and tools", marks: 10,
    questions: [
      { id: "l38-4", marks: 4, lines: 4, prompt: <><b>Explain four DBMS features that address file-based problems.</b></>, answer: <p>Any four explained: central data management reduces incompatible copies; a data dictionary records structure/constraints; a logical schema separates the model from physical storage; integrity constraints maintain valid data/links; access rights/views restrict users; backup/recovery restores data; data modelling documents entities and relationships. <em>[4]</em></p> },
      { id: "l38-5", marks: 3, lines: 3, prompt: <><b>What is a data dictionary, and give two items it may contain.</b></>, answer: <p>A data dictionary stores metadata—data about the database structure. It may contain table/field names, data types, sizes, keys, relationships, validation rules, defaults, indexes, users/permissions or views. Definition plus any two items. <em>[3]</em></p> },
      { id: "l38-6", marks: 3, lines: 3, prompt: <><b>Distinguish a developer interface from a query processor.</b></>, answer: <p>The developer interface provides tools to create/modify database objects and often forms, reports or menus. The query processor accepts/parses/optimises/executes a query such as SQL and returns the requested result or reports an error. <em>[3]</em></p> },
    ],
  },
  {
    code: "C", title: "Published design and DBMS questions", subtitle: "Paper 1 normalisation and terminology", marks: 10,
    questions: [
      { id: "l38-7", marks: 4, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Convert an unnormalised car-hire design into BOOKING, CAR and CUSTOMER tables in 3NF, showing keys.</b><p>Adapted from 9618/13 M/J 2023 Q4(c). [4]</p></>, answer: <p>CAR(<u>CarRegistration</u>, CarModel, CarColour); CUSTOMER(<u>CustomerID</u>, CustomerFirstName, CustomerLastName, EmailAddress, TelephoneNumber); BOOKING(<u>BookingID</u>, CarRegistration, CustomerID, StartDate, EndDate). BOOKING.CarRegistration and CustomerID are foreign keys. Marks reward three suitable tables, correct primary keys, both foreign keys in BOOKING and all fields placed correctly. <em>[4]</em></p> },
      { id: "l38-8", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Match these DBMS terms to their purposes: data dictionary, query processor, logical schema, developer interface.</b><p>Adapted from 9618/12 M/J 2023 Q2(a). [4]</p></>, answer: <p><strong>Data dictionary:</strong> metadata/structure. <strong>Query processor:</strong> processes query conditions/SQL and returns results. <strong>Logical schema:</strong> implementation-independent logical database model. <strong>Developer interface:</strong> tools used to create database objects/interfaces such as tables, forms and reports. <em>[4]</em></p> },
      { id: "l38-9", marks: 2, lines: 2, prompt: <><b>Explain two ways DBMS access rights protect data security.</b></>, answer: <p>Rights can restrict which tables/fields/rows a user or group may view, and can separately restrict operations such as insert, update or delete. This applies least privilege and reduces unauthorised disclosure or modification. <em>[2]</em></p> },
    ],
  },
];

export default function Lesson38Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Reveal a transitive dependency as a hidden duplicate fact.", prompt: "Ask: if DepartmentName changes, why should every employee row not need editing?", source: "Coursebook 11.05-11.06 printed pp.166-170; syllabus 8.1-8.2.", content: <Slide number="01" eyebrow="CHAPTER 8 · 3NF + DBMS" sourceLabel="TEXTBOOK CH.11 · pp.166-170" syllabusLabel="SYLLABUS 8.1–8.2" className="da-title"><section className="da-title-grid"><div className="da-title-copy"><span>LESSON 38 · 90 MINUTES</span><h1>Give every fact<br />its <em>rightful home.</em></h1><p>Remove transitive dependencies, produce complete 3NF designs and explain how a DBMS manages structure, integrity, security and queries.</p></div><div className="da-title-map"><div><b>3NF</b><span>NO NON-KEY → NON-KEY DEPENDENCY</span></div><div><b>DICT</b><span>METADATA DEFINES STRUCTURE</span></div><div><b>SCHEMA</b><span>LOGICAL MODEL OF THE DATABASE</span></div><div><b>TOOLS</b><span>DEVELOP + PROCESS QUERIES</span></div></div></section></Slide> },
    { time: "5 min", focus: "Show how two syllabus subsections meet without entering SQL syntax.", prompt: "Students point to the boundary: SQL begins next lesson.", source: "Syllabus 8.1-8.2 pp.25-26; Coursebook 11.05-11.06 printed pp.166-170.", content: <Slide number="02" eyebrow="TEXTBOOK × SYLLABUS" sourceLabel="TEXTBOOK §§11.05-11.06 · pp.166-170" syllabusLabel="SYLLABUS 8.1–8.2" title="Complete normalisation, then see what the DBMS provides."><section className="da-grid four"><article className="da-card"><span>3NF</span><p>remove transitive/non-key dependencies</p></article><article className="da-card"><span>DESIGN</span><p>explain whether tables are in 3NF; produce a normalised design</p></article><article className="da-card"><span>DBMS FEATURES</span><p>management, modelling, schema, integrity, security, backup and rights</p></article><article className="da-card"><span>DBMS TOOLS</span><p>data dictionary, developer interface and query processor</p></article></section><p className="da-note">DDL and DML syntax are explicitly deferred to Lessons 39–40.</p></Slide> },
    { time: "6 min", focus: "Define 3NF using functional dependency.", prompt: "Students complete: every non-key attribute depends on…", source: "Coursebook 11.05 printed pp.166-167, corrected; syllabus 8.1 3NF.", content: <Slide number="03" eyebrow="THIRD NORMAL FORM · 3NF" sourceLabel="TEXTBOOK §11.05 · pp.166-167" syllabusLabel="SYLLABUS 8.1" title="2NF + no transitive dependency."><section className="da-grid three"><article className="da-card"><span>THE KEY</span><p>A primary key uniquely identifies the row.</p></article><article className="da-card"><span>THE WHOLE KEY</span><p>No non-key attribute depends on only part of a composite key.</p></article><article className="da-card"><span>NOTHING BUT THE KEY</span><p>No non-key attribute depends on another non-key attribute.</p></article></section><p className="da-warning">The memory phrase helps, but marks come from identifying the actual dependency and moving attributes to the correct table.</p></Slide> },
    { time: "6 min", focus: "Make a transitive dependency visible as a chain.", prompt: "Ask which arrow causes DepartmentName to be repeated.", source: "Coursebook 11.05 printed pp.166-167; syllabus 8.1.", content: <Slide number="04" eyebrow="TRANSITIVE DEPENDENCY" sourceLabel="TEXTBOOK §11.05 · pp.166-167" syllabusLabel="SYLLABUS 8.1" title="EmployeeID determines DepartmentName through DepartmentID."><section className="da-flow"><span>EmployeeID<br /><strong>PRIMARY KEY</strong></span><i>→</i><span>DepartmentID<br /><strong>NON-KEY</strong></span><i>→</i><span>DepartmentName<br /><strong>NON-KEY</strong></span><i>→</i><span>MOVE DEPARTMENT<br />FACTS OUT</span></section><pre className="da-code">EMPLOYEE(<strong>EmployeeID</strong>, EmployeeName, <span className="accent">DepartmentID</span>){"\n"}DEPARTMENT(<strong>DepartmentID</strong>, DepartmentName)</pre></Slide> },
    { time: "6 min", focus: "Connect dependencies to update, insertion and deletion anomalies.", prompt: "For each anomaly, say which fact is lost or forced to duplicate.", source: "Coursebook 11.01 and 11.05; syllabus 8.1 purpose of normalisation.", content: <Slide number="05" eyebrow="WHY NORMALISE?" sourceLabel="TEXTBOOK §§11.01 + 11.05" syllabusLabel="SYLLABUS 8.1" title="Dependencies create predictable data anomalies."><section className="da-grid three"><article className="da-card"><span>UPDATE ANOMALY</span><h3>Many copies</h3><p>A department rename must be changed in every employee row or copies disagree.</p></article><article className="da-card"><span>INSERT ANOMALY</span><h3>Missing parent context</h3><p>A new department cannot be stored until it has an employee.</p></article><article className="da-card"><span>DELETE ANOMALY</span><h3>Unintended fact loss</h3><p>Deleting the last employee may also delete the only department details.</p></article></section></Slide> },
    { time: "6 min", focus: "Give one reusable normalisation decision routine.", prompt: "Students identify which question corresponds to 1NF, 2NF and 3NF.", source: "Coursebook 11.05 printed pp.165-167; syllabus 8.1 complete design.", content: <Slide number="06" eyebrow="NORMALISATION ROUTINE" sourceLabel="TEXTBOOK §11.05 · METHOD" syllabusLabel="SYLLABUS 8.1" title="Keys and dependencies drive every move."><section className="da-flow"><span>REMOVE REPEATING<br />GROUPS · 1NF</span><i>→</i><span>IDENTIFY THE<br />PRIMARY KEY</span><i>→</i><span>REMOVE PARTIAL<br />DEPENDENCIES · 2NF</span><i>→</i><span>REMOVE TRANSITIVE<br />DEPENDENCIES · 3NF</span></section><p className="da-note">After splitting, show every primary key and the foreign keys that reconstruct the original relationships.</p></Slide> },
    { time: "6 min", focus: "Introduce the DBMS as the controlled layer between applications and stored data.", prompt: "What rule belongs centrally rather than being rewritten in every app?", source: "Coursebook 11.06 printed pp.168-170; syllabus 8.2.", content: <Slide number="07" eyebrow="WHAT A DBMS PROVIDES" sourceLabel="TEXTBOOK §11.06 · pp.168-170" syllabusLabel="SYLLABUS 8.2" title="One managed model, many authorised users and applications."><section className="da-grid four"><article className="da-card"><span>MANAGEMENT + MODEL</span><p>define, store, organise and change data through a logical schema</p></article><article className="da-card"><span>INTEGRITY</span><p>types, validation, key uniqueness and referential constraints</p></article><article className="da-card"><span>SECURITY</span><p>individual/group access rights, views and controlled operations</p></article><article className="da-card"><span>RECOVERY</span><p>backup procedures and restoration after loss or corruption</p></article></section></Slide> },
    { time: "7 min", focus: "Work a complete 3NF design with explicit dependencies and links.", prompt: "Students underline PKs and label FKs before discussing table names.", source: "Coursebook 11.05 worked normalisation; syllabus 8.1 produce a design.", content: <Slide number="08" eyebrow="WORKED 3NF DESIGN · BOOKINGS" sourceLabel="TEXTBOOK §11.05 · pp.165-167" syllabusLabel="SYLLABUS 8.1" title="One booking links one customer and one vehicle."><pre className="da-code">CUSTOMER(<strong>CustomerID</strong>, FirstName, LastName, Email){"\n"}CAR(<strong>CarRegistration</strong>, Model, Colour){"\n"}BOOKING(<strong>BookingID</strong>, <span className="accent">CustomerID</span>, <span className="accent">CarRegistration</span>, StartDate, EndDate)</pre><section className="da-grid three"><article className="da-card"><span>IDENTITY</span><p>each table has a stable primary key</p></article><article className="da-card"><span>DEPENDENCY</span><p>descriptive facts depend only on their table&apos;s key</p></article><article className="da-card"><span>LINKS</span><p>BOOKING carries both foreign keys</p></article></section></Slide> },
    { time: "6 min", focus: "Distinguish the logical schema from the metadata that describes it.", prompt: "Sort example items into schema design versus dictionary entry.", source: "Coursebook 11.06 printed pp.168-170; syllabus 8.2.", content: <Slide number="09" eyebrow="SCHEMA + DATA DICTIONARY" sourceLabel="TEXTBOOK §11.06 · pp.168-170" syllabusLabel="SYLLABUS 8.2" title="The model says what exists; metadata records how it is defined."><section className="da-grid two"><article className="da-card"><span>LOGICAL SCHEMA</span><h3>Database model</h3><p>Tables, attributes, keys, relationships and constraints, independent of a particular physical storage layout.</p></article><article className="da-card"><span>DATA DICTIONARY</span><h3>Metadata catalogue</h3><p>Names, data types, sizes, keys, relationships, validation rules, defaults, indexes, views and access details.</p></article></section><p className="da-warning">Metadata is “data about data”. Access is privilege-controlled; it is not necessarily hidden from everyone except one administrator.</p></Slide> },
    { time: "6 min", focus: "Separate the two software tools explicitly named by the syllabus.", prompt: "Students trace a developer creating a table and a user submitting a query.", source: "Coursebook 11.06 printed p.169; syllabus 8.2 developer interface/query processor.", content: <Slide number="10" eyebrow="TOOLS INSIDE THE DBMS" sourceLabel="TEXTBOOK §11.06 · p.169" syllabusLabel="SYLLABUS 8.2" title="Build with the developer interface; execute through the query processor."><section className="da-flow"><span>DEVELOPER<br />INTERFACE</span><i>→</i><span>CREATE / MODIFY<br />OBJECTS + FORMS</span><i>·</i><span>QUERY<br />PROCESSOR</span><i>→</i><span>PARSE, OPTIMISE,<br />EXECUTE, RETURN</span></section><p className="da-note">Access rights may be assigned to individuals or groups and can separate read, insert, update and delete permissions.</p></Slide> },
    { time: "7 min", focus: "Teach the mark-scoring table-schema format.", prompt: "Students check three things: tables, keys/links, every attribute placed once.", source: "9618/13 M/J 2023 Q4(c) published mark scheme; syllabus 8.1.", content: <Slide number="11" eyebrow="EXAM METHOD · NORMALISED DESIGN" sourceLabel="9618/13 M/J 2023 · Q4(c)" syllabusLabel="SYLLABUS 8.1 — PAPER 1" title="Name relations, mark keys and preserve every required field."><section className="da-grid three"><article className="da-card"><span>1 · TABLE SET</span><p>one relation per entity/link with sensible names</p></article><article className="da-card"><span>2 · KEYS</span><p>clear primary keys and foreign keys on the correct side</p></article><article className="da-card"><span>3 · COVERAGE</span><p>all original attributes included once in the right relation</p></article></section><p className="da-warning">Do not invent unnecessary tables or lose a field during decomposition.</p></Slide> },
    { time: "8 min", focus: "Attempt an authentic normalisation design.", prompt: "Students produce relations with underlined PKs and labelled FKs before reveal.", source: "Adapted from 9618/13 M/J 2023 Q4(c), checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/13 M/J 2023 · Q4(c)" syllabusLabel="SYLLABUS 8.1 — PAPER 1" title="Normalise a car-hire design into BOOKING, CAR and CUSTOMER." className="slide--da-paper"><section className="da-paper-grid three"><article><span>TABLES</span><p>exactly three sensible relations</p></article><article><span>KEYS + LINKS</span><p>one PK each; BOOKING carries two FKs</p></article><article><span>ATTRIBUTES</span><p>place every given fact in its correct table</p></article></section><ExamReveal><p>CAR(CarRegistration, CarModel, CarColour); CUSTOMER(CustomerID, CustomerFirstName, CustomerLastName, EmailAddress, TelephoneNumber); BOOKING(BookingID, CarRegistration, CustomerID, StartDate, EndDate). BOOKING contains the CAR and CUSTOMER keys as foreign keys.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [4].</small></Slide> },
    { time: "8 min", focus: "Retrieve the four named DBMS terms in a published question.", prompt: "One precise purpose per term; students cannot use the term itself in its definition.", source: "Adapted from 9618/12 M/J 2023 Q2(a), checked against published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/12 M/J 2023 · Q2(a)" syllabusLabel="SYLLABUS 8.2 — PAPER 1" title="Identify four DBMS components or descriptions." className="slide--da-paper"><section className="da-paper-grid four"><article><span>DATA DICTIONARY</span><p>metadata and structure</p></article><article><span>QUERY PROCESSOR</span><p>conditions/SQL to result</p></article><article><span>LOGICAL SCHEMA</span><p>implementation-independent model</p></article><article><span>DEVELOPER INTERFACE</span><p>create objects and user interfaces</p></article></section><ExamReveal><p>The data dictionary records metadata; the query processor accepts and executes queries; the logical schema represents the database model independently of a specific DBMS/storage; the developer interface supplies tools to build and modify tables, forms, reports and related objects.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [4].</small></Slide> },
    { time: "5 min", focus: "Connect design quality to DBMS enforcement.", prompt: "Students give one 3NF rule and one DBMS feature for each risk.", source: "Syllabus 8.1-8.2 synthesis; Coursebook 11.05-11.06.", content: <Slide number="14" eyebrow="MIXED RETRIEVAL" sourceLabel="TEXTBOOK §§11.05-11.06 · REVIEW" syllabusLabel="SYLLABUS 8.1–8.2" title="Good structure + controlled management."><section className="da-flow"><span>REMOVE TRANSITIVE<br />DEPENDENCY</span><i>→</i><span>DEFINE LOGICAL<br />SCHEMA</span><i>→</i><span>RECORD METADATA<br />IN DICTIONARY</span><i>→</i><span>ENFORCE INTEGRITY,<br />RIGHTS + BACKUP</span></section></Slide> },
    { time: "4 min", focus: "Close Chapter 8 design concepts and signal the move to SQL.", prompt: "One sentence per card; collect as the lesson exit.", source: "Syllabus 8.1-8.2 checkpoint; Coursebook Chapter 11 sequence.", content: <Slide number="15" eyebrow="EXIT TICKET · NEXT: SQL" sourceLabel="TEXTBOOK CH.11 · pp.166-170" syllabusLabel="SYLLABUS 8.1–8.2" title="Three ideas before writing DDL."><section className="da-exit"><article><span>3NF</span><p>What dependency is removed?</p></article><article><span>DICTIONARY</span><p>What metadata does it hold?</p></article><article><span>DBMS</span><p>How do tools, integrity and security work together?</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="38" slides={slides} homework={<HomeworkSheet lessonNumber="38" title="Third Normal Form and DBMS Features" marks={30} minutes={45} syllabusLabel="SYLLABUS 8.1–8.2" sourceLabel="TEXTBOOK CH.11 · pp.166-170 + PAPER 1" instructions="Show functional dependencies before moving attributes. In every DBMS explanation, name the feature, what it stores or controls, and the problem it addresses." sections={homeworkSections} challenge={{ id: "l38-challenge", prompt: <p><Mark>CHALLENGE</Mark> Explain why a database can be in 3NF yet still need integrity constraints and backups.</p>, answer: <p>3NF controls structural dependencies and reduces anomalies; it does not stop an invalid value, unauthorised update, hardware failure or accidental deletion. Domain/key/referential constraints protect validity, access rights protect authorised use, and backups support recovery.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 8.1-8.2, Coursebook Chapter 11 printed pp.166-170 (PDF pp.173-177) and published Paper 1 questions/mark schemes." sourceDetail="Core: 3NF, transitive dependencies, complete normalised designs, DBMS data management/modelling/logical schema/integrity/security/backup/access rights, data dictionary, developer interface and query processor. Authentic anchors: 9618/13 M/J 2023 Q4(c) [4] and 9618/12 M/J 2023 Q2(a) [4]." />;
}
