/* SQL literals intentionally retain their source notation. */
/* eslint-disable react/no-unescaped-entities */
"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Build the result set", subtitle: "Clauses, sorting, grouping and aggregates", marks: 10,
    questions: [
      { id: "l40-1", marks: 4, lines: 4, prompt: <><b>Explain the purpose of SELECT, FROM, WHERE and ORDER BY.</b></>, answer: <p>SELECT chooses the fields/expressions returned; FROM identifies the source table(s); WHERE filters individual rows by a condition; ORDER BY sorts the final result by named field(s), ascending by default or descending with DESC. <em>[4]</em></p> },
      { id: "l40-2", marks: 3, lines: 3, prompt: <><b>Distinguish SUM, COUNT and AVG.</b></>, answer: <p>SUM totals the numeric values in a field; COUNT returns how many qualifying rows/non-null field values (COUNT(*) counts rows); AVG returns the arithmetic mean of qualifying non-null numeric values. <em>[3]</em></p> },
      { id: "l40-3", marks: 3, lines: 3, prompt: <><b>Explain why GROUP BY is used with an aggregate.</b></>, answer: <p>GROUP BY partitions qualifying rows by equal values in one or more fields. The aggregate is then calculated separately for each group, such as COUNT(*) for each Department. It is not merely a command to remove duplicates. <em>[3]</em></p> },
    ],
  },
  {
    code: "B", title: "Join and maintain", subtitle: "Two linked tables plus safe row changes", marks: 10,
    questions: [
      { id: "l40-4", marks: 4, lines: 5, prompt: <><b>Write SQL to return each BOOK.Title and its AUTHOR.AuthorName. BOOK.AuthorID references AUTHOR.AuthorID.</b></>, answer: <pre>SELECT BOOK.Title, AUTHOR.AuthorName{"\n"}FROM BOOK INNER JOIN AUTHOR{"\n"}ON BOOK.AuthorID = AUTHOR.AuthorID;</pre> },
      { id: "l40-5", marks: 3, lines: 4, prompt: <><b>Write SQL to change BookID 17 so InStock becomes FALSE.</b></>, answer: <pre>UPDATE BOOK{"\n"}SET InStock = FALSE{"\n"}WHERE BookID = 17;</pre> },
      { id: "l40-6", marks: 3, lines: 4, prompt: <><b>Write SQL to insert member 205, “Ari Khan”, active TRUE into MEMBER(MemberID, MemberName, Active).</b></>, answer: <pre>INSERT INTO MEMBER (MemberID, MemberName, Active){"\n"}VALUES (205, 'Ari Khan', TRUE);</pre> },
    ],
  },
  {
    code: "C", title: "Published SQL practice", subtitle: "Query, insert and delete under Paper 1 conditions", marks: 10,
    questions: [
      { id: "l40-7", marks: 5, lines: 6, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Return ProductID, ProductName and ComplaintDetails from PRODUCT and COMPLAINT where Rating is at most 5, ordered by Rating descending.</b><p>Adapted from 9618/13 O/N 2025 Q5(c). [5]</p></>, answer: <pre>SELECT PRODUCT.ProductID, PRODUCT.ProductName, COMPLAINT.ComplaintDetails{"\n"}FROM PRODUCT INNER JOIN COMPLAINT{"\n"}ON PRODUCT.ProductID = COMPLAINT.ProductID{"\n"}WHERE COMPLAINT.Rating &lt;= 5{"\n"}ORDER BY COMPLAINT.Rating DESC;</pre> },
      { id: "l40-8", marks: 3, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Insert a supplied collection record into a table, including text and numeric values.</b><p>Adapted from 9618/13 M/J 2025 Q6(b). [3 of 4 marks]</p></>, answer: <p>Use <code>INSERT INTO TableName (field list) VALUES (value list);</code>. Field and value order must match; text/date literals use quotes as required by the question/DBMS, numeric and Boolean values are not quoted. The original mark scheme also rewards the exact supplied identifiers and values. <em>[3]</em></p> },
      { id: "l40-9", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Delete every completed placement row.</b><p>Adapted from 9618/11 O/N 2025 Q2(c)(i). [2]</p></>, answer: <pre>DELETE FROM PLACEMENT{"\n"}WHERE Complete = TRUE;</pre> },
    ],
  },
];

export default function Lesson40Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame SQL as a pipeline from rows to a result, not a phrase-matching exercise.", prompt: "Ask: which rows survive, which fields remain, and in what order?", source: "Coursebook 11.07 printed pp.171-176; syllabus 8.3.", content: <Slide number="01" eyebrow="CHAPTER 8 · SQL DML" sourceLabel="TEXTBOOK CH.11 · pp.171-176" syllabusLabel="SYLLABUS 8.3" className="da-title"><section className="da-title-grid"><div className="da-title-copy"><span>LESSON 40 · 90 MINUTES</span><h1>Ask precisely.<br /><em>Change carefully.</em></h1><p>Build single- and two-table queries, aggregate groups and maintain data with INSERT, UPDATE and DELETE.</p></div><div className="da-title-map"><div><b>Q</b><span>SELECT · WHERE · ORDER</span></div><div><b>Σ</b><span>SUM · COUNT · AVG · GROUP</span></div><div><b>⋈</b><span>INNER JOIN TWO TABLES</span></div><div><b>Δ</b><span>INSERT · UPDATE · DELETE</span></div></div></section></Slide> },
    { time: "5 min", focus: "Expose every remaining 8.3 keyword and the two-table limit.", prompt: "Students identify which clauses change rows and which only return a result.", source: "Syllabus 8.3 p.27; Coursebook 11.07 printed pp.171-173 plus exam questions pp.174-176.", content: <Slide number="02" eyebrow="TEXTBOOK × SYLLABUS" sourceLabel="TEXTBOOK §11.07 · pp.171-176" syllabusLabel="SYLLABUS 8.3" title="Query and modify data in at most two tables."><section className="da-grid four"><article className="da-card"><span>CORE QUERY</span><p>SELECT · FROM · WHERE · ORDER BY</p></article><article className="da-card"><span>AGGREGATION</span><p>GROUP BY · SUM · COUNT · AVG</p></article><article className="da-card"><span>RELATIONSHIP</span><p>INNER JOIN … ON matching key fields</p></article><article className="da-card"><span>MAINTENANCE</span><p>INSERT INTO · UPDATE · DELETE FROM</p></article></section><p className="da-note">Not required here: OUTER JOIN, HAVING, DISTINCT, subqueries or joins across three or more tables.</p></Slide> },
    { time: "6 min", focus: "Teach the logical role and written order of core query clauses.", prompt: "Students narrate the query from FROM/WHERE to SELECT, while preserving SQL written order.", source: "Coursebook 11.07 printed pp.171-172; syllabus 8.3.", content: <Slide number="03" eyebrow="CORE SELECT PIPELINE" sourceLabel="TEXTBOOK §11.07 · pp.171-172" syllabusLabel="SYLLABUS 8.3" title="Source → filter → choose fields → sort the result."><pre className="da-code"><strong>SELECT</strong> StudentName, Score{"\n"}<strong>FROM</strong> RESULT{"\n"}<strong>WHERE</strong> Score &gt;= 70{"\n"}<strong>ORDER BY</strong> Score DESC;</pre><section className="da-flow"><span>FROM<br />SOURCE ROWS</span><i>→</i><span>WHERE<br />KEEP MATCHES</span><i>→</i><span>SELECT<br />RETURN FIELDS</span><i>→</i><span>ORDER BY<br />SORT RESULT</span></section></Slide> },
    { time: "6 min", focus: "Build compound WHERE conditions and explicit sort direction.", prompt: "Ask which rows pass both conditions and how ties are handled by a second sort field.", source: "Coursebook 11.07 printed pp.171-173; syllabus 8.3 WHERE/ORDER BY.", content: <Slide number="04" eyebrow="FILTER + SORT" sourceLabel="TEXTBOOK §11.07 · pp.171-173" syllabusLabel="SYLLABUS 8.3" title="Conditions use comparison and logic; sorting is ascending unless DESC is written."><pre className="da-code">SELECT ItemName, Price{"\n"}FROM PRODUCT{"\n"}WHERE Price &lt; 25.00 AND InStock = TRUE{"\n"}ORDER BY Price DESC, ItemName;</pre><section className="da-grid three"><article className="da-card"><span>WHERE</span><p>tests each source row</p></article><article className="da-card"><span>AND / OR / NOT</span><p>combine Boolean conditions carefully</p></article><article className="da-card"><span>ORDER BY</span><p>sorts surviving rows; a second field resolves ties</p></article></section></Slide> },
    { time: "6 min", focus: "Distinguish aggregate functions and COUNT(*) semantics.", prompt: "Predict the result type and what null values may change.", source: "Coursebook 11.07 printed pp.171-173, COUNT correction; syllabus 8.3.", content: <Slide number="05" eyebrow="AGGREGATE FUNCTIONS" sourceLabel="TEXTBOOK §11.07 · CORRECTED" syllabusLabel="SYLLABUS 8.3" title="Many qualifying rows become one calculated value."><section className="da-grid four"><article className="da-card"><span>SUM(Amount)</span><p>total of qualifying numeric values</p></article><article className="da-card"><span>COUNT(*)</span><p>number of qualifying rows</p></article><article className="da-card"><span>COUNT(Field)</span><p>number of qualifying non-null field values</p></article><article className="da-card"><span>AVG(Score)</span><p>mean of qualifying non-null numeric values</p></article></section><p className="da-warning">COUNT(*) FROM BAND counts band rows, not total members. Use SUM(NumberOfMembers) for the latter.</p></Slide> },
    { time: "6 min", focus: "Teach GROUP BY as partition then aggregate.", prompt: "Students sketch the intermediate groups before calculating COUNT.", source: "Coursebook 11.07 printed pp.171-173; syllabus 8.3 GROUP BY.", content: <Slide number="06" eyebrow="GROUP THEN CALCULATE" sourceLabel="TEXTBOOK §11.07 · pp.171-173" syllabusLabel="SYLLABUS 8.3" title="One output row per group."><pre className="da-code">SELECT Department, COUNT(*) AS StaffTotal{"\n"}FROM STAFF{"\n"}WHERE RemoteWorker = TRUE{"\n"}GROUP BY Department;</pre><table className="da-table"><thead><tr><th>Department group</th><th>qualifying rows</th><th>StaffTotal</th></tr></thead><tbody><tr><td>Sales</td><td>three remote staff rows</td><td>3</td></tr><tr><td>Support</td><td>two remote staff rows</td><td>2</td></tr></tbody></table></Slide> },
    { time: "6 min", focus: "Build an explicit INNER JOIN using matching primary/foreign keys.", prompt: "Circle the join fields and explain why unrelated combinations disappear.", source: "Coursebook 11.07 printed pp.171-173, old-style join corrected; syllabus 8.3.", content: <Slide number="07" eyebrow="INNER JOIN · TWO TABLES" sourceLabel="TEXTBOOK §11.07 · CORRECTED" syllabusLabel="SYLLABUS 8.3" title="Combine only rows whose key values match."><pre className="da-code">SELECT BOOK.Title, AUTHOR.AuthorName{"\n"}FROM BOOK <strong>INNER JOIN</strong> AUTHOR{"\n"}<span className="accent">ON BOOK.AuthorID = AUTHOR.AuthorID</span>{"\n"}WHERE BOOK.InStock = TRUE;</pre><p className="da-note">Qualify duplicate field names with their table, such as BOOK.AuthorID. In this syllabus, write joins for at most two tables.</p></Slide> },
    { time: "7 min", focus: "Work a joined, filtered and sorted query clause by clause.", prompt: "Students build the statement in the order SELECT, FROM/JOIN, ON, WHERE, ORDER BY.", source: "Coursebook 11.07 method; syllabus 8.3 two-table query.", content: <Slide number="08" eyebrow="WORKED QUERY · COMPLAINTS" sourceLabel="TEXTBOOK §11.07 · APPLICATION" syllabusLabel="SYLLABUS 8.3" title="Return product names with low-rated complaints, worst first."><pre className="da-code">SELECT PRODUCT.ProductID, PRODUCT.ProductName, COMPLAINT.ComplaintDetails{"\n"}FROM PRODUCT INNER JOIN COMPLAINT{"\n"}ON PRODUCT.ProductID = COMPLAINT.ProductID{"\n"}WHERE COMPLAINT.Rating &lt;= 5{"\n"}ORDER BY COMPLAINT.Rating ASC;</pre><section className="da-grid three"><article className="da-card"><span>JOIN</span><p>matches complaint to its product</p></article><article className="da-card"><span>FILTER</span><p>keeps ratings at most 5</p></article><article className="da-card"><span>SORT</span><p>ASC puts the lowest rating first</p></article></section></Slide> },
    { time: "6 min", focus: "Distinguish three data-maintenance commands and stress WHERE safety.", prompt: "Ask what happens if WHERE is omitted from UPDATE or DELETE.", source: "Coursebook 11.07 printed pp.171-173, INSERT corrected; syllabus 8.3.", content: <Slide number="09" eyebrow="MAINTAIN THE ROWS" sourceLabel="TEXTBOOK §11.07 · CORRECTED" syllabusLabel="SYLLABUS 8.3" title="INSERT adds; UPDATE changes; DELETE removes."><section className="da-grid three"><article className="da-card"><span>INSERT</span><pre className="da-code">INSERT INTO CLUB (ClubID, ClubName){"\n"}VALUES (7, 'Robotics');</pre></article><article className="da-card"><span>UPDATE</span><pre className="da-code">UPDATE CLUB SET Active = FALSE{"\n"}WHERE ClubID = 7;</pre></article><article className="da-card"><span>DELETE</span><pre className="da-code">DELETE FROM CLUB{"\n"}WHERE ClubID = 7;</pre></article></section><p className="da-warning">Without WHERE, UPDATE changes every row and DELETE removes every row. Read the required scope before writing the command.</p></Slide> },
    { time: "6 min", focus: "Repair the textbook's malformed INSERT and join examples.", prompt: "Students identify missing VALUES and the missing joined table.", source: "Coursebook 11.07 printed pp.171-173, syntax corrected against current syllabus.", content: <Slide number="10" eyebrow="TEXTBOOK SQL · REPAIR" sourceLabel="TEXTBOOK §11.07 · UPDATED" syllabusLabel="SYLLABUS 8.3" title="Correct syntax must also return the intended meaning."><section className="da-compare"><div><span>FAULT</span><span>CORRECTION</span><span>REASON</span></div><div><b>INSERT INTO Band ('ComputerKidz', 5)</b><span>INSERT INTO Band VALUES ('ComputerKidz', 5)</span><span>VALUES keyword is required</span></div><div><b>join condition names BandBooking but FROM omits it</b><span>explicit INNER JOIN with both tables</span><span>every referenced table must be in FROM/JOIN</span></div><div><b>GROUP BY removes duplicates</b><span>GROUP BY forms groups for aggregates</span><span>purpose is per-group calculation</span></div></section></Slide> },
    { time: "7 min", focus: "Teach a dependable query-building order.", prompt: "Students translate one natural-language requirement into the six boxes.", source: "9618/13 O/N 2025 Q5(c) mark-scheme categories; syllabus 8.3.", content: <Slide number="11" eyebrow="EXAM METHOD · BUILD BY CLAUSE" sourceLabel="9618/13 O/N 2025 · Q5(c)" syllabusLabel="SYLLABUS 8.3 — PAPER 1" title="Output fields → tables → link → filter → group → order."><section className="da-flow five"><span>SELECT<br />FIELDS</span><i>→</i><span>FROM +<br />JOIN TABLES</span><i>→</i><span>ON MATCHING<br />KEYS</span><i>→</i><span>WHERE / GROUP<br />CONDITIONS</span><i>→</i><span>ORDER BY<br />DIRECTION</span></section><p className="da-note">Then audit quoted text, Boolean/numeric literals, comparison operator and final semicolon.</p></Slide> },
    { time: "8 min", focus: "Attempt an authentic five-mark two-table query.", prompt: "One minute to annotate output, tables, link, filter and order; four minutes to write.", source: "Adapted from 9618/13 O/N 2025 Q5(c), checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 5 MARKS" sourceLabel="9618/13 O/N 2025 · Q5(c)" syllabusLabel="SYLLABUS 8.3 — PAPER 1" title="PRODUCT + COMPLAINT: low ratings in descending order." className="slide--da-paper"><section className="da-paper-grid three"><article><span>RETURN</span><p>ProductID, ProductName, ComplaintDetails</p></article><article><span>FILTER</span><p>Rating is at most 5</p></article><article><span>ORDER</span><p>Rating descending</p></article></section><ExamReveal><p>SELECT PRODUCT.ProductID, PRODUCT.ProductName, COMPLAINT.ComplaintDetails FROM PRODUCT INNER JOIN COMPLAINT ON PRODUCT.ProductID = COMPLAINT.ProductID WHERE COMPLAINT.Rating &lt;= 5 ORDER BY COMPLAINT.Rating DESC;</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [5].</small></Slide> },
    { time: "8 min", focus: "Practise two published maintenance forms with contrasting scope.", prompt: "Students write both, then underline VALUES and WHERE.", source: "Adapted from 9618/13 M/J 2025 Q6(b) and 9618/11 O/N 2025 Q2(c)(i), checked against mark schemes.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · MAINTENANCE" sourceLabel="9618/13 M/J 2025 + 9618/11 O/N 2025" syllabusLabel="SYLLABUS 8.3 — PAPER 1" title="Insert one supplied row; delete all completed placements." className="slide--da-paper"><section className="da-paper-grid"><article><span>INSERT</span><p>field order must match value order; quote text, not numbers/Boolean</p></article><article><span>DELETE</span><p>DELETE FROM PLACEMENT WHERE Complete = TRUE;</p></article></section><ExamReveal><p>Use INSERT INTO TableName (fields) VALUES (matching values); for the supplied record. For deletion: DELETE FROM PLACEMENT WHERE Complete = TRUE; The WHERE condition restricts removal to completed rows.</p></ExamReveal><small className="da-source-line">Concise adaptations; original allocations include [4] and [2].</small></Slide> },
    { time: "5 min", focus: "Retrieve all DML operations and close Chapter 8.", prompt: "Students name the clause or command for each teacher-described action.", source: "Syllabus 8.3 complete synthesis; Coursebook Chapter 11 summary/exam questions printed pp.174-176.", content: <Slide number="14" eyebrow="MIXED RETRIEVAL · CHAPTER 8" sourceLabel="TEXTBOOK CH.11 · pp.174-176" syllabusLabel="SYLLABUS 8.1–8.3" title="Select, connect, calculate and change."><section className="da-flow"><span>FILTER + SORT<br />ROWS</span><i>→</i><span>GROUP +<br />AGGREGATE</span><i>→</i><span>INNER JOIN<br />TWO TABLES</span><i>→</i><span>INSERT · UPDATE<br />DELETE</span></section></Slide> },
    { time: "4 min", focus: "Close Chapter 8 with one complete natural-language query plan.", prompt: "Students state clauses only; no full SQL needed unless time remains.", source: "Syllabus 8.3 exit check; Coursebook Chapter 11 review.", content: <Slide number="15" eyebrow="EXIT TICKET · CHAPTER 8 COMPLETE" sourceLabel="TEXTBOOK CH.11 · pp.157-176" syllabusLabel="SYLLABUS 8.1–8.3" title="Design first. Query second. Protect every change."><section className="da-exit"><article><span>QUERY</span><p>Which clauses return active members alphabetically?</p></article><article><span>AGGREGATE</span><p>How do you count members per club?</p></article><article><span>MAINTAIN</span><p>Why must UPDATE/DELETE usually include WHERE?</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="40" slides={slides} homework={<HomeworkSheet lessonNumber="40" title="SQL Aggregation, Joins and Data Maintenance" marks={30} minutes={45} syllabusLabel="SYLLABUS 8.3" sourceLabel="TEXTBOOK CH.11 · pp.171-176 + PAPER 1" instructions="Annotate the required output, source tables, key link, filters, groups and order before writing SQL. For maintenance, verify field/value order and the scope of every WHERE condition." sections={homeworkSections} challenge={{ id: "l40-challenge", prompt: <p><Mark>CHALLENGE</Mark> Write one query returning each ClubName and the average Score for that club, using CLUB and RESULT linked by ClubID.</p>, answer: <pre>SELECT CLUB.ClubName, AVG(RESULT.Score) AS AverageScore{"\n"}FROM CLUB INNER JOIN RESULT{"\n"}ON CLUB.ClubID = RESULT.ClubID{"\n"}GROUP BY CLUB.ClubName;</pre> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 8.3, Coursebook Chapter 11 printed pp.171-176 (PDF pp.178-183) and published 2025 Paper 1 questions/mark schemes; malformed textbook SQL examples were corrected." sourceDetail="Core: SELECT/FROM/WHERE/ORDER BY/GROUP BY, SUM/COUNT/AVG, INNER JOIN across at most two tables, INSERT INTO, UPDATE and DELETE FROM. Authentic anchors: 9618/13 O/N 2025 Q5(c) [5], 9618/13 M/J 2025 Q6(b) [4] and 9618/11 O/N 2025 Q2(c)(i) [2]. Chapter 8 is now complete." />;
}
