/* Pseudocode examples intentionally retain their source notation. */
/* eslint-disable react/no-unescaped-entities */
"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Specify the algorithm", subtitle: "Defined steps, identifiers and data roles", marks: 10,
    questions: [
      { id: "l42-1", marks: 2, lines: 2, prompt: <><b>Define an algorithm and state one property of its steps.</b></>, answer: <p>An algorithm is a solution to a problem expressed as a sequence of defined steps. Its steps must be unambiguous/ordered/finite and executable for the stated inputs. Definition plus one valid property. <em>[2]</em></p> },
      { id: "l42-2", marks: 4, lines: 4, prompt: <><b>Explain four rules or good practices for Cambridge pseudocode identifiers.</b></>, answer: <p>Start with a letter; use only letters, digits and underscore; contain no spaces/accents; do not use a keyword; use descriptive mixed-case names; treat names as case-insensitive; single letters only where conventional/clear. Award any four. <em>[4]</em></p> },
      { id: "l42-3", marks: 4, lines: 5, prompt: <><b>Create an identifier table for a rectangle-area algorithm using Length, Width and Area.</b></>, answer: <p>Length — REAL — input length of rectangle; Width — REAL — input width; Area — REAL — calculated area Length × Width. Award suitable identifier, data type and role descriptions up to four marks. <em>[4]</em></p> },
    ],
  },
  {
    code: "B", title: "Move from IPO to representation", subtitle: "Structured English, flowchart and pseudocode", marks: 10,
    questions: [
      { id: "l42-4", marks: 4, lines: 4, prompt: <><b>For converting Celsius to Fahrenheit, state the input, process and output, including the formula.</b></>, answer: <p>Input: Celsius temperature. Process: calculate Fahrenheit ← Celsius × 9 / 5 + 32. Output: the Fahrenheit temperature. The fourth mark is for a correct, ordered relationship or appropriate identifiers/types. <em>[4]</em></p> },
      { id: "l42-5", marks: 3, lines: 3, prompt: <><b>Write structured English for the same conversion.</b></>, answer: <p>INPUT a Celsius temperature; CALCULATE Fahrenheit as Celsius multiplied by 9, divided by 5, then add 32; OUTPUT the Fahrenheit temperature. Accept clear ordered statements that are language-independent. <em>[3]</em></p> },
      { id: "l42-6", marks: 3, lines: 3, prompt: <><b>Give one strength of each: structured English, flowchart and pseudocode.</b></>, answer: <p>Structured English is quick and accessible for early discussion; a flowchart makes control flow/branches visually clear; pseudocode is compact, precise and close enough to programming structure to translate into code without tying it to one language. <em>[3]</em></p> },
    ],
  },
  {
    code: "C", title: "Published Paper 2 foundations", subtitle: "Identifier tables and basic constructs", marks: 10,
    questions: [
      { id: "l42-7", marks: 4, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE · PAPER 2</Mark> <b>Complete identifier-table entries for Category, DateSold, ItemCost and ItemInStock.</b><p>Adapted from 9618/21 M/J 2025 Q1(a). [4]</p></>, answer: <p>Category — STRING; DateSold — DATE; ItemCost (or Price) — REAL; ItemInStock — BOOLEAN. In the original question, each complete identifier/type row earns one mark. <em>[4]</em></p> },
      { id: "l42-8", marks: 5, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE · PAPER 2</Mark> <b>Classify five fragments by sequence, selection or iteration; note where assignment occurs.</b><p>Adapted from 9618/21 M/J 2025 Q1(b). [5]</p></>, answer: <p>A function result stored in a variable is an assignment statement within sequence; WHILE is iteration; REPEAT…UNTIL containing INPUT is iteration plus an input statement; IF containing an assignment is selection plus assignment; CASE is selection. Assignment is not a fourth basic construct. <em>[5]</em></p> },
      { id: "l42-9", marks: 1, lines: 2, prompt: <><b>Which Cambridge document is authoritative for pseudocode syntax in 2027–2029?</b></>, answer: <p>The Cambridge International 9618 Pseudocode Guide for Teachers for examination in 2027, 2028 and 2029. <em>[1]</em></p> },
    ],
  },
];

export default function Lesson42Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Contrast a vague instruction with a defined executable step.", prompt: "Ask why 'make it suitable' cannot be followed consistently by a computer.", source: "Coursebook 12.02-12.04 printed pp.180-184; syllabus 9.2.", content: <Slide number="01" eyebrow="CHAPTER 9 · ALGORITHM DESIGN" sourceLabel="TEXTBOOK CH.12 · pp.180-184" syllabusLabel="SYLLABUS 9.2" className="da-title"><section className="da-title-grid"><div className="da-title-copy"><span>LESSON 42 · 90 MINUTES · PAPER 2</span><h1>Name the data.<br /><em>Define the steps.</em></h1><p>Turn a problem into input, process and output; choose meaningful identifiers and document the solution in three equivalent representations.</p></div><div className="da-title-map"><div><b>?</b><span>DEFINE THE PROBLEM</span></div><div><b>IPO</b><span>INPUT · PROCESS · OUTPUT</span></div><div><b>ID</b><span>IDENTIFIER TABLE</span></div><div><b>3×</b><span>ENGLISH · FLOWCHART · PSEUDOCODE</span></div></div></section></Slide> },
    { time: "5 min", focus: "Map the first half of 9.2 and point to the current Pseudocode Guide.", prompt: "Make clear that flowchart conversion continues next lesson.", source: "Syllabus 9.2 pp.27-28; Coursebook 12.02-12.04 printed pp.180-184; Pseudocode Guide 2027-2029.", content: <Slide number="02" eyebrow="TEXTBOOK × SYLLABUS × PSEUDOCODE GUIDE" sourceLabel="TEXTBOOK §§12.02-12.04 · pp.180-184" syllabusLabel="SYLLABUS 9.2 · PAPER 2" title="A language-independent solution with named data and defined steps."><section className="da-grid four"><article className="da-card"><span>ALGORITHM</span><p>solution expressed as a sequence of defined steps</p></article><article className="da-card"><span>IDENTIFIERS</span><p>suitable names represented in an identifier table</p></article><article className="da-card"><span>IPO</span><p>pseudocode contains input, process and output</p></article><article className="da-card"><span>REPRESENT</span><p>structured English, flowchart or pseudocode; translate between them</p></article></section><p className="da-note">The current Cambridge Pseudocode Guide overrides older syntax shown in the 2019 textbook.</p></Slide> },
    { time: "6 min", focus: "Define algorithm quality through properties students can audit.", prompt: "Apply each property to a recipe-like example.", source: "Coursebook 12.02 printed pp.180-182; syllabus 9.2.", content: <Slide number="03" eyebrow="WHAT MAKES AN ALGORITHM?" sourceLabel="TEXTBOOK §12.02 · pp.180-182" syllabusLabel="SYLLABUS 9.2" title="A solution is more than a topic list."><section className="da-grid four"><article className="da-card"><span>DEFINED</span><p>each step has an unambiguous operation</p></article><article className="da-card"><span>ORDERED</span><p>steps occur in a valid control sequence</p></article><article className="da-card"><span>FINITE</span><p>for valid input, the process can terminate</p></article><article className="da-card"><span>CORRECT</span><p>the output satisfies the stated problem for all required cases</p></article></section><p className="da-warning">“Calculate the answer” is not a defined process step unless the calculation/rule is stated.</p></Slide> },
    { time: "6 min", focus: "Use IPO to expose missing data and calculations before representation.", prompt: "Students identify values, transformations and observable result.", source: "Coursebook 12.03 printed pp.182-184; syllabus 9.2 input/process/output.", content: <Slide number="04" eyebrow="INPUT · PROCESS · OUTPUT" sourceLabel="TEXTBOOK §12.03 · pp.182-184" syllabusLabel="SYLLABUS 9.2" title="Trace data through the solution."><section className="da-flow"><span>INPUT<br />Miles</span><i>→</i><span>PROCESS<br />Km ← Miles × 1.61</span><i>→</i><span>OUTPUT<br />Km</span><i>→</i><span>CHECK<br />units + plausibility</span></section><p className="da-note">IPO is an analysis scaffold, not a fourth control construct. The algorithm still uses sequence, selection and/or iteration.</p></Slide> },
    { time: "6 min", focus: "Apply current identifier rules and good naming practice.", prompt: "Repair 2total, total cost, IF, score% and x.", source: "Pseudocode Guide 2027-2029 p.7; syllabus 9.2 suitable identifier names.", content: <Slide number="05" eyebrow="IDENTIFIERS" sourceLabel="PSEUDOCODE GUIDE · p.7" syllabusLabel="SYLLABUS 9.2" title="Valid form + meaningful role."><section className="da-grid four"><article className="da-card"><span>START</span><p>begin with a letter, never a digit</p></article><article className="da-card"><span>CHARACTERS</span><p>letters, digits and underscore only; no spaces/accents</p></article><article className="da-card"><span>RESERVED</span><p>never use a pseudocode keyword such as IF</p></article><article className="da-card"><span>MEANING</span><p>use descriptive mixed case, e.g. TotalCost</p></article></section><p className="da-warning">Identifiers are treated as case-insensitive: CountDown and Countdown cannot safely name different data.</p></Slide> },
    { time: "6 min", focus: "Build an identifier table that explains both type and purpose.", prompt: "Students reject descriptions that merely repeat the identifier name.", source: "Coursebook 12.04 printed p.184; syllabus 9.2 identifier table; Pseudocode Guide data types p.7.", content: <Slide number="06" eyebrow="IDENTIFIER TABLE" sourceLabel="TEXTBOOK §12.04 · p.184" syllabusLabel="SYLLABUS 9.2" title="Name · data type · role in this problem."><table className="da-table"><thead><tr><th>IDENTIFIER</th><th>DATA TYPE</th><th>PURPOSE</th></tr></thead><tbody><tr><td><strong>Miles</strong></td><td>REAL</td><td>input distance measured in miles</td></tr><tr><td><strong>Km</strong></td><td>REAL</td><td>calculated distance in kilometres</td></tr><tr><td><strong>ConversionRate</strong></td><td>REAL / constant</td><td>number of kilometres per mile (1.61)</td></tr></tbody></table><p className="da-note">Use only information the algorithm actually needs; the table should agree with every name and type used later.</p></Slide> },
    { time: "6 min", focus: "Compare three representations by audience and precision.", prompt: "Ask which form best exposes a branch and which is fastest to edit.", source: "Coursebook 12.03 printed pp.182-184; syllabus 9.2 documentation/translation.", content: <Slide number="07" eyebrow="THREE REPRESENTATIONS" sourceLabel="TEXTBOOK §12.03 · pp.182-184" syllabusLabel="SYLLABUS 9.2" title="Same logic; different form."><section className="da-grid three"><article className="da-card"><span>STRUCTURED ENGLISH</span><h3>Readable outline</h3><p>Controlled natural-language steps; useful early, but must remain precise.</p></article><article className="da-card"><span>FLOWCHART</span><h3>Visual control flow</h3><p>Symbols and arrows make order, branches and loops visible.</p></article><article className="da-card"><span>PSEUDOCODE</span><h3>Programmable detail</h3><p>Language-independent notation with defined keywords and structure.</p></article></section></Slide> },
    { time: "7 min", focus: "Represent one algorithm consistently as IPO, structured English and current pseudocode.", prompt: "Students match each line across the three forms.", source: "Coursebook 12.03-12.04 miles-to-km example; Pseudocode Guide pp.7-9,15.", content: <Slide number="08" eyebrow="WORKED ALGORITHM · MILES TO KM" sourceLabel="TEXTBOOK §§12.03-12.04 · UPDATED" syllabusLabel="SYLLABUS 9.2" title="Representation changes; meaning does not."><section className="da-grid two"><article className="da-card"><span>STRUCTURED ENGLISH</span><p>Input miles.<br />Multiply miles by 1.61 and store the result.<br />Output the kilometre result.</p></article><article className="da-card"><span>CURRENT PSEUDOCODE</span><pre className="da-code">DECLARE Miles : REAL{"\n"}DECLARE Km : REAL{"\n"}INPUT Miles{"\n"}Km ← Miles * 1.61{"\n"}OUTPUT Km</pre></article></section><p className="da-note">The equivalent flowchart uses Start → Input parallelogram → Process rectangle → Output parallelogram → End.</p></Slide> },
    { time: "6 min", focus: "Correct obsolete textbook pseudocode forms before they become habits.", prompt: "Students rewrite each old line in current form.", source: "Coursebook 12.03 versus Pseudocode Guide 2027-2029 pp.5-9,15.", content: <Slide number="09" eyebrow="CURRENT PSEUDOCODE RULES" sourceLabel="PSEUDOCODE GUIDE · 2027-2029" syllabusLabel="SYLLABUS 9.2" title="Use the current guide, not legacy examples."><section className="da-compare"><div><span>LEGACY / WRONG</span><span>CURRENT FORM</span><span>RULE</span></div><div><b>INPUT "Enter miles:" Miles</b><span>OUTPUT "Enter miles" then INPUT Miles</span><span>INPUT takes an identifier only</span></div><div><b>miles = 0</b><span>Miles ← 0</span><span>← assigns; = compares</span></div><div><b>keywords in mixed case</b><span>DECLARE, INPUT, OUTPUT</span><span>keywords are uppercase</span></div><div><b>unclear x, y</b><span>Miles, Km</span><span>names should describe purpose</span></div></section></Slide> },
    { time: "6 min", focus: "Guide identifier-table construction from a sales requirement.", prompt: "Pairs decide names/types for category, date, cost and availability.", source: "Syllabus 9.2 identifier table; 9618/21 M/J 2025 Q1(a) context.", content: <Slide number="10" eyebrow="GUIDED CONSTRUCTION · ITEM SALE" sourceLabel="TEXTBOOK §12.04 + PAPER 2 CONTEXT" syllabusLabel="SYLLABUS 9.2" title="Choose type from meaning, then write a useful description."><table className="da-table"><thead><tr><th>REQUIRED FACT</th><th>IDENTIFIER</th><th>TYPE</th><th>ROLE DESCRIPTION</th></tr></thead><tbody><tr><td>item category</td><td><strong>Category</strong></td><td>STRING</td><td>category assigned to the item</td></tr><tr><td>sale date</td><td><strong>DateSold</strong></td><td>DATE</td><td>calendar date on which the item was sold</td></tr><tr><td>price</td><td><strong>ItemCost</strong></td><td>REAL</td><td>selling price, possibly fractional</td></tr><tr><td>availability</td><td><strong>ItemInStock</strong></td><td>BOOLEAN</td><td>TRUE when the item remains available</td></tr></tbody></table></Slide> },
    { time: "7 min", focus: "Teach identifier-table marking and construct classification.", prompt: "Emphasise that each complete name/type row earns together, and assignment is not a fourth construct.", source: "9618/21 M/J 2025 Q1(a)-Q1(b) published mark scheme; syllabus 9.2.", content: <Slide number="11" eyebrow="EXAM METHOD · ALIGN EVERY REPRESENTATION" sourceLabel="9618/21 M/J 2025 · Q1" syllabusLabel="SYLLABUS 9.2 — PAPER 2" title="Names, types and control structure must agree."><section className="da-grid three"><article className="da-card"><span>IDENTIFIER ROW</span><p>correct name and appropriate type; match the scenario</p></article><article className="da-card"><span>THREE CONSTRUCTS</span><p>sequence, selection and iteration only</p></article><article className="da-card"><span>STATEMENTS INSIDE</span><p>assignment, input, output or calls occur within those constructs</p></article></section><p className="da-warning">If a fragment contains IF plus an assignment, identify selection and the assignment statement when the question asks for both.</p></Slide> },
    { time: "8 min", focus: "Attempt the published identifier-table entries.", prompt: "Students complete name/type pairs in two minutes, then justify each type.", source: "Adapted from 9618/21 M/J 2025 Q1(a), checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/21 M/J 2025 · Q1(a)" syllabusLabel="SYLLABUS 9.2 — PAPER 2" title="Complete four identifier-table rows." className="slide--da-paper"><section className="da-paper-grid four"><article><span>CATEGORY</span><p>text label</p></article><article><span>DATE SOLD</span><p>calendar value</p></article><article><span>ITEM COST</span><p>may contain a fraction</p></article><article><span>IN STOCK</span><p>two logical states</p></article></section><ExamReveal><p>Category : STRING; DateSold : DATE; ItemCost/Price : REAL; ItemInStock : BOOLEAN. In the original item, each correct complete row earns one mark.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [4].</small></Slide> },
    { time: "8 min", focus: "Classify five fragments using an authentic mark-scheme distinction.", prompt: "Students write S, SEL or ITER and note assignment where present.", source: "Adapted from 9618/21 M/J 2025 Q1(b), checked against published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 5 MARKS" sourceLabel="9618/21 M/J 2025 · Q1(b)" syllabusLabel="SYLLABUS 9.2 — PAPER 2" title="Which construct or statement does each fragment use?" className="slide--da-paper"><section className="da-paper-grid three"><article><span>WHILE / REPEAT</span><p>iteration; INPUT may occur inside</p></article><article><span>IF / CASE</span><p>selection; assignment may occur inside</p></article><article><span>STORE RESULT</span><p>assignment statement in sequence</p></article></section><ExamReveal><p>A stored function result is assignment within sequence. WHILE is iteration. REPEAT…UNTIL containing INPUT combines iteration with input. IF containing assignment combines selection with assignment. CASE is selection. The syllabus has three basic constructs; assignment is a statement, not a fourth.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [5].</small></Slide> },
    { time: "5 min", focus: "Retrieve the design path from problem to documented algorithm.", prompt: "Students give one artefact at each stage.", source: "Syllabus 9.2 synthesis; Coursebook 12.02-12.04; current Pseudocode Guide.", content: <Slide number="14" eyebrow="MIXED RETRIEVAL" sourceLabel="TEXTBOOK §§12.02-12.04 · REVIEW" syllabusLabel="SYLLABUS 9.2" title="Problem → data → IPO → representation."><section className="da-flow"><span>DEFINED<br />PROBLEM</span><i>→</i><span>IDENTIFIER<br />TABLE</span><i>→</i><span>INPUT · PROCESS<br />OUTPUT</span><i>→</i><span>ENGLISH / FLOWCHART<br />PSEUDOCODE</span></section></Slide> },
    { time: "4 min", focus: "Close with one naming, IPO and representation check.", prompt: "Collect three short responses; use errors to start Lesson 43.", source: "Syllabus 9.2 checkpoint; Coursebook Chapter 12 sequence.", content: <Slide number="15" eyebrow="EXIT TICKET · NEXT: CONTROL FLOW" sourceLabel="TEXTBOOK CH.12 · pp.180-184" syllabusLabel="SYLLABUS 9.2" title="Three foundations before branching and looping."><section className="da-exit"><article><span>IDENTIFIER</span><p>Repair 2 total cost into one valid meaningful name.</p></article><article><span>IPO</span><p>What process converts hours to minutes?</p></article><article><span>REPRESENT</span><p>Why must three forms preserve the same logic?</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="42" slides={slides} homework={<HomeworkSheet lessonNumber="42" title="Algorithm Design, Identifiers and IPO" marks={30} minutes={45} syllabusLabel="SYLLABUS 9.2 · PAPER 2" sourceLabel="TEXTBOOK CH.12 · pp.180-184 + PSEUDOCODE GUIDE + PAPER 2" instructions="Define the problem and data before writing steps. Keep identifier names/types consistent across the table, structured English, flowchart and pseudocode; use current 2027-2029 pseudocode conventions." sections={homeworkSections} challenge={{ id: "l42-challenge", prompt: <p><Mark>CHALLENGE</Mark> Produce an IPO table and identifier table for calculating the mean of three test scores.</p>, answer: <p>Inputs: Score1, Score2, Score3 (REAL/INTEGER according to stated domain). Process: Total ← Score1 + Score2 + Score3; Mean ← Total / 3. Output: Mean. Identifier table should include descriptive names, appropriate types and clear roles; Mean should be REAL even if scores are INTEGER.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 9.2, Coursebook Chapter 12 printed pp.180-184 (PDF pp.187-191), the official 2027-2029 Pseudocode Guide and published Paper 2 question/mark scheme." sourceDetail="Core: algorithm definition, suitable identifiers and identifier tables, input-process-output, structured English/flowchart/pseudocode as equivalent representations, and the three basic constructs at recognition level. Authentic Paper 2 anchor: 9618/21 M/J 2025 Q1(a)-Q1(b) [9]. Control-flow construction continues in Lesson 43." />;
}
