"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { LogicBlocks, LogicTable } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Boolean laws", subtitle: "Name the law and show the change", marks: 10,
    questions: [
      { id: "a2-14-1", marks: 3, lines: 5, prompt: <><b>Simplify:</b> <code>A + 0</code>, <code>A · 1</code> and <code>A + A</code>. Name each law.</>, answer: <p><code>A + 0 = A</code>, identity law <em>[1]</em>; <code>A · 1 = A</code>, identity law <em>[1]</em>; <code>A + A = A</code>, idempotent law <em>[1]</em>.</p> },
      { id: "a2-14-2", marks: 3, lines: 5, prompt: <><b>Simplify:</b> <code>A + A·B</code>. Show and name the relevant law.</>, answer: <p><code>A + A·B = A</code> <em>[1]</em> by the absorption law <em>[1]</em>. It means that when A is already true, the extra term <code>A·B</code> cannot change the output <em>[1]</em>.</p> },
      { id: "a2-14-3", marks: 4, lines: 7, prompt: <><b>Simplify:</b> <code>A + ¬A·B</code>. Show each step.</>, answer: <p><code>A + ¬A·B = (A + ¬A)(A + B)</code> by distributive law <em>[1]</em>; <code>= 1·(A + B)</code> by complement law <em>[1]</em>; <code>= A + B</code> by identity law <em>[1]</em>. Correct result <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "De Morgan and SOP", subtitle: "Move a NOT through the brackets correctly", marks: 10,
    questions: [
      { id: "a2-14-4", marks: 3, lines: 5, prompt: <><b>(a) Apply De Morgan&apos;s law:</b> <code>¬(A + B + C)</code>. <b>(b) State the two transformation rules used.</b></>, answer: <p><code>¬(A + B + C) = ¬A · ¬B · ¬C</code> <em>[1]</em>. The operator changes from OR to AND <em>[1]</em> and every variable is complemented <em>[1]</em>.</p> },
      { id: "a2-14-5", marks: 3, lines: 5, prompt: <><b>(a) Apply De Morgan&apos;s law:</b> <code>¬(A · B · C)</code>. <b>(b) Describe the equivalent gate arrangement.</b></>, answer: <p><code>¬(A · B · C) = ¬A + ¬B + ¬C</code> <em>[1]</em>. Invert A, B and C separately <em>[1]</em>, then feed them into a three-input OR gate <em>[1]</em>.</p> },
      { id: "a2-14-6", marks: 4, lines: 7, prompt: <><b>Write the canonical SOP expression</b> when F = 1 for inputs 010, 101 and 111.</>, answer: <p><code>¬A·B·¬C</code> for 010 <em>[1]</em>; <code>A·¬B·C</code> for 101 <em>[1]</em>; <code>A·B·C</code> for 111 <em>[1]</em>; therefore <code>F = ¬A·B·¬C + A·¬B·C + A·B·C</code> <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Circuit algebra", subtitle: "Translate, simplify, verify", marks: 10,
    questions: [
      { id: "a2-14-7", marks: 3, lines: 5, prompt: <><b>Write an expression</b> for: A and B enter an AND gate; its output is ORed with NOT C.</>, answer: <p>The AND output is <code>A·B</code> <em>[1]</em>; the inverted input is <code>¬C</code> <em>[1]</em>; final output <code>F = A·B + ¬C</code> <em>[1]</em>.</p> },
      { id: "a2-14-8", marks: 3, lines: 5, prompt: <><b>Simplify:</b> <code>(A + B)(A + ¬B)</code>.</>, answer: <p><code>(A + B)(A + ¬B) = A + B·¬B</code> <em>[1]</em> by the distributive identity; <code>B·¬B = 0</code> <em>[1]</em>; so <code>F = A</code> <em>[1]</em>.</p> },
      { id: "a2-14-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE · INSPIRED EXTENSION</span><p><b>Use Boolean algebra to simplify:</b> <code>¬(A·B) · A</code></p><p>Inspired by the De Morgan/algebra task in 9618/32 O/N 2022 Q8(c). [4]</p></>, answer: <p><code>¬(A·B) = ¬A + ¬B</code> by De Morgan <em>[1]</em>; multiply by A: <code>A·¬A + A·¬B</code> <em>[1]</em>; <code>A·¬A = 0</code> by inverse/complement law <em>[1]</em>; result <code>A·¬B</code> <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson14Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Treat Boolean algebra as a language for circuits.", prompt: "Why does 1 + 1 equal 1 in OR logic?", source: "2027–2029 syllabus 15.2; coursebook Chapter 19 printed pp.356–359.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch19" syllabusLabel="SYLLABUS 15.2" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 14 · 90 MINUTES</span><h1>Write the circuit.<br /><em>Simplify the logic.</em></h1><p>Boolean notation · laws · De Morgan · SOP · circuit expressions</p></div><div className="a2-at-hero" role="img" aria-label="Boolean expression simplified through logic stages"><strong>F = A + A·B</strong><span>IDENTITY</span><span>DE MORGAN</span><span>ABSORPTION</span><span>F = A</span></div></section></Slide> },
    { time: "5 min", focus: "Map each skill to syllabus 15.2.", prompt: "Students identify where they must state, apply, simplify and verify.", source: "Syllabus p.34; coursebook pp.356–359.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.34" syllabusLabel="15.2 · BOOLEAN ALGEBRA" title="Every algebra step should preserve the circuit's truth table." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "READ", title: "Notation", body: "AND · OR + NOT ¬" }, { eyebrow: "APPLY", title: "Named laws", body: "Rewrite without changing output." }, { eyebrow: "BUILD", title: "SOP", body: "One minterm for each output 1." }, { eyebrow: "CHECK", title: "Truth table", body: "Equivalent expressions match every row." }]} /></Slide> },
    { time: "5 min", focus: "Translate between gate language and algebra.", prompt: "Read each operator aloud before calculating.", source: "Coursebook §19.03 pp.356–357.", content: <Slide number="03" eyebrow="NOTATION" sourceLabel="TEXTBOOK pp.356–357" syllabusLabel="15.2 · USE" title="AND binds terms; OR joins alternatives; NOT complements a value." className="a2-slide a2-at-slide"><LogicBlocks blocks={[{ label: "AND", expression: "A · B", detail: "1 only when both are 1" }, { label: "OR", expression: "A + B", detail: "1 when either or both are 1" }, { label: "NOT", expression: "¬A = A̅ = NOT A", detail: "papers may use ¬ or an overbar" }]} /></Slide> },
    { time: "6 min", focus: "Use identity and null laws.", prompt: "Which constants leave a value unchanged, and which dominate it?", source: "Coursebook p.356 Boolean laws table.", content: <Slide number="04" eyebrow="IDENTITY + NULL" sourceLabel="TEXTBOOK p.356" syllabusLabel="15.2 · LAWS" title="Constants behave differently under AND and OR." className="a2-slide a2-at-slide"><CompareTable headers={["Law", "AND form", "OR form", "Result"]} rows={[["identity", "A·1", "A+0", "A"], ["null / domination", "A·0", "A+1", "0 / 1"]]} /></Slide> },
    { time: "6 min", focus: "Use idempotent, inverse/complement and double-NOT laws.", prompt: "Explain each law with one truth-value argument.", source: "Coursebook p.356.", content: <Slide number="05" eyebrow="CORE LAWS" sourceLabel="TEXTBOOK p.356" syllabusLabel="15.2 · LAWS" title="Repeated values collapse; complements either exclude or cover every case." className="a2-slide a2-at-slide"><CompareTable headers={["Law", "Forms", "Meaning"]} rows={[["idempotent", "A·A=A; A+A=A", "repetition adds nothing"], ["inverse / complement", "A·¬A=0; A+¬A=1", "opposites cannot both / one must be true"], ["double complement", "¬¬A=A", "two inversions cancel"]]} /></Slide> },
    { time: "6 min", focus: "Reorder and regroup safely.", prompt: "Which laws change arrangement but not variables?", source: "Coursebook pp.356–357.", content: <Slide number="06" eyebrow="ARRANGEMENT LAWS" sourceLabel="TEXTBOOK pp.356–357" syllabusLabel="15.2 · LAWS" title="Commutative and associative laws expose useful pairs." className="a2-slide a2-at-slide"><CompareTable headers={["Law", "AND", "OR"]} rows={[["commutative", "A·B = B·A", "A+B = B+A"], ["associative", "(A·B)·C = A·(B·C)", "(A+B)+C = A+(B+C)"]]} /></Slide> },
    { time: "6 min", focus: "Distribute and absorb terms.", prompt: "How can expanding an expression make it shorter later?", source: "Coursebook pp.356–357.", content: <Slide number="07" eyebrow="TRANSFORM" sourceLabel="TEXTBOOK pp.356–357" syllabusLabel="15.2 · SIMPLIFY" title="Distributive law reveals complements; absorption removes redundant cases." className="a2-slide a2-at-slide"><LogicBlocks blocks={[{ label: "Distribute", expression: "A(B+C)=AB+AC", detail: "expand or factor" }, { label: "Find redundancy", expression: "A + AB", detail: "A already covers AB" }, { label: "Absorb", expression: "A+AB=A", detail: "remove extra term" }]} /></Slide> },
    { time: "6 min", focus: "Apply both De Morgan laws visually.", prompt: "What two changes always occur when NOT crosses brackets?", source: "Coursebook §19.03 p.357; syllabus explicitly includes De Morgan.", content: <Slide number="08" eyebrow="DE MORGAN" sourceLabel="TEXTBOOK p.357" syllabusLabel="15.2 · REQUIRED" title="Complement each input and swap AND ↔ OR." className="a2-slide a2-at-slide"><CompareTable headers={["Original", "Equivalent", "Gate interpretation"]} rows={[["¬(A·B)", "¬A + ¬B", "NAND = OR with inverted inputs"], ["¬(A+B)", "¬A · ¬B", "NOR = AND with inverted inputs"], ["¬(A·B·C)", "¬A+¬B+¬C", "the rule extends beyond two inputs"]]} /></Slide> },
    { time: "6 min", focus: "Translate a circuit stage by stage.", prompt: "Name each intermediate output before writing the final expression.", source: "Coursebook §19.04 pp.358–359.", content: <Slide number="09" eyebrow="CIRCUIT → EXPRESSION" sourceLabel="TEXTBOOK pp.358–359" syllabusLabel="15.2 · PRODUCE" title="Intermediate labels prevent lost brackets and missing complements." className="a2-slide a2-at-slide"><LogicBlocks blocks={[{ label: "X = A·B", expression: "AND(A,B)" }, { label: "Y = ¬C", expression: "NOT(C)" }, { label: "F = X+Y", expression: "A·B + ¬C" }]} /></Slide> },
    { time: "6 min", focus: "Create canonical sum of products from output-one rows.", prompt: "Why does a zero input appear complemented inside its minterm?", source: "Coursebook §19.04 p.358.", content: <Slide number="10" eyebrow="TRUTH TABLE → SOP" sourceLabel="TEXTBOOK p.358" syllabusLabel="15.2 · PRODUCE" title="Each output-1 row becomes one AND term; OR joins the terms." className="a2-slide a2-at-slide"><LogicTable headers={["A", "B", "C", "F", "Minterm when F=1"]} rows={[[0,0,0,0,"—"], [0,1,0,1,"¬A·B·¬C"], [1,0,1,1,"A·¬B·C"], [1,1,1,1,"A·B·C"]]} /></Slide> },
    { time: "7 min", focus: "Simplify an expression with named justification.", prompt: "Students annotate the law above every equals sign.", source: "Coursebook pp.358–359; Paper 3 Boolean mark schemes.", content: <Slide number="11" eyebrow="WORKED SIMPLIFICATION" sourceLabel="TEXTBOOK pp.358–359" syllabusLabel="15.2 · SIMPLIFY" title="A correct answer needs a traceable algebra route." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "START", title: "A + ¬A·B" }, { eyebrow: "DISTRIBUTE", title: "(A+¬A)(A+B)" }, { eyebrow: "COMPLEMENT", title: "1·(A+B)" }, { eyebrow: "IDENTITY", title: "A+B" }]} /></Slide> },
    { time: "7 min", focus: "Verify equivalence without circular reasoning.", prompt: "Compare original and simplified output for all four A,B rows.", source: "Syllabus 15.2; verification method from truth-table work.", content: <Slide number="12" eyebrow="VERIFY" sourceLabel="SYLLABUS 15.2" syllabusLabel="15.2 · CHECK" title="Equivalent expressions produce the same output for every input row." className="a2-slide a2-at-slide"><LogicTable headers={["A", "B", "A+¬A·B", "A+B", "Match?"]} rows={[[0,0,0,0,"✓"], [0,1,1,1,"✓"], [1,0,1,1,"✓"], [1,1,1,1,"✓"]]} /></Slide> },
    { time: "7 min", focus: "Repair common notation and law errors.", prompt: "Students correct all four statements aloud.", source: "Recurring Paper 3 Boolean errors.", content: <Slide number="13" eyebrow="MISCONCEPTION REPAIR" sourceLabel="PAPER 3 EXAM LANGUAGE" syllabusLabel="15.2 · PRECISION" title="A missing bar or bracket changes the whole circuit." className="a2-slide a2-at-slide"><CompareTable headers={["Unsafe move", "Correct move"]} rows={[["¬(A+B)=¬A+¬B", "¬(A+B)=¬A·¬B"], ["A+A=2A", "A+A=A in Boolean algebra"], ["010 → A·B·C", "010 → ¬A·B·¬C"], ["erase a term by intuition", "cite absorption/complement/identity"]]} /></Slide> },
    { time: "8 min", focus: "Apply De Morgan and simplification mark points.", prompt: "Write one legal transformation per line.", source: "Exam-style extension inspired by Cambridge 9618/32 O/N 2022 Q8(c).", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE · INSPIRED" sourceLabel="9618/32 O/N 2022 · Q8(c)" syllabusLabel="15.2 · 6 MARKS" title="Simplify without changing the truth table." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="INSPIRED BY 9618/32 O/N 2022 · Q8(c) · EXTENDED" marks={6} prompt={<p>Use Boolean algebra to simplify <code>¬(A·B)·A</code>, naming the laws used. [6]</p>} answer={<ul><li>De Morgan: <code>¬(A·B)=¬A+¬B</code>. [2]</li><li>Distribute A: <code>A·¬A + A·¬B</code>. [1]</li><li>Inverse/complement law: <code>A·¬A=0</code>. [1]</li><li>Identity law: <code>0 + A·¬B = A·¬B</code>. [2]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve notation, laws, De Morgan and SOP.", prompt: "Students simplify one expression and verify one row before leaving.", source: "Syllabus 15.2 synthesis; coursebook pp.356–359.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch19 · SYLLABUS p.34" syllabusLabel="15.2 · CHECKPOINT" title="Translate carefully. Transform legally. Verify completely." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>NOTATION</span><p>AND · OR + NOT ¬.</p></article><article><span>LAWS</span><p>Identity to absorption.</p></article><article><span>DE MORGAN</span><p>Complement all; swap operator.</p></article><article><span>SOP</span><p>One minterm per output 1.</p></article></section><div className="homework-callout"><b>HOMEWORK 14</b><span>30 marks · Boolean laws, De Morgan and SOP</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="14" title="Boolean algebra and De Morgan's laws" syllabusLabel="SYLLABUS 15.2" sourceLabel="TEXTBOOK Ch19 · pp.356–359" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 15.2 p.34 · endorsed coursebook Chapter 19 printed pp.356–359 · verified 2022 Paper 3 question and mark scheme" sourceDetail="The lesson uses Boolean—not arithmetic—rules, names each algebraic transformation, and links canonical SOP directly to output-one truth-table rows." />;
}
