"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip, WorkedBoard } from "../../_components/a2-theory-lesson";
import { PageFrameMap } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Paging and address translation", subtitle: "Keep pages logical and frames physical", marks: 10,
    questions: [
      { id: "a2-19-1", marks: 3, lines: 5, prompt: <><b>Define a page, a frame and a page table.</b></>, answer: <p>A page is a fixed-size block of a process&apos;s logical address space <em>[1]</em>. A frame is an equal-sized block of physical RAM <em>[1]</em>. A page table maps page numbers to frame numbers/presence information <em>[1]</em>.</p> },
      { id: "a2-19-2", marks: 3, lines: 6, prompt: <><b>Explain how the logical address (page 3, offset 120)</b> is translated when page table entry 3 contains frame 8.</>, answer: <p>The page number 3 indexes the page table <em>[1]</em>; the entry supplies physical frame 8 <em>[1]</em>; the offset remains 120, giving physical location frame 8, offset 120 <em>[1]</em>.</p> },
      { id: "a2-19-3", marks: 4, lines: 7, prompt: <><b>Explain what happens after a page fault</b> when no free frame exists.</>, answer: <p>The OS detects that the required page is not resident in RAM <em>[1]</em>; selects a victim page/frame using a replacement method <em>[1]</em>; writes the victim back if modified and loads the required page from secondary storage <em>[1]</em>; updates the page table and restarts/resumes the instruction <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Virtual memory and replacement", subtitle: "Explain the mechanism and its cost", marks: 10,
    questions: [
      { id: "a2-19-4", marks: 3, lines: 6, prompt: <><b>Explain how virtual memory allows a process to use more memory than its current RAM allocation.</b></>, answer: <p>Only currently needed pages are kept in RAM <em>[1]</em>; other pages are stored on secondary storage/backing store <em>[1]</em>; the OS swaps/pages data in and out on demand, presenting a larger logical address space <em>[1]</em>.</p> },
      { id: "a2-19-5", marks: 3, lines: 5, prompt: <><b>Distinguish FIFO and LRU page replacement.</b></>, answer: <p>FIFO replaces the page that entered RAM earliest/has been resident longest <em>[1]</em>. LRU replaces the page that has not been referenced for the longest time <em>[1]</em>; therefore the two algorithms use different histories and can choose different victims <em>[1]</em>.</p> },
      { id: "a2-19-6", marks: 4, lines: 7, prompt: <><b>Explain disk thrashing and its effect on performance.</b></>, answer: <p>Too few frames/too many active working sets cause frequent page faults <em>[1]</em>; pages are repeatedly transferred between RAM and secondary storage <em>[1]</em>; disk access is much slower than RAM <em>[1]</em>, so the system spends more time swapping than executing useful instructions and performance collapses <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Segmentation and comparison", subtitle: "Use logical units, variable sizes and tables", marks: 10,
    questions: [
      { id: "a2-19-7", marks: 3, lines: 6, prompt: <><b>Describe segmentation for memory management.</b></>, answer: <p>A program is divided into variable-sized logical units such as code, data or procedures <em>[1]</em>. A logical address contains a segment identifier and an offset <em>[1]</em>; a segment table maps each segment to its base/limit in physical memory <em>[1]</em>.</p> },
      { id: "a2-19-8", marks: 3, lines: 6, prompt: <><b>Give three differences between paging and segmentation.</b></>, answer: <p>Pages are fixed size whereas segments are variable size <em>[1]</em>; pages are implementation blocks whereas segments match logical program units <em>[1]</em>; paging can cause internal fragmentation whereas segmentation can cause external fragmentation <em>[1]</em>.</p> },
      { id: "a2-19-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Describe segmentation and explain how disk thrashing can occur.</b></p><p>Adapted from 9618/31 O/N 2024 Q8. [4 adapted marks]</p></>, answer: <p>Segmentation creates variable-sized, named/logical program sections <em>[1]</em>, mapped through a segment table using segment identifier plus offset <em>[1]</em>. Thrashing occurs when repeated page faults cause excessive transfers between RAM and secondary storage <em>[1]</em>, leaving little time for useful processing and greatly reducing performance <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson19Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Introduce memory management as a mapping problem.", prompt: "How can one process see a large continuous space when RAM is small and fragmented?", source: "2027–2029 syllabus 16.1; coursebook Chapter 20 printed pp.372–375.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch20" syllabusLabel="SYLLABUS 16.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 19 · 90 MINUTES</span><h1>Logical space.<br /><em>Physical limits.</em></h1><p>paging · virtual memory · segmentation · replacement · thrashing</p></div><div className="a2-at-hero" role="img" aria-label="Logical pages map onto physical memory frames"><strong>MEMORY MANAGER</strong><span>PAGE</span><span>FRAME</span><span>TABLE</span><span>DISK</span></div></section></Slide> },
    { time: "5 min", focus: "Map every current memory-management objective.", prompt: "Which requirement asks for a direct comparison?", source: "Official 2027–2029 syllabus p.35.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.35" syllabusLabel="16.1 · REQUIRED" title="Know the structures, trace a miss, compare methods and explain failure." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "FIXED", title: "Paging", body: "Pages map to equal-sized frames." }, { eyebrow: "LOGICAL", title: "Segmentation", body: "Variable-sized program units." }, { eyebrow: "EXTEND", title: "Virtual memory", body: "Disk supports a larger logical space." }, { eyebrow: "COST", title: "Thrashing", body: "Excessive swapping destroys performance." }]} /></Slide> },
    { time: "5 min", focus: "Define paging without confusing a page with a frame.", prompt: "Which object belongs to the process, and which belongs to RAM?", source: "Coursebook §20.04 pp.372–373.", content: <Slide number="03" eyebrow="PAGES AND FRAMES" sourceLabel="TEXTBOOK pp.372–373" syllabusLabel="16.1 · PAGING" title="Fixed-size logical pages fit fixed-size physical frames." className="a2-slide a2-at-slide"><CompareTable headers={["Page", "Frame"]} rows={[["block of logical/process address space", "block of physical main memory"], ["identified by page number", "identified by frame number"], ["may currently be on disk", "exists in RAM"], ["fixed size", "same fixed size as a page"]]} /></Slide> },
    { time: "6 min", focus: "Show non-contiguous allocation through a page table.", prompt: "Where is P1, and what will accessing it cause?", source: "Coursebook §20.04 pp.372–373.", content: <Slide number="04" eyebrow="PAGE TABLE MAP" sourceLabel="TEXTBOOK pp.372–373" syllabusLabel="16.1 · PAGING" title="Consecutive logical pages do not need consecutive frames." className="a2-slide a2-at-slide"><PageFrameMap /></Slide> },
    { time: "6 min", focus: "Translate a logical address into a physical location.", prompt: "Which part changes and which part is preserved?", source: "Coursebook §20.04 pp.372–373.", content: <Slide number="05" eyebrow="ADDRESS TRANSLATION" sourceLabel="TEXTBOOK pp.372–373" syllabusLabel="16.1 · PAGING" title="Translate the page number; keep the offset." className="a2-slide a2-at-slide"><WorkedBoard label="Logical address = page 3, offset 120"><p>Use page number <code>3</code> to index the page table. If <code>P3 → frame 8</code>, the physical location is <code>frame 8, offset 120</code>.</p></WorkedBoard></Slide> },
    { time: "6 min", focus: "Explain virtual memory as an illusion backed by disk.", prompt: "Does virtual memory increase physical RAM?", source: "Coursebook §20.04 pp.373–374; 9618/31 O/N 2022 Q8.", content: <Slide number="06" eyebrow="VIRTUAL MEMORY" sourceLabel="9618/31 O/N 2022 · Q8" syllabusLabel="16.1 · VIRTUAL MEMORY" title="Only the current working pages need to occupy RAM." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "LOGICAL SPACE", title: "Process addresses many pages" }, { eyebrow: "RAM", title: "Keeps active pages" }, { eyebrow: "BACKING STORE", title: "Holds absent pages" }, { eyebrow: "OS", title: "Moves pages on demand" }]} /></Slide> },
    { time: "6 min", focus: "Trace the complete page-fault path.", prompt: "Why is a page fault not the same as a program error?", source: "Coursebook pp.373–374.", content: <Slide number="07" eyebrow="PAGE FAULT" sourceLabel="TEXTBOOK pp.373–374" syllabusLabel="16.1 · PAGE REPLACEMENT" title="An absent page triggers operating-system recovery." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "REFERENCE", title: "CPU requests absent page" }, { eyebrow: "TRAP", title: "OS handles page fault" }, { eyebrow: "LOAD", title: "Page moves disk → frame" }, { eyebrow: "RESUME", title: "Table updated; instruction retried" }]} /></Slide> },
    { time: "6 min", focus: "Explain why a victim page may be required.", prompt: "What extra action is needed if the chosen page was modified?", source: "Syllabus asks how pages can be replaced; coursebook pp.373–374.", content: <Slide number="08" eyebrow="MAKE SPACE" sourceLabel="TEXTBOOK pp.373–374" syllabusLabel="16.1 · REPLACE PAGES" title="With no free frame, the OS evicts a resident page." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "SELECT", title: "Victim page", body: "Use a replacement policy." }, { eyebrow: "WRITE BACK", title: "If modified", body: "Preserve its changed data on disk." }, { eyebrow: "UPDATE", title: "Page table", body: "Mark victim absent; new page present." }]} /></Slide> },
    { time: "6 min", focus: "Compare two concrete page-replacement approaches.", prompt: "Oldest resident and least recently accessed: are they always the same page?", source: "Coursebook §20.04 page-replacement discussion.", content: <Slide number="09" eyebrow="REPLACEMENT EXAMPLES" sourceLabel="TEXTBOOK pp.373–374" syllabusLabel="16.1 · HOW PAGES ARE REPLACED" title="FIFO remembers arrival; LRU remembers access." className="a2-slide a2-at-slide"><CompareTable headers={["Method", "Victim chosen", "Strength", "Cost / risk"]} rows={[["FIFO", "page loaded earliest", "simple queue", "may remove a frequently used page"], ["LRU", "page unused for longest", "uses recent locality", "must track/approximate references"]]} /></Slide> },
    { time: "6 min", focus: "Define segmentation through program meaning.", prompt: "Why might code, data and procedures need different sizes?", source: "Coursebook §20.04 pp.374–375; 9618/31 O/N 2024 Q8.", content: <Slide number="10" eyebrow="SEGMENTATION" sourceLabel="9618/31 O/N 2024 · Q8" syllabusLabel="16.1 · SEGMENTATION" title="A segment is a variable-sized logical section of a program." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "SEGMENT 0", title: "Code", body: "Executable instructions." }, { eyebrow: "SEGMENT 1", title: "Data", body: "Global/static values." }, { eyebrow: "SEGMENT 2", title: "Procedure", body: "A meaningful module with its own length." }]} /></Slide> },
    { time: "7 min", focus: "Translate a segmented logical address safely.", prompt: "What does the offset mean, and what does the limit protect?", source: "Coursebook pp.374–375; 2024 Paper 31 mark scheme interpreted consistently.", content: <Slide number="11" eyebrow="SEGMENT TABLE" sourceLabel="TEXTBOOK pp.374–375" syllabusLabel="16.1 · SEGMENTATION" title="Segment identifier selects base and limit; offset selects a location inside it." className="a2-slide a2-at-slide"><WorkedBoard label="Logical address = segment 2, offset 40"><p>Read segment 2&apos;s <strong>base address</strong> and <strong>limit/length</strong>. Check <code>40 &lt; limit</code>; then physical address = <code>base + 40</code>.</p></WorkedBoard></Slide> },
    { time: "7 min", focus: "Compare paging and segmentation on fixed versus logical organisation.", prompt: "Which method is more exposed to external fragmentation?", source: "Syllabus p.35; coursebook pp.372–375.", content: <Slide number="12" eyebrow="PAGING VS SEGMENTATION" sourceLabel="SYLLABUS p.35" syllabusLabel="16.1 · DIFFERENCE" title="One divides by equal size; the other divides by program meaning." className="a2-slide a2-at-slide"><CompareTable headers={["Paging", "Segmentation"]} rows={[["fixed-size pages", "variable-size segments"], ["implementation/memory blocks", "logical units: code, data, procedures"], ["page number + offset", "segment identifier + offset"], ["internal fragmentation possible", "external fragmentation possible"], ["page table", "segment table with base + limit"]]} /></Slide> },
    { time: "7 min", focus: "Explain disk thrashing as a feedback loop.", prompt: "Why does adding more active processes sometimes reduce throughput?", source: "Coursebook §20.04 pp.373–374; 9618/31 O/N 2024 Q8(b).", content: <Slide number="13" eyebrow="DISK THRASHING" sourceLabel="9618/31 O/N 2024 · Q8(b)" syllabusLabel="16.1 · THRASHING" title="Too few resident working pages cause page fault after page fault." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "PRESSURE", title: "Too few frames" }, { eyebrow: "FAULT", title: "Needed page absent" }, { eyebrow: "SWAP", title: "Slow disk transfer" }, { eyebrow: "COLLAPSE", title: "More swapping than execution" }]} /></Slide> },
    { time: "8 min", focus: "Answer segmentation and thrashing in an authentic exam format.", prompt: "Keep segment length separate from offset.", source: "Adapted from Cambridge 9618/31 O/N 2024 Q8.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/31 O/N 2024 · Q8" syllabusLabel="16.1 · 7 MARKS" title="Describe the structure, then explain the performance failure." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/31 O/N 2024 · Q8 · ADAPTED" marks={7} prompt={<p>Describe segmentation for memory management. Then explain what disk thrashing means and why it reduces performance. [7]</p>} answer={<ul><li>Program divided into named/logical, variable-sized segments such as code or data. [2]</li><li>Logical address uses segment identifier plus offset; segment table maps to a physical base and checks a limit. [2]</li><li>Frequent page faults cause repeated RAM↔disk transfers. [2]</li><li>Disk is slow, so little useful execution occurs. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve every memory-management distinction.", prompt: "Students complete: page is to frame as segment is to…", source: "Syllabus 16.1 synthesis; coursebook Chapter 20 pp.372–375.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch20 · SYLLABUS p.35" syllabusLabel="16.1 · CHECKPOINT" title="Map, load, replace—and recognise when swapping takes over." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>PAGE</span><p>Fixed logical block.</p></article><article><span>FRAME</span><p>Equal-sized RAM block.</p></article><article><span>SEGMENT</span><p>Variable logical unit.</p></article><article><span>THRASH</span><p>Excessive page swapping.</p></article></section><div className="homework-callout"><b>HOMEWORK 19</b><span>30 marks · paging, segmentation and virtual memory</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="19" title="Paging, virtual memory and segmentation" syllabusLabel="SYLLABUS 16.1" sourceLabel="TEXTBOOK Ch20 · pp.372–375" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 16.1 p.35 · endorsed coursebook Chapter 20 printed pp.372–375 · verified 2022–2024 Paper 3 questions and mark schemes" sourceDetail="The lesson keeps logical pages distinct from physical frames, traces address translation and page faults, compares paging with segmentation, and explains replacement and disk thrashing without treating virtual memory as extra RAM." />;
}
