"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip, Formula, WorkedBoard } from "../../_components/a2-theory-lesson";
import { NeuralNetworkDiagram } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Learning categories", subtitle: "Identify the feedback available to the learner", marks: 10,
    questions: [
      { id: "a2-24-1", marks: 3, lines: 6, prompt: <><b>Describe supervised learning.</b></>, answer: <p>A model is trained with labelled examples containing input and expected output pairs <em>[1]</em>. It changes model parameters to reduce the error between prediction and target <em>[1]</em>, then applies the learned mapping to unseen inputs <em>[1]</em>.</p> },
      { id: "a2-24-2", marks: 3, lines: 6, prompt: <><b>Describe unsupervised learning.</b></>, answer: <p>It analyses unlabelled data <em>[1]</em> to discover previously unknown patterns, similarities or differences <em>[1]</em>, for example by grouping similar records into clusters without supplied target outputs <em>[1]</em>.</p> },
      { id: "a2-24-3", marks: 4, lines: 7, prompt: <><b>Explain reinforcement learning using the terms agent, action and reward.</b></>, answer: <p>An agent observes/interacts with an environment <em>[1]</em>, chooses an action <em>[1]</em>, receives a reward or penalty as feedback <em>[1]</em>, and changes its policy through repeated trial and error to increase long-term reward <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Neural learning", subtitle: "Trace forward prediction and backward correction", marks: 10,
    questions: [
      { id: "a2-24-4", marks: 3, lines: 6, prompt: <><b>Explain how one artificial neuron produces an output.</b></>, answer: <p>Each input is multiplied by a weight <em>[1]</em>; weighted inputs and a bias are summed <em>[1]</em>; an activation function transforms the sum into the neuron&apos;s output <em>[1]</em>.</p> },
      { id: "a2-24-5", marks: 3, lines: 6, prompt: <><b>Explain why hidden layers make an artificial neural network useful for machine learning.</b></>, answer: <p>Connections and weights allow the network to model complex non-linear relationships <em>[1]</em>. Hidden layers learn intermediate features/patterns <em>[1]</em>, so outputs can be inferred for new inputs after training <em>[1]</em>.</p> },
      { id: "a2-24-6", marks: 4, lines: 7, prompt: <><b>Describe Deep Learning and give one reason for using it.</b></>, answer: <p>Deep Learning is Machine Learning using an ANN with many hidden layers <em>[1]</em>. Successive layers learn increasingly complex/hierarchical features <em>[1]</em>. It is useful for complex, high-dimensional data such as images, speech or language <em>[1]</em>, although it usually needs large datasets and substantial processing <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Correction and prediction", subtitle: "Use error to train; use regression for a continuous value", marks: 10,
    questions: [
      { id: "a2-24-7", marks: 3, lines: 6, prompt: <><b>Describe a regression method in machine learning.</b></>, answer: <p>Regression learns a relationship/function from input data to a continuous numerical output <em>[1]</em>. Model parameters are adjusted to reduce residual/error between predicted and known values <em>[1]</em>; the fitted model is then used to estimate an unseen value <em>[1]</em>.</p> },
      { id: "a2-24-8", marks: 3, lines: 6, prompt: <><b>Distinguish training data, validation data and test data.</b></>, answer: <p>Training data adjusts parameters/weights <em>[1]</em>. Validation data selects settings or detects overfitting during development <em>[1]</em>. Test data is held back for an independent final estimate of performance <em>[1]</em>.</p> },
      { id: "a2-24-9", marks: 4, lines: 8, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Describe back propagation of errors in a neural network.</b></p><p>Adapted from 9618/32 O/N 2025 Q9(b). [4]</p></>, answer: <p>Compare actual output with expected output to calculate an error/loss <em>[1]</em>. Work backwards through the network to determine how weights contributed to the error/its gradient <em>[1]</em>. Adjust neuron connection weights to reduce the error <em>[1]</em>, and repeat forward prediction and backward adjustment until results improve <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson24Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Connect data, model and feedback.", prompt: "What information tells a learning system that a prediction should change?", source: "2027–2029 syllabus 18.1 p.36; coursebook Chapter 22 printed pp.403–408.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch22" syllabusLabel="SYLLABUS 18.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 24 · 90 MINUTES</span><h1>Predict forward.<br /><em>Correct backward.</em></h1><p>machine learning · ANN · deep learning · reinforcement · regression</p></div><div className="a2-at-hero" role="img" aria-label="Machine learning lesson themes"><strong>MACHINE LEARNING</strong><span>DATA</span><span>WEIGHTS</span><span>ERROR</span><span>PREDICTION</span></div></section></Slide> },
    { time: "5 min", focus: "Map every current-syllabus AI requirement.", prompt: "Which requirement is new enough to be easy to miss if teaching only from memory?", source: "Official 2027–2029 syllabus p.36.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.36" syllabusLabel="18.1 · REQUIRED" title="Classify learning, explain neural networks, then show how error improves a model." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "CATEGORIES", title: "Supervised / unsupervised", body: "Labels determine the learning task." }, { eyebrow: "METHOD", title: "Reinforcement", body: "Reward from actions in an environment." }, { eyebrow: "MODEL", title: "ANN + deep learning", body: "Weighted layers learn representations." }, { eyebrow: "TRAIN / PREDICT", title: "Backprop + regression", body: "Reduce error; estimate numeric outcomes." }]} /></Slide> },
    { time: "5 min", focus: "Separate overlapping AI vocabulary.", prompt: "Why is Deep Learning not a rival category to Machine Learning?", source: "Coursebook §22.03–22.04 pp.403–408; syllabus 18.1.", content: <Slide number="03" eyebrow="THE AI LANDSCAPE" sourceLabel="TEXTBOOK pp.403–408" syllabusLabel="18.1 · TERMINOLOGY" title="Machine Learning is the broad process; Deep Learning is a layered neural approach within it." className="a2-slide a2-at-slide"><CompareTable headers={["Term", "Core idea", "Typical feedback/data"]} rows={[["Machine Learning", "learn patterns or a mapping from data", "depends on method"], ["supervised", "map inputs to known targets", "labelled examples"], ["unsupervised", "discover structure", "unlabelled examples"], ["reinforcement", "learn action policy", "reward / penalty"], ["Deep Learning", "many-layer ANN", "large, complex datasets"]]} /></Slide> },
    { time: "6 min", focus: "Explain supervised training as a labelled mapping.", prompt: "Where does the expected output come from?", source: "Coursebook machine-learning categories pp.403–405; 9618/31 M/J 2023 Q2(a).", content: <Slide number="04" eyebrow="SUPERVISED LEARNING" sourceLabel="9618/31 M/J 2023 · Q2(a)" syllabusLabel="18.1 · CATEGORY" title="Examples provide both the question and the correct answer." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "INPUT", title: "Features", body: "email words, image pixels, house data" }, { eyebrow: "LABEL", title: "Expected output", body: "spam/not spam or known price" }, { eyebrow: "TRAIN", title: "Reduce prediction error" }, { eyebrow: "USE", title: "Predict unseen examples" }]} /></Slide> },
    { time: "6 min", focus: "Describe regression as continuous numerical prediction.", prompt: "Is a predicted house price a class label or a continuous value?", source: "Coursebook regression analysis methods pp.405–406; syllabus 18.1.", content: <Slide number="05" eyebrow="REGRESSION" sourceLabel="TEXTBOOK pp.405–406" syllabusLabel="18.1 · REGRESSION METHODS" title="Fit a relationship that minimises residual error, then estimate a number." className="a2-slide a2-at-slide"><Formula>prediction = model(inputs) · residual = actual − predicted</Formula><ConceptCards items={[{ eyebrow: "TRAIN", title: "Known pairs", body: "Inputs with observed numerical outputs." }, { eyebrow: "FIT", title: "Reduce error", body: "Adjust line, curve or model parameters." }, { eyebrow: "PREDICT", title: "Continuous value", body: "Price, demand, temperature or score." }]} /></Slide> },
    { time: "6 min", focus: "Describe pattern discovery without targets.", prompt: "How can a system evaluate a cluster when no correct label was supplied?", source: "Coursebook pp.403–405; 9618/33 M/J 2025 Q10(c).", content: <Slide number="06" eyebrow="UNSUPERVISED LEARNING" sourceLabel="9618/33 M/J 2025 · Q10(c)" syllabusLabel="18.1 · CATEGORY" title="The algorithm searches unlabelled data for hidden structure." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "INPUT", title: "Unlabelled records", body: "No target output for each example." }, { eyebrow: "COMPARE", title: "Similarity", body: "Measure which records/features resemble each other." }, { eyebrow: "DISCOVER", title: "Clusters / patterns", body: "Reveal groups, differences or anomalies." }]} /></Slide> },
    { time: "6 min", focus: "Explain reinforcement as sequential feedback.", prompt: "Why is a reward not the same as a labelled answer for every action?", source: "Coursebook reinforcement learning pp.403–405; 9618/32 M/J 2024 Q11.", content: <Slide number="07" eyebrow="REINFORCEMENT LEARNING" sourceLabel="9618/32 M/J 2024 · Q11" syllabusLabel="18.1 · METHOD" title="An agent improves a policy through actions, consequences and reward." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "OBSERVE", title: "State" }, { eyebrow: "CHOOSE", title: "Action" }, { eyebrow: "RECEIVE", title: "Reward / penalty" }, { eyebrow: "UPDATE", title: "Policy" }, { eyebrow: "REPEAT", title: "Maximise long-term reward" }]} /></Slide> },
    { time: "6 min", focus: "Choose a learning method from the available feedback.", prompt: "Which method suits customer segmentation with no existing groups?", source: "Syllabus 18.1 synthesis; coursebook pp.403–405.", content: <Slide number="08" eyebrow="CHOOSE BY EVIDENCE" sourceLabel="TEXTBOOK pp.403–405" syllabusLabel="18.1 · REASONS" title="Ask what outcome information is available before naming the method." className="a2-slide a2-at-slide"><CompareTable headers={["Situation", "Best fit", "Reason"]} rows={[["diagnose from labelled scans", "supervised", "known classes train the mapping"], ["predict next month's sales", "regression", "continuous numerical target"], ["discover customer groups", "unsupervised", "no supplied class labels"], ["robot learns a route", "reinforcement", "actions receive delayed reward"], ["recognise complex speech", "Deep Learning", "hierarchical high-dimensional features"]]} /></Slide> },
    { time: "6 min", focus: "Map a biological analogy to ANN structure without overclaiming.", prompt: "What does a connection weight control?", source: "Coursebook §22.04 pp.406–407.", content: <Slide number="09" eyebrow="ARTIFICIAL NEURAL NETWORK" sourceLabel="TEXTBOOK pp.406–407" syllabusLabel="18.1 · ANN" title="Layers of connected artificial neurons transform inputs into outputs." className="a2-slide a2-at-slide"><NeuralNetworkDiagram /></Slide> },
    { time: "6 min", focus: "Calculate the role of weights, bias and activation.", prompt: "Which parameter changes the influence of one incoming value?", source: "Coursebook ANN explanation pp.406–407.", content: <Slide number="10" eyebrow="ONE ARTIFICIAL NEURON" sourceLabel="TEXTBOOK pp.406–407" syllabusLabel="18.1 · ANN" title="A neuron combines weighted evidence, then applies an activation function." className="a2-slide a2-at-slide"><Formula>output = activation((x₁w₁ + x₂w₂ + …) + bias)</Formula><ConceptCards items={[{ eyebrow: "INPUT x", title: "Evidence", body: "Values from data or a previous layer." }, { eyebrow: "WEIGHT w", title: "Influence", body: "Strength and direction of a connection." }, { eyebrow: "ACTIVATION", title: "Non-linearity", body: "Determines the neuron's emitted value." }]} /></Slide> },
    { time: "7 min", focus: "Describe training as repeated measurement and correction.", prompt: "Why must training use many examples and many passes?", source: "Coursebook ANN training pp.406–407.", content: <Slide number="11" eyebrow="TRAINING LOOP" sourceLabel="TEXTBOOK pp.406–407" syllabusLabel="18.1 · MACHINE LEARNING" title="A useful network is learned, not hand-filled with final weights." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "FORWARD", title: "Predict" }, { eyebrow: "COMPARE", title: "Calculate loss/error" }, { eyebrow: "BACKWARD", title: "Assign contribution" }, { eyebrow: "UPDATE", title: "Adjust weights" }, { eyebrow: "REPEAT", title: "Improve on examples" }]} /></Slide> },
    { time: "7 min", focus: "Explain back propagation in accepted mark-point order.", prompt: "What exactly travels backward: the original input or error information?", source: "Syllabus 18.1; coursebook p.407; 9618/32 O/N 2025 Q9(b).", content: <Slide number="12" eyebrow="BACK PROPAGATION OF ERRORS" sourceLabel="9618/32 O/N 2025 · Q9(b)" syllabusLabel="18.1 · REQUIRED" title="Use output error to calculate how each earlier weight should change." className="a2-slide a2-at-slide"><WorkedBoard label="Mark-scheme sequence"><ol><li>Compare predicted and expected outputs.</li><li>Calculate loss/error and its gradient.</li><li>Propagate contribution information backward through layers.</li><li>Adjust weights to reduce future error; repeat.</li></ol></WorkedBoard></Slide> },
    { time: "7 min", focus: "Define Deep Learning and balance benefit against cost.", prompt: "Why can more hidden layers help, and what resources do they demand?", source: "Coursebook Deep Learning pp.407–408; 9618/31 M/J 2024 Q9.", content: <Slide number="13" eyebrow="DEEP LEARNING" sourceLabel="9618/31 M/J 2024 · Q9" syllabusLabel="18.1 · REASONS" title="Many hidden layers learn a hierarchy of increasingly complex features." className="a2-slide a2-at-slide"><CompareTable headers={["Strength", "Cost / risk"]} rows={[["learns useful features from complex raw data", "needs large representative datasets"], ["models highly non-linear relationships", "requires substantial processor time/energy"], ["supports image, speech and language tasks", "difficult to interpret; can inherit bias"], ["performance can improve with scale", "may overfit without validation/regularisation"]]} /></Slide> },
    { time: "8 min", focus: "Write the current backpropagation answer in four linked steps.", prompt: "Each sentence should connect output error to a weight update.", source: "Adapted from Cambridge 9618/32 O/N 2025 Q9(b) and published mark scheme.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/32 O/N 2025 · Q9(b)" syllabusLabel="18.1 · 4 MARKS" title="Compare, calculate, propagate, adjust." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/32 O/N 2025 · Q9(b) · ADAPTED" marks={4} prompt={<p>Describe the back propagation of errors method used to train a neural network. [4]</p>} answer={<ul><li>Compare the network output with the expected output to obtain error/loss. [1]</li><li>Work backward to determine the contribution/gradient associated with earlier connections. [1]</li><li>Adjust neuron connection weights in the direction that reduces error. [1]</li><li>Repeat forward and backward passes until predictions become more accurate. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve the full Chapter 18 learning system.", prompt: "Students match label, reward, cluster and continuous value to a method.", source: "Syllabus 18.1 synthesis; coursebook Chapter 22 pp.403–408.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch22 · SYLLABUS p.36" syllabusLabel="18.1 · CHAPTER 18 CLOSE" title="Choose feedback, build a model, measure error and improve." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>LABEL</span><p>Supervised mapping.</p></article><article><span>NO LABEL</span><p>Unsupervised patterns.</p></article><article><span>REWARD</span><p>Reinforcement policy.</p></article><article><span>ERROR</span><p>Backpropagation updates weights.</p></article></section><div className="homework-callout"><b>HOMEWORK 24</b><span>30 marks · ML, ANN, regression and backprop</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="24" title="Machine learning, neural networks and back propagation" syllabusLabel="SYLLABUS 18.1" sourceLabel="TEXTBOOK Ch22 · pp.403–408" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 18.1 p.36 · endorsed coursebook Chapter 22 printed pp.403–408 · verified 2023–2025 Paper 3 questions and mark schemes" sourceDetail="The lesson distinguishes supervised, unsupervised and reinforcement learning; explains artificial neural networks and Deep Learning; and explicitly teaches the current-syllabus requirements for regression methods and back propagation of errors." />;
}
