"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Why professional ethics exists", subtitle: "Judgement beyond mere legal compliance", marks: 10,
    questions: [
      { id: "l33-1", marks: 4, lines: 4, prompt: <><b>Explain two purposes of ethics for a computing professional.</b></>, answer: <p>Examples: guide decisions where law/rules are incomplete; protect public safety, welfare, privacy and fairness; create consistent professional expectations; make practitioners accountable; preserve public trust. Award a clear purpose and linked explanation for each. <em>[2 + 2]</em></p> },
      { id: "l33-2", marks: 3, lines: 3, prompt: <><b>Distinguish law, organisational policy and professional ethics.</b></>, answer: <p><strong>Law</strong> is enforceable by the state. <strong>Policy</strong> is a rule set by an organisation for its people/systems. <strong>Ethics</strong> concerns reasoned standards of right professional conduct and may demand more than the legal or policy minimum. <em>[1 each]</em></p> },
      { id: "l33-3", marks: 3, lines: 3, prompt: <><b>A manager orders a developer to hide a known safety defect. Explain why “I followed orders” is not enough.</b></>, answer: <p>The developer has professional responsibility for foreseeable public harm, must raise/document the defect through appropriate channels and should not mislead stakeholders. Authority from a manager does not remove individual accountability or the duty to protect the public. <em>[3]</em></p> },
    ],
  },
  {
    code: "B", title: "Bodies, codes and judgement", subtitle: "BCS/IEEE as support—not replacements for thinking", marks: 10,
    questions: [
      { id: "l33-4", marks: 4, lines: 4, prompt: <><b>Explain four benefits of joining a professional ethical body.</b></>, answer: <p>Any four explained: access to an ethical code/guidance; professional development/training; legal or disciplinary guidance; peer network/mentoring; recognised standards/credentials; accountability processes; improved public/employer trust. <em>[1 each when linked]</em></p> },
      { id: "l33-5", marks: 3, lines: 3, prompt: <><b>State what BCS and IEEE contribute to ethical computing practice.</b></>, answer: <p>Both are professional organisations that publish codes/standards and guidance, support continuing professional development and communities, and promote accountability/public trust. Exact code wording need not be memorised; professionals use current guidance in context. <em>[3]</em></p> },
      { id: "l33-6", marks: 3, lines: 3, prompt: <><b>State three questions a developer should ask before releasing a facial-recognition attendance system.</b></>, answer: <p>Examples: Who benefits and who may be harmed? Is biometric collection necessary/proportionate and consented to? How accurate/fair is it across groups? Who can access the data? What appeal/human-review route exists? How can harm be mitigated? <em>[any 3 relevant]</em></p> },
    ],
  },
  {
    code: "C", title: "Published professional conduct", subtitle: "Colleagues, public and professional support", marks: 10,
    questions: [
      { id: "l33-7", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain why a computing professional should act ethically towards colleagues and the public.</b><p>Adapted from 9618/12 O/N 2024 Q5(a). [4]</p></>, answer: <p>Towards colleagues: act fairly, avoid discrimination, credit contributions, accept constructive criticism or support training. Towards the public: protect safety/welfare and data, be honest about software capability/risks and maintain trust. Award distinct explained points across both groups. <em>[4]</em></p> },
      { id: "l33-8", marks: 3, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>State consequences for a professional who does not join an ethical computing body.</b><p>Adapted from 9618/13 M/J 2025 Q3(d). [3]</p></>, answer: <p>They may miss legal/ethical guidance, professional training, networking/mentoring or recognised standards; this can lead to poorer practice, missed work and unethical or unlawful decisions. <em>[any 3 published-style points]</em></p> },
      { id: "l33-9", marks: 3, lines: 3, prompt: <><b>A company can quietly collect extra location data that would improve advertising but is not needed for the app.</b><p>Recommend an ethical action and justify it with stakeholders and mitigation.</p></>, answer: <p>Do not collect it by default; minimise data or request informed opt-in consent. Users face privacy/safety harm while the company gains revenue. Explain purpose, provide genuine choice, limit retention/access and audit use. <em>[decision + stakeholder balance + mitigation]</em></p> },
    ],
  },
];

export default function Lesson33Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame professional ethics as accountable judgement when code affects people.", prompt: "Ask: if an action is legal, is it automatically professionally ethical?", source: "Syllabus 7.1 ethics; Coursebook 10.01–10.03 printed pp.147–150.", content: <Slide number="01" eyebrow="CHAPTER 7 · ETHICS" sourceLabel="TEXTBOOK CH.10 · pp.146–150" syllabusLabel="SYLLABUS 7.1" className="se-title"><section className="se-title-grid"><div className="se-title-copy"><span>LESSON 33 · 90 MINUTES</span><h1>Code has <em>consequences.</em></h1><p>Use professional principles, stakeholder evidence and mitigations to make defensible decisions—not just legal ones.</p></div><div className="se-title-visual"><div><b>1</b><span>IDENTIFY THE DECISION</span></div><div><b>2</b><span>MAP STAKEHOLDERS + HARM</span></div><div><b>3</b><span>TEST DUTIES + EVIDENCE</span></div><div><b>4</b><span>ACT · DOCUMENT · REVIEW</span></div></div></section></Slide> },
    { time: "5 min", focus: "Surface competing obligations in a realistic software-release decision.", prompt: "Students choose release, delay or limited pilot and give one reason.", source: "Coursebook 10.02–10.03 professional/public good; syllabus 7.1 scenario impact.", content: <Slide number="02" eyebrow="DO NOW · SHIP TONIGHT?" sourceLabel="TEXTBOOK §§10.02–10.03" syllabusLabel="SYLLABUS 7.1" title="A hospital app passes most tests—but sometimes hides a severe allergy alert."><section className="se-grid three"><article className="se-card"><span>MANAGER</span><h3>Release deadline</h3><p>Delay costs money and breaks a contract milestone.</p></article><article className="se-card"><span>DEVELOPER</span><h3>Known uncertainty</h3><p>The defect is rare, repeatable and not yet fixed.</p></article><article className="se-card"><span>PATIENT + CLINICIAN</span><h3>Safety and trust</h3><p>A missed warning could cause direct harm.</p></article></section><p className="se-warning">Your decision must name stakeholders, evidence, likely impact and a mitigation—not only an opinion.</p></Slide> },
    { time: "6 min", focus: "Distinguish external law, internal policy and ethical professional duty.", prompt: "Give an action that is legal but still ethically questionable.", source: "Coursebook 10.01 printed p.147; syllabus 7.1 need and purpose of ethics.", content: <Slide number="03" eyebrow="THREE SOURCES OF EXPECTATION" sourceLabel="TEXTBOOK §10.01 · p.147" syllabusLabel="SYLLABUS 7.1" title="Ethics can demand more than minimum compliance."><section className="se-ethics-lens"><article><span className="se-kicker">LAW</span><h3>State-enforced boundary</h3><p>Defines legal duties and penalties; varies by jurisdiction.</p></article><article><span className="se-kicker">POLICY</span><h3>Organisation&apos;s rule</h3><p>Sets permitted behaviour, processes and consequences inside the organisation.</p></article><article><span className="se-kicker">ETHICS</span><h3>Reasoned professional duty</h3><p>Asks what ought to be done for fairness, safety, rights and public good.</p></article></section></Slide> },
    { time: "6 min", focus: "Explain why computing professionals need shared ethical principles.", prompt: "Which purpose still matters when no law has caught up with a new technology?", source: "Coursebook 10.01–10.02 printed pp.147–149; syllabus 7.1.", content: <Slide number="04" eyebrow="WHY ETHICS?" sourceLabel="TEXTBOOK §§10.01–10.02 · pp.147–149" syllabusLabel="SYLLABUS 7.1" title="Power, uncertainty and unequal expertise create responsibility."><section className="se-grid four"><article className="se-card"><span>GUIDE</span><p>decide where rules are incomplete</p></article><article className="se-card"><span>PROTECT</span><p>public safety, welfare, rights and privacy</p></article><article className="se-card"><span>ACCOUNT</span><p>make conduct open to review and consequence</p></article><article className="se-card"><span>TRUST</span><p>show that expertise serves the public good</p></article></section><p className="se-note">Professionals often understand technical risks that users, clients or managers cannot independently evaluate.</p></Slide> },
    { time: "6 min", focus: "Define a computing professional by competence, judgement and accountability.", prompt: "Why is technical skill necessary but not sufficient?", source: "Coursebook 10.02 printed pp.147–149; syllabus 7.1 computing professional.", content: <Slide number="05" eyebrow="PROFESSIONAL RESPONSIBILITY" sourceLabel="TEXTBOOK §10.02 · pp.147–149" syllabusLabel="SYLLABUS 7.1" title="Competence includes knowing when to question, disclose and escalate."><section className="se-grid four"><article className="se-card"><span>COMPETENCE</span><p>maintain knowledge; work within limits</p></article><article className="se-card"><span>HONESTY</span><p>do not conceal defects or exaggerate capability</p></article><article className="se-card"><span>DUE CARE</span><p>test, secure and consider foreseeable use</p></article><article className="se-card"><span>ACCOUNTABILITY</span><p>record decisions, accept review, correct harm</p></article></section></Slide> },
    { time: "6 min", focus: "Introduce BCS as an example of a professional ethical body without memorising frozen wording.", prompt: "Which benefit changes the member's decision before a problem occurs?", source: "Syllabus 7.1 explicitly includes BCS; Coursebook 10.02 printed pp.147–149.", content: <Slide number="06" eyebrow="BCS · PROFESSIONAL BODY EXAMPLE" sourceLabel="TEXTBOOK §10.02 · pp.147–149" syllabusLabel="SYLLABUS 7.1 · BCS" title="Code, competence, community and public trust."><section className="se-grid four"><article className="se-card"><span>CODE</span><p>shared ethical expectations and guidance</p></article><article className="se-card"><span>DEVELOPMENT</span><p>continuing learning and recognised practice</p></article><article className="se-card"><span>COMMUNITY</span><p>peer support, mentoring and professional network</p></article><article className="se-card"><span>ACCOUNTABILITY</span><p>standards and consequences support trust</p></article></section><p className="se-note">Use current codes in real practice; the exam assesses <strong>purpose and importance</strong>, not verbatim clauses.</p></Slide> },
    { time: "6 min", focus: "Introduce IEEE as a second international professional body and compare shared functions.", prompt: "Which functions overlap with BCS and which may differ by community?", source: "Syllabus 7.1 explicitly includes IEEE; Coursebook 10.02 professional organisations.", content: <Slide number="07" eyebrow="IEEE · PROFESSIONAL BODY EXAMPLE" sourceLabel="TEXTBOOK §10.02 + SYLLABUS" syllabusLabel="SYLLABUS 7.1 · IEEE" title="Ethical guidance within a global technical community."><section className="se-grid three"><article className="se-card"><span>ETHICAL GUIDANCE</span><h3>Principles</h3><p>public welfare, honesty, fairness, competence and responsible practice.</p></article><article className="se-card"><span>TECHNICAL COMMUNITY</span><h3>Standards + learning</h3><p>knowledge exchange, publications, conferences and continuing development.</p></article><article className="se-card"><span>PROFESSIONAL IDENTITY</span><h3>Trust + accountability</h3><p>membership signals commitment while conduct must still prove it.</p></article></section></Slide> },
    { time: "6 min", focus: "Explain why joining matters while rejecting the idea that membership guarantees ethics.", prompt: "Turn each noun—guidance, training, network—into a consequence chain.", source: "Coursebook 10.02; syllabus 7.1 importance of joining; 9618/13 M/J 2025 Q3(d).", content: <Slide number="08" eyebrow="WHY JOIN?" sourceLabel="TEXTBOOK §10.02 + 9618/13 M/J 2025" syllabusLabel="SYLLABUS 7.1" title="Resource → better judgement → professional consequence."><section className="se-compare"><div><b>RESOURCE</b><b>PRACTICAL VALUE</b><b>IF MISSING</b></div><div><b>Code + guidance</b><span>tests decisions against shared duties</span><span>unclear expectations; inconsistent conduct</span></div><div><b>Training</b><span>maintains competence as risks change</span><span>outdated practice; avoidable harm</span></div><div><b>Network/support</b><span>access to peers, mentoring and advice</span><span>isolation; missed learning/work opportunities</span></div></section><p className="se-warning">Membership supports ethical practice; it does not replace individual judgement or guarantee good behaviour.</p></Slide> },
    { time: "6 min", focus: "Map stakeholders broadly so indirect and unequal impacts are visible.", prompt: "Add one stakeholder not represented by the buyer or end user.", source: "Coursebook 10.03 public good printed pp.149–150; syllabus 7.1 scenario impact.", content: <Slide number="09" eyebrow="STAKEHOLDER MAP" sourceLabel="TEXTBOOK §10.03 · pp.149–150" syllabusLabel="SYLLABUS 7.1" title="Who gains, who carries risk and who has a voice?"><section className="se-stakeholder-map"><article><b>USERS</b><p>safety, dignity, access, privacy</p></article><article><b>CLIENT / EMPLOYER</b><p>cost, deadline, reputation, duty</p></article><article><b>COLLEAGUES</b><p>credit, fairness, workload, critique</p></article><article><b>PUBLIC</b><p>trust, welfare, shared resources</p></article><article className="center"><b>DECISION</b><p>benefit · harm · evidence · mitigation</p></article><article><b>NON-USERS</b><p>bystanders, excluded groups, future people</p></article></section></Slide> },
    { time: "6 min", focus: "Give students a repeatable ethical decision process.", prompt: "Which step prevents a confident opinion from substituting for evidence?", source: "Syllabus 7.1 act ethically and evaluate impact; Coursebook 10.02–10.03.", content: <Slide number="10" eyebrow="A DEFENSIBLE DECISION" sourceLabel="TEXTBOOK §§10.02–10.03" syllabusLabel="SYLLABUS 7.1" title="Turn values into an auditable process."><section className="se-decision-ladder"><span>1 · FACTS +<br />UNCERTAINTIES</span><i>→</i><span>2 · STAKEHOLDERS +<br />RIGHTS</span><i>→</i><span>3 · BENEFITS +<br />HARMS</span><i>→</i><span>4 · OPTIONS +<br />MITIGATIONS</span><i>→</i><span>5 · DECIDE,<br />DOCUMENT, REVIEW</span></section><p className="se-note">Use proportionality: is the data, risk or restriction <strong>necessary</strong>, and is there a less harmful route?</p></Slide> },
    { time: "5 min", focus: "Explore common duty conflicts without assuming one universal ranking.", prompt: "For each conflict, state what evidence would change your decision.", source: "Coursebook 10.02–10.03 ethical issues; syllabus 7.1 scenario reasoning.", content: <Slide number="11" eyebrow="CONFLICTS NEED EVIDENCE" sourceLabel="TEXTBOOK §§10.02–10.03" syllabusLabel="SYLLABUS 7.1" title="Useful benefits do not erase foreseeable harm."><section className="se-grid four"><article className="se-card"><span>DEADLINE / SAFETY</span><p>release pressure versus known defect</p></article><article className="se-card"><span>PERSONALISATION / PRIVACY</span><p>better service versus extra data</p></article><article className="se-card"><span>SECRECY / DISCLOSURE</span><p>employer interest versus public risk</p></article><article className="se-card"><span>AUTOMATION / FAIRNESS</span><p>efficiency versus unequal error</p></article></section></Slide> },
    { time: "7 min", focus: "Apply the decision ladder to one high-consequence case.", prompt: "Pairs produce a recommendation with two safeguards and a review trigger.", source: "Syllabus 7.1 ethical/unethical action in scenarios; Coursebook 10.03.", content: <Slide number="12" eyebrow="SCENARIO CLINIC" sourceLabel="TEXTBOOK §10.03 · APPLICATION" syllabusLabel="SYLLABUS 7.1" title="Facial recognition will replace manual school attendance."><section className="se-grid three"><article className="se-card"><span>EVIDENCE</span><h3>What must be tested?</h3><p>accuracy by group, false matches, security and necessity.</p></article><article className="se-card"><span>STAKEHOLDERS</span><h3>Who carries risk?</h3><p>pupils, families, staff, bystanders and excluded pupils.</p></article><article className="se-card"><span>MITIGATION</span><h3>What changes the design?</h3><p>alternative route, minimal retention, human review, appeal and audit.</p></article></section><p className="se-note">Recommendation format: <strong>decision → evidence → stakeholder effect → safeguards → review condition</strong>.</p></Slide> },
    { time: "8 min", focus: "Practise published ethical duties toward colleagues and the public.", prompt: "Write two colleague points and two public points; each must include a consequence.", source: "Adapted from 9618/12 O/N 2024 Q5(a), checked against the published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/12 O/N 2024 · Q5(a)" syllabusLabel="SYLLABUS 7.1 — EXAM PRACTICE" title="Why act ethically towards colleagues and the public?" className="slide--se-paper"><section className="se-paper-grid"><article><span>COLLEAGUES</span><p>Explain ethical conduct and its professional effect.</p></article><article><span>PUBLIC</span><p>Explain a duty and the harm/trust it affects.</p></article></section><ExamReveal><p>Examples: treat colleagues fairly, credit/help them and accept critique, improving work and workplace trust. Protect public safety/welfare and data; describe software honestly, reducing harm and maintaining confidence. Award distinct explained points across both groups.</p></ExamReveal><small className="se-source-line">Concise adaptation of 9618/12 O/N 2024 Q5(a); original allocation [4].</small></Slide> },
    { time: "8 min", focus: "Use the 2025 professional-body question to turn membership benefits into consequences.", prompt: "Students write three linked points, then label resource and consequence.", source: "Adapted from 9618/13 M/J 2025 Q3(d), checked against the published mark scheme.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE · 3 MARKS" sourceLabel="9618/13 M/J 2025 · Q3(d)" syllabusLabel="SYLLABUS 7.1 — EXAM PRACTICE" title="What can be lost by not joining a professional body?" className="slide--se-paper"><section className="se-paper-grid three"><article><span>GUIDANCE</span><p>ethical/legal support</p></article><article><span>DEVELOPMENT</span><p>training and current knowledge</p></article><article><span>COMMUNITY</span><p>networking, mentoring and opportunities</p></article></section><ExamReveal><p>Any three developed outcomes: limited ethical/legal guidance, less training/continuing development, less networking/support, missed work or increased risk of unethical/unlawful practice.</p></ExamReveal><small className="se-source-line">Concise adaptation of 9618/13 M/J 2025 Q3(d); original allocation [3].</small></Slide> },
    { time: "5 min", focus: "Close on the difference between compliance, membership and accountable conduct.", prompt: "Students give one sentence per card without using 'because it is good'.", source: "Syllabus 7.1 lesson synthesis; Coursebook 10.01–10.03.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK §§10.01–10.03 · REVIEW" syllabusLabel="SYLLABUS 7.1" title="Three claims a professional must defend."><section className="se-exit"><article><span>1 · DISTINGUISH</span><p>Legal does not always mean ethical because…</p></article><article><span>2 · EXPLAIN</span><p>A professional body improves practice by…</p></article><article><span>3 · ACT</span><p>Known public-safety defect: first action + reason.</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="33" slides={slides} homework={<HomeworkSheet lessonNumber="33" title="Professional Ethics: Codes, Stakeholders and Decisions" marks={30} minutes={45} syllabusLabel="SYLLABUS 7.1" sourceLabel="TEXTBOOK CH.10 · pp.146–150 + PAPER 1" instructions="For every ethical scenario, identify facts and uncertainty, map stakeholders, balance benefits and harms, recommend an action and add a practical mitigation. Do not treat legality or professional membership as proof that an action is ethical." sections={homeworkSections} challenge={{ id: "l33-challenge", prompt: <p><Mark>CHALLENGE</Mark> A developer discovers that an accessibility feature creates a small security risk for every user. Write a balanced recommendation with a review trigger.</p>, answer: <p>A defensible answer compares the accessibility benefit and the likelihood/severity of the security risk using evidence. It might keep the feature behind informed choice or redesign it with least privilege, monitoring and a secure alternative. Document the decision, involve affected users/security specialists, and trigger review if incidents, audit results or new evidence exceed an agreed threshold.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 7.1, Coursebook Chapter 10 printed pp.146–150, and the published 2024–2025 Paper 1 ethics questions and mark schemes." sourceDetail="Core: purpose of professional ethics; BCS and IEEE as examples of professional ethical bodies; accountability to colleagues and the public; structured evaluation of ethical and unethical action. Authentic anchors: 9618/12 O/N 2024 Q5(a) [4] and 9618/13 M/J 2025 Q3(d) [3]. Exact code wording can change, so the lesson assesses functions and judgement rather than memorisation." />;
}
