/* Pseudocode examples intentionally retain their source notation. */
/* eslint-disable react/no-unescaped-entities */
"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Control the path", subtitle: "Sequence, selection, iteration and logic", marks: 10,
    questions: [
      { id: "l43-1", marks: 3, lines: 3, prompt: <><b>Explain sequence, selection and iteration.</b></>, answer: <p>Sequence executes statements in a defined order; selection chooses a path according to a Boolean condition; iteration repeats a block while/until a condition or for a known count. These are the three basic constructs. <em>[3]</em></p> },
      { id: "l43-2", marks: 3, lines: 3, prompt: <><b>Write a logic condition for a pupil aged 12 to 18 inclusive who has permission.</b></>, answer: <pre>(Age &gt;= 12 AND Age &lt;= 18) AND HasPermission = TRUE</pre> },
      { id: "l43-3", marks: 4, lines: 4, prompt: <><b>Select a suitable construct for each: process five scores; repeat until a valid password is entered; output “Pass” or “Retry”. Justify briefly.</b></>, answer: <p>FOR/count-controlled iteration for exactly five scores; REPEAT…UNTIL/post-condition iteration when input must occur at least once and stops when valid; IF…ELSE selection for the two alternative outputs. Award construct and reason across the three contexts. <em>[4]</em></p> },
    ],
  },
  {
    code: "B", title: "Translate the representation", subtitle: "Symbols, paths and equivalent pseudocode", marks: 10,
    questions: [
      { id: "l43-4", marks: 4, lines: 4, prompt: <><b>State the purpose of the terminal, input/output, process and decision flowchart symbols.</b></>, answer: <p>Terminal/oval marks Start or End; parallelogram represents input or output; rectangle represents a processing/assignment step; diamond tests a condition and creates labelled alternative branches. <em>[4]</em></p> },
      { id: "l43-5", marks: 6, lines: 7, prompt: <><b>Write pseudocode: input Mark until it is between 0 and 100 inclusive; output “Pass” if Mark is at least 50, otherwise “Retry”.</b></>, answer: <pre>REPEAT{"\n"}   INPUT Mark{"\n"}UNTIL Mark &gt;= 0 AND Mark &lt;= 100{"\n"}IF Mark &gt;= 50 THEN{"\n"}   OUTPUT "Pass"{"\n"}ELSE{"\n"}   OUTPUT "Retry"{"\n"}ENDIF</pre> },
    ],
  },
  {
    code: "C", title: "Published Paper 2 algorithm", subtitle: "A number-guessing game", marks: 10,
    questions: [
      { id: "l43-6", marks: 8, lines: 8, prompt: <><Mark>PAST PAPER PRACTICE · PAPER 2</Mark> <b>Write pseudocode for a 1–100 guessing game: generate a secret integer, repeat prompted input until correct, report too high/too low, then output a success message.</b><p>Adapted from 9618/21 M/J 2025 Q3. [8]</p></>, answer: <pre>DECLARE Secret : INTEGER{"\n"}DECLARE Guess : INTEGER{"\n"}Secret ← INT(RAND(100)) + 1{"\n"}REPEAT{"\n"}   OUTPUT "Enter a guess"{"\n"}   INPUT Guess{"\n"}   IF Guess &gt; Secret THEN{"\n"}      OUTPUT "Too high"{"\n"}   ELSE{"\n"}      IF Guess &lt; Secret THEN{"\n"}         OUTPUT "Too low"{"\n"}      ENDIF{"\n"}   ENDIF{"\n"}UNTIL Guess = Secret{"\n"}OUTPUT "Correct"</pre> },
      { id: "l43-7", marks: 2, lines: 2, prompt: <><b>Explain why the prompt and INPUT must be inside the loop.</b></>, answer: <p>Each unsuccessful attempt must obtain a new guess before the condition is tested again; outside the loop, Guess would not change and the algorithm could repeat forever or never allow another attempt. <em>[2]</em></p> },
    ],
  },
];

export default function Lesson43Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Make control flow visible through a simple access decision and retry loop.", prompt: "Ask which step repeats and which condition chooses a path.", source: "Coursebook 12.05-12.07 printed pp.184-198; syllabus 9.2; Pseudocode Guide 2027-2029.", content: <Slide number="01" eyebrow="CHAPTER 9 · CONTROL FLOW" sourceLabel="TEXTBOOK CH.12 · pp.184-198" syllabusLabel="SYLLABUS 9.2" className="da-title"><section className="da-title-grid"><div className="da-title-copy"><span>LESSON 43 · 90 MINUTES · PAPER 2</span><h1>Same logic.<br /><em>Three representations.</em></h1><p>Build algorithms from sequence, selection and iteration; express conditions with Boolean logic and translate between structured English, flowcharts and pseudocode.</p></div><div className="da-title-map"><div><b>→</b><span>SEQUENCE · ORDER</span></div><div><b>◇</b><span>SELECTION · CHOOSE</span></div><div><b>↻</b><span>ITERATION · REPEAT</span></div><div><b>∧∨¬</b><span>AND · OR · NOT</span></div></div></section></Slide> },
    { time: "5 min", focus: "Map the remaining representation/construct requirements and current syntax authority.", prompt: "Explain the boundary: data structures and full programming syntax come in Chapters 10–11.", source: "Syllabus 9.2 pp.27-28; Coursebook 12.05-12.07; Pseudocode Guide pp.15-21.", content: <Slide number="02" eyebrow="TEXTBOOK × SYLLABUS × PSEUDOCODE GUIDE" sourceLabel="TEXTBOOK §§12.05-12.07 · pp.184-198" syllabusLabel="SYLLABUS 9.2 · PAPER 2" title="Construct and translate simple algorithms."><section className="da-grid four"><article className="da-card"><span>THREE CONSTRUCTS</span><p>sequence, selection, iteration</p></article><article className="da-card"><span>LOGIC</span><p>comparison statements combined with AND, OR and NOT</p></article><article className="da-card"><span>TRANSLATION</span><p>structured English ↔ flowchart ↔ pseudocode</p></article><article className="da-card"><span>BOUNDARY</span><p>no array/file/search/sort algorithms or formal module syntax yet</p></article></section></Slide> },
    { time: "6 min", focus: "Define sequence as ordered statements rather than merely one line.", prompt: "Students reorder a calculation whose result is used later.", source: "Coursebook 12.03 and 12.05; syllabus 9.2 sequence.", content: <Slide number="03" eyebrow="SEQUENCE · ORDER MATTERS" sourceLabel="TEXTBOOK §§12.03 + 12.05" syllabusLabel="SYLLABUS 9.2" title="Each statement executes once in its written order."><pre className="da-code">INPUT Hours{"\n"}INPUT Rate{"\n"}GrossPay ← Hours * Rate{"\n"}Tax ← GrossPay * 0.20{"\n"}NetPay ← GrossPay - Tax{"\n"}OUTPUT NetPay</pre><p className="da-note">Assignment is a statement within sequence. It is not a fourth basic construct.</p></Slide> },
    { time: "6 min", focus: "Build simple two-way selection using a Boolean condition.", prompt: "Trace exactly one branch for Mark=49 and Mark=50.", source: "Coursebook 12.06 printed pp.188-191; Pseudocode Guide p.18; syllabus 9.2 selection.", content: <Slide number="04" eyebrow="SELECTION · CHOOSE A PATH" sourceLabel="TEXTBOOK §12.06 + GUIDE p.18" syllabusLabel="SYLLABUS 9.2" title="A condition is TRUE or FALSE; only the selected branch executes."><pre className="da-code">IF Mark &gt;= 50 THEN{"\n"}   OUTPUT "Pass"{"\n"}ELSE{"\n"}   OUTPUT "Retry"{"\n"}ENDIF</pre><section className="da-grid two"><article className="da-card"><span>TRUE</span><p>execute the THEN block</p></article><article className="da-card"><span>FALSE</span><p>execute the ELSE block when present</p></article></section></Slide> },
    { time: "6 min", focus: "Compare count-, pre-condition and post-condition iteration at recognition level.", prompt: "Match a known count, possibly-zero repetitions and at-least-once input to the right form.", source: "Coursebook 12.07 printed pp.191-198; Pseudocode Guide pp.20-21; syllabus 9.2 iteration.", content: <Slide number="05" eyebrow="ITERATION · REPEAT A BLOCK" sourceLabel="TEXTBOOK §12.07 + GUIDE pp.20-21" syllabusLabel="SYLLABUS 9.2" title="Choose by what controls repetition."><section className="da-grid three"><article className="da-card"><span>FOR</span><h3>Known count/range</h3><p>FOR Index ← 1 TO 10 … NEXT Index</p></article><article className="da-card"><span>WHILE</span><h3>Pre-condition</h3><p>May execute zero times; no DO keyword in the current guide.</p></article><article className="da-card"><span>REPEAT … UNTIL</span><h3>Post-condition</h3><p>Executes at least once; stops when condition becomes TRUE.</p></article></section></Slide> },
    { time: "6 min", focus: "Compose Boolean conditions with correct comparison and precedence.", prompt: "Students evaluate each condition for boundary values 12 and 18.", source: "Coursebook 12.06 printed pp.188-191; Pseudocode Guide p.16; syllabus 9.2 logic statements.", content: <Slide number="06" eyebrow="LOGIC DEFINES THE DECISION" sourceLabel="TEXTBOOK §12.06 + GUIDE p.16" syllabusLabel="SYLLABUS 9.2" title="Comparisons produce Boolean values; logic combines them."><section className="da-grid three"><article className="da-card"><span>AND</span><p>both conditions must be TRUE: Age &gt;= 12 AND Age &lt;= 18</p></article><article className="da-card"><span>OR</span><p>at least one is TRUE: Day = 'S' OR Day = 'U'</p></article><article className="da-card"><span>NOT</span><p>invert a Boolean: NOT GameOver</p></article></section><p className="da-warning">Use = for comparison and ← for assignment. Add parentheses when a compound condition could be misread.</p></Slide> },
    { time: "6 min", focus: "Teach standard flowchart symbols and branch labelling.", prompt: "Students name the symbol, action and corresponding pseudocode role.", source: "Coursebook 12.03 printed pp.182-184; syllabus 9.2 flowcharts.", content: <Slide number="07" eyebrow="FLOWCHART GRAMMAR" sourceLabel="TEXTBOOK §12.03 · pp.182-184" syllabusLabel="SYLLABUS 9.2" title="Shape carries meaning; arrows carry control."><section className="da-symbols"><article><div className="da-symbol oval"><span>START</span></div><h3>Terminal</h3><p>Start / End</p></article><article><div className="da-symbol io"><span>INPUT</span></div><h3>Input / output</h3><p>read or display data</p></article><article><div className="da-symbol"><span>PROCESS</span></div><h3>Process</h3><p>calculate / assign</p></article><article><div className="da-symbol diamond"><span>?</span></div><h3>Decision</h3><p>label TRUE/FALSE branches</p></article></section></Slide> },
    { time: "7 min", focus: "Translate one validation-and-selection task into current pseudocode.", prompt: "Students identify the loop-back arrow before reading the code.", source: "Coursebook 12.03, 12.06-12.07; Pseudocode Guide pp.15,18,20.", content: <Slide number="08" eyebrow="WORKED TRANSLATION · VALID MARK" sourceLabel="TEXTBOOK CH.12 + CURRENT GUIDE" syllabusLabel="SYLLABUS 9.2" title="Input at least once; stop when valid; then choose an output."><pre className="da-code">REPEAT{"\n"}   OUTPUT "Enter mark from 0 to 100"{"\n"}   INPUT Mark{"\n"}UNTIL Mark &gt;= 0 AND Mark &lt;= 100{"\n"}IF Mark &gt;= 50 THEN{"\n"}   OUTPUT "Pass"{"\n"}ELSE{"\n"}   OUTPUT "Retry"{"\n"}ENDIF</pre><p className="da-note">Equivalent flowchart: I/O → decision “valid?” → false loop back; true continues to decision “Mark ≥ 50?”.</p></Slide> },
    { time: "6 min", focus: "Repair high-frequency translation and legacy-syntax mistakes.", prompt: "Students state the effect of each error, not just the correction.", source: "Coursebook Chapter 12 corrected using Pseudocode Guide 2027-2029.", content: <Slide number="09" eyebrow="MISCONCEPTION + SYNTAX AUDIT" sourceLabel="TEXTBOOK CH.12 · UPDATED" syllabusLabel="SYLLABUS 9.2" title="A correct idea can still be represented incorrectly."><section className="da-compare"><div><span>ERROR</span><span>CORRECTION</span><span>EFFECT</span></div><div><b>WHILE Valid = FALSE DO</b><span>WHILE Valid = FALSE</span><span>current guide has no DO keyword</span></div><div><b>INPUT outside retry loop</b><span>place prompt/input inside loop</span><span>value can change each iteration</span></div><div><b>unlabelled decision branches</b><span>label TRUE/FALSE or Yes/No</span><span>path meaning is unambiguous</span></div><div><b>loop arrow bypasses update</b><span>route through update then test</span><span>prevents non-termination</span></div></section></Slide> },
    { time: "6 min", focus: "Guide a full structured-English-to-pseudocode conversion.", prompt: "Pairs translate a ticket discount rule and validate quantity.", source: "Syllabus 9.2 translation; Coursebook 12.03, 12.06-12.07.", content: <Slide number="10" eyebrow="GUIDED TRANSLATION · TICKETS" sourceLabel="TEXTBOOK CH.12 · APPLICATION" syllabusLabel="SYLLABUS 9.2" title="Preserve every decision, repetition and output."><section className="da-refine"><div><b>ENGLISH</b><span>Input quantity until 1–8. Calculate subtotal. If member, reduce by 10%. Output total.</span></div><div><b>CONTROL</b><span>post-condition iteration → sequence calculation → selection → output</span></div><div><b>CHECK</b><span>same condition boundaries, same formula and exactly one final total</span></div></section><p className="da-note">Students now write the pseudocode and sketch the decision/loop arrows; compare logic rather than page layout.</p></Slide> },
    { time: "7 min", focus: "Teach an eight-point algorithm audit from a published game question.", prompt: "Students turn the natural-language requirement into a checklist before coding.", source: "9618/21 M/J 2025 Q3 published mark scheme; syllabus 9.2.", content: <Slide number="11" eyebrow="EXAM METHOD · REQUIREMENT CHECKLIST" sourceLabel="9618/21 M/J 2025 · Q3" syllabusLabel="SYLLABUS 9.2 — PAPER 2" title="One visible requirement → one testable code feature."><section className="da-grid four"><article className="da-card"><span>SETUP</span><p>declare identifiers; generate 1–100 integer</p></article><article className="da-card"><span>LOOP</span><p>condition-controlled; prompt/input inside</p></article><article className="da-card"><span>FEEDBACK</span><p>separate too-high and too-low decisions</p></article><article className="da-card"><span>FINISH</span><p>terminate when equal; output success</p></article></section></Slide> },
    { time: "8 min", focus: "Attempt the published guessing-game algorithm.", prompt: "Students annotate requirements, then write for five uninterrupted minutes.", source: "Adapted from 9618/21 M/J 2025 Q3, checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 8 MARKS" sourceLabel="9618/21 M/J 2025 · Q3" syllabusLabel="SYLLABUS 9.2 — PAPER 2" title="Guess a secret integer from 1 to 100." className="slide--da-paper"><section className="da-paper-grid three"><article><span>SECRET</span><p>generate integer in inclusive range 1–100</p></article><article><span>ATTEMPTS</span><p>prompt/input repeatedly until correct</p></article><article><span>FEEDBACK</span><p>too high, too low, then correct</p></article></section><ExamReveal><p>Use declarations; Secret ← INT(RAND(100)) + 1; a condition-controlled loop with prompt and INPUT inside; IF branches for Guess &gt; Secret and Guess &lt; Secret; stop when Guess = Secret; output a final correct/success message.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [8].</small></Slide> },
    { time: "8 min", focus: "Debrief the mark scheme and translate its control flow.", prompt: "Students draw the loop-back point and two selection paths from their own code.", source: "9618/21 M/J 2025 Q3 mark scheme; syllabus 9.2 flowchart/pseudocode translation.", content: <Slide number="13" eyebrow="MARK-SCHEME DEBRIEF · DRAW THE FLOW" sourceLabel="9618/21 M/J 2025 · Q3" syllabusLabel="SYLLABUS 9.2 — PAPER 2" title="Does the diagram preserve every path and repeat point?" className="slide--da-paper"><section className="da-flow"><span>GENERATE<br />SECRET</span><i>→</i><span>INPUT<br />GUESS</span><i>→</i><span>HIGH / LOW /<br />EQUAL?</span><i>↺</i><span>REPEAT OR<br />OUTPUT CORRECT</span></section><ExamReveal><p>The input must be reached on every new attempt. High and low paths output feedback and return to input. The equal path leaves the repetition and reaches the final success output. Branch labels and arrow directions must be unambiguous.</p></ExamReveal><small className="da-source-line">Conversion practice based on the same published problem; no new mark allocation claimed.</small></Slide> },
    { time: "5 min", focus: "Retrieve construct, logic and representation together.", prompt: "Teacher states a behaviour; students name construct, condition and flowchart shape.", source: "Syllabus 9.2 synthesis; Coursebook 12.03, 12.05-12.07; current guide.", content: <Slide number="14" eyebrow="MIXED RETRIEVAL" sourceLabel="TEXTBOOK CH.12 · REVIEW" syllabusLabel="SYLLABUS 9.2" title="Order · choose · repeat · translate."><section className="da-flow"><span>SEQUENCE<br />RECTANGLES</span><i>→</i><span>SELECTION<br />DIAMOND</span><i>→</i><span>ITERATION<br />LOOP-BACK</span><i>→</i><span>AND · OR · NOT<br />CONDITIONS</span></section></Slide> },
    { time: "4 min", focus: "Close with three short construction checks.", prompt: "Collect answers; use any loop misconceptions to open Lesson 44.", source: "Syllabus 9.2 checkpoint; Coursebook Chapter 12 sequence.", content: <Slide number="15" eyebrow="EXIT TICKET · NEXT: REFINEMENT" sourceLabel="TEXTBOOK CH.12 · pp.184-198" syllabusLabel="SYLLABUS 9.2" title="Three questions before refining a full solution."><section className="da-exit"><article><span>SELECT</span><p>Which construct chooses exactly one path?</p></article><article><span>REPEAT</span><p>Why must a loop change a tested value?</p></article><article><span>TRANSLATE</span><p>Where does a false decision arrow reconnect?</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="43" slides={slides} homework={<HomeworkSheet lessonNumber="43" title="Logic and the Three Basic Constructs" marks={30} minutes={45} syllabusLabel="SYLLABUS 9.2 · PAPER 2" sourceLabel="TEXTBOOK CH.12 · pp.184-198 + PSEUDOCODE GUIDE + PAPER 2" instructions="Preserve the same logic across structured English, flowchart and pseudocode. Use only current pseudocode syntax, label every decision branch and check that repetition can terminate." sections={homeworkSections} challenge={{ id: "l43-challenge", prompt: <p><Mark>CHALLENGE</Mark> Explain how a post-condition loop and a pre-condition loop could implement the same validation task, and state the extra setup one may need.</p>, answer: <p>REPEAT…UNTIL naturally inputs before testing, so it runs at least once. WHILE tests before the body; it may need an initial sentinel/invalid value or an input before the loop so the condition is defined. Both can repeat until the same validity rule is satisfied if the condition direction and updates are correct.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 9.2, Coursebook Chapter 12 printed pp.184-198 (PDF pp.191-205), the official 2027-2029 Pseudocode Guide and published Paper 2 question/mark scheme." sourceDetail="Core: sequence, selection, iteration, logic statements, standard flowchart symbols, and translation between structured English, flowchart and pseudocode. Authentic Paper 2 anchor: 9618/21 M/J 2025 Q3 [8]. Array, file, search/sort and formal module algorithms remain Chapters 10-11." />;
}
