"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l28-reveal-${id}`;
  return <div className="ss-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className={visible ? "ss-reveal__panel visible" : "ss-reveal__panel"} hidden={!visible}>{children}</div></div>;
}

function IDEMock({ prompt = false, error = false, debug = false }: { prompt?: boolean; error?: boolean; debug?: boolean }) {
  return <div className="ss-ide-shell" role="img" aria-label="Stylised integrated development environment showing source code and programming support panels"><div className="ss-ide-topbar"><span>student-program.py · IDE</span><span>● RUN <i /></span></div><div className="ss-ide-body"><div className="ss-ide-gutter"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span></div><div className="ss-code-editor"><code><span className="kw">PROCEDURE</span> CalculateTotal()</code><code>&nbsp;&nbsp;Total ← 0</code><code>&nbsp;&nbsp;<span className="kw">FOR</span> Index ← 1 <span className="kw">TO</span> 5</code><code>&nbsp;&nbsp;&nbsp;&nbsp;Total ← Total + Price[Index]</code><code className={error ? "err" : ""}>&nbsp;&nbsp;<span className="kw">NEXT</span> Index</code><code>&nbsp;&nbsp;OUTPUT <span className="str">&quot;Total: &quot;</span>, Total</code>{prompt && <div className="ss-prompt-pop"><b>Price[ ]</b>Available identifier · ARRAY OF REAL</div>}</div><aside className="ss-ide-panel"><b>{debug ? "DEBUG / LOCALS" : error ? "PROBLEMS" : "OUTLINE"}</b>{debug ? <><p>Index = 3</p><p>Total = 18.50</p><p>Price[3] = 7.25</p></> : error ? <><p>Line 5: block terminator does not match the current structure.</p><p>1 problem detected.</p></> : <><p>CalculateTotal()</p><p>Variables</p><p>Output</p></>}</aside></div></div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "IDE feature families", subtitle: "Name the feature and explain its benefit", marks: 10,
    questions: [
      { id: "l28-1", marks: 2, lines: 2, prompt: <><b>Define an Integrated Development Environment (IDE).</b></>, answer: <p>An IDE is one software environment that integrates tools to enter/edit, translate/run, test and debug program source code. <em>[1 integrated environment; 1 relevant tools]</em></p> },
      { id: "l28-2", marks: 4, lines: 4, prompt: <><b>Describe two presentation features of an IDE and give one benefit of each.</b></>, answer: <p>Examples: <strong>prettyprinting/automatic indentation or formatting</strong> makes structure easier to read and errors easier to spot; <strong>syntax colouring</strong> distinguishes language elements; <strong>expand/collapse code blocks</strong> hides detail and reduces scrolling. Award feature plus matching benefit for each. <em>[4]</em></p> },
      { id: "l28-3", marks: 4, lines: 4, prompt: <><b>Contrast a context-sensitive prompt with a dynamic syntax check.</b></>, answer: <p>A context-sensitive prompt predicts valid keywords/identifiers or gives help appropriate to the current insertion point, helping the programmer enter code. A dynamic syntax check analyses code while it is typed and highlights/reports invalid syntax, helping locate errors early. <em>[2 each]</em></p> },
    ],
  },
  {
    code: "B", title: "Debugging in the IDE", subtitle: "Use breakpoints, stepping and variable inspection", marks: 10,
    questions: [
      { id: "l28-4", marks: 3, lines: 3, prompt: <><b>Explain how a breakpoint helps investigate a logic error.</b></>, answer: <p>The programmer marks a chosen source line; execution runs normally until that point and then pauses; the programmer can inspect state or step through the suspicious section rather than tracing from the start. <em>[3]</em></p> },
      { id: "l28-5", marks: 4, lines: 4, prompt: <><b>A loop produces the wrong total. Explain how single stepping and a variable watch can locate the cause.</b></>, answer: <p>Execute one statement at a time through each iteration; display the current values of the total, index and input value; compare each value with the expected result; identify the first statement/iteration where the value becomes incorrect. <em>[4]</em></p> },
      { id: "l28-6", marks: 3, lines: 3, prompt: <><b>Name the most useful IDE feature for each need:</b><p>(i) reduce scrolling in a long procedure; (ii) list identifiers valid at the cursor; (iii) stop just before a faulty calculation.</p></>, answer: <p>(i) <strong>expand/collapse code blocks</strong>; (ii) <strong>context-sensitive prompts/auto-completion</strong>; (iii) <strong>breakpoint</strong>. <em>[1 each]</em></p> },
    ],
  },
  {
    code: "C", title: "Paper 1 + Chapter 5 consolidation", subtitle: "Keep IDE categories precise and connect the system-software chain", marks: 10,
    questions: [
      { id: "l28-7", marks: 2, lines: 2, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Identify two presentation features in a typical IDE.</b><p>Adapted from 9618/11 O/N 2025 Q5(c). [2]</p></>, answer: <p>Any two published answers: <strong>prettyprint</strong>; <strong>expanding and collapsing code blocks</strong>; <strong>automatic/smart indentation or formatting</strong>. <em>[2]</em></p> },
      { id: "l28-8", marks: 6, lines: 5, prompt: <><b>A student writes, tests and distributes a file-compression program.</b><p>Explain the role of (i) the OS, (ii) a program library/DLL and (iii) a language translator in this process.</p></>, answer: <p><strong>OS:</strong> supplies the interface and manages memory, files, hardware and processes while the program is developed/run. <strong>Library/DLL:</strong> supplies a reusable tested compression routine that can be linked/called. <strong>Translator:</strong> an interpreter can support incremental testing, while a compiler can produce the final executable. <em>[2 each]</em></p> },
      { id: "l28-9", marks: 2, lines: 3, prompt: <><b>A syntax check reports no errors, but the program calculates the wrong answer.</b><p>Name two IDE debugging features that should be used next.</p></>, answer: <p>Any two of <strong>breakpoints</strong>, <strong>single stepping</strong>, and <strong>variable watch/report window</strong>. <em>[2]</em></p> },
    ],
  },
];

export default function Lesson28Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame an IDE as a coordinated workspace for the full edit-run-debug loop.", prompt: "Ask which separate tools the class has already used that an IDE brings together.", source: "Syllabus 5.2; Coursebook Chapter 8 printed pp.129-132.", content: <Slide number="01" eyebrow="CHAPTER 5 · SYSTEM SOFTWARE" sourceLabel="TEXTBOOK CH.8 · pp.129-132" syllabusLabel="SYLLABUS 5.2" className="slide--ss-title"><section className="ss-title-grid"><div className="ss-title-copy"><span>LESSON 28 · 90 MINUTES</span><h1>See more.<br /><em>Debug faster.</em></h1><p>Use IDE coding, presentation and debugging features—then connect the complete system-software chapter.</p></div><div className="ss-title-visual"><div><b>1</b><span>WRITE + FORMAT</span></div><div><b>2</b><span>PROMPT + CHECK</span></div><div><b>3</b><span>RUN + PAUSE</span></div><div><b>4</b><span>STEP + INSPECT</span></div></div></section></Slide> },
    { time: "5 min", focus: "Define the IDE by integration and show its three main visible regions.", prompt: "Students identify editor, output/problem panel and controls in the mock-up.", source: "Coursebook 8.06 printed p.129; syllabus 5.2 IDE features.", content: <Slide number="02" eyebrow="WHAT IS AN IDE?" sourceLabel="TEXTBOOK p.129" syllabusLabel="SYLLABUS 5.2" title="One environment for the development cycle."><IDEMock /><p className="ss-note">An <strong>Integrated Development Environment</strong> combines source editing with tools to translate/run, test and debug a program.</p></Slide> },
    { time: "5 min", focus: "Organise features by function to prevent category errors in Paper 1 answers.", prompt: "Where would automatic indentation belong: coding, presentation or debugging?", source: "Syllabus 5.2 feature categories; Coursebook pp.129-131.", content: <Slide number="03" eyebrow="FEATURE FAMILIES" sourceLabel="TEXTBOOK pp.129-131" syllabusLabel="SYLLABUS 5.2" title="Name the feature family before the example."><section className="ss-card-grid three"><article><span>CODING SUPPORT</span><b>Enter valid code</b><p>context-sensitive prompts and auto-completion</p></article><article><span>PRESENTATION + CHECKS</span><b>Read and correct code</b><p>prettyprint, indentation, folding and dynamic syntax checks</p></article><article><span>DEBUGGING</span><b>Investigate behaviour</b><p>breakpoints, single stepping and variable inspection</p></article></section><p className="ss-warning">A useful IDE feature is not automatically a <strong>presentation</strong> feature. Match the command word&apos;s category.</p></Slide> },
    { time: "6 min", focus: "Explain prettyprinting through visible transformations rather than a vague claim that code looks better.", prompt: "Students identify three presentation changes in the editor.", source: "Coursebook p.129 prettyprinting; 9618/11 O/N 2025 Q5(c).", content: <Slide number="04" eyebrow="PRETTYPRINTING" sourceLabel="TEXTBOOK p.129" syllabusLabel="SYLLABUS 5.2" title="Make program structure visible."><IDEMock /><section className="ss-card-grid four"><article><span>INDENT</span><p>align nested blocks</p></article><article><span>COLOUR</span><p>distinguish keywords, strings and comments</p></article><article><span>FORMAT</span><p>apply consistent spacing/layout</p></article><article><span>BENEFIT</span><p>read and inspect structure faster</p></article></section></Slide> },
    { time: "5 min", focus: "Describe context-sensitive help as a prediction based on the current insertion point.", prompt: "Why is a list of every language keyword less useful than this prompt?", source: "Coursebook pp.129-130 context-sensitive prompts; syllabus 5.2.", content: <Slide number="05" eyebrow="CONTEXT-SENSITIVE PROMPTS" sourceLabel="TEXTBOOK pp.129-130" syllabusLabel="SYLLABUS 5.2" title="Offer valid choices for this exact point in the code."><IDEMock prompt /><p className="ss-note">The IDE can suggest suitable keywords, identifiers or routine parameters and may explain the selected construct. It reduces typing and recall errors; the programmer still chooses.</p></Slide> },
    { time: "5 min", focus: "Separate syntax detection from logic debugging.", prompt: "Would this feature detect a valid statement that uses the wrong formula?", source: "Coursebook p.130 dynamic syntax checks; syllabus 5.2.", content: <Slide number="06" eyebrow="DYNAMIC SYNTAX CHECKS" sourceLabel="TEXTBOOK p.130" syllabusLabel="SYLLABUS 5.2" title="Detect invalid language structure while code is entered."><IDEMock error /><p className="ss-note">The editor analyses code as it is typed, highlights the location and reports/explains the syntax problem. A logically wrong but syntactically valid formula can still pass.</p></Slide> },
    { time: "6 min", focus: "Show how code folding changes visibility without changing the program.", prompt: "What remains in the source file when a block is collapsed?", source: "Coursebook p.130 expanding and collapsing code blocks; syllabus 5.2.", content: <Slide number="07" eyebrow="EXPAND + COLLAPSE" sourceLabel="TEXTBOOK p.130" syllabusLabel="SYLLABUS 5.2" title="Hide detail—not code."><section className="ss-split"><article><span className="ss-kicker">EXPANDED</span><h3>− CalculateTotal()</h3><p>All statements are visible for editing and tracing.</p><div className="ss-folder-tree"><span>FOR each item</span><span>calculate subtotal</span><span>apply discount</span></div></article><article><span className="ss-kicker">COLLAPSED</span><h3>+ CalculateTotal() …</h3><p>The block remains intact but is hidden, reducing scrolling and helping the programmer focus on structure.</p></article></section></Slide> },
    { time: "6 min", focus: "Model breakpoints and single stepping as control over execution, not correction by the IDE.", prompt: "Where should a breakpoint be placed if the total first becomes wrong inside a loop?", source: "Coursebook pp.130-131 debugging and breakpoints; syllabus 5.2.", content: <Slide number="08" eyebrow="BREAKPOINT + SINGLE STEP" sourceLabel="TEXTBOOK pp.130-131" syllabusLabel="SYLLABUS 5.2" title="Pause before the fault; advance one statement at a time."><section className="ss-debug-timeline"><span>RUN<br />NORMALLY</span><i>→</i><span>BREAKPOINT<br />PAUSE</span><i>→</i><span>STEP<br />ONE LINE</span><i>→</i><span>COMPARE<br />STATE</span></section><p className="ss-note"><strong>Breakpoint:</strong> a selected stopping point. <strong>Single stepping:</strong> execute the next statement/instruction, then pause again.</p></Slide> },
    { time: "5 min", focus: "Use variable inspection to locate the first incorrect state transition.", prompt: "Which three values should be watched while diagnosing the example loop?", source: "Coursebook p.131 debug control and local-variable display; syllabus 5.2.", content: <Slide number="09" eyebrow="VARIABLE WATCH / REPORT WINDOW" sourceLabel="TEXTBOOK p.131" syllabusLabel="SYLLABUS 5.2" title="Observe what the program knows at the pause."><IDEMock debug /><p className="ss-note">A watch/report panel displays current values. Compare them with expected values after each step; the first divergence points toward the faulty statement or input.</p></Slide> },
    { time: "7 min", focus: "Require a feature-action-benefit chain rather than feature-name dumping.", prompt: "Pairs select the strongest feature for each developer need and justify it.", source: "Coursebook pp.129-131 feature applications; syllabus 5.2.", content: <Slide number="10" eyebrow="FEATURE → ACTION → BENEFIT" sourceLabel="TEXTBOOK pp.129-131" syllabusLabel="SYLLABUS 5.2" title="Choose from the programmer's problem."><section className="ss-card-grid four"><article><span>LONG FILE</span><b>Code folding</b><p>hide blocks → less scrolling</p></article><article><span>UNKNOWN NAME</span><b>Context prompt</b><p>suggest identifiers → fewer entry errors</p></article><article><span>INVALID GRAMMAR</span><b>Syntax check</b><p>highlight early → quicker correction</p></article><article><span>WRONG VALUE</span><b>Step + watch</b><p>trace state → locate logic error</p></article></section><p className="ss-note">For “describe”, include <strong>what the feature does</strong>. For “explain a benefit”, connect that action to saved time, clarity or fault location.</p></Slide> },
    { time: "9 min", focus: "Practise the precise presentation-feature category from the 2025 paper.", prompt: "Students write two answers in 45 seconds; reject debugging features even if they are valid IDE features.", source: "Adapted from 9618/11 O/N 2025 Q5(c), checked against the published mark scheme.", content: <Slide number="11" eyebrow="PAST PAPER PRACTICE · 2 MARKS" sourceLabel="9618/11 O/N 2025 · Q5(c)" syllabusLabel="SYLLABUS 5.2 — EXAM PRACTICE" title="Identify two presentation features in a typical IDE." className="slide--ss-paper"><section className="ss-paper-grid"><article><span>WRITE 1</span><p>A feature that automatically improves code layout.</p></article><article><span>WRITE 2</span><p>A feature that hides or reveals a block without deleting it.</p></article></section><Reveal id="paper-presentation" visible={revealed.has("paper-presentation")} onToggle={toggleReveal}><p>Published answers include <strong>prettyprint</strong>, <strong>expanding/collapsing code blocks</strong>, and <strong>automatic/smart indentation or formatting</strong>. Any two score.</p></Reveal><small>Adapted from 9618/11 O/N 2025 Q5(c).</small></Slide> },
    { time: "9 min", focus: "Expose common classification traps by contrasting presentation, coding support and debugging.", prompt: "Students move each tile to a family verbally and defend one disputed choice.", source: "Follow-up classification derived from 9618/11 O/N 2025 Q5(c) and syllabus 5.2.", content: <Slide number="12" eyebrow="PAST-PAPER PRECISION" sourceLabel="9618/11 O/N 2025 · Q5(c)" syllabusLabel="SYLLABUS 5.2 — EXAM PRACTICE" title="Useful feature—wrong category—zero mark."><section className="ss-card-grid five"><article><span>PRETTYPRINT</span><b>Presentation</b><p>formats layout</p></article><article><span>CODE FOLDING</span><b>Presentation</b><p>controls visible detail</p></article><article><span>CONTEXT PROMPT</span><b>Coding support</b><p>suggests valid entries</p></article><article><span>SYNTAX CHECK</span><b>Error detection</b><p>flags invalid syntax</p></article><article><span>BREAKPOINT</span><b>Debugging</b><p>pauses execution</p></article></section><Reveal id="category" visible={revealed.has("category")} onToggle={toggleReveal}><p>For the cited two-mark presentation question, the first two—or automatic indentation/formatting—fit the published mark scheme. The others remain valid IDE features but do not answer that category.</p></Reveal></Slide> },
    { time: "8 min", focus: "Rebuild the complete Chapter 5 chain across Lessons 25-28.", prompt: "Students explain how the four blocks cooperate during one software project.", source: "Coursebook Chapter 8 summary printed p.131 and exam-style questions p.132; syllabus 5.1-5.2.", content: <Slide number="13" eyebrow="CHAPTER 5 · COMPLETE MAP" sourceLabel="TEXTBOOK pp.131-132" syllabusLabel="SYLLABUS 5.1–5.2" title="One development story; four system-software roles."><section className="ss-chapter-map"><article><span>LESSON 25</span><h3>Operating system</h3><p>provides the platform and manages memory, files, security, hardware and processes</p></article><article><span>LESSON 26</span><h3>Utilities + libraries</h3><p>maintain the system and supply reusable routines, including DLLs</p></article><article><span>LESSON 27</span><h3>Translators</h3><p>convert assembly or high-level source into executable actions</p></article><article><span>LESSON 28</span><h3>IDE</h3><p>integrates tools for writing, presenting, checking and debugging code</p></article></section></Slide> },
    { time: "7 min", focus: "Use a short mixed sprint to distinguish adjacent Chapter 5 concepts.", prompt: "Students answer all four before revealing; one mark for the term and one for precise explanation where asked.", source: "Syllabus 5.1-5.2 consolidation; 2025 Paper 1 command-word patterns.", content: <Slide number="14" eyebrow="CHAPTER 5 EXAM SPRINT · 8 MARKS" sourceLabel="SYLLABUS + PAPER 1 STYLE" syllabusLabel="SYLLABUS 5.1–5.2" title="Name precisely. Explain causally." className="slide--ss-paper"><section className="ss-paper-grid three"><article><span>2 MARKS</span><p>Why is process management needed when three programs run?</p></article><article><span>2 MARKS</span><p>Name the utilities for bad sectors and a restorable copy.</p></article><article><span>4 MARKS</span><p>Explain how breakpoint + watch window help find a wrong total.</p></article></section><Reveal id="sprint" visible={revealed.has("sprint")} onToggle={toggleReveal}><p><strong>Process:</strong> schedule CPU/resources and resolve conflicts. <strong>Utilities:</strong> disk analysis/repair; backup. <strong>Debug:</strong> pause at the chosen point, inspect current variables, step through statements and identify the first incorrect value.</p></Reveal></Slide> },
    { time: "3 min", focus: "Close the chapter with a precise feature checklist and route to homework.", prompt: "Students name one presentation feature and one debugging pair from memory.", source: "Syllabus 5.1-5.2 completion check; Coursebook pp.121-132.", content: <Slide number="15" eyebrow="CHAPTER 5 · EXIT" sourceLabel="TEXTBOOK CH.8 · pp.121-132" syllabusLabel="SYLLABUS 5.1–5.2" title="Support the system. Support the programmer." className="slide--ss-exit"><section className="ss-exit-grid"><article><b>PRESENT</b><p>Prettyprint, automatic indentation and expand/collapse improve readable structure.</p></article><article><b>ASSIST</b><p>Context prompts and dynamic syntax checks improve code entry and early correction.</p></article><article><b>DEBUG</b><p>Breakpoints, single stepping and variable inspection expose runtime behaviour.</p></article></section><div className="ss-homework-callout"><b>HOMEWORK 28</b><span>30 marks · verified 2025 IDE anchor · Chapter 5 consolidation</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="28" slides={slides} homework={<HomeworkSheet lessonNumber="28" title="IDE Features and Chapter 5 Consolidation" marks={30} minutes={45} syllabusLabel="SYLLABUS 5.1–5.2" sourceLabel="TEXTBOOK CH.8 · pp.129-132 + PAPER 1" instructions="Match every IDE feature to the category requested and explain what it does before giving its benefit. The past-paper prompt is a concise adaptation checked against the published 2025 mark scheme." sections={homeworkSections} challenge={{ id: "l28-challenge", prompt: <p><Mark>CHALLENGE</Mark> A program is syntactically valid but gives the correct output for small inputs and the wrong output for large inputs. Design a three-step IDE debugging investigation.</p>, answer: <p>Set a breakpoint immediately before the calculation or loop where values change. Run a failing large input and inspect relevant variables in a watch/report window. Single-step through the calculation, comparing actual and expected values after each statement until the first divergence identifies the faulty condition, operation or boundary.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 5.1-5.2, Coursebook Chapter 8 printed pp.129-132, and the published 2025 Paper 1 question and mark scheme." sourceDetail="Core: describe IDE coding support, presentation, dynamic syntax checking and debugging features, then consolidate operating systems, utilities/libraries and translators. Authentic anchor: 9618/11 O/N 2025 Q5(c), whose published presentation-feature answers include prettyprint, expanding/collapsing code blocks and automatic/smart indentation or formatting. Brand-specific IDE operation and advanced debugger internals are outside this lesson." />;
}
