"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Think computationally", subtitle: "Purpose, essential detail and manageable sub-problems", marks: 10,
    questions: [
      { id: "l41-1", marks: 3, lines: 3, prompt: <><b>Define abstraction and explain one benefit.</b></>, answer: <p>Abstraction removes/ignores details that are unnecessary for the current purpose while preserving essential features. It reduces complexity, making a system easier to understand, model or solve and allowing attention to remain on relevant data/behaviour. <em>[3]</em></p> },
      { id: "l41-2", marks: 3, lines: 3, prompt: <><b>Define decomposition and explain how it supports program development.</b></>, answer: <p>Decomposition breaks a complex problem into smaller sub-problems. Each can become a coherent module/procedure/function concept, be designed and tested independently, and then be combined into the complete solution. <em>[3]</em></p> },
      { id: "l41-3", marks: 4, lines: 4, prompt: <><b>For a route-planning model, give two essential and two unnecessary details.</b></>, answer: <p>Essential examples: locations/stations, connections/roads, direction, distance/time/cost relevant to the selected route. Usually unnecessary for route finding: building colour, shop-window content, exact tree positions, decorative map texture. Credit depends on a stated purpose; a detail may change category if the purpose changes. <em>[4]</em></p> },
    ],
  },
  {
    code: "B", title: "Model and decompose", subtitle: "A school event booking system", marks: 10,
    questions: [
      { id: "l41-4", marks: 4, lines: 4, prompt: <><b>Produce an abstract model for booking a seat at a school event: list four essential data items.</b></>, answer: <p>Any four justified items: event identifier/date/time, customer/student identifier, seat or ticket category, number of tickets, availability/capacity, price, payment/booking status, contact information. Decorative poster colours or unrelated personal details are excluded. <em>[4]</em></p> },
      { id: "l41-5", marks: 4, lines: 4, prompt: <><b>Decompose the booking problem into four coherent sub-problems.</b></>, answer: <p>Examples: obtain/validate booking request; check event and seat availability; calculate cost; take/verify payment; create booking/update remaining capacity; issue confirmation; cancel/refund. Award four distinct, purpose-focused sub-problems. <em>[4]</em></p> },
      { id: "l41-6", marks: 2, lines: 2, prompt: <><b>Explain why “screen 1, screen 2, screen 3” is usually weaker decomposition than “check availability, calculate cost, record booking”.</b></>, answer: <p>The second set groups work by coherent responsibility/output, so each sub-problem can be designed, tested and reused independently; screens may mix several responsibilities and reflect interface layout rather than the underlying problem. <em>[2]</em></p> },
    ],
  },
  {
    code: "C", title: "Published Paper 2 thinking", subtitle: "Car hire and stock control", marks: 10,
    questions: [
      { id: "l41-7", marks: 5, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE · PAPER 2</Mark> <b>Explain abstraction for a car-hire model, give four essential data categories and two operations.</b><p>Adapted from 9618/21 O/N 2022 Q2(a)–(b). [3 + 2]</p></>, answer: <p>Abstraction filters unnecessary detail and keeps what is essential for the model. Data may include car details, customer details, hire start/return date or duration, and hire cost/payment data. Operations may include start/create/end/cancel a hire, check/update vehicle status, calculate cost or process payment. <em>[3 + 2]</em></p> },
      { id: "l41-8", marks: 3, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE · PAPER 2</Mark> <b>Explain how decomposition helps develop a stock-control solution.</b><p>Adapted from 9618/21 M/J 2025 Q1(c). [3]</p></>, answer: <p>Break stock control into smaller tasks such as receiving items, recording sales and checking reorder levels. These can become modules/procedures/functions and can be designed, tested and debugged separately before integration, making the complex solution easier to manage. <em>[3]</em></p> },
      { id: "l41-9", marks: 2, lines: 2, prompt: <><b>State one difference between decomposition and stepwise refinement.</b></>, answer: <p>Decomposition splits a problem horizontally into separate sub-problems/responsibilities; stepwise refinement repeatedly adds detail vertically to an initially broad step until it can be implemented. <em>[2]</em></p> },
    ],
  },
];

export default function Lesson41Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Demonstrate that useful detail depends on purpose.", prompt: "Show a journey, emergency-response and tourist purpose; ask what the same map must retain for each.", source: "Coursebook 12.01 printed pp.179-180; syllabus 9.1.", content: <Slide number="01" eyebrow="CHAPTER 9 · COMPUTATIONAL THINKING" sourceLabel="TEXTBOOK CH.12 · pp.179-180" syllabusLabel="SYLLABUS 9.1" className="da-title"><section className="da-title-grid"><div className="da-title-copy"><span>LESSON 41 · 90 MINUTES · PAPER 2</span><h1>Keep what matters.<br /><em>Break what remains.</em></h1><p>Use abstraction to build purpose-specific models and decomposition to turn complex problems into coherent, testable sub-problems.</p></div><div className="da-title-map"><div><b>A</b><span>DEFINE THE PURPOSE</span></div><div><b>−</b><span>REMOVE IRRELEVANT DETAIL</span></div><div><b>+</b><span>KEEP ESSENTIAL FEATURES</span></div><div><b>÷</b><span>DECOMPOSE INTO MODULE IDEAS</span></div></div></section></Slide> },
    { time: "5 min", focus: "Make the exact 9.1 scope and assessment component visible.", prompt: "Explain that Chapter 9 belongs to Paper 2; Paper 1 ends at Chapter 8.", source: "Syllabus 9.1 p.27 and assessment overview p.11; Coursebook 12.01 printed pp.179-180.", content: <Slide number="02" eyebrow="TEXTBOOK × SYLLABUS" sourceLabel="TEXTBOOK §12.01 · pp.179-180" syllabusLabel="SYLLABUS 9.1 · PAPER 2" title="Only two assessed computational-thinking skills here: abstraction and decomposition."><section className="da-grid four"><article className="da-card"><span>ABSTRACTION · NEED</span><p>complex real systems contain more detail than the task requires</p></article><article className="da-card"><span>ABSTRACTION · PURPOSE</span><p>produce a model containing only essential detail</p></article><article className="da-card"><span>DECOMPOSITION</span><p>break a problem into manageable sub-problems</p></article><article className="da-card"><span>MODULE CONCEPT</span><p>sub-problems can lead to procedures/functions; formal syntax comes later</p></article></section><p className="da-warning">The older textbook lists extra “strands”; the 2027 Chapter 9.1 requirements explicitly assess abstraction and decomposition.</p></Slide> },
    { time: "6 min", focus: "Define abstraction as a purposeful filtering decision.", prompt: "Students finish: irrelevant to which purpose?", source: "Coursebook 12.01 printed p.179; syllabus 9.1.", content: <Slide number="03" eyebrow="ABSTRACTION" sourceLabel="TEXTBOOK §12.01 · p.179" syllabusLabel="SYLLABUS 9.1" title="Remove unnecessary detail; preserve the features needed for the stated task."><section className="da-flow"><span>STATE THE<br />PURPOSE</span><i>→</i><span>LIST AVAILABLE<br />DETAIL</span><i>→</i><span>KEEP ESSENTIAL<br />FEATURES</span><i>→</i><span>BUILD A SMALLER<br />USABLE MODEL</span></section><p className="da-note">Benefits: reduced complexity, clearer reasoning, easier communication and a model that can be implemented or tested.</p></Slide> },
    { time: "6 min", focus: "Show that the same fact can be essential or irrelevant under different purposes.", prompt: "Classify each map feature for three users and defend the choice.", source: "Coursebook 12.01 route-map example printed p.179; syllabus 9.1 purpose of abstraction.", content: <Slide number="04" eyebrow="PURPOSE CHANGES THE MODEL" sourceLabel="TEXTBOOK §12.01 · MAP EXAMPLE" syllabusLabel="SYLLABUS 9.1" title="There is no context-free list of ‘unnecessary’ details."><table className="da-table"><thead><tr><th>DETAIL</th><th>FASTEST TRAIN ROUTE</th><th>WHEELCHAIR-ACCESSIBLE ROUTE</th><th>EMERGENCY EVACUATION</th></tr></thead><tbody><tr><td>station connections</td><td>essential</td><td>essential</td><td>sometimes</td></tr><tr><td>step-free access</td><td>optional</td><td><strong>essential</strong></td><td>essential</td></tr><tr><td>street/building exits</td><td>irrelevant</td><td>sometimes</td><td><strong>essential</strong></td></tr><tr><td>decorative building colour</td><td>irrelevant</td><td>irrelevant</td><td>irrelevant unless used as a landmark</td></tr></tbody></table></Slide> },
    { time: "6 min", focus: "Build an abstract model as data plus allowed behaviour.", prompt: "Ask what a car-hire system must know and do—but not how the car engine works.", source: "Coursebook 12.01 printed pp.179-180; 9618/21 O/N 2022 Q2.", content: <Slide number="05" eyebrow="AN ABSTRACT MODEL" sourceLabel="TEXTBOOK §12.01 + 9618/21 O/N 2022" syllabusLabel="SYLLABUS 9.1" title="A useful model states essential data, states and operations."><section className="da-grid three"><article className="da-card"><span>DATA</span><p>vehicle/customer identifiers, dates, price, availability</p></article><article className="da-card"><span>STATE</span><p>available, reserved, hired, returned, unavailable</p></article><article className="da-card"><span>OPERATIONS</span><p>create/cancel hire, calculate cost, update status, take payment</p></article></section><p className="da-warning">Paint chemistry, engine-part geometry and office decoration are real—but unnecessary for the booking purpose.</p></Slide> },
    { time: "6 min", focus: "Define decomposition by responsibility and output.", prompt: "Students break online checkout into sub-problems that each have a clear job.", source: "Coursebook 12.01 printed p.180; syllabus 9.1 decomposition.", content: <Slide number="06" eyebrow="DECOMPOSITION" sourceLabel="TEXTBOOK §12.01 · p.180" syllabusLabel="SYLLABUS 9.1" title="Split the problem into smaller, coherent sub-problems."><section className="da-grid four"><article className="da-card"><span>OBTAIN</span><p>capture and validate the request</p></article><article className="da-card"><span>CALCULATE</span><p>derive total, discount or route</p></article><article className="da-card"><span>DECIDE</span><p>check availability, rules or authorisation</p></article><article className="da-card"><span>RECORD / OUTPUT</span><p>update persistent state and communicate result</p></article></section><p className="da-note">Good sub-problems have a focused responsibility, identifiable inputs/outputs and limited overlap.</p></Slide> },
    { time: "6 min", focus: "Introduce modules only as a design destination, respecting the syllabus boundary.", prompt: "Which sub-problems return a value, and which perform an action?", source: "Syllabus 9.1 decomposition leads to procedure/function; Coursebook 12.01 and 12.09 concept only.", content: <Slide number="07" eyebrow="FROM SUB-PROBLEM TO MODULE IDEA" sourceLabel="TEXTBOOK §§12.01 + 12.09 · CONCEPT" syllabusLabel="SYLLABUS 9.1" title="A decomposition can suggest procedures and functions."><section className="da-grid two"><article className="da-card"><span>PROCEDURE IDEA</span><h3>Perform an action</h3><p>RecordBooking or DisplayReceipt may change data/output without being used as a value.</p></article><article className="da-card"><span>FUNCTION IDEA</span><h3>Return a value</h3><p>CalculateCost or IsAvailable can supply a result to the calling algorithm.</p></article></section><p className="da-warning">Formal headers, parameters, CALL syntax and local/global scope belong to Chapter 11.3—not this lesson.</p></Slide> },
    { time: "7 min", focus: "Work a purpose-specific abstraction and decomposition together.", prompt: "Students justify each retained data item, then map operations to sub-problems.", source: "Adapted teaching context from 9618/21 O/N 2022 Q2; syllabus 9.1.", content: <Slide number="08" eyebrow="WORKED MODEL · CAR HIRE" sourceLabel="TEXTBOOK §12.01 + PAPER 2 CONTEXT" syllabusLabel="SYLLABUS 9.1" title="Purpose: reserve, collect, return and charge for a vehicle."><section className="da-grid two"><article className="da-card"><span>ABSTRACT MODEL · KEEP</span><p>CarID/status/rate; CustomerID/licence; start/end dates; payment/total.</p><p><strong>Ignore:</strong> unrelated mechanical detail or showroom decoration.</p></article><article className="da-card"><span>DECOMPOSE · SOLVE</span><p>FindAvailableCar → RecordCustomer → CalculateHireCost → ProcessPayment → StartHire → EndHire.</p></article></section><p className="da-note">The model describes what matters; the decomposition describes which smaller responsibilities solve the whole task.</p></Slide> },
    { time: "6 min", focus: "Separate three related but different thinking moves.", prompt: "Match one classroom action to each concept.", source: "Syllabus 9.1 and 9.2; Coursebook 12.01 and 12.08.", content: <Slide number="09" eyebrow="DO NOT CONFUSE THE MOVES" sourceLabel="TEXTBOOK §§12.01 + 12.08" syllabusLabel="SYLLABUS 9.1–9.2" title="Filter, split or add detail?"><section className="da-compare"><div><span>SKILL</span><span>QUESTION IT ANSWERS</span><span>EXAMPLE</span></div><div><b>Abstraction</b><span>Which details matter for this purpose?</span><span>keep stations/connections; omit building texture</span></div><div><b>Decomposition</b><span>Which separate sub-problems make up the task?</span><span>availability, cost, payment, confirmation</span></div><div><b>Stepwise refinement</b><span>What smaller steps implement one broad step?</span><span>refine “calculate cost” into rate, days, discount, total</span></div></section><p className="da-note">Stepwise refinement is taught fully in Lesson 44.</p></Slide> },
    { time: "6 min", focus: "Guide a new abstraction/decomposition without code.", prompt: "Pairs model a school-lunch ordering system for one purpose: order and collect a meal.", source: "Syllabus 9.1 produce abstract model and use decomposition; Coursebook 12.01 method.", content: <Slide number="10" eyebrow="GUIDED CLINIC · SCHOOL LUNCH" sourceLabel="TEXTBOOK §12.01 · APPLICATION" syllabusLabel="SYLLABUS 9.1" title="Design the model before any pseudocode."><section className="da-flow"><span>PURPOSE:<br />ORDER + COLLECT</span><i>→</i><span>ESSENTIAL DATA:<br />WHO, MEAL, DATE</span><i>→</i><span>RULES:<br />STOCK + ALLERGY</span><i>→</i><span>SUB-PROBLEMS:<br />CHECK, PAY, RECORD</span></section><p className="da-warning">Do not collect extra personal data merely because it is available. Essential detail must be justified by the purpose.</p></Slide> },
    { time: "7 min", focus: "Teach mark-scoring contextualisation for computational-thinking explanations.", prompt: "Repair a generic definition by applying it to car hire.", source: "9618/21 O/N 2022 Q2 and 9618/21 M/J 2025 Q1(c) mark schemes.", content: <Slide number="11" eyebrow="EXAM METHOD · DEFINE + APPLY" sourceLabel="9618/21 O/N 2022 + M/J 2025" syllabusLabel="SYLLABUS 9.1 — PAPER 2" title="One definition; several context-specific details."><section className="da-grid three"><article className="da-card"><span>1 · DEFINE</span><p>state the general process accurately</p></article><article className="da-card"><span>2 · APPLY</span><p>name essential data or actual sub-problems in the scenario</p></article><article className="da-card"><span>3 · BENEFIT</span><p>show reduced complexity, independent design/testing or clearer model</p></article></section><p className="da-warning">Answers detached from the given system can be capped. Reuse the scenario&apos;s nouns and actions.</p></Slide> },
    { time: "8 min", focus: "Attempt a published abstraction/application item.", prompt: "Students list four data categories and two operations only after stating the abstraction rule.", source: "Adapted from 9618/21 O/N 2022 Q2(a)-Q2(b), checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 5 MARKS" sourceLabel="9618/21 O/N 2022 · Q2(a)–(b)" syllabusLabel="SYLLABUS 9.1 — PAPER 2" title="Build an abstract car-hire model." className="slide--da-paper"><section className="da-paper-grid three"><article><span>ABSTRACTION</span><p>filter unnecessary detail; retain essential features</p></article><article><span>DATA</span><p>car/customer, hire dates/duration, cost/payment</p></article><article><span>OPERATIONS</span><p>start/end/cancel hire, status, calculate/process</p></article></section><ExamReveal><p>State that abstraction keeps only purpose-essential detail. Valid data categories include car and customer details, start/return dates or duration and hire cost/payment. Valid operations include creating, starting, ending or cancelling a hire; checking/updating status; calculating cost or processing payment.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [3 + 2].</small></Slide> },
    { time: "8 min", focus: "Attempt a published decomposition explanation.", prompt: "Students use stock-control nouns and give one development benefit.", source: "Adapted from 9618/21 M/J 2025 Q1(c), checked against published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 3 MARKS" sourceLabel="9618/21 M/J 2025 · Q1(c)" syllabusLabel="SYLLABUS 9.1 — PAPER 2" title="Explain decomposition for stock control." className="slide--da-paper"><section className="da-paper-grid"><article><span>BREAK DOWN</span><p>receiving stock, recording sales, checking reorder levels</p></article><article><span>DEVELOP</span><p>modules can be designed, tested and debugged independently</p></article></section><ExamReveal><p>Decomposition breaks the whole stock-control problem into smaller tasks such as adding deliveries, deducting sales and identifying low stock. These can form modules/procedures/functions and can be built, tested and debugged separately before integration.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [3].</small></Slide> },
    { time: "5 min", focus: "Retrieve both skills through a single unfamiliar system.", prompt: "Use a cinema booking system; alternate keep/omit/sub-problem responses.", source: "Syllabus 9.1 complete synthesis; Coursebook 12.01.", content: <Slide number="14" eyebrow="MIXED RETRIEVAL" sourceLabel="TEXTBOOK §12.01 · REVIEW" syllabusLabel="SYLLABUS 9.1" title="Purpose → abstraction → decomposition."><section className="da-flow"><span>STATE THE<br />PURPOSE</span><i>→</i><span>KEEP ESSENTIAL<br />DATA + BEHAVIOUR</span><i>→</i><span>OMIT IRRELEVANT<br />DETAIL</span><i>→</i><span>DIVIDE INTO<br />COHERENT TASKS</span></section></Slide> },
    { time: "4 min", focus: "Close 9.1 and prepare for algorithm representations.", prompt: "Collect one applied sentence per card.", source: "Syllabus 9.1 checkpoint; Coursebook Chapter 12 sequence.", content: <Slide number="15" eyebrow="EXIT TICKET · NEXT: ALGORITHMS" sourceLabel="TEXTBOOK CH.12 · pp.179-180" syllabusLabel="SYLLABUS 9.1" title="Three choices before writing steps."><section className="da-exit"><article><span>PURPOSE</span><p>What exact task is the model for?</p></article><article><span>ABSTRACT</span><p>Which detail is essential—and why?</p></article><article><span>DECOMPOSE</span><p>Which sub-problem has a clear responsibility?</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="41" slides={slides} homework={<HomeworkSheet lessonNumber="41" title="Computational Thinking: Abstraction and Decomposition" marks={30} minutes={45} syllabusLabel="SYLLABUS 9.1 · PAPER 2" sourceLabel="TEXTBOOK CH.12 · pp.179-180 + PAPER 2" instructions="Always state the model's purpose. Justify why a detail is essential or unnecessary, and name scenario-specific sub-problems rather than repeating a generic definition." sections={homeworkSections} challenge={{ id: "l41-challenge", prompt: <p><Mark>CHALLENGE</Mark> Give one detail that is irrelevant to a standard route planner but essential to an emergency-access route planner, and explain the change.</p>, answer: <p>Road width or vehicle-height restrictions may be irrelevant to a pedestrian/standard shortest-route model but essential when routing a fire engine, because an otherwise short path may be physically inaccessible to the emergency vehicle.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 9.1, Coursebook Chapter 12 printed pp.179-180 (PDF pp.186-187) and published Paper 2 questions/mark schemes." sourceDetail="Core: need, purpose and benefits of abstraction; purpose-specific abstract models; decomposition into sub-problems leading to the concept of procedures/functions. Authentic Paper 2 anchors: 9618/21 O/N 2022 Q2(a)-Q2(b) [5] and 9618/21 M/J 2025 Q1(c) [3]. Formal module syntax remains Chapter 11.3." />;
}
