"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

type GateName = "NOT" | "AND" | "OR" | "NAND" | "NOR" | "XOR";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l15-reveal-${id}`;
  return <div className="c3-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className={visible ? "c3-reveal__panel visible" : "c3-reveal__panel"} hidden={!visible}>{children}</div></div>;
}

function GateIcon({ name }: { name: GateName }) {
  const lower = name.toLowerCase();
  return <div className={`logic-gate logic-gate--${lower}`} role="img" aria-label={`${name} logic gate symbol`}><div className="logic-gate__drawing"><i className="logic-input logic-input--1" />{name !== "NOT" && <i className="logic-input logic-input--2" />}<span className="logic-shape" /><i className="logic-output" /></div><b>{name}</b></div>;
}

function MiniTruth({ name, outputs }: { name: GateName; outputs: string }) {
  return <article className="logic-truth-card"><GateIcon name={name} /><p><span>AB</span><span>00</span><span>01</span><span>10</span><span>11</span></p><p><b>X</b>{outputs.split("").map((value, index) => <strong key={`${name}-${index}`}>{value}</strong>)}</p></article>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Gate functions", subtitle: "Use exact input conditions", marks: 10,
    questions: [
      { id: "l15-1", marks: 6, lines: 5, prompt: <><b>Define the output condition for each gate.</b><p>NOT · AND · OR · NAND · NOR · XOR</p></>, answer: <p><b>NOT:</b> opposite of input. <b>AND:</b> 1 only when both inputs are 1. <b>OR:</b> 1 when at least one input is 1. <b>NAND:</b> 0 only when both are 1. <b>NOR:</b> 1 only when both are 0. <b>XOR:</b> 1 when inputs differ. <em>[1 each]</em></p> },
      { id: "l15-2", marks: 4, lines: 4, prompt: <><b>Explain the difference between OR and XOR.</b><p>State the output of each for inputs 1,1 and 1,0.</p></>, answer: <p>OR is inclusive: it outputs 1 when one or both inputs are 1; XOR outputs 1 only when exactly one input is 1. For 1,1: OR=1, XOR=0. For 1,0: both output 1. <em>[2 distinction; 2 outputs]</em></p> },
    ],
  },
  {
    code: "B", title: "Individual truth tables", subtitle: "Use binary row order and check complements", marks: 10,
    questions: [
      { id: "l15-3", marks: 6, lines: 4, prompt: <><b>Write complete truth tables for NOT and AND.</b><p>Include headings and every input combination. NOT has one input; AND has two.</p></>, answer: <p><b>NOT:</b> 0→1, 1→0. <em>[2]</em> <b>AND</b> uses AB rows 00,01,10,11 and X=<strong>0,0,0,1</strong>. <em>[2 correct inputs; 2 correct outputs/headings]</em></p> },
      { id: "l15-4", marks: 4, lines: 5, prompt: <><b>For AB in the order 00, 01, 10, 11, write the four outputs for OR, NAND, NOR and XOR.</b></>, answer: <p><b>OR:</b> 0,1,1,1. <b>NAND:</b> 1,1,1,0. <b>NOR:</b> 1,0,0,0. <b>XOR:</b> 0,1,1,0. <em>[1 per complete correct sequence]</em></p> },
    ],
  },
  {
    code: "C", title: "Authentic Paper 1 practice", subtitle: "Gate language and a three-input expression", marks: 10,
    questions: [
      { id: "l15-5", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Describe the operation of NAND, NOR, XOR and OR.</b><p>Adapted from 9618/12 M/J 2024 Q1(a). [4]</p></>, answer: <p><b>NAND:</b> 0 only at 11. <b>NOR:</b> 1 only at 00. <b>XOR:</b> 1 when inputs differ. <b>OR:</b> 0 only at 00. <em>[1 each]</em></p> },
      { id: "l15-6", marks: 2, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Complete the output column for:</b><p>X = (A XOR B) NAND (A AND (B XOR C))</p><p>Use ABC rows 000 to 111. Adapted from 9618/12 O/N 2024 Q1(a). [2]</p></>, answer: <p>Outputs in row order 000,001,010,011,100,101,110,111: <strong>1, 1, 1, 1, 1, 0, 1, 1</strong>. <em>[1 first four; 1 final four]</em></p> },
      { id: "l15-7", marks: 4, lines: 4, prompt: <><b>A student claims: “NAND is OR with a bubble, and XOR means one or more.”</b><p>Identify and correct both errors, then give the 11 output for NAND and XOR.</p></>, answer: <p>NAND is <strong>AND followed by NOT</strong>, not OR followed by NOT. XOR means <strong>exactly one</strong> input is 1, not one or more. At 11, NAND=0 and XOR=0. <em>[4]</em></p> },
    ],
  },
];

export default function Lesson15Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "3 min", focus: "Connect physical two-state hardware to Boolean decisions.", prompt: "Ask what 1 and 0 could mean in a security system.", source: "Syllabus 3.2 p.18; Coursebook Chapter 4 printed pp.66-71.", content: <Slide number="01" eyebrow="CHAPTER 3 · LOGIC" sourceLabel="TEXTBOOK CH.4 · pp.66-71" syllabusLabel="SYLLABUS 3.2 · p.18" className="slide--logic-title"><section className="logic-title-grid"><div><span>LESSON 15 · 90 MINUTES</span><h1>Six gates.<br /><em>Two states.</em></h1><p>Recognise the symbols, state the exact rule and build every individual truth table.</p></div><div className="logic-hero"><GateIcon name="AND" /><GateIcon name="XOR" /><strong>0 / 1</strong></div></section></Slide> },
    { time: "4 min", focus: "Set the boundary between individual gates and full representation conversions.", prompt: "Students read the four success criteria aloud.", source: "Syllabus 3.2 p.18; Coursebook 4.01-4.04.", content: <Slide number="02" eyebrow="TODAY'S SYLLABUS ROUTE" sourceLabel="TEXTBOOK 4.01-4.04" syllabusLabel="SYLLABUS 3.2 · p.18" title="Recognise → define → tabulate → trace." className="slide--c3-map"><section className="c3-route-grid"><article><b>1</b><span>SYMBOL</span><p>six standard shapes</p></article><article><b>2</b><span>FUNCTION</span><p>exact input condition</p></article><article><b>3</b><span>TABLE</span><p>all input combinations</p></article><article><b>4</b><span>TRACE</span><p>one gate at a time</p></article></section><p className="c3-note"><Mark>LESSON 16</Mark> Full statement ↔ expression ↔ circuit ↔ truth-table conversions.</p></Slide> },
    { time: "5 min", focus: "Define a proposition and separate logical state from physical voltage details.", prompt: "Translate four yes/no statements into 0 or 1.", source: "Coursebook 4.01 printed p.67.", content: <Slide number="03" eyebrow="BOOLEAN PROPOSITIONS" sourceLabel="TEXTBOOK 4.01 · p.67" syllabusLabel="SYLLABUS 3.2" title="A logic input is a proposition that is either false or true." className="slide--logic-bits"><section className="logic-state-pair"><article><b>0</b><span>FALSE</span><p>door is not open</p></article><article><b>1</b><span>TRUE</span><p>door is open</p></article></section><p className="c3-note">The meaning comes from the problem statement; 1 does not always mean “safe” or “on”.</p></Slide> },
    { time: "7 min", focus: "Teach the visual grammar: inputs left, output right, inversion bubble.", prompt: "Students point to inputs, body, output and inversion bubble.", source: "Coursebook gate symbols pp.67-70; syllabus p.18 symbols.", content: <Slide number="04" eyebrow="READ A GATE SYMBOL" sourceLabel="TEXTBOOK pp.67-70" syllabusLabel="SYLLABUS 3.2 — SYMBOLS" title="Read left to right; a small output bubble means NOT." className="slide--logic-gallery"><section className="logic-gate-grid">{(["NOT","AND","OR","NAND","NOR","XOR"] as GateName[]).map((name) => <GateIcon name={name} key={name} />)}</section></Slide> },
    { time: "7 min", focus: "Establish NOT as the only one-input gate in this syllabus.", prompt: "Call an input; class responds with the output.", source: "Coursebook 4.02 p.68; syllabus 3.2.", content: <Slide number="05" eyebrow="NOT · INVERTER" sourceLabel="TEXTBOOK 4.02 · p.68" syllabusLabel="SYLLABUS 3.2 — NOT" title="NOT outputs the opposite state." className="slide--logic-focus"><section className="logic-focus-grid"><GateIcon name="NOT" /><div className="logic-one-table"><span>A</span><b>X</b><span>0</span><b>1</b><span>1</span><b>0</b></div><p><strong>X = NOT A</strong><br />One input only.</p></section></Slide> },
    { time: "8 min", focus: "Contrast restrictive AND with inclusive OR.", prompt: "Use access control and alarm scenarios to test the words all/any.", source: "Coursebook 4.03 pp.68-69.", content: <Slide number="06" eyebrow="AND vs OR" sourceLabel="TEXTBOOK 4.03 · pp.68-69" syllabusLabel="SYLLABUS 3.2 — AND / OR" title="AND needs both; OR needs at least one." className="slide--logic-pair"><section className="logic-two"><MiniTruth name="AND" outputs="0001" /><MiniTruth name="OR" outputs="0111" /></section><p className="c3-note"><Mark>WORD CLUE</Mark> AND = all conditions; OR = one or more conditions.</p></Slide> },
    { time: "8 min", focus: "Derive NAND and NOR by complementing AND/OR outputs.", prompt: "Students cover the final row and predict each complement.", source: "Coursebook 4.04 pp.69-70, with printed NAND wording corrected.", content: <Slide number="07" eyebrow="COMPLEMENTED GATES" sourceLabel="TEXTBOOK 4.04 · pp.69-70" syllabusLabel="SYLLABUS 3.2 — NAND / NOR" title="NAND = NOT AND. NOR = NOT OR." className="slide--logic-pair"><section className="logic-two"><MiniTruth name="NAND" outputs="1110" /><MiniTruth name="NOR" outputs="1000" /></section><p className="c3-warning"><b>Coursebook correction:</b> NAND is AND followed by NOT—not “NAND followed by NOT”.</p></Slide> },
    { time: "6 min", focus: "Lock in XOR as exactly one true input, not at least one.", prompt: "Compare OR and XOR only at row 11.", source: "Coursebook 4.04 pp.70-71.", content: <Slide number="08" eyebrow="XOR · EXCLUSIVE OR" sourceLabel="TEXTBOOK 4.04 · pp.70-71" syllabusLabel="SYLLABUS 3.2 — XOR" title="XOR outputs 1 when the two inputs differ." className="slide--logic-pair"><section className="logic-two"><MiniTruth name="OR" outputs="0111" /><MiniTruth name="XOR" outputs="0110" /></section><p className="c3-note"><Mark>TRAP</Mark> For 11, OR = 1 but XOR = 0.</p></Slide> },
    { time: "5 min", focus: "Standardise binary row order so tables are complete and comparable.", prompt: "Students generate the rows before calculating any outputs.", source: "Coursebook truth-table convention pp.67-71.", content: <Slide number="09" eyebrow="BUILD THE INPUT ROWS FIRST" sourceLabel="TEXTBOOK pp.67-71" syllabusLabel="SYLLABUS 3.2 — TRUTH TABLE" title="Two inputs give 2² = 4 combinations." className="slide--logic-order"><section className="logic-row-order"><span>00</span><i>→</i><span>01</span><i>→</i><span>10</span><i>→</i><span>11</span></section><p>For <b>n</b> inputs, a complete truth table has <strong>2<sup>n</sup></strong> rows.</p></Slide> },
    { time: "6 min", focus: "Consolidate all six outputs in one visual retrieval grid.", prompt: "Hide the outputs mentally and recite one row at a time.", source: "Syllabus 3.2 individual truth tables.", content: <Slide number="10" eyebrow="SIX-GATE RETRIEVAL GRID" sourceLabel="SYLLABUS TABLES" syllabusLabel="SYLLABUS 3.2" title="Know the rule; derive the row." className="slide--logic-all"><section className="logic-truth-grid"><MiniTruth name="AND" outputs="0001" /><MiniTruth name="OR" outputs="0111" /><MiniTruth name="NAND" outputs="1110" /><MiniTruth name="NOR" outputs="1000" /><MiniTruth name="XOR" outputs="0110" /><article className="logic-not-card"><GateIcon name="NOT" /><p>0→1 · 1→0</p></article></section></Slide> },
    { time: "5 min", focus: "Practise symbol recognition without relying on labels.", prompt: "Students identify four shuffled shapes and state one output condition.", source: "Syllabus 3.2 symbol recognition.", content: <Slide number="11" eyebrow="QUICK CHECK · SYMBOLS" sourceLabel="SYLLABUS CHECK" syllabusLabel="SYLLABUS 3.2" title="Name the gate before calculating." className="slide--logic-gallery"><section className="logic-gate-grid compact"><GateIcon name="NOR" /><GateIcon name="XOR" /><GateIcon name="NOT" /><GateIcon name="NAND" /></section><Reveal id="symbols" visible={revealed.has("symbols")} onToggle={toggleReveal}><p>NOR · XOR · NOT · NAND. The output bubbles on NOR, NOT and NAND indicate inversion.</p></Reveal></Slide> },
    { time: "7 min", focus: "Use an authentic operation-definition question with one mark per precise rule.", prompt: "Four minutes, then reveal and self-mark exact conditions.", source: "Adapted from 9618/12 M/J 2024 Q1(a), verified against the published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/12 M/J 2024 · Q1(a)" syllabusLabel="SYLLABUS 3.2 — EXAM PRACTICE" title="Describe the operation of NAND, NOR, XOR and OR." className="slide--c3-paper"><section className="c3-paper-grid four"><p><b>NAND</b><strong>[1]</strong></p><p><b>NOR</b><strong>[1]</strong></p><p><b>XOR</b><strong>[1]</strong></p><p><b>OR</b><strong>[1]</strong></p></section><Reveal id="gate-paper" visible={revealed.has("gate-paper")} onToggle={toggleReveal}><p>NAND is 0 only at 11; NOR is 1 only at 00; XOR is 1 when inputs differ; OR is 0 only at 00.</p></Reveal><small>Adapted from 9618/12 M/J 2024 Q1(a).</small></Slide> },
    { time: "8 min", focus: "Model safe truth-table evaluation using intermediate columns.", prompt: "Pairs calculate A XOR B, B XOR C, A AND (B XOR C), then the final NAND.", source: "Adapted from 9618/12 O/N 2024 Q1(a).", content: <Slide number="13" eyebrow="PAST PAPER WORKED METHOD" sourceLabel="9618/12 O/N 2024 · Q1(a)" syllabusLabel="SYLLABUS 3.2 — TRACE" title="One gate per column prevents invisible mistakes." className="slide--logic-worked"><p className="logic-expression">X = (A XOR B) NAND (A AND (B XOR C))</p><section className="logic-column-flow"><span>A XOR B</span><i>→</i><span>B XOR C</span><i>→</i><span>A AND ...</span><i>→</i><strong>NAND</strong></section><Reveal id="worked" visible={revealed.has("worked")} onToggle={toggleReveal}><p>Final X for ABC 000→111: <b>1, 1, 1, 1, 1, 0, 1, 1</b>.</p></Reveal></Slide> },
    { time: "6 min", focus: "Repair three frequent gate misconceptions before the final check.", prompt: "Students correct each statement in one sentence.", source: "Coursebook/syllabus misconception check.", content: <Slide number="14" eyebrow="MISCONCEPTION CLINIC" sourceLabel="EXAMINER LANGUAGE" syllabusLabel="SYLLABUS 3.2" title="Three statements to reject." className="slide--c3-retrieval"><section className="c3-quiz"><p><b>1</b> “OR means exactly one.”</p><p><b>2</b> “A bubble means output 1.”</p><p><b>3</b> “A three-input gate is fine in this syllabus.”</p></section><Reveal id="clinic" visible={revealed.has("clinic")} onToggle={toggleReveal}><p><b>1</b> XOR means exactly one; OR means one or more. <b>2</b> A bubble means inversion. <b>3</b> Except NOT, syllabus gates have two inputs; cascade gates for three conditions.</p></Reveal></Slide> },
    { time: "5 min", focus: "End with a complete verbal and tabular gate description.", prompt: "Students choose one gate: name, rule, 00–11 output sequence.", source: "Syllabus 3.2 exit check.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="SYLLABUS 3.2" syllabusLabel="CHAPTER 3 · LOGIC CHECK" title="Name it. Define it. Tabulate it." className="slide--c3-exit"><section className="logic-exit"><GateIcon name="XOR" /><p>Write the exact rule and all four outputs without notes.</p></section><div className="c3-homework-callout"><b>HOMEWORK 15</b><span>30 marks · two verified Paper 1 tasks · inline answers</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="15" slides={slides} homework={<HomeworkSheet lessonNumber="15" title="Logic Gates, Symbols, Functions & Truth Tables" marks={30} minutes={45} syllabusLabel="SYLLABUS 3.2 · p.18" sourceLabel="TEXTBOOK CH.4 · pp.66-71 + PAPER 1" instructions="Use input rows in binary order. State gate functions with exact conditions such as both, at least one, neither or different. Past-paper prompts are concise adaptations with original references." sections={homeworkSections} challenge={{ id: "l15-challenge", prompt: <p><Mark>CHALLENGE</Mark> Can every output of AND, OR and XOR be inverted using only an output bubble? Name the resulting gates where the syllabus provides one.</p>, answer: <p>Yes: inversion complements every output. AND + NOT gives NAND; OR + NOT gives NOR. An inverted XOR is XNOR, but XNOR is not one of the six gates required by this syllabus section.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 3.2 p.18, Coursebook 4.01-4.04 printed pp.67-71, and published 2024 Paper 1 questions and mark schemes." sourceDetail="Core: standard symbols and exact functions for NOT, AND, OR, NAND, NOR and XOR; individual truth tables; all non-NOT gates shown with two inputs. Authentic anchors: 9618/12 M/J 2024 Q1(a) and 9618/12 O/N 2024 Q1(a). Coursebook p.71 NAND wording is corrected. Full representation conversions continue in Lesson 16; Boolean simplification and De Morgan are deferred." />;
}
