"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Recognise the application", subtitle: "Input, intelligent task and useful output", marks: 10,
    questions: [
      { id: "l35-1", marks: 2, lines: 2, prompt: <><b>Define artificial intelligence at AS level.</b></>, answer: <p>AI describes computer systems that process data to perform tasks associated with intelligent behaviour, such as perception, language, learning, reasoning, prediction or decision support. The definition concerns capability, not consciousness. <em>[2]</em></p> },
      { id: "l35-2", marks: 4, lines: 4, prompt: <><b>Explain the roles of OCR/image recognition, natural language processing and text-to-speech in an accessibility app.</b></>, answer: <p>Image recognition/OCR analyses image pixels and identifies printed characters; NLP analyses/composes language and may interpret or translate the extracted words; text-to-speech converts the resulting text into generated audio. Together they turn a photographed document into spoken, understandable output. <em>[4]</em></p> },
      { id: "l35-3", marks: 4, lines: 4, prompt: <><b>For each system, state an AI application and one appropriate human decision that should remain:</b><p>(i) hospital scan triage; (ii) bank transaction monitoring.</p></>, answer: <p>(i) Computer vision/classification can flag suspicious scans; a clinician reviews diagnosis/treatment. (ii) Anomaly/fraud detection can score unusual transactions; authorised staff/customer evidence determines blocking or appeal. Award application plus justified human decision for each. <em>[2 + 2]</em></p> },
    ],
  },
  {
    code: "B", title: "Evaluate all three impact dimensions", subtitle: "Benefit, risk, affected group and mitigation", marks: 10,
    questions: [
      { id: "l35-4", marks: 4, lines: 4, prompt: <><b>Explain one positive and one negative social impact of an AI translation assistant.</b></>, answer: <p>Positive: real-time translation can improve access to services/education and communication for people who use different languages. Negative: mistranslation or biased output can mislead users, especially in medical/legal contexts, or private conversations may be processed. Human checking, warnings and data minimisation can reduce risk. <em>[2 + 2]</em></p> },
      { id: "l35-5", marks: 3, lines: 3, prompt: <><b>Explain a positive and a negative economic impact of workplace AI.</b></>, answer: <p>AI can automate repetitive tasks, increase productivity and create new products/roles. It can also displace or redesign jobs, concentrate gains and require costly reskilling. The final effect depends on deployment and how benefits/support are distributed. <em>[3]</em></p> },
      { id: "l35-6", marks: 3, lines: 3, prompt: <><b>Explain both sides of AI&apos;s environmental impact.</b></>, answer: <p>Training/inference and data centres use electricity/cooling resources; hardware production and replacement can create emissions and e-waste. AI can also optimise grids, transport, buildings, agriculture or industrial processes to reduce resource use. Compare the saved impact with the system&apos;s full lifecycle cost. <em>[3]</em></p> },
    ],
  },
  {
    code: "C", title: "Published AI contexts", subtitle: "Accessibility and education impacts", marks: 10,
    questions: [
      { id: "l35-7", marks: 6, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain how OCR/image recognition, NLP and text-to-speech can process photographed text, then give two social benefits.</b><p>Adapted from 9618/12 M/J 2025 Q3(a)–(b). [4 + 2]</p></>, answer: <p>Image recognition/OCR analyses pixels and recognises characters; NLP combines/interprets or translates words; text-to-speech generates audio from the processed text. Benefits include access for users with visual, reading or language difficulties and more independent/rapid access to information. <em>[4 + 2]</em></p> },
      { id: "l35-8", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Evaluate two social impacts of students using AI assistants for learning.</b><p>Adapted from 9618/11 O/N 2025 Q8(c). [4]</p></>, answer: <p>Possible negatives: reduced independent reasoning/skills, less human collaboration, misinformation, unequal access/digital divide, anxiety or isolation. Possible positives: personalised explanations, self-paced practice, accessibility and confidence. Award impact plus developed consequence/evaluation; a balanced answer may add verification, teacher oversight and task redesign. <em>[4]</em></p> },
    ],
  },
];

export default function Lesson35Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame AI as a family of capabilities and impacts, not one product or consciousness claim.", prompt: "Ask: which everyday systems already perceive, predict or generate?", source: "Syllabus 7.1 AI applications and social/economic/environmental impacts; Coursebook 10.06 printed pp.153–156.", content: <Slide number="01" eyebrow="CHAPTER 7 · ARTIFICIAL INTELLIGENCE" sourceLabel="TEXTBOOK §10.06 · pp.153–156" syllabusLabel="SYLLABUS 7.1" className="se-title"><section className="se-title-grid"><div className="se-title-copy"><span>LESSON 35 · 90 MINUTES</span><h1>Capability meets <em>consequence.</em></h1><p>Recognise AI applications, trace input to output and evaluate social, economic and environmental impacts from evidence—not slogans.</p></div><div className="se-title-visual"><div><b>1</b><span>WHAT TASK IS PERFORMED?</span></div><div><b>2</b><span>WHO BENEFITS?</span></div><div><b>3</b><span>WHO CARRIES THE RISK?</span></div><div><b>4</b><span>WHAT OVERSIGHT OR MITIGATION?</span></div></div></section></Slide> },
    { time: "5 min", focus: "Separate observable AI capability from science-fiction assumptions.", prompt: "Classify each example by perception, language, prediction or decision support.", source: "Coursebook 10.06 printed pp.153–155; syllabus 7.1 AI.", content: <Slide number="02" eyebrow="WHAT COUNTS AS AI HERE?" sourceLabel="TEXTBOOK §10.06 · pp.153–155" syllabusLabel="SYLLABUS 7.1" title="Systems performing tasks associated with intelligent behaviour."><section className="se-grid four"><article className="se-card"><span>PERCEPTION</span><p>recognise objects, faces, speech or printed text</p></article><article className="se-card"><span>LANGUAGE</span><p>interpret, translate, summarise or generate</p></article><article className="se-card"><span>PREDICTION</span><p>estimate risk, demand, fraud or likely preference</p></article><article className="se-card"><span>DECISION SUPPORT</span><p>rank options, recommend or control under rules</p></article></section><p className="se-warning">AI capability does not imply consciousness, perfect reasoning or freedom from human choices and data.</p></Slide> },
    { time: "6 min", focus: "Give a simple lifecycle for analysing any application without teaching model internals.", prompt: "At which stage can biased training examples affect later decisions?", source: "Coursebook 10.06 problem-solving/learning framework; syllabus 7.1 application impact.", content: <Slide number="03" eyebrow="READ AN AI SYSTEM" sourceLabel="TEXTBOOK §10.06 · pp.153–155" syllabusLabel="SYLLABUS 7.1" title="Input → learned/rule-based processing → output → human/system action."><section className="se-ai-pipeline"><div><b>INPUT</b><p>images, text, sound, sensor or transaction data</p></div><i>→</i><div><b>AI PROCESS</b><p>recognise patterns, infer, predict or generate</p></div><i>→</i><div><b>OUTPUT + ACTION</b><p>label, score, text, alert, recommendation or control</p></div></section><p className="se-note">Evaluate data quality, errors, affected users, action taken and whether <strong>human oversight</strong> is proportionate to risk.</p></Slide> },
    { time: "6 min", focus: "Explain computer vision and OCR through pixel analysis to symbolic output.", prompt: "What extra problem does OCR solve after a camera captures pixels?", source: "Coursebook 10.06 perception; 9618/12 M/J 2025 Q3(a); syllabus 7.1 AI applications.", content: <Slide number="04" eyebrow="VISION + OCR" sourceLabel="TEXTBOOK p.154 + 9618/12 M/J 2025" syllabusLabel="SYLLABUS 7.1" title="From image pixels to recognised objects or characters."><section className="se-flow"><span>CAMERA /<br />SCAN PIXELS</span><i>→</i><span>FEATURE / PATTERN<br />ANALYSIS</span><i>→</i><span>OBJECT OR<br />CHARACTER LABEL</span><i>→</i><span>SEARCH, READ OR<br />DECIDE</span></section><p className="se-note">Applications: OCR for accessible text, medical-image triage, manufacturing inspection, traffic perception and document processing.</p></Slide> },
    { time: "6 min", focus: "Connect NLP, speech and generative systems while preserving distinct input/output roles.", prompt: "Which component translates meaning, and which turns the result into sound?", source: "Coursebook 10.06 language; 9618/12 M/J 2025 Q3(a); syllabus 7.1.", content: <Slide number="05" eyebrow="LANGUAGE, SPEECH + GENERATION" sourceLabel="TEXTBOOK §10.06 + PAPER 1" syllabusLabel="SYLLABUS 7.1" title="Analyse human language; produce useful text, speech or other content."><section className="se-grid four"><article className="se-card"><span>NLP</span><p>interpret, combine, classify or translate language</p></article><article className="se-card"><span>SPEECH RECOGNITION</span><p>spoken audio → text/commands</p></article><article className="se-card"><span>TEXT-TO-SPEECH</span><p>text → generated spoken audio</p></article><article className="se-card"><span>GENERATIVE AI</span><p>produce text, image, audio or code from prompts/context</p></article></section><p className="se-warning">Fluent output can still be inaccurate, biased or fabricated; verification remains a human/system design responsibility.</p></Slide> },
    { time: "6 min", focus: "Survey prediction applications across high-stakes and everyday domains.", prompt: "For each application, state the output and a false-positive consequence.", source: "Coursebook 10.06 reasoning/learning; syllabus 7.1 AI applications.", content: <Slide number="06" eyebrow="PREDICT + RECOMMEND" sourceLabel="TEXTBOOK §10.06 · pp.153–155" syllabusLabel="SYLLABUS 7.1" title="A score or ranking becomes consequential only when someone acts on it."><section className="se-grid four"><article className="se-card"><span>RECOMMENDATION</span><p>rank products, media or learning tasks</p></article><article className="se-card"><span>FRAUD DETECTION</span><p>flag anomalous transactions for review</p></article><article className="se-card"><span>DIAGNOSIS SUPPORT</span><p>estimate condition/risk from clinical data</p></article><article className="se-card"><span>FORECASTING</span><p>predict demand, failure, weather-related risk</p></article></section></Slide> },
    { time: "6 min", focus: "Explore autonomous control and optimisation with safety and human override.", prompt: "Which action should be reversible or require approval in each context?", source: "Coursebook 10.06 robotics/problem-solving; syllabus 7.1 AI applications.", content: <Slide number="07" eyebrow="ACT + OPTIMISE" sourceLabel="TEXTBOOK §10.06 · pp.153–155" syllabusLabel="SYLLABUS 7.1" title="Perceive state, select an action, monitor the result."><section className="se-grid four"><article className="se-card"><span>AUTONOMOUS SYSTEM</span><p>vehicle/robot selects actions from sensor input</p></article><article className="se-card"><span>ENERGY</span><p>balance supply, demand and maintenance</p></article><article className="se-card"><span>LOGISTICS</span><p>route vehicles and allocate inventory</p></article><article className="se-card"><span>AGRICULTURE</span><p>target water, fertiliser or inspection</p></article></section><p className="se-note">Higher consequence calls for stronger testing, monitoring, fail-safe behaviour, explanation and human authority.</p></Slide> },
    { time: "6 min", focus: "Evaluate social impacts as access/safety versus rights, error and inequality.", prompt: "Choose one stakeholder who experiences both a benefit and a risk.", source: "Syllabus 7.1 social impacts; Coursebook 10.06; UNESCO Recommendation on the Ethics of AI.", content: <Slide number="08" eyebrow="SOCIAL IMPACT" sourceLabel="TEXTBOOK §10.06 + UNESCO" syllabusLabel="SYLLABUS 7.1 · SOCIAL" title="Access and assistance can coexist with bias, surveillance and misinformation."><section className="se-impact-grid"><article><h3>Potential benefit</h3><p><strong>Accessibility:</strong> speech, captioning, translation.</p><p><strong>Safety:</strong> earlier alerts and anomaly detection.</p></article><article><h3>Potential harm</h3><p><strong>Rights:</strong> privacy loss and surveillance.</p><p><strong>Fairness:</strong> unequal errors or exclusion.</p></article><article><h3>Mitigation</h3><p><strong>Human oversight:</strong> review and appeal.</p><p><strong>Evidence:</strong> test groups, provenance, monitoring.</p></article></section></Slide> },
    { time: "6 min", focus: "Evaluate economic impacts through tasks, productivity, distribution and transition.", prompt: "Why can productivity rise while some workers are worse off?", source: "Syllabus 7.1 economic impacts; Coursebook 10.06; OECD analysis of AI productivity and labour impacts.", content: <Slide number="09" eyebrow="ECONOMIC IMPACT" sourceLabel="TEXTBOOK §10.06 + OECD" syllabusLabel="SYLLABUS 7.1 · ECONOMIC" title="Automation changes tasks; gains and disruption are distributed unevenly."><section className="se-impact-grid"><article><h3>Potential benefit</h3><p><strong>Productivity:</strong> faster routine work and decisions.</p><p><strong>Innovation:</strong> new products, services and roles.</p></article><article><h3>Potential harm</h3><p><strong>Displacement:</strong> some tasks/jobs shrink or change.</p><p><strong>Concentration:</strong> skills, data and capital shape who gains.</p></article><article><h3>Response</h3><p><strong>Reskill:</strong> training and transition support.</p><p><strong>Redesign:</strong> complement people; audit outcomes.</p></article></section></Slide> },
    { time: "6 min", focus: "Evaluate environmental costs and benefits across the full lifecycle.", prompt: "What measurement would show whether an optimisation system saves more than it consumes?", source: "Syllabus 7.1 environmental impacts; IEA Energy and AI (2025); Coursebook 10.06 updated.", content: <Slide number="10" eyebrow="ENVIRONMENTAL IMPACT" sourceLabel="TEXTBOOK §10.06 + IEA 2025" syllabusLabel="SYLLABUS 7.1 · ENVIRONMENTAL" title="Compute has a footprint; optimisation can also reduce another footprint."><section className="se-impact-grid"><article><h3>Resource cost</h3><p><strong>Electricity:</strong> training, inference and data centres.</p><p><strong>Cooling + hardware:</strong> water/material use and e-waste.</p></article><article><h3>Potential saving</h3><p><strong>Optimise:</strong> grids, buildings, routes and industry.</p><p><strong>Detect:</strong> leaks, faults and wasted inputs.</p></article><article><h3>Evaluate</h3><p><strong>Lifecycle:</strong> build, operate, replace and dispose.</p><p><strong>Net effect:</strong> compare measured savings with added cost.</p></article></section><p className="se-source-line">Current context: International Energy Agency, <em>Energy and AI</em> (2025).</p></Slide> },
    { time: "5 min", focus: "Teach a balanced impact paragraph structure that names evidence and mitigation.", prompt: "Turn 'AI is bad for jobs' into a conditional evaluated claim.", source: "Syllabus 7.1 impacts; UNESCO human oversight/accountability principles; Coursebook 10.06.", content: <Slide number="11" eyebrow="FROM CLAIM TO EVALUATION" sourceLabel="TEXTBOOK §10.06 + UNESCO" syllabusLabel="SYLLABUS 7.1" title="Application → stakeholder → mechanism → consequence → mitigation → judgement."><section className="se-decision-ladder"><span>APPLICATION +<br />CONTEXT</span><i>→</i><span>AFFECTED<br />STAKEHOLDER</span><i>→</i><span>HOW THE IMPACT<br />HAPPENS</span><i>→</i><span>SAFEGUARD /<br />TRADE-OFF</span><i>→</i><span>CONDITIONAL<br />JUDGEMENT</span></section><p className="se-note">UNESCO emphasises proportionality, privacy, fairness, accountability and human oversight. Apply these as questions, not decorative vocabulary.</p></Slide> },
    { time: "7 min", focus: "Apply all three impact dimensions to one school deployment.", prompt: "Groups produce one benefit, risk, stakeholder and mitigation per dimension.", source: "Syllabus 7.1 social/economic/environmental impacts; Coursebook 10.06; current UNESCO/IEA context.", content: <Slide number="12" eyebrow="SCENARIO CLINIC · AI TUTOR" sourceLabel="TEXTBOOK §10.06 · APPLICATION" syllabusLabel="SYLLABUS 7.1" title="The school proposes a 24/7 generative study assistant."><section className="se-impact-grid"><article><h3>Social</h3><p>accessibility and individual help</p><p>misinformation, privacy, over-reliance, unequal access</p></article><article><h3>Economic</h3><p>teacher time and scalable support</p><p>fees, vendor lock-in, changed roles and training</p></article><article><h3>Environmental</h3><p>less travel/printing in some contexts</p><p>data-centre energy, cooling and device lifecycle</p></article></section><p className="se-note">End with a decision: pilot, conditions, human review, success/harm measures and a stop/review trigger.</p></Slide> },
    { time: "8 min", focus: "Practise the current Paper 1 accessibility pipeline and social benefits.", prompt: "Write one processing verb per component and two distinct user benefits.", source: "Adapted from 9618/12 M/J 2025 Q3(a)–(b), checked against the published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 6 MARKS" sourceLabel="9618/12 M/J 2025 · Q3(a)–(b)" syllabusLabel="SYLLABUS 7.1 — EXAM PRACTICE" title="Photographed text becomes translated speech." className="slide--se-paper"><section className="se-paper-grid"><article><span>4 MARKS</span><p>Explain OCR/image recognition, NLP and text-to-speech in the pipeline.</p></article><article><span>2 MARKS</span><p>Give two developed social/accessibility benefits.</p></article></section><ExamReveal><p>OCR/image recognition analyses pixels and recognises characters; NLP combines/interprets/translates words; text-to-speech generates audio. Benefits include more independent access for users with visual/reading needs and communication across language barriers.</p></ExamReveal><small className="se-source-line">Concise adaptation of 9618/12 M/J 2025 Q3(a)–(b); original allocation [4 + 2].</small></Slide> },
    { time: "8 min", focus: "Evaluate AI use in education using the published 2025 impact range.", prompt: "Write two impacts; each requires a mechanism and consequence, not a list word.", source: "Adapted from 9618/11 O/N 2025 Q8(c), checked against the published mark scheme.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/11 O/N 2025 · Q8(c)" syllabusLabel="SYLLABUS 7.1 — EXAM PRACTICE" title="Evaluate social impacts of AI assistants for students." className="slide--se-paper"><section className="se-paper-grid"><article><span>POSSIBLE BENEFIT</span><p>personalised, self-paced support or improved accessibility/confidence</p></article><article><span>POSSIBLE HARM</span><p>skill loss, reduced collaboration, misinformation, unequal access or anxiety</p></article></section><ExamReveal><p>Develop each chosen point: explain how use changes learning or wellbeing and who is affected. A balanced evaluation can add teacher oversight, source checking, equitable access and redesigned assessment rather than a blanket ban or claim of perfection.</p></ExamReveal><small className="se-source-line">Concise adaptation of 9618/11 O/N 2025 Q8(c); original allocation [4].</small></Slide> },
    { time: "5 min", focus: "Close Chapter 7 by reconnecting ethics, ownership and AI impact judgement.", prompt: "Students give one sentence linking all three cards to a new AI product.", source: "Syllabus 7.1 complete chapter synthesis; Coursebook Chapter 10 summary printed p.155.", content: <Slide number="15" eyebrow="EXIT TICKET · CHAPTER 7 COMPLETE" sourceLabel="TEXTBOOK CH.10 · pp.155–156" syllabusLabel="SYLLABUS 7.1" title="Three lenses for every computing decision."><section className="se-exit"><article><span>L33 · ETHICS</span><p>Who benefits or may be harmed, and what duty follows?</p></article><article><span>L34 · OWNERSHIP</span><p>Who owns the work, and what permissions apply?</p></article><article><span>L35 · AI</span><p>What capability creates which social, economic and environmental effects?</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="35" slides={slides} homework={<HomeworkSheet lessonNumber="35" title="Artificial Intelligence: Applications and Impacts" marks={30} minutes={45} syllabusLabel="SYLLABUS 7.1" sourceLabel="TEXTBOOK CH.10 · pp.153–156 + PAPER 1" instructions="Name the AI task and trace input to output before evaluating impact. Every impact must identify an affected stakeholder, causal mechanism and consequence; balanced answers add mitigation, human oversight and a conditional judgement." sections={homeworkSections} challenge={{ id: "l35-challenge", prompt: <p><Mark>CHALLENGE</Mark> Design four measurable indicators for a one-term AI-tutor pilot: one learning, one fairness, one staff/economic and one environmental indicator.</p>, answer: <p>Examples: <strong>learning</strong>—change in independently completed assessment scores; <strong>fairness</strong>—error/benefit and access rates compared across relevant pupil groups; <strong>staff/economic</strong>—teacher hours saved minus review/training time and licence cost; <strong>environmental</strong>—estimated energy/device use compared with any reduced printing/travel. Predefine thresholds and review/stop the pilot if harm or inequality rises.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 7.1, Coursebook Chapter 10 printed pp.153–156, published 2025 Paper 1 questions/mark schemes, UNESCO AI ethics guidance and the IEA Energy and AI report." sourceDetail="Core: AI applications and social, economic and environmental impacts, evaluated with stakeholders, evidence, mitigation and human oversight. Authentic anchors: 9618/12 M/J 2025 Q3(a)–(b) [6] and 9618/11 O/N 2025 Q8(c) [4]. Current context: UNESCO Recommendation on the Ethics of AI and IEA Energy and AI (2025). Neural-network structure/training algorithms remain A Level material." additionalSourceLinks={[{ href: "https://www.unesco.org/en/artificial-intelligence/recommendation-ethics", label: "UNESCO AI ethics" }, { href: "https://www.iea.org/reports/energy-and-ai", label: "IEA Energy and AI" }]} />;
}
