"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { FlynnMatrix } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Flynn classification", subtitle: "Count instruction and data streams", marks: 10,
    questions: [
      { id: "a2-12-1", marks: 3, lines: 5, prompt: <><b>Expand SISD, SIMD and MIMD.</b></>, answer: <p>SISD: Single Instruction Stream, Single Data Stream <em>[1]</em>; SIMD: Single Instruction Stream, Multiple Data Stream <em>[1]</em>; MIMD: Multiple Instruction Stream, Multiple Data Stream <em>[1]</em>.</p> },
      { id: "a2-12-2", marks: 3, lines: 5, prompt: <><b>Describe MISD</b> and give one suitable application idea.</>, answer: <p>Multiple Instruction Streams operate on the same/single data stream <em>[2]</em>. A possible use is fault-tolerant safety processing in which different algorithms examine the same sensor data and results are compared <em>[1]</em>.</p> },
      { id: "a2-12-3", marks: 4, lines: 7, prompt: <><b>Classify and justify:</b> one calculation applied to every pixel; four cores running independent programs.</>, answer: <p>Pixel operation: <strong>SIMD</strong> because one instruction is applied simultaneously to multiple pixel data items <em>[2]</em>. Independent programs: <strong>MIMD</strong> because different instruction streams process different data independently <em>[2]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Architecture decisions", subtitle: "Do not confuse kinds of parallelism", marks: 10,
    questions: [
      { id: "a2-12-4", marks: 3, lines: 5, prompt: <><b>Explain one difference between SIMD and pipelining.</b></>, answer: <p>SIMD applies the same instruction to multiple data items at the same time <em>[1]</em>. A pipeline overlaps different stages of different instructions <em>[1]</em>; it is instruction-stage overlap rather than multiple data streams <em>[1]</em>.</p> },
      { id: "a2-12-5", marks: 3, lines: 5, prompt: <><b>Explain why MIMD processors may finish their tasks at different times.</b></>, answer: <p>They run different instruction streams <em>[1]</em> on different data <em>[1]</em>, so workloads and execution paths can differ and the processors may operate asynchronously <em>[1]</em>.</p> },
      { id: "a2-12-6", marks: 4, lines: 6, prompt: <><b>Choose a Flynn class</b> for a sequential calculator and for redundant flight-control checks. Justify both.</>, answer: <p>Calculator: SISD—one instruction stream works on one data stream sequentially <em>[2]</em>. Redundant checks: MISD—different algorithms/instruction streams inspect the same sensor data, allowing results to be compared for reliability <em>[2]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Massive parallelism", subtitle: "Coordinate many processors", marks: 10,
    questions: [
      { id: "a2-12-7", marks: 3, lines: 5, prompt: <><b>State three features of a massively parallel computer.</b></>, answer: <p>It uses a very large number of processors/computers <em>[1]</em>, works on parts of a problem simultaneously <em>[1]</em>, and communicates through network infrastructure/message passing to coordinate work <em>[1]</em>.</p> },
      { id: "a2-12-8", marks: 3, lines: 5, prompt: <><b>Explain why communication overhead can limit speed-up.</b></>, answer: <p>A problem must be split and data sent between processors <em>[1]</em>. Processors may wait for messages or synchronisation <em>[1]</em>, so extra processors do not guarantee a proportional reduction in total time <em>[1]</em>.</p> },
      { id: "a2-12-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE + EXTENSION</span><p><b>(a) Describe a massively parallel computer. [3] (b) State one coordination challenge. [1]</b></p><p>Part (a) adapted from 9618/31 M/J 2023 Q8.</p></>, answer: <p>It contains a very large number of processors/separate computers <em>[1]</em> performing coordinated computations simultaneously <em>[1]</em> and communicating by messages over network infrastructure <em>[1]</em>. Challenge: communication/synchronisation overhead, unequal work or a remaining serial step can limit speed-up <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson12Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Classify computing systems by streams, not by product names.", prompt: "Count instruction streams and data streams in each scenario.", source: "2027–2029 syllabus 15.1; coursebook Chapter 18 printed pp.344–346.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch18" syllabusLabel="SYLLABUS 15.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 12 · 90 MINUTES</span><h1>How many instructions?<br /><em>How many data streams?</em></h1><p>Flynn taxonomy · parallel workloads · massively parallel systems</p></div><div className="a2-at-hero" role="img" aria-label="Four forms of processing"><strong>PARALLEL?</strong><span>SISD</span><span>SIMD</span><span>MISD</span><span>MIMD</span></div></section></Slide> },
    { time: "5 min", focus: "Map the exact parallel-processing outcomes.", prompt: "Students define stream before expanding the four acronyms.", source: "Syllabus p.34; coursebook pp.344–346.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.34" syllabusLabel="15.1 · PARALLEL" title="Two questions classify the architecture: instruction count and data count." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "INSTRUCTION", title: "What operation?", body: "One shared stream or several independent streams." }, { eyebrow: "DATA", title: "What values?", body: "One shared stream or several different streams." }, { eyebrow: "SCALE", title: "How many processors?", body: "A massive system coordinates very many workers." }]} /></Slide> },
    { time: "5 min", focus: "Place all four classes in one visual matrix.", prompt: "Predict each acronym before labels are revealed.", source: "Coursebook §18.03 pp.344–345.", content: <Slide number="03" eyebrow="FLYNN MATRIX" sourceLabel="TEXTBOOK pp.344–345" syllabusLabel="15.1 · SISD/SIMD/MISD/MIMD" title="The initials describe instruction streams first, then data streams." className="a2-slide a2-at-slide"><FlynnMatrix /></Slide> },
    { time: "6 min", focus: "Describe SISD with a sequential trace.", prompt: "What is single: the processor, instruction stream, data stream—or all three?", source: "Coursebook p.344; 9618/31 O/N 2023 Q5.", content: <Slide number="04" eyebrow="SISD" sourceLabel="9618/31 O/N 2023 · Q5" syllabusLabel="15.1 · DESCRIBE" title="One instruction stream processes one data stream sequentially." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "I1", title: "Fetch A[0]" }, { eyebrow: "I2", title: "Process A[0]" }, { eyebrow: "I3", title: "Fetch A[1]" }, { eyebrow: "I4", title: "Process A[1]" }]} /></Slide> },
    { time: "6 min", focus: "Describe SIMD through one repeated data operation.", prompt: "Why are image and vector workloads a natural fit?", source: "Coursebook p.344; 9618/32 O/N 2023 Q10.", content: <Slide number="05" eyebrow="SIMD" sourceLabel="9618/32 O/N 2023 · Q10" syllabusLabel="15.1 · DESCRIBE" title="One instruction is broadcast to several data items at once." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "+10", title: "Pixel 1", body: "42 → 52" }, { eyebrow: "+10", title: "Pixel 2", body: "70 → 80" }, { eyebrow: "+10", title: "Pixel 3", body: "13 → 23" }, { eyebrow: "+10", title: "Pixel 4", body: "91 → 101" }]} /></Slide> },
    { time: "6 min", focus: "Describe MISD and keep the same-data requirement visible.", prompt: "How could diverse calculations increase confidence in a safety result?", source: "Coursebook p.345; 9618/32 O/N 2023 Q10.", content: <Slide number="06" eyebrow="MISD" sourceLabel="O/N 2023 · PAPER 32" syllabusLabel="15.1 · DESCRIBE" title="Different instruction streams examine the same data stream." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SENSOR", title: "One input stream" }, { eyebrow: "ALGORITHM A", title: "Range check" }, { eyebrow: "ALGORITHM B", title: "Trend check" }, { eyebrow: "COMPARE", title: "Fault-tolerant decision" }]} /></Slide> },
    { time: "6 min", focus: "Describe MIMD with independent processors.", prompt: "Which words show that work is not locked to one shared instruction?", source: "Coursebook p.345; 9618/31 O/N 2023 Q5.", content: <Slide number="07" eyebrow="MIMD" sourceLabel="O/N 2023 · PAPER 31" syllabusLabel="15.1 · DESCRIBE" title="Processors run different instructions on different data." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "CORE 1", title: "Render frame", body: "instructions R · data set 1" }, { eyebrow: "CORE 2", title: "Process audio", body: "instructions A · data set 2" }, { eyebrow: "CORE 3", title: "Handle network", body: "instructions N · data set 3" }]} /></Slide> },
    { time: "6 min", focus: "Compare all four without relying on examples alone.", prompt: "Cover the examples, then classify from the two defining dimensions.", source: "Syllabus 15.1; coursebook pp.344–345.", content: <Slide number="08" eyebrow="CLASSIFICATION GRID" sourceLabel="TEXTBOOK pp.344–345" syllabusLabel="15.1 · COMPARE" title="Architecture is defined by streams; examples only illustrate it." className="a2-slide a2-at-slide"><CompareTable headers={["Class", "Instruction streams", "Data streams", "Useful example"]} rows={[["SISD", "single", "single", "sequential processor"], ["SIMD", "single", "multiple", "pixels / vectors"], ["MISD", "multiple", "single", "redundant safety checks"], ["MIMD", "multiple", "multiple", "multicore / distributed tasks"]]} /></Slide> },
    { time: "6 min", focus: "Prevent the common SIMD-pipeline confusion.", prompt: "Identify what overlaps in each design.", source: "Coursebook Chapters 18.02–18.03.", content: <Slide number="09" eyebrow="NOT THE SAME" sourceLabel="TEXTBOOK pp.343–345" syllabusLabel="15.1 · PRECISION" title="A pipeline overlaps stages; SIMD duplicates one operation across data." className="a2-slide a2-at-slide"><CompareTable headers={["Pipelining", "SIMD"]} rows={[["different stages", "same instruction"], ["different instructions in flight", "different data items"], ["instruction-level temporal overlap", "data-level parallelism"], ["can exist inside one core", "needs multiple execution lanes/units"]]} /></Slide> },
    { time: "6 min", focus: "Define a massively parallel computer.", prompt: "Which feature makes it more than an ordinary multicore processor?", source: "Coursebook pp.345–346; 9618/31 M/J 2023 Q8.", content: <Slide number="10" eyebrow="MASSIVELY PARALLEL" sourceLabel="9618/31 M/J 2023 · Q8" syllabusLabel="15.1 · DESCRIBE" title="A very large number of processors collaborate on one large problem." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "SCALE", title: "Many processors", body: "Often separate nodes or computers." }, { eyebrow: "NETWORK", title: "Message passing", body: "Nodes exchange data through network infrastructure." }, { eyebrow: "GOAL", title: "Coordinated solution", body: "Partial results combine into the final result." }]} /></Slide> },
    { time: "7 min", focus: "Trace the split-compute-communicate-combine workflow.", prompt: "Where can coordination cost appear?", source: "Coursebook pp.345–346.", content: <Slide number="11" eyebrow="WORKFLOW" sourceLabel="TEXTBOOK pp.345–346" syllabusLabel="15.1 · MASSIVE SYSTEMS" title="Parallel speed requires a problem that can be divided." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SPLIT", title: "Partition problem/data" }, { eyebrow: "DISTRIBUTE", title: "Send work to nodes" }, { eyebrow: "COMPUTE", title: "Process simultaneously" }, { eyebrow: "MESSAGE", title: "Share dependencies" }, { eyebrow: "COMBINE", title: "Assemble result" }]} /></Slide> },
    { time: "7 min", focus: "Evaluate benefits and coordination limits.", prompt: "Why is twice as many processors rarely exactly twice as fast?", source: "Coursebook p.346; syllabus understanding of massively parallel computers.", content: <Slide number="12" eyebrow="SPEED-UP LIMITS" sourceLabel="TEXTBOOK p.346" syllabusLabel="15.1 · REASON" title="Communication, serial work and imbalance consume time." className="a2-slide a2-at-slide"><CompareTable headers={["Benefit", "Limitation"]} rows={[["many calculations run together", "some steps remain sequential"], ["large data sets can be partitioned", "partitions may not be equal"], ["nodes can contribute local memory", "messages and synchronisation add overhead"], ["system can scale", "software is harder to design"]]} /></Slide> },
    { time: "7 min", focus: "Choose an architecture from workload evidence.", prompt: "Underline same/different instruction and same/different data in each case.", source: "Adapted Paper 3 classification practice.", content: <Slide number="13" eyebrow="WORKLOAD SORT" sourceLabel="2023 PAPER 3 THEMES" syllabusLabel="15.1 · APPLY" title="Classify from the workload—not from the number of labels." className="a2-slide a2-at-slide"><CompareTable headers={["Workload", "Class", "Evidence"]} rows={[["brightness across pixels", "SIMD", "same operation, many data"], ["independent app threads", "MIMD", "different operations and data"], ["single sequential payroll", "SISD", "one stream of each"], ["several checks of one sensor", "MISD", "different operations, same data"]]} /></Slide> },
    { time: "8 min", focus: "Apply accurate descriptions to current Paper 3 styles.", prompt: "Write one defining sentence and one mechanism sentence.", source: "Adapted from Cambridge 9618/32 O/N 2023 Q10 and 9618/31 M/J 2023 Q8.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/32 O/N 2023 Q10 · 9618/31 M/J 2023 Q8" syllabusLabel="15.1 · 5 MARKS" title="Describe SIMD and a massively parallel computer." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/32 O/N 2023 Q10 + 9618/31 M/J 2023 Q8 · ADAPTED" marks={5} prompt={<p>Describe SIMD processing [2] and a massively parallel computer [3].</p>} answer={<ul><li>SIMD uses one instruction stream on multiple data streams simultaneously. [2]</li><li>A massively parallel system uses a very large number of processors/separate computers for coordinated simultaneous computation. [2]</li><li>They communicate by messages over network infrastructure. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve all four classes and the massive workflow.", prompt: "Students give a definition before an example for every acronym.", source: "Syllabus 15.1 synthesis; coursebook pp.344–346.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch18 · SYLLABUS p.34" syllabusLabel="15.1 · CHECKPOINT" title="Count the streams. Then explain the coordination." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>SISD</span><p>One instruction · one data.</p></article><article><span>SIMD</span><p>One instruction · many data.</p></article><article><span>MISD</span><p>Many instructions · one data.</p></article><article><span>MIMD</span><p>Many instructions · many data.</p></article></section><div className="homework-callout"><b>HOMEWORK 12</b><span>30 marks · Flynn classes + massively parallel systems</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="12" title="Parallel processing architectures" syllabusLabel="SYLLABUS 15.1" sourceLabel="TEXTBOOK Ch18 · pp.344–346" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 15.1 p.34 · endorsed coursebook Chapter 18 printed pp.344–346 · verified 2023 Paper 3 questions and mark schemes" sourceDetail="The classification always uses instruction and data streams; the lesson explicitly separates SIMD from pipelining and treats massively parallel coordination as a networked workflow." />;
}
