"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Read the model", subtitle: "Cardinality, keys and E-R structure", marks: 10,
    questions: [
      { id: "l37-1", marks: 3, lines: 3, prompt: <><b>Distinguish one-to-one, one-to-many and many-to-many relationships.</b></>, answer: <p>1:1 means one instance on each side can relate to at most one on the other. 1:M means one parent can relate to many child rows, while each child relates to one parent. M:M means many instances on each side can relate to many on the other and normally needs a link entity. <em>[3]</em></p> },
      { id: "l37-2", marks: 4, lines: 4, prompt: <><b>Explain how to replace a many-to-many STUDENT–CLUB relationship.</b></>, answer: <p>Create a MEMBERSHIP link table/entity between STUDENT and CLUB. Its rows contain StudentID and ClubID as foreign keys; together they may form a composite primary key (or an added MembershipID may be the PK with a uniqueness rule). This creates STUDENT 1:M MEMBERSHIP and CLUB 1:M MEMBERSHIP. <em>[4]</em></p> },
      { id: "l37-3", marks: 3, lines: 3, prompt: <><b>Describe three features that a complete logical E-R diagram should show.</b></>, answer: <p>Named entities/tables; relationships with correct cardinality (1:1, 1:M or resolved M:M); and key attributes/foreign-key links where the notation requires them. Award one per valid feature. <em>[3]</em></p> },
    ],
  },
  {
    code: "B", title: "Normalise the data", subtitle: "Atomic values, repeating groups and partial dependencies", marks: 10,
    questions: [
      { id: "l37-4", marks: 3, lines: 3, prompt: <><b>State the conditions for a relation to be in 1NF.</b></>, answer: <p>Each field contains one atomic value; there are no repeating groups/multivalued columns; and each row is identifiable by a key. The key requirement supports a valid relation, while the examinable distinction is atomic values/no repeating groups. <em>[3]</em></p> },
      { id: "l37-5", marks: 3, lines: 3, prompt: <><b>Define partial dependency and explain why it violates 2NF.</b></>, answer: <p>A partial dependency exists when a non-key attribute depends on only part of a composite primary key. 2NF requires 1NF and every non-key attribute to depend on the whole primary key, so the partially dependent attribute belongs in a separate table. <em>[3]</em></p> },
      { id: "l37-6", marks: 4, lines: 5, prompt: <><b>Normalise ENROLMENT(StudentID, StudentName, CourseID, CourseTitle) to 2NF. The primary key is (StudentID, CourseID).</b></>, answer: <p>STUDENT(<u>StudentID</u>, StudentName); COURSE(<u>CourseID</u>, CourseTitle); ENROLMENT(<u>StudentID</u>, <u>CourseID</u>), with both ENROLMENT fields also foreign keys. StudentName depends only on StudentID and CourseTitle only on CourseID, so both partial dependencies are removed. <em>[4]</em></p> },
    ],
  },
  {
    code: "C", title: "Published E-R and integrity context", subtitle: "STUDENT, PLACEMENT and COMPANY", marks: 10,
    questions: [
      { id: "l37-7", marks: 2, lines: 2, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Complete the cardinalities for STUDENT–PLACEMENT–COMPANY.</b><p>Adapted from 9618/11 O/N 2025 Q2(a). [2]</p></>, answer: <p>STUDENT 1:M PLACEMENT and COMPANY 1:M PLACEMENT. One student/company can have many placement rows; each placement references one student and one company. <em>[2]</em></p> },
      { id: "l37-8", marks: 3, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain referential integrity using the three-table placement design.</b><p>Adapted from 9618/11 O/N 2025 Q2(d). [3]</p></>, answer: <p>Every non-null PLACEMENT.StudentID must match STUDENT.StudentID and every PLACEMENT.CompanyID must match COMPANY.CompanyID. A key update/delete must be rejected or cascaded so no placement becomes orphaned and related data remains consistent. <em>[3]</em></p> },
      { id: "l37-9", marks: 2, lines: 2, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Give two reasons a set of placement tables could be in 3NF.</b><p>Adapted from 9618/11 O/N 2025 Q2(b). [2]</p></>, answer: <p>Any two: no repeating groups/fields are atomic; no unresolved many-to-many relationship; no partial dependency; no transitive dependency; every non-key attribute depends on the key, the whole key and nothing but the key. <em>[2]</em></p> },
      { id: "l37-10", marks: 3, lines: 3, prompt: <><b>Explain why normalisation can improve integrity but does not by itself guarantee accurate input.</b></>, answer: <p>Normalisation gives each fact one appropriate home and reduces update/insert/delete anomalies, so consistent updates are easier. Incorrect data can still be entered into a valid table unless validation, verification and other integrity constraints are also applied. <em>[3]</em></p> },
    ],
  },
];

export default function Lesson37Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Turn a familiar many-to-many situation into a modelling problem.", prompt: "Ask: one student joins many clubs; one club has many students—where does one membership live?", source: "Coursebook 11.03-11.05 printed pp.162-166; syllabus 8.1.", content: <Slide number="01" eyebrow="CHAPTER 8 · MODEL THE RELATIONSHIPS" sourceLabel="TEXTBOOK CH.11 · pp.162-166" syllabusLabel="SYLLABUS 8.1" className="da-title"><section className="da-title-grid"><div className="da-title-copy"><span>LESSON 37 · 90 MINUTES</span><h1>Draw the links.<br /><em>Remove the repeats.</em></h1><p>Use cardinality and E-R diagrams to expose structure, then normalise unstructured data into 1NF and 2NF.</p></div><div className="da-title-map"><div><b>1:1</b><span>ONE MATCH EACH SIDE</span></div><div><b>1:M</b><span>PARENT TO MANY CHILDREN</span></div><div><b>M:M</b><span>RESOLVE WITH A LINK ENTITY</span></div><div><b>2NF</b><span>DEPEND ON THE WHOLE KEY</span></div></div></section></Slide> },
    { time: "5 min", focus: "State the precise boundary: relationships, E-R modelling and normalisation only to 2NF today.", prompt: "Point out that 3NF and DBMS features continue next lesson.", source: "Syllabus 8.1 pp.25-26; Coursebook 11.03-11.05 printed pp.162-166.", content: <Slide number="02" eyebrow="TEXTBOOK × SYLLABUS" sourceLabel="TEXTBOOK §§11.03-11.05 · pp.162-166" syllabusLabel="SYLLABUS 8.1" title="Relationships → E-R design → UNF → 1NF → 2NF."><section className="da-grid four"><article className="da-card"><span>CARDINALITY</span><p>one-to-one, one-to-many and many-to-many</p></article><article className="da-card"><span>E-R DIAGRAM</span><p>entities and labelled relationships document logical design</p></article><article className="da-card"><span>1NF</span><p>atomic values and no repeating groups</p></article><article className="da-card"><span>2NF</span><p>1NF plus no non-key dependency on only part of a composite key</p></article></section><p className="da-note">Syllabus continuation: 3NF and complete normalised designs are consolidated in Lesson 38.</p></Slide> },
    { time: "6 min", focus: "Define the three cardinalities through constraints, not line decoration.", prompt: "Read each relationship in both directions.", source: "Coursebook 11.03 printed pp.162-164; syllabus 8.1 relationships.", content: <Slide number="03" eyebrow="CARDINALITY STATES THE RULE" sourceLabel="TEXTBOOK §11.03 · pp.162-164" syllabusLabel="SYLLABUS 8.1" title="How many instances may participate on each side?"><section className="da-grid three"><article className="da-card"><span>ONE-TO-ONE · 1:1</span><h3>PERSON — PASSPORT</h3><p>Each current passport belongs to one person; each person has at most one current passport.</p></article><article className="da-card"><span>ONE-TO-MANY · 1:M</span><h3>TUTOR — STUDENT</h3><p>One tutor supports many students; each student has one tutor.</p></article><article className="da-card"><span>MANY-TO-MANY · M:M</span><h3>STUDENT — CLUB</h3><p>Many students join many clubs; resolve this before implementing relations.</p></article></section></Slide> },
    { time: "6 min", focus: "Resolve many-to-many through an associative/link entity.", prompt: "Ask which table stores JoinedDate and why it belongs to the relationship.", source: "Coursebook 11.03-11.04 printed pp.163-165; syllabus 8.1 E-R design.", content: <Slide number="04" eyebrow="RESOLVE M:M" sourceLabel="TEXTBOOK §§11.03-11.04" syllabusLabel="SYLLABUS 8.1" title="Turn one many-to-many link into two one-to-many links."><section className="da-erd"><article className="da-entity"><h3>STUDENT</h3><p className="key">StudentID · PK</p><p>StudentName</p></article><div className="da-relation"><b>1</b><i /><b>M</b></div><article className="da-entity"><h3>MEMBERSHIP</h3><p className="key">StudentID · PK/FK</p><p className="key">ClubID · PK/FK</p><p>JoinedDate</p></article></section><p className="da-note">A second 1:M link connects CLUB to MEMBERSHIP. The composite key (StudentID, ClubID) prevents duplicate memberships.</p></Slide> },
    { time: "6 min", focus: "Teach a disciplined E-R reading routine.", prompt: "Students narrate STUDENT 1:M PLACEMENT and COMPANY 1:M PLACEMENT in words.", source: "Coursebook 11.04 printed pp.164-165; syllabus 8.1 E-R diagrams.", content: <Slide number="05" eyebrow="READ AN E-R DIAGRAM" sourceLabel="TEXTBOOK §11.04 · pp.164-165" syllabusLabel="SYLLABUS 8.1" title="Entity names are nouns; relationships express business rules."><section className="da-flow"><span>NAME EACH<br />ENTITY TYPE</span><i>→</i><span>READ EACH LINK<br />BOTH WAYS</span><i>→</i><span>CHECK 1:1,<br />1:M OR M:M</span><i>→</i><span>PLACE FK ON<br />THE MANY SIDE</span></section><p className="da-warning">Cardinality describes permitted instances, not the current number of rows. A company with no placement today can still be on the “one” side of a 1:M design.</p></Slide> },
    { time: "6 min", focus: "Define 1NF through atomicity and repeating-group removal.", prompt: "Split ClubIDs='C1,C7,C9' without simply making ClubID1, ClubID2, ClubID3.", source: "Coursebook 11.05 printed pp.165-167; syllabus 8.1 1NF.", content: <Slide number="06" eyebrow="FIRST NORMAL FORM · 1NF" sourceLabel="TEXTBOOK §11.05 · pp.165-167" syllabusLabel="SYLLABUS 8.1" title="One value per field; no repeating group."><table className="da-table"><thead><tr><th>UNNORMALISED</th><th>WHY IT FAILS</th><th>1NF REPAIR</th></tr></thead><tbody><tr><td>StudentID, Name, ClubIDs</td><td>ClubIDs contains several values</td><td>separate MEMBERSHIP rows</td></tr><tr><td>BookID, Author1, Author2, Author3</td><td>repeating Author fields</td><td>BOOK_AUTHOR link rows</td></tr><tr><td>OrderID, (ItemID, Quantity)*</td><td>repeating item group</td><td>ORDER_LINE relation</td></tr></tbody></table><p className="da-note">1NF does not mean “one table”. It often creates more rows or a separate link table so every field is atomic.</p></Slide> },
    { time: "6 min", focus: "Define 2NF with functional dependency and a composite-key example.", prompt: "Draw arrows from each part of (StudentID, CourseID) to its dependent attribute.", source: "Coursebook 11.05 printed pp.165-167, corrected terminology; syllabus 8.1 2NF.", content: <Slide number="07" eyebrow="SECOND NORMAL FORM · 2NF" sourceLabel="TEXTBOOK §11.05 · pp.165-167" syllabusLabel="SYLLABUS 8.1" title="Every non-key attribute depends on the whole primary key."><section className="da-grid three"><article className="da-card"><span>COMPOSITE KEY</span><h3>(StudentID, CourseID)</h3><p>Together they identify one enrolment.</p></article><article className="da-card"><span>PARTIAL DEPENDENCY</span><h3>StudentID → StudentName</h3><p>Name depends on only one part of the key.</p></article><article className="da-card"><span>REPAIR</span><h3>Move the fact</h3><p>STUDENT(StudentID, StudentName) gives it the correct home.</p></article></section><p className="da-warning">With a single-attribute primary key, partial dependency cannot occur; a 1NF table is therefore automatically in 2NF.</p></Slide> },
    { time: "7 min", focus: "Work one complete UNF-to-2NF transformation.", prompt: "Students identify repeating groups first, then partial dependencies.", source: "Coursebook 11.05 method printed pp.165-167; syllabus 8.1 normalisation.", content: <Slide number="08" eyebrow="WORKED NORMALISATION" sourceLabel="TEXTBOOK §11.05 · METHOD" syllabusLabel="SYLLABUS 8.1" title="ENROLMENT: from repeated course data to 2NF."><section className="da-normal"><article><b>UNF</b><p>STUDENT(StudentID, Name, (CourseID, CourseTitle, Grade)*)</p></article><i>→</i><article><b>1NF</b><p>ENROLMENT(<u>StudentID</u>, <u>CourseID</u>, Name, CourseTitle, Grade)</p></article><i>→</i><article><b>2NF</b><p>STUDENT(<u>StudentID</u>, Name)<br />COURSE(<u>CourseID</u>, CourseTitle)<br />ENROLMENT(<u>StudentID</u>, <u>CourseID</u>, Grade)</p></article></section><p className="da-note">Grade depends on the whole composite key: it is the grade for one student on one course.</p></Slide> },
    { time: "6 min", focus: "Separate normal-form rules that students often conflate.", prompt: "Students match each defect to the first normal form it violates.", source: "Coursebook 11.05, corrected with standard dependency definitions; syllabus 8.1.", content: <Slide number="09" eyebrow="MISCONCEPTION AUDIT" sourceLabel="TEXTBOOK §11.05 · CORRECTED" syllabusLabel="SYLLABUS 8.1" title="Atomicity is not the same as dependency."><section className="da-compare"><div><span>DEFECT</span><span>FIRST RULE BROKEN</span><span>REPAIR TEST</span></div><div><b>one cell stores three phone numbers</b><span>1NF</span><span>Does each field contain one atomic value?</span></div><div><b>CourseTitle depends only on CourseID within composite key</b><span>2NF</span><span>Does every non-key attribute need the whole key?</span></div><div><b>DepartmentName depends on DepartmentID, a non-key attribute</b><span>3NF</span><span>Does any non-key attribute determine another?</span></div></section><p className="da-note">The 3NF row previews Lesson 38; do not use it to redefine 2NF.</p></Slide> },
    { time: "6 min", focus: "Guide a design from scenario to E-R structure and 2NF tables.", prompt: "Pairs model doctors, patients and appointments; compare the key placement.", source: "Syllabus 8.1 produce database design; Coursebook 11.03-11.05.", content: <Slide number="10" eyebrow="GUIDED DESIGN · CLINIC" sourceLabel="TEXTBOOK §§11.03-11.05 · APPLICATION" syllabusLabel="SYLLABUS 8.1" title="One doctor sees many appointments; one patient books many appointments."><pre className="da-code">DOCTOR(<strong>DoctorID</strong>, DoctorName){"\n"}PATIENT(<strong>PatientID</strong>, PatientName){"\n"}APPOINTMENT(<strong>AppointmentID</strong>, <span className="accent">DoctorID</span>, <span className="accent">PatientID</span>, StartTime, Reason)</pre><section className="da-flow"><span>DOCTOR<br />1:M APPOINTMENT</span><i>+</i><span>PATIENT<br />1:M APPOINTMENT</span><i>→</i><span>NO DIRECT<br />M:M TABLE LINK</span><i>→</i><span>VALID FKs<br />PROTECT LINKS</span></section></Slide> },
    { time: "7 min", focus: "Teach students to score cardinality and referential-integrity points separately.", prompt: "Require table/field names in integrity explanations when a schema is supplied.", source: "9618/11 O/N 2025 Q2(a), Q2(d) published mark scheme.", content: <Slide number="11" eyebrow="EXAM METHOD · GENERIC + SPECIFIC" sourceLabel="9618/11 O/N 2025 · Q2" syllabusLabel="SYLLABUS 8.1 — PAPER 1" title="State the rule, then apply it to named keys."><section className="da-grid three"><article className="da-card"><span>1 · RULE</span><p>Every non-null foreign key must match a referenced key.</p></article><article className="da-card"><span>2 · APPLY</span><p>PLACEMENT.CompanyID must exist in COMPANY.CompanyID.</p></article><article className="da-card"><span>3 · CONSEQUENCE</span><p>Reject or cascade a change so no orphan placement remains.</p></article></section><p className="da-warning">Generic integrity explanations may be capped. Use the entities and attributes named in the question.</p></Slide> },
    { time: "8 min", focus: "Attempt a published E-R cardinality item.", prompt: "Students draw both 1:M links before revealing.", source: "Adapted from 9618/11 O/N 2025 Q2(a), checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 2 MARKS" sourceLabel="9618/11 O/N 2025 · Q2(a)" syllabusLabel="SYLLABUS 8.1 — PAPER 1" title="Complete STUDENT–PLACEMENT–COMPANY cardinalities." className="slide--da-paper"><section className="da-paper-grid three"><article><span>STUDENT</span><p>Can one student have several placement records?</p></article><article><span>PLACEMENT</span><p>Which two parent rows does each placement reference?</p></article><article><span>COMPANY</span><p>Can one company host several placements?</p></article></section><ExamReveal><p>STUDENT 1:M PLACEMENT and COMPANY 1:M PLACEMENT. Each placement belongs to one student and one company; either parent may be referenced by many placement rows.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [2].</small></Slide> },
    { time: "8 min", focus: "Apply referential integrity to the same published schema.", prompt: "Write one generic rule and one named example before reveal.", source: "Adapted from 9618/11 O/N 2025 Q2(d), checked against published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 3 MARKS" sourceLabel="9618/11 O/N 2025 · Q2(d)" syllabusLabel="SYLLABUS 8.1 — PAPER 1" title="Explain referential integrity in the placement database." className="slide--da-paper"><section className="da-paper-grid"><article><span>FOREIGN-KEY MATCH</span><p>Use StudentID or CompanyID with both table names.</p></article><article><span>UPDATE / DELETE</span><p>Explain rejection, cascade or prevention of an orphan row.</p></article></section><ExamReveal><p>Each non-null PLACEMENT.StudentID and CompanyID must match an existing primary key in STUDENT or COMPANY. If a parent key is changed or deleted, related placement rows must be updated/deleted by a defined cascade or the operation rejected, keeping the data consistent.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [3].</small></Slide> },
    { time: "5 min", focus: "Retrieve relationships and the first two normal forms.", prompt: "Students complete each arrow with a rule and one example.", source: "Syllabus 8.1 synthesis; Coursebook 11.03-11.05.", content: <Slide number="14" eyebrow="MIXED RETRIEVAL" sourceLabel="TEXTBOOK §§11.03-11.05 · REVIEW" syllabusLabel="SYLLABUS 8.1" title="Model first; normalise second."><section className="da-flow"><span>READ<br />CARDINALITY</span><i>→</i><span>RESOLVE<br />M:M</span><i>→</i><span>REMOVE REPEATS<br />FOR 1NF</span><i>→</i><span>REMOVE PARTIAL<br />DEPENDENCIES FOR 2NF</span></section></Slide> },
    { time: "4 min", focus: "Close with an E-R and dependency check.", prompt: "One sentence per card; collect before students leave.", source: "Syllabus 8.1 checkpoint; Coursebook Chapter 11 sequence.", content: <Slide number="15" eyebrow="EXIT TICKET · NEXT: 3NF + DBMS" sourceLabel="TEXTBOOK CH.11 · pp.162-166" syllabusLabel="SYLLABUS 8.1" title="Three checks before 3NF."><section className="da-exit"><article><span>RELATIONSHIP</span><p>How do you resolve a many-to-many relationship?</p></article><article><span>1NF</span><p>What makes a field atomic?</p></article><article><span>2NF</span><p>What dependency must be removed?</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="37" slides={slides} homework={<HomeworkSheet lessonNumber="37" title="Relationships, E-R Diagrams and Normalisation to 2NF" marks={30} minutes={45} syllabusLabel="SYLLABUS 8.1" sourceLabel="TEXTBOOK CH.11 · pp.162-166 + PAPER 1" instructions="Read every relationship in both directions. In normalisation, name the current normal form, identify the exact dependency and show keys clearly in the repaired relations." sections={homeworkSections} challenge={{ id: "l37-challenge", prompt: <p><Mark>CHALLENGE</Mark> Explain why replacing a many-to-many relationship with a link entity can preserve extra facts about the relationship itself.</p>, answer: <p>The link entity represents each participation as its own row, so attributes such as JoinedDate, Role or Grade can describe that specific Student–Club or Student–Course pairing without belonging incorrectly to either parent entity.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 8.1, Coursebook Chapter 11 printed pp.162-166 (PDF pp.169-173) and published 2025 Paper 1 questions/mark scheme." sourceDetail="Core: 1:1, 1:M and M:M relationships, associative entities, E-R diagrams, referential integrity, 1NF and 2NF. Authentic anchors: 9618/11 O/N 2025 Q2(a) [2], Q2(b) [2] and Q2(d) [3]. 3NF and full database designs continue in Lesson 38." />;
}
