"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l23-reveal-${id}`;
  return <div className="asm-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className="asm-reveal__panel" hidden={!visible}>{children}</div></div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Instruction groups and effects", subtitle: "Predict what changes before tracing", marks: 10,
    questions: [
      { id: "l23-1", marks: 5, lines: 4, prompt: <><b>Give one valid opcode for each instruction group.</b><p>Data movement · input/output · arithmetic · compare · conditional/unconditional jump</p></>, answer: <p>Examples: <b>data movement</b> LDM/LDD/LDI/LDX/LDR/MOV/STO; <b>I/O</b> IN/OUT; <b>arithmetic</b> ADD/SUB/INC/DEC; <b>compare</b> CMP/CMI; <b>jump</b> JMP/JPE/JPN. <em>[1 suitable opcode per group]</em></p> },
      { id: "l23-2", marks: 5, lines: 5, prompt: <><b>State the effect of each instruction.</b><p>LDM #7 · LDI 20 · STO 31 · CMP #0 · JPN LOOP</p></>, answer: <p><b>LDM #7:</b> ACC←7. <b>LDI 20:</b> ACC←M[M[20]]. <b>STO 31:</b> M[31]←ACC. <b>CMP #0:</b> compare ACC with 0 without changing ACC. <b>JPN LOOP:</b> jump to LOOP if the previous comparison was false. <em>[1 each]</em></p> },
    ],
  },
  {
    code: "B", title: "Three authentic traces", subtitle: "Enter executed addresses and only the state changes", marks: 10,
    questions: [
      { id: "l23-3", marks: 3, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>M[10]=12, M[11]=11, M[12]=10, M[13]=22, M[14]=22.</b><pre className="asm-program">100 LDD 10{"\n"}101 ADD 12{"\n"}102 STO 11{"\n"}103 CMP 14{"\n"}104 JPE 107{"\n"}105 INC ACC{"\n"}106 JMP 101{"\n"}107 STO 10{"\n"}108 END</pre><p>Trace the program. Adapted from 9618/12 M/J 2025 Q7(a)(i). [3]</p></>, answer: <p>Trace-table addresses before END: <b>100,101,102,103,104,107</b>. State changes: 100 ACC=12; 101 ACC=22; 102 M[11]=22; 107 M[10]=22. CMP finds 22=22, so JPE takes the branch and execution then reaches END. <em>[3 shaded trace sections in the published scheme]</em></p> },
      { id: "l23-4", marks: 4, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>M[80]=10, M[81]=8, M[82]=80, M[83]=81.</b><pre className="asm-program">200 LDD 81   201 INC ACC   202 STO 83{"\n"}203 LDI 82   204 CMP 83   205 JPE 209{"\n"}206 LDD 83   207 ADD #10  208 JMP 210{"\n"}209 DEC ACC  210 STO 81   211 END</pre><p>Trace the program. Adapted from 9618/11 M/J 2025 Q8(a). [4]</p></>, answer: <p>Trace-table path before END: <b>200,201,202,203,204,205,206,207,208,210</b>. Changes: ACC 8→9; M[83]=9; indirect load gives ACC=M[M[82]]=M[80]=10; compare with 9 is false; LDD 83 gives ACC=9; ADD #10 gives ACC=19; M[81]=19. Instruction 209 is skipped; execution then reaches END. <em>[4]</em></p> },
      { id: "l23-5", marks: 3, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>M[50]=47, M[51]=48, M[52]=49, M[53]=50.</b><pre className="asm-program">500 LDM #50  501 DEC ACC  502 CMP 51{"\n"}503 JPE 505  504 JMP 501  505 STO 50{"\n"}506 SUB #10  507 STO 51  508 END</pre><p>Trace the program. Adapted from 9618/13 M/J 2025 Q5(a)(i). [3]</p></>, answer: <p>Trace-table path before END: <b>500,501,502,503,504,501,502,503,505,506,507</b>. ACC becomes 50, then 49; comparison with M[51]=48 is false, so it loops. ACC becomes 48; comparison is true; M[50]=48; ACC becomes 38; M[51]=38; execution then reaches END. <em>[3]</em></p> },
    ],
  },
  {
    code: "C", title: "Read and trace", subtitle: "Combine classification, state and control flow", marks: 10,
    questions: [
      { id: "l23-6", marks: 3, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Identify three groups to which assembly instructions can belong.</b><p>Adapted from 9618/13 O/N 2025 Q6(c). [3]</p></>, answer: <p><b>Data movement; arithmetic operations; conditional and unconditional jump instructions.</b> <em>[1 each—the three accepted groups in the published scheme]</em></p> },
      { id: "l23-7", marks: 7, lines: 5, prompt: <><b>M[20]=3, M[21]=1 and M[22]=0. Trace this countdown.</b><pre className="asm-program">100 LDD 20{"\n"}101 SUB 21{"\n"}102 STO 20{"\n"}103 CMP 22{"\n"}104 JPE 107{"\n"}105 JMP 100{"\n"}107 END</pre><p>Give the executed-address pattern, all changes to ACC/M[20], the number of SUB executions and the program’s effect.</p></>, answer: <p>First cycle: ACC 3→2, M[20]→2; compare false, jump to 100. Second: ACC 2→1, M[20]→1; loop. Third: ACC 1→0, M[20]→0; comparison true, jump to 107. Pattern is <b>100–105 repeated, then 100–104,107</b>. SUB executes <b>three</b> times. The program repeatedly decreases M[20] until it is zero. <em>[7]</em></p> },
    ],
  },
];

export default function Lesson23Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "3 min", focus: "Frame tracing as disciplined state bookkeeping, not guessing purpose.", prompt: "Ask which three things can change after one instruction.", source: "Syllabus 4.2 p.20; Coursebook Chapter 6 printed pp.98-106.", content: <Slide number="01" eyebrow="CHAPTER 4 · PROGRAM EXECUTION" sourceLabel="TEXTBOOK CH.6 · pp.98-106" syllabusLabel="SYLLABUS 4.2 · p.20" className="slide--asm-title"><section className="asm-title-grid"><div className="asm-title-copy"><span>LESSON 23 · 90 MINUTES</span><h1>Execute.<br /><em>Record. Branch.</em></h1><p>Trace one instruction at a time while protecting the exact state of ACC, IX and memory.</p></div><div className="asm-chip-stack"><p><b>ACC</b><span>current working value</span></p><p><b>MEMORY</b><span>changes only after STO</span></p><p><b>PATH</b><span>changes after jumps</span></p></div></section></Slide> },
    { time: "4 min", focus: "Set three concrete success criteria.", prompt: "Students identify the state, effect and next instruction in a trace row.", source: "Syllabus 4.2 trace and instruction-group objectives.", content: <Slide number="02" eyebrow="TODAY'S ROUTE" sourceLabel="SYLLABUS 4.2" syllabusLabel="SYLLABUS 4.2 — TRACE" title="Classify → execute → record → choose the next address."><section className="asm-route"><article><b>CLASSIFY</b><p>instruction group</p></article><article><b>EXECUTE</b><p>apply opcode + mode</p></article><article><b>RECORD</b><p>only changed state</p></article><article><b>BRANCH</b><p>select next instruction</p></article></section></Slide> },
    { time: "6 min", focus: "Define the state that a trace table must preserve.", prompt: "Ask which values remain unchanged after CMP and JMP.", source: "Coursebook tracing examples pp.104-106.", content: <Slide number="03" eyebrow="THE MACHINE STATE" sourceLabel="TEXTBOOK pp.104-106" syllabusLabel="SYLLABUS 4.2" title="Every row starts from the state left by the previous row."><section className="asm-state-strip"><article><span>ADDRESS</span><b>PC path</b></article><article><span>ACC</span><b>working data</b></article><article><span>IX</span><b>index offset</b></article><article><span>MEMORY</span><b>stored data</b></article></section><p className="asm-note">Do not reset ACC or memory between rows. A blank trace-table cell means “no change”, not zero.</p></Slide> },
    { time: "8 min", focus: "Organise the complete syllabus instruction set into five functional groups.", prompt: "Students supply one opcode per group from memory.", source: "Syllabus instruction set p.21; Coursebook 6.06 pp.98-103.", content: <Slide number="04" eyebrow="INSTRUCTION GROUPS" sourceLabel="TEXTBOOK 6.06 · pp.98-103" syllabusLabel="SYLLABUS 4.2 — GROUPS" title="The group predicts what kind of state may change."><section className="asm-card-grid five"><article className="asm-card"><span>MOVE</span><h3>LDM · LDD · LDI · LDX · LDR · MOV · STO</h3><p>register ↔ data</p></article><article className="asm-card"><span>I/O</span><h3>IN · OUT</h3><p>character data</p></article><article className="asm-card"><span>ARITHMETIC</span><h3>ADD · SUB · INC · DEC</h3><p>change a value</p></article><article className="asm-card"><span>COMPARE</span><h3>CMP · CMI</h3><p>set comparison result</p></article><article className="asm-card"><span>CONTROL</span><h3>JMP · JPE · JPN · END</h3><p>change path</p></article></section></Slide> },
    { time: "5 min", focus: "Read opcode, operand and representation markers accurately.", prompt: "Students interpret #10, B00001010 and &0A.", source: "Syllabus instruction notation p.21.", content: <Slide number="05" eyebrow="READ THE INSTRUCTION" sourceLabel="SYLLABUS TABLE · p.21" syllabusLabel="SYLLABUS 4.2" title="Opcode says what; operand says with what."><section className="asm-equation"><b>ADD</b><i>+</i><b>#10 / B00001010 / &0A</b><i>→</i><strong>same value: ten</strong></section><p className="asm-note"># is denary, B is binary and & is hexadecimal. An unmarked numeric operand is normally an address in the supplied instruction table.</p></Slide> },
    { time: "6 min", focus: "Give a safe row-by-row trace algorithm.", prompt: "Class applies the five verbs to LDI 82.", source: "Coursebook worked traces pp.104-106.", content: <Slide number="06" eyebrow="TRACE DISCIPLINE" sourceLabel="TEXTBOOK pp.104-106" syllabusLabel="SYLLABUS 4.2 — METHOD" title="One instruction; one complete decision."><section className="asm-mode-strip"><article><b>1 · FETCH ROW</b><code>address</code><p>write the executed address</p></article><article><b>2 · DECODE</b><code>opcode</code><p>state its effect</p></article><article><b>3 · RESOLVE</b><code>operand</code><p>apply addressing mode</p></article><article><b>4 · UPDATE</b><code>state</code><p>record changed cells</p></article><article><b>5 · NEXT</b><code>path</code><p>sequential or jump</p></article></section></Slide> },
    { time: "7 min", focus: "Begin a worked trace with load, arithmetic and store.", prompt: "Students predict each changed cell before it appears.", source: "Coursebook trace method pp.104-106.", content: <Slide number="07" eyebrow="WORKED TRACE · DATA PATH" sourceLabel="TEXTBOOK pp.104-106" syllabusLabel="SYLLABUS 4.2" title="Load changes ACC; store changes memory."><div className="asm-table-wrap"><table><thead><tr><th>Address</th><th>Instruction</th><th>ACC</th><th>M[11]</th></tr></thead><tbody><tr><td>100</td><td>LDD 10 · M[10]=12</td><td className="changed">12</td><td>11</td></tr><tr><td>101</td><td>ADD 12 · M[12]=10</td><td className="changed">22</td><td>11</td></tr><tr><td>102</td><td>STO 11</td><td>22</td><td className="changed">22</td></tr></tbody></table></div></Slide> },
    { time: "7 min", focus: "Separate comparison from conditional jump.", prompt: "Ask whether CMP or JPE changes ACC.", source: "Coursebook compare and jump instructions pp.100-101.", content: <Slide number="08" eyebrow="COMPARE THEN BRANCH" sourceLabel="TEXTBOOK pp.100-101" syllabusLabel="SYLLABUS 4.2 — CONTROL" title="CMP records a result; the following conditional instruction uses it."><section className="asm-memory-chain"><article><span>CMP 14</span><b>22 = M[14]</b></article><i>→</i><article><span>RESULT</span><b>TRUE</b></article><i>→</i><article><span>JPE 107</span><b>jump</b></article></section><p className="asm-note"><b>JPE</b> jumps when the comparison is true; <b>JPN</b> jumps when it is false. Neither changes ACC.</p></Slide> },
    { time: "6 min", focus: "Contrast conditional and unconditional changes of path.", prompt: "Students give the next address in three branch cases.", source: "Syllabus instruction table p.21.", content: <Slide number="09" eyebrow="NEXT-ADDRESS RULES" sourceLabel="SYLLABUS p.21" syllabusLabel="SYLLABUS 4.2 — JUMPS" title="The next row is not always the next number."><section className="asm-card-grid"><article className="asm-card"><span>JMP</span><h3>always jump</h3><p>next address = operand</p></article><article className="asm-card"><span>JPE</span><h3>jump if equal/true</h3><p>otherwise continue</p></article><article className="asm-card"><span>JPN</span><h3>jump if not equal/false</h3><p>otherwise continue</p></article></section></Slide> },
    { time: "8 min", focus: "Complete the worked trace and explain every blank cell.", prompt: "Pairs enter executed addresses before entering values.", source: "Adapted method from 9618/12 M/J 2025 Q7(a)(i).", content: <Slide number="10" eyebrow="COMPLETE WORKED TRACE" sourceLabel="9618/12 M/J 2025 · Q7(a)(i)" syllabusLabel="SYLLABUS 4.2 — TRACE" title="The equal comparison skips addresses 105 and 106."><div className="asm-table-wrap"><table><thead><tr><th>Address</th><th>Instruction</th><th>Changed state</th></tr></thead><tbody><tr><td>100</td><td>LDD 10</td><td>ACC=12</td></tr><tr><td>101</td><td>ADD 12</td><td>ACC=22</td></tr><tr><td>102</td><td>STO 11</td><td>M[11]=22</td></tr><tr><td>103</td><td>CMP 14</td><td>no data change; true</td></tr><tr><td>104</td><td>JPE 107</td><td>next=107</td></tr><tr><td>107</td><td>STO 10</td><td>M[10]=22</td></tr></tbody></table></div><p className="asm-note">The next instruction is END; the published trace stops after the final state-changing instruction.</p></Slide> },
    { time: "8 min", focus: "Use a verified 2025 trace under timed conditions.", prompt: "Four minutes trace, then reveal the path and changes.", source: "Adapted from 9618/12 M/J 2025 Q7(a)(i), checked against published mark scheme.", content: <Slide number="11" eyebrow="PAST PAPER PRACTICE · 3 MARKS" sourceLabel="9618/12 M/J 2025 · Q7(a)(i)" syllabusLabel="SYLLABUS 4.2 — EXAM" className="asm-paper" title="Trace until END: which addresses execute and what changes?"><section className="asm-paper-grid"><article><b>Initial data</b><p>M[10]=12, M[11]=11, M[12]=10, M[14]=22.</p></article><article><b>Core path</b><p>LDD 10 · ADD 12 · STO 11 · CMP 14 · JPE 107 · STO 10.</p></article></section><Reveal id="q7" visible={revealed.has("q7")} onToggle={toggleReveal}><p>100 ACC=12; 101 ACC=22; 102 M[11]=22; 103/104 no data change; branch to 107; 107 M[10]=22.</p></Reveal><small>Adapted from 9618/12 M/J 2025 Q7(a)(i).</small></Slide> },
    { time: "5 min", focus: "Use a verified instruction-group recall question.", prompt: "Students write three groups without opcodes, then self-mark.", source: "Adapted from 9618/13 O/N 2025 Q6(c).", content: <Slide number="12" eyebrow="PAST PAPER CHECK · 3 MARKS" sourceLabel="9618/13 O/N 2025 · Q6(c)" syllabusLabel="SYLLABUS 4.2 — EXAM" className="asm-paper" title="Identify three groups of assembly-language instructions."><section className="asm-paper-grid three"><article><b>GROUP 1</b></article><article><b>GROUP 2</b></article><article><b>GROUP 3</b></article></section><Reveal id="groups" visible={revealed.has("groups")} onToggle={toggleReveal}><p><strong>Data movement · arithmetic operations · conditional and unconditional jump instructions.</strong></p></Reveal><small>Adapted from 9618/13 O/N 2025 Q6(c).</small></Slide> },
    { time: "5 min", focus: "Repair trace-table errors before independent work.", prompt: "Students explain why each behaviour corrupts the trace.", source: "Recurring Paper 1 trace errors.", content: <Slide number="13" eyebrow="TRACE ERROR CLINIC" sourceLabel="EXAMINER LANGUAGE" syllabusLabel="SYLLABUS 4.2" title="Three habits that lose the path."><section className="asm-card-grid"><article className="asm-card"><span>DO NOT</span><h3>reset ACC</h3><p>carry state into the next row</p></article><article className="asm-card"><span>DO NOT</span><h3>write zero in blanks</h3><p>blank means no change</p></article><article className="asm-card"><span>DO NOT</span><h3>execute skipped lines</h3><p>follow the jump target</p></article></section></Slide> },
    { time: "7 min", focus: "Run a short independent loop trace and explain termination.", prompt: "Five minutes attempt; two minutes compare paths.", source: "Syllabus-style original trace.", content: <Slide number="14" eyebrow="TIMED TRACE · 7 MARKS" sourceLabel="SYLLABUS-STYLE ORIGINAL" syllabusLabel="SYLLABUS 4.2 — APPLY" className="asm-paper" title="M[20]=3, M[21]=1, M[22]=0. Count down to zero."><pre className="asm-program">100 LDD 20   101 SUB 21   102 STO 20{"\n"}103 CMP 22   104 JPE 107  105 JMP 100{"\n"}107 END</pre><Reveal id="count" visible={revealed.has("count")} onToggle={toggleReveal}><p>ACC/M[20] move 3→2→1→0 across three cycles. The first two comparisons are false; the third is true and JPE reaches END. SUB executes three times.</p></Reveal></Slide> },
    { time: "5 min", focus: "Close with the four decisions in every trace row.", prompt: "Students narrate one instruction using the exit frame.", source: "Syllabus 4.2 exit check.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK CH.6 · REVIEW" syllabusLabel="SYLLABUS 4.2" className="slide--asm-exit" title="Address. Effect. State. Next."><section className="asm-exit-grid"><article><b>EXECUTE</b><p>Which instruction?</p></article><article><b>CHANGE</b><p>Which ACC/IX/memory cell?</p></article><article><b>CONTINUE</b><p>Sequential or jump?</p></article></section><div className="asm-homework-callout"><b>HOMEWORK 23</b><span>30 marks · four verified Paper 1 anchors · inline answers</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="23" slides={slides} homework={<HomeworkSheet lessonNumber="23" title="Instruction Groups & Program Tracing" marks={30} minutes={45} syllabusLabel="SYLLABUS 4.2 · pp.20-21" sourceLabel="TEXTBOOK CH.6 · pp.98-106 + PAPER 1" instructions="Trace one executed instruction per row. Preserve the previous state, write only changed register/memory values and follow the actual branch path. Every adapted past-paper task is cited with component, session, question and marks." sections={homeworkSections} challenge={{ id: "l23-challenge", prompt: <p><Mark>CHALLENGE</Mark> Explain how a trace reveals an infinite loop without running forever.</p>, answer: <p>Identify a repeated machine state at the same instruction address: the same ACC/register/memory values and same comparison result will force the same future path. Once that state repeats with no external input, the execution cycle will repeat indefinitely.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 4.2 pp.20-21, Coursebook Chapter 6 printed pp.98-106, and published 2025 Paper 1 questions and mark schemes." sourceDetail="Core: data movement, input/output, arithmetic, compare and jump groups; opcode/operand notation; trace-table state; conditional and unconditional paths. Authentic anchors: 9618/12 M/J 2025 Q7(a)(i), 9618/11 M/J 2025 Q8(a), 9618/13 M/J 2025 Q5(a)(i), and 9618/13 O/N 2025 Q6(c). Every past-paper prompt is marked Adapted." />;
}
