"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

type GateName = "NOT" | "AND" | "OR" | "NAND" | "NOR" | "XOR";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l16-reveal-${id}`;
  return <div className="c3-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className={visible ? "c3-reveal__panel visible" : "c3-reveal__panel"} hidden={!visible}>{children}</div></div>;
}

function GateIcon({ name }: { name: GateName }) {
  const lower = name.toLowerCase();
  return <div className={`logic-gate logic-gate--${lower}`} role="img" aria-label={`${name} logic gate symbol`}><div className="logic-gate__drawing"><i className="logic-input logic-input--1" />{name !== "NOT" && <i className="logic-input logic-input--2" />}<span className="logic-shape" /><i className="logic-output" /></div><b>{name}</b></div>;
}

function TruthStrip({ outputs }: { outputs: string[] }) {
  return <div className="logic-table"><div className="logic-table__head"><b>A</b><b>B</b><b>C</b><strong>X</strong></div>{outputs.map((output, index) => <div key={`row-${index}`}><span>{index >> 2 & 1}</span><span>{index >> 1 & 1}</span><span>{index & 1}</span><strong>{output}</strong></div>)}</div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Statements and expressions", subtitle: "Define variables, preserve grouping and use two-input gates", marks: 10,
    questions: [
      { id: "l16-1", marks: 4, lines: 4, prompt: <><b>A greenhouse fan runs when the temperature is high AND the window is NOT open.</b><p>Let T=temperature high and W=window open. Write the expression and describe a valid two-gate circuit.</p></>, answer: <p><strong>X = T AND (NOT W).</strong> Feed W into a NOT gate; feed T and NOT W into a two-input AND gate. <em>[2 expression; 2 circuit]</em></p> },
      { id: "l16-2", marks: 6, lines: 5, prompt: <><b>An alarm sounds if a door is open OR a window is open, but only while the system is armed.</b><p>Let D, W and A represent the three conditions. Write the expression, state the first gate and describe the complete circuit.</p></>, answer: <p><strong>X = (D OR W) AND A.</strong> First combine D and W with OR. Feed that output and A into AND. The brackets preserve the required order. <em>[2 expression; 1 first gate; 3 complete circuit]</em></p> },
    ],
  },
  {
    code: "B", title: "Truth-table conversions", subtitle: "Use intermediate columns and write a sum-of-products expression", marks: 10,
    questions: [
      { id: "l16-3", marks: 6, lines: 5, prompt: <><b>Complete the output column for X = (A OR B) AND (NOT C).</b><p>Use rows ABC = 000, 001, 010, 011, 100, 101, 110, 111. Show the two intermediate columns.</p></>, answer: <p><strong>A OR B:</strong> 0,0,1,1,1,1,1,1. <strong>NOT C:</strong> 1,0,1,0,1,0,1,0. Final X: <strong>0,0,1,0,1,0,1,0</strong>. <em>[2 each intermediate column; 1 first four X; 1 final four X]</em></p> },
      { id: "l16-4", marks: 4, lines: 5, prompt: <><b>A truth table has X=1 only for rows 001, 010 and 100.</b><p>Write an expression that exactly represents these three rows.</p></>, answer: <p><strong>X = ((NOT A) AND (NOT B) AND C) OR ((NOT A) AND B AND (NOT C)) OR (A AND (NOT B) AND (NOT C)).</strong> Three-input AND terms must be built by cascading two-input AND gates. <em>[4]</em></p> },
    ],
  },
  {
    code: "C", title: "Authentic Paper 1 practice", subtitle: "Circuit, expression and problem-statement skills", marks: 10,
    questions: [
      { id: "l16-5", marks: 4, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Work in both directions.</b><p>(i) Draw the circuit for Q = NOT ((A NAND B) XOR ((NOT A) OR (NOT C))). [2]</p><p>(ii) A truth table has Q=1 only for RST rows 110 and 001. Write its expression. [2]</p><p>Adapted from 9618/11 O/N 2025 Q3(a)-(b).</p></>, answer: <p>(i) Form <strong>A NAND B</strong> and <strong>(NOT A) OR (NOT C)</strong>, feed both to XOR, then invert the output. <em>[2]</em> (ii) <strong>Q = (R AND S AND (NOT T)) OR ((NOT R) AND (NOT S) AND T)</strong>. <em>[2]</em></p> },
      { id: "l16-6", marks: 2, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>A security system defines A=external daylight is low, B=front door open, C=person within 2 m, D=back door open and E=system on.</b><p>Write X for the outside light: system on, daylight low and person close. Write Y for the alarm: system on and at least one of B, C or D. Adapted from 9618/11 O/N 2024 Q5(b). [2]</p></>, answer: <p><strong>X = E AND A AND C</strong>; <strong>Y = E AND (B OR C OR D)</strong>. Each three-input operation must be cascaded when drawn with two-input gates. <em>[1 each]</em></p> },
      { id: "l16-7", marks: 3, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>A greenhouse output is true only when both conditions hold:</b><p>(1) T is true and W is false; (2) at least one of R or M is false.</p><p>Describe the branch gates and final connection. Adapted from 9618/12 O/N 2022 Q3(a). [3]</p></>, answer: <p>Build <strong>T AND (NOT W)</strong> for the first branch. Build <strong>(NOT R) OR (NOT M)</strong> for the second branch. Feed both branch outputs into a final AND gate. <em>[1 each]</em></p> },
      { id: "l16-8", marks: 1, lines: 2, prompt: <><b>State one final check that can detect a conversion error.</b></>, answer: <p>Test one or more input rows through both representations and confirm the outputs match; or compare every row of their truth tables. <em>[1]</em></p> },
    ],
  },
];

export default function Lesson16Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "3 min", focus: "Frame the lesson as four equivalent representations of one logical rule.", prompt: "Ask which representation students find easiest to verify.", source: "Syllabus 3.2 p.18; Coursebook worked examples printed pp.71-75.", content: <Slide number="01" eyebrow="CHAPTER 3 · LOGIC" sourceLabel="TEXTBOOK CH.4 · pp.71-75" syllabusLabel="SYLLABUS 3.2 · p.18" className="slide--logic-title"><section className="logic-title-grid"><div><span>LESSON 16 · 90 MINUTES</span><h1>One rule.<br /><em>Four forms.</em></h1><p>Move safely between problem statements, expressions, logic circuits and truth tables.</p></div><div className="logic-conversion-wheel"><b>WORDS</b><span>→</span><b>EXPRESSION</b><span>→</span><b>CIRCUIT</b><span>→</span><b>TABLE</b></div></section></Slide> },
    { time: "4 min", focus: "Make every direction in the syllabus explicit.", prompt: "Students identify the input and output form for each route.", source: "Syllabus 3.2 p.18 conversion objectives.", content: <Slide number="02" eyebrow="THE COMPLETE SYLLABUS ROUTE" sourceLabel="SYLLABUS CONVERSIONS" syllabusLabel="SYLLABUS 3.2 · p.18" title="Read, build, tabulate—and reverse the process." className="slide--logic-convert"><section className="logic-four-form"><article><b>STATEMENT</b><p>meaning and conditions</p></article><i>↔</i><article><b>EXPRESSION</b><p>operators and brackets</p></article><i>↔</i><article><b>CIRCUIT</b><p>symbols and wires</p></article><i>↔</i><article><b>TRUTH TABLE</b><p>every input case</p></article></section></Slide> },
    { time: "5 min", focus: "Translate verbal clues without assuming that 1 means good or on.", prompt: "Underline all, any, not and exactly one in sample statements.", source: "Coursebook problem statements pp.71-72.", content: <Slide number="03" eyebrow="WORDS → OPERATORS" sourceLabel="TEXTBOOK pp.71-72" syllabusLabel="SYLLABUS 3.2" title="Underline the decision words first." className="slide--logic-language"><section className="logic-language-grid"><p><b>all / both</b><strong>AND</strong></p><p><b>any / at least one</b><strong>OR</strong></p><p><b>not / is false</b><strong>NOT</strong></p><p><b>exactly one / different</b><strong>XOR</strong></p></section><p className="c3-note">Define every variable before writing the expression.</p></Slide> },
    { time: "6 min", focus: "Model statement-to-expression grouping.", prompt: "Ask why removing the brackets changes the rule.", source: "Coursebook expression method pp.71-73.", content: <Slide number="04" eyebrow="STATEMENT → EXPRESSION" sourceLabel="TEXTBOOK pp.71-73" syllabusLabel="SYLLABUS 3.2" title="Group the conditions that must be combined first." className="slide--logic-expression"><section className="logic-worked-rule"><p>Alarm if <em>door OR window</em> is open,<br />but only when <em>armed</em>.</p><strong>X = (D OR W) AND A</strong><div><span>first branch</span><span>final decision</span></div></section></Slide> },
    { time: "5 min", focus: "Translate an expression into gates from the innermost brackets outward.", prompt: "Students number the operations in execution order.", source: "Coursebook circuit construction pp.72-73.", content: <Slide number="05" eyebrow="EXPRESSION → CIRCUIT" sourceLabel="TEXTBOOK pp.72-73" syllabusLabel="SYLLABUS 3.2" title="One operator becomes one gate." className="slide--logic-build"><p className="logic-expression">X = (A OR B) AND (NOT C)</p><section className="logic-build-flow"><div><span>A · B</span><GateIcon name="OR" /></div><i>+</i><div><span>C</span><GateIcon name="NOT" /></div><i>→</i><div><span>branch outputs</span><GateIcon name="AND" /></div><strong>X</strong></section></Slide> },
    { time: "7 min", focus: "Apply the syllabus rule that all gates except NOT have exactly two inputs.", prompt: "Class redesigns A AND B AND C without drawing a three-input gate.", source: "Syllabus 3.2 p.18: exactly two inputs except NOT.", content: <Slide number="06" eyebrow="CASCADE MULTIPLE CONDITIONS" sourceLabel="SYLLABUS INPUT RULE" syllabusLabel="SYLLABUS 3.2" title="Three conditions need two two-input gates." className="slide--logic-cascade"><section className="logic-cascade"><span>A</span><span>B</span><GateIcon name="AND" /><i>→</i><span>C</span><GateIcon name="AND" /><strong>X</strong></section><p className="c3-warning">Do not draw a three-input AND, OR, NAND, NOR or XOR in this syllabus.</p></Slide> },
    { time: "7 min", focus: "Read a circuit from inputs to output and preserve intermediate signals.", prompt: "Students name P and Q before writing X.", source: "Coursebook circuit-to-expression examples pp.73-74.", content: <Slide number="07" eyebrow="CIRCUIT → EXPRESSION" sourceLabel="TEXTBOOK pp.73-74" syllabusLabel="SYLLABUS 3.2" title="Name each wire; combine only at the final gate." className="slide--logic-read"><section className="logic-branch-read"><div><b>P</b><span>A OR B</span></div><div><b>Q</b><span>NOT C</span></div><i>→</i><strong>X = P AND Q<br />= (A OR B) AND (NOT C)</strong></section></Slide> },
    { time: "7 min", focus: "Build a truth table using intermediate columns rather than mental shortcuts.", prompt: "Calculate columns left to right for one row at a time.", source: "Coursebook truth-table construction pp.74-75.", content: <Slide number="08" eyebrow="EXPRESSION → TRUTH TABLE" sourceLabel="TEXTBOOK pp.74-75" syllabusLabel="SYLLABUS 3.2" title="Create one column for each operation." className="slide--logic-table"><section className="logic-table-method"><ol><li>List <b>2³ = 8</b> input rows.</li><li>Calculate <b>A OR B</b>.</li><li>Calculate <b>NOT C</b>.</li><li>AND the two columns.</li></ol><TruthStrip outputs={["0","0","1","0","1","0","1","0"]} /></section></Slide> },
    { time: "5 min", focus: "Verify the worked table before moving to reverse construction.", prompt: "Students predict which property all output-1 rows share.", source: "Derived syllabus practice from 3.2.", content: <Slide number="09" eyebrow="CHECK THE PATTERN" sourceLabel="DERIVED EXAM PRACTICE" syllabusLabel="SYLLABUS 3.2" title="For X = (A OR B) AND (NOT C), what makes X true?" className="slide--logic-check"><section className="logic-pattern"><b>AT LEAST ONE OF A/B IS TRUE</b><span>AND</span><b>C IS FALSE</b></section><Reveal id="pattern" visible={revealed.has("pattern")} onToggle={toggleReveal}><p>Output 1 occurs at 010, 100 and 110—exactly the rows where A OR B = 1 and C = 0.</p></Reveal></Slide> },
    { time: "6 min", focus: "Introduce truth-table-to-expression via output-1 rows.", prompt: "Build the term for row A,B,C = 0,1,0.", source: "Syllabus 3.2 truth table to expression; Coursebook pp.74-75.", content: <Slide number="10" eyebrow="TRUTH TABLE → EXPRESSION" sourceLabel="TEXTBOOK pp.74-75" syllabusLabel="SYLLABUS 3.2" title="Turn each output-1 row into an AND term; OR the terms." className="slide--logic-minterms"><section className="logic-minterm"><p><b>row 010</b><strong>(NOT A) AND B AND (NOT C)</strong></p><p><b>row 100</b><strong>A AND (NOT B) AND (NOT C)</strong></p><p><b>combine</b><strong>term 1 OR term 2 …</strong></p></section><p className="c3-note">A 0 input is written with NOT; a 1 input is written unchanged.</p></Slide> },
    { time: "6 min", focus: "Use a verified recent past-paper conversion in both directions.", prompt: "Pairs number the circuit operations, then build one term per output-1 row.", source: "Adapted from 9618/11 O/N 2025 Q3(a)-(b), checked against the published mark scheme.", content: <Slide number="11" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/11 O/N 2025 · Q3(a-b)" syllabusLabel="SYLLABUS 3.2 — EXAM PRACTICE" title="Expression → circuit. Truth table → expression." className="slide--c3-paper"><section className="logic-paper-branches"><p><b>P</b>A NAND B</p><p><b>Q</b>(NOT A) OR (NOT C)</p><p><b>FINAL</b>NOT (P XOR Q)</p><strong>Truth-table output 1 only at RST rows 110 and 001</strong></section><Reveal id="paper-expression" visible={revealed.has("paper-expression")} onToggle={toggleReveal}><p>Circuit: form P and Q, XOR them, then NOT the output. Table expression: <strong>(R AND S AND NOT T) OR (NOT R AND NOT S AND T)</strong>.</p></Reveal><small>Adapted from 9618/11 O/N 2025 Q3(a)-(b).</small></Slide> },
    { time: "7 min", focus: "Use an authentic problem-statement-to-expression task.", prompt: "Students write both expressions independently under timed conditions.", source: "Adapted from 9618/11 O/N 2024 Q5(b), checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 2 MARKS" sourceLabel="9618/11 O/N 2024 · Q5(b)" syllabusLabel="SYLLABUS 3.2 — EXAM PRACTICE" title="Translate two security rules into expressions." className="slide--c3-paper"><section className="logic-security-rule"><p><b>X</b> system E on AND daylight A low AND person C within 2 m</p><p><b>Y</b> system E on AND front door B, person C or back door D detected</p></section><Reveal id="security" visible={revealed.has("security")} onToggle={toggleReveal}><p><strong>X = E AND A AND C</strong><br /><strong>Y = E AND (B OR C OR D)</strong></p></Reveal><small>Adapted from 9618/11 O/N 2024 Q5(b).</small></Slide> },
    { time: "5 min", focus: "Run a complete problem-to-table workflow in pairs.", prompt: "Require variable definitions and intermediate columns.", source: "Syllabus-style original consolidation task.", content: <Slide number="13" eyebrow="PAIR CHALLENGE · FULL CHAIN" sourceLabel="SYLLABUS-STYLE ORIGINAL" syllabusLabel="SYLLABUS 3.2" title="A lamp turns on when it is dark AND motion is detected, OR when override is on." className="slide--logic-chain"><section className="logic-chain"><span>define D, M, O</span><i>→</i><span>write expression</span><i>→</i><span>draw circuit</span><i>→</i><span>build 8-row table</span></section><Reveal id="full-chain" visible={revealed.has("full-chain")} onToggle={toggleReveal}><p><strong>X = (D AND M) OR O.</strong> AND D/M first, then OR with O. Outputs for DMO 000→111: <b>0,1,0,1,0,1,1,1</b>.</p></Reveal></Slide> },
    { time: "12 min", focus: "Complete a mixed exam sprint and self-mark representation equivalence.", prompt: "Seven minutes individual, two minutes compare, three minutes mark.", source: "Adapted from 9618/13 O/N 2024 Q1(b)-(c) and 9618/12 O/N 2022 Q3(a).", content: <Slide number="14" eyebrow="CHAPTER 3 EXAM SPRINT · 7 MARKS" sourceLabel="PAPER 1 · 2022 / 2024" syllabusLabel="SYLLABUS 3.2 — EXAM PRACTICE" title="Attempt every conversion before revealing." className="slide--logic-sprint"><section className="logic-sprint-grid three"><article><b>2 marks</b><p>P=A NOR B; Q=A OR B; R=B AND C. P/Q feed AND; that result and R feed NAND. Write X.</p><span>9618/13 O/N 2024 Q1(b)</span></article><article><b>2 marks</b><p>Draw X=((NOT A AND (B AND C)) OR (B NAND C)) AND NOT A.</p><span>9618/13 O/N 2024 Q1(c)</span></article><article><b>3 marks</b><p>Draw a greenhouse output true only when both T AND NOT W, and NOT R OR NOT M, hold.</p><span>9618/12 O/N 2022 Q3(a)</span></article></section><Reveal id="sprint" visible={revealed.has("sprint")} onToggle={toggleReveal}><p><b>1</b> X=((A NOR B) AND (A OR B)) NAND (B AND C). <b>2</b> Build each bracket from the inside out, OR the first two branches, then AND with NOT A. <b>3</b> Build T AND NOT W; build NOT R OR NOT M; feed both to final AND.</p></Reveal></Slide> },
    { time: "5 min", focus: "Close the first three syllabus chapters with an actionable mastery check.", prompt: "Students name one secure skill and one item to revisit.", source: "Syllabus Chapters 1-3 completion check.", content: <Slide number="15" eyebrow="CHAPTERS 1–3 COMPLETE" sourceLabel="SYLLABUS pp.14-18" syllabusLabel="AS CONTENT · 1–3" title="Represent. Connect. Control. Decide." className="slide--c3-exit"><section className="logic-chapter-close"><p><b>CHAPTER 1</b>Data representation</p><p><b>CHAPTER 2</b>Communication</p><p><b>CHAPTER 3</b>Hardware + logic</p></section><div className="c3-homework-callout"><b>HOMEWORK 16</b><span>30 marks · three verified Paper 1 anchors · inline answers</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="16" slides={slides} homework={<HomeworkSheet lessonNumber="16" title="Logic Representation Conversions" marks={30} minutes={45} syllabusLabel="SYLLABUS 3.2 · p.18" sourceLabel="TEXTBOOK CH.4 · pp.71-75 + PAPER 1" instructions="Show intermediate expressions and truth-table columns. Except for NOT, build every multi-condition rule from two-input gates. Past-paper prompts are concise adaptations with original references." sections={homeworkSections} challenge={{ id: "l16-challenge", prompt: <p><Mark>CHALLENGE</Mark> Write an expression for a 2-out-of-3 majority decision, where X=1 when at least two of A, B and C are 1.</p>, answer: <p><strong>X = (A AND B) OR (A AND C) OR (B AND C).</strong> Each pair detects one way that at least two inputs are 1; cascade the final OR operations using two-input gates.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 3.2 p.18, Coursebook Chapter 4 printed pp.71-75, and published 2022-2025 Paper 1 questions and mark schemes." sourceDetail="Core: construct circuits, truth tables and expressions from problem statements and from each other. Authentic anchors: 9618/11 O/N 2025 Q3(a)-(b), 9618/13 O/N 2024 Q1(b)-(c), 9618/11 O/N 2024 Q5(b), and 9618/12 O/N 2022 Q3(a). Gates other than NOT are treated as exactly two-input gates. Boolean simplification, De Morgan's laws and Karnaugh maps are outside this AS section." />;
}
