"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { LayerStack, PacketRoute } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Protocol foundations", subtitle: "Explain why shared rules are essential", marks: 10,
    questions: [
      { id: "a2-07-1", marks: 3, lines: 4, prompt: <><b>Define a communication protocol.</b><p>Include two categories of rule that it may specify.</p></>, answer: <p>A protocol is an agreed or common set of rules for communication <em>[1]</em>. It may define any two of data format, timing, sequence/order, addressing, error checking or acknowledgement <em>[2]</em>.</p> },
      { id: "a2-07-2", marks: 3, lines: 4, prompt: <><b>Explain why protocols are essential</b> when two computers communicate.</>, answer: <p>Both devices must use the same rules/standard <em>[1]</em>, so data is interpreted correctly <em>[1]</em> and different hardware, operating systems or manufacturers can interoperate <em>[1]</em>.</p> },
      { id: "a2-07-3", marks: 4, lines: 5, prompt: <><b>Two devices agree on the data format but not its timing or acknowledgement rules.</b><p>Explain two possible consequences.</p></>, answer: <p>A receiver may sample or read at the wrong time and lose/corrupt data <em>[2]</em>. A sender may not know whether data arrived, so missing data is not resent or a successful message is duplicated <em>[2]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Four-layer TCP/IP suite", subtitle: "Use current 2027–2029 layer names", marks: 10,
    questions: [
      { id: "a2-07-4", marks: 3, lines: 4, prompt: <><b>State the four TCP/IP layers</b> in order from the user-facing layer downwards.</>, answer: <p><strong>Application</strong> <em>[1]</em>, <strong>Transport</strong> <em>[1]</em>, then <strong>Internet</strong> and <strong>Link</strong> in that order <em>[1]</em>.</p> },
      { id: "a2-07-5", marks: 3, lines: 5, prompt: <><b>Describe the Transport layer.</b></>, answer: <p>It provides end-to-end delivery <em>[1]</em>, splits data into segments/packets and adds sequence/control information <em>[1]</em>, and supports reliability such as checking, acknowledgements or retransmission <em>[1]</em>.</p> },
      { id: "a2-07-6", marks: 4, lines: 6, prompt: <><b>Distinguish the Internet and Link layers.</b></>, answer: <p>The Internet layer uses source/destination IP addresses and routing between networks <em>[2]</em>. The Link layer creates frames and manages local-network delivery/access to the transmission medium <em>[2]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Host-to-host transfer", subtitle: "Apply the stack as an exam sequence", marks: 10,
    questions: [
      { id: "a2-07-7", marks: 3, lines: 5, prompt: <><b>Explain what happens to control information</b> as data moves down the sender&apos;s stack and up the receiver&apos;s stack.</>, answer: <p>Each relevant sender layer adds its header/control information <em>[1]</em>. The corresponding receiver layers inspect it <em>[1]</em> and remove it as the message moves upwards <em>[1]</em>.</p> },
      { id: "a2-07-8", marks: 3, lines: 5, prompt: <><b>Explain how layers in a protocol stack interact.</b></>, answer: <p>Each layer has a distinct function <em>[1]</em>, exchanges data through a defined interface with adjacent layers <em>[1]</em>, and uses services below while providing services to the layer above <em>[1]</em>.</p> },
      { id: "a2-07-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Describe four interactions in the TCP/IP protocol stack.</b></p><p>Adapted from 9618/31 O/N 2024 Q4. [4]</p></>, answer: <p>Award one mark each for four valid points: adjacent layers exchange input/output; a defined interface connects adjacent layers; layers add/remove headers; most layer behaviour is software; the user/application interacts at Application; hardware/network-medium access is at Link.</p> },
    ],
  },
];

export default function A2Lesson07Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Expose the need for common communication rules.", prompt: "Students propose three rules that two incompatible devices must agree.", source: "2027–2029 syllabus 14.1; coursebook Chapter 17 printed pp.331–333.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch17" syllabusLabel="SYLLABUS 14.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 07 · 90 MINUTES</span><h1>Agree the rules.<br /><em>Move the message.</em></h1><p>Communication protocols · four-layer TCP/IP · host-to-host transfer</p></div><div className="a2-at-hero" role="img" aria-label="Four protocol layers surrounding a message"><strong>MESSAGE</strong><span>APPLICATION</span><span>TRANSPORT</span><span>INTERNET</span><span>LINK</span></div></section></Slide> },
    { time: "5 min", focus: "Map every lesson objective to the current syllabus.", prompt: "Why must the exam answer use four layers rather than the textbook's older five-layer diagram?", source: "Syllabus p.33; coursebook pp.331–334.", content: <Slide number="02" eyebrow="SOURCE MAP" sourceLabel="SYLLABUS p.33 · TEXTBOOK pp.331–334" syllabusLabel="14.1 · PROTOCOLS" title="Use the current four-layer model in every exam answer." className="a2-slide a2-at-slide"><ConceptCards columns={3} items={[{ eyebrow: "RULES", title: "Why protocols?", body: "Shared format, timing, order and control." }, { eyebrow: "STACK", title: "Four functions", body: "Application · Transport · Internet · Link." }, { eyebrow: "JOURNEY", title: "Down, across, up", body: "Headers added, used and removed." }]} /><p className="a2-alert"><b>Version control</b><span>The 2027–2029 syllabus uses <strong>Internet</strong> where the older textbook says Network, and its <strong>Link</strong> layer covers the textbook&apos;s Data Link + Physical layers. Write the current four names in the exam.</span></p></Slide> },
    { time: "5 min", focus: "Diagnose communication failures caused by mismatched rules.", prompt: "Match each symptom to format, timing, ordering or acknowledgement.", source: "Coursebook §17.02 p.331; syllabus 14.1.", content: <Slide number="03" eyebrow="DO NOW · FAILURE CLINIC" sourceLabel="TEXTBOOK p.331" syllabusLabel="14.1 · WHY PROTOCOLS" title="A cable is not enough: both ends must interpret the same exchange." className="a2-slide a2-at-slide"><CompareTable headers={["Mismatch", "Possible symptom", "Rule needed"]} rows={[["format", "fields decoded incorrectly", "structure / encoding"], ["timing", "receiver samples too early", "speed / synchronisation"], ["order", "parts form the wrong message", "sequence numbers"], ["reliability", "loss goes unnoticed", "acknowledge / resend"]]} /></Slide> },
    { time: "6 min", focus: "Build an exam-ready definition of protocol.", prompt: "Students improve a one-mark definition into a two-mark definition.", source: "Coursebook §17.02 p.331; 9618/32 M/J 2024 Q2(a).", content: <Slide number="04" eyebrow="DEFINITION" sourceLabel="TEXTBOOK p.331 · M/J 2024 Q2" syllabusLabel="14.1 · PROTOCOL" title="A protocol is an agreed set of rules governing communication." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "FORMAT", title: "How data is structured" }, { eyebrow: "TIMING", title: "When data is sent" }, { eyebrow: "ORDER", title: "Which part comes next" }, { eyebrow: "CONTROL", title: "Check · acknowledge · resend" }]} /></Slide> },
    { time: "6 min", focus: "Explain interoperability rather than merely define it.", prompt: "Give a linked explanation using devices from different manufacturers.", source: "Syllabus 14.1; published Paper 3 mark schemes 2022–2024.", content: <Slide number="05" eyebrow="WHY ESSENTIAL?" sourceLabel="9618 PAPER 3 MARK POINTS" syllabusLabel="14.1 · EXPLAIN" title="A shared standard lets unlike systems exchange data correctly." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "SENDER", title: "Encodes by the rules", body: "Known fields, timing and control data." }, { eyebrow: "STANDARD", title: "Bridges differences", body: "Hardware, OS and manufacturer may differ." }, { eyebrow: "RECEIVER", title: "Decodes by the same rules", body: "The intended message is reconstructed." }]} /></Slide> },
    { time: "6 min", focus: "Explain why a suite contains multiple cooperating protocols.", prompt: "Why is one giant protocol harder to design, test and change?", source: "Coursebook §§17.03–17.04 pp.331–332.", content: <Slide number="06" eyebrow="FROM PROTOCOL TO SUITE" sourceLabel="TEXTBOOK pp.331–332" syllabusLabel="14.1 · STACK" title="Layering decomposes one communication problem into stable services." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "DECOMPOSE", title: "One job per layer" }, { eyebrow: "INTERFACE", title: "Adjacent layers exchange data" }, { eyebrow: "REUSE", title: "Upper layers use lower services" }, { eyebrow: "CHANGE", title: "Replace one layer with less disruption" }]} /></Slide> },
    { time: "6 min", focus: "Model adjacent-layer interaction precisely.", prompt: "Students draw arrows only between valid neighbours.", source: "Coursebook §17.03 p.331; 9618/31 O/N 2024 Q4.", content: <Slide number="07" eyebrow="HOW A STACK WORKS" sourceLabel="TEXTBOOK p.331 · O/N 2024 Q4" syllabusLabel="14.1 · LAYERING" title="Each layer provides a service upward and receives a service from below." className="a2-slide a2-at-slide"><LayerStack layers={[{ name: "Application", detail: "application-facing service" }, { name: "Transport", detail: "end-to-end service" }, { name: "Internet", detail: "inter-network delivery" }, { name: "Link", detail: "local transmission" }]} footer="Logical peer-to-peer rules operate between matching layers; implementation passes data through adjacent layers." /></Slide> },
    { time: "6 min", focus: "Secure the exact current order and names.", prompt: "Cover the labels and rebuild the stack from memory.", source: "2027–2029 syllabus p.33.", content: <Slide number="08" eyebrow="THE FOUR TCP/IP LAYERS" sourceLabel="SYLLABUS p.33" syllabusLabel="14.1 · CORE" title="Application → Transport → Internet → Link." className="a2-slide a2-at-slide"><LayerStack layers={[{ name: "Application", detail: "services used by applications", tag: "HTTP · FTP · EMAIL · P2P" }, { name: "Transport", detail: "end-to-end delivery", tag: "SEGMENT · SEQUENCE · RELIABILITY" }, { name: "Internet", detail: "IP addressing and routing", tag: "SOURCE IP · DESTINATION IP" }, { name: "Link", detail: "frames and local-medium access", tag: "LOCAL NETWORK DELIVERY" }]} /></Slide> },
    { time: "6 min", focus: "Describe the Application layer without confusing it with an app.", prompt: "What service does a browser need before any bits can move?", source: "Syllabus 14.1; coursebook pp.332, 335–337.", content: <Slide number="09" eyebrow="APPLICATION LAYER" sourceLabel="TEXTBOOK pp.335–337" syllabusLabel="14.1 · FUNCTION" title="Application protocols define the service seen by user software." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "ACCESS", title: "Interface for software", body: "Browser, mail client and file software use network services." }, { eyebrow: "RULES", title: "Application protocol", body: "Defines request, response or transfer behaviour." }, { eyebrow: "HAND-OFF", title: "Pass data to Transport", body: "Lower layers move it; the application need not manage routes." }]} /></Slide> },
    { time: "6 min", focus: "Describe segmentation, sequencing and reliability.", prompt: "Which Transport information lets the receiver detect a gap?", source: "Coursebook §17.04 p.332; 9618/31 M/J 2024 Q2(b).", content: <Slide number="10" eyebrow="TRANSPORT LAYER" sourceLabel="TEXTBOOK p.332 · M/J 2024 Q2" syllabusLabel="14.1 · FUNCTION" title="Transport manages an end-to-end conversation." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SPLIT", title: "Segment the message" }, { eyebrow: "NUMBER", title: "Add sequence/control data" }, { eyebrow: "CHECK", title: "Detect loss or error" }, { eyebrow: "RECOVER", title: "Acknowledge / resend" }]} /></Slide> },
    { time: "7 min", focus: "Connect IP addressing to inter-network routing.", prompt: "Why does a router need the destination IP rather than the application name?", source: "Coursebook §17.04 p.333; syllabus 14.1.", content: <Slide number="11" eyebrow="INTERNET LAYER" sourceLabel="TEXTBOOK p.333" syllabusLabel="14.1 · FUNCTION" title="Internet identifies endpoints and moves packets between networks." className="a2-slide a2-at-slide"><PacketRoute nodes={[{ label: "192.0.2.10", detail: "source IP", state: "host" }, { label: "R1", detail: "inspect destination" }, { label: "R2", detail: "select next hop" }, { label: "198.51.100.8", detail: "destination IP", state: "host" }]} /></Slide> },
    { time: "7 min", focus: "Define Link as the current lower layer.", prompt: "Separate a local frame from an Internet-layer packet.", source: "Syllabus p.33; selected support from coursebook §§17.04–17.05 pp.333–335.", content: <Slide number="12" eyebrow="LINK LAYER" sourceLabel="TEXTBOOK pp.333–335" syllabusLabel="14.1 · FUNCTION" title="Link turns an Internet-layer packet into a local transmission." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "FRAME", title: "Local unit", body: "Encapsulates the packet for the current link." }, { eyebrow: "ACCESS", title: "Use the medium", body: "Works with local network hardware and signalling." }, { eyebrow: "HOP", title: "One link at a time", body: "A new local frame may be used at the next network." }]} /><p className="a2-alert"><b>Exam boundary</b><span>Use the syllabus term <strong>Link</strong>. Ethernet sub-layer names in the older textbook are supporting detail, not the four required layer names.</span></p></Slide> },
    { time: "7 min", focus: "Trace encapsulation and decapsulation through both hosts.", prompt: "Narrate one action at each sender layer and one at each receiver layer.", source: "Syllabus 14.1 host-to-host application; coursebook pp.332–333.", content: <Slide number="13" eyebrow="HOST A → HOST B" sourceLabel="TEXTBOOK pp.332–333" syllabusLabel="14.1 · APPLY" title="Down the sender, across the network, up the receiver." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "APPLICATION", title: "Create message" }, { eyebrow: "TRANSPORT", title: "Segment + control" }, { eyebrow: "INTERNET", title: "Add IP + route" }, { eyebrow: "LINK", title: "Frame + transmit" }]} /><p className="a2-answer-band"><b>DESTINATION</b>Link checks frame → Internet checks IP → Transport reorders/reassembles → Application receives data</p></Slide> },
    { time: "8 min", focus: "Apply current mark-scheme language under timed conditions.", prompt: "Four minutes closed-book, then reveal and annotate one phrase per mark.", source: "Adapted from Cambridge 9618/31 O/N 2024 Q4.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/31 O/N 2024 · Q4" syllabusLabel="14.1 · 4 MARKS" title="Describe how layers of the TCP/IP stack interact." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/31 O/N 2024 · Q4 · ADAPTED" marks={4} prompt={<p>Describe four valid interactions or implementation features of a layered TCP/IP stack. [4]</p>} answer={<ul><li>Each layer accepts input from an adjacent layer and sends output to an adjacent layer.</li><li>Adjacent layers communicate through a defined interface.</li><li>Headers/control information are added on the way down and removed on the way up.</li><li>Most layers are implemented in software; Application exposes user/application access and Link reaches network hardware.</li></ul>} /></Slide> },
    { time: "5 min", focus: "Check definitions, order and transfer sequence.", prompt: "Students answer all four prompts without notes.", source: "Lesson synthesis aligned to syllabus 14.1.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch17 · SYLLABUS p.33" syllabusLabel="SYLLABUS 14.1" title="Can you move one message through all four layers?" className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>01</span><p>Define <b>protocol</b>.</p></article><article><span>02</span><p>Write the four layers in order.</p></article><article><span>03</span><p>Give one function of each layer.</p></article><article><span>04</span><p>Explain add/check/remove control data.</p></article></section><div className="homework-callout"><b>HOMEWORK 07</b><span>30 marks · stack functions + host-to-host sequence · inline answers</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="07" title="Protocols and the TCP/IP stack" syllabusLabel="SYLLABUS 14.1" sourceLabel="TEXTBOOK Ch17 · pp.331–335" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus §14.1 p.33 · endorsed coursebook Chapter 17 printed pp.331–335 · verified 2022–2024 Paper 3 questions and mark schemes" sourceDetail="The coursebook's older lower-layer split is reconciled with the current syllabus: exam answers consistently use Application, Transport, Internet and Link." />;
}
