"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { LogicTable, SrLatchDiagram } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Truth tables and adders", subtitle: "Trace every row systematically", marks: 10,
    questions: [
      { id: "a2-15-1", marks: 3, lines: 5, prompt: <><b>State the number of rows</b> needed for truth tables with 2, 3 and 4 inputs. Give the rule.</>, answer: <p>Two inputs: 4 rows <em>[1]</em>; three inputs: 8 rows <em>[1]</em>; four inputs: 16 rows, following <code>2ⁿ</code> rows for n inputs <em>[1]</em>.</p> },
      { id: "a2-15-2", marks: 3, lines: 5, prompt: <><b>Give the two half-adder outputs</b> and their expressions.</>, answer: <p>Sum output <code>S = A XOR B</code> <em>[1]</em>; carry output <code>C = A AND B</code> <em>[1]</em>. The half adder adds exactly two input bits and has no carry-in <em>[1]</em>.</p> },
      { id: "a2-15-3", marks: 4, lines: 7, prompt: <><b>Explain how two half adders and one OR gate form a full adder.</b></>, answer: <p>The first half adder adds A and B <em>[1]</em>; the second adds the first sum to <code>Cin</code> <em>[1]</em>; their sum output is final S <em>[1]</em>; the OR gate combines the two carry outputs to form <code>Cout</code> <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "SR storage", subtitle: "Follow feedback and active input levels", marks: 10,
    questions: [
      { id: "a2-15-4", marks: 3, lines: 7, prompt: <><b>Draw and label a NOR SR latch</b> and state its hold-input combination.</>, answer: <p>Draw two NOR gates with the output of each cross-coupled to one input of the other <em>[1]</em>; label inputs S/R and outputs Q/Q̅ <em>[1]</em>; for a NOR SR latch, <code>S=0,R=0</code> holds the previous state <em>[1]</em>.</p> },
      { id: "a2-15-5", marks: 3, lines: 5, prompt: <><b>Explain why S=1, R=1 is invalid</b> for a NOR SR latch.</>, answer: <p>Both NOR outputs are forced to 0 <em>[1]</em>, so Q and ¬Q are no longer complements <em>[1]</em>; when the inputs return low the final stored state may be unpredictable <em>[1]</em>.</p> },
      { id: "a2-15-6", marks: 4, lines: 7, prompt: <><b>Give the NAND SR actions</b> for 11, 01, 10 and 00.</>, answer: <p>For active-low inputs: 11 holds <em>[1]</em>; 01 sets Q <em>[1]</em>; 10 resets Q <em>[1]</em>; 00 is invalid because both inputs are asserted and outputs cease to be complements <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "JK and exam clinic", subtitle: "Replace the invalid state with toggle", marks: 10,
    questions: [
      { id: "a2-15-7", marks: 3, lines: 5, prompt: <><b>Distinguish combinational and sequential logic.</b></>, answer: <p>Combinational output depends only on current inputs <em>[1]</em>. Sequential output also depends on previous state/output <em>[1]</em>, normally using feedback or storage <em>[1]</em>.</p> },
      { id: "a2-15-8", marks: 3, lines: 5, prompt: <><b>State the JK actions</b> for 00, 10 and 11 at the active clock edge.</>, answer: <p><code>J=0,K=0</code>: hold <em>[1]</em>; <code>1,0</code>: set Q to 1 <em>[1]</em>; <code>1,1</code>: toggle Q to its complement <em>[1]</em>.</p> },
      { id: "a2-15-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>A circuit has outputs E = 0,1,1,0 and F = 0,0,0,1 for inputs 00,01,10,11. Identify the circuit and outputs.</b></p><p>Adapted from 9618/32 M/J 2022 Q6(a)–(b). [4 adapted marks]</p></>, answer: <p>The circuit is a <strong>half adder</strong> <em>[1]</em>. E is the sum output/XOR of the two inputs <em>[1]</em>; F is the carry output/AND of the inputs <em>[1]</em>; a half adder adds two bits without a carry-in <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson15Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Connect binary addition and one-bit memory to logic gates.", prompt: "Which circuits only calculate, and which remember?", source: "2027–2029 syllabus 15.2; coursebook Chapter 19 printed pp.351–356.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch19" syllabusLabel="SYLLABUS 15.2" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 15 · 90 MINUTES</span><h1>Calculate a bit.<br /><em>Remember a bit.</em></h1><p>truth tables · half/full adders · SR and JK flip-flops</p></div><div className="a2-at-hero" role="img" aria-label="Logic circuits calculate and store bits"><strong>1-BIT LOGIC</strong><span>SUM</span><span>CARRY</span><span>SET / RESET</span><span>TOGGLE</span></div></section></Slide> },
    { time: "5 min", focus: "Map every circuit skill to syllabus 15.2.", prompt: "Students distinguish produce, draw, derive and explain.", source: "Syllabus p.34; coursebook pp.351–356.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.34" syllabusLabel="15.2 · LOGIC CIRCUITS" title="Truth tables describe both calculation and stored state." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "PRODUCE", title: "Truth tables", body: "Including more than two inputs." }, { eyebrow: "BUILD", title: "Adders", body: "Half and full binary addition." }, { eyebrow: "DERIVE", title: "SR / JK", body: "Circuit → next-state table." }, { eyebrow: "EXPLAIN", title: "Storage", body: "Feedback preserves one bit." }]} /></Slide> },
    { time: "5 min", focus: "Generate truth-table rows systematically.", prompt: "Why does one extra input double the row count?", source: "Coursebook §19.01 pp.351–352.", content: <Slide number="03" eyebrow="TRUTH TABLE DISCIPLINE" sourceLabel="TEXTBOOK pp.351–352" syllabusLabel="15.2 · PRODUCE" title="n binary inputs require 2ⁿ input combinations." className="a2-slide a2-at-slide"><CompareTable headers={["Inputs n", "Rows 2ⁿ", "Input order starts"]} rows={[[2,4,"00, 01, 10, 11"], [3,8,"000, 001, 010, …"], [4,16,"0000, 0001, 0010, …"]]} /></Slide> },
    { time: "6 min", focus: "Produce truth tables for gates with more than two inputs.", prompt: "Which rows make a three-input AND or OR output 1?", source: "Coursebook pp.351–352; syllabus explicitly includes gates with more than two inputs.", content: <Slide number="04" eyebrow="MORE THAN TWO INPUTS" sourceLabel="TEXTBOOK pp.351–352" syllabusLabel="15.2 · MULTI-INPUT" title="The gate rule stays the same when a third input is added." className="a2-slide a2-at-slide"><LogicTable headers={["A", "B", "C", "A·B·C", "A+B+C"]} rows={[[0,0,0,0,0], [0,0,1,0,1], [0,1,0,0,1], [0,1,1,0,1], [1,0,0,0,1], [1,0,1,0,1], [1,1,0,0,1], [1,1,1,1,1]]} /></Slide> },
    { time: "6 min", focus: "Explain the need for sum and carry outputs.", prompt: "Add 1 + 1 in binary and label both result bits.", source: "Coursebook §19.01 pp.351–352.", content: <Slide number="05" eyebrow="BINARY ADDITION" sourceLabel="TEXTBOOK pp.351–352" syllabusLabel="15.2 · ADDERS" title="One column can produce a sum bit and a carry bit." className="a2-slide a2-at-slide"><CompareTable headers={["A", "B", "Binary total", "Sum S", "Carry C"]} rows={[[0,0,"0",0,0], [0,1,"1",1,0], [1,0,"1",1,0], [1,1,"10",0,1]]} /></Slide> },
    { time: "6 min", focus: "Derive the half-adder table and expressions.", prompt: "Which familiar gates match the S and C columns?", source: "Coursebook pp.351–352; 9618/32 M/J 2022 Q6.", content: <Slide number="06" eyebrow="HALF ADDER" sourceLabel="9618/32 M/J 2022 · Q6" syllabusLabel="15.2 · TRUTH TABLE" title="A half adder combines two bits—but has no carry-in." className="a2-slide a2-at-slide"><LogicTable headers={["A", "B", "S = A XOR B", "C = A AND B"]} rows={[[0,0,0,0], [0,1,1,0], [1,0,1,0], [1,1,0,1]]} /></Slide> },
    { time: "6 min", focus: "Explain why a full adder needs three inputs.", prompt: "Where does Cin come from in a multi-bit addition?", source: "Coursebook §19.01 pp.352–353.", content: <Slide number="07" eyebrow="FULL ADDER" sourceLabel="TEXTBOOK pp.352–353" syllabusLabel="15.2 · TRUTH TABLE" title="A full adder includes the carry from the previous column." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "INPUT 1", title: "A", body: "bit from first number" }, { eyebrow: "INPUT 2", title: "B", body: "bit from second number" }, { eyebrow: "INPUT 3", title: "Cin", body: "carry from less significant column" }]} /></Slide> },
    { time: "6 min", focus: "Read all eight full-adder cases.", prompt: "Which rows have Cout=1, and why?", source: "Coursebook p.353.", content: <Slide number="08" eyebrow="FULL ADDER TABLE" sourceLabel="TEXTBOOK p.353" syllabusLabel="15.2 · PRODUCE" title="Sum is odd parity; carry is 1 when at least two inputs are 1." className="a2-slide a2-at-slide"><LogicTable headers={["A", "B", "Cin", "S", "Cout"]} rows={[[0,0,0,0,0], [0,0,1,1,0], [0,1,0,1,0], [0,1,1,0,1], [1,0,0,1,0], [1,0,1,0,1], [1,1,0,0,1], [1,1,1,1,1]]} /></Slide> },
    { time: "6 min", focus: "Build a full adder from smaller blocks.", prompt: "Trace both possible carry outputs into Cout.", source: "Coursebook p.353.", content: <Slide number="09" eyebrow="COMPOSE THE CIRCUIT" sourceLabel="TEXTBOOK p.353" syllabusLabel="15.2 · FULL ADDER" title="Two half adders plus OR create a full adder." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "HA 1", title: "Add A + B" }, { eyebrow: "HA 2", title: "Add first sum + Cin" }, { eyebrow: "SUM", title: "Second sum → S" }, { eyebrow: "OR", title: "carry₁ + carry₂ → Cout" }]} /></Slide> },
    { time: "6 min", focus: "Separate combinational outputs from stored state.", prompt: "Why can no truth-table row for a latch be complete without previous Q?", source: "Coursebook p.353 introduction to sequential logic.", content: <Slide number="10" eyebrow="COMBINATIONAL VS SEQUENTIAL" sourceLabel="TEXTBOOK p.353" syllabusLabel="15.2 · STORAGE" title="Feedback makes previous state part of the next output." className="a2-slide a2-at-slide"><CompareTable headers={["Combinational", "Sequential"]} rows={[["output uses current inputs only", "output uses inputs + previous state"], ["no memory required", "feedback/storage required"], ["adder example", "flip-flop/latch example"], ["same inputs → same output", "same inputs may hold different prior Q"]]} /></Slide> },
    { time: "7 min", focus: "Draw the NOR SR latch and trace its cross-coupled feedback.", prompt: "Point to S, R, Q, Q̅ and both feedback paths before deriving any row.", source: "Coursebook §19.02 pp.353–354; 9618/32 O/N 2022 Q8(a).", content: <Slide number="11" eyebrow="DRAW THE SR LATCH" sourceLabel="9618/32 O/N 2022 · Q8(a)" syllabusLabel="15.2 · DRAW + LABEL" title="Two cross-coupled NOR gates preserve one binary state." className="a2-slide a2-at-slide"><SrLatchDiagram /></Slide> },
    { time: "7 min", focus: "Derive the NOR table and contrast active-low NAND control.", prompt: "Which input pair holds, and which is invalid, in each version?", source: "Coursebook §19.02 pp.353–355; O/N 2022 Paper 32.", content: <Slide number="12" eyebrow="DERIVE THE STATE TABLE" sourceLabel="TEXTBOOK pp.353–355" syllabusLabel="15.2 · SR" title="NOR asserts high; NAND asserts low." className="a2-slide a2-at-slide"><CompareTable headers={["Action", "NOR SR", "NAND SR (active-low)"]} rows={[["hold previous Q", "00", "11"], ["set Q=1", "10", "01"], ["reset Q=0", "01", "10"], ["invalid", "11", "00"]]} /></Slide> },
    { time: "7 min", focus: "Explain how JK removes the invalid control combination.", prompt: "At the active clock edge, what does J=K=1 do?", source: "Coursebook pp.355–356.", content: <Slide number="13" eyebrow="JK FLIP-FLOP" sourceLabel="TEXTBOOK pp.355–356" syllabusLabel="15.2 · FLIP-FLOP" title="JK uses the 11 case to toggle the stored bit." className="a2-slide a2-at-slide"><LogicTable headers={["J", "K", "Next Q", "Action"]} rows={[[0,0,"previous Q","hold"], [1,0,1,"set"], [0,1,0,"reset"], [1,1,"¬Q","toggle"]]} /></Slide> },
    { time: "8 min", focus: "Complete and interpret an authentic half-adder table.", prompt: "Derive both output columns before naming the circuit.", source: "Adapted from Cambridge 9618/32 M/J 2022 Q6(a)–(b).", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/32 M/J 2022 · Q6(a)–(b)" syllabusLabel="15.2 · 5 MARKS" title="Read a truth table as a circuit specification." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/32 M/J 2022 · Q6(a)–(b) · ADAPTED" marks={5} prompt={<p>Complete E and F for inputs 00,01,10,11; then name the circuit and state the purpose of each output. [5]</p>} answer={<ul><li>E: 0,1,1,0 and F: 0,0,0,1. [2]</li><li>The circuit is a half adder. [1]</li><li>E is sum; F is carry. [2]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve calculate versus remember.", prompt: "Students complete one adder row and one next-state row.", source: "Syllabus 15.2 synthesis; coursebook pp.351–356.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch19 · SYLLABUS p.34" syllabusLabel="15.2 · CHECKPOINT" title="Adders calculate; feedback circuits store." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>2ⁿ</span><p>Rows for n binary inputs.</p></article><article><span>HALF</span><p>A, B → sum + carry.</p></article><article><span>FULL</span><p>A, B, Cin → S + Cout.</p></article><article><span>FLIP-FLOP</span><p>Feedback stores one bit.</p></article></section><div className="homework-callout"><b>HOMEWORK 15</b><span>30 marks · adders, SR and JK flip-flops</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="15" title="Adders and flip-flops" syllabusLabel="SYLLABUS 15.2" sourceLabel="TEXTBOOK Ch19 · pp.351–356" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 15.2 p.34 · endorsed coursebook Chapter 19 printed pp.351–356 · verified 2022 Paper 3 questions and mark schemes" sourceDetail="The lesson builds truth tables systematically, keeps half and full adder inputs distinct, and contrasts NOR SR, active-low NAND SR and JK next-state behaviour." />;
}
