"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { LayerStack, PacketRoute } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Router decisions", subtitle: "Explain one hop at a time", marks: 10,
    questions: [
      { id: "a2-10-1", marks: 3, lines: 5, prompt: <><b>State three actions performed by a router</b> when it receives a packet.</>, answer: <p>It reads the destination address in the packet header <em>[1]</em>, consults its routing table/network information <em>[1]</em>, and selects the next/best available hop before forwarding the packet <em>[1]</em>.</p> },
      { id: "a2-10-2", marks: 3, lines: 5, prompt: <><b>Explain why a router may send later packets from one message along a different route.</b></>, answer: <p>Packets are routed independently <em>[1]</em>. Network availability or congestion may have changed <em>[1]</em>, so the routing table/algorithm selects a different best next hop <em>[1]</em>.</p> },
      { id: "a2-10-3", marks: 4, lines: 6, prompt: <><b>Explain why a router does not normally reassemble the whole application message.</b></>, answer: <p>The router forwards individual packets hop by hop <em>[1]</em> using destination/header information <em>[1]</em>. Packets may take different paths and arrive at different times <em>[1]</em>; ordering and reassembly are destination/Transport responsibilities <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Complete packet journey", subtitle: "Connect headers, routers and destination recovery", marks: 10,
    questions: [
      { id: "a2-10-4", marks: 3, lines: 5, prompt: <><b>State three core items in a packet header</b> and give the purpose of each.</>, answer: <p>Destination IP/address routes the packet to the receiver <em>[1]</em>; source IP/address identifies the sender/return endpoint <em>[1]</em>; sequence or packet number supports reordering and detection of missing packets <em>[1]</em>.</p> },
      { id: "a2-10-5", marks: 3, lines: 5, prompt: <><b>Explain how packet switching provides completeness.</b></>, answer: <p>Sequence/control information identifies every expected packet <em>[1]</em>. The receiver detects a missing number <em>[1]</em> and requests or triggers retransmission <em>[1]</em>.</p> },
      { id: "a2-10-6", marks: 4, lines: 6, prompt: <><b>Explain how a web response uses both the TCP/IP stack and packet switching.</b></>, answer: <p>HTTP forms the Application-layer response <em>[1]</em>; Transport segments/numbers it <em>[1]</em>; Internet adds IP addressing and routers forward packets <em>[1]</em>; Link transmits frames locally and the destination stack reassembles/delivers the response <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Chapter 14 exam clinic", subtitle: "Select the command word and the mark points", marks: 10,
    questions: [
      { id: "a2-10-7", marks: 3, lines: 5, prompt: <><b>Correct this statement:</b><p>“The Transport layer chooses the route and HTTP retransmits missing packets.”</p></>, answer: <p>The <strong>Internet</strong> layer handles IP addressing/routing <em>[1]</em>. Transport manages sequencing/reliability and retransmission <em>[1]</em>. HTTP is an Application-layer web protocol <em>[1]</em>.</p> },
      { id: "a2-10-8", marks: 3, lines: 5, prompt: <><b>Give one delivery or recovery mechanism</b> for each of accuracy, completeness and resilience.</>, answer: <p>Accuracy: error/check data can reveal corruption <em>[1]</em>. Completeness: missing sequence numbers can be detected and resent <em>[1]</em>. Resilience: packets can be rerouted around failed/congested links <em>[1]</em>.</p> },
      { id: "a2-10-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Explain how routers help four packets reach a destination across the Internet.</b></p><p>Adapted from 9618/31 O/N 2021 Q6. [4]</p></>, answer: <p>Each router receives a packet and reads its destination IP/header <em>[1]</em>; consults a routing table/current route information <em>[1]</em>; selects a suitable next hop, which may differ for each packet <em>[1]</em>; and forwards the packet until the destination network/host is reached <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson10Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Follow one packet through a sequence of router decisions.", prompt: "At each router, what is known and what still has to be chosen?", source: "2027–2029 syllabus 14.2; coursebook Chapter 17 printed pp.330–333.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch17" syllabusLabel="SYLLABUS 14.2" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 10 · 90 MINUTES</span><h1>Read the header.<br /><em>Choose the next hop.</em></h1><p>Routers · routing tables · reassembly · Chapter 14 Paper 3 clinic</p></div><div className="a2-at-hero" role="img" aria-label="Packet travelling through routers"><strong>DESTINATION IP</strong><span>HEADER</span><span>ROUTING TABLE</span><span>NEXT HOP</span><span>FORWARD</span></div></section></Slide> },
    { time: "5 min", focus: "Turn the complete Chapter 14 syllabus into a retrieval checklist.", prompt: "Students mark each objective green, amber or red before the lesson.", source: "Syllabus p.33; coursebook Chapter 17 pp.329–339.", content: <Slide number="02" eyebrow="CHAPTER 14 CHECKPOINT" sourceLabel="SYLLABUS p.33 · TEXTBOOK Ch17" syllabusLabel="14.1 + 14.2" title="Protocols explain the rules; switching and routers explain the journey." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "14.1", title: "Protocol", body: "Agreed rules and layered implementation." }, { eyebrow: "14.1", title: "TCP/IP", body: "Four layers and host-to-host application." }, { eyebrow: "14.1", title: "Six services", body: "Web, files, email and P2P." }, { eyebrow: "14.2", title: "Switch + route", body: "Circuit, packets and router decisions." }]} /></Slide> },
    { time: "5 min", focus: "Retrieve packet header functions before routing.", prompt: "Match address, sequence and error data to a network action.", source: "Coursebook pp.330–333; 9618 packet-switching mark schemes.", content: <Slide number="03" eyebrow="DO NOW · HEADER" sourceLabel="TEXTBOOK pp.330–333" syllabusLabel="14.2 · RETRIEVAL" title="The header carries the evidence needed to forward and rebuild." className="a2-slide a2-at-slide"><CompareTable headers={["Header item", "Immediate use", "Later consequence"]} rows={[["destination IP", "choose next hop", "reach receiver"], ["source IP", "identify sender", "return / acknowledgement"], ["sequence number", "identify packet position", "reorder and detect gaps"], ["checksum/control", "test data", "discard/resend corruption"]]} /></Slide> },
    { time: "6 min", focus: "State the router's first decision input.", prompt: "Why is a packet's payload irrelevant to the normal forwarding decision?", source: "Coursebook §17.04 p.333; syllabus 14.2.", content: <Slide number="04" eyebrow="ROUTER INPUT" sourceLabel="TEXTBOOK p.333" syllabusLabel="14.2 · ROUTER" title="Inspect the destination address—not the user's message." className="a2-slide a2-at-slide"><PacketRoute nodes={[{ label: "Incoming link", detail: "packet arrives" }, { label: "Router", detail: "read destination IP" }, { label: "Routing table", detail: "candidate next hops" }, { label: "Outgoing link", detail: "forward packet" }]} packets={["203.0.113.7"]} /></Slide> },
    { time: "6 min", focus: "Explain what a routing table contributes.", prompt: "Students identify destination/network, next hop and cost/status fields.", source: "Coursebook p.333; 9618/31 O/N 2021 Q6.", content: <Slide number="05" eyebrow="ROUTING TABLE" sourceLabel="TEXTBOOK p.333 · O/N 2021 Q6" syllabusLabel="14.2 · ROUTER" title="A routing table maps destination information to a next hop." className="a2-slide a2-at-slide"><CompareTable headers={["Destination network", "Next hop", "Route status / cost"]} rows={[["198.51.100.0/24", "R4", "available · 3 hops"], ["203.0.113.0/24", "R2", "available · 1 hop"], ["default", "R1", "fallback route"]]} /></Slide> },
    { time: "6 min", focus: "Frame routing as repeated local choices rather than one global reservation.", prompt: "Which device chooses the second hop: sender or second router?", source: "Syllabus 14.2; coursebook p.333.", content: <Slide number="06" eyebrow="HOP BY HOP" sourceLabel="TEXTBOOK p.333" syllabusLabel="14.2 · ROUTER" title="Each router chooses the packet's next hop using current information." className="a2-slide a2-at-slide"><PacketRoute nodes={[{ label: "Sender", detail: "uses default gateway", state: "host" }, { label: "R1", detail: "next hop R3" }, { label: "R3", detail: "next hop R5" }, { label: "Receiver", detail: "destination", state: "host" }]} /></Slide> },
    { time: "6 min", focus: "Explain adaptive route choice under congestion or failure.", prompt: "A table entry becomes unavailable: what can change for the next packet?", source: "Coursebook p.333; published 9618 router mark schemes.", content: <Slide number="07" eyebrow="NETWORK CONDITIONS" sourceLabel="9618/31 O/N 2021 · Q6" syllabusLabel="14.2 · RESILIENCE" title="Independent routing allows later packets to avoid a bad link." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "CONGESTION", title: "Long queue / high cost", body: "A different next hop may reduce delay." }, { eyebrow: "FAILURE", title: "Route unavailable", body: "Forward through another reachable network." }, { eyebrow: "UPDATE", title: "Table information changes", body: "The next packet can receive a new decision." }]} /></Slide> },
    { time: "6 min", focus: "Separate router forwarding from destination reassembly.", prompt: "Sort actions into router, Transport layer and Application layer.", source: "Syllabus 14.1–14.2; coursebook pp.332–333.", content: <Slide number="08" eyebrow="AT THE DESTINATION" sourceLabel="TEXTBOOK pp.332–333" syllabusLabel="14.1 + 14.2" title="Routers deliver packets; the destination stack rebuilds the service data." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "LINK", title: "Receive local frame" }, { eyebrow: "INTERNET", title: "Confirm destination IP" }, { eyebrow: "TRANSPORT", title: "Check, order, reassemble" }, { eyebrow: "APPLICATION", title: "Deliver message to software" }]} /></Slide> },
    { time: "6 min", focus: "Use accuracy, completeness and resilience as linked evaluation.", prompt: "Provide a mechanism for each claimed benefit.", source: "9618/31 O/N 2021 Q6 mark scheme; packet-switching principles.", content: <Slide number="09" eyebrow="WHY PACKETS WORK" sourceLabel="O/N 2021 Q6" syllabusLabel="14.2 · EXPLAIN" title="A benefit earns the mark when its mechanism is clear." className="a2-slide a2-at-slide"><ConceptCards items={[{ eyebrow: "ACCURACY", title: "Check data", body: "Detect corruption; reject and resend." }, { eyebrow: "COMPLETENESS", title: "Sequence the packets", body: "A missing number reveals a gap." }, { eyebrow: "RESILIENCE", title: "Reroute", body: "A router can avoid a failed path." }]} /></Slide> },
    { time: "6 min", focus: "Integrate application, stack and switching in one response.", prompt: "Trace an HTTP response without assigning actions to the wrong layer.", source: "Syllabus 14.1–14.2 synthesis; coursebook Chapter 17.", content: <Slide number="10" eyebrow="ONE WEB RESPONSE" sourceLabel="TEXTBOOK Ch17" syllabusLabel="14.1 + 14.2 · SYNTHESIS" title="The service, layers and route describe different parts of one transfer." className="a2-slide a2-at-slide"><LayerStack layers={[{ name: "Application", detail: "HTTP creates the response" }, { name: "Transport", detail: "segments, numbers and checks" }, { name: "Internet", detail: "adds IP; routers forward" }, { name: "Link", detail: "frames cross each local link" }]} footer="At the receiver, the path reverses through the stack and the browser receives the reconstructed resource." /></Slide> },
    { time: "7 min", focus: "Repair common conceptual and terminology errors.", prompt: "Students rewrite all four statements into exam-safe language.", source: "Recurring errors in 2022–2024 Paper 3 responses.", content: <Slide number="11" eyebrow="MISCONCEPTION REPAIR" sourceLabel="PAPER 3 EXAM LANGUAGE" syllabusLabel="14 · PRECISION" title="A correct noun with the wrong job still loses the mark." className="a2-slide a2-at-slide"><CompareTable headers={["Unsafe statement", "Exam-safe correction"]} rows={[["HTTP routes packets", "HTTP transfers web resources at Application"], ["Transport chooses the route", "Internet/IP and routers handle routing"], ["packets always take different paths", "packets may take different paths"], ["BitTorrent has no server anywhere", "there is no central content server; peers supply pieces"]]} /></Slide> },
    { time: "7 min", focus: "Match command words to response structure.", prompt: "Turn one topic into state, describe, explain and compare answers.", source: "Cambridge command-word practice applied to Chapter 14.", content: <Slide number="12" eyebrow="COMMAND WORD CONTROL" sourceLabel="CAMBRIDGE PAPER 3" syllabusLabel="14 · EXAM SKILL" title="Answer the command word before adding detail." className="a2-slide a2-at-slide"><CompareTable headers={["Command", "Required response", "Packet example"]} rows={[["state / name", "short fact or term", "destination address"], ["describe", "what happens", "router reads table and forwards"], ["explain", "link cause to consequence", "sequence reveals missing packet"], ["compare", "paired differences", "reserved route whereas shared routes"]]} /></Slide> },
    { time: "7 min", focus: "Plan a compact Chapter 14 mini-paper response.", prompt: "Students allocate one distinct marking point to each line.", source: "Adapted structure from 2024 Paper 3 Chapter 14 questions.", content: <Slide number="13" eyebrow="MINI-PAPER PLAN" sourceLabel="2024 PAPER 3 MIX" syllabusLabel="14 · 12 MARKS" title="Layer the answer: rule → service → route → consequence." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "3 MARKS", title: "Protocol + why essential" }, { eyebrow: "3 MARKS", title: "Layer + function" }, { eyebrow: "3 MARKS", title: "Router + next hop" }, { eyebrow: "3 MARKS", title: "Switching evaluation" }]} /></Slide> },
    { time: "8 min", focus: "Apply router mark points to a packet journey.", prompt: "Four minutes closed-book; underline destination, table, next hop and forward.", source: "Adapted from Cambridge 9618/31 O/N 2021 Q6 and 9618/32 O/N 2024 Q1.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/31 O/N 2021 · Q6" syllabusLabel="14.2 · 6 MARKS" title="Explain one packet's Internet journey and recovery." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/31 O/N 2021 · Q6 · ADAPTED" marks={6} prompt={<p>Explain how routers forward a packet and how the destination deals with ordering or loss. [6]</p>} answer={<ul><li>Router reads destination IP/header and consults its routing table. [2]</li><li>It selects a next/best available hop and forwards the packet; later packets may use other routes. [2]</li><li>Destination uses sequence data to reorder/detect a gap and requests retransmission of missing data. [2]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Close Chapter 14 with a complete retrieval route.", prompt: "Students answer one prompt for every syllabus line without notes.", source: "Chapter 14 synthesis aligned to syllabus p.33.", content: <Slide number="15" eyebrow="CHAPTER 14 EXIT" sourceLabel="TEXTBOOK Ch17 · SYLLABUS p.33" syllabusLabel="CHAPTER 14 COMPLETE" title="Rules agreed. Layers applied. Packets routed." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>14.1</span><p>Protocol + four TCP/IP layers.</p></article><article><span>14.1</span><p>Six application protocols.</p></article><article><span>14.2</span><p>Circuit vs packet switching.</p></article><article><span>14.2</span><p>Router decision + destination recovery.</p></article></section><div className="homework-callout"><b>HOMEWORK 10</b><span>30 marks · router decisions + Chapter 14 exam clinic</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="10" title="Routers and Chapter 14 review" syllabusLabel="SYLLABUS 14.1–14.2" sourceLabel="TEXTBOOK Ch17 · pp.329–339" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus Chapter 14 p.33 · endorsed coursebook Chapter 17 printed pp.329–339 · verified 2021–2024 Paper 3 questions and mark schemes" sourceDetail="The checkpoint integrates protocol purpose, four-layer responsibilities, packet headers, router decisions and destination recovery without reproducing Cambridge paper pages." />;
}
