/* Pseudocode examples intentionally retain their source notation. */
/* eslint-disable react/no-unescaped-entities */
"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Refine with purpose", subtitle: "Levels, completeness and programmable detail", marks: 10,
    questions: [
      { id: "l44-1", marks: 3, lines: 3, prompt: <><b>Define stepwise refinement and explain its purpose.</b></>, answer: <p>Stepwise refinement starts with broad algorithm steps and repeatedly breaks each into more detailed operations. It continues until the actions and conditions are precise enough to implement/program, reducing complexity while preserving the overall solution. <em>[3]</em></p> },
      { id: "l44-2", marks: 3, lines: 3, prompt: <><b>Give three qualities of a lowest-level refined step.</b></>, answer: <p>Any three: unambiguous; finite/executable; states required input/data; gives exact calculation/condition/update/output; uses ordered actions; covers boundary/error cases; can map directly to a programming construct. <em>[3]</em></p> },
      { id: "l44-3", marks: 4, lines: 5, prompt: <><b>Refine “calculate order total” into at least four precise steps.</b></>, answer: <p>Example: set Total to 0; for each ordered item, multiply quantity by unit price; add the line value to Total; if a valid discount applies, calculate and subtract it; calculate/add tax or delivery if required; output/return the final Total. Award four coherent, ordered refinements. <em>[4]</em></p> },
    ],
  },
  {
    code: "B", title: "Design an integrated solution", subtitle: "Identifiers, IPO, logic and representation", marks: 10,
    questions: [
      { id: "l44-4", marks: 4, lines: 5, prompt: <><b>Create an identifier table for a taxi-fare algorithm using DistanceKm, BaseFare, RatePerKm and TotalFare.</b></>, answer: <p>All four are REAL. DistanceKm is input journey distance; BaseFare is fixed starting charge; RatePerKm is charge for each kilometre; TotalFare is calculated amount payable. Award complete appropriate name/type/role entries up to four marks. <em>[4]</em></p> },
      { id: "l44-5", marks: 4, lines: 5, prompt: <><b>Refine “calculate taxi fare” so journeys above 20 km receive a 10% discount.</b></>, answer: <p>Input DistanceKm; set TotalFare ← BaseFare + DistanceKm × RatePerKm; IF DistanceKm &gt; 20 THEN TotalFare ← TotalFare × 0.90 ENDIF; output TotalFare. Credit exact condition, correct percentage operation, order and output. <em>[4]</em></p> },
      { id: "l44-6", marks: 2, lines: 2, prompt: <><b>State one way to check that the refined design still matches the original problem.</b></>, answer: <p>Trace representative and boundary inputs against every original requirement, or map each requirement to a specific refined step and confirm no step changes/omits it. <em>[2]</em></p> },
    ],
  },
  {
    code: "C", title: "Published refinement task", subtitle: "Non-empty strings appended to a text file", marks: 10,
    questions: [
      { id: "l44-7", marks: 6, lines: 7, prompt: <><Mark>PAST PAPER PRACTICE · PAPER 2</Mark> <b>Using detailed English steps rather than pseudocode, refine an algorithm that appends every non-empty item from a 65-element STRING array to a text file.</b><p>Adapted from 9618/23 O/N 2025 Q2(a). [6]</p></>, answer: <p>Open the text file in append mode; initialise an index at the first array position; repeat for all 65 positions; access the array element using the index; test whether it is not the empty string; if non-empty, write it to the file; increment/move to the next index; after all elements, close the file. The original scheme awards six of seven detailed points. <em>[6]</em></p> },
      { id: "l44-8", marks: 2, lines: 2, prompt: <><Mark>PAST PAPER PRACTICE · PAPER 2</Mark> <b>Besides iteration, identify and explain another construct required.</b><p>Adapted from 9618/23 O/N 2025 Q2(b). [2]</p></>, answer: <p>Selection is required to test whether the current string is empty and write only when it is non-empty. Sequence is also defensible when linked to ensuring actions occur in the correct order. Construct plus contextual explanation. <em>[2]</em></p> },
      { id: "l44-9", marks: 2, lines: 2, prompt: <><b>Explain why the answer to the published refinement task should not use formal file pseudocode.</b></>, answer: <p>The question explicitly requests detailed non-pseudocode steps, testing stepwise refinement rather than recall of file syntax. Clear structured English satisfies the representation requested. <em>[2]</em></p> },
    ],
  },
];

export default function Lesson44Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Expose the gap between a broad intention and programmable detail.", prompt: "Ask whether a programmer could implement 'process the order' without further decisions.", source: "Coursebook 12.08 printed pp.199-201; syllabus 9.2.", content: <Slide number="01" eyebrow="CHAPTER 9 · STEPWISE REFINEMENT" sourceLabel="TEXTBOOK CH.12 · pp.199-208" syllabusLabel="SYLLABUS 9.2" className="da-title"><section className="da-title-grid"><div className="da-title-copy"><span>LESSON 44 · 90 MINUTES · PAPER 2</span><h1>Start broad.<br /><em>Finish executable.</em></h1><p>Refine a high-level algorithm into precise steps, preserve requirements and combine abstraction, identifiers, IPO, logic and representations.</p></div><div className="da-title-map"><div><b>L0</b><span>STATE THE WHOLE TASK</span></div><div><b>L1</b><span>NAME MAJOR STEPS</span></div><div><b>L2</b><span>ADD DATA + DECISIONS</span></div><div><b>L3</b><span>REACH PROGRAMMABLE DETAIL</span></div></div></section></Slide> },
    { time: "5 min", focus: "Map the last syllabus bullet and the integrated Chapter 9 review.", prompt: "Make clear that structure charts/lifecycle/testing belong to Chapter 12, not this chapter.", source: "Syllabus 9.2 p.28; Coursebook 12.08 and summary/exam pp.199-208.", content: <Slide number="02" eyebrow="TEXTBOOK × SYLLABUS" sourceLabel="TEXTBOOK §12.08 + REVIEW · pp.199-208" syllabusLabel="SYLLABUS 9.2 · PAPER 2" title="Refine until the task may be programmed—then verify the design still matches the problem."><section className="da-grid four"><article className="da-card"><span>REFINE</span><p>replace broad actions with smaller defined steps</p></article><article className="da-card"><span>DETAIL</span><p>name data, calculations, decisions, repetition and outputs</p></article><article className="da-card"><span>PRESERVE</span><p>keep every original requirement and boundary condition</p></article><article className="da-card"><span>INTEGRATE</span><p>abstraction, decomposition, identifier table, IPO, logic and representation</p></article></section><p className="da-warning">Formal module definitions/parameters are Chapter 11.3; lifecycle, structure charts, state transitions and testing are Chapter 12.</p></Slide> },
    { time: "6 min", focus: "Define refinement as progressive detail, not merely rewriting.", prompt: "Students identify what new information is added at each level.", source: "Coursebook 12.08 printed pp.199-201; syllabus 9.2.", content: <Slide number="03" eyebrow="STEPWISE REFINEMENT" sourceLabel="TEXTBOOK §12.08 · pp.199-201" syllabusLabel="SYLLABUS 9.2" title="Each level answers questions left open by the level above."><section className="da-refine"><div><b>LEVEL 0</b><span>Process a customer order.</span></div><div><b>LEVEL 1</b><span>Input items → validate → calculate total → take payment → output receipt.</span></div><div><b>LEVEL 2</b><span>Define identifiers, loop through items, calculate line totals, apply rules and handle invalid/payment outcomes.</span></div></section><p className="da-note">Stop when every lowest-level step is unambiguous enough to translate into code.</p></Slide> },
    { time: "6 min", focus: "Show what counts as added detail and what remains too vague.", prompt: "Students repair three vague verbs: handle, process and check.", source: "Coursebook 12.08 printed pp.199-201; syllabus 9.2 programmable detail.", content: <Slide number="04" eyebrow="WHAT DETAIL MUST APPEAR?" sourceLabel="TEXTBOOK §12.08 · pp.199-201" syllabusLabel="SYLLABUS 9.2" title="Data · operation · condition · repetition · result."><section className="da-grid five"><article className="da-card"><span>DATA</span><p>which identifier/value?</p></article><article className="da-card"><span>OPERATION</span><p>what exact calculation/update?</p></article><article className="da-card"><span>CONDITION</span><p>what Boolean test?</p></article><article className="da-card"><span>REPETITION</span><p>what repeats and when stops?</p></article><article className="da-card"><span>OUTPUT</span><p>what observable result?</p></article></section><p className="da-warning">“Validate the input” is still broad. State the valid condition and what happens when it is false.</p></Slide> },
    { time: "6 min", focus: "Audit refined steps for completeness, order and termination.", prompt: "Use a retry loop to identify an unchanged test variable.", source: "Coursebook 12.08; syllabus 9.2 algorithms and refinement.", content: <Slide number="05" eyebrow="QUALITY CHECK" sourceLabel="TEXTBOOK §12.08 · METHOD" syllabusLabel="SYLLABUS 9.2" title="A detailed design can still be wrong."><section className="da-grid four"><article className="da-card"><span>COMPLETE</span><p>every requirement and outcome is represented</p></article><article className="da-card"><span>ORDERED</span><p>a value is created before being used</p></article><article className="da-card"><span>UNAMBIGUOUS</span><p>conditions and operations have one meaning</p></article><article className="da-card"><span>TERMINATING</span><p>repetition changes state toward its stop condition</p></article></section></Slide> },
    { time: "6 min", focus: "Use logic statements as the precise language of a refined decision.", prompt: "Students test the discount rule at 19, 20 and 21 km.", source: "Coursebook 12.06 and 12.08; syllabus 9.2 logic/refinement.", content: <Slide number="06" eyebrow="REFINE A DECISION WITH LOGIC" sourceLabel="TEXTBOOK §§12.06 + 12.08" syllabusLabel="SYLLABUS 9.2" title="Boundary words must become exact comparisons."><table className="da-table"><thead><tr><th>REQUIREMENT</th><th>LOGIC STATEMENT</th><th>BOUNDARY CHECK</th></tr></thead><tbody><tr><td>discount journeys above 20 km</td><td><strong>DistanceKm &gt; 20</strong></td><td>20: no; 20.1: yes</td></tr><tr><td>valid mark from 0 to 100 inclusive</td><td><strong>Mark &gt;= 0 AND Mark &lt;= 100</strong></td><td>0 and 100: yes</td></tr><tr><td>weekend day code S or U</td><td><strong>Day = 'S' OR Day = 'U'</strong></td><td>either code: yes</td></tr></tbody></table></Slide> },
    { time: "6 min", focus: "Integrate the full Chapter 9 design sequence without adding later syllabus topics.", prompt: "Students explain how one artefact feeds the next.", source: "Syllabus 9.1-9.2 complete chapter; Coursebook Chapter 12.", content: <Slide number="07" eyebrow="INTEGRATED DESIGN PATH" sourceLabel="TEXTBOOK CH.12 · SYNTHESIS" syllabusLabel="SYLLABUS 9.1–9.2" title="From purpose to a programmable algorithm."><section className="da-flow five"><span>ABSTRACT<br />ESSENTIALS</span><i>→</i><span>DECOMPOSE<br />SUB-PROBLEMS</span><i>→</i><span>IDENTIFIERS<br />+ IPO</span><i>→</i><span>REFINE<br />CONTROL + LOGIC</span><i>→</i><span>DOCUMENT<br />+ TRACE</span></section><p className="da-note">The three representations may be used at different stages, but their final control logic must be equivalent.</p></Slide> },
    { time: "7 min", focus: "Work a three-level refinement with a boundary decision.", prompt: "Students propose Level 2 before the model is shown.", source: "Coursebook 12.08 method; syllabus 9.2.", content: <Slide number="08" eyebrow="WORKED REFINEMENT · TAXI FARE" sourceLabel="TEXTBOOK §12.08 · APPLICATION" syllabusLabel="SYLLABUS 9.2" title="Refine “calculate fare” without losing the discount rule."><section className="da-refine"><div><b>LEVEL 0</b><span>Calculate and output the taxi fare.</span></div><div><b>LEVEL 1</b><span>Input distance → calculate base fare → apply long-journey discount → output.</span></div><div><b>LEVEL 2</b><span>TotalFare ← BaseFare + DistanceKm × RatePerKm; IF DistanceKm &gt; 20 THEN TotalFare ← TotalFare × 0.90; OUTPUT TotalFare.</span></div></section><p className="da-warning">Test 20 exactly: “above 20” means &gt; 20, not &gt;= 20.</p></Slide> },
    { time: "6 min", focus: "Distinguish decomposition, refinement and final representation.", prompt: "Students classify each design action in an event-booking example.", source: "Syllabus 9.1-9.2; Coursebook 12.01, 12.03 and 12.08.", content: <Slide number="09" eyebrow="THREE SCALES OF DESIGN" sourceLabel="TEXTBOOK CH.12 · COMPARE" syllabusLabel="SYLLABUS 9.1–9.2" title="Split responsibilities; deepen steps; encode control."><section className="da-compare"><div><span>ACTION</span><span>DESIGN MOVE</span><span>RESULT</span></div><div><b>separate availability, pricing and payment</b><span>decomposition</span><span>coherent sub-problems</span></div><div><b>expand “calculate price” into formula + discount rule</b><span>stepwise refinement</span><span>programmable detail</span></div><div><b>draw diamonds/arrows or write IF</b><span>representation</span><span>documented control logic</span></div></section></Slide> },
    { time: "6 min", focus: "Guide refinement in structured English, matching the published non-pseudocode demand.", prompt: "Pairs refine an array-to-file task without using formal syntax.", source: "Syllabus 9.2 stepwise refinement; 9618/23 O/N 2025 Q2 context.", content: <Slide number="10" eyebrow="GUIDED REFINEMENT · APPEND NON-EMPTY ITEMS" sourceLabel="TEXTBOOK §12.08 + PAPER 2 CONTEXT" syllabusLabel="SYLLABUS 9.2" title="Write defined English steps, not pseudocode."><section className="da-flow"><span>OPEN FILE IN<br />APPEND MODE</span><i>→</i><span>VISIT EACH OF<br />65 ELEMENTS</span><i>→</i><span>IF NON-EMPTY,<br />WRITE IT</span><i>→</i><span>AFTER ALL ITEMS,<br />CLOSE FILE</span></section><p className="da-note">Refine “visit each” further: initialise an index, access by index, update it and stop after exactly 65 positions.</p></Slide> },
    { time: "7 min", focus: "Teach how to answer a non-code refinement question point by point.", prompt: "Students underline nouns, quantities, conditions and lifecycle actions in the requirement.", source: "9618/23 O/N 2025 Q2 published mark scheme; syllabus 9.2.", content: <Slide number="11" eyebrow="EXAM METHOD · MATCH THE REQUESTED FORM" sourceLabel="9618/23 O/N 2025 · Q2" syllabusLabel="SYLLABUS 9.2 — PAPER 2" title="Detailed English can be the correct algorithm representation."><section className="da-grid four"><article className="da-card"><span>RESOURCE</span><p>open in correct mode; close after use</p></article><article className="da-card"><span>BOUNDS</span><p>initialise and traverse exactly the required elements</p></article><article className="da-card"><span>CONDITION</span><p>test current value in the loop</p></article><article className="da-card"><span>ACTION</span><p>write only qualifying data; update progress</p></article></section><p className="da-warning">If the question says “not pseudocode”, formal keywords can obscure the skill being assessed. Follow the requested representation.</p></Slide> },
    { time: "8 min", focus: "Attempt the six-mark published refinement task.", prompt: "Students write seven short ordered steps; six may score.", source: "Adapted from 9618/23 O/N 2025 Q2(a), checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 6 MARKS" sourceLabel="9618/23 O/N 2025 · Q2(a)" syllabusLabel="SYLLABUS 9.2 — PAPER 2" title="Append non-empty values from a 65-element array." className="slide--da-paper"><section className="da-paper-grid three"><article><span>FILE</span><p>append-open before; close after</p></article><article><span>TRAVERSE</span><p>initialise index; access and update through 65 items</p></article><article><span>SELECT</span><p>test non-empty; write only qualifying strings</p></article></section><ExamReveal><p>Open the file in append mode. Initialise an index at the first array position. Repeat through all 65 elements: access the indexed string, test that it is not empty, write it only when non-empty, and move to the next index. Close the file after the traversal. The original scheme awards six of seven detailed points.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [6].</small></Slide> },
    { time: "8 min", focus: "Identify the constructs and debrief why representation matters.", prompt: "Students answer the two-mark follow-up, then compare with their refinement.", source: "Adapted from 9618/23 O/N 2025 Q2(b), checked against published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 2 MARKS" sourceLabel="9618/23 O/N 2025 · Q2(b)" syllabusLabel="SYLLABUS 9.2 — PAPER 2" title="Besides iteration, which construct is required—and why?" className="slide--da-paper"><section className="da-paper-grid"><article><span>SELECTION</span><p>test whether current string is empty; write only if it is not</p></article><article><span>SEQUENCE</span><p>also defensible when tied to correct ordered actions</p></article></section><ExamReveal><p>Selection is needed to branch on the empty-string test so only non-empty values are written. An explained sequence point may also be credited: open, traverse/write and close must occur in the correct order.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [2].</small></Slide> },
    { time: "5 min", focus: "Retrieve the whole chapter as one design cycle.", prompt: "One student explains each transition; peers challenge missing assumptions.", source: "Syllabus 9.1-9.2 complete synthesis; Coursebook Chapter 12 summary printed pp.206-208.", content: <Slide number="14" eyebrow="CHAPTER 9 RETRIEVAL" sourceLabel="TEXTBOOK CH.12 · pp.206-208" syllabusLabel="SYLLABUS 9.1–9.2" title="From complexity to a defined, documented solution."><section className="da-flow five"><span>ABSTRACTION</span><i>→</i><span>DECOMPOSITION</span><i>→</i><span>IDENTIFIERS<br />+ IPO</span><i>→</i><span>CONSTRUCTS<br />+ LOGIC</span><i>→</i><span>STEPWISE<br />REFINEMENT</span></section></Slide> },
    { time: "4 min", focus: "Close Chapter 9 and set the boundary for Chapter 10.", prompt: "Students answer one sentence per card without notes.", source: "Syllabus 9.1-9.2 complete checkpoint; Coursebook Chapter 12.", content: <Slide number="15" eyebrow="EXIT TICKET · CHAPTER 9 COMPLETE" sourceLabel="TEXTBOOK CH.12 · pp.178-208" syllabusLabel="SYLLABUS 9.1–9.2" title="Three final distinctions."><section className="da-exit"><article><span>ABSTRACT vs DECOMPOSE</span><p>Filter details or split sub-problems?</p></article><article><span>SELECT vs ITERATE</span><p>Choose a path or repeat a block?</p></article><article><span>REFINE</span><p>When is a step detailed enough to program?</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="44" slides={slides} homework={<HomeworkSheet lessonNumber="44" title="Stepwise Refinement and Integrated Algorithm Design" marks={30} minutes={45} syllabusLabel="SYLLABUS 9.2 · PAPER 2" sourceLabel="TEXTBOOK CH.12 · pp.199-208 + PSEUDOCODE GUIDE + PAPER 2" instructions="Refine broad actions into ordered, unambiguous operations, conditions and updates. Match the requested representation: structured English is required when the question says not to write pseudocode." sections={homeworkSections} challenge={{ id: "l44-challenge", prompt: <p><Mark>CHALLENGE</Mark> Create a requirement-to-step traceability check for your taxi-fare refinement.</p>, answer: <p>Map each requirement to one or more steps: obtain distance → INPUT DistanceKm; calculate standard fare → BaseFare + DistanceKm × RatePerKm; discount only above 20 km → IF DistanceKm &gt; 20 and multiply by 0.90; communicate charge → OUTPUT TotalFare. Trace 20 and a value above 20 to verify the boundary.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 9.1-9.2, Coursebook Chapter 12 printed pp.199-208 (PDF pp.206-215), the official 2027-2029 Pseudocode Guide and published Paper 2 questions/mark scheme." sourceDetail="Core: stepwise refinement to programmable detail, logic statements, preservation of requirements and integrated Chapter 9 design. Authentic Paper 2 anchors: 9618/23 O/N 2025 Q2(a)-Q2(b) [8]. Formal modules, structure charts, lifecycle and testing remain later syllabus chapters. Chapter 9 is now complete." />;
}
