"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l17-reveal-${id}`;
  return <div className="pc-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className={visible ? "pc-reveal__panel visible" : "pc-reveal__panel"} hidden={!visible}>{children}</div></div>;
}

function CpuMap() {
  return <div className="pc-cpu-map" role="img" aria-label="Von Neumann computer with processor, memory, input and output"><section><b>CPU</b><div><span>CU</span><span>ALU</span><span>REGISTERS</span></div></section><i>↔</i><section><b>IAS / MEMORY</b><p>instructions + data</p></section><i>↔</i><section><b>INPUT / OUTPUT</b><p>outside world</p></section></div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Architecture and components", subtitle: "Use stored-program language and state precise roles", marks: 10,
    questions: [
      { id: "l17-1", marks: 4, lines: 4, prompt: <><b>State four features of the basic Von Neumann model.</b></>, answer: <p>One processor/CPU; processor has direct access to memory; instructions and data are stored in the same memory; a program is stored as instructions; instructions are normally executed sequentially unless control flow changes. <em>[Any four, 1 each]</em></p> },
      { id: "l17-2", marks: 6, lines: 5, prompt: <><b>Explain the roles of the CU, ALU, system clock and IAS.</b></>, answer: <p><b>CU:</b> decodes instructions and sends control signals to coordinate components. <b>ALU:</b> performs arithmetic and logical operations. <b>Clock:</b> supplies timing pulses that synchronise processor activity. <b>IAS:</b> fast, volatile storage holding programs, instructions and data currently in use. <em>[6 linked points]</em></p> },
    ],
  },
  {
    code: "B", title: "Register roles", subtitle: "Name the register, then say exactly what it holds", marks: 10,
    questions: [
      { id: "l17-3", marks: 7, lines: 5, prompt: <><b>State the role of each register.</b><p>PC · MAR · MDR · CIR · ACC · IX · Status Register</p></>, answer: <p><b>PC:</b> address of next instruction. <b>MAR:</b> address currently accessed. <b>MDR:</b> data/instruction read from or written to that address. <b>CIR:</b> current instruction being decoded/executed. <b>ACC:</b> value/result used by the ALU. <b>IX:</b> value added to an address for indexed addressing. <b>Status:</b> individual condition flags. <em>[1 each]</em></p> },
      { id: "l17-4", marks: 3, lines: 3, prompt: <><b>Distinguish a general-purpose register from a special-purpose register and give one suitable example of each.</b></>, answer: <p>A general-purpose register can hold working data/results for different operations, for example the <b>ACC in the syllabus instruction model</b>. A special-purpose register has a defined control/data-transfer role, for example PC, MAR, MDR, CIR or Status Register. <em>[1 distinction; 1 each example]</em></p> },
    ],
  },
  {
    code: "C", title: "Authentic Paper 1 practice", subtitle: "Recent Cambridge wording, concisely adapted", marks: 10,
    questions: [
      { id: "l17-5", marks: 3, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Correct these three statements.</b><p>PC stores the next instruction. CU sends signals on the data bus. MDR transfers data to the address held in MAR.</p><p>Adapted from 9618/12 M/J 2025 Q1(a). [3]</p></>, answer: <p>PC stores the <b>address</b> of the next instruction. CU sends control signals on the <b>control bus</b>. MDR <b>holds</b> data read from, or to be written to, the address held in MAR. <em>[1 each]</em></p> },
      { id: "l17-6", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Describe the Immediate Access Store.</b><p>Adapted from 9618/11 O/N 2023 Q5(b). [2]</p></>, answer: <p>It is fast, volatile storage that holds data, instructions and programs currently in use. <em>[Any two valid points]</em></p> },
      { id: "l17-7", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Describe the roles of ACC and CIR.</b><p>Adapted from 9618/11 O/N 2025 Q6(a). [2]</p></>, answer: <p><b>ACC:</b> stores a value before/after an ALU operation. <b>CIR:</b> stores the instruction currently being decoded/executed. <em>[1 each]</em></p> },
      { id: "l17-8", marks: 3, lines: 4, prompt: <><b>An instruction is stored at memory address 240.</b><p>Name the three registers that successively hold 240, the fetched instruction and then the instruction being decoded.</p></>, answer: <p><b>MAR</b> holds 240; <b>MDR</b> holds the instruction read from memory; <b>CIR</b> holds it while decoding/execution. <em>[1 each]</em></p> },
    ],
  },
];

export default function Lesson17Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "3 min", focus: "Open Chapter 4 with the stored-program idea that connects every later processor topic.", prompt: "Ask: what must be inside a computer before it can follow an instruction?", source: "Syllabus 4.1 p.19; Coursebook Chapter 5, printed pp.80-83 / PDF pp.87-90.", content: <Slide number="01" eyebrow="CHAPTER 4 · PROCESSOR FUNDAMENTALS" sourceLabel="TEXTBOOK CH.5 · pp.80-83" syllabusLabel="SYLLABUS 4.1 · p.19" className="slide--pc-title"><section className="pc-title-grid"><div><span>LESSON 17 · 90 MINUTES</span><h1>The processor<br /><em>remembers what comes next.</em></h1><p>Build the Von Neumann model, then give every CPU component and register its exact job.</p></div><CpuMap /></section></Slide> },
    { time: "4 min", focus: "Make the three assessable outcomes visible before teaching detail.", prompt: "Students translate each outcome into an action verb: explain, label or distinguish.", source: "Syllabus 4.1 p.19.", content: <Slide number="02" eyebrow="TODAY'S SYLLABUS ROUTE" sourceLabel="OFFICIAL SYLLABUS · p.19" syllabusLabel="SYLLABUS 4.1" title="Model → components → registers." className="slide--pc-route"><section className="pc-route-grid"><article><b>1</b><span>MODEL</span><p>stored program</p></article><article><b>2</b><span>CPU</span><p>CU · ALU · clock · IAS</p></article><article><b>3</b><span>REGISTERS</span><p>purpose and role</p></article></section><p className="pc-note">By the end: annotate a processor diagram and answer a register-role question using one precise sentence per mark.</p></Slide> },
    { time: "6 min", focus: "Define the stored-program concept without reducing it to sequential execution.", prompt: "What two kinds of information share memory?", source: "Coursebook 5.01, printed p.81 / PDF p.88; Syllabus 4.1 p.19.", content: <Slide number="03" eyebrow="THE STORED-PROGRAM CONCEPT" sourceLabel="TEXTBOOK 5.01 · p.81" syllabusLabel="SYLLABUS 4.1" title="Instructions and data live in the same memory." className="slide--pc-stored"><section className="pc-memory-bank"><div><span>240</span><b>LDD 512</b><small>instruction</small></div><div><span>241</span><b>ADD 513</b><small>instruction</small></div><div><span>512</span><b>18</b><small>data</small></div><div><span>513</span><b>7</b><small>data</small></div></section><p className="pc-takeaway"><b>Stored program:</b> changing the instructions in memory changes what the same hardware does.</p></Slide> },
    { time: "6 min", focus: "Establish the minimal Von Neumann architecture and normal sequential flow.", prompt: "Point to where instructions wait, where they are processed and where data enters/leaves.", source: "Coursebook 5.01-5.02, printed p.81 / PDF p.88.", content: <Slide number="04" eyebrow="THE BASIC MODEL" sourceLabel="TEXTBOOK 5.01-5.02 · p.81" syllabusLabel="SYLLABUS 4.1" title="One processor fetches from directly accessible memory." className="slide--pc-map"><CpuMap /><section className="pc-sequence"><b>FETCH</b><i>→</i><b>DECODE</b><i>→</i><b>EXECUTE</b><span>normally sequential; a jump can change the next address</span></section></Slide> },
    { time: "7 min", focus: "Differentiate the active CPU components and immediate storage.", prompt: "Give each component one verb: calculate, coordinate, synchronise, hold.", source: "Syllabus 4.1 p.19; Coursebook 5.02 and 5.04, printed pp.82,85 / PDF pp.89,92.", content: <Slide number="05" eyebrow="FOUR CORE ROLES" sourceLabel="TEXTBOOK pp.82,85" syllabusLabel="SYLLABUS 4.1" title="Each component contributes a different part of processing." className="slide--pc-components"><section className="pc-four"><article><span>CU</span><b>COORDINATE</b><p>decodes and sends control signals</p></article><article><span>ALU</span><b>CALCULATE</b><p>arithmetic and logic</p></article><article><span>CLOCK</span><b>SYNCHRONISE</b><p>timing pulses pace activity</p></article><article><span>IAS</span><b>HOLD NOW</b><p>fast, volatile, currently used</p></article></section></Slide> },
    { time: "6 min", focus: "Use Cambridge-safe IAS language grounded in a published mark scheme.", prompt: "Ask which three adjectives or phrases earn the two available marks.", source: "Syllabus 4.1 p.19; adapted from 9618/11 O/N 2023 Q5(b) and published mark scheme.", content: <Slide number="06" eyebrow="IAS · EXAM-SAFE DEFINITION" sourceLabel="9618/11 O/N 2023 · Q5(b)" syllabusLabel="SYLLABUS 4.1 — EXAM PRACTICE" title="IAS holds what the computer is using now." className="slide--pc-dark"><section className="pc-ias"><strong>IMMEDIATE ACCESS STORE</strong><div><b>FAST ACCESS</b><b>VOLATILE</b><b>CURRENT DATA + INSTRUCTIONS + PROGRAMS</b></div></section><p className="pc-dark-note">Do not reduce IAS to “the cache”. The syllabus asks for its role in the computer system.</p></Slide> },
    { time: "6 min", focus: "Explain register speed/capacity and handle the syllabus classification tension safely.", prompt: "Why can a tiny register be useful even though memory is much larger?", source: "Coursebook 5.02, printed pp.82-83 / PDF pp.89-90; Syllabus pp.19,21.", content: <Slide number="07" eyebrow="WHY REGISTERS?" sourceLabel="TEXTBOOK 5.02 · pp.82-83" syllabusLabel="SYLLABUS 4.1" title="Registers are tiny stores beside the working parts of the CPU." className="slide--pc-registers"><section className="pc-register-scale"><article><b>REGISTER</b><span>very small</span><strong>very fast</strong></article><i>↔</i><article><b>IAS / MEMORY</b><span>much larger</span><strong>slower</strong></article></section><div className="pc-caution"><b>EXAM NOTE</b><p>The current instruction model calls ACC the one general-purpose register, while p.19 lists its role with named registers. Learn the role; follow the wording of the question.</p></div></Slide> },
    { time: "7 min", focus: "Connect PC, MAR, MDR and CIR as a chain rather than isolated definitions.", prompt: "Students narrate the arrows using address, memory contents and instruction.", source: "Coursebook Table 5.01, printed p.83 / PDF p.90.", content: <Slide number="08" eyebrow="THE FETCH REGISTER CHAIN" sourceLabel="TEXTBOOK TABLE 5.01 · p.83" syllabusLabel="SYLLABUS 4.1" title="Address first. Memory contents second. Current instruction last." className="slide--pc-chain"><section className="pc-reg-chain"><article><b>PC</b><p>next instruction address</p></article><i>→</i><article><b>MAR</b><p>address being accessed</p></article><i>→</i><article><b>MDR</b><p>instruction fetched</p></article><i>→</i><article><b>CIR</b><p>instruction decoded/executed</p></article></section><p className="pc-note">Lesson 19 will write this movement in register transfer notation.</p></Slide> },
    { time: "6 min", focus: "Complete the register set with ALU, addressing and flag roles.", prompt: "Which register would you inspect after an overflow? Which supports array access?", source: "Coursebook Table 5.01, printed pp.82-83 / PDF pp.89-90; Syllabus 4.1 p.19.", content: <Slide number="09" eyebrow="WORKING VALUES AND FLAGS" sourceLabel="TEXTBOOK 5.02 · pp.82-83" syllabusLabel="SYLLABUS 4.1" title="ACC works with the ALU; IX changes an address; Status records conditions." className="slide--pc-trio"><section className="pc-three"><article><span>ACC</span><b>VALUE / RESULT</b><p>before and after an ALU operation</p></article><article><span>IX</span><b>OFFSET</b><p>added to an address for indexed addressing</p></article><article><span>STATUS</span><b>FLAGS</b><p>zero · carry · negative · overflow</p></article></section></Slide> },
    { time: "7 min", focus: "Apply the full register chain to one concrete instruction.", prompt: "Which object is an address at each stage, and which is the instruction itself?", source: "Derived worked example from Coursebook 5.02 and 5.06.", content: <Slide number="10" eyebrow="WORKED REGISTER JOURNEY" sourceLabel="TEXTBOOK pp.83,87" syllabusLabel="SYLLABUS 4.1" title="Fetch the instruction stored at address 240." className="slide--pc-journey"><section className="pc-journey"><p><b>PC</b><span>240</span></p><i>→</i><p><b>MAR</b><span>240</span></p><i>→</i><p><b>MDR</b><span>LDD 512</span></p><i>→</i><p><b>CIR</b><span>LDD 512</span></p></section><Reveal id="journey" visible={revealed.has("journey")} onToggle={toggleReveal}><p>PC and MAR hold an <b>address</b>. MDR and CIR hold the <b>instruction</b>. After execution, ACC will receive the data stored at address 512.</p></Reveal></Slide> },
    { time: "7 min", focus: "Retrieve all named roles without giving students the answer order.", prompt: "Pairs match seven roles, then explain one rejected match.", source: "Syllabus 4.1 p.19; Coursebook Table 5.01 p.83.", content: <Slide number="11" eyebrow="PAIR CHECK · 7 ROLES" sourceLabel="TEXTBOOK TABLE 5.01" syllabusLabel="SYLLABUS 4.1" title="Which register holds each item?" className="slide--pc-match"><section className="pc-match-grid"><p>next instruction address</p><p>address being accessed</p><p>data crossing memory boundary</p><p>current instruction</p><p>ALU working value</p><p>indexed offset</p><p>condition flags</p></section><Reveal id="match" visible={revealed.has("match")} onToggle={toggleReveal}><p><b>PC · MAR · MDR · CIR · ACC · IX · Status Register</b>, in that order.</p></Reveal></Slide> },
    { time: "8 min", focus: "Use a recent published Paper 1 misconception-correction task.", prompt: "Five minutes silent; then require the corrected subject and object in each sentence.", source: "Adapted from 9618/12 M/J 2025 Q1(a), checked against the published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 3 MARKS" sourceLabel="9618/12 M/J 2025 · Q1(a)" syllabusLabel="SYLLABUS 4.1 — EXAM PRACTICE" title="Correct the three inaccurate statements." className="slide--pc-paper"><section className="pc-paper-list"><p><b>1</b>PC stores the next instruction.</p><p><b>2</b>CU sends signals on the data bus.</p><p><b>3</b>MDR transfers data to the address in MAR.</p></section><Reveal id="paper-a" visible={revealed.has("paper-a")} onToggle={toggleReveal}><p><b>1</b> PC stores the <em>address</em> of the next instruction. <b>2</b> CU sends signals on the <em>control bus</em>. <b>3</b> MDR <em>holds</em> data read from, or waiting to be written to, the address in MAR.</p></Reveal><small>Concise adaptation of 9618/12 M/J 2025 Q1(a).</small></Slide> },
    { time: "7 min", focus: "Practise the two-part register-name plus role marking pattern.", prompt: "Insist that a named register and its matching role are a pair.", source: "Adapted from 9618/12 M/J 2025 Q1(b), checked against published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 2 MARKS" sourceLabel="9618/12 M/J 2025 · Q1(b)" syllabusLabel="SYLLABUS 4.1 — EXAM PRACTICE" title="Name one other F-E register and describe its role." className="slide--pc-paper"><p className="pc-big-question">The question already gives <b>PC, MAR, MDR and ACC.</b><br />Choose one different register.</p><Reveal id="paper-b" visible={revealed.has("paper-b")} onToggle={toggleReveal}><p><b>CIR:</b> stores the instruction currently being decoded/executed. Alternatively, <b>Status Register:</b> stores individual condition/event flags. <em>[1 name + 1 matching role]</em></p></Reveal><small>Adapted from 9618/12 M/J 2025 Q1(b).</small></Slide> },
    { time: "6 min", focus: "Consolidate architecture and registers under short exam timing.", prompt: "One minute per item; students underline the noun each answer must contain.", source: "Syllabus-style consolidation based on 4.1 and Coursebook 5.01-5.02.", content: <Slide number="14" eyebrow="EXAM SPRINT · 6 MARKS" sourceLabel="SYLLABUS-STYLE ORIGINAL" syllabusLabel="SYLLABUS 4.1" title="Six sentences. One precise idea in each." className="slide--pc-sprint"><section className="pc-sprint-grid"><p><b>1</b>Stored program</p><p><b>2</b>ALU role</p><p><b>3</b>CU role</p><p><b>4</b>IAS property</p><p><b>5</b>MAR vs MDR</p><p><b>6</b>Status flag</p></section><Reveal id="sprint" visible={revealed.has("sprint")} onToggle={toggleReveal}><p>Instructions and data share memory; ALU calculates; CU decodes/coordinates; IAS is fast/volatile/current-use storage; MAR holds an address while MDR holds its data/instruction; Status stores condition bits such as zero/carry.</p></Reveal></Slide> },
    { time: "4 min", focus: "Close with a retrieval commitment and direct students to the inline-marked homework.", prompt: "Students say the PC→MAR→MDR→CIR chain without notes.", source: "Lesson 17 synthesis; Syllabus 4.1 p.19.", content: <Slide number="15" eyebrow="EXIT · SAY THE CHAIN" sourceLabel="LESSON 17 SYNTHESIS" syllabusLabel="SYLLABUS 4.1" title="PC → MAR → MDR → CIR." className="slide--pc-exit"><section className="pc-exit-copy"><b>ADDRESS</b><i>→</i><b>ADDRESS</b><i>→</i><b>FETCHED CONTENT</b><i>→</i><b>CURRENT INSTRUCTION</b></section><div className="pc-homework-callout"><b>HOMEWORK 17</b><span>30 marks · 45 minutes · answers beside every question</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="17" slides={slides} homework={<HomeworkSheet lessonNumber="17" title="Von Neumann Architecture and Registers" marks={30} minutes={45} syllabusLabel="SYLLABUS 4.1 · p.19" sourceLabel="TEXTBOOK CH.5 · PRINTED pp.80-83 / PDF pp.87-90 + PAPER 1" instructions="Use one precise role per mark. Where a question asks what a register stores, name the item and distinguish an address from the contents at that address. Past-paper prompts are concise adaptations with original references." sections={homeworkSections} challenge={{ id: "l17-challenge", prompt: <p><Mark>CHALLENGE</Mark> Explain why PC and MAR can temporarily contain the same value but still have different roles.</p>, answer: <p>During fetch, the next-instruction address is copied from PC to MAR. PC identifies the program sequence and is then incremented or changed by a jump; MAR identifies the memory location currently being accessed.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 4.1 p.19, Coursebook Chapter 5 printed pp.80-83 (PDF pp.87-90), and published 2023/2025 Paper 1 questions and mark schemes." sourceDetail="Core: Von Neumann stored-program model; CU, ALU, clock and IAS; PC, MAR, MDR, ACC, IX, CIR and Status Register. Authentic anchors: 9618/12 M/J 2025 Q1(a)-(b), 9618/11 O/N 2025 Q6(a), and 9618/11 O/N 2023 Q5(b). The ACC classification is presented cautiously because syllabus p.19 and the p.21 instruction-set note use different labels; students are trained to follow the exact question wording." />;
}
