"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l25-reveal-${id}`;
  return <div className="ss-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className={visible ? "ss-reveal__panel visible" : "ss-reveal__panel"} hidden={!visible}>{children}</div></div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Why an operating system?", subtitle: "Explain the platform between users, programs and hardware", marks: 10,
    questions: [
      { id: "l25-1", marks: 4, lines: 4, prompt: <><b>A computer starts with no operating system loaded.</b><p>Explain two facilities that the user would lose and why each facility matters.</p></>, answer: <p>Any two developed pairs, for example: no <strong>user interface</strong>, so the user cannot conveniently communicate with the computer; no <strong>program-hardware interface</strong>, so applications would need to control hardware directly; no resource management, so processes could conflict for memory, processor time or devices. <em>[1 facility + 1 explanation each]</em></p> },
      { id: "l25-2", marks: 6, lines: 5, prompt: <><b>Distinguish system software from application software.</b><p>Give one example of each and explain how they interact when a user prints a document.</p></>, answer: <p><strong>System software</strong> operates or supports the computer, for example an OS or device driver. <strong>Application software</strong> performs a user task, for example a word processor. The application sends a print request to the OS; the OS uses the printer driver, schedules access to the device and transfers the output. <em>[2 definitions; 2 examples; 2 interaction]</em></p> },
    ],
  },
  {
    code: "B", title: "The five management tasks", subtitle: "Apply memory, file, security, hardware and process management", marks: 10,
    questions: [
      { id: "l25-3", marks: 3, lines: 3, prompt: <><b>Two programs both request the same memory location.</b><p>Describe how memory management protects the system.</p></>, answer: <p>The OS allocates each process an appropriate area of memory, records which locations are in use and prevents one process accessing another process&apos;s protected locations. <em>[3]</em></p> },
      { id: "l25-4", marks: 3, lines: 3, prompt: <><b>A user saves coursework into a named folder.</b><p>State three file-management tasks involved.</p></>, answer: <p>Valid tasks include applying a file-naming convention, maintaining the directory/folder structure, recording the file location, enforcing access permissions, and supporting create/save/delete operations. <em>[any 3]</em></p> },
      { id: "l25-5", marks: 2, lines: 2, prompt: <><b>A printer and webcam are connected.</b><p>State two hardware-management tasks.</p></>, answer: <p>Install/use the appropriate device drivers; manage communication and access to the devices; handle their hardware interrupts. <em>[any 2]</em></p> },
      { id: "l25-6", marks: 2, lines: 2, prompt: <><b>Three applications are open together.</b><p>State two process-management tasks.</p></>, answer: <p>Schedule processor time between processes and resolve conflicts when processes request the same resource. Accept allocating resources or ensuring fair access. <em>[any 2]</em></p> },
    ],
  },
  {
    code: "C", title: "Authentic Paper 1 practice", subtitle: "Recent 2025 operating-system question forms", marks: 10,
    questions: [
      { id: "l25-7", marks: 5, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>A newly purchased computer includes an operating system.</b><p>Describe five purposes of the OS. Adapted from 9618/11 M/J 2025 Q6(b). [5]</p></>, answer: <p>Award one mark per valid purpose: provide a user interface; manage memory; manage files; manage hardware/input/output; manage processes/processor time; manage security. Developed details are also creditworthy, up to <strong>5</strong>. <em>[5]</em></p> },
      { id: "l25-8", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>State two tasks carried out by hardware management.</b><p>Adapted from 9618/11 O/N 2025 Q5(a)(i). [2]</p></>, answer: <p>Install driver software for devices; manage communication between devices; manage hardware interrupts. <em>[any 2]</em></p> },
      { id: "l25-9", marks: 3, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Memory management is already given.</b><p>Name three other key management tasks performed by an OS. Adapted from 9618/13 O/N 2025 Q8(d). [3]</p></>, answer: <p><strong>File management; security management; hardware/peripheral or input/output management; process management.</strong> <em>[any 3]</em></p> },
    ],
  },
];

export default function Lesson25Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame the operating system as an active manager, not just the desktop screen.", prompt: "Ask students what would stop working if the OS vanished after startup.", source: "Syllabus 5.1; Coursebook Chapter 8 printed pp.121-122.", content: <Slide number="01" eyebrow="CHAPTER 5 · SYSTEM SOFTWARE" sourceLabel="TEXTBOOK CH.8 · pp.121-124" syllabusLabel="SYLLABUS 5.1" className="slide--ss-title"><section className="ss-title-grid"><div className="ss-title-copy"><span>LESSON 25 · 90 MINUTES</span><h1>The invisible<br /><em>manager.</em></h1><p>Why every general-purpose computer needs an operating system—and what its five managers actually do.</p></div><div className="ss-title-visual"><div><b>1</b><span>MEMORY</span></div><div><b>2</b><span>FILES</span></div><div><b>3</b><span>SECURITY</span></div><div><b>4</b><span>HARDWARE</span></div><div><b>5</b><span>PROCESSES</span></div></div></section></Slide> },
    { time: "5 min", focus: "Establish the need for a software platform that hides hardware complexity.", prompt: "Compare launching an app with manually controlling every processor, memory and device action.", source: "Coursebook 8.01 printed p.122; syllabus 5.1 need for an OS.", content: <Slide number="02" eyebrow="WHY AN OS?" sourceLabel="TEXTBOOK p.122" syllabusLabel="SYLLABUS 5.1" title="Applications need services; hardware needs control."><section className="ss-split"><article><span className="ss-kicker">WITHOUT AN OS</span><h3>Every program controls hardware itself</h3><ul><li>different commands for every device</li><li>no shared rules for memory or files</li><li>processes compete without coordination</li></ul></article><article><span className="ss-kicker">WITH AN OS</span><h3>One platform coordinates the system</h3><ul><li>consistent services for applications</li><li>safe, efficient resource allocation</li><li>a usable interface for people</li></ul></article></section></Slide> },
    { time: "5 min", focus: "Locate the OS between application software and physical hardware.", prompt: "Trace a print request down the stack and the completion message back up.", source: "Coursebook pp.122-123: user-system and program-hardware interfaces.", content: <Slide number="03" eyebrow="THE SOFTWARE STACK" sourceLabel="TEXTBOOK pp.122-123" syllabusLabel="SYLLABUS 5.1" title="The OS is the controlled route to the hardware."><section className="ss-os-stack"><div><b>USER</b><span>clicks Print</span></div><div><b>APPLICATION</b><span>requests an OS service</span></div><div><b>OPERATING SYSTEM</b><span>schedules, checks and uses a driver</span></div><div><b>HARDWARE</b><span>printer receives data</span></div></section><p className="ss-note"><strong>User interface:</strong> CLI or GUI. <strong>Program-hardware interface:</strong> applications use OS services instead of device-specific control.</p></Slide> },
    { time: "5 min", focus: "Separate system software from software that performs a user's task.", prompt: "Classify an OS, printer driver, browser and spreadsheet—and justify each choice.", source: "Coursebook p.122 distinction between system and application software.", content: <Slide number="04" eyebrow="SYSTEM OR APPLICATION?" sourceLabel="TEXTBOOK p.122" syllabusLabel="SYLLABUS 5.1" title="Ask what the software is primarily for."><section className="ss-card-grid two"><article><span>SYSTEM SOFTWARE</span><b>Runs or supports the computer</b><p>Operating systems and device drivers manage the platform used by other software.</p></article><article><span>APPLICATION SOFTWARE</span><b>Performs a user task</b><p>A browser, editor or spreadsheet uses services supplied by the operating system.</p></article></section><p className="ss-note">Exam language: the OS <strong>provides an environment in which programs can run</strong>.</p></Slide> },
    { time: "5 min", focus: "Make all five syllabus management categories retrievable as a set.", prompt: "Hide the labels verbally and ask students to reconstruct the five from the examples.", source: "Syllabus 5.1 five key management tasks; Coursebook pp.123-124.", content: <Slide number="05" eyebrow="THE FIVE MANAGERS" sourceLabel="TEXTBOOK pp.123-124" syllabusLabel="SYLLABUS 5.1" title="Every shared resource needs rules."><section className="ss-management-hub"><article><span>01</span><b>Memory</b><p>allocate, protect, optimise</p></article><article><span>02</span><b>Files</b><p>name, locate, organise, protect</p></article><article><span>03</span><b>Security</b><p>authenticate, authorise, recover</p></article><article><span>04</span><b>Hardware</b><p>drivers, communication, interrupts</p></article><article><span>05</span><b>Processes</b><p>schedule and resolve conflicts</p></article></section></Slide> },
    { time: "7 min", focus: "Explain allocation, protection and optimisation as distinct memory-management jobs.", prompt: "Which failure is prevented when one process cannot overwrite another process's memory?", source: "Coursebook p.123 memory management; syllabus 5.1.", content: <Slide number="06" eyebrow="MEMORY MANAGEMENT" sourceLabel="TEXTBOOK p.123" syllabusLabel="SYLLABUS 5.1" title="Give each process space—and keep the spaces safe."><section className="ss-memory-map"><div className="ss-memory-blocks" aria-label="Main memory allocated to processes"><span>OS</span><span>P1</span><span>P1</span><span>P2</span><span>FREE</span><span>P3</span></div><div className="ss-card-grid"><article><span>ALLOCATE</span><b>Choose locations</b><p>Track which blocks are free or in use.</p></article><article><span>PROTECT</span><b>Separate processes</b><p>Prevent unauthorised access to another process&apos;s memory.</p></article><article><span>OPTIMISE</span><b>Use limited RAM well</b><p>Decide what remains in main memory; use virtual memory when needed.</p></article></div></section></Slide> },
    { time: "7 min", focus: "Define process and connect scheduling to efficient, fair resource use.", prompt: "Why is a running music player a process but its stored executable file is not?", source: "Coursebook p.123 process/resource management; syllabus 5.1 process management.", content: <Slide number="07" eyebrow="PROCESS MANAGEMENT" sourceLabel="TEXTBOOK p.123" syllabusLabel="SYLLABUS 5.1" title="A program becomes a process when execution begins."><section className="ss-split"><article><span className="ss-kicker">PROCESS SCHEDULING</span><div className="ss-process-lanes"><div><b>Browser</b><i /></div><div><b>Music</b><i /></div><div><b>Backup</b><i /></div></div></article><article><span className="ss-kicker">OS DECISIONS</span><h3>Who gets the resource next?</h3><ul><li>allocate processor time</li><li>track process states</li><li>resolve competing requests</li><li>support multitasking fairly</li></ul></article></section></Slide> },
    { time: "6 min", focus: "Connect familiar folder actions to underlying file-management responsibilities.", prompt: "Name three OS records needed to retrieve a saved file later.", source: "Coursebook p.123 file management; syllabus 5.1.", content: <Slide number="08" eyebrow="FILE MANAGEMENT" sourceLabel="TEXTBOOK p.123" syllabusLabel="SYLLABUS 5.1" title="A filename is only the start of the job."><section className="ss-split"><div className="ss-folder-tree" aria-label="Folder hierarchy"><span>coursework/</span><span>chapter5/</span><span>lesson25.docx</span><span>diagram.png</span></div><article><span className="ss-kicker">THE OS PROVIDES</span><ul><li>file naming conventions</li><li>directory or folder structures</li><li>location and metadata records</li><li>access-control mechanisms</li><li>create, copy, move and delete services</li></ul></article></section></Slide> },
    { time: "6 min", focus: "Show why device drivers and interrupt handling belong to hardware management.", prompt: "Where would a new printer driver sit in this flow?", source: "Coursebook p.123 device management; 9618/11 O/N 2025 Q5(a)(i).", content: <Slide number="09" eyebrow="HARDWARE MANAGEMENT" sourceLabel="TEXTBOOK p.123" syllabusLabel="SYLLABUS 5.1" title="One OS service; many different devices."><section className="ss-device-bridge"><article><b>APPLICATION</b><p>makes a generic output request</p></article><i>→</i><article><b>OS + DRIVER</b><p>translates, schedules and manages communication</p></article><i>→</i><article><b>DEVICE</b><p>signals completion with an interrupt</p></article></section><p className="ss-note">Key tasks: install/use drivers, manage communication and access, and handle hardware interrupts.</p></Slide> },
    { time: "6 min", focus: "Keep security management distinct from later cybersecurity mechanisms.", prompt: "For each control, identify whether it prevents, limits, records or recovers.", source: "Coursebook p.124 security management; 9618/11 O/N 2025 Q5(a)(ii).", content: <Slide number="10" eyebrow="SECURITY MANAGEMENT" sourceLabel="TEXTBOOK p.124" syllabusLabel="SYLLABUS 5.1" title="Decide who may do what—and preserve a route back."><section className="ss-security-shield"><div className="ss-shield">OS<br />SECURITY</div><div className="ss-security-list"><p><b>Authenticate</b> users and processes.</p><p><b>Authorise</b> actions with access rights and permissions.</p><p><b>Audit</b> activity using logs.</p><p><b>Update</b> operating-system security.</p><p><b>Recover</b> lost data through planned provision.</p></div></section></Slide> },
    { time: "8 min", focus: "Apply the five categories to one realistic multitasking scenario.", prompt: "Pairs assign every numbered event to one management task; some events may involve two.", source: "Coursebook Task 8.01 concept, adapted to syllabus 5.1 categories.", content: <Slide number="11" eyebrow="CLASSIFY THE OS WORK" sourceLabel="TEXTBOOK TASK 8.01" syllabusLabel="SYLLABUS 5.1" title="One action can involve several managers."><section className="ss-scenario-board"><article><h3>A student opens a protected file, edits it and prints while music plays.</h3><ol><li>verify the login</li><li>locate and open the file</li><li>allocate RAM to the editor</li><li>share processor time with music</li><li>send output through a printer driver</li></ol></article><article><span className="ss-kicker">YOUR LABELS</span><p>Security · File · Memory · Process · Hardware</p><Reveal id="scenario" visible={revealed.has("scenario")} onToggle={toggleReveal}><p><strong>1 Security; 2 File; 3 Memory; 4 Process; 5 Hardware.</strong> Printing may also involve process scheduling and access permissions.</p></Reveal></article></section></Slide> },
    { time: "10 min", focus: "Practise the broad five-mark purpose question using mark-scheme-sized points.", prompt: "Give students five minutes closed-book, then reveal and self-mark one distinct purpose per point.", source: "Adapted from 9618/11 M/J 2025 Q6(b), checked against the published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 5 MARKS" sourceLabel="9618/11 M/J 2025 · Q6(b)" syllabusLabel="SYLLABUS 5.1 — EXAM PRACTICE" title="A computer includes an OS. Describe five purposes." className="slide--ss-paper"><section className="ss-paper-grid"><article><span>RULE 1</span><p>Write <strong>five distinct functions</strong>, not five examples of one function.</p></article><article><span>RULE 2</span><p>Use a management verb: provides, allocates, protects, schedules or controls.</p></article></section><Reveal id="paper-purpose" visible={revealed.has("paper-purpose")} onToggle={toggleReveal}><p>User interface; memory management; file management; hardware/input-output management; process management; security management. Any five valid purposes score. </p></Reveal><small>Adapted from 9618/11 M/J 2025 Q6(b).</small></Slide> },
    { time: "8 min", focus: "Target the more precise hardware/security task wording seen in 2025.", prompt: "Students produce four short, non-overlapping task statements under three minutes.", source: "Adapted from 9618/11 O/N 2025 Q5(a), checked against the published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/11 O/N 2025 · Q5(a)" syllabusLabel="SYLLABUS 5.1 — EXAM PRACTICE" title="Give two hardware tasks and two security tasks." className="slide--ss-paper"><section className="ss-paper-grid"><article><span>HARDWARE · 2</span><p>What must the OS do for connected devices?</p></article><article><span>SECURITY · 2</span><p>What must the OS do about users, permissions or recovery?</p></article></section><Reveal id="paper-tasks" visible={revealed.has("paper-tasks")} onToggle={toggleReveal}><p><strong>Hardware:</strong> install/use drivers; manage device communication; handle interrupts. <strong>Security:</strong> authenticate; enforce access rights; update security; audit/log; provide recovery. Award any two in each category.</p></Reveal><small>Adapted from 9618/11 O/N 2025 Q5(a)(i)-(ii).</small></Slide> },
    { time: "5 min", focus: "Use rapid retrieval to expose confused categories before the exit.", prompt: "Call one scenario at a time; students answer with only the management category and one verb.", source: "Syllabus 5.1 retrieval practice; 2025 Paper 1 command-word patterns.", content: <Slide number="14" eyebrow="60-SECOND RETRIEVAL" sourceLabel="SYLLABUS-STYLE ORIGINAL" syllabusLabel="SYLLABUS 5.1" title="Name the manager. Add the action."><section className="ss-card-grid four"><article><span>01</span><b>Two apps need the CPU</b><p>Process: schedule</p></article><article><span>02</span><b>A USB printer arrives</b><p>Hardware: driver</p></article><article><span>03</span><b>A user opens a folder</b><p>File: locate/access</p></article><article><span>04</span><b>One app reaches another&apos;s RAM</b><p>Memory: protect</p></article></section><p className="ss-note">Add a fifth: a failed login → <strong>security management: authenticate and deny access</strong>.</p></Slide> },
    { time: "3 min", focus: "Close with a compact, actionable checklist and direct students to homework.", prompt: "Students state one category they can explain and one they need to revisit.", source: "Syllabus 5.1 completion check; Coursebook pp.121-124.", content: <Slide number="15" eyebrow="LESSON 25 · EXIT" sourceLabel="TEXTBOOK pp.121-124" syllabusLabel="SYLLABUS 5.1" title="Interface. Coordinate. Protect." className="slide--ss-exit"><section className="ss-exit-grid"><article><b>EXPLAIN THE NEED</b><p>The OS provides a usable platform between people, programs and hardware.</p></article><article><b>NAME ALL FIVE</b><p>Memory, files, security, hardware and processes.</p></article><article><b>APPLY THE VERB</b><p>Allocate, organise, authenticate, control or schedule.</p></article></section><div className="ss-homework-callout"><b>HOMEWORK 25</b><span>30 marks · three verified 2025 Paper 1 anchors · inline answers</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="25" slides={slides} homework={<HomeworkSheet lessonNumber="25" title="Operating Systems and Management Tasks" marks={30} minutes={45} syllabusLabel="SYLLABUS 5.1" sourceLabel="TEXTBOOK CH.8 · pp.121-124 + PAPER 1" instructions="Use precise management verbs and make each mark point distinct. Recent-paper questions are concise adaptations; answers follow the published 2025 mark schemes." sections={homeworkSections} challenge={{ id: "l25-challenge", prompt: <p><Mark>CHALLENGE</Mark> A video call, virus scan and backup run together while a student prints. Explain how three OS management tasks interact to keep the system responsive and safe.</p>, answer: <p>Process management schedules processor time between the call, scan, backup and print process. Memory management allocates and protects their working areas. Hardware management coordinates camera, microphone, storage and printer through drivers and interrupts. Security management controls permissions, and file management coordinates files read or written. Any three linked explanations are valid.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 5.1, Coursebook Chapter 8 printed pp.121-124, and published 2025 Paper 1 questions and mark schemes." sourceDetail="Core: explain why an operating system is needed and describe memory, file, security, hardware and process management. Authentic anchors: 9618/11 M/J 2025 Q6(b), 9618/11 O/N 2025 Q5(a), and 9618/13 O/N 2025 Q8(d). Detailed scheduling algorithms and implementation-level virtual-memory mechanisms are outside this lesson." />;
}
