"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Read SQL precisely", subtitle: "DDL, DML and the seven syllabus data types", marks: 10,
    questions: [
      { id: "l39-1", marks: 3, lines: 3, prompt: <><b>Distinguish DDL, DML and SQL.</b></>, answer: <p>DDL creates or changes database structure, such as databases, tables and constraints. DML queries or maintains the rows stored in those structures. SQL is the industry-standard language containing both DDL and DML statements. <em>[3]</em></p> },
      { id: "l39-2", marks: 4, lines: 4, prompt: <><b>Select a suitable SQL data type for IsActive, BirthDate, Score and FamilyName (maximum 40 characters).</b></>, answer: <p>IsActive: BOOLEAN; BirthDate: DATE; Score: INTEGER if whole numbers or REAL if fractions are permitted; FamilyName: VARCHAR(40). Award Score only with a reasonable stated assumption. <em>[4]</em></p> },
      { id: "l39-3", marks: 3, lines: 3, prompt: <><b>Explain the purpose of PRIMARY KEY and FOREIGN KEY constraints.</b></>, answer: <p>PRIMARY KEY makes the selected field/set unique and non-null so each row is identifiable. FOREIGN KEY identifies the referencing field and referenced table/key, allowing the DBMS to enforce valid relationships/referential integrity. <em>[3]</em></p> },
    ],
  },
  {
    code: "B", title: "Define the structure", subtitle: "CREATE and ALTER scripts", marks: 10,
    questions: [
      { id: "l39-4", marks: 2, lines: 2, prompt: <><b>Write SQL to create a database called LibraryDB.</b></>, answer: <pre>CREATE DATABASE LibraryDB;</pre> },
      { id: "l39-5", marks: 6, lines: 5, prompt: <><b>Write SQL to create AUTHOR(AuthorID, AuthorName, BirthDate). AuthorID is the primary key and AuthorName allows up to 60 characters.</b></>, answer: <pre>CREATE TABLE AUTHOR ({"\n"}   AuthorID INTEGER,{"\n"}   AuthorName VARCHAR(60),{"\n"}   BirthDate DATE,{"\n"}   PRIMARY KEY (AuthorID){"\n"});</pre> },
      { id: "l39-6", marks: 2, lines: 3, prompt: <><b>BOOK already contains AuthorID. Write SQL to add a foreign-key constraint that references AUTHOR.AuthorID.</b></>, answer: <pre>ALTER TABLE BOOK{"\n"}ADD FOREIGN KEY (AuthorID){"\n"}REFERENCES AUTHOR (AuthorID);</pre> },
    ],
  },
  {
    code: "C", title: "Published DDL practice", subtitle: "CREATE TABLE and ALTER TABLE", marks: 10,
    questions: [
      { id: "l39-7", marks: 4, lines: 6, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Write CREATE TABLE for STAFF with StaffID, StaffName, Department, JobTitle and RemoteWorker, choosing suitable types and a primary key.</b><p>Adapted from 9618/13 O/N 2025 Q5(b). [4]</p></>, answer: <pre>CREATE TABLE STAFF ({"\n"}   StaffID INTEGER,{"\n"}   StaffName VARCHAR(60),{"\n"}   Department VARCHAR(40),{"\n"}   JobTitle VARCHAR(50),{"\n"}   RemoteWorker BOOLEAN,{"\n"}   PRIMARY KEY (StaffID){"\n"});</pre> },
      { id: "l39-8", marks: 2, lines: 3, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Add ExamID in EXAM_QUESTION as a foreign key referencing EXAM.</b><p>Adapted from 9618/12 M/J 2024 Q4(c). [2]</p></>, answer: <pre>ALTER TABLE EXAM_QUESTION{"\n"}ADD FOREIGN KEY (ExamID){"\n"}REFERENCES EXAM (ExamID);</pre> },
      { id: "l39-9", marks: 4, lines: 4, prompt: <><b>Explain what this statement returns:</b><pre>SELECT StaffName FROM STAFF{"\n"}WHERE RemoteWorker = TRUE{"\n"}ORDER BY StaffName;</pre></>, answer: <p>It reads rows in STAFF, keeps only rows whose RemoteWorker value is TRUE, returns only StaffName, and sorts the result in ascending alphabetical order because no DESC is specified. <em>[4]</em></p> },
    ],
  },
];

export default function Lesson39Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Separate structure from stored rows using one database change and one query.", prompt: "Ask: which command changes the blueprint, and which reads the contents?", source: "Coursebook 11.07 printed pp.170-172; syllabus 8.3.", content: <Slide number="01" eyebrow="CHAPTER 8 · SQL DDL" sourceLabel="TEXTBOOK CH.11 · pp.170-172" syllabusLabel="SYLLABUS 8.3" className="da-title"><section className="da-title-grid"><div className="da-title-copy"><span>LESSON 39 · 90 MINUTES</span><h1>Write the database<br /><em>blueprint.</em></h1><p>Distinguish DDL from DML, choose syllabus data types and write valid CREATE and ALTER statements with primary and foreign keys.</p></div><div className="da-title-map"><div><b>DDL</b><span>DEFINE OR CHANGE STRUCTURE</span></div><div><b>DML</b><span>QUERY OR MAINTAIN DATA</span></div><div><b>PK</b><span>IDENTIFY EACH ROW</span></div><div><b>FK</b><span>ENFORCE THE LINK</span></div></div></section></Slide> },
    { time: "5 min", focus: "Map every examinable DDL element and the small DML bridge.", prompt: "Students highlight the seven data types from the syllabus badge.", source: "Syllabus 8.3 pp.26-27; Coursebook 11.07 printed pp.170-172.", content: <Slide number="02" eyebrow="TEXTBOOK × SYLLABUS" sourceLabel="TEXTBOOK §11.07 · pp.170-172" syllabusLabel="SYLLABUS 8.3" title="DDL creates structure; core DML reads rows."><section className="da-grid four"><article className="da-card"><span>CREATE</span><p>CREATE DATABASE and CREATE TABLE</p></article><article className="da-card"><span>DATA TYPES</span><p>CHARACTER, VARCHAR(n), BOOLEAN, INTEGER, REAL, DATE, TIME</p></article><article className="da-card"><span>CONSTRAINTS</span><p>PRIMARY KEY and FOREIGN KEY … REFERENCES</p></article><article className="da-card"><span>ALTER + READ</span><p>ALTER TABLE; SELECT/FROM/WHERE/ORDER BY</p></article></section><p className="da-note">Aggregates, GROUP BY, INNER JOIN and data maintenance are Lesson 40.</p></Slide> },
    { time: "6 min", focus: "Define DDL, DML and SQL with examples.", prompt: "Students classify six statement starters without completing the syntax.", source: "Coursebook 11.07 printed pp.170-173; syllabus 8.3.", content: <Slide number="03" eyebrow="ONE LANGUAGE · TWO PURPOSES" sourceLabel="TEXTBOOK §11.07 · pp.170-173" syllabusLabel="SYLLABUS 8.3" title="SQL includes both definition and manipulation statements."><section className="da-grid two"><article className="da-card"><span>DDL · DATA DEFINITION LANGUAGE</span><h3>Changes the schema</h3><p>CREATE DATABASE, CREATE TABLE, ALTER TABLE, PRIMARY KEY and FOREIGN KEY constraints.</p></article><article className="da-card"><span>DML · DATA MANIPULATION LANGUAGE</span><h3>Works with stored rows</h3><p>SELECT queries data; INSERT, UPDATE and DELETE maintain it.</p></article></section><p className="da-warning">A DBMS carries out the command. SQL is the standard language used to express the request.</p></Slide> },
    { time: "6 min", focus: "Choose only the data types named in the 2027 syllabus.", prompt: "Give one plausible field for each type; discuss INTEGER versus REAL.", source: "Syllabus 8.3 specified types; Coursebook 11.07 updated.", content: <Slide number="04" eyebrow="SEVEN EXAMINABLE DATA TYPES" sourceLabel="TEXTBOOK §11.07 · SYLLABUS UPDATED" syllabusLabel="SYLLABUS 8.3" title="Match the domain, not the appearance of the sample."><table className="da-table"><thead><tr><th>TYPE</th><th>USE</th><th>EXAMPLE FIELD</th></tr></thead><tbody><tr><td><strong>CHARACTER</strong></td><td>fixed/single character in this course context</td><td>Grade</td></tr><tr><td><strong>VARCHAR(n)</strong></td><td>variable-length text up to n</td><td>FamilyName VARCHAR(40)</td></tr><tr><td><strong>BOOLEAN</strong></td><td>TRUE/FALSE</td><td>Returned</td></tr><tr><td><strong>INTEGER / REAL</strong></td><td>whole / fractional number</td><td>Quantity / Mass</td></tr><tr><td><strong>DATE / TIME</strong></td><td>calendar date / time of day</td><td>LoanDate / StartTime</td></tr></tbody></table></Slide> },
    { time: "6 min", focus: "Build correct CREATE DATABASE and CREATE TABLE skeletons.", prompt: "Students supply commas, brackets and the final semicolon.", source: "Coursebook 11.07 printed pp.170-171, syntax corrected; syllabus 8.3.", content: <Slide number="05" eyebrow="CREATE THE STRUCTURE" sourceLabel="TEXTBOOK §11.07 · pp.170-171" syllabusLabel="SYLLABUS 8.3" title="A table definition lists fields, types and constraints."><pre className="da-code"><strong>CREATE DATABASE</strong> ClubDB;{"\n\n"}<strong>CREATE TABLE</strong> CLUB ({"\n"}   ClubID INTEGER,{"\n"}   ClubName VARCHAR(50),{"\n"}   MeetingDay CHARACTER,{"\n"}   Active BOOLEAN,{"\n"}   PRIMARY KEY (ClubID){"\n"});</pre><p className="da-note">Use commas between definitions, parentheses around the table body and a semicolon to terminate the statement.</p></Slide> },
    { time: "6 min", focus: "Write primary and foreign key constraints with valid references.", prompt: "Ask why StudentID may repeat in MEMBERSHIP even though it is a foreign key.", source: "Coursebook 11.07 printed pp.170-171, corrected; syllabus 8.3.", content: <Slide number="06" eyebrow="DECLARE THE KEYS" sourceLabel="TEXTBOOK §11.07 · CORRECTED" syllabusLabel="SYLLABUS 8.3" title="Constraints make identity and relationships executable."><pre className="da-code">CREATE TABLE MEMBERSHIP ({"\n"}   StudentID INTEGER,{"\n"}   ClubID INTEGER,{"\n"}   JoinedDate DATE,{"\n"}   <strong>PRIMARY KEY (StudentID, ClubID)</strong>,{"\n"}   <span className="accent">FOREIGN KEY (StudentID) REFERENCES STUDENT (StudentID)</span>,{"\n"}   <span className="accent">FOREIGN KEY (ClubID) REFERENCES CLUB (ClubID)</span>{"\n"});</pre></Slide> },
    { time: "6 min", focus: "Introduce ALTER TABLE and the readable core of single-table DML.", prompt: "Students identify clause order and execution meaning.", source: "Coursebook 11.07 printed pp.170-172; syllabus 8.3.", content: <Slide number="07" eyebrow="CHANGE THE BLUEPRINT · READ THE ROWS" sourceLabel="TEXTBOOK §11.07 · pp.170-172" syllabusLabel="SYLLABUS 8.3" title="ALTER changes structure; SELECT states the required result."><section className="da-grid two"><article className="da-card"><span>DDL</span><pre className="da-code">ALTER TABLE BOOK{"\n"}ADD FOREIGN KEY (AuthorID){"\n"}REFERENCES AUTHOR (AuthorID);</pre></article><article className="da-card"><span>DML</span><pre className="da-code">SELECT Title{"\n"}FROM BOOK{"\n"}WHERE InStock = TRUE{"\n"}ORDER BY Title;</pre></article></section></Slide> },
    { time: "7 min", focus: "Construct two linked tables from a clean schema.", prompt: "Students verify types, commas, PKs and the FK reference line by line.", source: "Coursebook 11.07 method; syllabus 8.3 DDL.", content: <Slide number="08" eyebrow="WORKED DDL · AUTHOR + BOOK" sourceLabel="TEXTBOOK §11.07 · APPLICATION" syllabusLabel="SYLLABUS 8.3" title="Turn the logical schema into executable definitions."><pre className="da-code">CREATE TABLE AUTHOR (AuthorID INTEGER, AuthorName VARCHAR(60), PRIMARY KEY (AuthorID));{"\n\n"}CREATE TABLE BOOK ({"\n"}   BookID INTEGER, Title VARCHAR(100), Price REAL, Published DATE,{"\n"}   AuthorID INTEGER, PRIMARY KEY (BookID),{"\n"}   FOREIGN KEY (AuthorID) REFERENCES AUTHOR (AuthorID){"\n"});</pre><p className="da-note">Define the referenced parent table before the child table that uses its key.</p></Slide> },
    { time: "6 min", focus: "Correct high-risk syntax and semantics in the older textbook examples.", prompt: "Students repair each red fragment aloud.", source: "Coursebook 11.07 printed pp.170-173, corrected to syllabus SQL subset.", content: <Slide number="09" eyebrow="TEXTBOOK SQL · REQUIRED CORRECTIONS" sourceLabel="TEXTBOOK §11.07 · UPDATED" syllabusLabel="SYLLABUS 8.3" title="Use the current syllabus subset and valid SQL form."><section className="da-compare"><div><span>AVOID</span><span>USE</span><span>WHY</span></div><div><b>Band-Booking</b><span>BandBooking or Band_Booking</span><span>hyphen is an operator unless the identifier is quoted</span></div><div><b>VARCHAR2</b><span>VARCHAR(n)</span><span>2027 syllabus specifies VARCHAR(n)</span></div><div><b>FOREIGN KEY Name) REFERENCES…</b><span>FOREIGN KEY (Name) REFERENCES Table (Name)</span><span>parentheses must be balanced</span></div><div><b>SQL is never case-sensitive</b><span>uppercase keywords; quote string literals</span><span>identifier/string behaviour depends on DBMS and collation</span></div></section></Slide> },
    { time: "6 min", focus: "Guide students through a DDL construction checklist.", prompt: "Pairs write EVENT and BOOKING definitions from the displayed attribute list.", source: "Syllabus 8.3 write simple DDL; Coursebook 11.07.", content: <Slide number="10" eyebrow="GUIDED CONSTRUCTION" sourceLabel="TEXTBOOK §11.07 · APPLICATION" syllabusLabel="SYLLABUS 8.3" title="From schema notation to SQL without losing a constraint."><section className="da-flow"><span>NAME TABLE<br />+ FIELDS</span><i>→</i><span>CHOOSE EACH<br />DATA TYPE</span><i>→</i><span>ADD PRIMARY<br />KEY</span><i>→</i><span>ADD FOREIGN KEY<br />+ REFERENCES</span></section><pre className="da-code">EVENT(<strong>EventID</strong>, EventName, EventDate){"\n"}BOOKING(<strong>BookingID</strong>, <span className="accent">EventID</span>, Seats, Paid)</pre></Slide> },
    { time: "7 min", focus: "Teach a fast DDL accuracy audit.", prompt: "Students annotate a model answer using the four audit headings.", source: "9618/13 O/N 2025 Q5(b) mark scheme; syllabus 8.3.", content: <Slide number="11" eyebrow="EXAM METHOD · FOUR-PASS AUDIT" sourceLabel="9618/13 O/N 2025 · Q5(b)" syllabusLabel="SYLLABUS 8.3 — PAPER 1" title="Structure · fields · types · constraints."><section className="da-grid four"><article className="da-card"><span>1 · STRUCTURE</span><p>CREATE TABLE, parentheses, commas, semicolon</p></article><article className="da-card"><span>2 · FIELDS</span><p>every required identifier exactly once</p></article><article className="da-card"><span>3 · TYPES</span><p>text length, Boolean, numeric/date/time domain</p></article><article className="da-card"><span>4 · KEYS</span><p>correct PK and any FK reference</p></article></section></Slide> },
    { time: "8 min", focus: "Attempt a published CREATE TABLE item.", prompt: "Students write the complete statement in five minutes, then self-mark one point per category.", source: "Adapted from 9618/13 O/N 2025 Q5(b), checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/13 O/N 2025 · Q5(b)" syllabusLabel="SYLLABUS 8.3 — PAPER 1" title="Create STAFF with suitable fields, types and primary key." className="slide--da-paper"><section className="da-paper-grid three"><article><span>TEXT FIELDS</span><p>name, department and job title</p></article><article><span>ID + BOOLEAN</span><p>StaffID and RemoteWorker</p></article><article><span>CONSTRAINT</span><p>StaffID is the primary key</p></article></section><ExamReveal><p>One valid answer: CREATE TABLE STAFF (StaffID INTEGER, StaffName VARCHAR(60), Department VARCHAR(40), JobTitle VARCHAR(50), RemoteWorker BOOLEAN, PRIMARY KEY (StaffID)); Marks reward overall syntax, suitable text types, suitable ID/Boolean types and the correct primary key.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [4].</small></Slide> },
    { time: "8 min", focus: "Attempt a published ALTER TABLE foreign-key item.", prompt: "Students identify the table being altered, then the referencing and referenced fields.", source: "Adapted from 9618/12 M/J 2024 Q4(c), checked against published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 2 MARKS" sourceLabel="9618/12 M/J 2024 · Q4(c)" syllabusLabel="SYLLABUS 8.3 — PAPER 1" title="Add ExamID as a foreign key in EXAM_QUESTION." className="slide--da-paper"><pre className="da-code">ALTER TABLE EXAM_QUESTION{"\n"}ADD ____________________________________{"\n"}________________________________________;</pre><ExamReveal><p>ALTER TABLE EXAM_QUESTION ADD FOREIGN KEY (ExamID) REFERENCES EXAM (ExamID); One mark identifies the correct table/ALTER form; one correctly defines the foreign-key reference.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [2].</small></Slide> },
    { time: "5 min", focus: "Retrieve the full DDL grammar and read one DML statement.", prompt: "Students fill the missing tokens without notes.", source: "Syllabus 8.3 synthesis; Coursebook 11.07.", content: <Slide number="14" eyebrow="MIXED RETRIEVAL" sourceLabel="TEXTBOOK §11.07 · REVIEW" syllabusLabel="SYLLABUS 8.3" title="Can you reconstruct each statement family?"><section className="da-flow"><span>CREATE DATABASE<br />name ;</span><i>→</i><span>CREATE TABLE<br />(fields + types)</span><i>→</i><span>PRIMARY / FOREIGN<br />KEY CONSTRAINTS</span><i>→</i><span>SELECT · FROM<br />WHERE · ORDER BY</span></section></Slide> },
    { time: "4 min", focus: "Close with a classification, type and syntax check.", prompt: "Collect one response per card before Lesson 40.", source: "Syllabus 8.3 checkpoint; Coursebook Chapter 11 sequence.", content: <Slide number="15" eyebrow="EXIT TICKET · NEXT: DML" sourceLabel="TEXTBOOK CH.11 · pp.170-172" syllabusLabel="SYLLABUS 8.3" title="Three checks before querying two tables."><section className="da-exit"><article><span>CLASSIFY</span><p>Is CREATE TABLE DDL or DML—and why?</p></article><article><span>CHOOSE</span><p>Which type stores a fractional measurement?</p></article><article><span>WRITE</span><p>Give the complete FOREIGN KEY … REFERENCES form.</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="39" slides={slides} homework={<HomeworkSheet lessonNumber="39" title="SQL DDL and Core Single-Table DML" marks={30} minutes={45} syllabusLabel="SYLLABUS 8.3" sourceLabel="TEXTBOOK CH.11 · pp.170-172 + PAPER 1" instructions="Write uppercase SQL keywords, one definition per line and a semicolon at the end. Audit brackets, commas, field names, syllabus data types and key constraints before checking the answer." sections={homeworkSections} challenge={{ id: "l39-challenge", prompt: <p><Mark>CHALLENGE</Mark> Write linked CREATE TABLE statements for TEAM and PLAYER, then explain why TEAM should be created first.</p>, answer: <p>TEAM(TeamID PK, TeamName) is the referenced parent. PLAYER(PlayerID PK, PlayerName, TeamID FK) references TEAM(TeamID). Creating TEAM first ensures the referenced table/key exists when PLAYER&apos;s foreign-key constraint is defined.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 8.3, Coursebook Chapter 11 printed pp.170-172 (PDF pp.177-179), published Paper 1 questions/mark schemes and the current syllabus SQL subset." sourceDetail="Core: SQL as DDL and DML, CREATE DATABASE, CREATE TABLE, CHARACTER/VARCHAR(n)/BOOLEAN/INTEGER/REAL/DATE/TIME, ALTER TABLE, PRIMARY KEY, FOREIGN KEY REFERENCES, plus SELECT/FROM/WHERE/ORDER BY reading. Authentic anchors: 9618/13 O/N 2025 Q5(b) [4] and 9618/12 M/J 2024 Q4(c) [2]." />;
}
