"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l26-reveal-${id}`;
  return <div className="ss-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className={visible ? "ss-reveal__panel visible" : "ss-reveal__panel"} hidden={!visible}>{children}</div></div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Choose the utility", subtitle: "Match each maintenance problem to a precise utility", marks: 10,
    questions: [
      { id: "l26-1", marks: 2, lines: 2, prompt: <><b>Define utility software.</b></>, answer: <p>A utility is system software that performs a maintenance, protection or optimisation task. It can be supplied with the OS or installed separately and is run when needed rather than forming part of normal OS operation. <em>[any 2]</em></p> },
      { id: "l26-2", marks: 6, lines: 5, prompt: <><b>Name the most appropriate utility for each need:</b><p>(i) prepare a reused disk; (ii) detect malware; (iii) place split magnetic-disk file blocks together; (iv) find bad sectors; (v) reduce an email attachment; (vi) create a restorable second copy.</p></>, answer: <p>(i) <strong>disk formatter</strong>; (ii) <strong>virus checker</strong>; (iii) <strong>defragmentation software</strong>; (iv) <strong>disk contents analysis/disk repair software</strong>; (v) <strong>file compression software</strong>; (vi) <strong>backup software</strong>. <em>[1 each]</em></p> },
      { id: "l26-3", marks: 2, lines: 3, prompt: <><b>Explain why a virus checker needs regular updates.</b></>, answer: <p>New malware appears after the utility is released, so the checker needs new signatures/patterns or detection rules to recognise it. <em>[1 new malware; 1 updated detection information]</em></p> },
    ],
  },
  {
    code: "B", title: "Libraries and DLLs", subtitle: "Explain reuse, linking and the dependency trade-off", marks: 10,
    questions: [
      { id: "l26-4", marks: 3, lines: 3, prompt: <><b>Explain three benefits of using a program-library routine.</b></>, answer: <p>Any three: saves coding time because code is pre-written; saves testing time because a routine is already tested/documented; increases reliability; provides complex functionality the programmer may not be able to write; can improve readability because a named routine is called. <em>[3]</em></p> },
      { id: "l26-5", marks: 4, lines: 4, prompt: <><b>Contrast copying a library routine into every executable with using a DLL.</b></>, answer: <p>A copied/static routine becomes part of each executable, increasing storage and possibly duplicating it in memory. A DLL remains separate; executables include a link and processes can share one loaded copy, reducing executable size and memory use. <em>[2 static; 2 DLL]</em></p> },
      { id: "l26-6", marks: 3, lines: 3, prompt: <><b>Describe one benefit and one risk of replacing a DLL with a newer version.</b></>, answer: <p><strong>Benefit:</strong> programs using the shared routine can receive a fix or improvement without each executable being rebuilt. <strong>Risk:</strong> the new DLL may be missing, incompatible, corrupt or buggy, causing dependent programs to fail or give incorrect results. <em>[1 benefit; 1 risk; 1 developed consequence]</em></p> },
    ],
  },
  {
    code: "C", title: "Authentic Paper 1 practice", subtitle: "Utility and program-library forms from 2025", marks: 10,
    questions: [
      { id: "l26-7", marks: 2, lines: 2, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Image files on a restaurant touchscreen have become corrupted.</b><p>Identify two utilities that could recover the images. Adapted from 9618/12 O/N 2025 Q8(b)(ii). [2]</p></>, answer: <p><strong>Disk repair/disk contents analysis software</strong> and <strong>backup software</strong>. <em>[1 each]</em></p> },
      { id: "l26-8", marks: 3, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain how program libraries benefit a programmer during development.</b><p>Adapted from 9618/13 O/N 2025 Q8(b). [3]</p></>, answer: <p>Any three: save programming time through pre-written code; save testing time because routines are tested/documented; improve reliability; provide complex procedures; routines may be updated or improved. <em>[3]</em></p> },
      { id: "l26-9", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Describe one benefit and one drawback of library routines.</b><p>Develop each point. Adapted from 9618/11 O/N 2025 Q5(b). [4]</p></>, answer: <p><strong>Benefit:</strong> for example, less code is written because the routine is pre-written, reducing development time. <strong>Drawback:</strong> for example, compatibility or quality is not guaranteed, so the routine may cause unexpected errors or require editing and retesting. <em>[1 point + 1 development each]</em></p> },
      { id: "l26-10", marks: 1, lines: 2, prompt: <><b>A large log file must be transmitted but remain bit-for-bit exact.</b><p>Name the relevant utility action.</p></>, answer: <p>Use <strong>lossless file compression</strong>, then decompress at the destination. <em>[1]</em></p> },
    ],
  },
];

export default function Lesson26Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame utilities as specialist tools and libraries as reusable program components.", prompt: "Ask which tool repairs the system and which tool helps build new software.", source: "Syllabus 5.1; Coursebook Chapter 8 printed pp.124-127.", content: <Slide number="01" eyebrow="CHAPTER 5 · SYSTEM SOFTWARE" sourceLabel="TEXTBOOK CH.8 · pp.124-127" syllabusLabel="SYLLABUS 5.1" className="slide--ss-title"><section className="ss-title-grid"><div className="ss-title-copy"><span>LESSON 26 · 90 MINUTES</span><h1>Maintain.<br /><em>Reuse.</em></h1><p>Choose the right utility for the job, then explain how program libraries and DLLs reuse trusted code.</p></div><div className="ss-title-visual"><div><b>1</b><span>FORMAT · CHECK</span></div><div><b>2</b><span>SCAN · REPAIR</span></div><div><b>3</b><span>COMPRESS · BACK UP</span></div><div><b>4</b><span>LINK · SHARE</span></div></div></section></Slide> },
    { time: "5 min", focus: "Define utility software without incorrectly equating it with the whole OS.", prompt: "Is a backup utility always running as part of the OS? Why might it still run automatically?", source: "Coursebook 8.03 printed p.124; syllabus 5.1 utility software.", content: <Slide number="02" eyebrow="WHAT IS A UTILITY?" sourceLabel="TEXTBOOK p.124" syllabusLabel="SYLLABUS 5.1" title="A focused system-maintenance program."><section className="ss-flow"><article><b>PROBLEM</b><p>storage, malware, damage or transfer need</p></article><i>→</i><article><b>UTILITY RUNS</b><p>started by a user, the OS or a schedule</p></article><i>→</i><article><b>SYSTEM IMPROVES</b><p>prepared, protected, repaired or recoverable</p></article></section><p className="ss-note">A utility may be supplied with the OS or installed separately. It is invoked when needed; it is not the whole operating system.</p></Slide> },
    { time: "5 min", focus: "Make the complete six-item syllabus list visible and memorable.", prompt: "Students pair each noun with its action verb before details are shown.", source: "Syllabus 5.1 six utility types; Coursebook pp.124-126.", content: <Slide number="03" eyebrow="THE SIX REQUIRED UTILITIES" sourceLabel="TEXTBOOK pp.124-126" syllabusLabel="SYLLABUS 5.1" title="Name the tool from the symptom."><section className="ss-utility-ring"><article><b>Disk formatter</b><p>prepare and organise a disk</p></article><article><b>Virus checker</b><p>detect and respond to malware</p></article><article><b>Defragmenter</b><p>rejoin scattered file blocks</p></article><article><b>Disk analysis / repair</b><p>find errors and bad sectors</p></article><article><b>File compression</b><p>reduce stored or transmitted size</p></article><article><b>Backup software</b><p>create copies for restoration</p></article></section></Slide> },
    { time: "6 min", focus: "Explain formatting as creation of a usable disk structure, not merely deletion.", prompt: "Why is 'deletes everything' an incomplete two-mark answer?", source: "Coursebook pp.124-125 hard disk formatter and checker.", content: <Slide number="04" eyebrow="DISK FORMATTER" sourceLabel="TEXTBOOK pp.124-125" syllabusLabel="SYLLABUS 5.1" title="Prepare storage before files can be organised."><section className="ss-card-grid three"><article><span>01 · CLEAR</span><b>Remove existing data</b><p>when a previously used disk is reformatted</p></article><article><span>02 · STRUCTURE</span><b>Create the file system</b><p>set up records that map files to physical storage</p></article><article><span>03 · DIVIDE</span><b>Create partitions</b><p>split one physical disk into logical drives if required</p></article></section><p className="ss-warning"><strong>Formatting is destructive.</strong> A file system and partitions are the important technical purpose.</p></Slide> },
    { time: "6 min", focus: "Model scanning, detection information and response as separate virus-checker steps.", prompt: "Why can a newly released virus initially escape an old checker?", source: "Coursebook p.126 virus checker; syllabus 5.1.", content: <Slide number="05" eyebrow="VIRUS CHECKER" sourceLabel="TEXTBOOK p.126" syllabusLabel="SYLLABUS 5.1" title="Scan, recognise, isolate—then update."><section className="ss-scan-line"><code>file_01 ........ <strong>CLEAN</strong></code><code>attachment.exe . <em>SUSPICIOUS PATTERN</em></code><code>macro.docm ..... <strong>QUARANTINED</strong></code><code>definitions .... <strong>UPDATED TODAY</strong></code></section><p className="ss-note">The utility scans files, compares content with known signatures/rules, reports a match and may quarantine or delete it. Updates add knowledge of new malware.</p></Slide> },
    { time: "6 min", focus: "Use a visual before/after model to explain fragmentation and reorganisation.", prompt: "Which physical delay is reduced when magnetic-disk blocks become contiguous?", source: "Coursebook p.125 Figure 8.01 and defragmenter explanation.", content: <Slide number="06" eyebrow="DISK DEFRAGMENTER" sourceLabel="TEXTBOOK p.125" syllabusLabel="SYLLABUS 5.1" title="Put each magnetic-disk file back into contiguous blocks."><section className="ss-disk-before-after"><div className="ss-disk-row"><b>BEFORE</b><span className="a">A</span><span className="c">C</span><span className="a">A</span><span /><span className="b">B</span><span className="c">C</span><span /><span className="a">A</span><span className="b">B</span><span /></div><div className="ss-disk-row"><b>AFTER</b><span className="a">A</span><span className="a">A</span><span className="a">A</span><span className="b">B</span><span className="b">B</span><span className="c">C</span><span className="c">C</span><span /><span /><span /></div></section><p className="ss-note">Fewer head movements can reduce access time on a magnetic disk. Defragmentation needs free working space and is not a repair for damaged sectors.</p></Slide> },
    { time: "6 min", focus: "Distinguish logical/file-system checks from physical bad-sector handling.", prompt: "What can a repair utility do if data in a bad sector cannot be recovered?", source: "Coursebook pp.124-125 disk contents analysis and repair.", content: <Slide number="07" eyebrow="DISK ANALYSIS + REPAIR" sourceLabel="TEXTBOOK pp.124-125" syllabusLabel="SYLLABUS 5.1" title="Find damage; stop the file system using it again."><section className="ss-flow"><article><b>ANALYSE</b><p>check file-system records and sectors for errors</p></article><i>→</i><article><b>REPAIR</b><p>recover usable data and correct logical damage</p></article><i>→</i><article><b>ISOLATE</b><p>mark bad sectors so they are no longer allocated</p></article></section><p className="ss-warning">A utility may have to delete an unrecoverable damaged file. Recovery is not guaranteed.</p></Slide> },
    { time: "6 min", focus: "Connect compression to both storage and transmission while preserving the lossless requirement for exact files.", prompt: "Why is compressing an email attachment useful even if the disk has plenty of space?", source: "Coursebook p.126 file compression; prior syllabus 1.3 knowledge.", content: <Slide number="08" eyebrow="FILE COMPRESSION" sourceLabel="TEXTBOOK p.126" syllabusLabel="SYLLABUS 5.1" title="Store or transmit fewer bits."><section className="ss-split"><article><span className="ss-kicker">COMPRESS</span><h3>Original → smaller encoded file</h3><p>Uses less storage and takes less time/bandwidth to transmit.</p></article><article><span className="ss-kicker">DECOMPRESS</span><h3>Encoded file → usable original</h3><p>For programs, documents and archives, lossless compression preserves every bit.</p></article></section><p className="ss-note">“Zip” describes a common archive action; the exam answer should explain the reduction and later restoration.</p></Slide> },
    { time: "6 min", focus: "Treat backup as a planned recovery system rather than a casual copy.", prompt: "Which choices must be made before a failure occurs?", source: "Coursebook p.126 backup software; syllabus 5.1.", content: <Slide number="09" eyebrow="BACKUP SOFTWARE" sourceLabel="TEXTBOOK p.126" syllabusLabel="SYLLABUS 5.1" title="A backup matters only if it can be restored."><section className="ss-backup-cycle"><span>SELECT<br />DATA</span><i>→</i><span>SCHEDULE<br />COPIES</span><i>→</i><span>STORE<br />SEPARATELY</span><i>→</i><span>RESTORE<br />AFTER LOSS</span></section><p className="ss-note">Software can schedule backups and copy only files changed since an earlier backup. A backup is a separate recovery copy—not the live file itself.</p></Slide> },
    { time: "5 min", focus: "Build decision-making speed by matching symptoms to exact syllabus labels.", prompt: "Students answer before the utility names are revealed.", source: "Syllabus 5.1 application practice; Coursebook pp.124-126.", content: <Slide number="10" eyebrow="UTILITY TRIAGE" sourceLabel="TEXTBOOK pp.124-126" syllabusLabel="SYLLABUS 5.1" title="Diagnose first. Then name the tool."><section className="ss-card-grid four"><article><span>SYMPTOM 1</span><b>Missing file after failure</b><p>restore from backup</p></article><article><span>SYMPTOM 2</span><b>Known malicious signature</b><p>virus checker</p></article><article><span>SYMPTOM 3</span><b>Scattered magnetic blocks</b><p>defragmenter</p></article><article><span>SYMPTOM 4</span><b>Bad sector warning</b><p>disk analysis/repair</p></article></section></Slide> },
    { time: "6 min", focus: "Introduce libraries as collections of callable, reusable routines.", prompt: "What development work is avoided when a tested sort routine is reused?", source: "Coursebook 8.04 printed pp.126-127; syllabus 5.1 program libraries.", content: <Slide number="11" eyebrow="PROGRAM LIBRARIES + DLLs" sourceLabel="TEXTBOOK pp.126-127" syllabusLabel="SYLLABUS 5.1" title="Reuse a routine; do not rewrite the solution."><section className="ss-library-link"><article><b>YOUR SOURCE CODE</b><p>calls Sort(records)</p></article><i>→</i><article><b>LIBRARY ROUTINE</b><p>pre-written, documented and tested procedure</p></article><i>→</i><article><b>LINKED PROGRAM</b><p>uses the routine when it runs</p></article></section><p className="ss-note"><strong>DLL:</strong> a separately stored dynamic-link library can be shared by several processes, reducing duplicated executable code and memory use.</p></Slide> },
    { time: "9 min", focus: "Practise the 2025 utility recovery item and require exact utility names.", prompt: "Students answer in 60 seconds, then explain why each tool is relevant.", source: "Adapted from 9618/12 O/N 2025 Q8(b)(ii), checked against the published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 2 MARKS" sourceLabel="9618/12 O/N 2025 · Q8(b)(ii)" syllabusLabel="SYLLABUS 5.1 — EXAM PRACTICE" title="Touchscreen image files are corrupted. Name two recovery utilities." className="slide--ss-paper"><section className="ss-paper-grid"><article><span>CLUE 1</span><p>One utility may analyse and repair disk contents.</p></article><article><span>CLUE 2</span><p>Another may restore an earlier clean copy.</p></article></section><Reveal id="paper-utilities" visible={revealed.has("paper-utilities")} onToggle={toggleReveal}><p><strong>Disk repair/disk contents analysis software</strong> and <strong>backup software</strong>. The published mark scheme awards one mark for each.</p></Reveal><small>Adapted from 9618/12 O/N 2025 Q8(b)(ii).</small></Slide> },
    { time: "9 min", focus: "Use recent questions to balance benefits with library dependency risks.", prompt: "Pairs write one developed benefit and one developed drawback before revealing.", source: "Adapted from 9618/13 O/N 2025 Q8(b) and 9618/11 O/N 2025 Q5(b), checked against mark schemes.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/11 + /13 O/N 2025" syllabusLabel="SYLLABUS 5.1 — EXAM PRACTICE" title="Describe one benefit and one drawback of library routines." className="slide--ss-paper"><section className="ss-paper-grid"><article><span>BENEFIT · 2</span><p>Name it, then connect it to saved development/testing time or added capability.</p></article><article><span>DRAWBACK · 2</span><p>Name it, then connect it to compatibility, quality or later-change risk.</p></article></section><Reveal id="paper-library" visible={revealed.has("paper-library")} onToggle={toggleReveal}><p>Example: pre-written, tested code reduces coding and testing time. However, a routine may be incompatible or insufficiently tested, causing errors and requiring editing/retesting. Other published alternatives are valid.</p></Reveal><small>Adapted from 9618/11 O/N 2025 Q5(b); benefit points also align with 9618/13 O/N 2025 Q8(b).</small></Slide> },
    { time: "8 min", focus: "Synthesize utility choice and dynamic linking in one applied system-design prompt.", prompt: "Teams give one sentence per decision; every sentence must include because.", source: "Syllabus-style consolidation from 5.1 and Coursebook pp.124-127.", content: <Slide number="14" eyebrow="SYSTEM-SOFTWARE DESIGN SPRINT" sourceLabel="SYLLABUS-STYLE ORIGINAL" syllabusLabel="SYLLABUS 5.1" title="A school deploys one media editor to 200 computers."><section className="ss-paper-grid three"><article><span>RECOVERY</span><p>Which utility protects student projects after storage failure?</p></article><article><span>TRANSFER</span><p>Which utility reduces the size of exported project archives?</p></article><article><span>SHARED CODE</span><p>Why might common media routines be supplied in a DLL?</p></article></section><Reveal id="design" visible={revealed.has("design")} onToggle={toggleReveal}><p><strong>Backup software</strong> creates restorable copies; <strong>lossless compression</strong> reduces archive size while preserving content; a <strong>DLL</strong> lets programs share one loaded routine and allows a common update, reducing duplicated storage/memory.</p></Reveal></Slide> },
    { time: "3 min", focus: "Close with the complete specification list and the library/DLL distinction.", prompt: "Students name all six utilities without looking, then explain DLL in one sentence.", source: "Syllabus 5.1 completion check; Coursebook pp.124-127.", content: <Slide number="15" eyebrow="LESSON 26 · EXIT" sourceLabel="TEXTBOOK pp.124-127" syllabusLabel="SYLLABUS 5.1" title="Choose. Maintain. Reuse." className="slide--ss-exit"><section className="ss-exit-grid"><article><b>NAME SIX UTILITIES</b><p>Formatter, virus checker, defragmenter, disk repair, compression and backup.</p></article><article><b>EXPLAIN THE ACTION</b><p>Link the system symptom to what the chosen utility changes.</p></article><article><b>EXPLAIN A DLL</b><p>A separately stored shared library loaded or linked when a program needs it.</p></article></section><div className="ss-homework-callout"><b>HOMEWORK 26</b><span>30 marks · verified 2025 utility and library practice · inline answers</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="26" slides={slides} homework={<HomeworkSheet lessonNumber="26" title="Utility Software, Libraries and DLLs" marks={30} minutes={45} syllabusLabel="SYLLABUS 5.1" sourceLabel="TEXTBOOK CH.8 · pp.124-127 + PAPER 1" instructions="Name utilities precisely and develop library benefits or drawbacks with a consequence. Past-paper prompts are concise adaptations checked against the published 2025 mark schemes." sections={homeworkSections} challenge={{ id: "l26-challenge", prompt: <p><Mark>CHALLENGE</Mark> Explain why replacing many copied library routines with one DLL can reduce storage and memory use, yet make the programs less independent.</p>, answer: <p>Copied routines are included in every executable and may be loaded separately for every process. With a DLL, executables hold a small link and processes can use one shared loaded copy. This saves storage and memory, but every dependent program relies on that separate DLL remaining present, compatible and correct.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 5.1, Coursebook Chapter 8 printed pp.124-127, and published 2025 Paper 1 questions and mark schemes." sourceDetail="Core: describe disk formatter, virus checker, defragmentation, disk analysis/repair, compression and backup utilities; explain program libraries including DLLs. Authentic anchors: 9618/12 O/N 2025 Q8(b)(ii), 9618/11 O/N 2025 Q5(b), and 9618/13 O/N 2025 Q8(b). Detailed backup rotation schemes and platform-specific DLL implementation are outside this lesson." />;
}
