"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip } from "../../_components/a2-theory-lesson";
import { KeyJourney } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Encryption foundations", subtitle: "Use plaintext, ciphertext and key correctly", marks: 10,
    questions: [
      { id: "a2-21-1", marks: 3, lines: 5, prompt: <><b>Define plaintext, ciphertext and encryption.</b></>, answer: <p>Plaintext is the original/readable data <em>[1]</em>. Ciphertext is the unreadable/encrypted form <em>[1]</em>. Encryption applies an algorithm and key to transform plaintext into ciphertext <em>[1]</em>.</p> },
      { id: "a2-21-2", marks: 3, lines: 6, prompt: <><b>Explain symmetric-key encryption.</b></>, answer: <p>The same shared secret key is used to encrypt and decrypt <em>[1]</em>. It is normally fast/suitable for large amounts of data <em>[1]</em>, but the key must be distributed securely and each communicating pair needs a shared secret <em>[1]</em>.</p> },
      { id: "a2-21-3", marks: 4, lines: 7, prompt: <><b>Compare symmetric and asymmetric cryptography.</b></>, answer: <p>Symmetric uses one shared secret key; asymmetric uses a mathematically related public/private pair <em>[1+1]</em>. Symmetric is generally faster for bulk data <em>[1]</em>; asymmetric simplifies public key distribution but uses more computation/is generally slower <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Confidential delivery", subtitle: "Recipient public key in; recipient private key out", marks: 10,
    questions: [
      { id: "a2-21-4", marks: 3, lines: 6, prompt: <><b>Explain how a member of the public sends a private message to an organisation</b> using asymmetric cryptography.</>, answer: <p>The organisation generates a key pair and publishes its public key <em>[1]</em>. The sender encrypts using the organisation&apos;s public key <em>[1]</em>. Only the organisation&apos;s matching private key can decrypt the ciphertext <em>[1]</em>.</p> },
      { id: "a2-21-5", marks: 3, lines: 5, prompt: <><b>Explain why the public key can be published</b> without revealing the private key.</>, answer: <p>The keys are mathematically related but designed so deriving the private key from the public key is computationally infeasible <em>[1]</em>. The public key is intended for distribution <em>[1]</em>; the private key remains secret with its owner <em>[1]</em>.</p> },
      { id: "a2-21-6", marks: 4, lines: 7, prompt: <><b>Explain why encrypting confidential data with the sender&apos;s private key would not keep it secret.</b></>, answer: <p>The sender&apos;s public key is available to everyone <em>[1]</em>; data transformed using the matching private key could therefore be checked/recovered by anyone with the public key <em>[1]</em>. This direction supports origin verification/signing <em>[1]</em>, not confidentiality; confidentiality needs the recipient&apos;s public key <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Verified public messages", subtitle: "Sender private key signs; sender public key verifies", marks: 10,
    questions: [
      { id: "a2-21-7", marks: 3, lines: 6, prompt: <><b>Explain how asymmetric keys support a verified message to the public.</b></>, answer: <p>The sender creates a digital signature using the sender&apos;s private key <em>[1]</em>. A recipient uses the sender&apos;s public key to verify it <em>[1]</em>, supporting authenticity/integrity and showing control of the private key <em>[1]</em>.</p> },
      { id: "a2-21-8", marks: 3, lines: 6, prompt: <><b>Explain why many secure systems use both asymmetric and symmetric cryptography.</b></>, answer: <p>Asymmetric cryptography authenticates endpoints or protects agreement of a session secret <em>[1]</em>. A symmetric session key is then used for bulk data <em>[1]</em> because symmetric encryption is normally faster/less computationally expensive <em>[1]</em>.</p> },
      { id: "a2-21-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>Fred must send Sheila a confidential document. Explain the asymmetric-key steps.</b></p><p>Adapted from 9618/32 M/J 2024 Q4. [4 adapted marks]</p></>, answer: <p>Sheila generates a public/private key pair <em>[1]</em> and makes her public key available to Fred <em>[1]</em>. Fred encrypts the document with Sheila&apos;s public key <em>[1]</em>. Sheila decrypts it using her private key, which only she should possess <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson21Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame cryptography through two separate goals.", prompt: "Do confidentiality and verified origin require the same key direction?", source: "2027–2029 syllabus 17.1; coursebook Chapter 21 printed pp.387–392.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch21" syllabusLabel="SYLLABUS 17.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 21 · 90 MINUTES</span><h1>Keep it private.<br /><em>Prove who sent it.</em></h1><p>plaintext · ciphertext · symmetric · public/private key directions</p></div><div className="a2-at-hero" role="img" aria-label="Cryptographic keys provide privacy and verification"><strong>CRYPTOGRAPHY</strong><span>PLAINTEXT</span><span>CIPHERTEXT</span><span>PRIVATE</span><span>VERIFIED</span></div></section></Slide> },
    { time: "5 min", focus: "Map every encryption requirement in syllabus 17.1.", prompt: "Which scenario starts with a public recipient key, and which ends with public verification?", source: "Official 2027–2029 syllabus p.36.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.36" syllabusLabel="17.1 · REQUIRED" title="Know the vocabulary, compare methods and choose the key direction." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "TRANSFORM", title: "Plain ↔ cipher", body: "Algorithm plus key." }, { eyebrow: "SHARED", title: "Symmetric", body: "One secret key." }, { eyebrow: "PAIR", title: "Asymmetric", body: "Public and private keys." }, { eyebrow: "PURPOSE", title: "Private or verified", body: "Different owners and directions." }]} /></Slide> },
    { time: "5 min", focus: "Use the core encryption vocabulary in one reversible model.", prompt: "What must change for the same plaintext to be protected differently?", source: "Coursebook §21.01 pp.387–388.", content: <Slide number="03" eyebrow="CORE MODEL" sourceLabel="TEXTBOOK pp.387–388" syllabusLabel="17.1 · HOW ENCRYPTION WORKS" title="A key controls the transformation between readable and protected data." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "INPUT", title: "Plaintext", body: "Readable original data." }, { eyebrow: "ENCRYPT", title: "Algorithm + key" }, { eyebrow: "TRANSMIT", title: "Ciphertext", body: "Unintelligible without the correct key." }, { eyebrow: "DECRYPT", title: "Recover plaintext" }]} /></Slide> },
    { time: "6 min", focus: "Separate confidentiality from integrity and authenticity.", prompt: "If ciphertext changes in transit, which security property is threatened?", source: "Coursebook Chapter 21 security purposes; verified Paper 3 mark schemes.", content: <Slide number="04" eyebrow="SECURITY GOALS" sourceLabel="TEXTBOOK Ch21" syllabusLabel="17.1 · PURPOSE" title="Encryption protects confidentiality; signatures add origin and change checks." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "CONFIDENTIALITY", title: "Who can read?", body: "Only authorised holders of the decryption key." }, { eyebrow: "INTEGRITY", title: "Was it changed?", body: "A verified digest detects modification." }, { eyebrow: "AUTHENTICITY", title: "Who sent it?", body: "Signature links message to private-key control." }, { eyebrow: "NON-REPUDIATION", title: "Can origin be denied?", body: "A valid signature supplies evidence of origin." }]} /></Slide> },
    { time: "6 min", focus: "Explain symmetric encryption and its key-distribution problem.", prompt: "How can two parties share the key before they have a secure channel?", source: "Coursebook §21.01 pp.387–389.", content: <Slide number="05" eyebrow="SYMMETRIC CRYPTOGRAPHY" sourceLabel="TEXTBOOK pp.387–389" syllabusLabel="17.1 · SYMMETRIC KEY" title="One shared secret performs both encryption and decryption." className="a2-slide a2-at-slide"><KeyJourney purpose="CONFIDENTIALITY WITH ONE SHARED SECRET" steps={[{ actor: "ALICE", action: "Encrypts plaintext", keyLabel: "KEY K" }, { actor: "NETWORK", action: "Carries ciphertext" }, { actor: "BOB", action: "Decrypts ciphertext", keyLabel: "SAME KEY K" }]} /></Slide> },
    { time: "6 min", focus: "Evaluate the benefits and limitations of a shared key.", prompt: "Why is symmetric cryptography preferred for bulk data?", source: "Coursebook pp.387–389.", content: <Slide number="06" eyebrow="SYMMETRIC TRADE-OFF" sourceLabel="TEXTBOOK pp.387–389" syllabusLabel="17.1 · SYMMETRIC KEY" title="Fast data protection creates a difficult secret-sharing problem." className="a2-slide a2-at-slide"><CompareTable headers={["Benefits", "Drawbacks"]} rows={[["fast; low computational cost", "key must reach both parties securely"], ["efficient for large data streams", "compromise exposes both encryption and decryption"], ["mature algorithms and hardware support", "many communicating pairs require many shared secrets"]]} /></Slide> },
    { time: "6 min", focus: "Define a public/private key pair without implying the private key is transmitted.", prompt: "Which key may be copied widely?", source: "Coursebook asymmetric methods pp.391–392.", content: <Slide number="07" eyebrow="ASYMMETRIC CRYPTOGRAPHY" sourceLabel="TEXTBOOK pp.391–392" syllabusLabel="17.1 · PUBLIC / PRIVATE" title="The public key is distributed; its matching private key stays with the owner." className="a2-slide a2-at-slide"><CompareTable headers={["Public key", "Private key"]} rows={[["published/shared", "kept secret by owner"], ["used by others to encrypt for owner", "decrypts confidential data sent to owner"], ["verifies owner's digital signature", "creates owner's digital signature"], ["cannot feasibly reveal private key", "loss/compromise breaks trust"]]} /></Slide> },
    { time: "6 min", focus: "Trace private delivery from the public to one recipient.", prompt: "Whose public key is used—the sender's or the recipient's?", source: "Syllabus p.36; 9618/32 M/J 2024 Q4.", content: <Slide number="08" eyebrow="SEND A PRIVATE MESSAGE" sourceLabel="9618/32 M/J 2024 · Q4" syllabusLabel="17.1 · PUBLIC → INDIVIDUAL" title="Encrypt for the recipient using the recipient's public key." className="a2-slide a2-at-slide"><KeyJourney purpose="CONFIDENTIAL MESSAGE TO SHEILA" steps={[{ actor: "SHEILA", action: "Creates pair; publishes public key", keyLabel: "SHEILA PUBLIC" }, { actor: "FRED", action: "Encrypts the document", keyLabel: "SHEILA PUBLIC" }, { actor: "SHEILA", action: "Decrypts the ciphertext", keyLabel: "SHEILA PRIVATE" }]} /></Slide> },
    { time: "6 min", focus: "Trace a verified public message in the reverse ownership direction.", prompt: "Why can everyone verify but only the sender create the signature?", source: "Syllabus p.36; coursebook digital signatures pp.389–391.", content: <Slide number="09" eyebrow="SEND A VERIFIED MESSAGE" sourceLabel="TEXTBOOK pp.389–391" syllabusLabel="17.1 · VERIFIED → PUBLIC" title="The sender's private key signs; the sender's public key verifies." className="a2-slide a2-at-slide"><KeyJourney purpose="VERIFIED ANNOUNCEMENT FROM SHEILA" steps={[{ actor: "SHEILA", action: "Creates signature for message", keyLabel: "SHEILA PRIVATE" }, { actor: "PUBLIC", action: "Receives message + signature" }, { actor: "READER", action: "Verifies sender and integrity", keyLabel: "SHEILA PUBLIC" }]} /></Slide> },
    { time: "6 min", focus: "Contrast the two asymmetric scenarios in one table.", prompt: "Who is the key owner in each row?", source: "Official syllabus 17.1 key-use scenarios.", content: <Slide number="10" eyebrow="KEY-DIRECTION CHECK" sourceLabel="SYLLABUS p.36" syllabusLabel="17.1 · PRIVATE VS VERIFIED" title="Key ownership—not the word public alone—determines the answer." className="a2-slide a2-at-slide"><CompareTable headers={["Goal", "First operation", "Matching operation", "Result"]} rows={[["confidential to Bob", "encrypt with Bob public key", "Bob decrypts with Bob private key", "only Bob reads"], ["verified from Alice", "Alice signs with Alice private key", "public verifies with Alice public key", "origin/integrity checked"]]} /></Slide> },
    { time: "7 min", focus: "Explain what asymmetric encryption does and does not guarantee.", prompt: "Does encrypting with Bob's public key prove Alice was the sender?", source: "Coursebook pp.389–392; syllabus key directions.", content: <Slide number="11" eyebrow="PURPOSE BEFORE KEY" sourceLabel="TEXTBOOK pp.389–392" syllabusLabel="17.1 · APPLY" title="Confidentiality and verified origin are separate claims." className="a2-slide a2-at-slide"><CompareTable headers={["Action", "What it supports", "What it does not prove alone"]} rows={[["encrypt with recipient public key", "only recipient private key can decrypt", "which member of the public sent it"], ["verify sender signature", "private-key control and message integrity", "that the message was secret in transit"]]} /></Slide> },
    { time: "7 min", focus: "Introduce the efficient hybrid used by real secure channels.", prompt: "Which method handles the long data stream?", source: "Coursebook pp.392–393; supports later SSL/TLS lesson.", content: <Slide number="12" eyebrow="HYBRID PATTERN" sourceLabel="TEXTBOOK Ch21" syllabusLabel="17.1 · ENCRYPT / DECRYPT" title="Asymmetric trust can establish a fast symmetric session." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "AUTHENTICATE", title: "Check public-key identity" }, { eyebrow: "ESTABLISH", title: "Agree session secret" }, { eyebrow: "ENCRYPT", title: "Use symmetric session key" }, { eyebrow: "RENEW", title: "Discard after session" }]} /></Slide> },
    { time: "7 min", focus: "Reject unsafe shorthand about key use.", prompt: "Students repair each sentence before seeing the answer.", source: "Syllabus 17.1 and verified 2021–2024 mark schemes.", content: <Slide number="13" eyebrow="EXAM LANGUAGE CLINIC" sourceLabel="SYLLABUS 17.1" syllabusLabel="17.1 · PRECISION" title="Always name the owner, operation, key and security purpose." className="a2-slide a2-at-slide"><CompareTable headers={["Unsafe", "Exam-safe"]} rows={[["Use the public key.", "Encrypt with the recipient's public key for confidentiality."], ["The private key is sent back.", "The recipient's private key never leaves the owner."], ["Private-key encryption is secret.", "A sender private key creates a signature for public verification."], ["Encryption proves the sender.", "Confidential encryption alone does not authenticate a public sender."]]} /></Slide> },
    { time: "8 min", focus: "Apply the recipient-key pattern to a published-paper scenario.", prompt: "Write one mark point per step and repeat the key owner each time.", source: "Adapted from Cambridge 9618/32 M/J 2024 Q4.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/32 M/J 2024 · Q4" syllabusLabel="17.1 · 4 MARKS" title="For confidential delivery, the recipient owns both keys." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/32 M/J 2024 · Q4 · ADAPTED" marks={4} prompt={<p>Fred must send Sheila a confidential document over an untrusted network. Explain the asymmetric-key sequence. [4]</p>} answer={<ul><li>Sheila generates a matching public/private key pair. [1]</li><li>She publishes/sends her public key to Fred. [1]</li><li>Fred encrypts the document with Sheila&apos;s public key. [1]</li><li>Only Sheila decrypts with Sheila&apos;s private key. [1]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve both cryptographic methods and both key directions.", prompt: "Students complete two arrows: confidential to X; verified from Y.", source: "Syllabus 17.1 synthesis; coursebook Chapter 21 pp.387–392.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch21 · SYLLABUS p.36" syllabusLabel="17.1 · CHECKPOINT" title="Recipient keys protect privacy; sender keys establish verification." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>PLAIN</span><p>Readable input.</p></article><article><span>CIPHER</span><p>Encrypted output.</p></article><article><span>PRIVATE TO X</span><p>X public → X private.</p></article><article><span>VERIFIED FROM Y</span><p>Y private → Y public.</p></article></section><div className="homework-callout"><b>HOMEWORK 21</b><span>30 marks · symmetric/asymmetric key use</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="21" title="Symmetric and asymmetric cryptography" syllabusLabel="SYLLABUS 17.1" sourceLabel="TEXTBOOK Ch21 · pp.387–392" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 17.1 p.36 · endorsed coursebook Chapter 21 printed pp.387–392 · verified 2022–2024 Paper 3 questions and mark schemes" sourceDetail="The lesson makes key ownership explicit in both required scenarios: recipient public-to-private for confidential delivery, and sender private-to-public for a verified message. Symmetric and asymmetric methods are compared before a supporting hybrid pattern." />;
}
