"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Diagnose the storage model", subtitle: "Limitations, structures and precise terminology", marks: 10,
    questions: [
      { id: "l36-1", marks: 4, lines: 4, prompt: <><b>Explain two limitations of storing customer data in separate department files.</b></>, answer: <p>Any two developed pairs: duplicated data creates redundancy and wastes storage; copies can disagree after only one is updated, causing inconsistency; file structures are tied to programs, so a format change requires program changes; sharing and complex retrieval are difficult; separate files make central access control and validation harder. <em>[2 × 2]</em></p> },
      { id: "l36-2", marks: 4, lines: 4, prompt: <><b>Define entity, attribute, tuple and table in a relational database.</b></>, answer: <p>An <strong>entity</strong> is a distinguishable real-world object/type about which data is stored; an <strong>attribute</strong> is one property of that entity; a <strong>tuple</strong> is one row representing one entity instance; a <strong>table</strong> is the relation containing rows and columns for an entity type. <em>[4]</em></p> },
      { id: "l36-3", marks: 2, lines: 2, prompt: <><b>State two properties of a suitable primary key.</b></>, answer: <p>It must uniquely identify each record and must not be null. A strong answer may also state stable, minimal and never duplicated. Award any two valid properties. <em>[2]</em></p> },
    ],
  },
  {
    code: "B", title: "Build reliable relations", subtitle: "Keys, integrity and retrieval choices", marks: 10,
    questions: [
      { id: "l36-4", marks: 4, lines: 4, prompt: <><b>A school stores pupil details and tutor details in one repeated spreadsheet. Explain two relational-database improvements.</b></>, answer: <p>Put tutor data once in a TUTOR table and reference it from PUPIL using TutorID, reducing duplicated tutor details. A single update then keeps all pupils linked to the current tutor details. The DBMS can also enforce types/validation and give different users views/access rights. Award two developed improvements. <em>[4]</em></p> },
      { id: "l36-5", marks: 3, lines: 3, prompt: <><b>Distinguish candidate, primary and secondary keys.</b></>, answer: <p>A candidate key is any minimal attribute/set that could uniquely identify a row. One candidate key is selected as the primary key. A secondary key is another field used for searching/retrieval and need not be unique; some mark schemes use it for an unselected candidate key, so the context must be read carefully. <em>[3]</em></p> },
      { id: "l36-6", marks: 3, lines: 3, prompt: <><b>Explain how a foreign key and referential integrity work together.</b></>, answer: <p>A foreign key stores a value that references a key in another table. Referential integrity requires every non-null foreign-key value to match an existing referenced key, preventing invalid links/orphan records. A controlled update/delete may be rejected or cascaded. <em>[3]</em></p> },
    ],
  },
  {
    code: "C", title: "Published database foundations", subtitle: "Cambridge Paper 1 concepts and terminology", marks: 10,
    questions: [
      { id: "l36-7", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain how a relational database addresses two limitations of a file-based approach.</b><p>Adapted from 9618/13 M/J 2023 Q4(a). [4]</p></>, answer: <p>Give two paired points. Examples: linked tables store an item once, reducing redundancy; changing one stored value makes the current value available everywhere, reducing inconsistency; separation of data from programs reduces program-data dependency; SQL enables more flexible queries; views/access rights restrict what users see. <em>[2 × 2]</em></p> },
      { id: "l36-8", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Define entity, tuple, secondary key and foreign key.</b><p>Adapted from 9618/13 M/J 2023 Q4(b). [4]</p></>, answer: <p><strong>Entity:</strong> object/type about which data is stored. <strong>Tuple:</strong> one row/record for an instance. <strong>Secondary key:</strong> non-primary field/key used to locate records. <strong>Foreign key:</strong> field that references a key in another table and creates the link. <em>[4]</em></p> },
      { id: "l36-9", marks: 2, lines: 2, prompt: <><b>For STUDENT(StudentID, SchoolEmail, FamilyName), identify two candidate keys and select the safer primary key.</b></>, answer: <p>StudentID and SchoolEmail can both be candidate keys if each is unique. StudentID is normally the safer primary key because it is compact, controlled by the system and less likely to change. <em>[2]</em></p> },
    ],
  },
];

export default function Lesson36Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Expose the cost of duplicate facts before naming database terminology.", prompt: "Ask: if a tutor changes phone number, how many places must be edited?", source: "Coursebook 11.01 printed pp.158-159; syllabus 8.1.", content: <Slide number="01" eyebrow="CHAPTER 8 · DATABASE FOUNDATIONS" sourceLabel="TEXTBOOK CH.11 · pp.158-162" syllabusLabel="SYLLABUS 8.1" className="da-title"><section className="da-title-grid"><div className="da-title-copy"><span>LESSON 36 · 90 MINUTES</span><h1>Store a fact <em>once.</em></h1><p>Diagnose file-based problems, organise relational data and choose keys that make every row identifiable and every link valid.</p></div><div className="da-title-map"><div><b>01</b><span>FIND REDUNDANCY</span></div><div><b>02</b><span>SEPARATE ENTITIES</span></div><div><b>03</b><span>CHOOSE KEYS</span></div><div><b>04</b><span>PROTECT LINKS</span></div></div></section></Slide> },
    { time: "5 min", focus: "Make the exact textbook and syllabus overlap visible.", prompt: "Students identify which green syllabus terms they already know from spreadsheets.", source: "Syllabus 8.1 pp.25-26; Coursebook 11.01-11.02 printed pp.158-162.", content: <Slide number="02" eyebrow="TEXTBOOK × SYLLABUS" sourceLabel="TEXTBOOK §§11.01-11.02 · pp.158-162" syllabusLabel="SYLLABUS 8.1" title="Today: file-based limitations, relational remedies, terminology and keys."><section className="da-grid four"><article className="da-card"><span>FILE-BASED</span><p>redundancy, inconsistency, dependency, difficult sharing/retrieval</p></article><article className="da-card"><span>RELATIONAL</span><p>tables connected through defined keys and centrally managed rules</p></article><article className="da-card"><span>TERMS</span><p>entity, attribute, field, tuple, record, table</p></article><article className="da-card"><span>IDENTITY + LINKS</span><p>candidate, primary, secondary and foreign keys; referential integrity; index</p></article></section><p className="da-note">Next lesson adds cardinality, E-R diagrams and normalisation.</p></Slide> },
    { time: "6 min", focus: "Build causal explanations for file-based limitations.", prompt: "For each symptom, require a consequence rather than a one-word list.", source: "Coursebook 11.01 printed pp.158-159; syllabus 8.1 file-based limitations.", content: <Slide number="03" eyebrow="WHY SEPARATE FILES FAIL" sourceLabel="TEXTBOOK §11.01 · pp.158-159" syllabusLabel="SYLLABUS 8.1" title="The same fact can become duplicated, inconsistent and hard to retrieve."><section className="da-grid four"><article className="da-card"><span>REDUNDANCY</span><h3>Repeated storage</h3><p>The same customer or product fact appears in several files.</p></article><article className="da-card"><span>INCONSISTENCY</span><h3>Copies disagree</h3><p>One update leaves other copies obsolete or incorrect.</p></article><article className="da-card"><span>DEPENDENCY</span><h3>Programs know layout</h3><p>Changing a file structure can force every linked program to change.</p></article><article className="da-card"><span>ISOLATION</span><h3>Poor sharing/querying</h3><p>Combining departments, applying rules and controlling access is difficult.</p></article></section></Slide> },
    { time: "6 min", focus: "Map relational vocabulary from model to row and column.", prompt: "Use a single STUDENT row to distinguish entity type from entity instance.", source: "Coursebook 11.02 printed pp.160-161; syllabus 8.1 terminology.", content: <Slide number="04" eyebrow="RELATIONAL VOCABULARY" sourceLabel="TEXTBOOK §11.02 · pp.160-161" syllabusLabel="SYLLABUS 8.1" title="Entity type → table; entity instance → tuple (record).
"><table className="da-table"><thead><tr><th>MODEL IDEA</th><th>RELATIONAL FORM</th><th>EXAMPLE</th></tr></thead><tbody><tr><td><strong>Entity type</strong></td><td>Table / relation</td><td>STUDENT</td></tr><tr><td><strong>Entity instance</strong></td><td>Tuple / record / row</td><td>one particular student</td></tr><tr><td><strong>Attribute</strong></td><td>Field / column</td><td>FamilyName</td></tr><tr><td><strong>Domain</strong></td><td>permitted set/type of values</td><td>YearGroup is an integer in an allowed range</td></tr></tbody></table><p className="da-warning">Do not say an individual student “is a table”. The table represents the entity type; each row represents one instance.</p></Slide> },
    { time: "6 min", focus: "Show how a relational design reduces rather than magically eliminates redundancy.", prompt: "Circle the only place where TutorPhone is stored.", source: "Coursebook 11.01-11.02 printed pp.158-161; syllabus 8.1 relational features.", content: <Slide number="05" eyebrow="ONE FACT · ONE HOME" sourceLabel="TEXTBOOK §§11.01-11.02" syllabusLabel="SYLLABUS 8.1" title="Separate entity facts, then link them."><section className="da-erd"><article className="da-entity"><h3>TUTOR</h3><p className="key">TutorID · primary key</p><p>TutorName</p><p>TutorPhone</p></article><div className="da-relation"><b>1</b><i /><b>M</b></div><article className="da-entity"><h3>STUDENT</h3><p className="key">StudentID · primary key</p><p>FamilyName</p><p>TutorID · foreign key</p></article></section><p className="da-note">Relational design <strong>reduces/minimises</strong> avoidable redundancy. A foreign-key value is deliberately repeated so rows can be linked.</p></Slide> },
    { time: "6 min", focus: "Distinguish four key roles and select keys using explicit criteria.", prompt: "Which attributes could uniquely identify a student, and which should be chosen?", source: "Coursebook 11.02 printed pp.160-161; syllabus 8.1 keys.", content: <Slide number="06" eyebrow="KEYS GIVE IDENTITY" sourceLabel="TEXTBOOK §11.02 · pp.160-161" syllabusLabel="SYLLABUS 8.1" title="Candidate → choose one primary; use foreign keys to link."><section className="da-grid four"><article className="da-card"><span>CANDIDATE KEY</span><p>Any minimal attribute/set that can uniquely identify every row.</p></article><article className="da-card"><span>PRIMARY KEY</span><p>The selected candidate key: unique, non-null, stable and preferably compact.</p></article><article className="da-card"><span>SECONDARY KEY</span><p>A field/key used for retrieval besides the primary key; it may be non-unique.</p></article><article className="da-card"><span>FOREIGN KEY</span><p>An attribute whose value references a key in another table; duplicates are expected.</p></article></section></Slide> },
    { time: "6 min", focus: "Connect referential integrity and indexing without claiming either key must be unique.", prompt: "Predict what happens if TutorID 99 does not exist in TUTOR.", source: "Coursebook 11.02 and 11.06 printed pp.161,169; syllabus 8.1 referential integrity/indexing.", content: <Slide number="07" eyebrow="VALID LINKS · FASTER LOOKUP" sourceLabel="TEXTBOOK pp.161 + 169" syllabusLabel="SYLLABUS 8.1" title="Integrity protects meaning; an index accelerates access."><section className="da-grid two"><article className="da-card"><span>REFERENTIAL INTEGRITY</span><h3>No orphan reference</h3><p>Each non-null foreign key must match a referenced key. Invalid insert/update/delete is rejected or handled by a defined cascade.</p></article><article className="da-card"><span>INDEX</span><h3>Search structure</h3><p>Maps indexed values to row locations. It can be non-unique; it speeds reads but uses storage and adds work to inserts/updates.</p></article></section><p className="da-warning">A foreign key is not required to be unique. Many STUDENT rows may contain the same TutorID in a one-to-many relationship.</p></Slide> },
    { time: "7 min", focus: "Construct a complete two-table design from a repeated spreadsheet.", prompt: "Students nominate the fact that belongs in each table before keys are added.", source: "Coursebook 11.01-11.02 worked context; syllabus 8.1 relational design.", content: <Slide number="08" eyebrow="WORKED DESIGN · SCHOOL CLUBS" sourceLabel="TEXTBOOK METHOD · pp.158-162" syllabusLabel="SYLLABUS 8.1" title="From repeated club details to two linked relations."><table className="da-table"><thead><tr><th>BEFORE: MEMBER FILE</th><th>AFTER: MEMBER</th><th>AFTER: CLUB</th></tr></thead><tbody><tr><td>MemberID</td><td><strong>MemberID (PK)</strong></td><td><strong>ClubID (PK)</strong></td></tr><tr><td>MemberName</td><td>MemberName</td><td>ClubName</td></tr><tr><td>ClubID</td><td><strong>ClubID (FK)</strong></td><td>Room</td></tr><tr><td>ClubName</td><td>—</td><td>TeacherEmail</td></tr><tr><td>Room, TeacherEmail</td><td>—</td><td>—</td></tr></tbody></table><p className="da-note">Club details now have one authoritative row. ClubID links each member to the correct club.</p></Slide> },
    { time: "6 min", focus: "Correct common absolutes and key misconceptions.", prompt: "Students vote true/false, then repair every false claim.", source: "Coursebook 11.01-11.06, corrected against syllabus terminology.", content: <Slide number="09" eyebrow="MISCONCEPTION AUDIT" sourceLabel="TEXTBOOK CH.11 · CORRECTED" syllabusLabel="SYLLABUS 8.1" title="Repair the claim, not just the vocabulary."><section className="da-compare"><div><span>CLAIM</span><span>VERDICT</span><span>REPAIR</span></div><div><b>Relational databases eliminate all redundancy.</b><span>False</span><span>They minimise avoidable redundancy; foreign keys deliberately repeat link values.</span></div><div><b>An index must use a unique field.</b><span>False</span><span>An index may contain duplicate values; it maps values to row locations.</span></div><div><b>Every foreign key value must identify a different row.</b><span>False</span><span>Many rows may reference the same parent key.</span></div><div><b>A primary key identifies one row.</b><span>True</span><span>Its value is unique and non-null.</span></div></section></Slide> },
    { time: "6 min", focus: "Guide students from requirements to relations and key choices.", prompt: "Pairs design BOOK and LOAN; insist each attribute has exactly one home.", source: "Syllabus 8.1 produce/use relational terminology; Coursebook 11.02.", content: <Slide number="10" eyebrow="GUIDED CONSTRUCTION" sourceLabel="TEXTBOOK §11.02 · APPLICATION" syllabusLabel="SYLLABUS 8.1" title="Library brief: books can be loaned many times."><section className="da-flow"><span>LIST ENTITY<br />TYPES</span><i>→</i><span>ASSIGN EACH<br />ATTRIBUTE</span><i>→</i><span>CHOOSE<br />PRIMARY KEYS</span><i>→</i><span>PLACE THE<br />FOREIGN KEY</span></section><pre className="da-code">BOOK(<strong>BookID</strong>, Title, Author){"\n"}LOAN(<strong>LoanID</strong>, <span className="accent">BookID</span>, BorrowerID, LoanDate, Returned)</pre><p className="da-note">Check: can a LOAN refer to a BookID that is absent from BOOK? Referential integrity says no.</p></Slide> },
    { time: "7 min", focus: "Teach the two-part developed-point method for database comparison questions.", prompt: "Turn each one-word benefit into mechanism plus consequence.", source: "9618/13 M/J 2023 Q4(a) mark-scheme structure; syllabus 8.1.", content: <Slide number="11" eyebrow="EXAM METHOD · DEVELOP THE LINK" sourceLabel="9618/13 M/J 2023 · Q4(a)" syllabusLabel="SYLLABUS 8.1 — PAPER 1" title="Feature → mechanism → consequence."><section className="da-grid three"><article className="da-card"><span>1 · NAME</span><h3>Reduced redundancy</h3><p>Do not stop here.</p></article><article className="da-card"><span>2 · EXPLAIN HOW</span><h3>Store a fact once</h3><p>Linked tables reference the authoritative row.</p></article><article className="da-card"><span>3 · CONSEQUENCE</span><h3>Fewer inconsistent copies</h3><p>One update supplies the current value to every query.</p></article></section><p className="da-warning">“Better security” alone is not a developed answer. State views/access rights and what unauthorised users cannot see or change.</p></Slide> },
    { time: "8 min", focus: "Attempt an authentic file-based versus relational explanation.", prompt: "Students write two paired improvements in four minutes, then reveal.", source: "Adapted from 9618/13 M/J 2023 Q4(a), checked against published mark scheme.", content: <Slide number="12" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/13 M/J 2023 · Q4(a)" syllabusLabel="SYLLABUS 8.1 — PAPER 1" title="Explain two ways a relational database addresses file-based limitations." className="slide--da-paper"><section className="da-paper-grid"><article><span>PAIR 1</span><p>name the limitation/improvement, then explain the relational mechanism</p></article><article><span>PAIR 2</span><p>use a different issue: redundancy, dependency, inconsistency, querying or restricted views</p></article></section><ExamReveal><p>Example: linked tables store one authoritative copy of a fact, reducing redundancy and inconsistency. Data is managed separately from application programs, so a structural change does not necessarily require every program to be rewritten. Other accepted routes include flexible queries and restricted views.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [4].</small></Slide> },
    { time: "8 min", focus: "Practise exact relational vocabulary from a published question.", prompt: "One mark per precise definition; ban circular answers such as 'an entity in a database'.", source: "Adapted from 9618/13 M/J 2023 Q4(b), checked against published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/13 M/J 2023 · Q4(b)" syllabusLabel="SYLLABUS 8.1 — PAPER 1" title="Define four relational-database terms." className="slide--da-paper"><section className="da-paper-grid four"><article><span>ENTITY</span><p>What does the database store data about?</p></article><article><span>TUPLE</span><p>What does one row represent?</p></article><article><span>SECONDARY KEY</span><p>How else can records be located?</p></article><article><span>FOREIGN KEY</span><p>How is another relation referenced?</p></article></section><ExamReveal><p>Entity: a distinguishable object/type about which data is stored. Tuple: one row/record representing an instance. Secondary key: a non-primary field/key used to locate data. Foreign key: an attribute that references a key in another table and creates a relationship.</p></ExamReveal><small className="da-source-line">Concise adaptation; original allocation [4].</small></Slide> },
    { time: "5 min", focus: "Retrieve the complete lesson as a dependency chain.", prompt: "Cold-call one student per arrow; each explains why the next stage is needed.", source: "Syllabus 8.1 lesson synthesis; Coursebook 11.01-11.02.", content: <Slide number="14" eyebrow="MIXED RETRIEVAL" sourceLabel="TEXTBOOK §§11.01-11.02 · REVIEW" syllabusLabel="SYLLABUS 8.1" title="Can you reconstruct the design logic?"><section className="da-flow"><span>FILE LIMIT<br />+ CONSEQUENCE</span><i>→</i><span>ENTITY TYPE<br />+ ATTRIBUTES</span><i>→</i><span>PRIMARY +<br />FOREIGN KEY</span><i>→</i><span>REFERENTIAL<br />INTEGRITY</span></section><p className="da-note">Extension: explain why adding an index may speed retrieval but slow inserts and updates.</p></Slide> },
    { time: "4 min", focus: "Close with three concise checks and point to Lesson 37.", prompt: "Collect one sentence per card; students may not use the word 'better' without explaining how.", source: "Syllabus 8.1 checkpoint; Coursebook Chapter 11 sequence.", content: <Slide number="15" eyebrow="EXIT TICKET · NEXT: E-R + NORMALISATION" sourceLabel="TEXTBOOK CH.11 · pp.158-162" syllabusLabel="SYLLABUS 8.1" title="Three sentences prove database foundations."><section className="da-exit"><article><span>DIAGNOSE</span><p>Explain how duplicated facts can create inconsistency.</p></article><article><span>IDENTIFY</span><p>Distinguish a primary key from a foreign key.</p></article><article><span>PROTECT</span><p>State the rule enforced by referential integrity.</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="36" slides={slides} homework={<HomeworkSheet lessonNumber="36" title="From File-Based Data to Relational Databases" marks={30} minutes={45} syllabusLabel="SYLLABUS 8.1" sourceLabel="TEXTBOOK CH.11 · pp.158-162 + PAPER 1" instructions="Use precise relational terminology. For every advantage, explain the mechanism and consequence; for every key, state its role in identity or linking." sections={homeworkSections} challenge={{ id: "l36-challenge", prompt: <p><Mark>CHALLENGE</Mark> Explain why a relational database can still contain deliberate redundancy without being badly designed.</p>, answer: <p>Foreign keys repeat referenced key values so that tables can be related. This controlled repetition preserves the link and is different from duplicating descriptive facts such as a tutor phone number in many student rows.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 8.1, Coursebook Chapter 11 printed pp.158-162 (PDF pp.165-169) and published Paper 1 question/mark scheme." sourceDetail="Core: file-based limitations, relational remedies, entity/table/record/field/tuple/attribute, candidate/primary/secondary/foreign keys, referential integrity and indexing. Authentic anchor: 9618/13 M/J 2023 Q4(a)-Q4(b) [8]. E-R cardinality and normalisation follow in Lesson 37." />;
}
