"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l19-reveal-${id}`;
  return <div className="pc-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className={visible ? "pc-reveal__panel visible" : "pc-reveal__panel"} hidden={!visible}>{children}</div></div>;
}

function FetchCycle() {
  return <div className="pc-cycle" role="img" aria-label="Fetch, decode and execute cycle followed by an interrupt check"><b>FETCH</b><i>→</i><b>DECODE</b><i>→</i><b>EXECUTE</b><i>→</i><strong>INTERRUPT<br />CHECK</strong><span>↶ next cycle</span></div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Fetch, decode and execute", subtitle: "Keep addresses separate from memory contents", marks: 10,
    questions: [
      { id: "l19-1", marks: 4, lines: 4, prompt: <><b>Put these fetch transfers in order and explain each one.</b><p>CIR ← [MDR] · MDR ← [[MAR]] · MAR ← [PC] · PC ← [PC] + 1</p></>, answer: <p><b>1</b> MAR ← [PC]: copy next-instruction address. <b>2</b> MDR ← [[MAR]]: fetch contents at that address. <b>3</b> PC ← [PC]+1: prepare next sequential address; this can occur alongside step 2. <b>4</b> CIR ← [MDR]: copy fetched instruction for decoding. <em>[1 each]</em></p> },
      { id: "l19-2", marks: 6, lines: 5, prompt: <><b>Describe a complete fetch-decode-execute cycle after the instruction reaches CIR.</b></>, answer: <p>The CU decodes the opcode and identifies any operand/address; it sends control signals; required data may be fetched into a register; the ALU or another component performs the operation; a result may be stored in ACC/memory and flags updated; the next cycle begins using PC unless a jump/interrupt changes it. <em>[Any six developed points]</em></p> },
    ],
  },
  {
    code: "B", title: "Register transfer notation", subtitle: "Square brackets mean contents", marks: 10,
    questions: [
      { id: "l19-3", marks: 4, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Write the fetch stage using register transfer notation.</b><p>Adapted from 9618/13 M/J 2025 Q2(a)(ii). [4]</p></>, answer: <p><strong>MAR ← [PC]</strong>; <strong>PC ← [PC] + 1</strong>; <strong>MDR ← [[MAR]]</strong>; <strong>CIR ← [MDR]</strong>, with the transfers in a valid fetch order. <em>[4]</em></p> },
      { id: "l19-4", marks: 6, lines: 5, prompt: <><b>Interpret each item in MDR ← [[MAR]].</b><p>Explain MDR, MAR, [MAR], [[MAR]], and the arrow; then state whether the transfer is a read or write.</p></>, answer: <p>MDR is the destination register; MAR holds an address; [MAR] means the contents of MAR—the address; [[MAR]] means the contents of the memory location at that address; ← means the value on the right is copied to the left; this is a <b>memory read</b>. <em>[1 each]</em></p> },
    ],
  },
  {
    code: "C", title: "Interrupt handling", subtitle: "Detection, priority, state, ISR and return", marks: 10,
    questions: [
      { id: "l19-5", marks: 4, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Explain how an input-device interrupt is detected and handled.</b><p>Adapted from 9618/12 M/J 2025 Q1(c). [4]</p></>, answer: <p>At the start/end of an F-E cycle, pending interrupts and their priority are checked. For a sufficiently high-priority interrupt, register contents are saved on the stack and the relevant ISR is called. After it finishes, further higher-priority interrupts are checked; otherwise state is restored and the next F-E cycle continues. <em>[Any four]</em></p> },
      { id: "l19-6", marks: 2, lines: 3, prompt: <><b>Give two different causes of interrupts.</b></>, answer: <p>For example: input ready, I/O request, timer signal, user interaction, hardware fault, runtime error or out-of-bounds access. <em>[Any two]</em></p> },
      { id: "l19-7", marks: 4, lines: 4, prompt: <><b>Explain why processor state is saved before an ISR and restored afterwards.</b></>, answer: <p>The interrupted program has partially completed work; registers contain its current values/next address. Saving prevents the ISR overwriting that context. Restoring returns those values and PC, allowing execution to resume correctly rather than restart or continue from the wrong place. <em>[4 linked points]</em></p> },
    ],
  },
];

export default function Lesson19Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "3 min", focus: "Frame execution as a repeating cycle that can be safely paused between instructions.", prompt: "Ask what the CPU needs before it can obey an instruction.", source: "Syllabus 4.1 p.19; Coursebook 5.06-5.08, printed pp.87-90 / PDF pp.94-97.", content: <Slide number="01" eyebrow="CHAPTER 4 · PROCESSOR FUNDAMENTALS" sourceLabel="TEXTBOOK CH.5 · pp.87-90" syllabusLabel="SYLLABUS 4.1 · p.19" className="slide--pc-title"><section className="pc-title-grid"><div><span>LESSON 19 · 90 MINUTES</span><h1>Fetch. Decode. Execute.<br /><em>Pause safely.</em></h1><p>Track each register transfer, then follow an interrupt into an ISR and back again.</p></div><FetchCycle /></section></Slide> },
    { time: "4 min", focus: "Show the exact assessment route, including register transfer notation.", prompt: "Students identify which outcome is procedural and which is explanatory.", source: "Syllabus 4.1 p.19.", content: <Slide number="02" eyebrow="TODAY'S SYLLABUS ROUTE" sourceLabel="OFFICIAL SYLLABUS · p.19" syllabusLabel="SYLLABUS 4.1" title="Cycle → notation → interrupt." className="slide--pc-route"><section className="pc-route-grid"><article><b>1</b><span>F-E CYCLE</span><p>stages in order</p></article><article><b>2</b><span>RTN</span><p>register transfers</p></article><article><b>3</b><span>INTERRUPTS</span><p>detect · handle · return</p></article></section><p className="pc-note">The exam may ask for prose, notation or both.</p></Slide> },
    { time: "6 min", focus: "Establish the whole cycle before zooming into individual transfers.", prompt: "Which stage interprets the opcode? Which stage changes data?", source: "Coursebook 5.06, printed p.87 / PDF p.94.", content: <Slide number="03" eyebrow="THE COMPLETE LOOP" sourceLabel="TEXTBOOK 5.06 · p.87" syllabusLabel="SYLLABUS 4.1" title="One instruction completes before the next cycle begins." className="slide--pc-cycle"><FetchCycle /><section className="pc-cycle-meaning"><p><b>FETCH</b>bring instruction from memory</p><p><b>DECODE</b>work out operation + operand</p><p><b>EXECUTE</b>carry out the operation</p></section></Slide> },
    { time: "6 min", focus: "Teach the grammar of RTN before students copy equations.", prompt: "Read A ← [B] as a complete English sentence.", source: "Coursebook 5.07, printed p.88 / PDF p.95.", content: <Slide number="04" eyebrow="REGISTER TRANSFER NOTATION" sourceLabel="TEXTBOOK 5.07 · p.88" syllabusLabel="SYLLABUS 4.1" title="The arrow means copy; brackets mean contents." className="slide--pc-rtn"><section className="pc-rtn-key"><article><b>MAR</b><span>register name</span></article><article><b>[PC]</b><span>contents of PC</span></article><article><b>[[MAR]]</b><span>contents of memory at the address in MAR</span></article><article><b>←</b><span>copy right to left</span></article></section></Slide> },
    { time: "7 min", focus: "Model the first fetch transfer and distinguish PC purpose from MAR purpose.", prompt: "Why copy the address instead of sending the entire instruction from PC?", source: "Coursebook 5.06-5.07, printed pp.87-88 / PDF pp.94-95.", content: <Slide number="05" eyebrow="FETCH · STEP 1" sourceLabel="TEXTBOOK pp.87-88" syllabusLabel="SYLLABUS 4.1" title="Copy the next-instruction address into MAR." className="slide--pc-transfer"><section className="pc-transfer"><div><b>PC</b><span>240</span></div><i>MAR ← [PC]</i><div><b>MAR</b><span>240</span></div></section><p className="pc-note">PC controls the program sequence. MAR identifies the memory location currently being accessed.</p></Slide> },
    { time: "7 min", focus: "Show memory read and PC increment as independent transfers that can share a clock cycle.", prompt: "What does each destination contain after these two transfers?", source: "Coursebook 5.06-5.07, printed pp.87-88 / PDF pp.94-95.", content: <Slide number="06" eyebrow="FETCH · STEPS 2 AND 3" sourceLabel="TEXTBOOK pp.87-88" syllabusLabel="SYLLABUS 4.1" title="Read memory while preparing the next address." className="slide--pc-parallel"><section className="pc-parallel-flow"><article><strong>MDR ← [[MAR]]</strong><p>MDR receives the instruction at memory[240]</p></article><article><strong>PC ← [PC] + 1</strong><p>PC becomes 241</p></article></section><p className="pc-takeaway">These transfers can occur in the same clock cycle because they use different destinations.</p></Slide> },
    { time: "6 min", focus: "Complete fetch and state what decode and execute contribute.", prompt: "What remains unchanged when MDR is copied to CIR?", source: "Coursebook 5.06-5.07, printed p.88 / PDF p.95.", content: <Slide number="07" eyebrow="FETCH · FINAL TRANSFER" sourceLabel="TEXTBOOK 5.07 · p.88" syllabusLabel="SYLLABUS 4.1" title="CIR receives the instruction; CU can now decode it." className="slide--pc-decode"><section className="pc-code-card"><b>CIR ← [MDR]</b><span>LDD 512</span></section><section className="pc-decode-flow"><p><b>OPCODE</b>LDD → load direct</p><p><b>OPERAND</b>512 → memory address</p><p><b>EXECUTE</b>ACC receives memory[512]</p></section></Slide> },
    { time: "7 min", focus: "Apply all transfers to one concrete memory snapshot.", prompt: "Students fill each blank before revealing the chain.", source: "Derived worked example from Coursebook 5.06-5.07.", content: <Slide number="08" eyebrow="WORKED FETCH" sourceLabel="TEXTBOOK pp.87-88" syllabusLabel="SYLLABUS 4.1" title="PC starts at 240; memory[240] is ADD 510." className="slide--pc-worked"><section className="pc-worked-fetch"><p>MAR = <b>?</b></p><p>MDR = <b>?</b></p><p>PC = <b>?</b></p><p>CIR = <b>?</b></p></section><Reveal id="worked" visible={revealed.has("worked")} onToggle={toggleReveal}><p><b>MAR=240</b>; <b>MDR=ADD 510</b>; <b>PC=241</b>; <b>CIR=ADD 510</b>. Decode identifies ADD and address 510; execution adds memory[510] to ACC.</p></Reveal></Slide> },
    { time: "6 min", focus: "Define interrupts by purpose: timely attention without constant polling or abandoning current work.", prompt: "Why should a printer not control the CPU's whole schedule?", source: "Coursebook 5.08, printed pp.88-89 / PDF pp.95-96; Syllabus 4.1 p.19.", content: <Slide number="09" eyebrow="WHY INTERRUPTS?" sourceLabel="TEXTBOOK 5.08 · pp.88-89" syllabusLabel="SYLLABUS 4.1" title="An interrupt requests CPU attention after the current instruction." className="slide--pc-interrupt"><section className="pc-interrupt-scene"><div><b>PROGRAM</b><span>running normally</span></div><i>⚑</i><div><b>DEVICE / EVENT</b><span>requests attention</span></div></section><p className="pc-takeaway">The current instruction finishes; the processor can then transfer control safely.</p></Slide> },
    { time: "6 min", focus: "Cover the syllabus range of causes and applications without treating every interrupt as an error.", prompt: "Sort each example into hardware, software, I/O, timer or user event.", source: "Coursebook 5.08, printed p.88 / PDF p.95.", content: <Slide number="10" eyebrow="CAUSES AND APPLICATIONS" sourceLabel="TEXTBOOK 5.08 · p.88" syllabusLabel="SYLLABUS 4.1" title="Interrupts can signal readiness, time, requests or faults." className="slide--pc-causes"><section className="pc-cause-grid"><p><b>INPUT READY</b>key pressed</p><p><b>I/O REQUEST</b>printer completed</p><p><b>TIMER</b>time slice ended</p><p><b>USER</b>interaction/event</p><p><b>HARDWARE</b>device fault</p><p><b>SOFTWARE</b>runtime error</p></section></Slide> },
    { time: "6 min", focus: "Locate interrupt detection at a safe cycle boundary and introduce priority.", prompt: "What happens to a low-priority request while a higher-priority process runs?", source: "Syllabus 4.1 p.19; Coursebook 5.08 pp.88-89; 9618/12 M/J 2025 Q1(c) mark scheme.", content: <Slide number="11" eyebrow="WHEN IS IT DETECTED?" sourceLabel="TEXTBOOK 5.08 · pp.88-89" syllabusLabel="SYLLABUS 4.1" title="Check pending interrupts at a fetch-execute boundary." className="slide--pc-priority"><section className="pc-priority-flow"><b>FINISH INSTRUCTION</b><i>→</i><b>CHECK PENDING</b><i>→</i><b>COMPARE PRIORITY</b><i>→</i><strong>HANDLE OR CONTINUE</strong></section><p className="pc-note">Exam wording accepts a check at the start/end of the cycle; do not claim the CPU abandons a half-executed instruction.</p></Slide> },
    { time: "8 min", focus: "Teach the full ISR sequence as a reversible context switch.", prompt: "Students identify the two steps that make returning to the original program possible.", source: "Coursebook 5.08, printed pp.88-89 / PDF pp.95-96; Syllabus 4.1 p.19.", content: <Slide number="12" eyebrow="INTERRUPT HANDLING ROUTINE" sourceLabel="TEXTBOOK 5.08 · pp.88-89" syllabusLabel="SYLLABUS 4.1" title="Save → service → restore → resume." className="slide--pc-isr"><section className="pc-isr-flow"><article><b>1</b><p>save PC and registers on stack</p></article><article><b>2</b><p>load/call the relevant ISR</p></article><article><b>3</b><p>service event; check higher priorities</p></article><article><b>4</b><p>restore state and resume</p></article></section><p className="pc-takeaway">ISR = Interrupt Service Routine: a program written to handle a particular interrupt.</p></Slide> },
    { time: "8 min", focus: "Use a recent four-mark interrupt question under timed conditions.", prompt: "Four minutes silent; then map each answer clause to one mark point.", source: "Adapted from 9618/12 M/J 2025 Q1(c), checked against published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/12 M/J 2025 · Q1(c)" syllabusLabel="SYLLABUS 4.1 — EXAM PRACTICE" title="Explain how an input interrupt is detected and handled." className="slide--pc-paper"><p className="pc-big-question">Write a linked sequence containing <b>detection, priority, saved state, ISR and return.</b></p><Reveal id="paper-interrupt" visible={revealed.has("paper-interrupt")} onToggle={toggleReveal}><p>At a cycle boundary, pending interrupts and priority are checked. If accepted, register contents are saved on the stack and the relevant ISR is called. Afterwards, higher-priority requests are checked; if none, the saved state is restored and the next F-E cycle continues. <em>[Any four]</em></p></Reveal><small>Adapted from 9618/12 M/J 2025 Q1(c).</small></Slide> },
    { time: "6 min", focus: "Pair an exact recent RTN task with one diagnostic notation item.", prompt: "Students write notation first, then annotate every bracket.", source: "Adapted from 9618/13 M/J 2025 Q2(a)(ii), checked against published mark scheme.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/13 M/J 2025 · Q2(a)(ii)" syllabusLabel="SYLLABUS 4.1 — EXAM PRACTICE" title="Write the complete fetch sequence in RTN." className="slide--pc-paper"><section className="pc-rtn-blanks"><p>MAR ← ______</p><p>MDR ← ______</p><p>PC ← ______</p><p>CIR ← ______</p></section><Reveal id="paper-rtn" visible={revealed.has("paper-rtn")} onToggle={toggleReveal}><p><strong>MAR ← [PC]</strong>; <strong>MDR ← [[MAR]]</strong>; <strong>PC ← [PC]+1</strong>; <strong>CIR ← [MDR]</strong>. Memory read and PC increment may be shown in either valid concurrent order.</p></Reveal><small>Adapted from 9618/13 M/J 2025 Q2(a)(ii).</small></Slide> },
    { time: "4 min", focus: "Close by joining normal instruction flow to safe interrupt handling.", prompt: "Students complete: the cycle is safe to pause only after…", source: "Lesson 19 synthesis; Syllabus 4.1 p.19.", content: <Slide number="15" eyebrow="EXIT · ONE COMPLETE LOOP" sourceLabel="LESSON 19 SYNTHESIS" syllabusLabel="SYLLABUS 4.1" title="Finish the instruction. Check. Save. Service. Return." className="slide--pc-exit"><FetchCycle /><div className="pc-homework-callout"><b>HOMEWORK 19</b><span>30 marks · 45 minutes · inline mark schemes</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="19" slides={slides} homework={<HomeworkSheet lessonNumber="19" title="Fetch-Execute Cycle, RTN and Interrupts" marks={30} minutes={45} syllabusLabel="SYLLABUS 4.1 · p.19" sourceLabel="TEXTBOOK CH.5 · PRINTED pp.87-90 / PDF pp.94-97 + PAPER 1" instructions="Use square brackets consistently in register transfer notation. For an interrupt answer, write a sequence from cycle-boundary detection through saved state and ISR to restoration and resumption. Past-paper prompts are concise adaptations with original references." sections={homeworkSections} challenge={{ id: "l19-challenge", prompt: <p><Mark>CHALLENGE</Mark> Explain why MDR ← [[MAR]] and PC ← [PC] + 1 can occur together without either transfer using the wrong address.</p>, answer: <p>MAR already contains the address of the instruction being fetched. The memory read uses MAR, while the increment changes PC to prepare the next sequential address. They use different source/destination registers.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 4.1 p.19, Coursebook Chapter 5 printed pp.87-90 (PDF pp.94-97), and published 2025 Paper 1 questions and mark schemes." sourceDetail="Core: fetch-decode-execute stages, Cambridge register transfer notation, interrupt causes/applications, cycle-boundary detection, priority, saved state, ISR and return. Authentic anchors: 9618/13 M/J 2025 Q2(a)(ii) and 9618/12 M/J 2025 Q1(c). Fetch instruction and fetch operand are kept distinct; interrupts are not presented as errors only." />;
}
