"use client";

import { useState, type ReactNode } from "react";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

function Reveal({ id, visible, onToggle, children }: { id: string; visible: boolean; onToggle: (id: string) => void; children: ReactNode }) {
  const panelId = `l21-reveal-${id}`;
  return <div className="asm-reveal"><button type="button" onClick={() => onToggle(id)} aria-expanded={visible} aria-controls={panelId}>{visible ? "Hide answer" : "Reveal answer"}</button><div id={panelId} className="asm-reveal__panel" hidden={!visible}>{children}</div></div>;
}

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Know the five modes", subtitle: "Separate the operand from the effective address", marks: 10,
    questions: [
      { id: "l21-1", marks: 5, lines: 5, prompt: <><b>State how the operand is used in each addressing mode.</b><p>Immediate · direct · indirect · indexed · relative</p></>, answer: <p><b>Immediate:</b> operand is the data. <b>Direct:</b> operand is the address of the data. <b>Indirect:</b> operand addresses a location that stores the address of the data. <b>Indexed:</b> effective address = operand + IX. <b>Relative:</b> effective address = base address + signed offset/distance. <em>[1 each]</em></p> },
      { id: "l21-2", marks: 5, lines: 5, prompt: <><b>Calculate each result.</b><p>IX=4; M[20]=7, M[21]=40, M[24]=99, M[40]=13. Give the ACC after LDM #20, LDD 20, LDI 21 and LDX 20. Then give the target address for base 200 with relative offset +6.</p></>, answer: <p><b>LDM #20 → 20; LDD 20 → 7; LDI 21 → M[M[21]]=M[40]=13; LDX 20 → M[20+4]=M[24]=99; relative target → 200+6=206.</b> <em>[1 each]</em></p> },
    ],
  },
  {
    code: "B", title: "Effective-address calculations", subtitle: "Use current register and memory contents", marks: 10,
    questions: [
      { id: "l21-3", marks: 4, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>IX=2 and M[98]=8, M[99]=16, M[100]=3, M[101]=98, M[102]=32.</b><p>(i) State what relative addressing means. [1] (ii) Give the ACC after each independent instruction: LDM #98; LDI 101; LDX 100. [3]</p><p>Adapted from 9618/12 O/N 2025 Q3(a)(i),(b).</p></>, answer: <p><b>(i)</b> The operand is an offset added to a base address. <b>(ii)</b> <span className="asm-code">98</span>, <span className="asm-code">8</span>, <span className="asm-code">32</span>. For LDI, M[101]=98 then M[98]=8; for LDX, 100+IX=102 then M[102]=32. <em>[1+3]</em></p> },
      { id: "l21-4", marks: 6, lines: 5, prompt: <><b>For direct, indirect and indexed addressing, state:</b><p>(a) how the effective address is formed, and (b) the value loaded when operand=30, IX=3, M[30]=50, M[33]=9 and M[50]=12.</p></>, answer: <p><b>Direct:</b> EA=30, load M[30]=50. <b>Indirect:</b> EA=M[30]=50, load M[50]=12. <b>Indexed:</b> EA=30+3=33, load M[33]=9. <em>[1 address formation + 1 loaded value for each]</em></p> },
    ],
  },
  {
    code: "C", title: "Authentic Paper 1 practice", subtitle: "Definitions, a changed opcode and exam precision", marks: 10,
    questions: [
      { id: "l21-5", marks: 3, lines: 4, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Complete three addressing-mode descriptions.</b><p>The operand holds the address of the data; the operand holds an address that stores the address of the data; the operand is the data. Adapted from 9618/12 M/J 2023 Q3(b). [3]</p></>, answer: <p><b>Direct; indirect; immediate</b>, in that order. <em>[1 each]</em></p> },
      { id: "l21-6", marks: 3, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>A program begins LDD 10, then ADD 12 and compares with M[14]. M[10]=12, M[12]=10 and M[14]=22.</b><p>(i) Explain the effect of changing LDD 10 to LDM #10. [1] (ii) Identify and describe one addressing mode not used by the supplied instruction table. [2]</p><p>Adapted from 9618/12 M/J 2025 Q7(a)(ii)-(iii).</p></>, answer: <p><b>(i)</b> ACC starts with 10 rather than M[10]=12; ADD 12 gives 20 rather than 22, so the comparison fails and the loop does not terminate. <b>(ii)</b> One valid pair: indirect—operand points to a location containing the data address; indexed—operand+IX forms the data address; or relative—offset/distance is added to a base address. <em>[1+2]</em></p> },
      { id: "l21-7", marks: 4, lines: 4, prompt: <><b>Correct both statements and give one matching instruction.</b><p>“Immediate addressing follows one pointer.” “Direct addressing adds IX to the operand.”</p></>, answer: <p>Immediate addressing uses the <strong>operand itself as data</strong>, for example <span className="asm-code">LDM #7</span>. Direct addressing uses the <strong>operand as the data address</strong>, for example <span className="asm-code">LDD 40</span>. Following a pointer is indirect; adding IX is indexed. <em>[2 corrections; 2 examples]</em></p> },
    ],
  },
];

export default function Lesson21Client() {
  const [revealed, setRevealed] = useState<Set<string>>(() => new Set());
  const toggleReveal = (id: string) => setRevealed((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });

  const slides: SlideData[] = [
    { time: "3 min", focus: "Frame addressing as the route from an operand to data.", prompt: "Ask: is 40 a value, an address or part of a calculation?", source: "Syllabus 4.2 p.20; Coursebook Chapter 6 printed pp.94 and 98.", content: <Slide number="01" eyebrow="CHAPTER 4 · ASSEMBLY LANGUAGE" sourceLabel="TEXTBOOK CH.6 · pp.94, 98" syllabusLabel="SYLLABUS 4.2 · p.20" className="slide--asm-title"><section className="asm-title-grid"><div className="asm-title-copy"><span>LESSON 21 · 90 MINUTES</span><h1>Find the<br /><em>real address.</em></h1><p>Read an operand, identify its addressing mode and calculate exactly where the data comes from.</p></div><div className="asm-chip-stack"><p><b>#40</b><span>the value 40</span></p><p><b>40</b><span>memory address 40</span></p><p><b>40 + IX</b><span>a calculated address</span></p></div></section></Slide> },
    { time: "4 min", focus: "Make all five syllabus modes visible before teaching details.", prompt: "Students sort the five modes into data, one address, two addresses and calculations.", source: "Syllabus 4.2 p.20; Coursebook Table 6.06 p.98.", content: <Slide number="02" eyebrow="TODAY'S ROUTE" sourceLabel="TEXTBOOK TABLE 6.06 · p.98" syllabusLabel="SYLLABUS 4.2" title="Five modes; one question: how is the effective address found?"><section className="asm-route"><article><b>VALUE</b><p>immediate</p></article><article><b>ONE LOOKUP</b><p>direct</p></article><article><b>TWO LOOKUPS</b><p>indirect</p></article><article><b>CALCULATE</b><p>indexed · relative</p></article></section></Slide> },
    { time: "6 min", focus: "Define operand and effective address separately.", prompt: "Students label each part of LDX 40.", source: "Coursebook 6.03 and Table 6.06.", content: <Slide number="03" eyebrow="THE CORE DISTINCTION" sourceLabel="TEXTBOOK 6.03 / 6.06" syllabusLabel="SYLLABUS 4.2 — ADDRESSING" title="The operand is written in the instruction; the effective address is where data are accessed."><section className="asm-equation"><b>operand</b><i>+</i><b>mode rule</b><i>→</i><strong>effective address</strong></section><p className="asm-note">Immediate addressing is the exception: the operand is already the data, so no data address is formed.</p></Slide> },
    { time: "6 min", focus: "Teach immediate addressing and its syntax marker.", prompt: "Call three operands; students distinguish value from address.", source: "Coursebook Table 6.06 p.98; syllabus example instruction set p.21.", content: <Slide number="04" eyebrow="IMMEDIATE" sourceLabel="TEXTBOOK p.98" syllabusLabel="SYLLABUS 4.2 — IMMEDIATE" title="Use the operand itself as the data."><section className="asm-memory-chain"><article><span>INSTRUCTION</span><b>LDM #37</b></article><i>→</i><article><span>OPERAND IS DATA</span><b>37</b></article><i>→</i><article><span>ACC</span><b>37</b></article></section><p className="asm-note"><b>#</b> denotes a denary literal in the syllabus instruction set. It is not a memory lookup.</p></Slide> },
    { time: "6 min", focus: "Teach direct addressing as one lookup.", prompt: "Ask what changes if M[40] changes but the instruction does not.", source: "Coursebook Table 6.06 p.98.", content: <Slide number="05" eyebrow="DIRECT" sourceLabel="TEXTBOOK p.98" syllabusLabel="SYLLABUS 4.2 — DIRECT" title="The operand is the address of the data."><section className="asm-memory-chain"><article><span>INSTRUCTION</span><b>LDD 40</b></article><i>→</i><article><span>M[40]</span><b>73</b></article><i>→</i><article><span>ACC</span><b>73</b></article></section><p className="asm-note">Effective address = <b>40</b>. Loaded value = <b>M[40]</b>.</p></Slide> },
    { time: "7 min", focus: "Teach indirect addressing as a pointer followed by a second lookup.", prompt: "Students trace each arrow aloud without skipping the pointer.", source: "Coursebook Table 6.06 p.98.", content: <Slide number="06" eyebrow="INDIRECT" sourceLabel="TEXTBOOK p.98" syllabusLabel="SYLLABUS 4.2 — INDIRECT" title="The first location stores the address of the data."><section className="asm-memory-chain"><article><span>LDI 40</span><b>operand 40</b></article><i>→</i><article><span>M[40]</span><b>73</b></article><i>→</i><article><span>M[73]</span><b>12 → ACC</b></article></section><p className="asm-warning">Do not load 73. It is the pointer—the effective address—not the final data.</p></Slide> },
    { time: "7 min", focus: "Calculate indexed addresses using the current IX value.", prompt: "Change IX and predict which array-like element is selected.", source: "Coursebook Table 6.06 p.98; syllabus LDX/LDR p.21.", content: <Slide number="07" eyebrow="INDEXED" sourceLabel="TEXTBOOK p.98" syllabusLabel="SYLLABUS 4.2 — INDEXED" title="Add the contents of IX to the operand."><section className="asm-equation"><b>operand 40</b><i>+</i><b>IX = 3</b><i>→</i><strong>EA = 43</strong></section><section className="asm-state-strip"><article><span>INSTRUCTION</span><b>LDX 40</b></article><article><span>M[43]</span><b>91</b></article><article><span>ACC</span><b>91</b></article><article><span>IX</span><b>3</b></article></section></Slide> },
    { time: "7 min", focus: "Explain relative addressing as a signed displacement from a base.", prompt: "Calculate targets using positive and negative offsets.", source: "Coursebook 6.03 p.94; syllabus 4.2 p.20.", content: <Slide number="08" eyebrow="RELATIVE" sourceLabel="TEXTBOOK 6.03 · p.94" syllabusLabel="SYLLABUS 4.2 — RELATIVE" title="Add an offset or distance to a base address."><section className="asm-equation"><b>base 206</b><i>+</i><b>offset −8</b><i>→</i><strong>target 198</strong></section><p className="asm-note">The offset may be positive or negative. State both the base and the displacement when explaining the mode.</p></Slide> },
    { time: "6 min", focus: "Consolidate all modes in one comparison table.", prompt: "Hide the last two columns and derive them from the instruction.", source: "Coursebook Table 6.06 p.98.", content: <Slide number="09" eyebrow="FIVE-MODE COMPARISON" sourceLabel="TEXTBOOK TABLE 6.06" syllabusLabel="SYLLABUS 4.2" title="Name the route before touching memory."><div className="asm-table-wrap"><table><thead><tr><th>Mode</th><th>Example</th><th>Effective address / data</th><th>Lookups</th></tr></thead><tbody><tr><td>Immediate</td><td>LDM #20</td><td>data = 20</td><td>0</td></tr><tr><td>Direct</td><td>LDD 20</td><td>EA = 20</td><td>1</td></tr><tr><td>Indirect</td><td>LDI 20</td><td>EA = M[20]</td><td>2</td></tr><tr><td>Indexed</td><td>LDX 20</td><td>EA = 20 + IX</td><td>1 after add</td></tr><tr><td>Relative</td><td>offset −4</td><td>EA = base − 4</td><td>target calculation</td></tr></tbody></table></div></Slide> },
    { time: "8 min", focus: "Model a current 2025 effective-address question.", prompt: "Five minutes independent, then reveal and annotate each lookup.", source: "Adapted from 9618/12 O/N 2025 Q3(a)(i),(b), checked against the published mark scheme.", content: <Slide number="10" eyebrow="PAST PAPER PRACTICE · 4 MARKS" sourceLabel="9618/12 O/N 2025 · Q3(a)(i),(b)" syllabusLabel="SYLLABUS 4.2 — EXAM" className="asm-paper" title="IX=2. Calculate three independent loads."><section className="asm-paper-grid three"><article><b>LDM #98</b><p>ACC = ?</p></article><article><b>LDI 101</b><p>M[101]=98; M[98]=8</p></article><article><b>LDX 100</b><p>M[102]=32</p></article></section><Reveal id="on25" visible={revealed.has("on25")} onToggle={toggleReveal}><p>Relative means an offset added to a base. Results: <strong>98, 8, 32</strong>.</p></Reveal><small>Adapted from 9618/12 O/N 2025 Q3(a)(i),(b).</small></Slide> },
    { time: "6 min", focus: "Use a verified fill-in question to lock exact definitions.", prompt: "Students answer without examples, then mark terminology.", source: "Adapted from 9618/12 M/J 2023 Q3(b).", content: <Slide number="11" eyebrow="PAST PAPER PRACTICE · 3 MARKS" sourceLabel="9618/12 M/J 2023 · Q3(b)" syllabusLabel="SYLLABUS 4.2 — EXAM" className="asm-paper" title="Name each mode from its operand description."><section className="asm-paper-grid three"><p>operand holds the memory address of the data</p><p>operand holds an address that stores the data address</p><p>operand is the data</p></section><Reveal id="mj23" visible={revealed.has("mj23")} onToggle={toggleReveal}><p><strong>Direct · indirect · immediate.</strong></p></Reveal><small>Adapted from 9618/12 M/J 2023 Q3(b).</small></Slide> },
    { time: "6 min", focus: "Give a repeatable algorithm for any effective-address question.", prompt: "Students use the four steps on LDI 101.", source: "Derived from Coursebook 6.03/6.06 and Paper 1 mark schemes.", content: <Slide number="12" eyebrow="SAFE CALCULATION METHOD" sourceLabel="TEXTBOOK + MARK SCHEMES" syllabusLabel="SYLLABUS 4.2" title="Mode → formula → address → value."><section className="asm-route"><article><b>1 · NAME</b><p>identify the mode</p></article><article><b>2 · FORM</b><p>write EA rule</p></article><article><b>3 · RESOLVE</b><p>calculate/follow address</p></article><article><b>4 · LOAD</b><p>read final data</p></article></section></Slide> },
    { time: "5 min", focus: "Repair the three common addressing errors.", prompt: "Students correct each claim in one sentence.", source: "Recurring Paper 1 distractors.", content: <Slide number="13" eyebrow="MISCONCEPTION CLINIC" sourceLabel="EXAMINER LANGUAGE" syllabusLabel="SYLLABUS 4.2" title="Three routes that students collapse into one."><section className="asm-card-grid"><article className="asm-card"><span>ERROR 1</span><h3>#40 is address 40</h3><p>No: # marks immediate data.</p></article><article className="asm-card"><span>ERROR 2</span><h3>LDI loads the pointer</h3><p>No: follow it to the data.</p></article><article className="asm-card"><span>ERROR 3</span><h3>LDX changes IX</h3><p>No: IX helps form the address.</p></article></section></Slide> },
    { time: "8 min", focus: "Apply mode semantics to a changed instruction and explain the program effect.", prompt: "Attempt for five minutes; award one effect mark and two addressing marks.", source: "Adapted from 9618/12 M/J 2025 Q7(a)(ii)-(iii).", content: <Slide number="14" eyebrow="EXAM SPRINT · 3 MARKS" sourceLabel="9618/12 M/J 2025 · Q7(a)(ii-iii)" syllabusLabel="SYLLABUS 4.2 — EXAM" className="asm-paper" title="What changes when LDD 10 becomes LDM #10?"><section className="asm-paper-grid"><article><b>Program data</b><p>M[10]=12, M[12]=10, comparison value=22.</p></article><article><b>Then identify</b><p>one unused addressing mode and describe it.</p></article></section><Reveal id="change" visible={revealed.has("change")} onToggle={toggleReveal}><p>ACC starts 10, not 12; addition gives 20, comparison fails and the loop does not terminate. One valid unused mode: indirect, indexed or relative, with its matching route. <em>[1+2]</em></p></Reveal><small>Adapted from 9618/12 M/J 2025 Q7(a)(ii)-(iii).</small></Slide> },
    { time: "5 min", focus: "Close with one route explained in words and notation.", prompt: "Each student chooses the mode they found hardest.", source: "Syllabus 4.2 exit check.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK CH.6 · REVIEW" syllabusLabel="SYLLABUS 4.2" className="slide--asm-exit" title="Name it. Form the address. Load the value."><section className="asm-exit-grid"><article><b>NAME</b><p>Which mode is shown?</p></article><article><b>CALCULATE</b><p>What is the effective address?</p></article><article><b>RESOLVE</b><p>What reaches ACC?</p></article></section><div className="asm-homework-callout"><b>HOMEWORK 21</b><span>30 marks · three verified Paper 1 anchors · inline answers</span><strong>HOMEWORK TAB ↑</strong></div></Slide> },
  ];

  return <LessonShell lessonNumber="21" slides={slides} homework={<HomeworkSheet lessonNumber="21" title="Addressing Modes & Effective Addresses" marks={30} minutes={45} syllabusLabel="SYLLABUS 4.2 · p.20" sourceLabel="TEXTBOOK CH.6 · pp.94, 98 + PAPER 1" instructions="For every calculation, name the mode, show how the effective address is formed, then state the final value. Past-paper wording is concisely adapted and cited beside each task." sections={homeworkSections} challenge={{ id: "l21-challenge", prompt: <p><Mark>CHALLENGE</Mark> Explain why indexed addressing is useful when accessing consecutive elements of an array.</p>, answer: <p>The operand can hold the fixed base address while IX holds a changing displacement. Incrementing IX selects successive locations without changing the instruction itself.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 4.2 p.20, Coursebook Chapter 6 printed pp.94 and 98, and published 2023/2025 Paper 1 questions and mark schemes." sourceDetail="Core: immediate, direct, indirect, indexed and relative addressing; operand versus effective address; applying current IX and memory contents. Authentic anchors: 9618/12 O/N 2025 Q3(a)(i),(b), 9618/12 M/J 2023 Q3(b), and 9618/12 M/J 2025 Q7(a)(ii)-(iii). Every past-paper prompt is marked Adapted." />;
}
