"use client";

import { ExamReveal } from "../_components/exam-reveal";
import { HomeworkSheet, LessonShell, Mark, Slide, type HomeworkSection, type SlideData } from "../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Ownership and permission", subtitle: "Copyright protects work; licences state allowed use", marks: 10,
    questions: [
      { id: "l34-1", marks: 4, lines: 4, prompt: <><b>Distinguish copyright from a software licence.</b></>, answer: <p><strong>Copyright</strong> gives legal protection/control over an original work as intellectual property. A <strong>software licence</strong> is a legal agreement from the rights holder defining what a user may do, such as install, copy, modify or redistribute, plus restrictions/conditions. Ownership protection and granted permission are different. <em>[2 + 2]</em></p> },
      { id: "l34-2", marks: 3, lines: 3, prompt: <><b>Explain why copyright legislation is needed for software.</b></>, answer: <p>It identifies/protects the creator or rights holder, controls unauthorised copying/distribution/adaptation and provides legal remedies. This supports recognition and potential income/investment while allowing permission to be granted by licence. <em>[any 3 linked points]</em></p> },
      { id: "l34-3", marks: 3, lines: 3, prompt: <><b>A school buys one copy of a program and installs it on 200 computers.</b><p>Explain why payment alone may not make this lawful.</p></>, answer: <p>Buying a copy does not automatically transfer copyright or unlimited installation rights. The licence states the number of devices/users and other conditions. The school needs a site/multi-user licence or further permission; otherwise the copying/installations may breach the agreement/copyright. <em>[3]</em></p> },
    ],
  },
  {
    code: "B", title: "Four syllabus models", subtitle: "Freedom, source access, trial and proprietary permission", marks: 10,
    questions: [
      { id: "l34-4", marks: 2, lines: 2, prompt: <><b>Describe the Free Software Foundation view of “free software”.</b></>, answer: <p>“Free” concerns user freedoms—such as to run, study, modify and share under the licence—not necessarily zero price. Source access is needed to study/modify, and software may still be sold. <em>[2]</em></p> },
      { id: "l34-5", marks: 2, lines: 2, prompt: <><b>Describe software distributed under an OSI-approved open-source licence.</b></>, answer: <p>Source code is available and the licence permits use, inspection/modification and redistribution subject to its stated conditions. It remains copyrighted/licensed and may be used commercially. <em>[2]</em></p> },
      { id: "l34-6", marks: 2, lines: 2, prompt: <><b>Describe shareware.</b></>, answer: <p>Software is distributed for trial, often for a limited time or with restricted features, after which payment/registration is required for continued or full use. Source code need not be provided. <em>[2]</em></p> },
      { id: "l34-7", marks: 2, lines: 2, prompt: <><b>Describe a commercial/proprietary software licence.</b></>, answer: <p>A paid or commercially supplied licence grants specified use while the publisher normally keeps source code and intellectual-property control; copying, modification and redistribution are restricted by terms. <em>[2]</em></p> },
      { id: "l34-8", marks: 2, lines: 2, prompt: <><b>Explain why “commercial” and “open source” are not opposites.</b></>, answer: <p>Open-source software can be sold and used to generate revenue; “open source” describes licence permissions/source availability, while “commercial” describes a business context or paid product/service. <em>[2]</em></p> },
    ],
  },
  {
    code: "C", title: "Paper 1 licence decisions", subtitle: "Define precisely, then justify from requirements", marks: 10,
    questions: [
      { id: "l34-9", marks: 6, lines: 5, prompt: <><Mark>PAST PAPER PRACTICE</Mark> <b>Define copyright, OSI/open-source software, shareware and a software licence; state one purpose of a professional code of conduct.</b><p>Adapted from 9618/12 O/N 2025 Q2(a)–(b). [4 + 2]</p></>, answer: <p><strong>Copyright:</strong> legal ownership/protection of intellectual property. <strong>OSI/open source:</strong> licensed so source can be inspected and software copied/distributed/modified under conditions. <strong>Shareware:</strong> trial/limited version before payment or registration. <strong>Licence:</strong> legal agreement defining usage rights/terms. <strong>Code:</strong> sets professional behaviour/expectations and consequences, supporting safe practice/reputation/trust. <em>[6]</em></p> },
      { id: "l34-10", marks: 4, lines: 4, prompt: <><b>A small medical company needs to inspect and adapt source code, redistribute its changes and obtain specialist support.</b><p>Recommend a licensing route and justify two requirements it must check.</p></>, answer: <p>An appropriate <strong>open-source/free-software licence</strong> can permit inspection, modification and redistribution. The company must check the exact licence conditions for derivative/redistributed code and whether suitable paid support/security maintenance is available. Medical risk also requires testing and accountability; source access alone is not a safety guarantee. <em>[recommendation + 3 linked points]</em></p> },
    ],
  },
];

export default function Lesson34Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Frame copyright and licensing as ownership versus granted permission.", prompt: "Ask: if source code is visible, does that make it public domain?", source: "Syllabus 7.1 copyright and licensing; Coursebook 10.04–10.05 printed pp.150–153.", content: <Slide number="01" eyebrow="CHAPTER 7 · OWNERSHIP" sourceLabel="TEXTBOOK §§10.04–10.05 · pp.150–153" syllabusLabel="SYLLABUS 7.1" className="se-title"><section className="se-title-grid"><div className="se-title-copy"><span>LESSON 34 · 90 MINUTES</span><h1>Own the work.<br /><em>Grant the rights.</em></h1><p>Separate copyright from licence, then choose among FSF/free-software, OSI/open-source, shareware and commercial models from a real user&apos;s needs.</p></div><div className="se-title-visual"><div><b>1</b><span>WHO HOLDS THE RIGHTS?</span></div><div><b>2</b><span>WHAT DOES THE LICENCE ALLOW?</span></div><div><b>3</b><span>WHAT CONDITIONS APPLY?</span></div><div><b>4</b><span>WHY DOES THIS USER NEED IT?</span></div></div></section></Slide> },
    { time: "5 min", focus: "Expose the difference between buying access and acquiring ownership rights.", prompt: "Students identify which claim depends on the actual licence text.", source: "Coursebook 10.04–10.05 printed pp.150–153; syllabus 7.1.", content: <Slide number="02" eyebrow="DO NOW · WE PAID—CAN WE COPY?" sourceLabel="TEXTBOOK §§10.04–10.05" syllabusLabel="SYLLABUS 7.1" title="A school buys one download and installs it in every classroom."><section className="se-grid three"><article className="se-card"><span>PURCHASE</span><h3>Access to a copy</h3><p>Payment alone does not necessarily transfer copyright.</p></article><article className="se-card"><span>LICENCE</span><h3>Permission + conditions</h3><p>Device/user count, term, copying and distribution depend on agreement.</p></article><article className="se-card"><span>COPYRIGHT</span><h3>Underlying legal control</h3><p>Rights holder controls protected uses unless law/licence allows them.</p></article></section></Slide> },
    { time: "6 min", focus: "Establish a durable distinction that works across all licence models.", prompt: "Complete: copyright answers __; a licence answers __.", source: "Coursebook 10.04–10.05; syllabus 7.1 need for copyright and licensing.", content: <Slide number="03" eyebrow="COPYRIGHT ≠ LICENCE" sourceLabel="TEXTBOOK §§10.04–10.05" syllabusLabel="SYLLABUS 7.1" title="Protection of rights versus permission to use them."><section className="se-compare"><div><b>CONCEPT</b><b>CORE QUESTION</b><b>EFFECT</b></div><div><b>Copyright</b><span>Who controls this original intellectual work?</span><span>legal protection and remedies against unauthorised acts</span></div><div><b>Software licence</b><span>What may this user do—and under which conditions?</span><span>permission to install/use/copy/modify/redistribute as stated</span></div></section><p className="se-warning">Open source is still protected by copyright and a licence; it is not automatically public domain.</p></Slide> },
    { time: "6 min", focus: "Explain the policy reasons for copyright without claiming all rights are absolute.", prompt: "Which purpose benefits users or society as well as creators?", source: "Coursebook 10.04 printed pp.150–151; syllabus 7.1 need for copyright legislation.", content: <Slide number="04" eyebrow="WHY COPYRIGHT LEGISLATION?" sourceLabel="TEXTBOOK §10.04 · pp.150–151" syllabusLabel="SYLLABUS 7.1" title="Recognition, control, remedy and sustainable creation."><section className="se-grid four"><article className="se-card"><span>IDENTIFY</span><p>recognise creator/rights holder</p></article><article className="se-card"><span>CONTROL</span><p>authorise copying, distribution and adaptation</p></article><article className="se-card"><span>REMEDY</span><p>act against unauthorised exploitation</p></article><article className="se-card"><span>INCENTIVE</span><p>support investment, income and continued work</p></article></section><p className="se-note">Exact exceptions, duration and employee ownership vary by law and contract. Apply the syllabus concepts—not invented universal rules.</p></Slide> },
    { time: "6 min", focus: "Show that common software acts require explicit permission or a legal exception.", prompt: "Which action can be allowed for one product and forbidden for another?", source: "Coursebook 10.04–10.05; syllabus 7.1 software licensing.", content: <Slide number="05" eyebrow="RIGHTS A LICENCE CAN SHAPE" sourceLabel="TEXTBOOK §§10.04–10.05" syllabusLabel="SYLLABUS 7.1" title="Do not infer permission from price or availability."><section className="se-grid five"><article className="se-card"><span>RUN</span><p>who and how many devices/users?</p></article><article className="se-card"><span>COPY</span><p>backup or extra installations?</p></article><article className="se-card"><span>STUDY</span><p>is source code available?</p></article><article className="se-card"><span>MODIFY</span><p>may derivative versions be made?</p></article><article className="se-card"><span>REDISTRIBUTE</span><p>may originals/changes be shared?</p></article></section></Slide> },
    { time: "6 min", focus: "Define software licence as a legal agreement, not a technical lock.", prompt: "What could a licence allow even if the installer has no copy-protection mechanism?", source: "Coursebook 10.05 printed pp.151–153; syllabus 7.1 licence types.", content: <Slide number="06" eyebrow="SOFTWARE LICENCE" sourceLabel="TEXTBOOK §10.05 · pp.151–153" syllabusLabel="SYLLABUS 7.1" title="Read the grant, restrictions, obligations and support terms."><section className="se-flow"><span>RIGHTS<br />HOLDER</span><i>→</i><span>GRANTS<br />PERMISSIONS</span><i>→</i><span>USER ACCEPTS<br />CONDITIONS</span><i>→</i><span>USE / COPY /<br />MODIFY / SHARE</span></section><p className="se-note">Licence violations are legal/contract issues even when copying or modification is technically easy.</p></Slide> },
    { time: "6 min", focus: "Correct the common misconception that FSF 'free' means zero price.", prompt: "Which freedom requires source code access? Which does not imply no charge?", source: "Coursebook 10.05 printed pp.151–152, corrected for FSF meaning; syllabus 7.1 FSF.", content: <Slide number="07" eyebrow="FREE SOFTWARE FOUNDATION · FSF" sourceLabel="TEXTBOOK §10.05 · pp.151–152" syllabusLabel="SYLLABUS 7.1 · FSF" title="Free as in freedom—not necessarily price."><section className="se-grid four"><article className="se-card"><span>RUN</span><p>use the program for a chosen purpose</p></article><article className="se-card"><span>STUDY</span><p>inspect how it works; source access matters</p></article><article className="se-card"><span>MODIFY</span><p>adapt it to meet needs</p></article><article className="se-card"><span>SHARE</span><p>redistribute under licence conditions</p></article></section><p className="se-warning">Free software may be sold, and not every free-software licence uses identical copyleft conditions.</p></Slide> },
    { time: "6 min", focus: "Describe OSI as defining/approving open-source licences, not providing all software.", prompt: "Why must a team inspect the exact approved licence rather than stop at 'open source'?", source: "Coursebook 10.05 printed p.152, corrected for OSI role; syllabus 7.1 OSI.", content: <Slide number="08" eyebrow="OPEN SOURCE INITIATIVE · OSI" sourceLabel="TEXTBOOK §10.05 · p.152" syllabusLabel="SYLLABUS 7.1 · OSI" title="Source available; use, modification and redistribution licensed under stated conditions."><section className="se-grid three"><article className="se-card"><span>DEFINITION</span><h3>Criteria</h3><p>OSI maintains the Open Source Definition and approves conforming licences.</p></article><article className="se-card"><span>PERMISSION</span><h3>Inspect + adapt + share</h3><p>Rights exist because a licence grants them, with conditions.</p></article><article className="se-card"><span>BUSINESS</span><h3>Can be commercial</h3><p>Revenue may come from distribution, hosting, support or services.</p></article></section></Slide> },
    { time: "6 min", focus: "Define shareware through trial/limited access and later payment.", prompt: "Why is beta software not automatically shareware?", source: "Coursebook 10.05 printed p.152; syllabus 7.1 shareware.", content: <Slide number="09" eyebrow="SHAREWARE" sourceLabel="TEXTBOOK §10.05 · p.152" syllabusLabel="SYLLABUS 7.1" title="Try first; pay or register for continued/full use."><section className="se-flow"><span>DOWNLOAD<br />TRIAL</span><i>→</i><span>TIME / FEATURES<br />LIMITED</span><i>→</i><span>EVALUATE<br />PRODUCT</span><i>→</i><span>PAY / REGISTER<br />TO CONTINUE</span></section><p className="se-warning">Shareware does not imply source code access. A beta describes a testing stage; it is not automatically a licensing model.</p></Slide> },
    { time: "6 min", focus: "Describe commercial/proprietary licensing and avoid equating 'commercial' only with closed source.", prompt: "Which requirements make paid vendor support valuable?", source: "Coursebook 10.05 printed pp.152–153; syllabus 7.1 commercial software.", content: <Slide number="10" eyebrow="COMMERCIAL / PROPRIETARY SOFTWARE" sourceLabel="TEXTBOOK §10.05 · pp.152–153" syllabusLabel="SYLLABUS 7.1" title="Specified use, retained control and often paid support."><section className="se-grid four"><article className="se-card"><span>FEE</span><p>purchase, subscription or service charge</p></article><article className="se-card"><span>TERMS</span><p>users/devices, duration and permitted purpose</p></article><article className="se-card"><span>RESTRICTIONS</span><p>source, copying, modification or redistribution</p></article><article className="se-card"><span>SUPPORT</span><p>vendor updates, documentation and accountability</p></article></section><p className="se-note">Some open-source software is commercial. In exam answers, justify from the <strong>actual licence needs</strong>.</p></Slide> },
    { time: "5 min", focus: "Compare all four required models without false binaries.", prompt: "Which column describes a trial model rather than a source-code permission model?", source: "Syllabus 7.1 required licence models; Coursebook 10.05.", content: <Slide number="11" eyebrow="COMPARE THE MODELS" sourceLabel="TEXTBOOK §10.05 · pp.151–153" syllabusLabel="SYLLABUS 7.1" title="Ask about rights and conditions—not labels alone."><section className="se-compare four"><div><b>MODEL</b><b>SOURCE / CHANGE</b><b>DISTRIBUTION</b><b>PRICE / SUPPORT</b></div><div><b>FSF/free software</b><span>freedoms to study/modify</span><span>allowed under licence terms</span><span>may charge; community/paid support</span></div><div><b>OSI/open source</b><span>source available; modification permitted</span><span>allowed under approved licence conditions</span><span>may be commercial</span></div><div><b>Shareware</b><span>usually no source right</span><span>trial distribution permitted as stated</span><span>pay/register after limit</span></div><div><b>Commercial/proprietary</b><span>often closed/restricted</span><span>normally tightly limited</span><span>fee plus vendor support may apply</span></div></section></Slide> },
    { time: "7 min", focus: "Teach licence justification as requirements matching rather than slogan selection.", prompt: "Rank criteria for a safety-critical school product and defend the top two.", source: "Coursebook 10.05 application; syllabus 7.1 justify software licence.", content: <Slide number="12" eyebrow="CHOOSE FROM REQUIREMENTS" sourceLabel="TEXTBOOK §10.05 · APPLICATION" syllabusLabel="SYLLABUS 7.1" title="Requirement → licence permission → condition → consequence."><section className="se-decision-ladder"><span>1 · COST +<br />DURATION</span><i>→</i><span>2 · SOURCE +<br />MODIFICATION</span><i>→</i><span>3 · COPY +<br />REDISTRIBUTE</span><i>→</i><span>4 · SUPPORT +<br />UPDATES</span><i>→</i><span>5 · RISK +<br />COMPLIANCE</span></section><p className="se-note">Strong justification: “Choose X <strong>because</strong> its permission Y meets requirement Z; check condition C.”</p></Slide> },
    { time: "8 min", focus: "Practise current Paper 1 definitions across ownership, licensing and professional conduct.", prompt: "Write six independent mark points; do not define open source as 'free of charge'.", source: "Adapted from 9618/12 O/N 2025 Q2(a)–(b), checked against the published mark scheme.", content: <Slide number="13" eyebrow="PAST PAPER PRACTICE · 6 MARKS" sourceLabel="9618/12 O/N 2025 · Q2(a)–(b)" syllabusLabel="SYLLABUS 7.1 — EXAM PRACTICE" title="Define four terms; state why a code of conduct matters." className="slide--se-paper"><section className="se-paper-grid three"><article><span>OWNERSHIP</span><p>copyright</p></article><article><span>LICENSING</span><p>OSI/open source · shareware · software licence</p></article><article><span>PROFESSION</span><p>one purpose of a code of conduct</p></article></section><ExamReveal><p>Copyright is legal protection/ownership of intellectual property. OSI/open source permits source inspection and copying/distribution/modification under licence. Shareware is trial/limited before payment. A licence is a legal agreement defining usage rights/terms. A code sets expected safe professional behaviour and consequences, protecting trust/reputation.</p></ExamReveal><small className="se-source-line">Concise adaptation of 9618/12 O/N 2025 Q2(a)–(b); original allocation [4 + 2].</small></Slide> },
    { time: "8 min", focus: "Apply licensing to a business that needs modification and continued revenue.", prompt: "Pairs write a recommendation plus one condition and one risk.", source: "Adapted from 9618/12 O/N 2024 Q5(b), checked against the published mark scheme.", content: <Slide number="14" eyebrow="PAST PAPER SCENARIO · 5 MARKS" sourceLabel="9618/12 O/N 2024 · Q5(b)" syllabusLabel="SYLLABUS 7.1 — EXAM PRACTICE" title="A business needs adaptable source code and a way to earn income." className="slide--se-paper"><section className="se-paper-grid"><article><span>LICENCE CHOICE</span><p>Explain how FSF/OSI permissions support inspection and modification.</p></article><article><span>OWNERSHIP + INCOME</span><p>Explain how copyright and licensed services/updates support the programmer.</p></article></section><ExamReveal><p>Use an appropriate free/open-source licence to permit inspection and modification under its conditions. Copyright still establishes ownership and legal recourse; income can come from selling distribution, support, hosted services or updates. The exact redistribution obligations must be checked.</p></ExamReveal><small className="se-source-line">Concise adaptation of 9618/12 O/N 2024 Q5(b); original allocation [5].</small></Slide> },
    { time: "5 min", focus: "Close on three misconceptions with exact counterclaims.", prompt: "Students replace each false statement with one accurate sentence.", source: "Syllabus 7.1 lesson synthesis; Coursebook 10.04–10.05 corrected.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK §§10.04–10.05 · REVIEW" syllabusLabel="SYLLABUS 7.1" title="Correct the claim."><section className="se-exit"><article><span>1 · “OPEN = PUBLIC DOMAIN”</span><p>Correct it using copyright + licence.</p></article><article><span>2 · “FREE = ZERO PRICE”</span><p>Correct it using freedom + source.</p></article><article><span>3 · “COMMERCIAL = CLOSED”</span><p>Correct it using business + permissions.</p></article></section></Slide> },
  ];

  return <LessonShell lessonNumber="34" slides={slides} homework={<HomeworkSheet lessonNumber="34" title="Copyright and Software Licensing" marks={30} minutes={45} syllabusLabel="SYLLABUS 7.1" sourceLabel="TEXTBOOK CH.10 · pp.150–153 + PAPER 1" instructions="Separate ownership from permission. Define each model through its actual rights and conditions, then justify a licence by matching source access, modification, redistribution, cost, support and risk requirements." sections={homeworkSections} challenge={{ id: "l34-challenge", prompt: <p><Mark>CHALLENGE</Mark> Explain how the same program could be open source, commercial and protected by copyright at the same time.</p>, answer: <p>The creator owns copyright and uses an open-source licence to grant source inspection, modification and redistribution under stated conditions. The program or related services can still be sold—for example paid distribution, hosting, support or custom development. Copyright supplies the legal basis for enforcing the licence; open source describes permissions, and commercial describes business activity.</p> }} />} courseMapHref="../?view=roadmap" sourceSummary="Checked against syllabus 7.1, Coursebook Chapter 10 printed pp.150–153, and the published 2024–2025 Paper 1 copyright and licensing questions and mark schemes." sourceDetail="Core: purpose of copyright legislation; distinction between copyright and licence; Free Software Foundation/free software, Open Source Initiative/open source, shareware and commercial software; justified licence selection. Authentic anchors: 9618/12 O/N 2025 Q2(a)–(b) [6] and 9618/12 O/N 2024 Q5(b) [5]. Jurisdiction-specific exceptions and contract law are outside this lesson." />;
}
