"use client";

import { A2TheoryLesson, CompareTable, ConceptCards, ExamPractice, FlowStrip, WorkedBoard } from "../../_components/a2-theory-lesson";
import { ScheduleBar } from "../../_components/a2-advanced-diagrams";
import { Slide, type HomeworkSection, type SlideData } from "../../_components/lesson-shell";

const homeworkSections: HomeworkSection[] = [
  {
    code: "A", title: "Scheduling foundations", subtitle: "Choose, dispatch and account for overhead", marks: 10,
    questions: [
      { id: "a2-18-1", marks: 3, lines: 5, prompt: <><b>Explain why process scheduling is needed.</b></>, answer: <p>More processes may be ready than can execute simultaneously <em>[1]</em>. Scheduling allocates limited CPU time <em>[1]</em> to improve utilisation/throughput, responsiveness or fairness <em>[1]</em>.</p> },
      { id: "a2-18-2", marks: 3, lines: 5, prompt: <><b>Distinguish the scheduler from the dispatcher.</b></>, answer: <p>The scheduler selects which ready process should run next <em>[1]</em>. The dispatcher performs the context switch/restores that process context <em>[1]</em> and gives it control of the CPU <em>[1]</em>.</p> },
      { id: "a2-18-3", marks: 4, lines: 7, prompt: <><b>Distinguish pre-emptive and non-pre-emptive scheduling</b> and give one named example of each.</>, answer: <p>Pre-emptive scheduling can interrupt a running process before its CPU burst finishes <em>[1]</em>; round robin or SRT is an example <em>[1]</em>. Non-pre-emptive scheduling normally keeps the process running until it finishes or blocks <em>[1]</em>; FCFS or SJF is an example <em>[1]</em>.</p> },
    ],
  },
  {
    code: "B", title: "Four routines", subtitle: "Use the selection rule, benefit and limitation", marks: 10,
    questions: [
      { id: "a2-18-4", marks: 3, lines: 6, prompt: <><b>Describe first come first served</b> and give one benefit and one limitation.</>, answer: <p>Processes run in arrival/ready-queue order <em>[1]</em>. It is simple and has low scheduling overhead <em>[1]</em>, but a long job can delay all shorter jobs behind it/produce poor response time <em>[1]</em>.</p> },
      { id: "a2-18-5", marks: 3, lines: 6, prompt: <><b>Describe shortest job first</b> and give one benefit and one limitation.</>, answer: <p>The ready process with the shortest estimated total burst/job is chosen <em>[1]</em>. It can reduce average waiting time/increase throughput <em>[1]</em>, but burst time must be estimated or long jobs may starve <em>[1]</em>.</p> },
      { id: "a2-18-6", marks: 4, lines: 7, prompt: <><b>Compare round robin with shortest remaining time.</b></>, answer: <p>Round robin gives each ready process a fixed time quantum in cyclic order <em>[1]</em> and pre-empts at quantum expiry <em>[1]</em>. SRT selects the process with the least remaining execution time <em>[1]</em> and can pre-empt when a shorter job arrives <em>[1]</em>.</p> },
    ],
  },
  {
    code: "C", title: "Kernel and exam clinic", subtitle: "Link interrupt handling to low-level scheduling", marks: 10,
    questions: [
      { id: "a2-18-7", marks: 3, lines: 6, prompt: <><b>Explain one effect of making a round-robin time quantum too short</b> and one effect of making it too long.</>, answer: <p>Too short causes frequent context switches and excessive overhead <em>[1]</em>. Too long reduces overhead <em>[1]</em> but gives poorer interactive response and approaches FCFS behaviour <em>[1]</em>.</p> },
      { id: "a2-18-8", marks: 3, lines: 6, prompt: <><b>State three actions performed when the kernel handles an interrupt.</b></>, answer: <p>Any three: identify/check priority of the interrupt <em>[1]</em>; save the current process context <em>[1]</em>; locate and run the ISR <em>[1]</em>; update process state/invoke scheduler; restore or switch context.</p> },
      { id: "a2-18-9", marks: 4, lines: 7, prompt: <><span className="syllabus-mark">PAST PAPER PRACTICE</span><p><b>For FCFS, SJF and round robin, give the selection rule and one benefit.</b></p><p>Adapted from 9618/32 O/N 2022 Q9. [4 adapted marks]</p></>, answer: <p>FCFS uses arrival order and is simple/low overhead <em>[1]</em>. SJF selects the smallest estimated job and can reduce average waiting time/increase throughput <em>[1]</em>. Round robin gives a fixed time slice cyclically <em>[1]</em>, improving fairness/response and preventing one process monopolising the CPU <em>[1]</em>.</p> },
    ],
  },
];

export default function A2Lesson18Client() {
  const slides: SlideData[] = [
    { time: "4 min", focus: "Make scheduling a decision problem, not a vocabulary list.", prompt: "If five processes are ready, who should receive the next millisecond?", source: "2027–2029 syllabus 16.1; coursebook Chapter 20 printed pp.370–372 plus syllabus-specified SJF/SRT.", content: <Slide number="01" eyebrow="A2 · PAPER 3" sourceLabel="TEXTBOOK Ch20" syllabusLabel="SYLLABUS 16.1" className="a2-slide a2-title a2-at-slide"><section className="a2-title-grid"><div><span>LESSON 18 · 90 MINUTES</span><h1>Who runs<br /><em>next?</em></h1><p>FCFS · SJF · round robin · SRT · kernel interrupt handling</p></div><div className="a2-at-hero" role="img" aria-label="Scheduler selects one ready process"><strong>SCHEDULER</strong><span>ARRIVAL</span><span>BURST</span><span>QUANTUM</span><span>PRE-EMPT</span></div></section></Slide> },
    { time: "5 min", focus: "Map all named scheduling routines and the interrupt requirement.", prompt: "Which two routines are pre-emptive?", source: "Official 2027–2029 syllabus p.35.", content: <Slide number="02" eyebrow="TODAY'S EXAM MAP" sourceLabel="SYLLABUS p.35" syllabusLabel="16.1 · REQUIRED" title="Each routine has a selection rule, benefit and trade-off." className="a2-slide a2-at-slide"><ConceptCards columns={4} items={[{ eyebrow: "ORDER", title: "FCFS", body: "Earliest arrival first." }, { eyebrow: "DURATION", title: "SJF", body: "Shortest estimated whole job." }, { eyebrow: "TIME SLICE", title: "Round robin", body: "Cyclic turns of fixed length." }, { eyebrow: "REMAINING", title: "SRT", body: "Least work left; may pre-empt." }]} /></Slide> },
    { time: "5 min", focus: "Separate the selection decision from its execution.", prompt: "Which component chooses, and which actually switches?", source: "Coursebook §20.03 pp.370–372.", content: <Slide number="03" eyebrow="READY QUEUE" sourceLabel="TEXTBOOK pp.370–372" syllabusLabel="16.1 · NEED FOR SCHEDULING" title="The scheduler chooses; the dispatcher performs the context switch." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "READY QUEUE", title: "Eligible processes" }, { eyebrow: "SCHEDULER", title: "Applies a routine" }, { eyebrow: "DISPATCHER", title: "Saves/restores context" }, { eyebrow: "CPU", title: "Runs selected process" }]} /></Slide> },
    { time: "6 min", focus: "Classify routines by whether they can remove the CPU.", prompt: "Does an interrupt always mean the running process is replaced?", source: "Coursebook pp.370–372; syllabus scheduling guidance.", content: <Slide number="04" eyebrow="PRE-EMPTION" sourceLabel="TEXTBOOK pp.370–372" syllabusLabel="16.1 · SCHEDULING" title="Pre-emptive routines can stop a process that is still runnable." className="a2-slide a2-at-slide"><CompareTable headers={["Non-pre-emptive", "Pre-emptive"]} rows={[["runs until completion or blocking", "may remove CPU before burst completes"], ["FCFS; usually SJF", "round robin; SRT"], ["fewer context switches", "better interactive response"], ["long jobs may delay others", "extra switching overhead"]]} /></Slide> },
    { time: "6 min", focus: "Apply first come first served to a timeline.", prompt: "What happens to C even though it needs only one unit?", source: "Coursebook §20.03 pp.370–372; 9618/32 O/N 2022 Q9.", content: <Slide number="05" eyebrow="FIRST COME FIRST SERVED" sourceLabel="9618/32 O/N 2022 · Q9" syllabusLabel="16.1 · FCFS" title="FCFS preserves arrival order and ignores job length." className="a2-slide a2-at-slide"><ScheduleBar title="FCFS · A(4), B(3), C(1), all ready at t=0" segments={[{ process: "A", start: 0, end: 4 }, { process: "B", start: 4, end: 7 }, { process: "C", start: 7, end: 8 }]} /></Slide> },
    { time: "6 min", focus: "Apply shortest job first and expose its assumptions.", prompt: "What information must the OS estimate before SJF can choose?", source: "Required by syllabus 16.1; coursebook gives general scheduling context.", content: <Slide number="06" eyebrow="SHORTEST JOB FIRST" sourceLabel="SYLLABUS p.35" syllabusLabel="16.1 · SJF" title="SJF minimises short-job waiting—but duration is only an estimate." className="a2-slide a2-at-slide"><ScheduleBar title="SJF · A(4), B(3), C(1), all ready at t=0" segments={[{ process: "C", start: 0, end: 1 }, { process: "B", start: 1, end: 4 }, { process: "A", start: 4, end: 8 }]} /></Slide> },
    { time: "6 min", focus: "Trace a cyclic ready queue with a fixed quantum.", prompt: "After A uses two units, where does it go?", source: "Coursebook §20.03 pp.371–372; 9618/32 O/N 2022 Q9.", content: <Slide number="07" eyebrow="ROUND ROBIN" sourceLabel="TEXTBOOK pp.371–372" syllabusLabel="16.1 · RR" title="Every ready process gets a turn; unfinished work returns to the queue." className="a2-slide a2-at-slide"><ScheduleBar title="Round robin · quantum 2 · A(4), B(3), C(1)" segments={[{ process: "A", start: 0, end: 2 }, { process: "B", start: 2, end: 4 }, { process: "C", start: 4, end: 5 }, { process: "A", start: 5, end: 7 }, { process: "B", start: 7, end: 8 }]} /></Slide> },
    { time: "6 min", focus: "Explain the quantum trade-off.", prompt: "At what point does round robin begin to resemble FCFS?", source: "Coursebook pp.371–372.", content: <Slide number="08" eyebrow="CHOOSE THE QUANTUM" sourceLabel="TEXTBOOK pp.371–372" syllabusLabel="16.1 · RR BENEFITS" title="Responsiveness and context-switch overhead pull in opposite directions." className="a2-slide a2-at-slide"><CompareTable headers={["Quantum", "Effect"]} rows={[["very short", "fast apparent response; many context switches and high overhead"], ["balanced", "fair turns with acceptable overhead"], ["very long", "low switching overhead; poor response; behaves increasingly like FCFS"]]} /></Slide> },
    { time: "6 min", focus: "Distinguish shortest remaining time from SJF.", prompt: "What new arrival can pre-empt the running process?", source: "Required by 2027–2029 syllabus 16.1.", content: <Slide number="09" eyebrow="SHORTEST REMAINING TIME" sourceLabel="SYLLABUS p.35" syllabusLabel="16.1 · SRT" title="SRT re-evaluates the least remaining work whenever the ready set changes." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "RUNNING", title: "A has 5 units left" }, { eyebrow: "ARRIVAL", title: "B needs 2 units" }, { eyebrow: "COMPARE", title: "2 < 5" }, { eyebrow: "PRE-EMPT", title: "B runs; A returns ready" }]} /></Slide> },
    { time: "6 min", focus: "Compare the four routines on exam dimensions.", prompt: "Which routine risks starvation, and which prevents monopolisation?", source: "Syllabus 16.1; coursebook pp.370–372; verified Paper 3 mark schemes.", content: <Slide number="10" eyebrow="FOUR-ROUTINE MATRIX" sourceLabel="SYLLABUS p.35" syllabusLabel="16.1 · FUNCTION + BENEFIT" title="Selection rule determines fairness, response and overhead." className="a2-slide a2-at-slide"><CompareTable headers={["Routine", "Select by", "Pre-emptive?", "Main strength", "Main risk"]} rows={[["FCFS", "arrival", "no", "simple; low overhead", "convoy effect"], ["SJF", "whole estimated burst", "usually no", "low average wait", "long-job starvation"], ["RR", "cyclic quantum", "yes", "fair; responsive", "switch overhead"], ["SRT", "remaining burst", "yes", "short jobs finish fast", "long-job starvation"]]} /></Slide> },
    { time: "7 min", focus: "Put the kernel at the centre of interrupt handling.", prompt: "Why must execution context be saved before the ISR runs?", source: "Coursebook §20.03; 9618/32 O/N 2024 Q9(a).", content: <Slide number="11" eyebrow="KERNEL AS INTERRUPT HANDLER" sourceLabel="9618/32 O/N 2024 · Q9(a)" syllabusLabel="16.1 · KERNEL" title="An interrupt transfers controlled execution into the kernel." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "SIGNAL", title: "Interrupt arrives" }, { eyebrow: "KERNEL", title: "Checks source / priority" }, { eyebrow: "CONTEXT", title: "Saves process state" }, { eyebrow: "ISR", title: "Runs service routine" }]} /></Slide> },
    { time: "7 min", focus: "Link interrupt completion to low-level scheduling.", prompt: "When can the original process fail to resume immediately?", source: "Official syllabus p.35; 9618/32 O/N 2024 Q9(a) MS.", content: <Slide number="12" eyebrow="INTERRUPT → SCHEDULING" sourceLabel="SYLLABUS p.35" syllabusLabel="16.1 · LOW-LEVEL SCHEDULING" title="Handling an interrupt may change which processes are ready." className="a2-slide a2-at-slide"><FlowStrip steps={[{ eyebrow: "ISR", title: "Handles event", body: "For example, I/O completes." }, { eyebrow: "STATE", title: "Updates process", body: "Blocked process may become ready." }, { eyebrow: "SCHEDULER", title: "Reconsiders ready queue" }, { eyebrow: "DISPATCH", title: "Restores chosen context" }]} /></Slide> },
    { time: "7 min", focus: "Calculate a schedule without losing arrival information.", prompt: "Students annotate arrival, remaining burst and every switch.", source: "Syllabus-defined scheduling practice.", content: <Slide number="13" eyebrow="WORKED DECISION" sourceLabel="SYLLABUS 16.1" syllabusLabel="16.1 · SRT TRACE" title="For SRT, compare remaining—not original—burst time." className="a2-slide a2-at-slide"><WorkedBoard label="A arrives t=0, burst 6 · B arrives t=2, burst 2"><p><code>t0–2 A</code>: A has 4 left. At t=2, B has 2, so B pre-empts A. <code>t2–4 B</code>: B completes. <code>t4–8 A</code>: A completes.</p></WorkedBoard></Slide> },
    { time: "8 min", focus: "Write compact benefits for three routines from an authentic prompt.", prompt: "Every named routine needs both its rule and why it helps.", source: "Adapted from Cambridge 9618/32 O/N 2022 Q9.", content: <Slide number="14" eyebrow="PAST PAPER PRACTICE" sourceLabel="9618/32 O/N 2022 · Q9" syllabusLabel="16.1 · 6 MARKS" title="A scheduling explanation is rule + consequence." className="a2-slide a2-paper a2-at-slide"><ExamPractice reference="9618/32 O/N 2022 · Q9 · ADAPTED" marks={6} prompt={<p>Describe FCFS, SJF and round robin. For each, state one benefit in a multi-tasking operating system. [6]</p>} answer={<ul><li>FCFS: arrival order; simple and low overhead. [2]</li><li>SJF: shortest estimated job; reduces average waiting or increases throughput. [2]</li><li>Round robin: cyclic fixed time quantum; fair/responsive and prevents CPU monopolisation. [2]</li></ul>} /></Slide> },
    { time: "5 min", focus: "Retrieve the four algorithms and the interrupt chain.", prompt: "Students give one comparison using pre-emption and one using fairness.", source: "Syllabus 16.1 synthesis; coursebook Chapter 20 pp.370–372.", content: <Slide number="15" eyebrow="EXIT TICKET" sourceLabel="TEXTBOOK Ch20 · SYLLABUS p.35" syllabusLabel="16.1 · CHECKPOINT" title="Choose by arrival, whole job, time slice or remaining work." className="a2-slide a2-exit a2-at-slide"><section className="a2-exit-grid"><article><span>FCFS</span><p>Earliest arrival.</p></article><article><span>SJF</span><p>Shortest whole estimate.</p></article><article><span>RR</span><p>Fixed cyclic quantum.</p></article><article><span>SRT</span><p>Shortest work remaining.</p></article></section><div className="homework-callout"><b>HOMEWORK 18</b><span>30 marks · scheduling routines and interrupts</span><strong>45 min</strong></div></Slide> },
  ];

  return <A2TheoryLesson lessonNumber="18" title="CPU scheduling and interrupt handling" syllabusLabel="SYLLABUS 16.1" sourceLabel="TEXTBOOK Ch20 · pp.370–372" slides={slides} homeworkSections={homeworkSections} sourceSummary="Official 2027–2029 syllabus 16.1 p.35 · endorsed coursebook Chapter 20 printed pp.370–372 · verified 2022 and 2024 Paper 3 questions and mark schemes" sourceDetail="The coursebook's FCFS and round-robin coverage is extended with the syllabus-required SJF and SRT routines. Every routine is taught through its selection rule, pre-emption behaviour, benefit and limitation." />;
}
